### ISSUE TITLE
integrate core evals for auction, vaults, and price feeds

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#10020]
change core-eval for priceFeed, vaults, auctions

later ones need to be coordinated with earlier ones using promises

## Test Plan

include a3p test

**Comment by Chris-Hibbert** [comment]
overtaken by #10074

**Comment by dckc** [comment]
Closing this as completed looks misleading.

I'm not sure what it means for an issue to be overtaken by an open PR.

I'm inclined to use this to track the stuff I handed over in #9827 .

**Comment by dckc** [comment]
fixed in #10074
