### ISSUE TITLE
swing-store: stopUsingTranscript fails to delete transcript spans

### ISSUE THREAD

**Issue by gibson042** [Agoric/Agoric#10054]
## Describe the bug
Unlike [`rolloverIncarnation` and `rolloverSpan`](https://github.com/Agoric/agoric-sdk/blob/2e66067830c76bc9f1e0ab76c54f10aec1a19f1a/packages/swing-store/src/transcriptStore.js#L296-L320), [`stopUsingTranscript`](https://github.com/Agoric/agoric-sdk/blob/2e66067830c76bc9f1e0ab76c54f10aec1a19f1a/packages/swing-store/src/transcriptStore.js#L368) does not run `sqlDeleteOldItems` even when `keepTranscripts` is false and therefore leaves entries for the previously-current span.

## Additional context
This is implicitly fixed by reloading from an export that does not include the orphaned data, but we still shouldn't leave it hanging around.

**Comment by mhofman** [comment]
I thought the design of slow deletion was to not delete the transcript spans at all, and leave that for a slow cleanup function. I suppose after we landed the change to only delete the previously current span entries, it would be fine to just immediately delete those entries, leaving only the span description for the slow deletion process.
