### ISSUE TITLE
SwingStore hostStorage `setExportCallback` is unsafe

### ISSUE THREAD

**Issue by gibson042** [Agoric/Agoric#10062]
## Describe the bug
As [documented](https://github.com/Agoric/agoric-sdk/blob/914bee2aa7472039ba230267d72027b940bf8a1c/packages/swing-store/docs/swingstore.md#hoststorage), "_`hostStorage.setExportCallback()` is used to register an export callback after swingstore creation [but] Most applications will instead provide `options.exportCallback` to `openSwingStore()`_". But looking at the implementation, [`noteExport`](https://github.com/Agoric/agoric-sdk/blob/67275c2ac643b53bb74422cc92fe1f3565150d12/packages/swing-store/src/swingStore.js#L286) performs a database write if and only if there is a defined `exportCallback` **at the time**. This means that calling `setExportCallback` too late will result in the callback seeing only a subset of exports when it is later called, which is a footgun.

## Proposed solution
We should just remove the method, since the `exportCallback` option provides equivalent functionality and doesn't suffer from the same issue (and in fact [we never even use `setExportCallback`](https://github.com/search?q=org%3AAgoric%20setExportCallback&type=code), even in testing).

**Comment by mhofman** [comment]
Possibly related: https://github.com/Agoric/agoric-sdk/issues/9655
