### ISSUE TITLE
import @agoric/orchestration fails to find types.js

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#10086]
## To Reproduce
1. put the code below in `packages/builders/scripts/orch-imp.js`
2. run `node scripts/orch-imp.js`
3. Error

```js
import * as orch from '@agoric/orchestration';

console.log(orch);
```

```console
$ cd agoric-sdk/packages/builders
$ node scripts/orch-imp.js 
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/connolly/projects/agoric-sdk/packages/orchestration/src/types.js' imported from /home/connolly/projects/agoric-sdk/packages/orchestration/index.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:327:11)
    at moduleResolve (node:internal/modules/esm/resolve:980:10)
    at defaultResolve (node:internal/modules/esm/resolve:1193:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
    at link (node:internal/modules/esm/module_job:75:36) {
  url: 'file:///home/connolly/projects/agoric-sdk/packages/orchestration/src/types.js',
  code: 'ERR_MODULE_NOT_FOUND'
}


```

## Expected behavior

No error.

## Platform Environment
 - what OS are you using? what version of Node.js?

Node.js v18.20.1

 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

66e4cc0f36 (actually a few commits from that version of master: b38b7f3fbc )

## Additional context

@mhofman asked about this in https://github.com/Agoric/agoric-sdk/pull/10057#discussion_r1758138375

**Comment by turadg** [comment]
Simpler repro,
```
node --input-type=module -e "import '@agoric/orchestration'"
```

Reasons not to change this:
- The fix, using `.d.ts`, skips typechecking
- Imports work fine from NPM installations (this affects only repo peer packages)
- Even barrel imports work fine from a `.ts` file
- Repo peer packages can still use deep imports
- This has not been a problem yet in the course of building orchestration and testing it in `packages/boot` and `multichain-testing`

**Comment by dckc** [comment]
> Imports work fine from NPM installations (this affects only repo peer packages)

How does that work?

I'm struggling to confirm, fwiw.

```console
$ mkdir /tmp/fun1
$ cd /tmp/fun1
$ yarn add @agoric/orchestration@dev

$ node --input-type=module -e "import '@agoric/orchestration'"
node:internal/modules/esm/resolve:265
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module ...
```

**Comment by turadg** [comment]
> How does that work?

I misremembered that it uses a `dist` folder like `@agoric/cosmic-proto` does.

It already has a `prepack` that does tsc build. Top-level imports with NPM installations _can_ work if we make it output to `dist` and set the entrypoints to that… but then we'd have to build dist as part of our monorepo workflow, which we've avoided.

So I don't have a good solution. There's a trade-off to be made.

A reasonable stop-gap is that we remove `types.js` from the index and export it at `/types.js`.

**Comment by mhofman** [comment]
I really don't think we should compromise on the public shape, which includes importing types from the entry point.

I'm wondering if there's a possible solution for this type check issue: another level of indirection. Have index.js import from `./types.js` which is defined as a manual empty .js file and a .d.ts file which simply does `export * from './src/types.js'` which is actually written as types.ts

**Comment by turadg** [comment]
Good idea. I suppose a manual `index.d.ts` would also work, but risk getting out of sync with `index.js`. I like empty types.js for indirection because it will always be empty.

**Comment by mhofman** [comment]
To clarify however, the output would be alongside the src, and not in a `dist` folder, right ?
