### ISSUE TITLE
Remove `orchestrator.makeLocalAccount` which is basically a shortcut for `orchestrator.getChain("agoric").makeAccount()`

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#10106]
## What is the Problem Being Solved?
`orchestrator.makeLocalAccount` is basically a shortcut for `orchestrator.getChain("agoric").makeAccount()`. While potentially helpful, this helper/shortcut can confuse a developer by creating multiple ways to accomplish the same task.

## Description of the Design
I intend to remove the public facet method and use compilation/testing to verify that all vestiges, callers, and related examples are gone.

## Security Considerations
None. This is removing code that doesn't uphold any interesting security property. All the same functionality is still available to contract devs - just through a slightly modified bit of code.

## Scaling Considerations
None.

## Test Plan
Red code. If all tests continue to pass we're solid.

## Upgrade Considerations
None. This isn't upgrading/changing something live on chain.

**Comment by dckc** [comment]
We seem to have API reference docs that include this method:
https://docs.agoric.com/guides/orchestration/getting-started/api.html#makelocalaccount

So please add a PR or issue or whatever to remove it there too.
Maybe just get rid of that whole page in favor of the [@agoric/orchestration package reference docs](https://agoric-sdk.pages.dev/modules/_agoric_orchestration)?

**Comment by turadg** [comment]
`makeLocalAccount` returns a `LocalChainAccount` whereas `getChain('agoric').makeAccount()` returns an `OrchestrationAccount` that  is parameterized with Agoric chain capabilities.

Also, the latter is to be used in place of the former, the jsdoc needs updating because it says "remote chain":
```js
  /**
   * Creates a new account on the remote chain.
   * @returns an object that controls a new remote account on Chain
   */
  makeAccount: () => Promise<OrchestrationAccount<CI>>;
```
