### ISSUE TITLE
Proposer can use CosGov to propose new committee via core eval (install bundle, upload files)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#10138]
## What is the Problem Being Solved?

To rotate the EC membership, someone needs to be able to submit a proposal to do so.

## Description of the Design

A [builder script](https://github.com/Agoric/agoric-sdk/tree/master/packages/builders/scripts) to go with `gov-replace-committee.js` (as revised along the lines of #10105) such that `agoric run new-builder-script.js` produces the relevant artifacts.

## Test Plan

Should be covered by `a3p-integration` tests in #10136, #10137 . But those are P2, so if we choose not to do them, let's be sure to test that here.

**Comment by aj-agoric** [comment]
Per meeting 9/24 this ticket is to create the input files to be used in the [cosgov/agoric](https://cosgov.org/agoric?msgType=coreEvalProposal) proposal builder

**Comment by dckc** [comment]
test plan should include

 - [ ] estimate the cost of installing the bundles

**Comment by dckc** [comment]
@otoole-brendan I suggest moving "can use CosGov to " out of the title to the design. It's sort of misleading - it looks like we're making a change to CosGov.

**Comment by dckc** [comment]
as noted in https://github.com/Agoric/agoric-sdk/pull/10164#issuecomment-2392456173 , there's a little work to do here

**Comment by dckc** [comment]
@otoole-brendan @frazarshad  I think this is now obsolete in favor of...

 - #10258

**Comment by dckc** [comment]
obsolete in favor of #10258
