### ISSUE TITLE
Outgoing members should not be able to propose

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#10136]
## What is the Problem Being Solved?

Outgoing members should not be able to propose

## Design

 - A revision to `econCommitteeCharter.js` to add a shutdown method.
   - **problematic**. See #10137 for options on shutdown design.
 - a core eval script based on `gov-replace-committee.js` (see #10105) that **upgrades the original EC contract** and calls the new shutdown method

## Test Plan

 - Unit test for the shutdown method (makeZoeForTest, startInstance, get the creatorFacet, call shutDown; then try to make an invitation to propose a parameter change)
 - Bootstrap test: test that when an outgoing member tries to propose, they get an error
 - `a3p-integration` test for upgrading the contract

## Upgrade Considerations

yes. See design, test plan.

**Comment by otoole-brendan** [comment]
@frazarshad @rabi-siddique could you please estimate?

**Comment by rabi-siddique** [comment]
> A revision to econCommitteeCharter.js to add a shutdown method

This has been completed today. 

Work for the core eval script and tests remain.

**Comment by frazarshad** [comment]
Currently, outgoing members have the invitation that can propose, but they cannot propose through the econ-gov-ui due to https://github.com/Agoric/dapp-econ-gov/pull/131

**Comment by otoole-brendan** [comment]
Not planned - closing
