### ISSUE TITLE
Grant proposing rights to continuing/incoming members

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#10133]
## What is the Problem Being Solved?

We need to grant rights to continuing / incoming members

## Description of the Design

a core eval script based on `gov-replace-committee.js` that:

 - Starts a new charter
 - Invites members
 - Introduces governed instances: each of the 6 kinds of governed contract (PSM, VaultFactory, Auctioneer, reserve, Provision pool, fluxAggregator aka priceFeed)
   - [x] how to enumerate price feeds?

## Test Plan

Bootstrap test. Test that

 - A proposal from a continuing member, supported by 2 continuing members, can govern (change parameters and/or invoke governed APIs) in each of the governed instances

## Security Considerations

_many and subtle_

## Scaling Considerations

not much

## Upgrade Considerations

While starting a new charter isn't an upgrade, the new instance should include the shutdown enhancement from #10136 .

**Comment by otoole-brendan** [comment]
@frazarshad @rabi-siddique could you please estimate this ticket?

**Comment by rabi-siddique** [comment]
We've completed the core eval script for this work item that starts the new charter and invites the new members. 


> A proposal from a continuing member, supported by 2 continuing members, can govern (change parameters and/or invoke governed APIs) in each instance of each of the 6 kinds of governed contract (PSM, VaultFactory, Auctioneer, reserve, Provision pool, fluxAggregator aka priceFeed

The bootstrap test remains. We've manually tested it for PSM, VaultFactory, and Auctioneer. We need to incorporate changes for the missing contracts.
