### ISSUE TITLE
Outgoing members must not be able to vote

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#10135]
```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/10134
```

**Comment by dckc** [comment]
@otoole-brendan this is largely subsumed by #10134, #10137 . We can track it separately as a user story if you like, but I wonder whether that's worthwhile.

**Comment by otoole-brendan** [comment]
@dckc If we're confident the functionality is delivered via #10134 and #10137 then it's redundant and I'm happy to close as not planned

**Comment by dckc** [comment]
I think "must not be able to vote" is delivered by "revoke voting rights" #10134 .
