### ISSUE TITLE
helper for async providing a value into a SharedStateRecord

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#10130]
## What is the Problem Being Solved?

This is subject to race conditions:
https://github.com/Agoric/agoric-sdk/blob/ad7f65598df6099b7661a7f201039d306561e5a1/packages/orchestration/src/examples/send-anywhere.flows.js#L44-L48

Multiple invocations of the same flow can concurrently find the localAccount to not be created yet, and attempt to create it.

## Description of the Design

We need some `provideOnce`

Without membranes we’ve used [makeAtomicProvider](https://github.com/Agoric/agoric-sdk/blob/78fb22ddbafbf8abfb53ef6bc776c14f52171433/packages/store/src/stores/store-utils.js#L152) which takes a store and returns a provideAsync that uses a pending promises map to only try making each key once.

**Comment by mhofman** [comment]
IMO we should completely avoid the "shared state" record pattern unless the "provider" of the value is idempotent so that it can be invoked again in new incarnations because the "shared state" is not durable. And even then, I don't see why the "provider" cannot be directly endowed instead.
