### ISSUE TITLE
The newly elected EC must be able to govern (propose + vote)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#10185]
Delivery of this functionality may be via https://github.com/Agoric/agoric-sdk/issues/10133 and https://github.com/Agoric/agoric-sdk/issues/10134. This ticket serves to explicitly validate the functionality through UI testing

Test plan:
Use Synpress to test interaction the interaction between EC member and Econ Gov UI

**Comment by rabi-siddique** [comment]
#10133 was completed in PR #10164, and #10134 was completed in PR #10166.

The Synpress end-to-end tests were done in [#135](https://github.com/Agoric/dapp-econ-gov/pull/135) and tracked in issue [#134](https://github.com/Agoric/dapp-econ-gov/issues/134).

**Comment by dckc** [comment]
Struggles with a3p testing suggests that sort of testing should be part of the test plan for this functionality.

 - https://github.com/Agoric/agoric-sdk/pull/10241

In particular, we're currently stuck on a very strange corner-case where an EC member fails to accept their invitation.

 - https://github.com/Agoric/agoric-sdk/issues/10292
 - https://github.com/endojs/endo/issues/2588
