### ISSUE TITLE
Update hardcoded EC addresses with newly elected committee members

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#10194]
The 3 members and their addresses are:

    "Chloe White": "agoric1d4228cvelf8tj65f4h7n2td90sscavln2283h5"
        "Chris Berg": "agoric13p9adwk0na5npfq64g22l6xucvqdmu3xqe70wq"
        "Joe Clark": "agoric1zayxg4e9vd0es9c9jlpt36qtth255txjp6a8yc"

See comment below for more details

**Comment by dckc** [comment]
make the gov3 -> gov4 change for this issue, please

**Comment by otoole-brendan** [comment]
The 3 proposed members are known. I'm validating their addresses before sharing them so they can be hard-coded in

**Comment by otoole-brendan** [comment]
These are the addresses of the 3 members that will continue to serve. Note they are already serving on the EC so we can reuse addresses already in code (taken from https://github.com/Agoric/agoric-sdk/blob/e1baf4e7e8efaab527d7eadf7305281dac8656c9/packages/vm-config/decentral-main-vaults-config.json#L165-L171) 

            "Chloe White": "agoric1d4228cvelf8tj65f4h7n2td90sscavln2283h5"
            "Chris Berg": "agoric13p9adwk0na5npfq64g22l6xucvqdmu3xqe70wq"
            "Joe Clark": "agoric1zayxg4e9vd0es9c9jlpt36qtth255txjp6a8yc"

For avoidance of doubt I'm validating these with these EC members to ensure accuracy and no changes

cc @frazarshad

**Comment by dckc** [comment]
I also see in the [14 Oct community forum post](https://community.agoric.com/t/ec-elections-2024/708):
> we’re pleased to announce that Chloe White, Chris Berg, and Joseph Clark have indicated their willingness to serve another term.

**Comment by otoole-brendan** [comment]
@frazarshad Dan has confirmed the source of these addresses so feeling pretty confident about them. Over to you to code these where appropriate! If the EC members say otherwise I'll flag but these are unlikely to change
