### ISSUE TITLE
Integrate CCTP

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/Agoric#10222]

**Comment by samsiegart** [comment]
For CCTP, we can mock this by minting from the faucet on the starship chain. See [noble-tools](https://github.com/Agoric/agoric-sdk/pull/10384/files#diff-e4e2dfd392184618eba42272bf67610036a6a2dfe1e56f1a42206bc29bc0299c)

Test example: [noble-forwarding-test](https://github.com/Agoric/agoric-sdk/pull/10384/files#diff-0884150adda85c31cab996fb8fe337ac9fe21b8af6a44be9a258aacea63fd3a7)
