### ISSUE TITLE
Design/plan for Fast USDC testing infrastructure

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/Agoric#10233]
User story: allow agoric engineers to be able to test their Fast USDC work with confidence

**Comment by LuqiPan** [comment]
By EOD today, a stub document where the whole team can contribute to

**Comment by samsiegart** [comment]
https://docs.google.com/document/d/15ubiqKNIk4rhmp0nAUEzA_vxUBN5xzSNTzqBTh07cig/edit?usp=sharing
