### ISSUE TITLE
Add widget to simplify future EC slate changes

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#10275]
Future implementation of new EC slates can be even further simplified with the addition of a widget that allows proposer to do a core eval and seat new EC members by specifying the new EC addresses i.e. `seatECMembers({fred: 'agoric134...', ...})`

Questions:
Widget where? In CosGov FE? In AgoricSDK repo? Contract code? cc @dckc

**Comment by otoole-brendan** [comment]
Let's estimate this and determine if we want to deliver it in next/final sprint @dckc

**Comment by dckc** [comment]
Perhaps the following IBIS clarifies. Adding a "widget" is the "add `seatECMembers` item to bootstrap space" item:

```
? how to handle future EC elections?
  : add config to builder for each election
    . for example, `main2026: { voterAddresses: { ... } } `
    . builder is [replace-electorate-core.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/builders/scripts/inter-protocol/replace-electorate-core.js)
    - Agoric ENG is in the critical path each time
  : add cosgov form, template
    - requires 1 time cosgov enhancement development, testing effort
    + self-serve for proposers such as DCF
    ? what template to use
      : based on output of `agoric run _builder_`
        . precedent template: [add-vault.js](https://github.com/DCFoundation/cosmos-proposal-builder/blob/main/src/config/inter/addVault/add-vault.js)
        - core-eval script is >150 lines of boilerplate
      : add `seatECMembers` item to bootstrap space
        + proposal would be approx. 1 line per memeber: `seatECMembers({fred: 'agoric134...', ...})`
        - Agoric ENG is in the critical path for a 1 time change
```

[codecider rendering](https://codecider-app.vercel.app/6500a2b5-ab3f-43ba-a4f9-d1353d142b53) looks like

![image](https://github.com/user-attachments/assets/6802562e-39c1-4b39-81e8-2d76ef99d963)

**Comment by otoole-brendan** [comment]
This is not a priority. Closing as 'Not planned'. We can re-open if that changes.

**Comment by dckc** [comment]
github shows

> closed this as completed

I'm more inclined to believe...

> Closing as 'Not planned'.

so I'll re-open and close...

**Comment by aj-agoric** [comment]
Since Dan re-opened and closed it,, was moved to code complete in this project. Since its not planned I will remove it fromthe project.
