### ISSUE TITLE
CLI for FU Liquidity Provider

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#10328]
## Description of the Design

`deposit` command that does the public invitation maker. (for now whoever deposits first gets the sole right to withdraw)
`withdraw` command to withdraw deposits

Does not do anything for "requesting advance". @samsiegart is working on that.

## Upgrade Considerations

**Comment by dckc** [comment]
> Also fix up the "description" package.json of fast-usdc

was done in #10364
