### ISSUE TITLE
Contract flow tests

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#10388]
## What is the Problem Being Solved?

The FUC contract needs a test of its flows and error handling.

This issue is short of integrating with SwingSet, vstorage or other chains.

## Description of the Design / Test Plan

Package test exercising
 - [x] all the sequences in the product spec (#10572) and
 - [ ] all the code in the contract (#10607)

**Comment by LuqiPan** [comment]
@dckc is gonna remove skipped tests by either removing them or make them pass
