### ISSUE TITLE
Settler exo

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#10391]
## What is the Problem Being Solved?

Fast USDC needs a component to settle advances.

## Description of the Design

A Settler exo that performs the advancement operations.

It looks them up from Status Manager and settles per product spec.

## Test Plan

Exo test

Contract test is separate: https://github.com/Agoric/agoric-sdk/issues/10388

**Comment by dckc** [comment]
collecting details on the scope of this issue...

design sketch says:

An exo within FUC that handles settling transactions.

 - Taps the SettlementAccount to be notified of deposits
 - Extracts the EUD from the address parameters of the virtual address receiving the deposit
 - Looks up associated transaction using an Advancer method
 - Processes according to the sequence diagram
    - When in doubt, hold funds
 - Informs advancer of settlement

re "the SettlementAccount" - that presumes there is one. Does this exo make it?

**Comment by dckc** [comment]
re "settles per product spec" - this bit of the diagram seems particularly relevant:

```mermaid
sequenceDiagram
    rect rgb(255, 245, 230)
        Note over FUC,CFA: Settlement Process
        Note over FUC,SA: Tap on account reads MintAmount,<br/>parses EUD from virtual address recipient<br/>and looks up AdvanceAmount,PoolFee,ContractFee.<br/>Matches against an unsettled transaction (by EUD and approx amount).
        %% Treat starting the advance as an atomic action. Assume it will complete once started.
        alt Advance was started:
            FUC->>SA: Initiate transfers<br>out of settlement
            SA->>P: Deposit the AdvanceAmount + PoolFee<br>(= MintAmount - ContractFee)
            SA->>CFA: Deposit ContractFee
        else Advance for matched transaction that has not yet started:
            P->>NC: PFM transfer<br>(MintAmount of Agoric USDC denom) to EUD
            NC->>EUD: deliver MintAmount<br>as final USDC denom
        else Settlement for unknown transaction:
            %% Have not received notification of this Amount,EUD from the watcher
            Note over SA: Leave funds in SettlementAccount.
            Note over SA: Wait for observation from watcher
        end
    end
```
