### ISSUE TITLE
Vat Upgrade: v6-agoricNames

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#10408]
## What is the Problem Being Solved?

As mentioned in https://github.com/Agoric/agoric-sdk/issues/8158, we need the ability to restart all vats. This issue is concerned with upgrading `v6-agoricNames`.  agoricNames is **not** a Zoe contract.

The source code is [`nameHub.js`](https://github.com/Agoric/agoric-sdk/blob/mainnet1B/packages/vats/src/nameHub.js). It's a **critical** vat. It appears to be upgradeable. (uses `makeDurableZone` and `baggage`), though I haven't found an upgrade test.

I'm suspicious of `ephemera` and the native Maps (`new Map()`) it uses.

## Description of the Design

Write tests in a3p. verify that names bound to brands, instances, issuers, assets are retrievable after upgrade.

I think it's ok if reserved keys break across an upgrade.

OnUpdate doesn't look robust.  Verify that these continue to write to vstorage after the upgrade.
 * [orchestration has registered an `onUpdate` hook](https://github.com/Agoric/agoric-sdk/blob/d603b6c9c4d7b214dcd1a73f15a347c48e80b8bb/packages/orchestration/src/proposals/init-chain-info.js#L46) that doesn't look durable.
 * same in [chain-behavior.js](https://github.com/Agoric/agoric-sdk/blob/d603b6c9c4d7b214dcd1a73f15a347c48e80b8bb/packages/vats/src/core/chain-behaviors.js#L459-L461)

verify that code that holds both `nameHub` and `nameAdmin` facets will continue to have access, and that the hierarchy can be navigated post-upgrade.

## Security Considerations

Not directly security relevant, but continuity does impact the viability of the chain.

## Scaling Considerations

Not significant. This vat grows linearly with the data it holds.

## Test Plan

As described above. Thorough testing in `a3p-integration` should be sufficient.

## Upgrade Considerations

agoricNames normally holds promises that are resolved promptly. Are there any promises outstanding that matter?
@warner @mhofman Is this something you can check?

**Comment by toliaqat** [comment]
@anilhelvaci I am curious is this ticket has been verified on mainnet and can we change it's status to mainnet-validated?

**Comment by anilhelvaci** [comment]
Hey @toliaqat - Sorry for late reply. 

> I am curious is this ticket has been verified on mainnet and can we change it's status to mainnet-validated?

This ticket is shipped in `upgrade-19` and there are no reports of a bug that I'm aware of. I guess this makes it mainnet-validated?
