### ISSUE TITLE
Vat upgrade: 14 mintHolders

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#10410]
## What is the Problem Being Solved?

As mentioned in https://github.com/Agoric/agoric-sdk/issues/8158, we need the ability to restart or replace all vats. This issue is concerned with upgrading the 14 existing mintHolder contracts.

## Description of the Design

The source code is [mintHolder.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/vats/src/mintHolder.js).  These are not Zoe contracts.  [upgrade-vats.test.ts](https://github.com/Agoric/agoric-sdk/blob/fae2710728956d19413e67d7ac9bb399010bfdd2/packages/boot/test/upgrading/upgrade-vats.test.ts#L31) shows that They are upgradeable, though it doesn't test functionality. We should upgrade a mintHolder in `a3p-integration` and show that it continues to function correctly.

 * [x] v13: BLD
 * [x] v16: ATOM
 * [x] v17: USDC_axl
 * [x] v18: USDC_grv
 * [x] v19: USDT_axl
 * [x] v20: USDT_grv
 * [x] v21: DAI_axl
 * [x] v22: DAI_grv
 * [ ] v66: stATOM
 * [x] v71: USDC
 * [ ] v72: USDT
 * [ ] v96: stOSMO
 * [ ] v102: stTIA
 * [ ] v109: stkATOM

We should upgrade a few at first, and more over time.

## Security Considerations

mintHolders are the foundation for a lot of assets on our chain.

## Scaling Considerations

Not significant. Measurements haven't shown any indication of problems.

## Test Plan

As above. test in a3p-integration. 

## Upgrade Considerations

As above. Don't upgrade them all at once.

**Comment by anilhelvaci** [comment]
@Chris-Hibbert says "pick a number of vats and upgrade them, no need to upgrade all"

**Comment by Chris-Hibbert** [comment]
That was intended to be pick a number of vats and upgrade them in upgrade 19, and leave the rest for upgrade 20."
