### ISSUE TITLE
Core-Eval to change policy

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/Agoric#10507]
## What is the Problem Being Solved?

> C2 - ... BLD stakers MUST be able to revise the policy through a core-eval that updates what is written to vstorage.

## Description of the Design

follows...

 - https://github.com/Agoric/agoric-sdk/pull/10532

## Security Considerations

It's important to keep in mind that while the contract can state the confirmation policy, it cannot observe the relevant events on other blockchains in order to enforce the policy. The contract relies on the OCW to report external events accurately.

## Test Plan

 - [ ] bootstrap test to show that core-eval affected policy in vstorage

## Upgrade Considerations

This is an upgrade feature.

**Comment by dckc** [comment]
The way #10512 was addressed (in #10532) is that the contract never sees the chain policy.

Does that make this issue moot?
