### ISSUE TITLE
Comprehensive testing of failure scenarios

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/Agoric#10510]
## Description of the Design

RunUtils test covering happy path and error paths (from product)

Error paths from implementation and upstream service irregularities

Race conditions

Verify vstorage output

**Comment by 0xpatrickdev** [comment]
A lot of work was recently done around potential failure scenarios wrt to StatusManager. Namely, accounting for failed IBC transfers and unexpected timings around advance and settlement.

The bulk of the above was captured in #10530 which also included diagrams of the state machine:
https://github.com/Agoric/agoric-sdk/blob/23120a923c2bd3ca182291df2080214fbd5f20ca/packages/fast-usdc/README.md#status-manager

At the time of writing, there is a mistake in the `Minted -> Forwarded` step. `Mints` should wait for `Observe` before proceeding.

**Comment by 0xpatrickdev** [comment]
> At the time of writing, there is a mistake in the `Minted -> Forwarded` step. `Mints` should wait for `Observe` before proceeding.

This might suggest we need an additional state - perhaps `Minted` - to capture "minted before observed". If it's not a requirement of the state machine internals, we might want it for vstroage reporting _(under a new key since we won't have the evm `txHash`)_.

This surfaced when discussing #10508 with @samsiegart. Our current plan is only to report **TxStatus** statuses (below)  to vstorage and log the "minted before observed" events to the swingset console.

https://github.com/Agoric/agoric-sdk/blob/23120a923c2bd3ca182291df2080214fbd5f20ca/packages/fast-usdc/src/constants.js#L6-L22

**Comment by dckc** [comment]
In discussion of #10572 / #10388, we agreed to postpone this one to here:

  - [ ] [todo] C12 - Contract MUST only pay back the Pool only if they started the advance before USDC is minted

**Comment by 0xpatrickdev** [comment]
### Task List

_I suggest we create separate issues for each and close this once were in agreement:_ 

| Priority | Task | Details |
|----------|------|---------|
| 1 | Wrap vow handlers that create promises| • Some onFulfilled and onRejected handlers can throw; these failures will be silent (no unhandled promise rejection logs) until #10576<br>• @dckc suggests wrapping anything that can throw in try/catch for more graceful capture |
| 2 | Boot tests for Tx status updates and Pool Metrics | • Covers requirements around visibility for happy and failure paths from off-chain perspective<br>• All paths/states should be tested in bootstrap |
| 3 | Debug logging coverage | • vstorage writes do not generate a console log<br>• Need observability through TX lifecycle in console logs<br>• Current coverage is decent but could improve in: eventFeed, statusManager |
| 4 | `localTransfer`, `withdrawToSeat` failure paths | • Unexpected case but low effort to return payment to LP<br>• Task involves wiring up this return mechanism |
| 5 | `FORWARD_FAILED` state | • Transition to Forwarded on success, not initation<br>• Add state for ForwardFailed|


[Google Doc](https://docs.google.com/document/d/1ut26-p20pnr9iHF1LrKKBYjz2fOknRTCpjfkQ04ZDUY/) where much of this was fleshed out. There are many other paths around LP share path, fee calcs, and unexpected sequences we already have sufficient coverage for.

Tickets:
1. Boot Tests  + Debug Logging  (combined 2 +3)
2. localTransfer, withdrawToSeat failure paths
3. `FORWARD_FAILED` state

**Comment by 0xpatrickdev** [comment]
Resulting tickets:
- https://github.com/Agoric/agoric-sdk/issues/10623
- https://github.com/Agoric/agoric-sdk/issues/10624
- https://github.com/Agoric/agoric-sdk/issues/10625
