### ISSUE TITLE
`z:acceptance` "user can open a vault under debt limit" is flakey

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/Agoric#10599]
## What is the Problem Being Solved?

The `user can open a vault under debt limit` test in `a3p-integration/proposals/z:acceptance/vaults.test.js` seems to be flaky. 

Several PR's that do not touch `@agoric/inter-protocol` nor `@agoric/synthetic-chain` are consistently failing with:

```
 vaults.test.js:243

   242:                                     
   243:   t.is(                             
   244:     istBalanceBefore + Number(mint),

  The IST balance should increase by the minted amount

  Difference (- actual, + expected):

  - 43975819.49
  + 43975819.29

  › file://vaults.test.js:243:5
```

https://github.com/Agoric/agoric-sdk/actions/runs/12092142628/job/33721506423?pr=10588#step:10:6598
https://github.com/Agoric/agoric-sdk/actions/runs/12092261743/job/33721780758?pr=10571#step:10:6638
https://github.com/Agoric/agoric-sdk/actions/runs/12123427233/job/33798927107?pr=10591#step:10:6534

## Description of the Design

- `test.skip` should be restored
- test should consistently pass in CI

**Comment by turadg** [comment]
```
  Error: psmSwap tx send failed: {"exitCode":2}
      at psmSwap (file:///usr/src/proposals/z:acceptance/test-lib/psm-lib.js:552:11)
      at async file:///usr/src/proposals/z:acceptance/psm.test.js:195:3
```
[failure](https://github.com/Agoric/agoric-sdk/actions/runs/12145860881/job/33868460958?pr=10605) that is [passing on retry ](https://github.com/Agoric/agoric-sdk/actions/runs/12145860881/job/33871012612?pr=10605)


Upstream in the logs,
```
7:00PM ERR Error on broadcastTxCommit err="timed out waiting for tx to be included in a block" module=rpc
psmSwap tx send failed {
  command: 'agoric wallet --keyring-backend=test send --offer /tmp/agops.OlQ --from agoric1zlesuj60a3f59slushj65xx5asmzd8s7mn59qm --verbose',
  durationMs: 11091.834717,
  shortMessage: "Command failed with exit code 2: agoric wallet '--keyring-backend=test' send --offer /tmp/agops.OlQ --from agoric1zlesuj60a3f59slushj65xx5asmzd8s7mn59qm --verbose",
  cause: undefined,
  exitCode: 2,
…
    'Error: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). RPC error -32603 - Internal error: timed out waiting for tx to be included in a block\n' +
```
