### ISSUE TITLE
vat-priceAuthority upgrade is not tested

### ISSUE THREAD

**Issue by anilhelvaci** [Agoric/Agoric#10727]
## Problem Definition
Related https://github.com/Agoric/agoric-sdk/issues/10401

Currently the [registry.test.js](https://github.com/Agoric/agoric-sdk/blob/master/a3p-integration/proposals/p%3Aupgrade-19/registry.test.js) is not included in [test.sh](https://github.com/Agoric/agoric-sdk/blob/master/a3p-integration/proposals/p%3Aupgrade-19/test.sh).

Also looking at the contents of `registry.test.sh`:

https://github.com/Agoric/agoric-sdk/blob/9418efc6d8ba27f3361754ea2a55b47a367e06b3/a3p-integration/proposals/p%3Aupgrade-19/registry.test.js#L1-L20

We don't see that the `vat-priceAuthority` upgrade isn't carried out (looking for something like `evalBundles` or another way of running a core-eval) in `registry.test.js`. 

As to the nature of how we planned `Upgrade 19`, vat upgrade core-evals are commented out in `upgrade.go` including `upgrade-paRegistry.js`.

In conclusion;
* There's no code running that covers `upgrade-paRegistry.js`
* Code that covers `priceAuthority` upgrade is not executed

## Solution
* Add another test to `registry.test.js` like:
   ```js
   test.serial('upgrade vat-priceAuthority', async t => {
     await evalBundles('upgradePaRegistry');
   });
   ```
* Add below line to `test.sh`

   ```sh
   yarn ava registery.test.js
   ```

## Potential Improvement
Ideally, we should check that we can push prices and the pushed prices are received by the clients like `vaultFactory`.  This is currently tested in `z:acceptance`. However, since we are not upgrading `vat-priceAuthority`, `z:acceptance` is not aware of any changes to vat-priceAuthority. So I see two options here;
* We move upgrade vat-priceAuthority durably, `EVAL` or `USE` phase. This is sort of contrary to upgrade 19 plan as we comment out other core-evals.

OR;
 
* We implement the case I described above in `registry.test.js` 

Thoughts? @Chris-Hibbert

**Comment by Chris-Hibbert** [comment]
Thanks for cross-checking this. Certainly we should add `registry.test.js` to `test.sh`. If the incarnation check shows that the upgrade isn't happening, then we'll add the `evalBundle`, but "vats/upgrade-paRegistry.js" is included in `package.json`, so the upgrade ought to be invoked by `eval.sh`.

I'll take care of this.

**Comment by Chris-Hibbert** [comment]
```
{"vatName":"priceAuthority","vatID":"v8","incarnation":1,"bundleID":"b1-42cc2eec648914a9bd89beeb7888a2a4c7b0529a8705a9e5ddc106cbfdd7722e7ac3e6a3343728bd238f29dc4ad1724681594509d2036f7002df68467582bea0"}
  ✔ priceAuthorityRegistry upgrade
  ─

  1 test passed
```

**Comment by anilhelvaci** [comment]
> but "vats/upgrade-paRegistry.js" is included in package.json, so the upgrade ought to be invoked by eval.sh.

Oh yeah, there's `evalSubmission.js` that takes care of this. Thanks Chris!
