### ISSUE TITLE
get rid of `-bblock` in cli tooling

### ISSUE THREAD

**Issue by anilhelvaci** [Agoric/Agoric#10746]
## Context 
As of `v0.47` of `cosmos-sdk`, `block` broadcast mode is deprecated. See [ChangeLog](https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/CHANGELOG.md#api-breaking-changes-1). 

We've seen this caused some issues in our acceptance tests. See #10728.

Currently, `agoric wallet send` uses `-bblock`:

https://github.com/Agoric/agoric-sdk/blob/7b7ceb911dff780df7b4e562b7d87ed2fd628b92/packages/agoric-cli/src/commands/wallet.js#L175

I assume we should remove `-bblock` and start using default option `sync`. Thoughts? @turadg @LuqiPan 

cc @Chris-Hibbert

**Comment by mhofman** [comment]
I believe our plan is to keep support of `-bblock` in our fork, and actually remove the 30s timeout. @michaelfig @JeancarloBarrios

**Comment by michaelfig** [comment]
> our plan is to keep support of `-bblock` in our fork, and actually remove the 30s timeout.

Correct, we will make it more reliable than ever before!  See agoric-labs/cosmos-sdk#423

Having an implementation within `agd tx ...` allows us to avoid any tricky client-side synchronisation problems, as well as copy-pasta between all shell scripts currently using `-bblock`.

Closing this issue as "not planned."

**Comment by michaelfig** [comment]
Oh, maybe I didn’t actually clarify.  `-bblock` has been a feature for the cosmos-sdk `< v0.47.0`.  We’re currently on a fork of `v0.46.x`.  When we upgrade, it will be to a fork of `v0.50.x`, with our reimplementation of `-bblock` added to our fork.

**Comment by anilhelvaci** [comment]
> Having an implementation within `agd tx ...` allows us to avoid any tricky client-side synchronisation problems

In cosmos-sdk I've seen that `sync` option is said to be good for 99% of the cases. Are those "tricky client-side synchronisation problems" related to SwingSet then (assuming it has something to with its async nature)?

**Comment by michaelfig** [comment]
> > Having an implementation within `agd tx ...` allows us to avoid any tricky client-side synchronisation problems
> 
> In cosmos-sdk I've seen that `sync` option is said to be good for 99% of the cases. Are those "tricky client-side synchronisation problems" related to SwingSet then (assuming it has something to with its async nature)?

It's not related to SwingSet, it's related to multiple calls to `agd tx ...` to result in errors if any of the transactions didn't get included in a block, without having to do a manual "subscribe to tx event, submit tx sync, wait for subscription to report" wrapper every time.

**Comment by anilhelvaci** [comment]
Alright, thanks Micheal! I think I need to do a little bit more research on broadcast modes and how clients are effected from the events happening between mempool and block inclusion. Maybe then I can bother you again.
