### ISSUE TITLE
Please explain how to repair the test like I'm five

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#3823]
The test at

https://github.com/Agoric/agoric-sdk/blob/1b93efe7dee3cdd57282acc75548ad75b118f0c3/packages/zoe/test/swingsetTests/refillMeter/test-refillMeter.js#L49-L53

is necessarily fragile. Changes to code (like https://github.com/Agoric/agoric-sdk/pull/3821 ) that are not at all about metering can tickle performance to put something just slightly over or under some threshold, causing this test to fail. However, the comments at that test

```js
  // If this assertion fails, please update this test with the new
  // computron values. This test aims to be resilient to changes in
  // computron values for particular actions but a significant change
  // may break the test.
```

assume too much knowledge about metering --- knowledge that the person who needs to fix may not have. Like, for example, the author of https://github.com/Agoric/agoric-sdk/pull/3821 . What do I need to do to fix this test without breaking the usefulness of the test? Where should this be documented?

**Comment by erights** [comment]
The failures provoking this are https://github.com/Agoric/agoric-sdk/pull/3821/checks?check_run_id=3593496385 and https://github.com/Agoric/agoric-sdk/pull/3821/checks?check_run_id=3593516416

**Comment by katelynsills** [comment]
There's a related issue here: https://github.com/Agoric/agoric-sdk/issues/3804

I think this will probably be fixed if we can do as Brian suggests. We might want to split this into two tests: one for checking the correct functionality, and another as a canary for breaking changes to the computrons used.

**Comment by katelynsills** [comment]
In the meantime, I can fix the test in your PR, if that'd be helpful!

**Comment by erights** [comment]
> In the meantime, I can fix the test in your PR, if that'd be helpful!

Yes, thanks!!!!

**Comment by erights** [comment]
@warner is this still relevant? Can it be closed?

**Comment by warner** [comment]
too stale to be useful, closing
