### ISSUE TITLE
reduce boilerplate for Far and E?

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#3833]
## What is the Problem Being Solved?
`import { Far } from '@agoric/marshal';` in order to get `Far` is "surprisingly ugly" (@dtribble 's words). It's "get some low-level package you might not recognize in order to us a declaration you need to have everywhere".

## Description of the Design

Does it make sense to either:
- have it in the global 
- have a package named Far
- perhaps have it in eventual-send so we import it and E from there

@michaelfig notes:
Getting Far's type is trickier if we don't import it.

Getting all the details of another global (typing, Compartment threading...) is tricky, but that's a 1-time pain for us vs. every contract writer every day.

@erights adds:
Let's revisit this after eventual-send and marshal have been migrated from agoric-sdk to endo.

## Security Considerations

?

## Test Plan

?

_assigned to @erights , @dtribble in a customer role_

**Comment by zarutian** [comment]
I often do
```js
import { Far, E } from "@agoric/eventual-send";
```
with the assumption that `Far` was imported into and re-exported by the `eventual-send` package. Basically the third enumerated option above.

**Comment by kriskowal** [comment]
The current correct answer is `import { E, Far } from '@endo/far';` which now entrains only `@endo/eventual-send` and `@endo/pass-style`. Contracts will not carry the weight of `@endo/marshal` in bundles after the next release and sync with Endo.
