### ISSUE TITLE
Typing: IDE correctly complains of typing error `yarn lint` does not see

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#3840]
Provoked by https://github.com/Agoric/agoric-sdk/pull/3821#discussion_r710526027 . See discussion there.

With no `@ts-ignore` or `@ts-expect-error`, at

https://github.com/Agoric/agoric-sdk/blob/f193fa225c6e2e88b067d43e22b1fcc1230ebb98/packages/marshal/src/marshal.js#L405

causes my IDE to indicate a typescript typing error that seems correct

![image](https://user-images.githubusercontent.com/273868/133692696-51342702-7bfc-42f6-8d01-2ea5f988670e.png)

However, `yarn lint` does not report this error. Thus, when I try to suppress the error *properly* with `@ts-expect-error` my IDE no longer indicates a problem, but yarn lint complaints with

![image](https://user-images.githubusercontent.com/273868/133693708-be1d2b90-c93b-45ec-af7f-1821e89de112.png)

also seen at https://github.com/Agoric/agoric-sdk/pull/3821/checks?check_run_id=3626466228

**Comment by dckc** [comment]
ew. I can imagine version skew at play. But first...

Various forms of "turn it off and turn it on again" come to mind.
  - In the shift-command-p menu:
      - **TypeScript: Restart TypeScript server**
      - **Developer: Reload Window**
  - Elsewhere:
      - reinstall vs-code
      - throw computer out window and get new one
      - ... or don't get new one; take up gardening instead :)

**Comment by mhofman** [comment]
Wondering if TS in VSCode picks up types that jsconfig doesn't. It might be a case of ambient types leaking in the IDE but not un the lint command

**Comment by mhofman** [comment]
I take that back, the `types.js` is explicitly imported, however it has a `ts-no-check` which may cause some issues. But even after making it `ts-check` and fixing a type declaration issue, I still get the same error during lint.

**Comment by mhofman** [comment]
I went for it and converted `types.js` to `types.d.ts`, removing all ambient types and `import 'types.js';`, and no luck, same error. At this point it may be that the language server in VS Code forces some options on which allow to correctly do type narrowing, and for some reason, the same type narrowing is lost in aa direct `tsc` invocation. I'm not sure how to debug this further.

For reference, here is the result of my conversion to type declaration file: https://github.com/Agoric/agoric-sdk/compare/mhofman/marshal-convert-type-declaration

**Comment by michaelfig** [comment]
> At this point it may be that the language server in VS Code forces some options on which allow to correctly do type narrowing

The explanation is even simpler than this.  Try hitting `Cmd-Shift-P` in VScode, then type `TypeScript: Select TypeScript Version...` and notice the following:

![image](https://user-images.githubusercontent.com/457244/133908555-18833e96-ad4a-4f13-90c4-e34691e33548.png)

Latest VSCode's builtin Typescript is `v4.4.2` and the `agoric-sdk` workspace version is `v4.2.3`.  If you want your VSCode annotations to line up with the project's `yarn lint`, you need these two to be the same (or at least the same minor version).  We could upgrade the workspace to use `v4.4.x`, if somebody wants to take that on and fix all the incompatibilities, or you could just select the workspace version (`v4.2.3`) and your VSCode won't have different behaviour.

Have fun!

**Comment by mhofman** [comment]
🤦‍♂️ how did I forget about that. Also curious now which change in TS caused the difference!

**Comment by mhofman** [comment]
I'm putting my money on https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#control-flow-analysis-of-aliased-conditions-and-discriminants, which also means we should be able to remove things like: https://github.com/Agoric/agoric-sdk/blob/f193fa225c6e2e88b067d43e22b1fcc1230ebb98/packages/marshal/src/marshal.js#L319-L322

**Comment by erights** [comment]
https://github.com/Agoric/agoric-sdk/issues/3840#issuecomment-922374493 solves the problem. Thanks!

Closing.
