### ISSUE TITLE
[object Object] obscure form in xsnap console

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#3844]
## Describe the bug

In un-redacted console messages, our [xsnap console shim](https://github.com/Agoric/agoric-sdk/blob/master/packages/xsnap/lib/console-shim.js) prints `[object Object]` where we're used to more detail from the node.js console.

```
Error#4: Withdrawal of [object Object] failed because the purse only contained [object Object]
```

## To Reproduce

for example: https://github.com/Agoric/testnet-load-generator/issues/30

## Expected behavior

something more like [inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options).

or perhaps `assert.quote` from SES?

## Platform Environment
 - what version of the Agoric-SDK are you using? d48e6a7

## Additional context

originally discussed in https://github.com/Agoric/testnet-load-generator/issues/30

cc @kriskowal @katelynsills @mhofman

**Comment by kriskowal** [comment]
This probably requires a virtual-terminal console emulation backed by `print` to run inside XS. I believe `ava` has one and there is a `util` shim. We may need to find and use the lightest of these options.

**Comment by kriskowal** [comment]
We may also have to adapt an existing one to XS or adapt XS to provide `process.stderr`. We should also not have `console.log` going to `stdout` like the Node.js prior-art.

**Comment by dckc** [comment]
virtual-terminal? process.stderr? I am not following at all.

`assert.quote()` seems like The Right Thing, to me.

**Comment by kriskowal** [comment]
If `quote` transpires not to be the right thing, as it won’t in every case, the underlying object should still be rendered in a useful way thru the powerful console in the start compartment, and in that case, we’ll want a more expressive console. Perhaps not so far as using one that does TV100 like Node.js, but one that at least renders like `quote`.

**Comment by dckc** [comment]
In what case will `assert.quote` not be the right thing? Can't we just decide that it _is_ correct?

**Comment by kriskowal** [comment]
`assert.quote` should not be used if the underlying value should not be revealed to intermediate stack frames, and may be revealed to the powerful console.

**Comment by dckc** [comment]
I meant this issue to be only about _un-redacted console messages_. I clarified the description.

My suggestion is not that the caller of `console.log()` should use `assert.quote` in the situation in question, but that `assert.quote` might replace the implementation of the actual console in our console shim, which is currently an ad-hoc combination of whatever XS's `print` does with some `.toString()` calls and exception catching.
