### ISSUE TITLE
no supported workflow for installing from npm

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#3857]
## Describe the bug

We don't have a supported workflow of building dapps by installing packages such as `@agoric/zoe` from npm. Only building from source is adequately supported.

For example, the agoric cli is installed using `yarn link-cli`, unlike other npm tools that are installed using `npm install -g` or the like.

## To Reproduce

If you run `agoric install` from inside an `agoric-sdk`, you're in a world of hurt.

If you then make a new `agoric-sdk` clone, forgetting to `yarn link-cli` leads to difficult-to-diagnose version skew (this cost @dtribble a bunch of time today).

`npx agoric init demo` doesn't work:
```
$ npx agoric init demo
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/gitpod/.npm/_npx/1639/lib/node_modules/agoric/bin/agoric
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/gitpod/.npm/_npx/1639/lib/node_modules/agoric/bin/agoric'
```

running `agoric` with a pre-ESM version gives a pretty bad diagnostic:
```
$ agoric
/home/connolly/projects/agoric/agoric-sdk/packages/agoric-cli/lib/entrypoint.js:6
import 'esm';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
```

## Expected behavior

like other dev tools in the npm world

cc @mhofman @katelynsills @warner @michaelfig

**Comment by michaelfig** [comment]
> The agoric cli is installed using yarn link-cli, unlike other npm tools that are installed using npm install -g or the like.

We can certainly make `npm install -g agoric` and `yarn global add agoric` work (again), but that can only use the latest published NPM version of the SDK, and hence is inappropriate for rapid development.

Be aware that if you want to use an existing checkout of `agoric-sdk` and have it immediately use any of your changes, there will always need to be a special case for that, whether:

a. Use `yarn link-cli`
b. Set some environment variable to point to the SDK
c. Install the SDK in a conventional location
d. Explicitly run `.../agoric-sdk/packages/agoric-cli/bin/agoric` or some other entrypoint within the SDK
e. Something else?

Pick your poison.

**Comment by mhofman** [comment]
> > The agoric cli is installed using yarn link-cli, unlike other npm tools that are installed using npm install -g or the like.
> 
> We can certainly make `npm install -g agoric` and `yarn global add agoric` work (again), but that can only use the latest published NPM version of the SDK, and hence is inappropriate for rapid development.

The usual workflow for this is `yarn link`. Maybe a possible flow for an `agoric-cli` package globally installed would be:
- (optional, in agoric-sdk) `yarn link-cli`: setup global link for the `agoric-cli` from this sdk location.
- ` agoric use-sdk [sdk-path]` (in dapp): sets up yarn links for this project, using the sdk path the `agoric-cli` is coming from if above step was done and no specific path was provided. It'd replace `agoric install`, and would be use once (TBD: I'm not sure what a `yarn install` does after a `yarn link`)
- other `agoric` commands defer to the `agoric-cli` of the local project (equivalent to `npx agoric`)

> Be aware that if you want to use an existing checkout of `agoric-sdk` and have it immediately use any of your changes, there will always need to be a special case for that, whether:
> 
> a. Use `yarn link-cli`
> b. Set some environment variable to point to the SDK
> c. Install the SDK in a conventional location
> d. Explicitly run `.../agoric-sdk/packages/agoric-cli/bin/agoric` or some other entrypoint within the SDK
> e. Something else?
> 
> Pick your poison.

`npx agoric` will pick `./node_modules/.bin/agoric` if `agoric-cli` is installed as a dependency, either from registry or from `yarn link`.

**Comment by dckc** [comment]
@mhofman reports that we're not quite there yet: https://github.com/Agoric/agoric-sdk/pull/4129#issuecomment-991423552

**Comment by dckc** [comment]
I ran into another person trying to do `npm i @agoric/zoe` like it says on https://www.npmjs.com/package/@agoric/zoe and it doesn't work.

**Comment by mhofman** [comment]
We disabled the CI test that uses `local-npm`, so paint me not surprised.

**Comment by dckc** [comment]
I'm not surprised either; https://docs.agoric.com/guides/getting-started/ is the only currently supported path. This open issue is just an acknowledgement that we're behind market norms in this respect.

**Comment by dckc** [comment]
I tried using the SDK as normal npm packages in the context of some recent work on [a smart-wallet style app starter](https://github.com/agoric-labs/dapp-join-game/pull/2), but I hit:

```
Cannot find module '.../simple-game/contract/node_modules/@agoric/swingset-liveslots/tools/fakeVirtualSupport.js'
```

looks like `@agoric/swingset-liveslots` doesn't include it in its npm package.

So I went back to `agoric install` style links :-/

p.s. my WIP: [dc-test-contract](https://github.com/agoric-labs/dapp-join-game/tree/dc-test-contract) https://github.com/agoric-labs/dapp-join-game/commit/1a653c0268fa77c9f5c696252a0df66a97243f29

**Comment by mhofman** [comment]
Known issue tracked in #8380 and which will be solved by #8390

**Comment by dckc** [comment]
recent progress:

 - #8530

**Comment by dckc** [comment]
We now have a supported workflow based on `yarn create ...` from #8530 that works for at least one dapp . There are likely rough edges, but let's address those in other issues.

https://docs.agoric.com/guides/getting-started/ documents it as of [1cf164c](https://github.com/Agoric/documentation/commit/1cf164c5816dcad8e979a3c1b337addf1d3cfab8)
