### ISSUE TITLE
make Treasury Vaults transferrable

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#3864]
## What is the Problem Being Solved?

RUN Protocol Vaults operate as an ongoing contract, where the owner of the vault holds a seat in the ongoing activity of the vault. Our general model of smart contracts is that such "Seats" should be transferable. We should accomplish that with our initial smart contract use case.

Vaults contain collateral for a "loan". Loans start out over-collateralized, so the vaults can represent a valuable asset. The asset should be transferrable using standard ERTP approaches. If buyers believe that the value of the collateral will grow faster than the required interest, it could make sense to purchase it.

## Description of the Design

The owner of the vault should have the ability to request a transfer. This would prevent further withdrawals, and return an invitation with sufficient specificity that a potential buyer could evaluate the contents.

The basic idea is that without further support from Zoe, the contract can create an invitation that when completed would turn all the assets (stored on the internal `vaultSeat`) over to a new seat. The current assertVaultIsOpen() call would be updated to also check a generation number if the idea is to transfer the vault object to the new owner rather than reallocating all the assets.

## Security Considerations

Standard ERTP visibility issues. There doesn't seem to be financial risk to the system. The owner can't extract collateral unless the loan is overcollateralized. The new owner doesn't have more access to the contents than the original owner did.

## Test Plan

nothing special.

**Comment by Tartuffo** [comment]
needs design with @rowgraus, @dtribble, @Chris-Hibbert , @erights

**Comment by Chris-Hibbert** [comment]
We had an (unrecorded, unfortunately) conversation at the Zoe/ERTP meeting yesterday. 

The basic idea is that without further support from Zoe, the contract can create an invitation that when completed would turn all the assets over to a new seat. While the invitation is live, it would make sense to allow the current holder of the vault to continue to pay down debt. It's probably worth while to forbid increasing the loan amount, so that the holder of the invitation has a better idea of what they're being offered.

If we want to add general purpose support to Zoe, it would probably make sense to disable all state changes for the use object. With vaults, that's probably not the ideal outcome. (Someone could get exclusive access to the invitation and never exercise it.)

The current `assertVaultIsOpen()` call would be updated to also check a generation number if the idea is to transfer the vault object to the new owner rather than reallocating all the assets.
