### ISSUE TITLE
Enable Governance to change Liquidation contract in Vaults

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#3865]
## What is the Problem Being Solved?

The LiquidationStrategy used in the treasury can be specified in the terms. Currently there is only one implementation, and the choice is made when the contract is started. This should be under the control of governance.

## Description of the Design

Even without actually adding a second Liquidation implementation, it would be valuable to make the choice of contract be subject to governance. The current ContractGovernor supports parameters that specifies installations, so adding this to the governedParams would be straightforward.

## Security Considerations

Governance could make bad choices. 

## Test Plan

The usual

**Comment by Tartuffo** [comment]
@dtribble Did you start working on this?  @Chris-Hibbert seems to think that you did.

**Comment by Tartuffo** [comment]
@dtribble is working on the new liquidation contract (#4568).  This issue is about being able to CHANGE the liquidation contract via Governance.

**Comment by Tartuffo** [comment]
@dtribble I believe this is not necessary for RUN Protocol Review, please confirm.

**Comment by Chris-Hibbert** [comment]
closed by #5211
