### ISSUE TITLE
Create Input Validation Helpers for Contract Devs

### ISSUE THREAD

**Issue by katelynsills** [Agoric/Agoric#3867]
## What is the Problem Being Solved?

Arrays and Copy Records need to confirmed as such to be safe. Otherwise, an attacker can provide an array or object that appears to act normally, but which can change behavior at will. 

## Description of the Design

Helpers that do `passStyleOf` for `copyRecord` and `copyArray` and `remotable`

**Comment by katelynsills** [comment]
Related: https://github.com/Agoric/agoric-sdk/issues/72

**Comment by erights** [comment]
See conversation at https://github.com/Agoric/agoric-sdk/pull/3955#discussion_r726747784
