### ISSUE TITLE
Internal Governance Demo

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#3869]
## What is the Problem Being Solved?

Give a demo to the team of how the pieces of the governance system interact

## Description of the Design

Tentatively scheduled for 9/27. That's at risk since @Chris-Hibbert is OOO 9/23-24 and @rowgraus is OOO though 9/22.

 - [Gov Demo \- Google Slides](https://docs.google.com/presentation/d/1ZVN0pzJlLqzCXm407Z_fS_KlDCMC7yVXSHGAMmRAqyg/edit#slide=id.gf2d65c313f_0_7)
 - https://gov-demo-ag-2.netlify.app/ 
 - https://github.com/agoric-labs/gov-demo1

## Security Considerations

None

## Test Plan

a few run-throughs.

**Comment by dckc** [comment]
I sorta got a UI working: https://github.com/agoric-labs/gov-demo1

![image](https://user-images.githubusercontent.com/150986/134783403-d213ed12-cbc3-4ffe-85f6-719758c571a6.png)

[older screenshot](https://user-images.githubusercontent.com/150986/134765462-735ee3b0-3fea-491b-8388-b6b43436fa7b.png)

The first roughly-working version, `65ccaaf`, was about 550 LOC, not counting stuff I copied from dapp-card-store more or less verbatim:
```
$ wc package.json index.html src/*.js
   46    95  1205 package.json
  110   270  3441 index.html
  318   762  9150 src/main.js
   81   318  2557 src/ui.js
  555  1445 16353 total
```

```
$ wc public/agoric-wallet.html src/utils/fetch-websocket.js 
  77  234 2741 public/agoric-wallet.html
 206  537 5811 src/utils/fetch-websocket.js
 283  771 8552 total
```


cc @samsiegart @michaelfig @katelynsills

**Comment by dckc** [comment]
@michaelfig it works from localhost, but when I deploy to https://gov-demo-ag-2.netlify.app/ I get a 404 when connecting to the wallet.

I suppose I should be able to find the configuration stuff that I neglected to preserve when I was adapting code from dapp-card-store, but maybe you could find it faster?

The netlify stuff is deploying from https://github.com/dckc/gov-demo1 (cuz it looks like I lack some relevant magic powers for agoric-labs).

**Comment by katelynsills** [comment]
That's super impressive!

**Comment by dckc** [comment]
It's deployed at https://gov-demo-ag-2.netlify.app/ (currently rev `a481149`)

Thanks, @michaelfig and @samsiegart for [@agoric/wallet-connection](https://github.com/Agoric/agoric-sdk/tree/master/packages/wallet-connection)

**Comment by dckc** [comment]
We went thru the demo today. Recording is available internally.

We used rev `3fab61b` of https://github.com/agoric-labs/gov-demo1/network/members for the demo, plus the committee registrar contract from the `contractGovernanceMgr-3185`.

**Comment by dckc** [comment]
@dtribble @katelynsills @Chris-Hibbert @rowgraus should these be issues? (_the conservative answer to that question is always "yes"..._)

 - @dtribble found the terminology in the design diagrams and the API confusing. For example:
   - A registrar corresponds to an electorate; "Electorate" is easier to talk about in some ways.
 - A separate vat per vote counter seems ... awkward? expensive?
   - CH: one motivation is checkable terms
     - DT: the contract governor seems like the authority on questions; we could rely on that rather than zoe for terms. or maybe the vote counter
     - KS: this use of zoe does protect against giving one answer now and then another later... so we'd have to be careful if we use on another mechanism

_p.s. I suppose @katelynsills is reviewing #3448 , so we can use that for follow-up._

**Comment by Chris-Hibbert** [comment]
I wrote a note-to-self on finding something public-facing to rename to be the electorate. An issue for that would be a fine thing, though I'm not sure it will be done as a separate task.

An issue on whether and how to maintain the verifiability of vote counters without one vat per vote would be a fine thing.

**Comment by zarutian** [comment]
On dtribbler terminology note: I got the impression that Registrar kept the records on who, in a sense, are part of the electorate and can cast votes in governance voting that relie on that Registrar.
