### ISSUE TITLE
[ERTP] Examine input validation and augment

### ISSUE THREAD

**Issue by katelynsills** [Agoric/Agoric#3885]
We need to examine ERTP for circumstances in which a user-provided value is being handled and needs to be validated. We should look in particular for any assumption of copyArrays or copyRecords. 

Related: https://github.com/Agoric/agoric-sdk/issues/3867

**Comment by erights** [comment]
See conversation at https://github.com/Agoric/agoric-sdk/pull/3955#discussion_r726747784
