### ISSUE TITLE
Contract deploy time

### ISSUE THREAD

**Issue by ctjlewis** [Agoric/Agoric#3896]
Deploying contracts seems to take an absurd amount of time (on order of minutes). Are there any resources on why this process takes so long, and/or how it can be optimized?

I'm just working with the example Card Dapp for now.

**Comment by dckc** [comment]
The `yarn start:contract` step in dapp-agoric-basics integration testing took 32 seconds in [a recent job](https://github.com/Agoric/dapp-offer-up/actions/runs/11354689170/job/31582471789).
