### ISSUE TITLE
Add sourceURL to endoZipBase64 bundle format to restore parity with nestedEvaluate

### ISSUE THREAD

**Issue by kriskowal** [Agoric/Agoric#3899]
## What is the Problem Being Solved?

Refs: #3843

No Agoric bundles currently have useful `//#sourceURL` comments for local development. By default, bundles are and must be suitable for submission to a chain and two users submitting the same source artifact from different home directories should arrive at the same bundle and the same hash.

## Description of the Design

But, we could extend Endo to produce development versions of an archive that keep track of original sourceURLs and leave a mark in their `compartment-map.json` that provides some indicator that it is a debug build and an indicator of who the bundle should work for and no-one else.

## Security Considerations

Our deployment scripts should guard against submitting such bundles to a live chain, and every bundle importer should refuse to run bundles built by other users.

## Test Plan

This will require unit and integration tests in `@endo/compartment-mapper`, `@agoric/bundle-source`, `@agoric/import-bundle`, and `@agoric/` deployment code.

**Comment by kriskowal** [comment]
@warner An open design question is how far to go to mark a debug archive. Would a user name suffice for a guard? Could this go as far as signing? This is a safety mechanism and not a security mechanism, so I think a user name in the manifest would suffice. Having any marker would guard against submission to a live chain.

@michaelfig Do we have a way for the receiver of a bundle to know whether they’re running in debug or prod? Can we rely on `ENVIRONMENT=production|development`?

**Comment by michaelfig** [comment]
> @michaelfig Do we have a way for the receiver of a bundle to know whether they’re running in debug or prod? Can we rely on `ENVIRONMENT=production|development`?

```
../cosmic-swingset/src/chain-main.js
252:    const consensusMode = env.DEBUG === undefined;
```

Thus, the test for production mode is: `process.env.DEBUG === undefined`.

**Comment by kriskowal** [comment]
@erights suggested at the Endo sync that tools like VS-Code are sufficiently hinted with a prefix in `sourceURL` like `//#sourceURL=ses/src/lockdown-shim.js`

**Comment by erights** [comment]
The existing `{stackFiltering: 'concise'}` lockdown options heuristically creates such source prefix now, as displayed in stack traces on the console. The vscode experience on clicking on them is very pleasant. Reliable developer independent suffixes would be great. Shouldn't even need a switch. No `stackFiltering` or developer vs production. We should keep these suffixes in production.

https://github.com/endojs/endo/blob/master/packages/ses/lockdown-options.md#stackfiltering-options

**Comment by dckc** [comment]
Thanks for the pointer to this, @kriskowal .

I suggest re-phrasing the title etc. as a bug than an enhancement; it's a devex regression.

**Comment by kriskowal** [comment]
> Thanks for the pointer to this, @kriskowal .
> 
> I suggest re-phrasing the title etc. as a bug than an enhancement; it's a devex regression.

Do you have a case that fails to provide names now, but is fixed by changing the default bundle format in `bundle-source` back to `nestedEvaluate`?

**Comment by dckc** [comment]
yes; note the `makeAddTypeInvitation` stack frame:

using `endoZipBase64` on master (975974eb2):

```
Logging sent error stack (Error#1)
Error#1: Check failed
Error: Check failed
 at construct ()
 at Error (/home/connolly/projects/agoric/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:9427)
 at makeError (/home/connolly/projects/agoric/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:3697)
 at fail (/home/connolly/projects/agoric/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:3825)
 at baseAssert (/home/connolly/projects/agoric/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:3843)
 at makeAddTypeInvitation (#527:136)
 at ()
 at ()
```

using `nestedEvaluate`:

```
Logging sent error stack (Error#1)
Error#1: Check failed
Error: Check failed
 at construct ()
 at Error (/home/connolly/projects/agoric/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:9427)
 at makeError (/home/connolly/projects/agoric/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:3697)
 at fail (/home/connolly/projects/agoric/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:3825)
 at baseAssert (/home/connolly/projects/agoric/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:3843)
 at makeAddTypeInvitation (/bundled-source/.../packages/treasury/src/stablecoinMachine.js:136)
 at ()
 at ()
```

**Comment by kriskowal** [comment]
From conversation out of band with @dckc @michaelfig @erights:

For parity, we only need <kbd>⌘/＾</kbd>+<kbd>click</kbd> on file names in stack traces in VS Code’s Terminal view to reveal the corresponding source in the open workspace. For this it is sufficient for the source URL to be `.../` + the basename of the package name (last path component, e.g., `compartment-mapper` for `@endo/compartment-mapper` joined with on the package-relative module specifier.

We learned that the VS Debug view doesn’t make file names in stack traces reliably clickable, so that isn’t a success criterion.

Debugger statements work already and regardless of the sourceURL, so that isn’t a success criterion either.

Beyond parity, we arrived at mutual understanding of an idea that would preserve the consistent hash of bundles, avoid accidental exposure of local debug information to production systems, and produce a good experience for IDE breakpoints in the stepping debuggers. The sourceURL evaluated locally must be the exact file URL on the debugging machine for this to work. We propose that we could hook bundleSource and importBundle such that the `bundleSource` leaves a note in a per-user database (like one stored under `~/.agoric`) that maps the hash of the bundle to a file that indicates the fully qualified path for each package in the archive’s compartment map. Then, `importBundle` would rehydrate the sourceURL’s according to the local information for that hash. https://github.com/endojs/endo/issues/929

**Comment by dckc** [comment]
We won't actually enjoy the fix until agoric-sdk is upgraded to a new SES release, I expect.

**Comment by kriskowal** [comment]
Yes, any change from the Endo repository requires a release to realize in
Agoric SDK.

**Comment by michaelfig** [comment]
@kriskowal, would it be possible to add some kind of postamble hook to the `archive['import']` call so that the SDK has a place to stand to add `sourceURL` and/or sourceMaps during `@agoric/import-bundle`?  I'd like to see that in the coming release, if possible.

**Comment by kriskowal** [comment]
@michaelfig I am looking into a design for your suggestion and assume that I would need to provide hooks for both creating and consuming archives for this to be useful. Do I assume correctly that this would be a request toward experimenting with your idea with a shared database?

**Comment by michaelfig** [comment]
> @michaelfig I am looking into a design for your suggestion and assume that I would need to provide hooks for both creating and consuming archives for this to be useful.

Yes, that would make sense.

> Do I assume correctly that this would be a request toward experimenting with your idea with a shared database?

Yes, if the hooks are (soonish) in place, that makes my job easier/possible.

**Comment by kriskowal** [comment]
https://github.com/endojs/endo/pull/932 completes the compartment mapper API necessary for fully qualified debug source URL’s.
