### ISSUE TITLE
expose XS the->currentHeapCount to metering/delivery results

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#3910]
## What is the Problem Being Solved?

It'd be awfully helpful to have xsnap delivery results include `the->currentHeapCount`, as described in https://github.com/Agoric/agoric-sdk/issues/2631#issuecomment-922007282

This tracks the number of "slots" allocated by the XS heap. Each slot uses 32 bytes (on my 64-bit kernel), and most native JS objects need one or two of them. The number grows whenever an object is created (even temporarily), and only drops when GC happens. This is close enough to what we want a spacebank to measure that we should expose it so we can start paying attention to it.

It probably doesn't include "bulk" memory (used for strings, the backing store on an Array, the hash tables in Maps/Sets, also I think large `BigInt`s use a slab), so we'll need to find the right way to track that too.

`the->allocatedSpace` tracks a high-water mark of slots, never goes down, is denominated in bytes, and grows in much larger steps (maybe 128kiB? 1 MiB?). It tracks how much memory (for slots) XS has requested/received from the operating system, formerly via `malloc` and now through `mmap`. We currently report `the->allocatedSpace` in the metering results as `allocate`. We should keep reporting it, for now.

The task is to add `slots` to the metering results (which currently contain `compute` and `allocate`).

## Security Considerations

The number of slots allocated during execution is just as revealing as the number of computrons consumed, so the security profile doesn't change. Metering results are initially private to the kernel, but exposed (via Meters) to the controlling vat through the admin facet.

## Test Plan

`packages/xsnap` should acquire some more unit tests, next to the existing ones for `compute`, to ensure that the C code is including the metering results.

CC @dckc : if you feel you can take this on, go for it, else assign me and I'll see what I can figure out. We should check our work with the Moddable folks. Also, perhaps this ticket should be filed/transferred to the xsnap-pub repo, I wasn't sure.

**Comment by warner** [comment]
https://github.com/agoric-labs/xsnap-pub/pull/7 added the support to the `xsnap` binary. I'll make a PR to add support to the JS side (`packages/xsnap/`).

**Comment by dckc** [comment]
Adding `currentHeapCount` requires a test update near the trigger for updating `METER_TYPE`. Should I bump METER_TYPE to `xs-meter-12` even though the compute and allocate numbers don't change?
