### ISSUE TITLE
add collateral to AMM under governance (internal demo)

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#3913]
Internal Demo: New collateral type X added to the treasury, Treasury sells BLD for collateral, then mints RUN and initializes a pool

initially from a Sep 29 meeting.

_probably belongs in the treasury epic #3863 and/or the governance planning Epic #3185._

**Comment by dckc** [comment]
I asked @michaelfig about the mechanics of adding a collateral type, governance or no governance; he provided me with an `addCollateral.js` script, presumably developed in the heat of other demos...

https://gist.github.com/dckc/eb16477068dfdc0930ac0e2c2266971f

**Comment by dckc** [comment]
I spent some quality time with [addCollateral.js](https://github.com/agoric-labs/gov-demo1/blob/add-collateral/src/addCollateral.js) yesterday:
  1. getting concrete experience with a sim-chain
  2. factored 3 smaller functions out of the one big function (currently `c3fe00b`)
      - the result probably has more round trips in some cases

### What collateral to add? `FungibleFaucet.Token`

I don't see any way to adding a new issuer / mint from a deploy script alone, without deploying a contract.

The Fungible Faucet does exactly that, so I have been using its `Token`. As far as I can tell, it does what we need for demo purposes.

**Comment by Chris-Hibbert** [comment]
The AMM docs also talk about [adding liquidity to a pool](https://agoric.com/documentation/zoe/guide/contracts/multipoolAutoswap.html#adding-liquidity-to-an-existing-pool)

**Comment by dckc** [comment]
I got as far as proposing a parameter change.

 - `7a78fe94f7d7` feat: propose parameter change https://github.com/agoric-labs/gov-demo1/tree/add-collateral

### deploy script

```
~/projects/agoric/gov-demo
01:48 connolly@jambox$ yarn deploy:contracts
yarn run v1.22.5
warning package.json: No license field
$ agoric deploy tools/gov-demo-prep.js
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /home/connolly/projects/agoric/gov-demo/tools/gov-demo-prep.js
agoric: deploy: Deploy script will run with Node.js ESM
await feesAvailable...
{
  feesAvailable: { brand: Object [Alleged: RUN brand] {}, value: 148100207n }
}
await bundle contracts...
await install contracts...
await start electorate...
await start contractGovernor...
await get board Ids...
{
  governor: '794977354',
  governorInstance: '529406044',
  governedInstance: '715805464',
  committee: '474502210',
  binaryVoteCounter: '688500812',
  contractGovernor: '112440918',
  governedContract: '1675202761'
}
Done in 35.73s.
```

### ui

![image](https://user-images.githubusercontent.com/150986/136750692-dee78ab6-49a3-4253-9c1a-b320c5f57668.png)

and in the console:

```
proposing change... 
{paramSpec: {…}, proposedValue: Alleged: USDC brand}
...
{result: {…}}
```

**Comment by dckc** [comment]
The progress above depends on a small tweak to the governance package: https://github.com/Agoric/agoric-sdk/pull/3952

**Comment by dckc** [comment]
We did the demo today. We were able to
 - claim treasury committee member invitations
   - `agoric start --reset` a local sim chain
   - `agoric deploy tools/gov-demo-prep.js` to get board ids for `agoricNames` and `chainTimerService`
   - `agoric open --repl` to start the wallet
   - `yarn start` the gov-demo app; approve it in the wallet
   - **Get Committee Invitations** with the Agoric Names boardID
   - copy an invitation board id; **claim**
     - issue: the invitations should go via the wallet (#3901)
     - but before we fix that: the board should be elected by stake weight voting (#3192)
 - propose to add collateral
   - `agoric deploy contract/deploy.js api/deploy.js` in the fungible faucet dapp to get a new issuer and its board id
   - **Propose New Collateral** with the `chainTimerService`, issuer, and duration
 - vote x4
 - see that the vote passed (though in an error message from the demo UI)
 - see that the treasury added the issuer as a form of collateral
   - `getCollaterals()` via the public facet of the treasury instance from agoricNames threw `Error#3: brandIn not found: "[Alleged: Tokens brand]"` because a prerequisite in the AMM or priceAuthority wasn't set up.

versions used:
  - agoric-sdk 0408b5469c616
  - [gov-demo](https://github.com/agoric-labs/gov-demo1) b6e8e4f
  - dapp-fungible-faucet a723a99219 (via `agoric init`)

_a recording is available internally_
