### ISSUE TITLE
amount (Amount typo) masks typing problems in contractSupport importers

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#3914]
Fixing this typo exposes dozens of places where `moola(10)` should be `moola(10n)` in tests.

https://github.com/Agoric/agoric-sdk/blob/fc84ee045631c1722b24bca7a2d8b3fc3c25f77b/packages/zoe/src/contractSupport/types.js#L146-L158

cc @katelynsills @Chris-Hibbert

**Comment by Tartuffo** [comment]
@dckc Please close if done.

**Comment by dckc** [comment]
the problem is still there:
https://github.com/Agoric/agoric-sdk/blob/8a6875f40025c2e6f3d7184f687ce81a2c611e51/packages/zoe/src/contractSupport/types.js#L149

**Comment by dckc** [comment]
looks like the tests got cleaned up in #3892
