### ISSUE TITLE
store.get throws on not found: same name as Map.get but different semantics

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#3917]
In a review of an AMM contract (#3791) I wondered why `tsc` doesn't complain about the case where `getPool()` returns `undefined`, but I see that `store.get()` throws on key not found.

https://github.com/Agoric/agoric-sdk/blob/aa2394b2f955a28116f6da38eddae2f707086a64/packages/store/src/types.js#L28-L29

The standard js [Map.get](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/get) returns `undefined` on key not found. Is it wise to use the same name with different semantics?

I see that we use `init` as distinct from `set` to mean "throw if it's already there."

for reference, `swing-store` also returns undefined on not found:

https://github.com/Agoric/agoric-sdk/blob/aa2394b2f955a28116f6da38eddae2f707086a64/packages/swing-store/src/swingStore.js#L35

**Comment by FUDCo** [comment]
This is @erights' preferred semantics for store.  I like the `Map` semantics better, but it's his call.

**Comment by erights** [comment]
While I agree that @dckc and @FUDCo make a good point, on balance I like the current store semantics better. The semantics are strongly analogous, making the learning burden much lower. The differential typescript experience does make the case stronger, but IMO it was already strong enough. It is a judgement call, but that the way I'm calling it. Closing.

If new arguments appear, please reopen.
