### ISSUE TITLE
Investigate testing React apps with ses enabled

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#3918]
## What is the Problem Being Solved?

Jest is the default testing environment for `create-react-app`, but it does not work out of the box with ses. When calling lockdown, the following error occurs: 
```
Unexpected intrinsic intrinsics.ArrayBuffer.__proto__ at %FunctionPrototype%
```
(context: https://github.com/Agoric/agoric-sdk/commit/2abb793a9444a105409f896e19989a33bd24ea6a)

## Description of the Design

Ava is the more supported testing environment for ses, so we should attempt to switch a fresh `create-react-app` to use Ava instead of Jest and document the complexity of such work. If this works, there will at least be a way to write unit tests for react apps that use ses. Then, take a deeper dive into Jest to figure out where it's breaking, and perhaps open an issue for that.

## Acceptance Criteria

Establish a working pattern for writing react tests in ses (in either Ava or Jest). If Jest is not supported, decide on the priority and feasibility of implementing support for it.

**Comment by dckc** [comment]
@rowgraus , @katelynsills suggested we get your input on this as a product feature.

**Comment by samsiegart** [comment]
I tried getting Ava to work. I was able to call `lockdown` with no problems. However, I ran into issues with ES6 module imports from dependencies. There is probably some way to resolve these using webpack/babel, but it requires `eject`ing the `create-react-app` and comes with a lot of configuration overhead (assuming you can get it to work).

After talking to @michaelfig we agreed that Jest would be the more preferred testing framework, and unit testing components doesn't necessarily require locking down the environment. I was able to mock out all the ses-related dependencies (like `eventual-send`) in a reasonably convenient way and get some unit tests written with `jest`/`enzyme` in https://github.com/Agoric/agoric-sdk/pull/3922.

Perhaps we still want to investigate getting lockdown to work, but I don't see it as a hard requirement for unit testing, maybe integration-level tests if we need those at some point.

**Comment by erights** [comment]
The error above could only have been thrown from 

https://github.com/endojs/endo/blob/1ee0a1f46f549710aa6ab1bb5c9f6af7f52c89d2/packages/ses/src/whitelist-intrinsics.js#L119

The only way this could happen is if, before `lockdown`, something had modified the `ArrayBuffer` constructor to inherit from something other than the original `Function.prototype`. Worth investigating! This is a weird thing to modify.

**Comment by samsiegart** [comment]
Looking into the jest code, this might be related: https://github.com/facebook/jest/blob/8c35c4d5581d0a27952851fb94723dc73842c97a/packages/jest-environment-node/src/index.ts#L42

And also this issue might be similar https://github.com/facebook/jest/issues/3186

**Comment by michaelfig** [comment]
> The only way this could happen is if, before `lockdown`, something had modified the `ArrayBuffer` constructor to inherit from something other than the original `Function.prototype`. Worth investigating! This is a weird thing to modify.

When I was trying to move my `tame-metering` changes after importing `ses` (so that I could use `assert` in them), I got a similar error during `lockdown`.  Would it be possible to add a `lockdown` option to tolerate this behaviour?

I know we have to do more work to support vetted shims in general; this seems related.

**Comment by erights** [comment]
Possibly. I'd like to first understand better what the behavior is. If we try locking down first, then we might get a good diagnostic failure when something tries and fails to modify ArrayBuffer. Can we try that?

**Comment by samsiegart** [comment]
I was able to run `lockdown` in a script before loading and running `jest`. When `jest` runs, it shows:
```
 FAIL  src/App.test.js
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'constructor' of object '[object Object]'
```

Unfortunately, I can't see where in the jest code this error is being thrown from (haven't been able to get `--verbose` or anything similar to show a stack trace). I'll keep looking.

**Comment by samsiegart** [comment]
I uploaded the code I was testing with to a repo here https://github.com/samsiegart/jest-ses

**Comment by samsiegart** [comment]
Opened https://github.com/facebook/jest/issues/11952 to see if the Jest team can offer any help

**Comment by samsiegart** [comment]
Closing because we've been able to write unit tests with vitest and e2e tests with agoric/synpress with ses enabled
