### ISSUE TITLE
Withdraw fees from the user's `vbank` (Cosmos-level) RUN purse by default

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Agoric#3931]
## What is the Problem Being Solved?

Forcing the user to pay for Zoe fees from a separate purse than just their `vbank` (Cosmos) RUN purse is not very ergonomic.  This is especially so if other (SwingSet-level) RUN fees will need to be withdrawn directly from the Cosmos account.

## Description of the Design

It would be easiest to explain, and wouldn't require people to think as much about where their fees are being drawn from if the user's `home.zoe` facet was bound to their `vbank` RUN purse.  If a user wants to sequester some funds from their `vbank` RUN purse, they can easily do so by creating a new RUN purse and transferring their savings to it.

As discussed in a recent Zoe/ERTP meeting, @katelynsills and I came to an agreement that it may be worthwhile to allow Zoe fee purses to be any object supplied by the user.  That change would permit the `vbank` purse to be used as a Zoe fee purse.  Then, the user's `vbank` RUN purse would be set up to be the one that the user's Zoe fees are drawn from.

After performing this transition, we would revert the change made to several dapps deploy scripts (and loadgen) that hard-codes the `"Zoe fee purse"` petname and transfers some arbitrary amount of RUN to it to attempt to avoid overdraught failures when deploying contracts or using Zoe.

## Security Considerations

IIUC, Zoe only does `E(feePurse).withdraw(...)` and claims the resulting payment.  That should have good error behaviour, and shouldn't have any inherent interleaving hazards.

The code that does the withdrawal should be examined to ensure that it is defensively consistent if arbitrary user-specified Far objects are allowed instead of just purses created by Zoe.

## Test Plan

Try running dapp deployment scripts without the explicit "transfer to Zoe fee purse" feature, and ensure that everything using the ag-solo's Zoe still works and fees are properly deducted.

**Comment by katelynsills** [comment]
Thanks for making this! There were complications that were also discussed in the meeting, so I want to make sure that this isn't a "Todo" yet but rather something to still work through. But this issue is very helpful for explaining the situation and the potential easy solution. I'll add more information about the complications when I can.

**Comment by michaelfig** [comment]
I'm aware that the "work item" template is for work that may or may not be done.

> I'll add more information about the complications when I can.

Looking forward to it.  Resolving this somehow won't be on the critical path for cosmic-swingset until after #3752 is complete, so don't worry about timing.
