### ISSUE TITLE
Small Zoe/ERTP Tasks

### ISSUE THREAD

**Issue by katelynsills** [Agoric/Agoric#3959]
These are tasks which should be relatively easy to do, but which just take a little bit of time and context switching. Please tag @katelynsills as a reviewer.

**Comment by dckc** [comment]
IOU more precise issues or PRs, but on my mind based on experience with governance work:

 - `ERef<TimerService>` vs. `TimerService`
 - `E(zoe).startInstance()` could take an `ERef<Instance>`
 -- https://github.com/Agoric/agoric-sdk/issues/3802#issuecomment-94056711

**Comment by erights** [comment]
>  - `E(zoe).startInstance()` could take an `ERef<Instance>`

@dckc did you mean "an `ERef<installation>` ? It looks like it already does. Is this subproblem now fixed?

**Comment by dckc** [comment]
I suppose it is fixed. I'll be sure to verify it before closing #3802.
