### ISSUE TITLE
Testing for https://github.com/Agoric/agoric-sdk/pull/3736/

### ISSUE THREAD

**Issue by katelynsills** [Agoric/Agoric#3962]
@erights would like to prioritize https://github.com/Agoric/agoric-sdk/pull/3736/ so that it can be approved and merged within the next day or so. 

We need to do some basic manual testing of the dapps and wallet (these are unfortunately not fully covered by automated testing.)

The dapps that we need to test manually are:

- [x] dapp-card-store (Buy a card - @samsiegart)
- [x] dapp-treasury (Swap on the AMM, create a vault, adjust a vault, close a vault @samsiegart )
- [x] dapp-fungible-faucet (Get tokens from the faucet @samsiegart )
- [x] testnet-load-generator (@mhofman is on it)
- [x] dapp-nft-drop

The dapps we don't need to test because they are fully covered by automated tests and CI on agoric-sdk PRs are:
- documentation (full test coverage for snippets)
- dapp-otc (no frontend, full test coverage)

Dapps no longer supported or known to be broken
-  dapp-loan (no longer supported)
- dapp-token-economy (deleted in favor of the public dapp-treasury)
- dapp-simple-exchange (known to be broken)
- dapp-autoswap (known to be broken, see the AMM in dapp-treasury instead)
- dapp-oracle (known to be broken)
- dapp-pegasus (no ui or api yet, contract is in agoric-sdk)

**Comment by samsiegart** [comment]
Testing dapp-fungible-faucet: When pressing "mint fungible tokens", the Zoe invite is received in the wallet but the offer is not displayed. The following error is thrown in the backend:

```
2021-10-14T08:45:05.046Z web: 127.0.0.1:60012[17]: inbound error: Remotables must be explicitly declared: {"handled":"[Function handled]"} from {
  "type": "walletAddOffer",
  "data": {
    "dappContext": true,
    "id": 1634201097812,
    "invitationHandleBoardId": "794977354",
    "proposalTemplate": {
      "want": {
        "Token": {
          "pursePetname": [
            "FungibleFaucet",
            "Token"
          ],
          "value": 1000
        }
      }
    }
  },
  "dappOrigin": "http://127.0.0.1:3000",
  "meta": {
    "channelID": 17,
    "origin": "http://localhost:8000",
    "query": {
      "isQuery": true,
      "suggestedDappPetname": "FungibleFaucet"
    },
    "url": "/private/wallet-bridge",
    "date": 1634201104925
  }
}
```

I tried wrapping the object in a `Far` from the fungible faucet UI, but get an error the way I tried doing it:
```
cannot serialize Remotables with non-methods like "type" in {"type":"walletAddOffer","data":{"dappContext":true,"id":1634202350487,"invitationHandleBoardId":"1675202761","proposalTemplate":{"want":{"Token":{"pursePetname":["FungibleFaucet","Token"],"value":1000}}}}}
```
It seems like we're sending a lot of "non-methods", I'm not sure how to approach this.

**Comment by erights** [comment]
Do you have a method or function named "handled" anywhere? I don't see one in dapp-fungible-faucet on main or in agoric-sdk on master.

**Comment by erights** [comment]
It does not look like the object with {"type":...} is the problem.

**Comment by samsiegart** [comment]
> Do you have a method or function named "handled" anywhere? I don't see one in dapp-fungible-faucet on main or in agoric-sdk on master.

Right sorry, I just realized this is actually inside the wallet, trying to explicitly declare this as far now: https://github.com/Agoric/agoric-sdk/blob/master/packages/dapp-svelte-wallet/api/src/wallet.js#L458

**Comment by erights** [comment]
Yup, that's the one. Should be
```js
const actions = Far('actions', {
```
or whatever literal string you think would be descriptive here.

**Comment by erights** [comment]
That means we had an uncaught bug in agoric-sdk that your checking of a dapp caught. Thanks!

**Comment by samsiegart** [comment]
Got fungible faucet working with https://github.com/Agoric/agoric-sdk/pull/3977

**Comment by samsiegart** [comment]
I discovered https://github.com/Agoric/agoric-sdk/issues/3982 while testing which is unrelated, but other than that all dapps are working now.

**Comment by erights** [comment]
#3736 is merged. Does that mean we can close this issue?

**Comment by samsiegart** [comment]
> #3736 is merged. Does that mean we can close this issue?

If testnet-load-generator works then yes

**Comment by katelynsills** [comment]
Let's wait to close this until we confirm that the testnet-loadgen works

**Comment by mhofman** [comment]
Oh I thought I had reported it does work
