### ISSUE TITLE
Remove getBootstrapPayment() from Treasury

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4021]
## What is the Problem Being Solved?

The Treasury has a method `getBootstrapPayment()` designed to provide RUN for the vbank at startup. It won't be needed once we have access to pre-existing RUN at chain startup.

## Description of the Design

Remove the method and anything that refers to bootstrapPayment. There's a test, and code in `install-on-chain` and `vats/src/bootstrap.js`.

## Security Considerations

It will be hard to convince reviewers and ourselves that there is nothing else using this functionality.

## Test Plan

Not needed once the code is gone.

**Comment by Tartuffo** [comment]
@Chris-Hibbert After various meetings, this ended up with a MN-1 tag *AND* in the Product Backlog pipeline (not MN-1 Backlog).  Please modify appropriately for what it should actually be.

**Comment by dckc** [comment]
This came up while working on #4165 ; the plan @michaelfig and I came up with is: make a single-purpose `centralSupply` contract that just mints the initial central supply based on `supplyCoins` from genesis and deposits it using the `bankManager`.

initial draft: 4c55bca0d34c07d9515d29577ff6047e02d90e15, bb83419a48bf5fe9373d609e7ce9466bafe70481
