### ISSUE TITLE
struggling to launch validator due to lack of peers, seeds

### ISSUE THREAD

**Issue by iammelea** [Agoric/Agoric#4030]
After following the instructions for mainnet, the node is unusable, does not connect with any peer after few restarts and more 24 hours ago trying, and also does not do a constant search of peers to connect. After having participated and configured the previous testnets without problems, it is clear that this software does not work correctly for p2p

Also I find it sad that launching a mainnet network is done without the proper persistent peers and no seeds. This will only result in a centralized network with few nodes and poor coverage.

At the moment I cannot configure the validator due to this problem, despite this Im oke.

I can see in discord that the problem has been raised, but there are no answers for the dev team, so I will open this issue to record.

**Comment by dckc** [comment]
I recommend you reach out to your peers in the validator community for seed nodes and peer addresses. See, for example, [a message at 9:29 Chicago time today in #validators](https://discord.com/channels/585576150827532298/755164695849205942/905826103199928331).

The [65 active validators](https://main.explorer.agoric.net/) demonstrate that the software works in at least some cases. If you have a reproducible failure mode, feel free to elaborate, following our [bug report template](https://github.com/Agoric/agoric-sdk/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by dckc** [comment]
I heard from a cosmos expert:

> the problems with P2P come mostly from the default incoming peers is 40
> and really it should be more like 300
