### ISSUE TITLE
SwingSet kernel: retireImports dispatch does not have any effect on liveSlots 

### ISSUE THREAD

**Issue by danwt** [Agoric/Agoric#4043]
_Surfaced from @informalsystems audit of Agoric/agoric-sdk/SwingSet at hash 774cb6ad306395e261027a1869cc3ea9db451823_

# Description

The [liveSlots](https://github.com/Agoric/agoric-sdk/blob/774cb6ad306395e261027a1869cc3ea9db451823/packages/SwingSet/src/kernel/liveSlots.js) code that handles the dispatch:

```javascript
  function retireImports(vrefs) {
    assert(Array.isArray(vrefs));
    vrefs.map(vref => insistVatType('object', vref));
    vrefs.map(vref => assert(!parseVatSlot(vref).allocatedByVat));
    // console.log(`-- liveSlots ignoring retireImports ${vrefs.join(',')}`);
  }
```

The code does does implement any feature of the garbage collection protocol. The lack of action taken here indicates some slack in the garbage collector protocol.

## Recommendation

Change this code to either take some action in the liveSlots, or remove the `retireImports` dispatch call entirely and design a new mechanism by which vats can clear dead weakrefs that are no longer valuable.

**Comment by warner** [comment]
The "virtual reference manager" now has work to do during `retireImports`:

```js
  function retireImports(vrefs) {
    assert(Array.isArray(vrefs));
    vrefs.map(vref => insistVatType('object', vref));
    vrefs.map(vref => assert(!parseVatSlot(vref).allocatedByVat));
    vrefs.forEach(vrm.ceaseRecognition);
  }
```

If this importing vat had previously stashed a recognizer for the imported object, e.g.  `const wm = new WeakMap(); wmset(obj, stuff)`, but didn't maintain reachability of the object (`delete obj` or it just falls out of scope), then when nothing else keeps the object alive, the exporting vat uses `retireImports` to signal this importing vat that it can get rid of the storage for `stuff` (and anything that might be kept alive by `stuff`).

This didn't matter until we had virtual object -keyed collections, where entries could be weakly keyed but need code to run to release the storage for the values. We implemented this after the audit completed.
