### ISSUE TITLE
Protobuf utilities in golang/cosmos are broken

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#4063]
## Describe the bug

The protobuf related `make` targets in `golang/cosmos` are in various states of broken.

In no particular order:

- `make proto-lint` complains about a missing `gogo.proto`, despite the fact that it's in `third_party`
- the `protoc-gen-grpc-gateway` tools must be installed manually (undocumented)
- `make proto-gen` does not work
- several other issues

## To Reproduce
See above

## Expected behavior
The `make` targets should download the files and tools as necessary to work.

## Platform Environment
MacOS

**Comment by dckc** [comment]
blocking #3991 , I heard @JimLarson say
