### ISSUE TITLE
Validate Zoe inputs

### ISSUE THREAD

**Issue by katelynsills** [Agoric/Agoric#4068]
## What is the Problem Being Solved?

Zoe and contracts need a thorough analysis of whether user-provided inputs are being adequately validated. 

## Description of the Design

See https://github.com/Agoric/agoric-sdk/blob/master/packages/ERTP/docs/INPUT_VALIDATION.md for a walkthrough of the methodology needed. ERTP has been already done.

## Security Considerations

Without this, there may be vulnerabilities in Zoe and Zoe contracts due to inadequate input validation.

## Test Plan
Add additional tests with malicious or malformed inputs.

**Comment by Tartuffo** [comment]
@erights Please assign an estimate for this ticket.

**Comment by Tartuffo** [comment]
This should be considered in Restival. 
The time estimate is for the consideration by Restival, NOT to implement this fully in Zoe.

**Comment by Tartuffo** [comment]
This still needs examined adversarially.  Assigning to Jessy to make that happen.

**Comment by Tartuffo** [comment]
This is outdated, replaced by #5955
