### ISSUE TITLE
"agoric": executable file not found due to outdated docker image

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4072]
## Describe the bug

A user reports following https://github.com/Agoric/agoric-sdk/wiki/Setting-up-an-Agoric-Dapp-Client-with-docker-compose up to `docker-compose exec ag-solo agoric open --repl` and getting:

```
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "agoric": executable file not found in $PATH: unknown
```

## To Reproduce

I'm not sure; I'm not able to reproduce the problem. I suspect it's an interaction with windows.

## Expected behavior
a URL to open the wallet is printed

## Platform Environment

I'm not sure about these:

 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

**Comment by mhofman** [comment]
Will try to repro on my machine.
The steps work fine for me in Docker desktop backed by WSL2. I do not have a non WSL docker environment so I cannot verify there.

**Comment by jmche** [comment]
Linux jamesChe 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Docker version 20.10.10, build b485636
docker-compose version 1.25.4, build 8d51620a
nodev10.13.0
npm6.4.1
agoric/cosmic-swingset-solo   2.14.0

**Comment by mhofman** [comment]
We figured that was because of an outdated `docker-compose.yml` file found in https://github.com/Agoric/agoric-sdk/blob/master/docker/docker-compose.yml

**Comment by michaelfig** [comment]
I updated the [Quick start](https://github.com/Agoric/agoric-sdk/wiki/Setting-up-an-Agoric-Dapp-Client-with-docker-compose#quick-start-overview) to say explicitly to download the correct docker-compose.yml.  That should help avoid these problems.

**Comment by dckc** [comment]
I updated the title now that we have a diagnosis.
