### ISSUE TITLE
Getting type error on deploy step on Starting A Project Sample On Site

### ISSUE THREAD

**Issue by schnetzlerjoe** [Agoric/Agoric#4078]
## Describe the bug
At contract deploy I am getting a type error:

schnetzlerjoe@penguin:~/demo$ agoric deploy ./contract/deploy.js ./api/deploy.js
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /home/schnetzlerjoe/demo/contract/deploy.js
agoric: deploy: Deploy script will run with Node.js ESM
agoric: (TypeError#1)
TypeError#1: Invalid URL: 

  at async WebSocket.<anonymous> (packages/agoric-cli/src/deploy.js:256:15)

## To Reproduce
1. Follow the instructions for the sample here: https://agoric.com/documentation/getting-started/start-a-project.html
2. On the deploy contract step:  agoric deploy ./contract/deploy.js ./api/deploy.js ---> I am getting an error: 
TypeError#1: Invalid URL: 

  at async WebSocket.<anonymous> (packages/agoric-cli/src/deploy.js:256:15)

## Platform Environment
 - Using Linux Debian (Pixelbook) with Node version v14.18.0
 - I am using Crostini built-in Linux, maybe that's why?
 - what version of the Agoric-SDK are you using? 0.13.19

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.
![Screenshot 2021-11-13 12 51 23 AM](https://user-images.githubusercontent.com/41382129/141609276-b613c879-5ed9-41ed-b44b-927309edb126.png)

**Comment by schnetzlerjoe** [comment]
Figured this out. For anyone getting this error. It was due to a hangup on the default port 8000. Make sure you have that port open and ready to go.

**Comment by dckc** [comment]
someone else reported similar symptoms;  I tried to reproduce it, but without luck.

Until we have more clear info on how to reproduce this, I'm closing it.
