### ISSUE TITLE
Wallet fails to deposit non-live payment

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4087]
## Describe the bug

When I try to adjust balances with the treasury app, the wallet seems to receive a non-payment. It can't deposit, and leaves gadgets on screen that take up space uselessly.

## To Reproduce

1. Bring up the treasury and wallet.
2. Take out a loan
3. attempt to adjust the balance. Every combination of settings has resulted in the same response
4. After approving the transaction in the wallet, the transaction goes through.  Several payment widgets are displayed; most are automatically processed. At the end one (in addition to whatever was there before) remains.
Neither of the buttons (`Refresh`, `Deposit`) does anything useful

## Expected behavior

If there are unusable or empty payments received as a result of the transaction, the wallet should detect them and make them go away. If it tries to deposit something and fails, it shouldn't leave a reminder on the home wallet page.

## Platform Environment
 - MacOS 12. Node  v14.17.0
 - is there anything special/unusual about your platform?   **No**
 - what version of the Agoric-SDK are you using? **@agoric/sdk@10.0.2-150-g6412c2883**

## Additional context

none

## Screenshots

<img width="503" alt="Wallet-badPayment" src="https://user-images.githubusercontent.com/13372636/142067380-443521dc-a096-4f5a-bb17-467ee0cfe245.png">
.

**Comment by Chris-Hibbert** [comment]
The same thing happens with transactions with `Swap`.

**Comment by samsiegart** [comment]
This is the same root cause as https://github.com/Agoric/agoric-sdk/issues/3982. The react wallet won't display these failed payments, but we may want to clean them up from the backend somehow as well.

**Comment by Tartuffo** [comment]
Dup with #3982.
