### ISSUE TITLE
A Contract for posing Governance Questions

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4142]
## What is the Problem Being Solved?

The facet that allows one to pose new governance questions is returned when an Electorate is started. For contract governance, its returned when the governed contract is started. Currently, that happens in `bootstrap.js` for the VaultMaker and the AMM, but `bootstrap.js` doesn't make any use of it.

## Description of the Design

Allow stakeholders to put up some stake in order to get the ability to pose a question. `bootstrap.js` could then hand its poser facets to this contract, and the question creation contract could have a publicly accessible facet for creating new questions.

## Security Considerations

Resolves the issue of how the fundamental economic contracts can make changes to their parameters.  This contract would be part of governance, so it would need to be included in that security review.

## Test Plan

nothing special

**Comment by Chris-Hibbert** [comment]
At the Zoe meeting on 2022/4/27, we talked about how this should be managed for the contracts the Economic committee controls. A proposal was raised to create a contract that would hold the poser facet for the core contracts of our economy. It would allow proposal that match one of a few templates to be sent to a vote. We already have a start at a list of governed params that they might consider changing (*link?*). The ability to invoke the imminent ZCF API that allows some invitations to be blocked should also be include.

**Comment by dckc** [comment]
We deployed such a contract (from a pending PR, https://github.com/Agoric/agoric-sdk/pull/5257 ) to devnet yesterday.
https://devnet.explorer.agoric.net/proposals/5
End Voting Time 2 May 2022, 11:28:20pm UTC

**Comment by rowgraus** [comment]
@Tartuffo per conversation with @Chris-Hibbert we believe the existing contract referenced above is sufficient for Mainnet 1.  The result is that one member of the committee will have the ability to pose arbitrary governance questions (which may be malicious or dumb) to the econ committee, but the committee must approve any question for it to be implemented.

This issue, which would constrain the questions allowed, is a nice to have.  Moving to Mainnet 1.1 tag/release

**Comment by Chris-Hibbert** [comment]
We have two examples now:

 #6110 adds a charter for the PSM which plays this role for the PSM. 
#6089 added a charter for the broader econ committee.
