### ISSUE TITLE
PriceAuthority AMM wrapper to get prices without slippage

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4177]
## What is the Problem Being Solved?

The PriceAuthority produced by the AMM uses the amount offered in computing the current price, which means the quote is worse the more that is offered.

## Description of the Design

For purposes like choosing a liquidation trigger, the amount offered should be replaced with a constant. Possibly one unit of the collateral.

## Security Considerations

Not particularly relevant to security.

## Test Plan

Will probably impact some existing tests.

**Comment by zmanian** [comment]
Couldn't this trigger a premature liquidation?

**Comment by Chris-Hibbert** [comment]
The concern is that the current approach would trigger prematurely. If we change the prices coming from the oracle based on the AMM to not have slippage for higher quantities, we should liquidate less.

Since this will overestimate the amount we can get from the AMM, it's arguable that it will then liquidate later than it should, but people seem to agree that liquidation should be based on the price level rather than what the AMM would provide on a momentary basis.

If we go to a scheme that liquidates relatively slowly, it would give arbitrageurs more opportunity to correct the prices mid-liquidation. We've talked about this, but it hasn't risen to the level of a plan yet.

**Comment by Tartuffo** [comment]
@Chris-Hibbert After various meetings, this ended up with a MN-1 tag *AND* in the Product Backlog pipeline (not MN-1 Backlog).  Please modify appropriately for what it should actually be.

**Comment by Tartuffo** [comment]
If not using AMM for liquidation decision, then we don't need to do this.  Might need this for Open Loan (unless we use the chainlink price).

**Comment by Chris-Hibbert** [comment]
The AMM was removed in #7074
