### ISSUE TITLE
Vault periods should be static

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4185]
## What is the Problem Being Solved?

The periods for charging interest and for recording updates are currently governed separately for each collateral type. The values should be consistent across collateral, and could likely be set at chain start-up and not be allowed to change.

## Security Considerations

This moves some governed parameters around. If the periods are static, then they won't be visible through governance.

## Test Plan

drops some mutability, so tests should mostly get simplified.

**Comment by turadg** [comment]
Discussion in RUN meeting:
- it's important to have a way to tweak the periods if needed
- therefore it should be governed, but shared across all brands

@dckc has some ideas for how to implement

**Comment by dckc** [comment]
### governed parameter across all assets / brands

In some sense, the straightforward approach is to make this a governed parameter of the VaultFactory. But currently, all the governed parameters are delegated on a per-VaultManager basis. Maybe mixing delegated with un-delegated is easy/straightforward, but if it's not...

### creatorFacet method

One option is to have a method on the `creatorFacet` of `VaultFactory` for setting the period, and keep the `creatorFacet` in the bootstrap powers for use with big hammer governance (#4352 ).

the `creatorFacet` is returned at https://github.com/Agoric/agoric-sdk/blob/master/packages/run-protocol/bundles/install-on-chain.js#L335 but then dropped on the floor at https://github.com/Agoric/agoric-sdk/blob/master/packages/vats/src/core/econ-behaviors.js#L40 ; I expect to fix that as part of #4165 .
