### ISSUE TITLE
Write up security claims about VaultFactory

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4186]
## What is the Problem Being Solved?

We will want a security review of the VaultFactory that ensures 

## Description of the Design

* Operations on one vault MUST NOT impact any other vault
* User operations MUST affect at most one vault.
* Individual vaults MUST NOT escape from the aggregate collections of vaults.  

(these need to be rephrased)

## Security Considerations

It's all in service of security.

**Comment by Chris-Hibbert** [comment]
Having access to one Vault doesn't provide access to others.
If one collateral issuer fails (or has other problems) it won't affect Vaults dealing in other currencies.
Users of a vault can't tie the vault up to prevent the mechanism from continuing to charge interest.

**Comment by Tartuffo** [comment]
@dtribble @jessysaurusrex I'm marking this for Restival.  Chris will probably do it, time allowing.

**Comment by dtribble** [comment]
I have a description edit in progress

**Comment by Tartuffo** [comment]
@dtribble Can you please complete your edit of the description?
