### ISSUE TITLE
Collateral Reserve

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4188]
## What is the Problem Being Solved?

We need a mechanism to manage crypto assets to improve the economy's liquidity and stability.  Multiple streams of assets must be disbursed or managed in different ways. Here it is called it the PCV (protocol-controlled value) Exchange. It has been referred to in other places as "The RUN protocol".

## Description of the Design

A Zoe contract holds onto various assets, and supports governance mechanisms to direct it to disburse them in various ways.
The assets include
 * crypto assets, which might have been deposited directly or might be the result of other operations.
    . For now, there is no intent to track sources, or ascribe partial ownership to any party.
	. Most of these will be disbursed by using them to fund AMM pools.
 * BLD, which can be sold directly.
 * Liquidity tokens from funding AMM pools.
   . For now, the expectation is that the contract will hold onto these. Some future upgrade may enable redeeming them in some cases.

A book order exchange contract for the sale of BLD for various asset types
 * The contract's creator can offer BLD for sale at specified times, velocities, tranche sizes
 * At time of sale, will sell up to a limit to the best offers better than some floor.
 * proceeds go in the pools

A governance-controlled mechanism for withdrawing (non-BLD) assets from pools, minting RUN, and creating and funding new AMM pools

A separate governance-controlled mechanism for withdrawing assets from pools and funding existing AMM pools.
This would require work on the AMM to allow adding arbitrary an mix of RUN/collateral to a pool

## Security Considerations

* takes no action without governance direction
* Book Order exchange controlled by Zoe guarantees
* Need an upgrade mechanism, since this list of functionality isn't complete.
* All the components need to support governance-style legibility
* The contract's holdings must be visible.

## Test Plan

Extensive, but the specifics will be details with each component.

**Comment by Chris-Hibbert** [comment]
We (@rowgraus, @btulloh and I) had another discussion, and I now understand why the book order exchange isn't an early part of this design. selling BLD for collateral is a possible approach to bringing in collateral, but there are other plausible mechanisms including business transactions that would result in collateral being available. The end result of this thread is that what we need at this stage is a Collateral "Reserve" that can hold onto various types of collateral, and allow governance to direct it to various uses. The first use is adding liquidity to AMM pools.

The plan is to enhance the AMM's addLiquidity to allow the liquidity to be added at an arbitrary ratio so we don't have to be in a race to deposit collateral. Then the mechanism can add liquidity in a single step.

**Comment by rowgraus** [comment]
@Chris-Hibbert let's talk about options for limiting scope on this

**Comment by Tartuffo** [comment]
@dtribble @Chris-Hibbert Do we need to have this work in an automated  fashion for MN-1?  The description says use of the reserve is controlled by Governance.

**Comment by Tartuffo** [comment]
@dtribble's feedback:
There are two parts to the automation:

1. Charge shortfall against the reserve. That's the basic mechanism that must work for it to really be a reserve. 
2. Automatically acquire assets for the Reserve from liquidation. That's in the new liquidation contract. It might not be in the work item. I'll add a separate ticket for that.

This is out of scope for MN1:
3. mint new BLD to refill the reserve.
