### ISSUE TITLE
makeHandle() is exported by Zoe and used by governance; it should be moved to a more general location

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4230]
## What is the Problem Being Solved?

`makeHandle()` makes generic opaque handles. The governance package shouldn't get it from Zoe

## Description of the Design

It should be provided by something else in @agoric.  The existing plausible places are `far`, `marshall`, and `store`. None seems quite right. Anyone have other suggestions?

## Security Considerations

Just reducing unnecessary cross-dependencies between security critical packages.

## Test Plan

No change of behavior is contemplated. Existing testing should be sufficient.

**Comment by erights** [comment]
Done by https://github.com/Agoric/agoric-sdk/pull/1472
