### ISSUE TITLE
Mark/Stamp non-standard ERTP Issuers?

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4237]
## What is the Problem Being Solved?

Issuers built using ERTP `makeIssuerKit` mitigate [risks from bad issuers](https://github.com/Agoric/agoric-sdk/wiki/Limited-Risk-from-Bad-Issuers). We expect them to be by far the norm, so that any issuers created another way should be treated with extreme skepticism.

Our wallet probably could distinguish ERTP issuers from `makeIssuerKit` and guide users to be skeptical of others. It currently does not.

## Description of the Design

Perhaps add a [trademark](https://github.com/Agoric/SES/blob/0.5.0/src/old/ejectorsGuardsTrademarks.js) to all ERTP issuers.

## Security Considerations

This should improve security in the market.

## Test Plan

ideally, user testing to see if it helps users avoid bad issuers

cc @dtribble @rowgraus @mhofman @samsiegart

**Comment by erights** [comment]
> Perhaps add a [trademark](https://github.com/Agoric/SES/blob/0.5.0/src/old/ejectorsGuardsTrademarks.js) to all ERTP issuers.

If someone ports `ejectorsGuardsTrademarks.js` to a modern Hardened JS PR, I will happily review. If you're interested, please let me know.

**Comment by samsiegart** [comment]
It's probably more important that we highlight non-standard issuers, rather than marking standard issuers which should be the norm. Some sort of cautionary badge, perhaps with a help-tip that explains to the user the associated risks.

**Comment by dckc** [comment]
yes; the UX should be that non-standard issuers look weird.

As a design / implementation, I'm suggesting that standard issuers get marked in such a way that the wallet can distinguish them from non-standard issuers.

**Comment by erights** [comment]
"Standard" is a weird word to use in an ecosystem of mutually suspicious chains. Any particular trademark can at most certify the issuers from a given chain as being reliable. The meaning of that certification is bounded by your trust in that chain. IOW, if you trust that chain only to "degree" X, then you shouldn't trust its trademarks or issuers, or any contracts that run on it, any more than X.

I know we're not in that world yet. But we are building for that world. If we don't, we paint ourselves into a corner preventing us from getting there. That doesn't mean we cannot take shortcuts. But we should be explicit about it and have a plan for how to grow beyond the shortcut.

**Comment by Tartuffo** [comment]
We don't plan to do this.

**Comment by dckc** [comment]
If we don't plan to do it ever, let's label it **wontfix** and close it, please.

If it's just out of scope for mainnet 1, the lack of a milestone works. (and it doesn't hurt to note explicitly as you did).

**Comment by zarutian** [comment]
I agree with @erights that chain-wide mark/stamp of ERTP Issuers made/resident on that chain is something nice to have. But implemented at much later date if ever. Perhaps that chains Zoe service could provide the stamp verifier(/?guard?) via public method if this ever gets implemented.

**Comment by erights** [comment]
> If we don't plan to do it ever, let's label it wontfix and close it, please.

Closing
