### ISSUE TITLE
Better-partition browser tests

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#4242]
## What is the Problem Being Solved?

There are currently some tests that require a headless browser to run (https://github.com/Agoric/agoric-sdk/blob/master/packages/web-components/package.json#L11). The browser is not bundled into the sdk, so running the tests locally may fail if the user has not installed a headless browser on their machine. This failure should not block other tests in the sdk from running, but perhaps warn the user that they were skipped.

## Description of the Design

Change all testing scripts to check for a local chrome installation before running in non-CI mode, then log a warning and skip the tests if not found.

**Comment by mhofman** [comment]
I want to highlight that CI should be configured to force running the headless tests, and fail if a headless browser is not available. This is to derisk changes which would cause chrome based integration tests to no longer run automatically in CI.

**Comment by samsiegart** [comment]
I initially thought we could rely on checking `CHROME_PATH`, but it seems like this isn't sufficient, since it doesn't exist on my mac yet the test still is able to run. I think the simplest possible workaround is to use a flag/env variable set by the user when running the test, like `SKIP_BROWSER_TESTS`. We could also do the opposite and explicitly require the variable (unless in CI), but I think the default should be to try and run it.

**Comment by mhofman** [comment]
Another way would be to try to run it, and not report a failure if the env variable isn't set. But I'd much prefer in that case if we could differentiate the failure type. I need to look at the launcher logic again see if there isn't a better way.

**Comment by Tartuffo** [comment]
@samsiegart This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, wallet, zoe contract

**Comment by Tartuffo** [comment]
BTW, I just added "UI" as a covered label, so you can use that if appropriate.
