### ISSUE TITLE
Land "core bootstrap" behind a feature flag

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Agoric#4247]
## What is the Problem Being Solved?

refs: #4165

Land new "core bootstrap" behind feature flags so that we can incrementally improve the bootstrap process.

## Description of the Design

- [x] pass command-line arguments through the `agoric-cli`
  - [x] `agoric deploy api/deploy.js -- --my-option=foo other thing bar`
  - [ ] `agoric start -- --my-option=foo other thing bar`
- [ ] feature command-line options on `ag-solo init`
  - [ ] flag to customize or turn off wallet deployment (maybe `--wallet=disable`)
  - [ ] flag `--decentral-config=@agoric/vats/decentral-core-config.json` to enable new bootstrap
  - [x] remove KLUDGE commits from `bootstrap-core` branch
- [x] create a `bootstrap-core` PR
  - [ ] document how to enable it with `agoric start -- --decentral-config=@agoric/vats/decentral-core-config.json --wallet=disable`
  - [ ] write a shortcut flag for that like `agoric start --bootstrap-core`

## Test Plan

Run CI to ensure nothing existing breaks, create a `--bootstrap-core` CI integration test to sniff that some new feature is enabled.

**Comment by dckc** [comment]
I see usage turned out a little different:

```
CHAIN_BOOTSTRAP_VAT_CONFIG=@agoric/vats/decentral-core-config.json agoric start --reset
```

**Comment by dckc** [comment]
@Tartuffo  was about to estimate this at 8 chunks, but all but 1 or 2 of those were before Jan 19 (going back to Dec 8 2be2939dc). The 2 estimate here reflects just work since Jan 19.
