### ISSUE TITLE
Atomically adjust pool ratio and add liquidity

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4249]
## What is the Problem Being Solved?

When the RUN Protocol wants to add liquidity, the pool's ratio may not match the intended price.

## Description of the Design

Add an API to the AMM that allows adding liquidity at a stated ratio. Presumably, this will take the ratio of the of the offered collaterals and trade with the pool to match that ratio, then take the remaining amounts in give and add them as liquidity.

I haven't been able to find a way to calculate the trade values that adjusts for the impact of the fees, but it looks like that doesn't make a big difference, so I expect to ignore that effect.

## Security Considerations

Handling this in a single call means that no other transaction will interfere. It's necessary to do a trade with fees, because the alternative would allow ostensible liquidity providers to trade without paying complete fees.

## Test Plan

Verify that the resulting pool balance is close to the ratio offered by the liquidity provider.

**Comment by Tartuffo** [comment]
How is this different from #4200?

**Comment by Chris-Hibbert** [comment]
#4200 was a previous approach. This supersedes it.
