### ISSUE TITLE
Make the wallet support getRUN / BLD Boost

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#4263]
## What is the Problem Being Solved?

For the `getRUN` protocol, dapps (e.g. the treasury) need to be able to propose offers for the wallet to lock and unlock various amounts of BLD, and borrow/repay various amounts of RUN. The problem is that with `getRUN`, the wallet needs to get an attestation for the `give` amount in the offers ([ref](https://github.com/Agoric/agoric-sdk/blob/dc-run-loc/packages/treasury/test/test-runLoC.js#L258)). Also, the BLD purse cannot be selected since it always must be the virtual BLD purse that can contain locked tokens. Due to these differences from a regular offer proposal, the wallet needs a way to know when to handle this separate case.

## Description of the Design

Add a new method to the [wallet bridge API](https://agoric.com/documentation/guides/wallet/api.html#walletbridge-api-commands) called `addGetRUNProposal` that takes a give/want amount of BLD/RUN. It should show an offer in the UI similar to regular offers, but when accepted it should get an attestation and do all of the required steps for `getRUN` (see ref above).

Note this doesn't include the other backend work required to support `makeAttestations` from the wallet, just the API that the dapps will use.

## Security Considerations

The UI should make it clear that tokens are being locked rather than "given" to the contract. It should also reflect the locked amount in the purse.

## Test Plan

Unit testing and e2e testing with the treasury dapp

**Comment by samsiegart** [comment]
I'm trying to decide if it's too clunky to bake this into the wallet API so explicitly, but I'm leaning towards not because it is after all a unique concept that's built into the chain.

**Comment by samsiegart** [comment]
cc @michaelfig @dckc

**Comment by dckc** [comment]
> Add a new method to the wallet bridge API called addGetRUNProposal that takes a give/want amount of BLD/RUN.

I suggest rather than a new method, the wallet uses the existing add API to add a proposal and uses this special code path in case the issuer is the attestation issuer.

**Comment by samsiegart** [comment]
> I suggest rather than a new method, the wallet uses the existing add API to add a proposal and uses this special code path in case the issuer is the attestation issuer.

How would the dapp get the attestation issuer/amount? I wasn't sure if the attestation was a step we'd want to abstract away from the dapps, since it seemed like it was subject to change.

**Comment by dckc** [comment]
The relevant issuer ("attestation" is a name that is unlikely to survive much longer) should be well known. Dapps get it from the board or agoriNames at deploy time or whatever  as usual.

**Comment by samsiegart** [comment]
> The relevant issuer ("attestation" is a name that is unlikely to survive much longer) should be well known.

Oh okay, I wasn't sure if the attestation issuer would be different between each wallet. It's just that each wallet has its own instance of `attMaker`, but they all use the same issuer then, is that correct?

**Comment by dckc** [comment]
yes, different instances of `attMaker` for each wallet, same issuer.

**Comment by dckc** [comment]
@samsiegart The `getRUN` branch (5662cbe15) should be set up to provide `attMaker` and such...

```
command[1] home.attMaker
history[1] [Object Alleged: attMaker]{}

command[2] E(home.agoricNames).lookup('instance', 'getRUN')
history[2] [Object Alleged: InstanceHandle]{}
```

I added a `getAttMaker` API to the wallet admin facet. Currently it requires the user to pass their attMaker from home to their walletAdminFacet:

```
command[4] E(home.wallet).getAdminFacet()
history[4] [Object Alleged: adminFacet]{}
command[5] wa = history[4]

command[6] E(wa).resolveAttMaker(home.attMaker)

command[7] E(wa).getAttMaker()
history[7] [Object Alleged: attMaker]{}
```

## Getting Started

0. `yarn && yarn build` as usual in `agoric-sdk`; then `cd; agoric init dapp-boot` (or whatever name you like)
1. start the local-solo:

```
dapp-boot$ CHAIN_BOOTSTRAP_VAT_CONFIG=@agoric/vats/decentral-demo-config.json \
  agoric start local-chain --reset -v \
  >,local.log 2>&1 &
dapp-boot$ less -R ,local.log
```

2. start the local-chain:

```
dapp-boot$ agoric start local-solo --reset -v >,solo.log 2>&1 &
```

3. open the REPL

```
dapp-boot$ agoric open --repl
```

Then, in this REPL, you should be able to see `attMaker` and such as above.

**Comment by dckc** [comment]
@samsiegart tells me:
> 32fdd23ebbfe is the agoric-sdk branch/commit for supporting getAccountState and attestation payments

That was after we tried the UI with the runStake on devnet and got:

```
×
Unhandled Rejection (TypeError): target has no method "getAccountState", has ["addOffer","getAgoricNames","getBoard","getBrandPetnames","getDepositFacetId","getIssuersNotifier","getNamesByAddress","getOffersNotifier","getPursesNotifier","getUINotifier","getZoe","suggestInstallation","suggestInstance","suggestIssuer"]
```

![image](https://user-images.githubusercontent.com/150986/162253695-8e20b1fe-1076-46d9-8c36-810214eb953f.png)

**Comment by dckc** [comment]
progress!

```
AG_SOLO_BASEDIR=/tmp/solo8 ./bin/ag-solo setup --netconfig=${NETCONFIG_URL:-https://devnet.agoric.net/network-config}
```

next challenge:

```
2022-04-07T20:48:21.099Z chain-cosmos-sdk: delivering to chain (trips=1) 716b105b188536259569d025ff2ba9d1c007d9d3e4f7b189c1547f692d357ca9 [
  [
    65,
    '65:55:deliver:ro+58021:lookup:rp-102;["uiConfig","VaultFactory"]'
  ]
] 55
```

**Comment by dckc** [comment]
I just heard @samsiegart say he has the ball on this.

cc @Tartuffo

**Comment by dckc** [comment]
small tweak to wallet stuff...

```patch
diff --git a/packages/wallet/api/src/lib-wallet.js b/packages/wallet/api/src/lib-wallet.js
index ffb9d55c9..efc7e71a4 100644
--- a/packages/wallet/api/src/lib-wallet.js
+++ b/packages/wallet/api/src/lib-wallet.js
@@ -572,7 +572,7 @@ export function makeWallet({
     // We now have everything we need to provide Zoe, so do the actual withdrawals.
     // Payments are made for the keywords in proposal.give.
     const keywordPaymentPs = Object.entries(proposal.give || harden({})).map(
-      async ([keyword, { amount, type }]) => {
+      async ([keyword, { type, ...amount }]) => {
         const purse = purseKeywordRecord[keyword];
         assert(
           purse !== undefined,
@@ -602,7 +602,7 @@ export function makeWallet({
     // Get Attestation-branded amounts for Attestastation "wants".
     await Promise.all(
       Object.entries(proposal.want || harden({})).map(
-        async ([keyword, { amount, type }]) => {
+        async ([keyword, { type, ...amount }]) => {
           console.log('TYPE', type);
           if (type === 'Attestation') {
             const attestationAmount = await makeAttestationAmount(amount);
@@ -697,7 +697,7 @@ export function makeWallet({
 
     // Convert gives'/wants' BLD amounts to Attestation amounts for
     // Attestations.
-    const convertToAttestationAmounts = ([keyword, { amount, type }]) => {
+    const convertToAttestationAmounts = ([keyword, { type, ...amount }]) => {
       if (type === 'Attestation') {
         amount = keywordToAttestation.get(keyword);
       }
@@ -959,11 +959,7 @@ export function makeWallet({
             const purse = getPurse(pursePetname);
             purseKeywordRecord[keyword] = purse;
             const brand = purseToBrand.get(purse);
-            const amount = {
-              brand,
-              value,
-            };
-            return [keyword, { amount, type }];
+            return [keyword, { brand, value, type }];
           },
         ),
       );
```

**Comment by dckc** [comment]
@michaelfig had a suggestion that got consensus in today's meeting:
 - home gets a new walletNotifier property
 - the attestation maker gets relayed to the wallet via this new walletNotifier

**Comment by dckc** [comment]
In discussion with @michaelfig we figured out that the design above involves no changes to the chain platform:

 - adding the notifier to home is something that can be done while adding `home.attMaker` in deployment of `runStake`
 - wallet changes to consume the notifier live in ag-solo, not on chain
