### ISSUE TITLE
Creating a new fungible asset with lots of `decimalPlaces` breaks the wallet UI after adding the Dapp

### ISSUE THREAD

**Issue by b4d2** [Agoric/Agoric#4272]
## Describe the bug

Following the steps of creating a Dapp per the steps at https://agoric.com/documentation/getting-started/start-a-project.html#initialize-demo-from-dapp-template, with a modified contract that creates a zcfMint with an extremely large amount of decimal places, results in a wallet UI crash after adding the Dapp to the wallet.

```js
  const zcfMint = await zcf.makeZCFMint("A", AssetKind.NAT, harden({ decimalPlaces: 999999999999999999999999 }));
```

## To Reproduce
1. Follow the Dapp hello world example, however replace the zcfMint definition with the one above
2. Deploy the contract (`agoric deploy ./contract/deploy.js ./api/deploy.js`)
3. Open the Dapp in a tab
4. Open the Wallet ui (`open -a "Google Chrome" $(agoric open --no-browser | grep http)`)
5. Accept the Dapp invitation
6. Shortly thereafter, the wallet will become unusable and only render a white page when attempting to view the dashboard.  Note that this behavior persists even after removing the Dapp from the wallet, as there is most likely a zero balance of the Asset still being displayed

## Expected behavior
No matter how poorly a Dapp is written, it should not be able to adversely affect the wallet UI 

## Platform Environment
 - what OS are you using? what version of Node.js?
 macOS 12.1, node v16.13.1
 - is there anything special/unusual about your platform?
 I only have 16gb of ram which may affect max string sizes?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
`72cc8d6bcf428596653593708959446fb0a29596`

## Additional Notes
While this can be immediately fixed in the wallet UI with a safety, it is also worthwhile to investigate if this value should have a limit within the context of zcf

## Screenshots
<img width="685" alt="Screen Shot 2022-01-10 at 7 33 18 PM" src="https://user-images.githubusercontent.com/96506545/148878092-f995d2b6-dcad-4d99-9057-c0b20be81e0c.png">
<img width="437" alt="Screen Shot 2022-01-10 at 7 33 00 PM" src="https://user-images.githubusercontent.com/96506545/148877876-f967174d-7643-4e04-9787-8a9f952d6e00.png">
<img width="590" alt="Screen Shot 2022-01-10 at 7 33 34 PM" src="https://user-images.githubusercontent.com/96506545/148877886-b9b32736-2ed0-4087-b67d-c4bc602d4675.png">
<img width="1024" alt="Screen Shot 2022-01-10 at 7 40 19 PM" src="https://user-images.githubusercontent.com/96506545/148877927-572af28e-3b5e-48ac-b2a8-29c550af6eee.png">

**Comment by samsiegart** [comment]
Thanks for reporting this. It is a good question on whether to protect against this in zcf, and what a good threshold would be for a safety in the UI. I think either way we should put some limit in the UI, though I'm not sure if there's some valid use cases that could need a lot of decimals. Perhaps we could use scientific notation to represent such numbers.

There's probably a few other ways a bad dapp could mess up the UI, such as spamming a large number of transactions/offers, or proposing an offer with a lot of data, but in any case the UI shouldn't break even if the user approves a bad dapp.

**Comment by michaelfig** [comment]
> I'm not sure if there's some valid use cases that could need a lot of decimals.

~~1000~~ ~~200~~ 100 decimals should be enough for anybody.  Ethereum has a limit of 77 (the 78th significant decimal place can only be 0 or 1):

```js
`${2n ** 256n}`.length === 78
`${2n ** 256n}`[0] === '1'
```

**Comment by michaelfig** [comment]
> > I'm not sure if there's some valid use cases that could need a lot of decimals.
> Ethereum has a limit of 77

I should retract this statement, as things are a bit more subtle.  `decimalPlaces` is just for display info, not a limit on Nat values (which Ethereum does have).
