### ISSUE TITLE
explorer doesn't detect changes to the identity after initial creation

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4274]
## Describe the bug

@michaelfig writes [Nov 7: in #validators](https://discord.com/channels/585576150827532298/755164695849205942/907089146366009444)
> This appears to be a bug in the version of big-dipper we're using; it doesn't detect changes to the identity after initial creation.  If you added your identity with edit-validator then this may have happened to you.

## To Reproduce

_not entirely clear to me_

## Expected behavior

Validators can change their identity / icon using [`agd tx staking edit-validator`](https://hub.cosmos.network/main/validators/validator-setup.html#edit-validator-description).

## Additional context

_This is most likely an upstream bug, but the [devnet explorer](https://devnet.explorer.agoric.net/) is part of the Agoric Software Development Kit inasmuch as it helps our validators and developers test and train._

**Comment by dckc** [comment]
Plans for hosting the explorer are in transition; we should know more by the end of January.

**Comment by michaelfig** [comment]
I would assert that this is not an MN-1 blocker.  Upgrading the explorer for testnets is laudable, but we will be using the new [bigdipper-v2](https://github.com/forbole/big-dipper-2.0-cosmos) in production.  If it turns out to have this same problem, we can address it then.

I've sent a query to Forbole to see if BD2 has the same problem.

**Comment by michaelfig** [comment]
> I've sent a query to Forbole to see if BD2 has the same problem.

According to Kwun Yeung, it should not be a problem with BD2.  Closing this issue (but feel free to open a new one if there are problems with BD2).
