### ISSUE TITLE
Method `home.vaultFactoryCreator.addVaultType` modifies state of the service even when being called with invalid arguments

### ISSUE THREAD

**Issue by b4d2** [Agoric/Agoric#4284]
## Describe the bug

The method `home.vaultFactoryCreator.addVaultType` modifies state of the service even when being called with invalid arguments.  

## To Reproduce
1. in simulator
1. tap the faucet `history[0] = E(home.faucet).tapFaucet()`
2. Add vault type with already registered issuer, which will fail since the issuer is already added to the vault
```js
E(home.vaultFactoryCreator).addVaultType(history[0][0]["issuer"], "AAAAAAAAAAAAAAAAA", null)
```
2. attempt to add the vault type again, and observe that the keyword is saved and is no longer unique, despite the .addVaultType call above failing
```js
E(home.vaultFactoryCreator).addVaultType(history[0][0]["issuer"], "AAAAAAAAAAAAAAAAA", null)
```

## Expected behavior
With invalid arguments, the addVaultType method should not modify any service state (leak)

## Platform Environment
 - what OS are you using? what version of Node.js?
 macOS 12.1, node v16.13.1
 - is there anything special/unusual about your platform?
 I only have 16gb of ram
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
`72cc8d6bcf428596653593708959446fb0a29596`

ref #4264

**Comment by Tartuffo** [comment]
@dtribble This does not have an area label that is covered by our weekly tech / planning meetings, so it will likely fall through the cracks for planning for MN-1. Can you please assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, ui, wallet, zoe, zoe contract

**Comment by Tartuffo** [comment]
@dtribble Bump.  For proper project planning and tracking, this needs an area label covered by one of our weekly planning meetings.  Please pick the appropriate one from: agd, agoric-cli, agoric-cosmos, amm, core economy, cosmic-swingset, endo, ertp, getrun, governance, installation-bundling, metering, oracle, pegasus, run-protocol, ses, staking, swingset, swingset-runner, tc39, token economy, tooling, ui, wallet, xsnap, zoe, zoe contract

**Comment by Tartuffo** [comment]
@dckc This seems like it is in the RUN Protocol space, can you please assign it the correct area label, and if possible an esimate and/or assignee?
