### ISSUE TITLE
`isObject` should not allocate

### ISSUE THREAD

**Issue by dtribble** [Agoric/Agoric#4287]
## What is the Problem Being Solved?
Marshaling uses `isObject` on every marshalled element to determine whether it needs to be handled specially. The current test is robust against future changes to the JS spec, but allocates in most circumstances. As a result, the test is (expected to be) horrifically expensive.

## Description of the Design
We use `isObject` so that we can change that test in one place. We should take advantage of that now to make the test non-allocating given the current JS spec.  Change it to
```javascript
export const isObject = val => val !== null &&  typeof val === 'object' || typeof val === 'function';
```

For usability, we should also add `isPrimitive` as the dual of `isObject`. Many uses would be much more readable as a result.

## Security Considerations

The test must be updated if future versions of the language add more `typeof` cases that are not primitives.

## Test Plan

Rerun tests with the `isObject` definition changed.

**Comment by mhofman** [comment]
If doing a `typeof` test, I believe we should implement `isPrimitive` and `isObject` as an exhaustive listing of the allowed types and values for each (yes there's that pesky `null`). That means with the introduction of new typeof values, a value may match neither. Code using these predicates should be aware of this, and pick the most appropriate test, including negating one of the predicates. I'm actually wondering if we need more predicates based on these which are more expressive towards their intent (e.g. "does not allow reaching any authority")

**Comment by erights** [comment]
> That means with the introduction of new typeof values, a value may match neither. 

Law of the excluded middle is not true under version skew!

**Comment by Tartuffo** [comment]
@dtribble This does not have an area label that is covered by our weekly tech / planning meetings, so it will likely fall through the cracks for planning for MN-1. Can you please assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, ui, wallet, zoe, zoe contract

**Comment by Tartuffo** [comment]
@dtribble Bump.  For proper project planning and tracking, this needs an area label covered by one of our weekly planning meetings.  Please pick the appropriate one from: agd, agoric-cli, agoric-cosmos, amm, core economy, cosmic-swingset, endo, ertp, getrun, governance, installation-bundling, metering, oracle, pegasus, run-protocol, ses, staking, swingset, swingset-runner, tc39, token economy, tooling, ui, wallet, xsnap, zoe, zoe contract

**Comment by Tartuffo** [comment]
This also needs an assignee.

**Comment by kriskowal** [comment]
@erights @dtribble We need a ruling on whether or not to do this. My preference is to do nothing until the current approach shows up as the long pole on a flame graph. If you agree something needs to be done, @mhofman or I could take this on.

**Comment by kriskowal** [comment]
@mhofman Proposes adding an accelerator table for known primitive types to avoid the alloc for all known primitives then fall back to an alloc when there’s a possibility of being an object or an unknown primitive. This works for me.

**Comment by mhofman** [comment]
Here are 2 variations of a suggestion, that should be as safe as the current always allocating `Object(value) === value`:

```js
const isObject = value => {
  switch (typeof value) {
    case 'undefined':
      // [[IsHTMLDDA]]
      return value !== undefined;
    case 'boolean':
    case 'number':
    case 'string':
    case 'bigint':
    case 'symbol':
      return false;
    default:
      return value !== null && Object(value) === value;
  }
};
```

or
```js
const knownSafePrimitives = freeze({
  __proto__: null,
  boolean: true,
  number: true,
  string: true,
  bigint: true,
  symbol: true,
  undefined: false,
  object: false,
  function: false,
});
const isObject = value =>
  !knownSafePrimitives[typeof value] &&
  value !== undefined && // [[IsHTMLDDA]] has typeof 'undefined'
  value !== null && // null has typeof 'object'
  Object(value) === value;
```

**Comment by gibson042** [comment]
Testing shows no slowdown with `Object(value) === value`, possibly implying efficient collection of the immediately-discarded objects. For future revisits, here are the results and the benchmark suite itself.

```sh
$ ~/.esvu/bin/xs -v
XS 11.6.0 32 4

$ ~/.esvu/bin/xs -s lodash.js benchmark.js suite.js 
naïve typeof x 236 ops/sec ±1.45% (59 runs sampled)
advanced typeof x 233 ops/sec ±1.83% (58 runs sampled)
always coerce x 390 ops/sec ±1.25% (60 runs sampled)
typeof table x 296 ops/sec ±0.70% (56 runs sampled)
shortsighted x 295 ops/sec ±1.96% (54 runs sampled)

$ ~/.esvu/bin/v8 --version
Warning: unknown flag --version.
Try --help for options
V8 version 10.2.9
d8>

$ ~/.esvu/bin/v8 lodash.js benchmark.js suite.js 
naïve typeof x 5,402 ops/sec ±0.45% (65 runs sampled)
advanced typeof x 5,374 ops/sec ±0.21% (68 runs sampled)
always coerce x 5,137 ops/sec ±0.54% (68 runs sampled)
typeof table x 3,737 ops/sec ±0.18% (68 runs sampled)
shortsighted x 7,266 ops/sec ±0.56% (41 runs sampled)
```

<details><summary>suite.js</summary>

```js
const isObject_naive = value => {
  switch (typeof value) {
    case 'undefined':
    case 'boolean':
    case 'number':
    case 'string':
    case 'bigint':
    case 'symbol':
      return false;
    default:
      return value !== null && Object(value) === value;
  }
};

const isObject_typeof = value => {
  switch (typeof value) {
    case 'undefined':
      // [[IsHTMLDDA]]
      return value !== undefined;
    case 'boolean':
    case 'number':
    case 'string':
    case 'bigint':
    case 'symbol':
      return false;
    default:
      return value !== null && Object(value) === value;
  }
};

const isObject_alwaysCoerce = value => Object(value) === value;

const alwaysPrimitive = {
  __proto__: null,
  boolean: true,
  number: true,
  string: true,
  bigint: true,
  symbol: true,
};
const isObject_table = value =>
  value !== undefined &&
  value !== null &&
  !alwaysPrimitive[typeof value] &&
  Object(value) === value;

const isObject_shortsighted = value => {
  const type = typeof value;
  return value !== null && value !== undefined && (type === 'object' || type === 'function');
};


const rand = Math.random;
const exemplars = [
  [ undefined, true, false ],
  (r=rand()) => (r=r/0.99)>=1 ? [-1, 0, 1].at(rand() * 3) / 0 : Math.tan(r * Math.PI),
  [ 'foo', 'bar', 'baz' ],
  (r=rand()) => BigInt(Math.tan(r * Math.PI) | 0),
  [ Symbol('foo'), Symbol('bar'), Symbol('baz') ],
  [ null, {id: 'a'}, {id: 'b'} ],
  () => function(){},
];
const inputs = [];
for(let i = 0; i < 10000; i++) {
  const exemplar = exemplars.at(rand() * exemplars.length);
  if(typeof exemplar === 'function') {
    inputs.push(exemplar());
  } else if(Array.isArray(exemplar)) {
    inputs.push(exemplar.at(rand() * exemplar.length));
  } else {
    inputs.push(exemplar);
  }
}


var suite = new Benchmark.Suite();

suite.add('naïve typeof', function() {
  let result;
  for(let v of inputs) result = isObject_naive(v);
  return result || true;
});
suite.add('advanced typeof', function() {
  let result;
  for(let v of inputs) result = isObject_typeof(v);
  return result || true;
});
suite.add('always coerce', function() {
  let result;
  for(let v of inputs) result = isObject_alwaysCoerce(v);
  return result || true;
});
suite.add('typeof table', function() {
  let result;
  for(let v of inputs) result = isObject_table(v);
  return result || true;
});
suite.add('shortsighted', function() {
  let result;
  for(let v of inputs) result = isObject_shortsighted(v);
  return result || true;
});

if(typeof print !== 'function') print = (...args) => console.log(...args);
suite.on('cycle', function(event) {
  print(String(event.target));
});

suite.run({ 'async': true });
```

</details>

**Comment by dtribble** [comment]
It seems to me that someone needed a distraction and so has done this. I propose we go ahead and integrate this change (we meaning @kriskowal :)

**Comment by kriskowal** [comment]
Please reopen if I’ve misunderstood the substance of the conversation above.

My understanding from above benchmark is that `isObject` proves to be the fastest option on both XS and V8 of all the options that are safe in the face of language change. Between Endo and Agoric SDK, we define `isObject` in `ses` and `marshal` and they are both already sorted.

- [x] ses https://github.com/endojs/endo/blob/c9b1909e3aa128a6d01f862b9d513237ad45d1a1/packages/ses/src/commons.js#L252
- [x] marshal https://github.com/endojs/endo/blob/c9b1909e3aa128a6d01f862b9d513237ad45d1a1/packages/marshal/src/helpers/passStyle-helpers.js#L20

Thank you @gibson042. Benchmarks are full of surprises!
