### ISSUE TITLE
Proposal for network decentralization

### ISSUE THREAD

**Issue by mintiayields** [Agoric/Agoric#4294]
Most existing blockchains now have "whale" validators, who get a lot of voting power. Although this is surely well deserved this may harm the blockchain idea of decentralization.
Will you consider the following:
The bigger the voting power of a validator is, the lower rewards to its delegators are. That way you will encourage your network decentralization. The expected result is that delegators stake to smaller voting power nodes to get a better return, thus to reduce the influence of whales. This can reduce the commission competition, too, especially those infamous 0% validators. Delegators will have to keep an eye on the status quo and may have to re-delegate to a different validator from time to time to keep their stakes working well. Not to bad taking into account that this is "paid" for: they spend some time to get better returns.

**Comment by dckc** [comment]
Hi. Thanks for raising this here at my suggestion. I now realize that https://commonwealth.im/agoric/ might be a better forum for it. If you agree, please raise it there and close this.

cc @rowgraus @jessysaurusrex @Chris-Hibbert

**Comment by Tartuffo** [comment]
@dckc @rowgraus @jessysaurusrex Suggestion was to open this on Commonwealth, can we close this ticket in our Github?

**Comment by mintiayields** [comment]
Yes, sure
