### ISSUE TITLE
Marshal unserialize allows creating thenable

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#4302]
## Describe the bug
`unserialize` can be tricked into generating a thenable (an object with a `then` method). This may cause unexpected issues in the consumer of the marshalled data, such a limited reentrancy. In general marshal's `unserialize` should never produce anything that isn't a passable (which thenable are not)

## To Reproduce
Steps to trigger:
- Get a `Far` function from the target vat.
- Serialize and send a message with `harden({ then: remoteFarFunction })` as payload. It should locally satisfy [`passStyleOf` checks](https://github.com/Agoric/agoric-sdk/blob/f0f3a7548d591fe9fe27e247c09097c647bc076d/packages/marshal/src/passStyleOf.js#L138-L141) as `remoteFarFunction` is a remotable proxy which does not currently have `typeof === 'function'` 
- When received observe `unserialize` creating a then-able with [the `then` property](https://github.com/Agoric/agoric-sdk/blob/f0f3a7548d591fe9fe27e247c09097c647bc076d/packages/marshal/src/marshal.js#L462) being the local function [result of `convertSlotToVal`](https://github.com/Agoric/agoric-sdk/blob/f0f3a7548d591fe9fe27e247c09097c647bc076d/packages/marshal/src/marshal.js#L409) of the remoted Far function.
- If the receiver awaits the thenable, or does any Promise wrapping triggering its `then`, it will synchronously call the `Far` function at that point.

## Expected behavior
`unserialize` should never produce non passable data. In this case, a then-able should not have been constructed.

## Platform Environment
 - what version of the Agoric-SDK are you using? `72cc8d6bcf428596653593708959446fb0a29596`

## Additional context
Part of the Zestival findings. There are other cases where `unserizalize` may produce unexpected non passable data, and the mitigation for this issue may be part of a broader approach. See https://github.com/Agoric/agoric-sdk/issues/4337

We may also want to consider making proxies for remote far functions have a `'function'` `typeof`, which would at least prevent legitimate code from sending such messages (we still need to protect against maliciously crafted messages)

**Comment by erights** [comment]
See https://github.com/endojs/endo/issues/991

This bug should also be fixed in marshal's new home, in the endojs/endo repository. Attn @kriskowal

**Comment by mhofman** [comment]
> We may also want to consider making proxies for remote far functions have a `'function'` `typeof`, which would at least prevent legitimate code from sending such messages (we still need to protect against maliciously crafted messages)

@erights, should we split this into its own issue?

**Comment by erights** [comment]
> @erights, should we split this into its own issue?

Yes please. Unlike the original problem, fixing this one runs into the "auxiliary data on presence" conundrum. We won't be able to fix the presence typeof until then.
