### ISSUE TITLE
Need so-called "use objects"

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#4320]
A use-object represents a right that is both exercisable (by invoking the objects) and exclusively transferable (by vacating it and turning it into an invitation, which can be redeemed for a fresh one). A use-object is a Far object that self identifies as a use object and should provide the expected use-object lifecycle methods. In particular, as part of the vacate-and-mint-invitation operation, the use-object provides a description to go into the invitation amount to explain to Fred what rights would obtain by reclaiming it from its present vacated state. After an upgrade, the redeeming of the invitation would result in a use-object in the successor vat.

But "use-object" is a terrible name. Given this role, what should we call it?

See #76 #4080

**Comment by Chris-Hibbert** [comment]
How much better is "utility object"? It at least doesn't have the multiple pronunciation problem. A possible distinction is the "utility object" vs. the "access object".

**Comment by erights** [comment]
"utility objects" seems plausible to me. Thanks!

Other suggestions before we decide?

**Comment by dckc** [comment]
"live object" got considerable support in an earlier bikeshed on this, IIRC.

**Comment by erights** [comment]
"live object" also seems plausible.

Better would be a name that somehow suggests that the right-to-use is exclusively transferable, rather than sharable as is the norm for ocaps.

Is it close enough to Nick Szabo's "Scarce Objects" https://nakamotoinstitute.org/scarce-objects/ to justify that name? Is it a good name for the concept? (attn @btulloh @dtribble )

**Comment by turadg** [comment]
> Better would be a name that somehow suggests that the right-to-use is exclusively transferable, rather than sharable as is the norm for ocaps.

That sounds like [rival good](https://www.investopedia.com/terms/r/rival_good.asp#:~:text=Goods%20are%20either%20classified%20as,of%20goods%20that%20are%20nonrival.) to me.  Though "rival objects" could be interpreted in other ways.

**Comment by erights** [comment]
"Rivalrous Object" is less likely to be misinterpreted, but is more verbose.

Elsewhere, "Usufruct" has been suggested.  It has the virtue of not colliding with anything and being generally unknown to our audience, so we can teach it the way we'd want to teach it. OTOH it does deepen the sense that our system has lots of new jargon you need to learn.

My favorite so far remains "Scare Object" if it does adequately correspond to what Nick was talking about.

**Comment by kriskowal** [comment]
Maybe it’s useful to think of this as a naming problem for the usable and transferrable modes as a dual.

- unpacked (for use) vs packaged (for transport)
- kinetic vs potential
- active vs inactive
- open vs closed
- wet vs dry

**Comment by erights** [comment]
I like that. For the packaged/potential/inactive/closed/dry form, we have a less urgent need for a standalone name, since it is already an invitation, and invitations are already exclusively transferable rights. Perhaps "adjective invitation".

But for the unpacked/kinetic/active/open/dry form, "adjective object" works much less well. Used by itself, none imply the possibility to exclusively transfer the right to use it.

**Comment by erights** [comment]
Perhaps "unpacked" vs "packaged" comes closest, since "unpacked" suggests a packed form, which is close to "packaged". A "packaged" form suggests transport. I'm warming to it.

If you heard "unpacked object" before you learned about it, what would you guess it means? Likewise for the other suggestions.

**Comment by erights** [comment]
Elsewhere, @warner just made my favorite suggestion so far: "transferrable object". I like it well enough that I think I'll go with that for now. Thanks @warner !

**Comment by dckc** [comment]
@dtribble asked why "use object" is not acceptable, given the cost to change not only the code but docs, etc., plus disconnecting future use from earlier presentations.

**Comment by zarutian** [comment]
Just to note that the object pattern I use for 'use objects' is that there is a non-fungible token that represents, for lack of a better term, thr title of the thing. This title nft is then used in an invatation made by invoking a spefic public method on the comtract that minted the title, to get a UserSeat and a use-object. So long the seat remains unexited the use-object remains usable. When the seat gets exited that use-object gets revoked and the title nft gets refunded back. This allows for lending out the titled thing without giving away the thing itself. Like you can lend your car to your friend without giving over the ownership of the car.

**Comment by erights** [comment]
@zarutian that's a nice pattern, and it is related. But it is different than the concept I'm trying to name. In your case, the transferable right is represented, while active, by a live seat. In the concept I'm trying to name, the use-object, by itself, represents both the rights to exercise and the right to vacate-and-transfer. What problem does this simpler design solve:

Currently, if we're providing a use right that would naturally be represented by an object, but which the recipient might want to transfer (sell to Fred, etc), then we always have to hand out an invitation first. If the recipient could turn a use-object into an invitation after they receive it, then we could give them the use-object first, enabling them to skip a step if they wanted to use it themselves rather than sell it.

**Comment by erights** [comment]
Done by https://github.com/Agoric/agoric-sdk/pull/8745

The name we settled on is "ownable".
