### ISSUE TITLE
Upgrade Prettier to 2.5.1

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4329]
## What is the Problem Being Solved?

Our version of `prettier` is old (1.8) and the longer we are behind the more git blame noise there is when we do upgrade. [Prettier 2.0](https://prettier.io/blog/2020/03/21/2.0.0.html) was a pretty big change. 2.5.1 is latest.

## Description of the Design

* Update prettier deps to latest
* Update code to latest
* Clean up tooling that checks and updates Prettier style (moving concern from packages to repo)
* Provide a scheme to minimize impact on existing branches (cc @mhofman )

## Security Considerations
n/a

## Test Plan

Get reviews from people doubtful of the Prettier code style.

**Comment by mhofman** [comment]
Here are suggestions regarding the merge / rebase dance.

For the PR upgrading prettier, it needs 2 stacked commits:
- Update version in `package.json` with no other changes. This specific commit doesn't pass formatting tests
- Apply prettier fix to all files. Possibly twice to make sure no instability issues remain
- Merge into master

For a branch started before the prettier change:
- Try to rebase on master. If no conflicts arise, nothing else to do. If there are complex conflicts, abort.
- Merge the first commit of the prettier PR upgrading version
- Merge the second commit of the prettier PR, ignoring incoming changes. Run prettier fix then commit the resolved merge.
- This branch can still not be rebased when landing the PR, only merged

Rebase alternative:
- Rebase the branch on top of the first prettier commit updating version
- Rebase the branch on top of the second prettier commit, resolving each conflict by ignoring incoming changes and applying prettier fix before committing

How to verify that unexpected changes don't sneak in:
- Rebase onto or merge the first prettier commit updating version
-  Apply prettier fix
- Stash changes
- Rebase onto or merge the second prettier commit, and perform conflict resolution
- Compare result with stash. There should be no difference

**Comment by Tartuffo** [comment]
@turadg This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, ui, wallet, zoe, zoe contract

**Comment by turadg** [comment]
@Tartuffo It doesn't fit any of those areas since it's for the whole monorepo. Should we have a new area like "tooling"?

**Comment by Tartuffo** [comment]
@warner Thoughts on a label to cover things like this, and loadgen?  i think tooling is fine, would we review them in the Swingset meeting (which Turadg does not go to)?

**Comment by turadg** [comment]
Thanks @mhofman @michaelfig for pointing out there's already a [tooling label](https://github.com/Agoric/agoric-sdk/labels/tooling). I've added it to this and will do so on similar PRs and issues going forward.
