### ISSUE TITLE
Stronger typing of slots

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#4334]
## What is the Problem Being Solved?

Currently slots only capture the type of the slot in the body of the message, and slots are completely opaque to the distributed system. Worse, the typing information is not consistent:
- promises have they own `qclass` but are mixed without identifiers amongst remotables in the slots.
- remotable qclass has an optional `iface` description in the body, but that is only included in the first mention of the slot, and the stability of the value isn't enforced (see https://github.com/Agoric/agoric-sdk/issues/4333)

Marshal doesn't enforce `convertSlotToVal` to create a value that is consistent with the qclass (remotable or promise) or the iface. It actually doesn't even enforce that the return value is passable (separate issue)

## Description of the Design

The slot mechanism could be made of 2 arrays: one containing the slot static info (promise, remotable + iface, maybe other object shape data), and one containing layer specific data returned by `convertValToSlot` (vref). The body would only include a `qclass: "slot"` and a `slotId` without any other info. Translation and metering layer could inform their logic by the static data, and the translation layers (comms) would only rewrite the dynamic data.

**Comment by erights** [comment]
Closing as fixed by smallcaps.

**Comment by mhofman** [comment]
To clarify, smallcaps only implements a differentiation of promise vs remotable in the body encoding, and I believe enforces that the decoded value matches. Transmitters that only touch the slots, such as the kernel (mostly) or comms, can still derive the type (promise vs remotable) from the slot encoding.

What this issue was initially about was to extract the type (promise, vs the specific iface of the remotable), in a place that didn't require the body to be parsed, or relied on the slot encoding itself. However after further discussions, that aspect is not needed since at least the iface would be user code derived and thus untrusted.
