### ISSUE TITLE
make run-protocol vault prioritization use the new Collections API

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4341]
## What is the Problem Being Solved?

Large scale storage in a contract should use virtual Stores. Vaults are O(large).

## Description of the Design

The Array in `prioritizedVaults.js` should be converted to some kind of Store. Since we want it to be sorted, we probably have to use the Ratios or a Number representing them as keys.

## Security Considerations

This is about robustness.

## Test Plan

It's not necessary to create huge numbers of vaults to test this.

**Comment by Tartuffo** [comment]
We should apply this to Vaults in batches.
