### ISSUE TITLE
Use Virtual Objects in Governance

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4343]
## What is the Problem Being Solved?

For MainNet 1, we must support durable objects for restart and upgrade. This is part way to https://github.com/Agoric/agoric-sdk/issues/5200

## Description of the Design

Collect a catalogue of all the persistent data types in Governance, and convert them to Virtual Objects.

## Security Considerations

Trust paging of defineKind APIs.

## Test Plan

Presumably extensive.

**Comment by Tartuffo** [comment]
Does need collections, just virtual objects for durability.

**Comment by Chris-Hibbert** [comment]
A quick survey of current storage:

**BinaryVoteCounter**

```
  /** @type {Store<Handle<'Voter'>,RecordedBallot> } */
  const allBallots = makeStore('voterHandle');
```

  The counter itself is an object with state
    question, isOpen, questionSpec, outcomePromise, tallyPromise

**Committee  (and shareHolders)**

```
  /** @type {Store<Handle<'Question'>, QuestionRecord>} */
  const allQuestions = makeStore('Question');
```

  invitations is an array

   The committee itself is an object with state:
       subscription, publication, committeeName, publicFacet

**contractGovernor** has no stores, but it has state itself

**governParams**

```
  const voteCounters = new WeakSet();

  let poserFacet;
  let currentInvitation;
```

**paramManager**
```
  const namesToParams = makeStore('Parameter Name');
  const { publication, subscription } = makeSubscriptionKit();
  const updateFns = {};
```

**Comment by turadg** [comment]
With https://github.com/Agoric/agoric-sdk/pull/7657 it's mostly durable. Any work now will be on making it fully durable, not virtual,
- #5200
