### ISSUE TITLE
Use Virtual Objects in AMM

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4344]
## What is the Problem Being Solved?

For MainNet 1, we intend to support durable objects for restart and upgrade.

## Description of the Design

Collect a catalogue of all the persistent data types in the AMM, and convert them to Virtual Objects.

## Security Considerations

This is about durability. It shouldn't have broader security implications.

## Test Plan

Presumably extensive.

**Comment by dtribble** [comment]
We must address all the `Far` elements that contain long-term state.
* [ ] multipoolMarketMaker - holds all the pools
* [ ] pool - holds state for each collateral

Ephemeral ones that we do not need to convert to virtual objects
* priceAuthority - wrapper on the oracle; ephemeral
* singlePool - may be ephemeral
* doublePool - ephemeral; created on demand
* calcSwapPrices - ephemeral

**Comment by Tartuffo** [comment]
@erights have you been working on this as your "sample contract to upgrade"?
