### ISSUE TITLE
Use Virtual Objects in Vaults

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4345]
## What is the Problem Being Solved?

For MainNet 1, we intend to support durable objects for restart and upgrade.

## Description of the Design

Collect a catalogue of all the persistent data types in Vaults, and convert them to Virtual Objects.

## Security Considerations

This is about durability. It shouldn't have broader security implications.

## Test Plan

Presumably extensive.

**Comment by Tartuffo** [comment]
Also related to #4344.

**Comment by Chris-Hibbert** [comment]
#4341 is a subset of this work.

**Comment by turadg** [comment]
> #4341 is a subset of this work.

True. For estimation I was reading this one as the work to be done to finish the job after #4341. So i'd call that one a blocker of this, because that one uses the Collections API and this ticket is to enable `durable: true` and make that fly.

**Comment by turadg** [comment]
https://github.com/Agoric/agoric-sdk/pull/4618 illustrates best practices
