### ISSUE TITLE
Governance control of new oracle nodes

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#4349]
New oracle providers for RUN Protocol price feeds need to be whitelisted by governance.  

For Mainnet 1, governance for this could occur at either the Cosmos layer or JavaScript layer.

**Comment by dtribble** [comment]
At the cosmos level, messages from this oracle should be added to the prioritized whitelist so they get through the mempool quickly.

At the JavaScript level, those senders need to be added to the FluxAggregator.

**Comment by dckc** [comment]
The oracles seem to be working on devnet!

Based on some clues @michaelfig gave me, I wrote up a little blurb on how to use them: https://github.com/Agoric/agoric-sdk/issues/7782

The documentation on how he set it up is https://github.com/Agoric/dapp-oracle/blob/main/README-gov.md
