### ISSUE TITLE
Decentralized dapp hosting

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#4350]
To demonstrate our ability to have decentralized Dapps on our platform, we'd like to find some community partners to host Dapps.

## Design

```[tasklist]
- [ ] https://github.com/Agoric/dapp-inter/pull/37
 - [ ] https://github.com/Agoric/agoric-sdk/issues/6860
```

Plus:
- https://github.com/Agoric/dapp-econ-gov/issues/32
- https://github.com/Agoric/dapp-inter/issues/57

Note that the first publish / pin part is permissionless; Agoric can do it, but so can anyone else.

**Comment by Tartuffo** [comment]
@dtribble Do we really need this for MN-1

**Comment by dtribble** [comment]
Yes.

**Comment by Tartuffo** [comment]
@rowgraus To demonstrate our ability to have decentralized Dapps on our platform, we'd like to find some community partners to host Dapps.

**Comment by Tartuffo** [comment]
Fred and Vanessa would be helpful to work with Rowland on this issue.

**Comment by dckc** [comment]
In a meeting yesterday, @arirubinstein sketched a solution using decentralized storage keyed by an on-chain hash.

**Comment by ivanlei** [comment]
@otoole-brendan is driving this with P2P

**Comment by dckc** [comment]
I replaced the **needs-design** label with some details in the description based on discussion with @dtribble, @otoole-brendan , @rowgraus @arirubinstein and @ivanlei 

In particular, @rowgraus ok'd the URLs `app.inter.trade` and `wallet.agoric.app`

**Comment by arirubinstein** [comment]
Approach has been agreed on and is remaining work is captured in:

 - https://github.com/Agoric/dapp-inter/issues/57
 - https://github.com/Agoric/dapp-econ-gov/issues/32
 - https://github.com/Agoric/dapp-inter/issues/36
