### ISSUE TITLE
store Zoe state in durable/virtual objects/collections

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4383]
## What is the Problem Being Solved?

To allow Zoe to maintain low RAM usage despite being involved in every contract, as well as to enable Zoe to be upgraded, we need it to store all long-term state using `makeDurableKind` and virtual/durable collections.

I don't know exactly what state Zoe uses. I know there are a lot of Offers and Seats and Invitations and stuff. As a first step, I'm guessing that each of these needs to be converted into a virtual-object Kind, and any collections of them need to be stored in a virtual-collection using something like `makeBigWeakMap`. Performing this translation/porting is probably the bulk of the work.

A small step is to then switch to Durable objects/collections instead of merely Virtual ones, for the state that needs to survive an upgrade.

Then a medium step is to record all the collection objects (and handles to the Kinds that must survive) in the #4325 "baggage", so the new Zoe version can retrieve it.

Another large design question is what state ought to survive the upgrade (kept in Durable storage), and what can be discarded (kept in Virtual storage). And what clients will experience during the process. The simplest approach is to just store everything in Durable, but @erights points out that vats and contracts should be more deliberate about their upgrade process.

**Comment by Tartuffo** [comment]
@Chris-Hibbert Assigning to you per the conversation in today's Eng Sync, please put an estimate on it once you have scoped out the task.

**Comment by Chris-Hibbert** [comment]
Here's a [Catalog of Zoe's storage](https://github.com/Agoric/agoric-sdk/blob/master/packages/zoe/docs/zoe-catalog-of-storage.md). It lists 1 WeakSet, 9 WeakStores, and 2 Native Sets.  I see at least 3 objects (`instanceAdmin`, `ZoeSeatAdmin`, `IssuerRecord`)  that must be converted to virtual objects. The other values to be stored may be handles or presences.

`sumsByBrand` is ephemeral and doesn't need to be persisted.

**Comment by Tartuffo** [comment]
Per conversation with @dtribble Chris does not need to prioritize this for Restival.

**Comment by Tartuffo** [comment]
Likely people to pick this up if @erights doesnt have the bandwidth to do this in the MN-1 timeframe: @Chris-Hibbert and @turadg
