### ISSUE TITLE
install-bundle transaction message

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4396]
## What is the Problem Being Solved?

#3269 has swingset expose a `controller.installBundle()` API. This ticket is to have cosmic-swingset take advantage of that API, and make the functionality available to external users through a new signed cosmos transaction message type.

Currently, contracts are installed into the chain by sending an object message to Zoe. These messages are by far the largest in our system: most operational messages (make offer, accept invitation, deposit/withdraw) serialize into a few hundred bytes, but contract bundles tend to be 1-2 MB in size. We'd like to move these large bodies out of object messages. Once complete, we'll be able to impose limits or fees on object messages to keep them to a reasonable size.

Cosmic-swingset defines a number of "modules": Go code to which messages can be dispatched. Each signed transaction contains one or more messages, each message has a type, each type is dispatched to a particular module. Currently the swingset module handles a message for mailbox additions, and another for changing the bean price table.

The task of this ticket is to add a third message type to the swingset module. This should be called `installBundle`, and should accept the 1-2MB bundle object as a payload. When executed, it should call `controller.installBundle()` with the payload. This needs to happen in the context of a block, so the kernel state is committed afterwards (which should happen naturally if it gets executed in DeliverTx as usual).

Contract installation needs to be limited in some fashion to protect the storage space of the validators, and to discourage the use of the bundlestore for spam. It might also be a good place to impose the MN-1-vs-2-vs-3 limits on who can install contracts, to guard the not-yet-hardened runtime against malicious contracts (and/or we should build a lock on `zoe~.install`). Even after everything is permissionless, bundle installation should probably change some large (but configurable) fee. A more sophisticated approach might include a deposit and a governance vote, something to require that contract installers are serious and will provide a net positive value to the chain as a whole. #4395 addresses this question.

## Description of the Design

I'll leave the details to @michaelfig , but I think the swingset Go module wants to acquire a new message type, and a handler which delivers something to the JS side, which should then do a `controller.installBundle()`. This should look a lot like the existing "add message to mailbox" pathway.

The fees to be charged need to be configurable.

If #4395 says that access to this message should be restricted, the module will need to implement that restriction.

**Comment by warner** [comment]
Ok, #3269 is landed, and the API is `controller.validateAndInstallBundle(bundle, allegedBundleID)`, so this is ready for the cosmic-swingset -side work. We don't have much in the way of code to generate bundle hashes yet, though, so it might be hard to test. You could crib something from `packages/SwingSet/src/validate-archive.js`, which can compute a hash from a bundle. @kriskowal says it's likely to be two or three weeks before Endo will have the real hash-computing support.

**Comment by dckc** [comment]
In a Feb 9 meeting, @dtribble pointed out that we can / should gate install-bundle messages on a previously governance-approved list of message hashes. (ref #3724 , #4395).

**Comment by dckc** [comment]
My impression is that this issue is a plan to add a 2nd cosmos level message type:
 1. Eventual Send for normal distribute object messages - this one would have a moderate size limit of O(100K) or so
 2. This install-bundle message - the would have a larger size limit to accommodate contracts, which, in practice, are up to some 1.2M.

background...

@Tartuffo recently asked whether this is critical for MN-1.
A few pointed out the plans to use hash-bundles rather than huge strings all over the vat transcripts. That stuff is pretty important, but in theory, we could perhaps do without it, except...

We decided to put a cap on message size for security reasons (#4280). So I'm marking this one as blocking #4280.

**Comment by kriskowal** [comment]
Solved in https://github.com/Agoric/agoric-sdk/pull/4975
