### ISSUE TITLE
The `StoreOption` type should be the partial one

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#4412]
At https://github.com/Agoric/agoric-sdk/blob/1dfbb4745ebfe84cbf7b8b803d05e70ce978ecf8/packages/store/src/types.js#L76-L77 I define the type `StoreOptions` as a normal TS record type with all fields mandatory. But that's of course not how options bags are intended to be used; including this one. Then when I use the type
https://github.com/Agoric/agoric-sdk/blob/1dfbb4745ebfe84cbf7b8b803d05e70ce978ecf8/packages/store/src/stores/scalarMapStore.js#L131
I decorate it with `Partial<...>=`. Instead, that should be folded into the `StoreOptions` type exported from `types.js`, since that's the only way it is intended to be used.

When reviewing #4136, I noticed the damage my mistake caused. @FUDCo , would you rather I fix this and land it before #4136, after, or would you rather just make this correction in #4136 itself?

**Comment by FUDCo** [comment]
I think it makes most sense to fold this into #4136; I will do that.  That PR is not yet final and this is a very minor change.

**Comment by FUDCo** [comment]
So on further examination, I'm confused.  All the properties in `StoreOptions` as defined in `store/src/types.js` are already declared optional.  What am I missing?

**Comment by Tartuffo** [comment]
is this done?

**Comment by FUDCo** [comment]
Yes, this is done.  Closing.
