### ISSUE TITLE
Connect to Kelpr from Wallet UI

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#4421]
## What is the Problem Being Solved?

For the on-chain wallet, requests will go through Keplr rather than ag-solo. We need to add functionality for the wallet frontend to connect to the Agoric chain through the extension.

## Description of the Design

A dropdown menu/button in the appbar for connecting to Keplr should be added. From the dropdown, users can select the network (devnet, local, mainnet etc.) or add another. Then, the UI will connect or suggest the chain to Keplr. For now we should just get the connection working, but eventually we'll have to make the wallet actions work properly through Keplr txns.

Notes:
CosmJS: https://docs.keplr.app/api/cosmjs.html#example
Custom txn types: https://github.com/Agoric/faucet/blob/cosmjs-rpc/src/gift.js
Local chain network-config.json:
```
{
  "chainName": "agoric",
  "peers": [
  ],
  "rpcAddrs": [
    "127.0.0.1:26657"
  ],
  "seeds": [
  ]
}
```

**Comment by dckc** [comment]
Is there some trick to get this to work? I see a **Connect to Wallet** button in screenshots in PR #4430 but not in my running wallet UI.

**Comment by samsiegart** [comment]
> Is there some trick to get this to work? I see a **Connect to Wallet** button in screenshots in PR #4430 but not in my running wallet UI.

Yes, the trick is `?onchain=true` in the URL. After you connect you can go as far as seeing `window.cosmJS` in your console, but nothing in the UI actually works on-chain yet.
