### ISSUE TITLE
Allow lien wrapper to work for additional vesting account methods

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#4424]
## What is the Problem Being Solved?

The lien wrapper account currently proxies the common vesting account methods, but `PeriodicVestingAccount` and `ClawbackVestingAccount` have additional methods. These must be proxied as well.

**Comment by Tartuffo** [comment]
@JimLarson This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, wallet, zoe contract.  Or, if this is accurately labeled by an area label we should be covering in one of our weekly meetings, please LMK.

**Comment by JimLarson** [comment]
Note that there's a bug in #4760 in calculating the amount to keep locked. Need to calculate max(0, max(locked, liened + unvested) - net_delegated).
