### ISSUE TITLE
Reward distribution for Mainnet-1 cosmos-sdk application

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#4425]
## What is the Problem Being Solved?

Must update the daemon application to configure the distribution hook for vesting so rewards to clawback vesting accounts can be properly distributed.

**Comment by Tartuffo** [comment]
@JimLarson This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, wallet, zoe contract.  Or, if this is accurately labeled by an area label we should be covering in one of our weekly meetings, please LMK.
