### ISSUE TITLE
Rename "Default" in the vaults to "Shortfall" when liquidation doesn't cover RUN debt

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#4439]

**Comment by dckc** [comment]
@dtribble help me find the relevant code? I spent a couple minutes without luck.

**Comment by dtribble** [comment]
It is determined in [liquidation.js:57](https://github.com/Agoric/agoric-sdk/blob/master/packages/run-protocol/src/vaultFactory/liquidation.js#L57).  It doesn't currently report that as an issue anywhere. That should propagate up to the vault manager to cover the shortfall.

**Comment by dckc** [comment]
Thanks.

The propagating probably fits better in #4399.

**Comment by dtribble** [comment]
There is no use of the term "default" in VaultFactory.
