### ISSUE TITLE
Sync Dapps with Endo Release Versions 2022-02

### ISSUE THREAD

**Issue by kriskowal** [Agoric/Agoric#4441]
The following dapps need to be migrated to use the latest versions of `nat`, `lockdown`, `init`, `captp`, `marshal`, `eventual-send`, `bundle-source`, and `import-bundle` from those most recently published in the `@endo` npm org. Where fitting, `*` dependencies should be changed to `dev` to align better with agoric-sdk versions published from npm and installed with `agoric install`.

- [x] dapp-card-store
- [x] dapp-treasury
- [x] dapp-fungible-faucet

The dapps we don't need to test because they are fully covered by automated tests and CI on agoric-sdk PRs are:

- [ ] testnet-load-generator (integration test in agoric-sdk)
- [ ] documentation (full test coverage for snippets)
- [ ] dapp-otc (no frontend, full test coverage)
- [ ] dapp-nft-drop

**Comment by Tartuffo** [comment]
@kriskowal This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, wallet, zoe contract

**Comment by Tartuffo** [comment]
@kriskowal I assume since you moved this to "In Progress", that it is needed for MN-1.

**Comment by kriskowal** [comment]
This is fallout from https://github.com/endojs/endo/issues/506, which was MN-1 dependent. That task created debt best paid off before it accumulates interest.

**Comment by mhofman** [comment]
I'd like to figure out a way for the loadgen to somehow be compatible with both older SDK versions and newer ones. Maybe that's a dream that gets shattered by this issue, but in the meantime, let's try to find a way.

**Comment by Tartuffo** [comment]
@mhofman Please update estimate, or close this and create new ticket for your work.

**Comment by mhofman** [comment]
I'm lacking context here. Have the changes to `agoric-sdk` landed to eject those packages? Or is this re-assignment about updating the loadgen code so it's compatible with these upcoming changes?

As I mentioned, I'd like the loadgen to stay backwards compatible, which needs design and probably requires support from endo's bundleSource. In general, what is the story regarding backwards compatibility for contracts?

**Comment by Tartuffo** [comment]
@mhofman I think it is about updating the loadgen code so it's compatible with these upcoming changes, but looping @kriskowal in for his opinion.

**Comment by kriskowal** [comment]
Indeed, I stopped at loadgen since the migration might break that, and because the migration process was sinking too much time. I intend to circle back as well.

**Comment by kriskowal** [comment]
I’m going to call this done. I’ll leave to @mhofman the concern of maintaining appropriate version ranges there. At this point, I’m not aware of breaking changes in these Endo packages that should impact compatibility, except perhaps some packages migrating away from ambient types.

**Comment by Tartuffo** [comment]
@samsiegart Assigned this to you, at @kriskowal's suggestion.
