### ISSUE TITLE
Prevent or notify broken master tests

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4459]
## What is the Problem Being Solved?

We recently had some build check failures for master:

> https://github.com/Agoric/agoric-sdk/runs/5069159963?check_suite_focus=true
> ```
> lerna ERR! EPUBLISHCONFLICT Cannot publish @agoric/cosmos@undefined over existing version.
> ```
>
> https://github.com/Agoric/agoric-sdk/runs/5069182650?check_suite_focus=true
> ```
> error @typescript-eslint/parser@5.10.2: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.15.5"
> error Found incompatible module.
> ```

They persisted for some days because there was no notification. The checks that were failing were defined for some purpose, so we should know when they fail (or if it doesn't matter then remove them).

## Description of the Design

TBD, some way to prevent persistent failures of master checks.

## Security Considerations
--
## Test Plan

TBD

**Comment by mhofman** [comment]
@michaelfig might be able to take the first one.

I probably broke the second one.

**Comment by mhofman** [comment]
https://github.com/Agoric/agoric-sdk/pull/4460 should fix the second issue.

**Comment by michaelfig** [comment]
> @michaelfig might be able to take the first one.

The first one was a test flake, AFAICT.

**Comment by mhofman** [comment]
I've fixed the second. If the first was a flake, can we close @turadg

**Comment by turadg** [comment]
The "fix" part is resolved. Open question as to whether to prevent. Shouldn't we have some notification of persistent failures checking master HEAD? I'll change the ticket description to focus on that issue.

**Comment by mhofman** [comment]
I believe the person merging a PR should received an email if their test fails, and address it. I believe the issue is that these tests don't run on PRs, only on master after merging. If an email to the merger is not sufficient (if it happens today), then yes we should find a better way to surface this.

**Comment by mhofman** [comment]
@Tartuffo we should prioritize this. Currently nobody seem to be getting emails for job failures on master branches, so unless we pay attention, we won't know if master is broken. Some what of surfacing that information (find a way to trigger emails, bot message on keybase, etc) is needed ASAP.

**Comment by michaelfig** [comment]
> I believe the person merging a PR should received an email if their test fails, and address it. I believe the issue is that these tests don't run on PRs, only on master after merging. If an email to the merger is not sufficient (if it happens today), then yes we should find a better way to surface this.

The email is sent to the last committer of the failed `workflow.yaml` file.

https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs

**Comment by mhofman** [comment]
Would that be the mergify bot since it creates the merge commit?

**Comment by michaelfig** [comment]
> Would that be the mergify bot since it creates the merge commit?

Currently @turadg:

```
git log .github/workflows/docker.yml
commit 2f0073a513dcf8339a1fab05b03f62441f3724da
Author: Turadg Aleahmad <turadg@agoric.com>
Date:   Tue Feb 1 08:00:33 2022 -0800

    style: yarn format (prettier 1.19.1 but 2.51 has same output)
```

**Comment by mhofman** [comment]
Oh the commiter of the workflow file, not of the merge commit on which the workflow ran! That's just weird...

**Comment by turadg** [comment]
Hmm, if it goes to the committer of the workflow file I'd expect to have received an email when https://github.com/Agoric/agoric-sdk/commit/1daf09d881e418a63b8ace4c60e12ea6bb86627e hit master right after that workflow change.

> The email is sent to the last committer of the failed workflow.yaml file.

I think that only applies to scheduled workflows.
> Notifications **for scheduled workflows** are sent to the user who initially created the workflow.

We're talking about workflows triggered on merge to master:

> If you enable email or web notifications for GitHub Actions, you'll receive a notification when any workflow runs **that you've triggered** have completed. The notification will include the workflow run's status (including successful, failed, neutral, and canceled runs). You can also choose to receive a notification only when a workflow run has failed. For more information about enabling or disabling notifications, see "[About notifications](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications)."

So I think @mhofman is right that it's going to Mergify since it was the "user" who triggered the master build workflow.

**Comment by michaelfig** [comment]
> So I think @mhofman is right that it's going to Mergify since it was the "user" who triggered the master build workflow.

The Mergify experiment was interesting, but they really want to charge us "Premium" just to get the ability to have a custom merge account whose e-mails we can forward.  I think we are going to need to do something like:

1. Self-host something like https://kodiakhq.com/ (free software, looks really well-thought-out).  Alternatively, we could pay for mergify premium ($18/user/mo!).
2. Set the Github notification e-mail address from the self-hosted `agoric-mergebot` account to something like `mergebot@agoric.com`, which would be an email list we maintain with interested folks
3. To satisfy @warner's clean(ish) tree requirements, we should manually rebase PRs against master just before hitting the `automerge` label.  Having the bot rebase PRs is either dreccky (with Mergify) or impossible (with Kodiak).

**Comment by mhofman** [comment]
I don't think the rebase feature from mergify is what does us in here. Even regular merge commits are problematic, as seen by https://github.com/Agoric/agoric-sdk/pull/4308 which didn't trigger a notification (afaik). So option 3 is out.

**Comment by michaelfig** [comment]
> So option 3 is out.

I don't mean options.  I mean steps.

**Comment by mhofman** [comment]
Gotcha. An alternative is to modify workflows that trigger on master to send a notification (email, keybase, etc) on failure.

**Comment by Tartuffo** [comment]
If this is is going to take more than 1 developer day to fix / workaround, then I'd rather just pay for Mogrify premium for now, and fix this after MN-1.

**Comment by turadg** [comment]
Recap of steps to achieve this if we upgrade Mergify:
- make a mailing list of people to be notified on master failure
- make a bot account with that mailing list as the email
- [select it in Mergify](https://blog.mergify.com/selecting-your-bot-account/)

Note that this still won't directly notify the person whose merge broke master.
