### ISSUE TITLE
Clawback vs lien vs slashing

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#4463]
We need to decide on the behavior we want when slashing causes a conflict between the expectations of clawback and liens.

As a reminder, staked tokens do not have bookkeeping on them to tell us which are locked, unvested, or liened. Therefore after slashing, we must externally decide the character of the funds that were lost.

At clawback time, we deem that vested funds were lost first, followed by unvested, with an eye towards maximizing the amount that can be clawed back.

For liens, we decided that the liened amount is *never* reduced by slashing, and that a lien liability persists even if all funds are lost to slashing. Furthermore, liens can only be taken on vested funds.

Lastly, clawback is implemented at the `cosmos-sdk` software which is ignorant of the lien mechanisms implemented in `agoric-sdk`. From the perspective of clawback, liened funds just look like other vested funds.

So we need to decide what happens in the following scenario: an account has 100BLD, all staked, with 50 vested and 50 unvested, and it takes a lien on the 50 vested BLD. Now it gets slashed for 20BLD (leaving 80BLD staked), and then clawback is executed. Since clawback is ignorant of the lien, it will currently transfer 50 staked BLD to the clawback destination, leaving only 30BLD as collateral for the 50BLD lien.

Is this acceptable? Note that a similar outcome can happen if the account had only 50 vested staked BLD in it originally.

**Comment by Tartuffo** [comment]
As discussed, the slashing must by pro-rata based on the proportion of vested vs. non-vested.  Or, that might not be the case, based on the language of the vesting contracts re: slashing.

**Comment by JimLarson** [comment]
Resolved by #4524, where we decided that yes, clawback ignores slashing losses.
