### ISSUE TITLE
AppHash failure in loadgen CI (multi-node)

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#4473]
## Describe the bug
I've been trying to enable loadgen CI in `agoric-sdk` as an extension to the 2 node chain deployment test job (see #4256).

I'm not running into an AppHash failure on last stage / restart. This is not a problem in `local-chain` mode.

## To Reproduce
https://github.com/Agoric/agoric-sdk/runs/5081545180?check_suite_focus=true

## Expected behavior
No `AppHash` failure

## Platform Environment
 - what OS are you using? what version of Node.js? Ubuntu node 14 GitHub Actions environment
 - is there anything special/unusual about your platform? It's slow, but nothing special besides that
 - what version of the Agoric-SDK are you using? `master`

## Screenshots
```
stage-2: chain: panic: Failed to process committed block (124:9701822B576A9D05A2F0F92CB19AD325F9A539315736FE2897CA47735F326E6C): wrong Block.Header.AppHash.  Expected 697529EF6B04EFF3EDAB2D610F66BE1CA54213412C9066BD2142E69A5F1CA4E0, got 1898E02D26880C3277B7C742E03185C87B9A5177495A1E79BD5FFD5D34A80D23
stage-2: chain: 
stage-2: chain: goroutine 70 [running]:
stage-2: chain: github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000d45180, 0x0)
stage-2: chain: 	/home/runner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/blockchain/v0/reactor.go:401 +0x1265
stage-2: chain: created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
stage-2: chain: 	/home/runner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/blockchain/v0/reactor.go:110 +0x85
```

https://github.com/Agoric/agoric-sdk/actions/runs/1801322829#artifacts

https://github.com/Agoric/agoric-sdk/suites/5193083757/artifacts/158221091

**Comment by michaelfig** [comment]
I looked at `validator0.slog` and `validator1.slog`, and found that `validator1.slog` was cut off mid-block, just where it was getting interesting.

Seems like the Node.js write buffer wasn't empty when the second validator diverged.  So, we don't have the data to see the source of the divergence.

When #4471 is landed we should get enough data to see what's going on.

**Comment by mhofman** [comment]
We should compare that to the loadgen's slog

**Comment by mhofman** [comment]
Here is another failure https://github.com/Agoric/agoric-sdk/actions/runs/1802678946

I rebased on top of #4471 to hopefully capture more data. Pending run: https://github.com/Agoric/agoric-sdk/actions/runs/1804841560

**Comment by mhofman** [comment]
I fixed the storage capture issue, and with @michaelfig fix of the flight-recorder, we now have more data in https://github.com/Agoric/agoric-sdk/suites/5199927032/artifacts/158727916

**Comment by mhofman** [comment]
So I hadn't noticed it at first, but there is actually consensus failure earlier, not just in restart. It's just that the loadgen didn't have logic to notice the failure earlier than a restart.

Here is a different artifact with immediate failure: https://github.com/Agoric/agoric-sdk/suites/5211621213/artifacts/159428893 (from run https://github.com/Agoric/agoric-sdk/actions/runs/1809197541)
