### ISSUE TITLE
Need at least one Canary (follower) node on Mainnet

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Agoric#4478]
Agoric OpCo needs to maintain at least one follower node on Mainnet, so that we have a baseline to help in debugging.

**Comment by Tartuffo** [comment]
FYI: @arirubinstein

**Comment by dckc** [comment]
@warner did some relevant work recently...

![Screenshot 2022-03-13 at 12-24-50 ag0-follower-2 (Munin ag0-follower-2 ag0-follower-2)](https://user-images.githubusercontent.com/150986/158267824-9b8407ee-fbd7-45f5-a475-c7eaca87d202.png)

see also: #3769

disk usage is about 165GiB

see also: #4106

**Comment by arirubinstein** [comment]
This is completed

**Comment by dckc** [comment]
Are there at least two of us that understand how it works?

**Comment by arirubinstein** [comment]
I wrote up a quick link guide here, and will flesh it out a bit more as well: https://docs.google.com/document/d/1XQIQ2SB6OCtQoqFqNaf9SpXlIuQq4kspBgnbO1gcDpc/edit?usp=sharing
