### ISSUE TITLE
MVP Implementation of On-Chain Wallet API

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#4483]
Implement the backend as an adapter to the collection of existing wallet backends.

Define the minimal API surface.

The wallet UI needs an API from the on-chain wallet, the current functionality of the UI requires the following [schema](https://github.com/Agoric/agoric-sdk/blob/master/packages/wallet/ui/src/util/WalletBackendAdapter.js):
```
  const firstSchema = harden({
    actions: Far('schemaActions', {
      createPurse: (issuer, id = newId('Purse')) =>
        E(walletBridge).makeEmptyPurse(issuer?.issuerPetname, id),
      createContact: (depositFacet, id = newId('Contact')) =>
        E(walletBridge).addContact(id, depositFacet),
      createIssuer: (issuer, id = newId('Issuer')) =>
        E(walletBridge).addIssuer(id, issuer, true),
    }),
    services: iterateNotifier(servicesNotifier),
    dapps: iterateNotifier(E(walletBridge).getDappsNotifier()),
    contacts: iterateNotifier(E(walletBridge).getContactsNotifier()),
    issuers: iterateNotifier(E(walletBridge).getIssuersNotifier()),
    offers: wrapOffersIterator(
      iterateNotifier(E(walletBridge).getOffersNotifier()),
    ),
    payments: iterateNotifier(E(walletBridge).getPaymentsNotifier()),
    purses: iterateNotifier(E(walletBridge).getPursesNotifier()),
  });
```

The wallet contract will contain all the users' wallets and expose one of these schemas to each user. The objects within the schema (e.g. services, dapps, etc.) need to be typed and documented properly.

**Comment by turadg** [comment]
@michaelfig this is listed as part of https://github.com/Agoric/agoric-sdk/issues/5356 but this morning we didn't include it in the release planning. Which is correct? cc @dckc

**Comment by dckc** [comment]
In particular, does / should this block either of these?
 - #5356 
 - #5354

**Comment by dckc** [comment]
@michaelfig tells me yes, this blocks #5354

**Comment by dckc** [comment]
on further consideration, some work already done makes this not necessary.
