### ISSUE TITLE
make Smart Wallet contract multitenant

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#4484]
All the wallet backends need to be implemented by a single wallet manager contract, since it is inefficient to have many small vats when a large one would suffice.  Multitenant backend wallet states, which are managed by a single Zoe contract, are presented as sealed individual backends, each of the schema in #4483, and broadcasted via the Cosmos event stream.

To get there from here, we will
 - [x] upgrade the `packages/wallet/api` directory to be multitenant, indexed first by tenant (such as their Cosmos address), and produce the existing wallet as a specialisation of that code.  Then, the wallet manager is an instance of that code as well, but built to handle inbound Cosmos transactions.

 - [ ] To facilitate migration to virtual/durable objects and collection, each individual wallet backend must be supplied with a new schema manager rather than instantiating its own collections.

# Design

Look up a tenant by its address at the top level and get ocaps. One mapping from address to that object.
That tenant's wallet is like a vault, closing over their data.

**Comment by Tartuffo** [comment]
@michaelfig should this be assigned to you?  (currently @turadg who does not know much about wallet.)

**Comment by Tartuffo** [comment]
@turadg is multi-tenant done, should we rename this to "Make Smart Wallet contract durable?

**Comment by turadg** [comment]
This was primary about multitenancy (which is why it blocked the two things it blocks). I've made https://github.com/Agoric/agoric-sdk/issues/5894 and closed this.
