### ISSUE TITLE
change 'yarn test' to run all test programs in parallel

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4493]
When we switched to AVA (#1568), one of our goals was to increase parallelism of test execution. AVA will run multiple test programs in parallel (one per CPU core, I think), and within each test program, it runs some number of test functions in parallel. But our current `yarn test` just does `yarn workspaces run test`, which runs AVA in a single package directory at a time, limiting the opportunities for parallelism to the test programs of a single package.

The last step of #1568 was to change this to something like `'test': 'ava packages/*/test/**/test-*.js'`. One blocker was that our use of injection-based metering caused some tests to need different options than others, but https://github.com/Agoric/agoric-sdk/issues/1568#issuecomment-1031959243 points out that we no longer need that.

I'm not 100% sure this is a good idea. One reason is visual confusion caused by mixing messages from multiple packages running concurrently: the stdout/stderr messages we get during test execution are hard enough to read right now, and that's only mixing messages from one package at a time. The other is that most of our packages are pretty big, so we're already getting most of the benefits of parallelism.

The task is to run the experiment (unify all the options, change the top-level `package.json` to run all `test-*.js` in parallel) and measure the time it takes (please record your CPU speed and number of cores, that'll make a big difference), and see whether this would be an improvement or not.

**Comment by b4d2** [comment]
A note - ava runs in parallel by default, so even if the initial invocation was serial by directory, each directory would invoke ava with parallel runs by default.  This test shows running everything in serial, serial directories but parallel testing per each, and full parallel testing for all directories.  As far as test output goes, it appears that ava is smart enough to group out failures by package name which may alleviate concerns around readability.

Hardware: MBA M1 16gb 8 core 4/4

Net improvement: ~3 minutes 34 seconds (~25% improvement)

There are a significant number of low-cpu tests where this change would benefit the total time needed to test all packages


```diff
diff --git a/package.json b/package.json
index 4b9d4a18c..97b60aa81 100644
--- a/package.json
+++ b/package.json
@@ -87,7 +87,8 @@
     "lint-fix": "yarn workspaces run lint-fix",
     "lint": "run-s --continue-on-error lint:*",
     "lint:packages": "yarn workspaces run lint",
-    "test": "yarn workspaces run test",
+    "test": "ava -v",
+    "test:serial": "ava -vs",
     "test:c8-all": "rm -rf coverage/tmp && C8_OPTIONS=\"--clean=false --temp-directory=$PWD/coverage/tmp\" lerna run test:c8",
     "test:xs": "yarn workspaces run test:xs",
     "build": "yarn workspaces run build",
```

### master
```sh
time yarn test
yarn test:old  2339.28s user 299.54s system 366% cpu 11:59.17 total
```
<img width="454" alt="Screen Shot 2022-02-09 at 8 05 13 PM" src="https://user-images.githubusercontent.com/96506545/153335068-6a1db59c-bd8b-4997-80d7-5d52dc322fa0.png">
<img width="454" alt="Screen Shot 2022-02-09 at 8 07 59 PM" src="https://user-images.githubusercontent.com/96506545/153335303-288a2fb5-c415-45e7-a6d6-721698f057f7.png">


### patched

```sh
time yarn test
yarn test  2857.70s user 342.24s system 633% cpu 8:25.13 total
```
<img width="454" alt="Screen Shot 2022-02-09 at 8 18 28 PM" src="https://user-images.githubusercontent.com/96506545/153336379-c2c774da-bab0-4578-9eab-b871b13c6ac8.png">


### informationally - full serial all tests:

```sh
time yarn test:serial
yarn test:serial  1448.24s user 144.48s system 114% cpu 23:05.03 total
```
<img width="454" alt="Screen Shot 2022-02-09 at 7 47 50 PM" src="https://user-images.githubusercontent.com/96506545/153333500-2e1312fe-b3b1-49d9-88f0-8e6ac701c300.png">

**Comment by Tartuffo** [comment]
@warner Need 1 line change to top level JSON file, please confirm.

**Comment by turadg** [comment]
Closing as I think this issue is obsolete. CI runs test in parallel in different jobs. Locally we almost never test the whole repo. When you do, as stated above, the packages are so large that there is plenty of parallelism.
