### ISSUE TITLE
Change stores so deletes don't kill iterations

### ISSUE THREAD

**Issue by FUDCo** [Agoric/Agoric#4503]
## What is the Problem Being Solved?

The current implementation of stores has a rule that collection operations that add or remove keys (which is to say, `init` and `delete`) cause any in-progress iterations through that collection to fail with an error, on the conservative principle that since the world has changed since the iteration started, assumptions made at that start might now be mistaken.  This has run headlong into the practice of iterating through a collection that represents some work to be done and deleting elements as they are processed, a use case that turns out to be both common and necessary.

After some discussion we decided that, pending a more involved design dealing with all aspects of concurrent modification and iteration (including what happens if multiple iterations overlap), the most immediate need was to support the above mentioned use case.  The most direct way to do this is simply to allow deletions during iteration (though insertions will still kill iterations).

## Description of the Design

In the database-backed store implementation, iterators check a generation count on the collection being iterated, and throw if it changes, while insertions and deletions increment this generation count.  The change is just to stop incrementing the generation count when deleting.  We believe the ephemeral (in-heap) implementation has similar logic that should be modified similarly, though there's a wee bit of investigation involved.

## Security Considerations

Nothing new to see here, move along. 

## Test Plan

Currently there are tests to verify that the concurrent modification exception logic works.  This will need to be changed to check that it sometimes doesn't.

**Comment by warner** [comment]
closed by #4505
