### ISSUE TITLE
Virtual objects and virtual stores for ERTP

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4504]
## What is the Problem Being Solved?

Support an extremely large number of purses and payments.

## Description of the Design

Convert purses and payments to virtual objects and keep them in virtual stores.

## Security Considerations

Performance impact only. Should be done in a way that doesn't impact our confidence in previous security reviews and purple team exercises.

## Test Plan

Verify that purses and payments can be revived from persistent data.

Verify that a vat can support more purses than fit in the heap. It would be fine to do something based on a small virtual heap if there's a way to do that. A test that relies on exhausting the actual heap would be expensive.

**Comment by dckc** [comment]
close #2841 as a dup of this?

Note also some previous work:
 - #1830
 - #2526
 - #3356
 - #3357

**Comment by dckc** [comment]
In the test plan, how about testing that a vat can support more purses than fit in the heap?

**Comment by Chris-Hibbert** [comment]
Thanks for digging all that up, @dckc!  I added that to the test plan.  Do you know if it's possible to do that without exhausting the actual heap?

**Comment by dckc** [comment]
Exhausting the actual heap (before fixing this) would be the point. We do it routinely in `packages/xsnap/test`. For example:

```js
test('heap exhaustion: orderly fail-stop', async t => 
```
https://github.com/Agoric/agoric-sdk/blob/master/packages/xsnap/test/test-xs-limits.js#L19

**Comment by Tartuffo** [comment]
Per @erights, this is done.
