### ISSUE TITLE
Consensus mode with verbose logging

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#4506]
## What is the Problem Being Solved?
It should be possible to have some more verbose logging of at least the kernel / cosmic-swingset process while keeping the node in consensus mode. While it may not be possible to have the vats in logging mode and stay in consensus (e.g. args to console calls would be inspected, which triggers a different execution), the kernel process shouldn't be as sensitive.

It appears a cause of #4473 was that the follower node was both in `DEBUG=agoric` and consensus mode.

## Description of the Design
Some value of `DEBUG` or other env that doesn't cause consensus divergences.

## Security Considerations
I don't believe there's any?

## Test Plan
Put the loadgen in that mode.

**Comment by warner** [comment]
If #4510 can move `consensusMode` to a transaction/consensus-driven switch, then I think `DEBUG=` could be left to control the remaining logging things without causing divergence. So let's say that once #4510 is fixed then we can make those changes to satisfy this ticket.

@michaelfig you know what DEBUG= does better than I do, does that seem reasonable? Mind if I assign this to you?
