### ISSUE TITLE
connection closed error from docker wallet calls to devnet

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4509]
## Describe the bug

I can't import an issuer using the wallet nor call `addPool` on the AMM. In both cases, I get:

```
Promise.reject("Error: \"http://127.0.0.1\" connection closed")
```

## To Reproduce
1. Start wallet client using https://github.com/Agoric/agoric-sdk/wiki/Setting-up-an-Agoric-Dapp-Client-with-docker-compose
2. `agoric install coin-demo` using a fresh `yarn build && yarn install` from current master (93ef5ae3b6a741a5bf536111f5fb38af59d45660)
3. put `makeCoin.js` (source below) under `coin-demo/contract`; `cd coin-demo/contract`
4. `agoric deploy makeCoin.js`
5. in the wallet, go to Asset Issuers and hit **+ IMPORT**. Set name to Note and board id to 860941641. Hit import.
6. See "failed to import issuer" and in the console: `RemoteError(error:captp:http://127.0.0.1:8000#20002)#3: "http://127.0.0.1" connection closed`
7. At the REPL, run `E(home.board).getValue('860941641')` to get the issuer, `history[4]`, then `E(home.agoricNames).lookup('instance','amm')` then `E(home.zoe).getPublicFacet(history[6])` and `ammAPI = history[7]` and `E(ammAPI).addPool(history[4], 'Note')`
8. `Promise.reject("Error: \"http://127.0.0.1\" connection closed")`

## Expected behavior

Issuer added to the AMM.

## Platform Environment
 - what OS are you using? Linux. what version of Node.js? v16.13.0
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) prettier2-reformat-54-g93ef5ae3b

## Additional context

```
09:24 connolly@jambox$ agoric deploy makeCoin.js 
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /home/connolly/projects/agoric/coin-demo/contract/makeCoin.js
agoric: deploy: Deploy script will run with Node.js ESM
awaiting home promise...
publishing issuer, brand to board
{ issuer: '860941641', brand: '860941641' }
saving noteMint to personal scratchpad...
```

`makeCoin.js`:

```js
import { E } from '@endo/far';
import { deeplyFulfilled } from '@endo/marshal';

import { makeIssuerKit, AssetKind } from '@agoric/ertp';

/**
 * @param {Promise<{zoe: ERef<ZoeService>, board: ERef<Board>, agoricNames:
 * Object, wallet: ERef<Object>, faucet: ERef<Object>}>} homePromise
 */
const deployContract = async (homePromise) => {
  console.log('awaiting home promise...');
  const home = await homePromise;

  const kit = makeIssuerKit('Note', AssetKind.NAT, harden({ decimalPlaces: 2 }));
  console.log('publishing issuer, brand to board');
  const published = await deeplyFulfilled(harden({
    proposedName: 'Note',
    issuer: E(home.board).getId(kit.issuer),
    brand: E(home.board).getId(kit.brand),
  }));
  console.log(published);
  console.log('saving noteMint to personal scratchpad...');
  await E(home.scratch).set('noteMint', kit.mint);
};

export default deployContract;
```

cc @michaelfig

**Comment by dckc** [comment]
ag-solo log:
https://gist.github.com/9072494cab89edd7df3fa9e6bb10b9ad

**Comment by michaelfig** [comment]
This error happens because the deploy script exits, severing connections to all of its objects.  You could either put the issuer kit in a solo vat (via the spawner), or hack around and just hang the deploy script so that it doesn't exit (`await new Promise(() => {});` would work).

**Comment by dckc** [comment]
Ah. of course. thanks.
