### ISSUE TITLE
non-Inter precious state is reachably durable

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4511]
Title was previously "all contracts should be using virtual/durable objects for high-cardinality and upgrade-critical state". @turadg changed it to distinguish from https://github.com/agoric/agoric-sdk/issues/4983 and removed child tickets that aren't needed for MN-1.

## What is the Problem Being Solved?

As with #4383 (for Zoe), we need all our built-in contracts to start using virtual objects. Any state that might get large (high cardinality) needs to be stored in virtual objects. This requires defining `makeKind` behaviors for all such objects.

In addition, we need to prepare for upgrade. This involves switching from merely-virtual to "durable" objects for anything that the later versions of a contract will need access to. It also requires registering some handles and collections in the (as-yet-undefined) "baggage".

The transition from virtual to durable should be pretty simple, as should the registration/baggage component, so I'm comfortable doing that in a second step. But contract authors need to think about what data is necessary for upgrade as they perform the merely-virtual conversion.

## Description of the Design

Use `makeKind` and `makeDurableKind` for virtual objects, and `makeDurableStore` for collections.

~~There's a documentation task in #4518 .~~ _It turned out to be incoherent._

**Comment by dckc** [comment]
subsumed by #4983

**Comment by dckc** [comment]
closing this was a mistake; I somehow didn't see some related stuff.

**Comment by dckc** [comment]
@warner and I are confident this is subsumed by #5014 , #6553
