### ISSUE TITLE
Document how to use virtual collections with a seat

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4518]

**Comment by Tartuffo** [comment]
@dtribble Do you want this done in the MN-1 timeframe?

**Comment by Tartuffo** [comment]
Probably in progress.

**Comment by Tartuffo** [comment]
This is for external developers.  Moving to MN-1.1

**Comment by erights** [comment]
Hi @Tartuffo , I see this is assigned to me but I don't know what "use virtual collections with a seat" means? What is this issue about? Is this actually just the need to document virtual collections? (If so, we should probably reassign)

**Comment by Tartuffo** [comment]
@Chris-Hibbert you referenced this issue in #4534, can you add any info about this issue?

**Comment by Chris-Hibbert** [comment]
I don't remember knowing anything about this, and I don't see my fingerprints anywhere.  Like @erights, the title seems incoherent. I'd recommend closing it.

Perhaps @dckc knows something. He is annotated as having edited the top comment of #4534, where the link to this issue appears.

**Comment by dckc** [comment]
I can't reconstruct my reasoning for adding that link.

@turadg if there's anything from your experience working on #4534 that says there's important work to do here, please re-open this.
