### ISSUE TITLE
runStake: use virtual objects for high-cardinality state

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4534]
part of #4511
There's a documentation task in #4518 .

**Comment by Tartuffo** [comment]
@dckc Please put an estimate on this.

**Comment by Tartuffo** [comment]
@dckc Only the virtual objects part needs to be done for RUN Protocol RC0 in devnet.  Durable objects can come after.

**Comment by dckc** [comment]
So this should be split into 2 issues?

**Comment by Tartuffo** [comment]
> So this should be split into 2 issues?

Yes, for tracking completion of RUN Protocol Preview release, that makes sense.
