### ISSUE TITLE
Ability for vault observers to know liquidated vs closed

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4539]
## What is the Problem Being Solved?

The vault's notification stream has a `liquidated` flag that can be used to determine whether a vault was liquidated, but it currently is `state === CLOSED`. A user will want the ability to distinguish between vaults closed by them vs by liquidation.

That used to be achieved by `getLiquidationPromise()` from the vault, but https://github.com/Agoric/agoric-sdk/pull/4527 removed it because,
- it was much harder to implement in the redesign
- it created a second stream for notifications from the vault
- it wasn't used anywhere yet so handling that use case could be deferred (to this ticket)

## Description of the Design

Tentatively: add fourth vault state 'LIQUIDATED' and change the name of CLOSED to distinguish.

## Security Considerations
--
## Test Plan

--

**Comment by Chris-Hibbert** [comment]
so you want `closedByUser` and `liquidated` as distinct states?

**Comment by turadg** [comment]
> so you want closedByUser and liquidated as distinct states?

yes, that would suffice for this issue. Full enumeration is being considered in another ticket https://github.com/Agoric/agoric-sdk/issues/3712#issuecomment-1039407607

**Comment by dtribble** [comment]
From #3712
I think that we need to record whether the vault was closed normally or via liquidation. Also it will have a transferring state. So I think the states are:

ACTIVE - vault is in use and can be changed
LIQUIDATING - vault is being liquidated by the vault manager, and cannot be changed by the user
CLOSED - vault was closed by the user and all assets have been paid out
LIQUIDATED - vault was closed by the manager and ... what's up with the assets?
TRANSFER - vault is converted to user state
