### ISSUE TITLE
Refactor vault notifications to not cascade interest charge events

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4540]
## What is the Problem Being Solved?

#4341 required moving interest accrual state from the vaults to the vault manager. https://github.com/Agoric/agoric-sdk/pull/4527 makes it so that when vaults are charged interest, it only affects the manager's state. However the downstream consumers of the vault's state still assume that interest charges come through there so it echoed the manager's notifications. This won't scale to millions of vaults.

## Description of the Design

The Vault’s dapp can have close coupling with the vault manager. No need to be consistent with other dapps, so do whatever’s simplest.
Simpler to have two notifiers for this case.
Notifiers should always include units. 

When we do this is a good time to also rename `getDebtAmount` to `getActualDebtAmount`.

## Security Considerations
TBD
## Test Plan

TBD

**Comment by Tartuffo** [comment]
Problem is - how do we notify the UI?  Only want to the signal / notification to go to the specific Vault.  The right thing is to have a Vault Manager notifier (per currency).  FE needs to listen to the additional notifier.

**Comment by Chris-Hibbert** [comment]
What is the goal of renaming `getDebtAmount` to `getActualDebtAmount`?  @dtribble likes to point out that all notifications are asynchronous, so they're always out of date to some extent. Calling it 'actual' doesn't make it more timely, is the contrast with some other amount that's less 'actual'?

**Comment by Chris-Hibbert** [comment]
> What is the goal of renaming `getDebtAmount` to `getActualDebtAmount`? 

Ah, I see. In the code, it changes to `getCurrentAmount`, which emphasizes that it captures a point in time.
