### ISSUE TITLE
syscall.send to resolved promise should run-queue to object, not to promise

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4542]
## What is the Problem Being Solved?

While discussing #3465 with @mhofman yesterday, our plan (kobjs have priority, promise *subscriptions* have priority, deliveries have priority of their `send` target or `notify` subscription, vats can `syscall.elevate(koids)` exported objects up to the current delivery priority, `syscall.subscribe` inherits the current delivery priority) makes it awkward to have run-queue events that send a message to a *promise*, rather than an object.

Currently, `syscall.send(target=object)` and `syscall.send(target=promise)` do exactly the same thing: they push a `send` event onto the run-queue with the given target. When this event reaches the front of the run-queue, `deliverToTarget(objectOrPromise)` looks at the target to see whether it's an object or a promise. If it's a promise, it looks at the status. If the promise is resolved to an object, the code delegates (recurses just once) to `deliverToTarget(object)`. If the promise resolved to a non-object or rejected, it rejects the result promise. And if the promise is unresolved, the message is pushed onto the kernel promise table's `pendingMessages` queue.

Later, if/when the promise is resolved, all those `pendingMessages` are pushed onto the back of the run-queue (unmodified, still targeting the promise), and they make a second journey through the queue. When they reach the front, they are handed to the same `deliverToTarget` as before, but this time the promise-status check reports "resolved (to object)", and the messages are delivered to a vat object.

I'm pretty sure this extra loop is unnecessary and bad for performance. I remember feeling lazy about it when I implemented it that way, but not being sure of what ordering properties were involved, so I've left it alone until now.

But more importantly, if the run-queue can hold messages aimed at a Promise, we don't have a story for what priority those messages should have (in this new plan). It would be restrict the run-queue to messages aimed at just objects.

## Description of the Design

So the plan would be:
* `syscall.send()` looks at the target immediately, and if it is a promise, check the resolution status:
  * if resolved-to-object, retrieve the `koid`, and push a run-queue event *to that object*
  * if resolved-to-non-object or rejected, resolve the result promise immediately
    * (note: this will happen before the vat has a change to `syscall.subscribe()`, so make sure the now-rejected promise doesn't get deleted or collected or anything too early, and make sure subscribe-after-resolve works well)
  * if unresolved, push the message onto the promise table's `pendingMessages` queue, not the run-queue

I need to think about what ordering properties the old approach had, and how this new approach might be different, and if anything could/should care.

## Security Considerations

Ordering property changes might be surprising.

## Test Plan

Unit tests.

**Comment by mhofman** [comment]
Thanks for the write up! I was thinking also that if necessary, we could still have a "delivery run-queue" where all syscalls made during a delivery end up temporarily and would be processed immediately after the end of the crank.

As for the ordering properties, I suppose the only thing this approach changes is that if a vat holds an presence and a resolved promise for that presence, then a message sent to the promise first would be delivered to the object before a second message sent to the presence, compared to now where the message sent to the promise would always be delivered after the message sent to the presence.

**Comment by mhofman** [comment]
Moved to https://github.com/Agoric/agoric-sdk/issues/5024#issuecomment-1101924739
