### ISSUE TITLE
Restart based test for divergence

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#4557]
## What is the Problem Being Solved?
With the addition of https://github.com/Agoric/agoric-sdk/pull/4133 and https://github.com/Agoric/agoric-sdk/pull/4256, we now have an integration test that can detect simple causes of divergence (closing https://github.com/Agoric/agoric-sdk/issues/3444).

However in the past we've encountered other triggers for divergence between nodes, in particular when a node restarts, e.g.:
- https://github.com/Agoric/agoric-sdk/issues/4159
- https://github.com/Agoric/agoric-sdk/issues/3471
- https://github.com/Agoric/agoric-sdk/issues/3726

## Description of the Design
A testnet with at least 4 nodes, with loadgen applied, where one node at a time gets randomly restarted. For best results, the loadgen should use a random RPC node which will get restarted.

## Security Considerations
None

## Test Plan
Probably part of a standalone nightly test.

**Comment by ivanlei** [comment]
From @mhofman in slack --

> Yeah the issues about hunting down divergences now have a better story given the improvements I've made to replay tools. I think we no longer need to use the loadgen or instagoric as the means to detect these. We could still use them, but mostly to generate transcripts that could be used as input to the replay tools.
