### ISSUE TITLE
Isolate BLD issuer / mint in its own contract vat

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4578]
## What is the Problem Being Solved?

The BLD issuer kit is created in the bootstrap vat, which means that the mint, issuer, and all the purses are there too. The bootstrap vat gets access to extremely high authority objects; it should _only_ partition access to those object among other components. Running the BLD mint in the same vat is awkward w.r.t. POLA.

## Description of the Design

Create a new contract whose only job is to create an IssuerKit. In fact, the `mint` could be the `creatorFacet` and the issuer could be the `publicFacet`.

## Security Considerations

See problem description above.

## Test Plan

It's not clear that this should result in any observable differences, so basic unit tests for the new contract, plus all the existing tests, seem to suffice.

cc @dtribble @Chris-Hibbert

**Comment by Chris-Hibbert** [comment]
> Create a new contract whose only job is to create an IssuerKit. In fact, the mint could be the creatorFacet and the issuer could be the publicFacet.

Huzzah!  I like this idea.
