### ISSUE TITLE
Telemetry for the Kernel

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4585]
Per our [Observability meeting](https://docs.google.com/document/d/1TuaCxiLPqygQsYQ86VdoWQgcBur4Pi7RR2QY0hYbLw0/edit#) on Feb 17, here are areas of the kernel to instrument:

1. Length of run queue(s)
2. Number of computrons and cranks consumed in a block (probably cosmic swingset)
3. Are we approaching hard limit of computrons / crank (could be an infinite loop)
4. Amount of time doing swingset computation per block
5. Vat manager: number of Vats extant, number of Vats created and dropped / evicted.
6. Key data structures: object table, promise table, clist (from kernel stats)
7. Data publish device - requests / second
8. We should identify all of our resource checks, and put metrics around those.
9. How frequently BOYD is called, and how long BOYD took

**Comment by Tartuffo** [comment]
@warner FYI

**Comment by mhofman** [comment]
Not swingset stat per se, but exposing in Honeycomb how many cosmos deliveries are made into swingset (bridge, wallet, etc.)

**Comment by mhofman** [comment]
Maybe combined with how many cranks happened in a block (currently a proxy is simply to count distinct crankNum and plot over time)

**Comment by arirubinstein** [comment]
Adding a few request:
- All log events are structured json
- All log events include the closest trace id, allowing us to correlate logs to a specific span
- Generalize names of spans so our logs can break out spans into services (e.g. vats, major components of the kernel)
- Traces to be pushed via the opentelemetry tracing platform

**Comment by Tartuffo** [comment]
We've got enough done for PSM RC0, anything else we need we can stand up in a separate follower.
