### ISSUE TITLE
Build bridge which gets RUN Proto economic notification, exposes via Prom end points

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4587]
Per our [Observability meeting](https://docs.google.com/document/d/1TuaCxiLPqygQsYQ86VdoWQgcBur4Pi7RR2QY0hYbLw0/edit#) on Feb 17, here are areas of RUN Protocol to instrument:

1. Contracts can log data using notifiers
  a) There’s concern that allowing contracts to log using the same mechanism would allow them to spam the system.
  a) AMM
  b) All currencies and ratios
  c) rade volume/velocity
6. Vault Manager
  a) Number of vaults
  b) Outstanding debt, collateral held
  c) How many are within epsilon of default? (maybe exposed by blockchain explorer?)
10. getRUN
  a) Net amount minted
  b) Total collateral
  c) Distribution of utilization of loan amount

**Comment by Tartuffo** [comment]
This can be done after primary code completion, but before going live.  E.g. when the code is out there as a RC.

**Comment by turadg** [comment]
This ticket has been scoped for econ operations. If there's an security/stability operations, please make a new ticket or point to a better ticket for the econ aspects.

In Run Proto meeting today @btulloh identified these requirements that the Econ committee needs on launch:
- Total RUN minted ever
- Total RUN burned ever
- Per debt limit (contracts authorized to mint RUN), the limit and RUN outstanding to debt limits
- Counts in reserve of PCV tokens

**Comment by ivanlei** [comment]
This has been "lost to the sands of time" and is quite out of date. Closing this in favor of the slightly newer #5854
