### ISSUE TITLE
Telemetry on Canary (follower) node

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4589]
Per our [Observability meeting](https://docs.google.com/document/d/1TuaCxiLPqygQsYQ86VdoWQgcBur4Pi7RR2QY0hYbLw0/edit#) on Feb 17, here are areas of our follower node to instrument:

1. Some Prometheus metrics are exposed by Cosmos, can monitor a fairly large set of details, but most/all validators will not give us an open firewall, to prevent DDOS.
2. Our follower node will be the only one we can really monitor ourselves.  What to monitor:
  a) Mempool (growth is already tracked)
  b) Size of things in mempool?
  c) Requests / sec / kind (already exposed)
  d) Lag between message coming in and when it is included in a block (this depends on the block proposer).
7. We’d like to start spans at the Cosmos / Tendermint level
8. I/O performance, e.g. IAVL writes / throughput (may be replaced by sparse Merkle tree)

Also:  Load average, CPU utilization, memory utilization, disk I/O

**Comment by Tartuffo** [comment]
In today's Eng Sync we agreed that we would monitor our Follower Node and set up alerts to send email to an appropriate target group when problems are detected (key metrics exceeding thresholds, patterns found in the slog files, etc.).  If possible, we may have an external paid party also be notified (probably via PagerDuty) who can do some initial triage and determine if the issue is widespread and serious enough to wake up team members.  And/or we can provide a mechnism for validators to assert there is a serious problem on the chain, and if there is a consensus, trigger a PagerDuty alert.

**Comment by Tartuffo** [comment]
This could be delayed until after primary code completion.

**Comment by Tartuffo** [comment]
@JimLarson this involves using Open Telemetry libraries in the golang side.

**Comment by Tartuffo** [comment]
FYI: @arirubinstein

**Comment by arirubinstein** [comment]
Collected and implemented today


Scraped: 
- All Kubernetes metrics
- All VM/Pod metrics (disk space, cpu, io, etc)
- All Tendermint prometheus metrics
- All Cosmos prometheus metrics
- All swingset prometheus metrics (automated, but only in devnet)
Pushed:
- Swingset OTEL trace spans (automated, but only in devnet)

Things that are outside of the initial implementation:
- Starting spans at the cosmos layer (may require cosmos upstream work)

**Comment by arirubinstein** [comment]
@Tartuffo do we want to break out the cosmos spans into a separate issue?

**Comment by Tartuffo** [comment]
Yes, I think spans should be a separate issue.

**Comment by arirubinstein** [comment]
looks like it's already captured in #4583 - since this is already wired up, I'm going to mark this as closed
