### ISSUE TITLE
Add limits for amounts between vault and vault manager

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4599]
## What is the Problem Being Solved?

Right now the amounts being passed between them have no limits. We should have them as a security/reliability assurance. 

## Description of the Design

Some ideas in https://github.com/Agoric/agoric-sdk/pull/4527#discussion_r810199659
- it should never be more than the max allowed for a vault
- should never be larger than this manager's total debt (so a bug in one manager can screw up the debt limit on the overall service)

## Security Considerations

Improvement.

## Test Plan

--

**Comment by Tartuffo** [comment]
Consider at Restival.

**Comment by Tartuffo** [comment]
We the decided the Vault should call the Vault Manager for minting.  (RUNStake should do the same thing.)

**Comment by dtribble** [comment]
The vault calling the manager to simultaneously mint and record that in the stats works well. And doing the same thing with `burn` ensures that the number is only debited when tokens are actually burned.

**Comment by dtribble** [comment]
This was addressed via moving minting into vaultManager
