### ISSUE TITLE
Property-based testing of AMM calc failed in CI

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4601]
## Describe the bug

In CI, @warner saw this  https://github.com/Agoric/agoric-sdk/runs/5251436118?check_suite_focus=true
It's the result of a new property-based test checked in with #4519.

At the last minute, I removed maximum limit on some values. #4600 reinstated the caps. This issue is for investigating whether the failure represents an actual issue in the code.

## Expected behavior

Property based testing uses random inputs. The version run in CI should probably use a stable seed, but only after sufficient runs to be sure there aren't uncovered corner cases.

## Platform Environment

This ran in CI. Other than reproducing the random seed, it's reproducible locally.

## Screenshots

![Screenshot 2022-02-18 at 09-51-11 merge bundle_vat-admin devices add waitForBundlecap() · Agoric_agoric-sdk@9f531c5](https://user-images.githubusercontent.com/13372636/154747107-2b3386a0-91dd-4991-91e8-df4c833d5ad8.png)

**Comment by Chris-Hibbert** [comment]
This is a case where there's too little in the pool initially to adequately represent the ratio of x and y being added to the pool.  The ratio between giveX=259759883662327545569828139124179253678021057075999500032721111752654434904 giveY=95378744968141100622444478270475529125895278461869363858523679558487987746315,

is 367.   The initial pool has 127 x 136.  That gives a starting K of 17272.   In order to approximate that K at a ratio of 367:1, you end up with 2518 as Y, and have to choose between 6 and 7 for X (6.8 would be ideal).  The AMM always uses floorDivide, so you end up with 6*2518, which is 15108, which is significantly different from 17272.   The test wants them to be within 5% of each other, and these values aren't that close.  

I don't think it's worth adding extra protection around the calls to reject situations like this, but the answer is don't add astronomical amounts of collateral when there's a miniscule amount in the pool.

**Comment by dckc** [comment]
I'm content with `max: oneB` i.e. `1_000_000_000n`.

I would prefer `max: oneB * dec6` where `const dec6 = 1_000_000n` to match the 6 digit convention in the cosmos community (ATOM, RUN, BLD, ...) but I can live without it.

If we plan to use WETH in this protocol, I'd like to see what happens with `max: oneB * dec18`. Again, I can live without it.

**Comment by dckc** [comment]
In discussion with @rowgraus , I learned:
WETH will probably be necessary to support in the not too distant future.
On the first launch we can assume 10k+ RUN.
