### ISSUE TITLE
Overhaul virtual objects API to address various problems found adapting code to it

### ISSUE THREAD

**Issue by FUDCo** [Agoric/Agoric#4606]
## What is the Problem Being Solved?

Recently, @erights and @dtribble undertook an exercise to estimate the difficulty of adapting our various contracts from the currently ubiquitous objects-as-closures style to instead use virtual objects. The exercise was to take one of the existing contract objects, convert it, and see how hard the conversion effort actually ended up being in practice. We anticipate quite a bit of this kind of conversion will be needed in preparation for MN-1 and so we want to get a handle on how much effort all this will take.  The exercise went mostly smoothly, but the code choked on a bug when they tried to test it.  @erights and @FUDCo traced the bug to a re-entrancy issue in virtual object initialization.  In the course of sorting this out we identified a way to change the `makeKind` API to prevent the problem situation from even being possible, as well as to make it much more obvious to a developer how to rework the code to accomplish the job that the problematic code had been trying to do in the first place.  Since we anticipate some of the other contracts may find themselves in a similar situation, it made sense to examine this API change concept more closely, which we did.  The outcome of this discussion was a strong consensus between @erights, @FUDCo, and @warner that this revised design was superior to the present one in almost every aspect, and so made the decision to proceed with it.

## Description of the Design

The revised design for `makeKind` replaces the current single, rather complicated parameter (I won't restate the existing API design here; consult the SwingSet `virtual-objects.md` document for details) with three parameters: a documentary tag string, an `init` function, and an `actualization` function (the names of the parameters are subject to revision if/when we develop better terminology; they are not material to the published API as these names are principally for documentation purposes).  We also decided, while we were at it, to rename `makeKind` to `defineKind`, to better reflect its purpose and to slightly reduced the bewildering variety of things we have named `makeXXX`.  The new API is thus:
```
makerFunction = defineKind(tagString, init, actualize);
```
where:
* `tagString` is a documentary tag string, exactly as used in our `Far` function (and we mean "exactly" because that is what it will be used for)
* `init` is an initialization function, taking as args whatever initialization arguments are desired by the kind developer and returning a plain JS object representing an initialized state for the object.  This replaces the `init` function returned by the instance kit maker that the current API uses.  It differs in that it generates and returns the state object itself rather than closing over an empty one that is provided for it that it just populates.
* `actualize` is a function that provides the behavior for instances of the virtual object.  It takes one argument, `state`, which represents the state of the virtual object, and returns an object full of methods that becomes the actual in-memory representative of the virtual object.  It replaces the `self` property returned by the instance kit maker that the current API uses.  It differs from `self` in that it is a function that returns a value rather than a value directly.

The return value from `defineKind` is an instance maker function exactly the same as that currently returned by the present `makeKind`.

A notable consequence of this design is that the `init` function has no access to the actualized self and `actualize` function only ever sees a fully initialized object state (which was the proximal cause of the reentrancy problem mentioned above).

## Security Considerations

There may be undiagnosed, slippery determinism/GC visibility issues associated with the virtual object machinery in general (though we have taken care to prevent these and are reasonably confident that we have been successful, that is still an unproven hypothesis).  However, we are fairly confident that this API change does not introduce any new such issues that were not already present.

## Test Plan

Once the existing body of virtual object implementation tests are rewritten to make use of this new API, those tests should be sufficient to exercise this API as well.

**Comment by zarutian** [comment]
[My understanding of how that API behaves](https://gist.github.com/zarutian/22f7bf743493106069e500ce07a9e603). Feel free to ignore.
