### ISSUE TITLE
`yarn test` fails locally on a clean agoric-sdk master

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#4616]
## Describe the bug

`yarn test` fails locally on a clean agoric-sdk master. However, I believe it does ***not fail under CI***.

## To Reproduce

What I did

$ git checkout master
$ git pull
$ git status # verify on clean master
$ find . -name node_modules -exec rm -rf {} \;
$ yarn && yarn build
$ cd packages/cosmic-swingset
$ yarn test test/test-make.js

## Expected behavior

passes. Instead it fails with
```
  make scenario2-run-chain-to-halt is successful

  Difference:

  - 2
  + 0

  › ChildProcess.<anonymous> (file://test/test-make.js:32:9)
```
See the attachment below for the full yarn test log.

## Platform Environment
 - what OS are you using?
       MacOS 12.2.1 M1 Pro

 - what version of Node.js?
       v16.13.1
       Also go version go1.17.6 darwin/amd64

 - is there anything special/unusual about your platform?
       Not that I know of.

 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
       prettier2-reformat-113-ga5de8dd29

## Additional context

[bad-log.txt](https://github.com/Agoric/agoric-sdk/files/8105527/bad-log.txt)

**Comment by kriskowal** [comment]
I was unable to reproduce with Mac OS, Node.js v14, at the same hash prettier2-reformat-132-gde29ce090 de29ce09004b2540bdcff54b0d15b2a68e9c0854
, running the test 12 times to check for non-determinism. I’ll run again with Node v16.

**Comment by kriskowal** [comment]
I was unable to reproduce with Node.js 14.19.0 on MacOS 10.15.7 through 7 successful runs.

**Comment by Tartuffo** [comment]
Not reproducible.
