### ISSUE TITLE
Type checker in IDE and CLI/CI sometimes disagree

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4620]
## Describe the bug

Presently, successful type checking depends on a `--maxNodeModulesJsDepth` flag which IDE use doesn't support. In some cases, `@ts-expect-error` can't be used because the IDE and CLI/CI disagree about the set of errors.

## Expected behavior
Set of errors reported by type checker is consistent no matter where it's run.

## Additional context

https://github.com/Agoric/agoric-sdk/issues/4560 will fix that but that's a work item and this ticket is the bug itself. Easier to find by title search and more clear when linked to from code as to why. When that's resolved it would be good to find the `ts-ignore` we resorted to and replace them with `ts-expect-error` where possible. I'm assigning this to myself to take care of that.

**Comment by erights** [comment]
Since we've made progress on removing `--maxNodeModulesJsDepth`, should this bug still remain open?

**Comment by turadg** [comment]
Unfortunately it's still a problem. https://github.com/Agoric/agoric-sdk/pull/6575 changes the `ts-ignore` to `ts-expect-error` and there are numerous errors reported:
https://github.com/Agoric/agoric-sdk/actions/runs/3483412832/jobs/5826921492
https://github.com/Agoric/agoric-sdk/actions/runs/3483412832/jobs/5826921018

Sampling,
```
Error: ../vat-data/src/far-class-utils.js(206,3): error TS2322: Type 'M & RemotableBrand<{}, M>' is not assignable to type 'T & RemotableBrand<{}, T>'.
  Type 'M & RemotableBrand<{}, M>' is not assignable to type 'T'.
    'T' could be instantiated with an arbitrary type which could be unrelated to 'M & RemotableBrand<{}, M>'.
Error: ../SwingSet/src/controller/controller.js(289,5): error TS2578: Unused '@ts-expect-error' directive.
Error: ../SwingSet/src/controller/controller.js(291,5): error TS2578: Unused '@ts-expect-error' directive.
Error: ../SwingSet/src/kernel/kernelSyscall.js(208,18): error TS2532: Object is possibly 'undefined'.
Error: ../SwingSet/src/kernel/kernelSyscall.js(210,20): error TS2532: Object is possibly 'undefined'.
Error: ../SwingSet/src/kernel/state/kernelKeeper.js(217,5): error TS2578: Unused '@ts-expect-error' directive.
Error: ../SwingSet/src/lib/storageAPI.js(166,7): error TS2578: Unused '@ts-expect-error' directive.
```

They could probably all be solved with some additional typing work. If we did that, we still wouldn't have the "Expected behavior" ,
>Set of errors reported by type checker is consistent no matter where it's run.

…because more could pop up until we solve this structurally with https://github.com/Agoric/agoric-sdk/issues/4560

**Comment by turadg** [comment]
We can fix this with https://github.com/typescript-eslint/typescript-eslint/pull/6754

It will probably make CI run faster too and may solve https://github.com/Agoric/agoric-sdk/issues/5788
