### ISSUE TITLE
Robust Cosmos SDK state rollback

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Agoric#4624]
## What is the Problem Being Solved?

The Cosmos SDK modules frequently perform speculative execution of transactions/messages, capture a result or error, then throw away the accumulated state to roll back the execution.  If SwingSet state is also mutated and not also rolled back before commit, this breaks the correspondence of Cosmos to SwingSet state.

This happens at least for:
- to process an `x/gov` proposal submission, Cosmos validates the proposal by speculatively executing the enactment handler, then discarding the enactment state
- during transaction simulation (at any time on an RPC node), Cosmos speculatively executes the transaction, then records the consumed gas, and finally, discards the execution state

## Description of the Design

Instead of calling JS functions from arbitrary Cosmos modules, only do side-effects within the `x/swingset` lifecycle events `BEGIN_BLOCK`, `END_BLOCK`, and `COMMIT_BLOCK`.

All other Cosmos interactions with SwingSet will be in the form of adding an action record to the `actionQueue` in the Cosmos kvstore state, for later dequeuing (and deletion) by cosmic-swingset during one of the lifecycle events.  Because this state is kept and updated in the kvstore, it will be properly rolled back if the kvstore changes are discarded before the lifecycle event.

The above queuing will be the coordination mechanism for any other per-message state changes.  This also enforces that responses from SwingSet are guaranteed to be asynchronous, and no leakage of nondeterministic behaviour results can propagate from cosmic-swingset back to the Golang code doing the queuing.

### Large data

Some transactions, like the bundlecaps upload transaction, require more storage than easily fits in the kvstore.

As an example of out-of-band data communication, we will queue an action describing a deterministic filename (indicated by a kvstore counter) and what to do with it, capturing additional data into that filename in a single-block-only staging directory.  Cosmic-swingset will delete this staging directory's contents upon `BEGIN_BLOCK` before consuming a new `actionQueue`.  If the action is rolled back, then the deletion step ensures that disk space is recovered.

It may be desirable to use this large data feature for any kind of data that is user-generated, in order to reduce memory pressure on the kvstore in exchange for potentially slower throughput.

## Security Considerations

Better partitioning between Cosmos and JS.

**Comment by dckc** [comment]
closed per @michaelfig
