### ISSUE TITLE
send `dispatch.startVat` to setup()-based vats too, remove comms DB initialized check

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4637]
## What is the Problem Being Solved?

https://github.com/Agoric/agoric-sdk/pull/4575#discussion_r809758731 suggests sending `dispatch.startVat()` to `setup()`-based ("raw") vats too, not just liveslots-based ones. At the time, I couldn't think of a use case for it, but looking at some old tickets, I realized there's a performance improvement to be had.

Commit 683b77108dbb6afaf6b2557dfacae2298016eaca (to fix #3726) makes the comms vat do a DB read on every delivery, because it must do some one-time initialization, and we can't use an in-RAM flag to remember whether it's been done or not (because comms does not use a transcript). We could save that DB read if the kernel could promise that it would inform the comms vat about initialization, exactly once (for the lifetime of the durable state).

## Description of the Design

* change `kernel.js` `processCreateVat()` to call `processStartVat()` (or whatever refactoring #4636 suggests) unconditionally, instead of only when `enableSetup` is false
* update all unit tests that use raw vats to provide a dummy `dispatch.startVat` (except for the new unit test that asserts that it is called, exactly once, even when the kernel is restarted)
* change comms to perform it's one-time initialization in response to `dispatch.startVat`, instead of checking the DB flag on every delivery

## Security Considerations

none

## Test Plan

unit tests

**Comment by Tartuffo** [comment]
Nice to have, not critical (would remove a syscall from every comms message).
