### ISSUE TITLE
Expose important economic data as RPC-backed subscriptions

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4639]
This data can be used in Blockchain Explorers and via sites like The Graph for the community to get key information about the state of the RUN Protocol components.

Values will be emitted as a stream of states (cf. [Notifiers and Subscriptions](https://agoric.com/documentation/guides/js-programming/notifiers.html)) published into cosmos chain storage (which is a map where values are strings and keys are strings representing a dot-separated hierarchical path, e.g. "animalia.arthropoda.crustacea.malacostraca.decapoda") and ideally also [events](https://docs.cosmos.network/master/core/events.html), and consumable as a "prefix-lossy" subscription reading from the associated key.

From [our meeting on Feb 22](https://docs.google.com/document/d/1HkNLG8Kmm9DV6XGxvZEGVWUtHli2OfkR5ph7Q77x3QE/edit#), here is the data we want to expose:

1. AMM
    1. All trading pairs, the algo for them
    2. The pool amounts (X, Y, LP)
    3. Trades as they occur
    4. Liquidity change events (add, remove)
    5. Governance parameters, contract terms, fees
2. Vault Factory
    1. Per Contract
        1. Governance parameters, contract terms, fees
        2. Allowed collateral types
        3. Current reward pool (fees collected so far)
        4. Number and amount of shortfall
    2. Per Collateral
        1. Governance parameters, interest rate, liquidation ratio, liquidation penalty per collateral
        2. Current debt limit
        3. Number of vaults
        4. Outstanding debt, collateral held
        5. Compounded interest
        6. Liquidation strategy (may be per contract)
        7. Liquidation state (how much is currently being liquidated)
    3. Per Vault
        1. Debt
        2. Collateral
        3. Interest snapshot (used to calc the compounded interest per collateral)
        4. Status (open, closed, liquidating)
3. Liquidation contract
    1. Governance parameters (price impact limits, rate limits)
    2. Collateral and debt that it is currently working on.
    3. Cohort sale event (with price and the net shortfall)
4. Reserve Contract
    1. How much of each asset type
    1. Size of the reward pool?  (Question for Chris)
    1. Governance parameters
5. Price Authourity
    1. For each asset
    2. Aggregate price
    3. Source information (per oracle node operator)
    4. Governance parameters
6. runStake
    1. Per Contract
        1. Net amount minted
        2. Total collateral
        3. Distribution of utilization of loan amount (?)
        4. Governance parameters (debt limit, allowed ratio, interest rate curve)
    2. Per Account
        1. Locked BLD amount
        2. Debt
        3. Interest rate (?)

**Comment by Tartuffo** [comment]
@Chris-Hibbert wrote: "AIUI, the reward funds are currently directed to the cosmos-level vbank, where they are distributed directly.  I think this shows up in the bootstrap wiring as rewardDistributor."  So we'll need a ticket for that.

**Comment by turadg** [comment]
I think all necessary data is in for Vaults Release. If any is missing, please file new issues.
