### ISSUE TITLE
Expose key Reserve Contract economic data via subscription

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4651]
This data can be used in Blockchain Explorers and via sites like The Graph for the community to get key information about the state of the RUN Protocol components.

From [our meeting on Feb 22](https://docs.google.com/document/d/1HkNLG8Kmm9DV6XGxvZEGVWUtHli2OfkR5ph7Q77x3QE/edit#), here is the data we want to expose from the Reserve Contract:

1. How much of each asset type
2. Governance parameters

We had initially thought the Reward Pool would be housed here, but @Chris-Hibbert wrote: "The collateral reserve contract holds funds from various sources. Its main goal is holding assets that governance decisions can direct to the AMM or other uses. It is unlikely to be the main repository for reward funds."

**Comment by dckc** [comment]
amount of RUN minted seems to be missing. The reserve contract can mint RUN.

@btulloh @Tartuffo @rowgraus do we want a dashboard of total RUN minted?

**Comment by btulloh** [comment]
We would like a dashboard that shows total IST in circulation, which should be total IST minted - total IST burned.  For example, the top graph at https://daistats.com/#/overview that shows total DAI relative to the Total Debt Limit.

**Comment by Chris-Hibbert** [comment]
#5431 added publishing of metrics from the Reserve. It only included pool balances and current shortfall.
