### ISSUE TITLE
Expose key Price Aggregator economic data via subscription

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4652]
This data can be used in Blockchain Explorers and via sites like The Graph for the community to get key information about the state of the RUN Protocol components.

From [our meeting on Feb 22](https://docs.google.com/document/d/1HkNLG8Kmm9DV6XGxvZEGVWUtHli2OfkR5ph7Q77x3QE/edit#), here is the data we want to expose from the Oracle:

1. For each asset pair
    1. Aggregate price https://github.com/Agoric/agoric-sdk/pull/5850
    2. Source information (per oracle node operator) Deferred to https://github.com/Agoric/agoric-sdk/issues/5854
3. ~Governance parameters~ there are none

Output stream of priceAggregator should be the same as its priceAuthority.

**Comment by dckc** [comment]
oracle providers provide unit prices

for aggregate: use output from flux aggregator...
