### ISSUE TITLE
Account provisioning: charge BLD for smart wallet

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4654]
## What is the Problem Being Solved?

In #4402 we discuss fee aspects of ~~RUN~~ IST onboarding, but there is also a question of provisioning accounts; that is: for creating an on-chain c-list and associating it with a cosmos account (key pair). How do we appropriately recover the cost of this operation?

Our devnet account provisioning process depends on a [discord faucet bot](https://github.com/Agoric/faucet) on our discord service to mitigate griefing and sybil attacks.

Additional open questions:
 - [ ] should we "walk before we run" w.r.t. the number of `SMART_WALLET` accounts, while we gather confidence in system performance?
 - [ ] provisioning ag-solo (`REMOTE_WALLET`) accounts is higher risk. how to manage that risk?

## Description of the Design

?

note [Feb 24 proposal](https://github.com/Agoric/agoric-sdk/issues/4654#issuecomment-1050386681)

## Security Considerations

_see problem statement above_

## Test Plan

_IOU_

cc @Tartuffo @michaelfig @dtribble @warner

**Comment by dckc** [comment]
@michaelfig and I think we have a design:

Scenario: User Una wants to accept (make) an offer (for example, to getRUN or to trade on the AMM or to take out a Vault). How does Una communicate with Zoe or any other object in the Agoric blockchain VM? @michaelfig and I concluded that _some_ introduction mechanism is necessary to join the Agoric society where members enjoy the benefits of offer safety etc. Una must have 1 BLD. Una uses a wallet web UI to send a "please provision" message that (1) liens gp=1 BLD and (2) creates a c-list and on-chain wallet.

Una can then proceed using `WalletAction` messages as in #4406 .

or RUN?

gp is a governable parameter

p.s. Alice...

**Comment by dckc** [comment]
cost?
JS "find or create" - small. 3.
cosmos level - more expensive.

option: free if they already have BLD?
easier to game

nearby issue: how to get my friend in Agoric when my BLD is locked? how much does it take to earn 1 BLD in 1 month from staking rewards?
"sponsoring" other "users"?

**Comment by Tartuffo** [comment]
@dckc I created #4723 to capture the "how to help a friend create an account" use case.  Assigned to @rowgraus , and put it in the general Product Backlog (not MN-1).

**Comment by dckc** [comment]
@samsiegart writes in https://github.com/Agoric/agoric-sdk/pull/5860#pullrequestreview-1056212401 :
> we will at some point want `provideSmartWallet` to be callable in this same way so a user can create their wallet from the browser.

The Feb 24 design above is one answer.

But I wonder if it's overkill. In order for the cosmos layer to check a signature, an account has to exist; that is: some tokens must have been sent there. Perhaps that's enough, initially? Yes, somebody could send a worthless token over IBC to get an account created... but maybe that's an acceptable risk, initially?

**Comment by dckc** [comment]
## SMART_WALLET option for instagoric faucet

@samsiegart 's [Smart Wallet AMM Trade](https://gist.github.com/samsiegart/9a81face0a8683fdb2ebb72c600a6563) notes include:

```
$ make ACCT_ADDR=agoric14l44ylg9kexqafvdxwacrzg5g0fal8ud0wl586 AGORIC_POWERS=SMART_WALLET fund-acct provision-acct
```

where `provision-acct` is

https://github.com/Agoric/agoric-sdk/blob/6b7b997439c86d21c2e181d7b4fa5e9970dd6014/packages/cosmic-swingset/Makefile#L216-L220

For end-to-end testing of an AMM swap (#5073), I'm inclined to add a corresponding `SMART_WALLET` option to the [instagoric faucet](https://github.com/Agoric/instagoric/blob/9f7505fd9ea53169f6eb12b7912becff8bcdaa84/bases/shared/instagoric-server/server.js#L348-L352).

cc @arirubinstein 

p.s.
 - https://github.com/Agoric/instagoric/pull/2

**Comment by dckc** [comment]
@dtribble @rowgraus as we have discussed, I added a couple questions to the problem statement:

 - should we "walk before we run" w.r.t. the number of `SMART_WALLET` accounts, while we gather confidence in system performance?
 - provisioning ag-solo (`REMOTE_WALLET`) accounts is higher risk. how to manage that risk?

**Comment by dckc** [comment]
Today's design: charge 10BLD for a SMART_WALLET account; put proceeds in community fund.

I plan to make a stretch-goal issue to make the 10BLD a cosmos governance parameter.

**Comment by dckc** [comment]
Since we're charging execution fees in IST based on message size (#5817), for bootstrapping, should we issue 1IST in exchange for the 10BLD? (or 0.25 IST or whatever)
