### ISSUE TITLE
self-reference cycles: do virtual object self-references elevate the refcount?

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4667]
When we were talking about multi-facet virtual objects (#3834) today, I realized that our current refcounting mechanism might be indicating a cycle when it doesn't have to. If a virtual object somehow stores a reference to itself:
```js
const makeFoo = makeKind('foo', () => ({ me: undefined }),
  state => {
    set(you) { state.me = you; }
  }
});

function run() {
  const foo = makeFoo();
  // vref is kept alive by: Representative pillar
  foo.set(foo);
  // vref is kept alive by: Representative pillar, virtualized-data pillar
  // now 'foo' goes out of scope
}
run();
// vref is kept alive by: virtualized-data pillar
```

then our refcounting code will increment the refcount on `foo`'s vref when `set()` is invoked. The `foo` Representative will maintain the object until it is deleted (or falls out of the JS scope), but the virtualized-data pillar cannot be dropped until the refcount goes to 0, and that won't happen until someone changes the state (impossible, nobody externally can reach the vref), or the vref is deleted (impossible, refcount is nonzero).

This is a cycle, albeit a tiny one. But it would still prevent the on-disk data from being deleted.

If we thought it was worth it, we could avoid this by changing the callers of `vrm.updateReferenceCounts(before.slots, after.slots)` to also pass in the slot ID of the holder. The idea would be to ignore the holder when iterating through the slots: a self-reference doesn't count.

This sort of self-cycle seems more likely to occur with multi-facet objects, especially if we don't provide a way for one facet to access the other facets, and authors react by storing e.g. the `depositFacet` in the `state` so that `purse.getDepositFacet()` can return it. In this case, the "holder ID" needs to be the cohort ID, not the individual Representative, because the state (and the refcounts) are on the cohort.

It might be worth creating a helper function that takes a vref and returns the "refcount index" to use on it, both for "which refcount needs to be changed", and "which self-reference needs to be ignored".

**Comment by warner** [comment]
I'm going to put this in MN-1 because I think it might have a signifcant performance consequence if we don't do it. But if it looks like none of our virtual-object patterns trigger a self-reference cycle, I'm happy to defer it until later.

**Comment by Tartuffo** [comment]
@warner can we defer this to after MN-1?

**Comment by FUDCo** [comment]
The concerning context raised above doesn't really happen because of the way we do cohorts, so this can fall back to the normal way we would deal with any other cyclic reference issue (i.e., we don't have a reason to need to treat this case specially).
Retiring this issue, as it doesn't introduce new problems that aren't already covered by dealing with reference cycles, issue #2870.
