### ISSUE TITLE
compareRank properties should be subject to property testing

### ISSUE THREAD

**Issue by gibson042** [Agoric/Agoric#4675]
## What is the Problem Being Solved?

The reflexivity/transitivity/etc. of `compareRank` functions are not verified as general properties, but should be.

## Description of the Design

Use [fast-check](https://www.npmjs.com/package/fast-check), which is already in use for other agoric-sdk packages.

## Security Considerations

n/a

## Test Plan

See above.

**Comment by Tartuffo** [comment]
@gibson042 should this be labeled cosmic-swingset?

**Comment by gibson042** [comment]
Hmm, I don't think so but I did add what looks like the appropriate label.

**Comment by Tartuffo** [comment]
@gibson042, @michaelfig Should the "stores" label be covered in the weekly Cosmic Swingset meeting?  If not, then by which meeting?

**Comment by michaelfig** [comment]
> @gibson042, @michaelfig Should the "stores" label be covered in the weekly Cosmic Swingset meeting? If not, then by which meeting?

SwingSet.  It's under @FUDCo and @warner's purview.
