### ISSUE TITLE
wrong line numbers in kernel stack traces

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4681]
Starting with the landing of PR #4604 (in commit 781f8a21abe6fcde2b69004c89d02c5a515a2e99), I started seeing kernel errors getting the wrong line number reported. I know that PR changed the way source bundles are created, so I'm not surprised that line numbering might have been affected.

To reproduce this:

Start with the "good" case:

* check out the pre-PR commit (`git checkout a5de8dd298f2d7226cd4e8c9a3de69fe493c630b`)
* `yarn && yarn build`
* `cd packages/SwingSet`
* edit `src/kernel/kernel.js` to insert `throw Error('line number here')` at the beginning of `async function start()` (line 934 in that version)
* run `yarn test -vs test/run-policy/test-run-policy.js -m "run policy - computrons"`
  * any test that bundles and evaluates the kernel will do, this is the one I was investigating
  * the injected error causes a stack trace like:
```
$ yarn test -vs test/run-policy/test-run-policy.js -m "run policy - computrons"
yarn run v1.22.15
$ ava -vs test/run-policy/test-run-policy.js -m 'run policy - computrons'

REJECTED from ava test: (Error#1)
Error#1: line number here
  at Object.start (.../swingset-vat/src/kernel/kernel.js:934:11)
  at makeSwingsetController (packages/SwingSet/src/controller.js:290:16)
  at async testCranks (packages/SwingSet/test/run-policy/test-run-policy.js:31:13)

  ✖ run policy - computrons Rejected promise returned by test
  ─

  run policy - computrons

  Rejected promise returned by test. Reason:

  Error {
    message: 'line number here',
  }

  › Object.start (.../swingset-vat/src/kernel/kernel.js:934:11)
  › makeSwingsetController (packages/SwingSet/src/controller.js:290:16)
  › async testCranks (packages/SwingSet/test/run-policy/test-run-policy.js:31:13)

  ─

  1 test failed
error Command failed with exit code 1.
```
* go to that line (934) and confirm that it is the Error line you added

Now test the "bad" version:
* `git checkout -- src/kernel/kernel.js` to remove your modification
* check out the bad version: `git checkout 781f8a21abe6fcde2b69004c89d02c5a515a2e99`
* edit `kernel.js` again (same line number: no lines were added/removed between these two commits)
* run the same test again
* this time the stack trace in the error message shows:
```
Error#1: line number here
  at Object.start (.../swingset-vat/src/kernel/kernel.js:930:11)
  at makeSwingsetController (packages/SwingSet/src/controller.js:290:16)
  at async testCranks (packages/SwingSet/test/run-policy/test-run-policy.js:31:13)
```
* look at `kernel.js` line 930, observe it is not the added `Error` line

**Comment by michaelfig** [comment]
The discrepancy is caused by non-preservation of the formatting of the arguments to `buildKernel`.  Looks like `recast` just isn't cut out for `retainLines: true`.

Here is the before-and-after:

```js
export default function buildKernel(
  kernelEndowments,
  deviceEndowments,
  kernelOptions = {},
) {
```

becomes:

```js
function buildKernel(kernelEndowments, deviceEndowments, kernelOptions = {}) {
```

![image](https://user-images.githubusercontent.com/457244/155861550-0c7186d6-72f9-4714-9c77-2f281d0a0174.png)
