### ISSUE TITLE
remove vault manager notifications from vault's notifications

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4685]
## What is the Problem Being Solved?

https://github.com/Agoric/agoric-sdk/issues/4540 removed the cascading but `interestRate` and `liquidationRatio` that vaultNotifier returns still come from the vault manager.

## Description of the Design

Remove those too.

Ensure tests still verify the values, but from governance subscription.

**Comment by Tartuffo** [comment]
@turadg Please verify it is done (and link to the item that closed it).

**Comment by Tartuffo** [comment]
@turadg is this done?

**Comment by turadg** [comment]
It wasn't. PR created now ^.
