### ISSUE TITLE
Rosetta implementation passes rosetta-cli data checks

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4689]
From the [Agoric Rosetta Readiness Checklist Template](https://docs.google.com/document/d/1s-nX69uK7y0uJTOWDKGDjJKRFFbQQPgTa8g3nm3qoas/edit#):

Rosetta implementation passes rosetta-cli data checks with all correctness checks passing [Example Config]. 
* This includes reconciliation check
* This includes balance tracking for all accounts (and subaccounts)
The Asset Issuers has provided their config.json file
Tabelized cli test outputs

**Comment by Tartuffo** [comment]
@michaelfig Is this done, via cosmos-sdk?

**Comment by joeabbey** [comment]
Tests added in #6815

**Comment by joeabbey** [comment]
@ivanlei please close 🙏
