### ISSUE TITLE
Rosetta includes all data and construction api requirements

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4690]
Rosetta includes all data and construction api requirements as described: https://www.rosetta-api.org/docs/all_methods.html
* All Data API
* All Construction API
* Including suggested Fee Support in Construction API

**Comment by Tartuffo** [comment]
@michaelfig Is this done, via cosmos-sdk?

**Comment by joeabbey** [comment]
Addressed by cosmos-sdk, tested in #6815

**Comment by joeabbey** [comment]
@michaelfig feel free to close!
