### ISSUE TITLE
Rosetta endpoint

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4691]
From the [Agoric Rosetta Readiness Checklist Template](https://docs.google.com/document/d/1s-nX69uK7y0uJTOWDKGDjJKRFFbQQPgTa8g3nm3qoas/edit#):

Network Operations (network/operations) endpoint returns a list of supported operations

We expect the AI to implement a network/operations endpoint and will use this to determine the supported operation types

Some details:
* By “long lived”, we expect the testnet to have been stably running for a minimum of a month so we have a variety of transaction types on it.
* By “syncing”: we expect minimal downtime for the blockchain, and the nodes should be able to auto-recover to continue to sync after the chain is back up.

More context:
A large part of our automated testing story is running rosetta-cli data check on software that accesses some long-lived testnet before its eventual release on mainnet. 
For this reason, we require that you maintain a long-lived testnet where you deploy all changes that will eventually land on mainnet. 
This test network provides us with the confidence we need that updated code will not break our integration with your implementation.

**Comment by Tartuffo** [comment]
@michaelfig Is this done, via cosmos-sdk?

**Comment by joeabbey** [comment]
Addressed by the cosmos-sdk 

See #6815
