### ISSUE TITLE
Rosetta testing account(s) in testnet

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4692]
From the [Agoric Rosetta Readiness Checklist Template](https://docs.google.com/document/d/1s-nX69uK7y0uJTOWDKGDjJKRFFbQQPgTa8g3nm3qoas/edit#):

We require a pre-funded testing accounts, in testnet, ready to utilize during our validation activities

These should be created in testnet by bootstrap.

Why: When we test the construction API, we need to make transfers among multiple accounts. If we don’t specify a pre-funded account, then we have to randomly pick up an account with a minimum balance. It’s not guaranteed that the account we select has enough funds (due to the random selection), and in this case, we have to ask AI to fund the account. 
This is not convenient because construction API testing may be run for multiple times, and AI has to fund a different account each time.

How many accounts: 1-2 accounts are sufficient.

Funds required: We recommend AI to limit the amount being transferred in each transaction, e.g 0.001 BTC. Therefore we don’t need a huge amount of tokens to be funded.

**Comment by Tartuffo** [comment]
@michaelfig Is this done, via cosmos-sdk?

**Comment by ivanlei** [comment]
This is no longer plan of record.
