### ISSUE TITLE
Rosetta unit test as part of CI

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4693]
From the [Agoric Rosetta Readiness Checklist Template](https://docs.google.com/document/d/1s-nX69uK7y0uJTOWDKGDjJKRFFbQQPgTa8g3nm3qoas/edit#):

Make sure that Rosetta endpoint is running and is responsive to the Rosetta CLI.

Account addresses: We expect AI to provide the faucet account address and its private key. Considering the sensitivity of private key leakage, this address should only be used for testing purposes.

Expected outputs:
* Test account(s) address’:
* Test account(s) private key:
* Funds in test account(s):

Do we need a testing account for each of the various clawback / slashing scenarios?

**Comment by Tartuffo** [comment]
@michaelfig Is this done, via cosmos-sdk?

**Comment by joeabbey** [comment]
Greetings, @michaelfig, could I get a review on #7168?
