### ISSUE TITLE
reduce logging noise

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4713]
## What is the Problem Being Solved?

Bootstrap is noisy:
<details>
   <summary>Console output for for a test before it starts</summary>
<pre>
BLD: new Promise
RUN: new Promise
Attestation: new Promise
BLD: new Promise
RUN: new Promise
Attestation: new Promise
contractGovernor: new Promise
committee: new Promise
noActionElectorate: new Promise
binaryVoteCounter: new Promise
amm: new Promise
VaultFactory: new Promise
liquidate: new Promise
getRUN: new Promise
pegasus: new Promise
economicCommittee: new Promise
amm: new Promise
ammGovernor: new Promise
VaultFactory: new Promise
Treasury: new Promise
VaultFactoryGovernor: new Promise
liquidate: new Promise
getRUN: new Promise
getRUNGovernor: new Promise
Pegasus: new Promise
VaultFactory: new Promise
Treasury: new Promise
makeBundle @agoric/governance/src/committee.js
makeBundle @agoric/governance/src/binaryVoteCounter.js
makeBundle @agoric/governance/src/contractGovernor.js
RUN settled; remaining: [ 'Attestation', 'BLD' ]
RUN settled; remaining: [ 'Attestation', 'BLD' ]
economicCommittee settled; remaining: [
  'Pegasus',
  'Treasury',
  'VaultFactory',
  'VaultFactoryGovernor',
  'amm',
  'ammGovernor',
  'getRUN',
  'getRUNGovernor',
  'liquidate'
]
contractGovernor settled; remaining: [
  'VaultFactory',
  'amm',
  'binaryVoteCounter',
  'committee',
  'getRUN',
  'liquidate',
  'noActionElectorate',
  'pegasus'
]
committee settled; remaining: [
  'VaultFactory',
  'amm',
  'binaryVoteCounter',
  'getRUN',
  'liquidate',
  'noActionElectorate',
  'pegasus'
]
binaryVoteCounter settled; remaining: [
  'VaultFactory',
  'amm',
  'getRUN',
  'liquidate',
  'noActionElectorate',
  'pegasus'
]
amm settled; remaining: [
  'Pegasus',
  'Treasury',
  'VaultFactory',
  'VaultFactoryGovernor',
  'ammGovernor',
  'getRUN',
  'getRUNGovernor',
  'liquidate'
]
ammGovernor settled; remaining: [
  'Pegasus',
  'Treasury',
  'VaultFactory',
  'VaultFactoryGovernor',
  'getRUN',
  'getRUNGovernor',
  'liquidate'
]
amm settled; remaining: [
  'VaultFactory',
  'getRUN',
  'liquidate',
  'noActionElectorate',
  'pegasus'
]
&& task was past its deadline when scheduled: 0 &&
@@ schedule task for:1, currently: 0 @@
TEST ONLY: capturing test data [Function (anonymous)]
VaultFactory settled; remaining: [
  'Pegasus',
  'Treasury',
  'VaultFactoryGovernor',
  'getRUN',
  'getRUNGovernor',
  'liquidate'
]
Treasury settled; remaining: [
  'Pegasus',
  'VaultFactoryGovernor',
  'getRUN',
  'getRUNGovernor',
  'liquidate'
]
VaultFactoryGovernor settled; remaining: [ 'Pegasus', 'getRUN', 'getRUNGovernor', 'liquidate' ]
VaultFactory settled; remaining: [ 'getRUN', 'liquidate', 'noActionElectorate', 'pegasus' ]
liquidate settled; remaining: [ 'getRUN', 'noActionElectorate', 'pegasus' ]
&& task was past its deadline when scheduled: 0 &&
@@ schedule task for:10, currently: 0 @@

</pre>
</details>

Other areas are noisy too, depending on your purposes. E.g. run-protocol logs a bunch of things that you wouldn't be interested in unless you're debugging run-protocol.

## Description of the Design

We've deferred solving logging: https://github.com/Agoric/agoric-sdk/issues/1318   @dckc explained to me it's complicated by https://github.com/Agoric/agoric-sdk/issues/2519 and vats can't access ENV or do any IO, even in dev. Maybe there's a way to run a vat in a certain mode that configures logging.

But some options:
- more concise output of what is logged (e.g. collapse multiline logs to one)
- opt-out options (for logs that are valuable in production but not development)
- opt-in options for what won't ever be useful in production and is only sometimes useful while debugging (e.g. like [debug](https://www.npmjs.com/package/debug) or [anylogger](https://www.npmjs.com/package/anylogger) used for https://github.com/Agoric/agoric-sdk/issues/571)

## Security Considerations
TBD
## Test Plan

TBD

**Comment by dckc** [comment]
this seems to help quite a bit. Bonus points to anybody who can context switch and get it in before I can...

```diff
modified   packages/vats/src/core/utils.js
@@ -215,7 +215,7 @@ harden(extractPowers);
  *
  */
 export const makeAgoricNamesAccess = (
-  log = console.debug,
+  log = () => {}, // console.debug
   reserved = agoricNamesReserved,
 ) => {
   const { nameHub: agoricNames, nameAdmin: agoricNamesAdmin } =
```
