### ISSUE TITLE
Vaults should price collateral in Dollars

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4714]
## What is the Problem Being Solved?

The stability of RUN relies on Vaults pricing collateral in dollars and lending RUN and liquidating Vaults based on the dollar price of the assets.
```
dtribble(keybase): Dollars. Or USDC potentially
btulloh(keybase): We must use USD prices of the collateral as reported by the oracle. Not USDC prices.
```

## Description of the Design

The current code in `vaults.js` asks for prices in RUN.
```
  const quoteAmount = await E(priceAuthority).quoteGiven(
      collateralAmount,
      runBrand,
    );
```

```
michaelfix(keybase): I know we must have USD price oracles.  My question is one of API: should we access those price authority pairs using xBrand-to-runBrand, or should we somehow use a fake brand (no mint or issuer) specifically for USD and have xBrand-to-fakeUsdBrand?
dckc(keybase): The latter. It's not so much "fakeUsd" as "USD as defined by the oracle network"
(oops... I see you used "fake" to mean no mint)
```

## Security Considerations

This is about economic security of the platform, and doesn't impact platform security.

## Test Plan

We'll need tests for the dollar-based oracles, and we'll need to update tests to rely on dollar-based oracles.

**Comment by dckc** [comment]
This is addressed by `scaledPriceAuthority.js` in #5190, I'm pretty sure.
