### ISSUE TITLE
remove the conventional commits check on PRs

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4721]
## What is the Problem Being Solved?

Not all PR commits need to be conventional com
mits but our config says a PR fails checks if they aren't.
<img width="860" alt="Screen Shot 2022-03-02 at 8 37 17 AM" src="https://user-images.githubusercontent.com/21505/156406370-978e3789-ec16-4cbf-a8dc-c95feec8b61f.png">

It makes it harder to see in a list view whether a PR has errors that need to be addressed before review. Here the only reason this PR in the list is red is because it has some commit messages that aren't conventional commits:
<img width="362" alt="Screen Shot 2022-03-02 at 8 37 04 AM" src="https://user-images.githubusercontent.com/21505/156406532-a156cda1-aa8a-4530-9cb2-7e2b8235f184.png">

Valid reasons to commits on a PR that aren't "conventional":
- a `fixup!` commit generated by `git commit --fixup` that makes it clear to the reviewer whether and how their request was addressed
- the PR will be squashed such that only the PR title becomes the commit message
- changes that don't need to entries in the changelog

Having the check on PR commits has be misunderstood in some cases to guarantee changelog entries. These are some squashed commits in which the author took care to make conventional commit message but master didn't get them:

85228b74c9ccffa74766c63d844354b6dc5982c8 4602 simpler vault uinotify 2 (#4610)
a4f297c415be08dd7fa07dd8b2191ec53637941b Keep small bigints small (#4469)
ae98f610cd8b8f1118aa9af92256aef738edffac Refresh parameter test on amm liquidity (#4607)
dafa8efa89399682ee0d018ac9c1bc7d84144d80 3864 transferrable vaults (#4581)
d3d3555265526fa68acb9fccb181db91ec4a9638 Test encodeKey and order invariants (#4465)
9bf0ee25f686eeee3d9f2de298cb0ec5f235ee45 fixup: makePromiseSpace

Here are some examples of commits that were made conventional but create noise in the changelog:
ee396514c14213a7c9dfa4f73919a9cfe77dd2e6 fix: quick "fix" of a red squiggle problem (#4447)
52a96e24de4cc19e5dac2fc3f2daa55e2f4d74d1 chore(swingset): improve typechecks
9324cfed2cff9cf96523859010537ffdea69e721 fix(zoe): fix InstanceRecord type
280d46b950f81a75a1f2967d204087baeab9cce9 chore: unit tests
655981f2ce67406088cc68af9d63d76fa5caeabc chore: yarn build
1e7dc9edbed7cfd9e82e669ca70be4fbb8c940cb chore: Update yarn.lock
70182bdf0eee4bf65243e997e7a8cdf5c158127e refactor: git grep '@agoric/bundle-source' | cut -d: -f1 | uniq | xargs sed -i '' 's|@agoric/bundle-source|@endo/bundle-source|g'

The point of conventional commits is to be readable by tooling, but not all commits meet the bar of going into the changelog. There's a decision to be made when authoring a commit as to how to communicate it to consumers. Often the meaningful change is at the PR level and we currently have no checking on the title.

## Description of the Design

- Disable the `conventional-commits` PR check
- in CONTRIBUTING.md explain when and how to write conventional commit messages
- ? [enforce conventional-commit on PR title](https://docs.mergify.com/actions/post_check/?highlight=conventional#enforcing-conventional-commits) ? 

## Security Considerations
--
## Test Plan
--

**Comment by mhofman** [comment]
For a merge or rebase PR I still think that each commit should follow conventional commits (in which case the merge commit itself doesn't really need to follow conventional commits IMO).

I still wish that we had some checks that only ran when a PR is landing, and fail the "merge" if those checks don't pass.

**Comment by turadg** [comment]
> For a merge or rebase PR I still think that each commit should follow conventional commits

Given that the PR check doesn't know whether it's a merge or rebase PR (and that can change right up until it's landed on master) are you okay with the "should follow" enforcement being human rather than a failing PR check?

**Comment by mhofman** [comment]
Given we don't have my wish, I think so
