### ISSUE TITLE
Ability to use debug AVA tests with a launch configuration

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4722]
## What is the Problem Being Solved?

When running tests with a launch configuration ([as here](https://github.com/avajs/ava/blob/main/docs/recipes/debugging-with-vscode.md#creating-a-launch-configuration)) I get this error,
```
SyntaxError: The requested module '[file:///opt/agoric/agoric-sdk/node_modules/@babel/types/lib/index.js]()' does not provide an export named 'default'
```

That's caused by `import '@agoric/babel-standalone' in `@endo/init/pre-bundle-source.js`. (That particular error goes away when I comment out that line.)

## Description of the Design

This might be solved by https://github.com/Agoric/agoric-sdk/pull/4718 . I'll check after that is merged.

## Security Considerations
--
## Test Plan

--

**Comment by kriskowal** [comment]
#4718 has merged. We may also be able to land a change that generally closes https://github.com/endojs/endo/issues/768

**Comment by turadg** [comment]
@kriskowal progress had been made! Error now,
```
[/opt/agoric/agoric-sdk/node_modules/]()@agoric[/babel-generator/lib/generators/modules.js:182]()
    if (specifiers?.length) {
                   ^

  SyntaxError: Invalid or unexpected token
```

**Comment by kriskowal** [comment]
> @kriskowal progress had been made! Error now,
> 
> ```
> [/opt/agoric/agoric-sdk/node_modules/]()@agoric[/babel-generator/lib/generators/modules.js:182]()
>     if (specifiers?.length) {
>                    ^
> 
>   SyntaxError: Invalid or unexpected token
> ```

cc @michaelfig This babel-generator version might be too new.

**Comment by kriskowal** [comment]
@turadg Can you confirm your Node.js version?

**Comment by turadg** [comment]
```
> node --version
v17.6.0
```
This works
```
cd packages/run-protocol
yarn test --serial test/vaultFactory/test-vaultFactory.js
yarn ava --serial test/vaultFactory/test-vaultFactory.js
```
But these gives the syntax error:
```
yarn ava packages/run-protocol/test/vaultFactory/test-vaultFactory.js
./node_modules/.bin/ava packages/run-protocol/test/vaultFactory/test-vaultFactory.js

```
The latter is how my launch configuration is set up, so it can be run anywhere in the repo.

**Comment by kriskowal** [comment]
I’ve experienced `ava`’s sensitivity to the working directory. For example, the paths you give it must be relative to the project root. But this specific error is weird and indicates a stale Node.js version in play. Maybe there’s a fully qualified path in an npm-generated shebang.

**Comment by turadg** [comment]
SyntaxError appears to have been coming from https://www.npmjs.com/package/esm . Root config (unlike the rest) had it has a preload `require`. The linked PR upgrades Ava and removes that from config. But doing that requires changing root package type to 'module' which shakes out some other things to update. I'm time boxing that but let me know if you know of a shorter path.

**Comment by kriskowal** [comment]
Per https://github.com/Agoric/agoric-sdk/pull/4758, we no longer depend on `@agoric/babel-standalone` or for that matter `recast`, therefore neither `@babel/types`. So that just leaves `esm` in `agoric-cli`, which is becoming rapidly less necessary as we’ve migrated most if not all dapp deploy scripts to Node.js ESM (NESM).

**Comment by michaelfig** [comment]
> Per #4758, we no longer depend on [...] `@babel/types`.

We still need `@babel/types`.  Maybe you were thinking `ast-types`?
