### ISSUE TITLE
get more RUN against slashed BLD should fail

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4728]
## Describe the bug

Slashing should affect the getRUN limit, but after we get an attestation, I don't see how to detect slashing.

## To Reproduce

This is case 9 resulting from a Dec 6 discussion with @JimLarson and @rowgraus:

9 | Extending LoC - unbonded (FAIL) |   |   |  
-- | -- | -- | -- | --
  |   | buy BLD | 1,000 |  
  |   | stake BLD | 800 |  
  |   | lien BLD | 800 |  
  |   | borrow RUN | 100 |  
  |   | slash | 300 |  
  |   | check BLD staked | 500 |  
  |   | borrow more RUN | 50 | fail
  |   | check RUN balance | 100 |  
  |   | check BLD liened | 800 |  

The "borrow more RUN" step _should_ fail, but the getRUN contract only has an immutable attestation, not a way to check the underlying cosmos state.

## Expected behavior

The "borrow more RUN" step _should_ fail.

## Additional context

This is in development of #3788.

cc @dtribble @JimLarson @rowgraus @turadg

**Comment by dckc** [comment]
Based on discussion with @dtribble , I'm postponing this to the general product backlog.

**Comment by ivanlei** [comment]
This is an antique plan lost to the sands of time.
