### ISSUE TITLE
add alleged name to `E(zoe).install()` and/or startInstance()?

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4738]
## What is the Problem Being Solved?

While talking with @Tartuffo and @mhofman about analyzing slogfiles from a perf-test run, we noted that it's non-trivial to figure out which vat is which. I've cobbled together tools which throw the `start-vat` and `send('start', [contractBundle])` events at some regexps to make a guess, but it would be a lot nicer if the code that loaded the vat could provide a hint. We will soon have BundleIDs in the slog instead of full bundles, which are unique, but not descriptive.

`E(vatAdminService).createVat()` currently takes an options bag, and I think both `name` and `description` are options.

@erights what do you think about adding an options bag to `E(zoe).install()` that could provide an alleged name? Zoe could combine this with maybe a sequence number, and use that as the name/description when creating the new vat. Each new vat is created from the ZCF bundle, but then receives a `start()` message with the contract bundle/bundleID. The name would be based upon the contract name, maybe `ZCF:${name}`.

Internally, this field would be recorded in the slogfile when the new vat gets created, giving our analysis tools something easier to work with.

Zoe would either prepend `Alleged:` to the string, or assert that it was already present. And actually, we could do without the sequence number: the analysis tools already know a VatID, so it would present strings like `v3-zoe` and `v4-AMM` and `v5-AMM`, with which the analyst could disambiguate multiple instances of the same contract.

Hm, this would have to change when we implement a ZCF zygote vat: the `{ name }` would be set when creating the zygote, but at that stage all we know is that it will start with ZCF, we don't know what contracts its clones will be used for. I think we'd want to make `adminNode~.clone()` operation take an options bag that could assign a new name to the new contract vat.

## Description of the Design

`E(zoe).installBundleID(bundleID)` becomes `E(zoe).installBundleID(bundleID, { name })`, which either prefixes or verifies an `Alleged:` prefix on `name`.

Zoe passes `name` through to `E(vatAdminService).createVat(bundleID, { name })`

## Security Considerations

The `name` would not be revealed to any user code (I would not suggest adding it to the information you can get about an `Installation` object). It would only be passed to `vatAdminService`, whose only use for `name` is the slog entry.

I think that means a malicous contract installer, who tries to claim they're installing the One True Zoe or something, would only be able to influence a slogfile analyst, and they're probably in a good position to ignore these names. I think that might even make it reasonable to drop the `Alleged:` prefix, but given our practice with `Far(iface)`, I suspect we wouldn't.

## Test Plan

Unit test in Zoe, maybe, but a single manual eyeball-check might be sufficient.

**Comment by dckc** [comment]
Yes, please! Based on my experience poring over testnet data, keeping names handy like this is _very_ valuable. It'll be important for telemetry too.

I concur that it shouldn't be visible to Zoe clients. Just to those of us in the platform / debugger / console role.

**Comment by erights** [comment]
Good.

>  but given our practice with `Far(iface)`, I suspect we wouldn't.

Weak precedent, but maybe. The reason the precedent is weak is that the iface name is exposed across captp, where we don't control what it is used for. OTOH, these names can come from users, so yes, `Alleged: ` is a good reminder.

Global Namespaces Considered Harmful!

**Comment by Tartuffo** [comment]
Design discussion: https://drive.google.com/drive/u/0/folders/13MifhaEn0slybFA-_bD_xMDOFJc2kJLV

**Comment by dckc** [comment]
## vat names in `ps` sure would be nice

I'm staring at another one of these lists of processes wondering which zcf is doing what:

```
$ pstree -a -p --hide-threads 2813590
bash,2813590
  ├─make,2342616 scenario2-run-chain-economy
...
  │           ├─xsnap-worker,2343485 v12:ibc
  │           ├─xsnap-worker,2343533 v14:zcf
  │           ├─xsnap-worker,2343537 v15:bank
  │           ├─xsnap-worker,2343739 v16:zcf
  │           ├─xsnap-worker,2343740 v17:zcf
  │           ├─xsnap-worker,2343744 v18:zcf
  │           ├─xsnap-worker,2343765 v19:zcf
...
```

**Comment by dckc** [comment]
@warner #6896 got me thinking... when the kernel is making a contract vat, does it have enough info to go "say... I saw the bundleId `b-23oi42oi3` go by under the name `bundle-walletFactory.js` a minute ago..." and use that for the xsnap worker name?

If not at the time the zcf worker is created, would it be too gross to have add a "set your label to X" thing to the xsnap worker pipe protocol that would update `argv[1]` so that it shows up in ps?

**Comment by dckc** [comment]
running into this again today - an xsnap worker is going nuts... it's labelled as v47, but it's not straightforward to figure out what contract that is.
