### ISSUE TITLE
bootstrap: add vat `name` when creating standard vats

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4739]
## What is the Problem Being Solved?

As with #4738, we noticed that slogfiles don't contain a straightforward way to figure out which vat is which. When the primary Agoric vats (zoe, AMM, vault, board, etc) were static, we had a name for each. But the recent `bootstrap` changes make everything but swingset's comms/vattp/timer into a dynamic vat, and it's hard to deduce a name for `v5` from the slog data.

However, `vatAdminService~.createVat()` accepts an options bag, and there's a `name` option (or maybe `description`, I need to check).

cc @dckc @michaelfig 

## Description of the Design

`bootstrap` should include the name when creating vats: `const zoeP = E(vatAdminService).createVat(zoeBundleID, { name: 'zoe' })`/

## Security Considerations

As mentioned in #4738, the name is not really exposed anywhere (there's no way to get it back from a vat's `adminNode`), so the risk of tricking someone into believing an incorrect name is limited to people reading the slogfile.

## Test Plan

Maybe nothing, just a one-time manual check.

**Comment by dckc** [comment]
We're currently using `createVatByName`;  it seems like that should suffice.

https://github.com/Agoric/agoric-sdk/blob/0c1a686b92f9197eeb275341c1a5eead30ac2111/packages/vats/src/core/basic-behaviors.js#L62-L69

**Comment by warner** [comment]
yep, good point, I'll make sure that's routed to the slog

**Comment by dckc** [comment]
You can re-use this issue if you change it to be a problem report / bug along the lines of "slogfiles don't contain a straightforward way to figure out which vat is which".
