### ISSUE TITLE
Unnecessary `await` in vaultManager.js

### ISSUE THREAD

**Issue by gibson042** [Agoric/Agoric#4773]
Code change: `await` is unnecessary in vaultManager.js on `outstandingQuote = await E(priceAuthority).mutableQuoteWhenLT`

## What is the Problem Being Solved?

Restival uncovered that the [first `await` in reschedulePriceCheck](https://github.com/Agoric/agoric-sdk/blob/0c1a686b92f9197eeb275341c1a5eead30ac2111/packages/run-protocol/src/vaultFactory/vaultManager.js#L217-L220) in /run-protocol/src/vaultFactory/vaultManager.js seems to be unnecessary and should be removed.

**Comment by Tartuffo** [comment]
May be fixed in branch @dtribble was editing during Restival.

**Comment by dtribble** [comment]
Fixed
