### ISSUE TITLE
[Vaults] When Vaults are liquidated, charge a fee

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4775]
## What is the Problem Being Solved?

When vaults are liquidated, a fee should be charged and accrued to the reward pool

## Description of the Design

New governance parameter `liquidationPenalty`, defaulting to 10%. Govern per VaultManager.

Proceeds from the penalty will go to the reserve pool. For now hold them in a `penaltyPoolSeat`.

Eventually make a timer for batching emptying the penalty seat into the reserve. The reserve doesn’t benefit from getting it sooner.

## Security Considerations

It's governed, but otherwise not a security issue

## Test Plan

add verification in the existing liquidation tests.

**Comment by Tartuffo** [comment]
May be fixed in branch @dtribble was editing during Restival.
