### ISSUE TITLE
Testing: Simulate divergence of oracles

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4778]
## What is the Problem Being Solved?

_not entirely clear to me... it's either divergence among the oracle nodes

## Description of the Design

?

## Security Considerations

?

## Test Plan

?

**Comment by Tartuffo** [comment]
How does our system respond to a divergence of multiple aggregators.

**Comment by Tartuffo** [comment]
Not needed.  (We can test how liquidity contract handles divergence between Oracle price and AMM price as part of the testing the liquidation contract.)
