### ISSUE TITLE
update all parameters for a collateral type

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4783]
## What is the Problem Being Solved?

Updating individual collateral parameters in separate governance questions may not result in a consistent outcome (interest rate increase passes but debt limit change does not).

## Description of the Design

Candidate: Narrow the authority in #4352 to only update the parameters associated with a collateral type in the VaultFactory. This can then be invoked by the BLDer DAO.

Possible enhancement(s):
  - invokable by a cosmos multisig
  - invokable by the economic governance committee

## Security Considerations

_IOU_

## Test Plan

_IOU_

raising on behalf of @dtribble 
cc @Chris-Hibbert

**Comment by Tartuffo** [comment]
We need to be able to make multiple parameter changes atomically via Cosmos Governance.  Current code handles this one parameter at a time. 
The contract governor can make a question able making a *single* param change, and registers a handler, and if the question was a param change, goes and applies it.
@rowgraus should consider this in his governance scenarios.

**Comment by Chris-Hibbert** [comment]
updating all parameters atomically can now be done from js governance (#4881). I don't know how to tie that to actions invoked by cosmos governance. Do we still need to be able to do the latter, or will solving this for the econ committee be sufficient? 

In order for the econ committee to vote on changes like this, we need to figure out how to get the question-posing facet into the hands of someone who can create the relevant ballot question.

**Comment by dckc** [comment]
Good question. The issue title says the latter, but [RUN Protocol Governance Summary](https://docs.google.com/document/d/1Nn5RpGYugG11K44v7tdFu2Z4OVldq_ZSgjor2yN3cWs/edit#) last revised 14 Apr by @rowgraus seems to say that solving this for the econ committee suffices:

> 10. Add ATOM as collateral to vaults
>   a. Pre-requisites: Collateralize ATOM/RUN AMM pool, enable ATOM/USD oracle price feed, deploy RUN Protocol contracts, elect economic committee
>   b. Approve ATOM as collateral with zero debt limit
>     i. **JS Hammer, API**
>   c. Connect ATOM/USD price feed to the vaults 
>     i. **Econ; Oracle**
>   d. Raise debt limit and set other key parameters
>     i. **Econ; Param**

Step 10.d seems to be the relevant one.

**Comment by dckc** [comment]
IIRC, @dtribble is still interested in the general form of this feature, but it's not critical path to any of our launch scenarios.

**Comment by dckc** [comment]
The EC workflow has supported multiple parameter changes in one question for some time now.
