### ISSUE TITLE
Remove “BLD” and “RUN” keys from run-protocol code

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4800]
# RUN/IST role cases

## vaultFactory
Token that is minted, secured by collateral (per vault manager)
keyword: `Minted`
Proposal shape will be {give: Collateral, want: Debt}

## runStake / bldBoost
Token that is minted, secured by collateral.
keyword: 'Minted'

## feeDistributor
Fee.
keyword: `Fee`
The CollectFees offer result will by a seat with `getPayout('Fee')`.

## assetReserve
Fee mint to hold penalties
keyword: `Fee`

## psm
Stable
keyword: Stable (already)

**Comment by dtribble** [comment]
This includes removing it as the keyword for the stable token in 
```javascript
  const runMint = await zcf.registerFeeMint('RUN', privateArgs.feeMintAccess);
```

**Comment by dckc** [comment]
@turadg to propose role-based keywords

**Comment by Chris-Hibbert** [comment]
I'd pretty strongly prefer 'loan' to 'debt' for the vault factory. It's only 'debt' on one side of the balance sheet.  Similarly with bldBoost.

**Comment by Chris-Hibbert** [comment]
'collateral' doesn't seem ideal for BLD. There are lots of assets that are collateral. BLD is uniquely the one that represents equity in the chain. Maybe 'Stake' would work.
