### ISSUE TITLE
[Vault] If adjust balances is called with two empty amounts, the reallocate fails

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4805]
## Describe the bug

During Restival, we were trying to prove that if you tried to `adustBalances` with only a change to one of `RUN` and `Collateral`, that it would fail due to not creating a staging. It turns out that both seats get stagings if either amount is positive. That led to a bug demonstration that if both are empty, the `reallocate` fails

## To Reproduce

Create a test case that tries to trade 0 RUN for 0 Collateral

## Expected behavior

It should cleanly trade nothing, or cleanly refusse.

## Platform Environment

irrelevant

**Comment by Tartuffo** [comment]
@samsiegart please confirm that the UI doesnt allow this, if confirmed, please move to 1.1 and make it about via API.

**Comment by samsiegart** [comment]
> @samsiegart please confirm that the UI doesnt allow this, if confirmed, please move to 1.1 and make it about via API.

Just confirmed the UI does not allow this
