### ISSUE TITLE
Simplify governance terms API

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4806]
## What is the Problem Being Solved?

Governance values aren't always fetched in their current state. We need to make that easier.

## Description of the Design

- Auto-generate mapping of keys to accessor functions
- Use type system instead of typed accessors ([demo](https://www.typescriptlang.org/play?#code/C4TwDgpgBA4hzAgJwM4B4AqAaKBVKEAHogHYAmKUA1hCAPYBmUGAfFALxQDeAsAFBRBUANoAFJHUhJQUAJYk8UAIaUABgHN4AEi4BhJWFnAlAG1kAvCGhTAk89VABkUcZOSgWAX1UBdAFxQABQAlBxsGGISUqA+-J4A3Pz8DACuJADGwLJ0CprAMHQAbsgkSqUZVhgExBDklHQARgBWEJk4+ESkFNS0jMwsgebpDAHYPSAoAQBKEEpkOSYgAIJISEogaLgswQFwCMjoY1vc-ILpOTbK6ekc3J7KlGUgiQJQDHRIQecklzQgUH0-ihQrxXmcLsAoKUALbQTgabRcP7eF5CK7pYQwiA+W4hMJQIYMYR-HyoqCeU5QJDwFJIBRKa4vCl8fjfS5kFLQhoALWGty4chIiGpNimSkQAQAjDhqeckGR7KJkNkyAEAOQoOiwgDKtnsapwaRSKAgqqgaq1RkQZDV5JebMh6iKtzyBWKdLKZXSEECHK5vIYOGEavkwogovFEAN5tlHwVJHUSrsdBtPmC9oudBMEAAdCY6OpAk7Cjm8gBJIXIcPAMWIEI54B0ABiskIppC6dZmezeYLRaKpfgMzl8cTypT9cbuDAUn0Jo7LwA9IuoAABYAoAC0REgmW3qw+XZ+Wdz+cLxcHwFwJGN7eCnb4QA
))
- clean up the redundancy between poolFeeBP and POOL_FEE_KEY (we don’t need to keep the initial value)

## Security Considerations
--
## Test Plan

--

**Comment by Chris-Hibbert** [comment]
See also #4784

**Comment by turadg** [comment]
Reopened because I still need to:
- clean up the redundancy between poolFeeBP and POOL_FEE_KEY (we don’t need to keep the initial value)
