### ISSUE TITLE
Review/rename 'main' keyword in parameter governance

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4818]
## What is the Problem Being Solved?

Parameter Governance uses `main` as the keyword in `terms` that contains the descriptions of parameters. 

## Description of the Design

Is the main concern usability?

## Security Considerations

As long as the keyword is documented and used consistently, there aren't any security consequences.

## Test Plan

Just a renaming. No affect on test requirements.

**Comment by turadg** [comment]
Recap from our discussion:
- Rename ‘main’ to “governed”. 

Other improvements we discussed that could be part of this ticket or another:
- In handleParamGovernance, `augmentPublicFacet` and `makeGovernorFacet`
-  "limited creator facet" --> "governed facet"
- Some naming changes to distinguish between the facet for the "agent" which can't govern and the fully powerful facet for the "governor"
- type interfaces for the above that can be used in contracts not using the helper
- move `makeParamManager` within the helper function so the contract doesn't hold it

**Comment by Chris-Hibbert** [comment]
blocked-by: #4868
