### ISSUE TITLE
Describe the user flows for Governance Legibility

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4828]
## What is the Problem Being Solved?

Much of the design of governance is driven by the perceived need for Legibility, the ability of various relying parties to verify the properties and relationships of governed contracts. It would be helpful to describe how end users will make use of this.

## Description of the Design

stories, interaction diagrams, mock-ups.

## Security Considerations

Knowing the end usages of our Legibility support will clarify where to put effort.

## Test Plan

Documentation doesn't need tests.

**Comment by Tartuffo** [comment]
@rowgraus We believe this is done from an Eng side.  If there is more work, please work with in the Monday Inter Protocol meetings.
