### ISSUE TITLE
Eliminate weird redundant `globals.d.ts` files

### ISSUE THREAD

**Issue by FUDCo** [Agoric/Agoric#4830]
In the course of maintaining the virtual objects stuff, whenever a change to the `VatData` API happens (which has been happening quite a bit as it's under active development and evolving), it is necessary to perform coordinated changes to 6 separate `globals.d.ts` files in 6 separate packages:
```
packages/xsnap/src/globals.d.ts
packages/deploy-script-support/globals.d.ts
packages/run-protocol/globals.d.ts
packages/ERTP/globals.d.ts
packages/pegasus/globals.d.ts
packages/vats/globals.d.t
```
With the exception of the `xsnap` package, all of these files are identical and only declare `VatData` and its related parts, and even `xsnaps`'s does little more than that.

This is ludicrous, annoying, and potentially dangerous.

If we can't get rid of these silly things, can we at least have just one of them in some standard place that everybody else can point to?

**Comment by FUDCo** [comment]
@erights

**Comment by FUDCo** [comment]
Tagging @turadg @mhofman @michaelfig and please also add any of our other TypeScript enthusiasts I might have missed

**Comment by mhofman** [comment]
The solution is, you guessed it, move away from ambient types. A module file (containing an `import` or `export`) can `declare global`. Then you should be able to have one declaration and import the rest from there? Also from a cursory look, all these files are all pretty much incorrect and basically won't do what you want besides typing the `makeFoo` and `any`.

**Comment by FUDCo** [comment]
I literally don't care what the solution is.  I just want somebody to make this go away.

**Comment by mhofman** [comment]
I think this could and should be tackled at the same time as #4560, but there may be a quicker fix.

**Comment by turadg** [comment]
For @FUDCo 's particular grief with updating `VatData` we could import the def from a canonical place. https://github.com/Agoric/agoric-sdk/issues/4255

I'll assign myself.
