### ISSUE TITLE
virtualObjectManager cleanups

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4833]
## What is the Problem Being Solved?

A couple of cleanups that I'd like to make at some point, but are too low-priority to do today:

* `setExportStatus` uses (as of PR #4742) a stringified array of single-letter export status flags, one per facet of a cohort. The letters are `[rsn]` for `[Reachable, Recognizable, Neither]`. I want to change that to something with a more visually-obvious rank/order. The most obvious choice (`[210]`), which builds upon what the previous single-facet encoding used (`1` for reachable, `0` for recognizable, missing entry for neither) is ruled out by confusion with a multi-digit integer reference count ("oh, that object has 2201 references, ok..."). I'm thinking `[Rc_]`, where the height of the character indicates the "strength" of the reference.
* `defineKindInternal()` uses names like `storedRepresentative` for both a single Representative (mono-facet) and the "cohort record" Array of Representatives (multi-facet), and having a single variable hold either an array of things or a single thing really bothers me. Also, that same array-or-not is held in other places under different names. Same for `exposedRepresentative`. I want to unify the name, unify the types somehow, and find a name that makes more sense to it.
* `wrappedData` is the name used for the getters/setters object that is then provided to the user code as `state`. I think it should be called `state` everywhere.

**Comment by warner** [comment]
Chip showed me the current code, and I'm ok with it. And I haven't looked at the `[rsn]` fields since I wrote this ticket, so apparently I don't really need to care as much as I once thought.

**Comment by FUDCo** [comment]
Of the three bullets above, the second and third do not describe the state of the code as it exists today.  I believe both of these pieces of feedback were previously incorporated as part of the durable objects work.  Per Brian's comment above, I think we can live with the existing `[rsn]` encoding, so I'm going to just close this.
