### ISSUE TITLE
vrefRecognizers uses RAM for purely virtual objects

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4834]
@FUDCo and I identified a performance (RAM usage) problem in the current virtualReferences.js code. There's a `Map` named `vrefRecognizers` which maps vrefs to a Set of things that might be able to recognize the corresponding object. This includes vref-aware WeakMaps/WeakSets, and all weak-keyed virtual collections. It tracks Presence-style keys and Representative-style keys, not Remotable-style keys.

The problem is that `vrefRecognizers` will have an entry for every vref that is used as a key, even if there is currently no Presence or Representative for that vref. This violates our intention that we don't consume RAM for objects in this state. We wrote this code before we had virtual collections, and it was ok for the vref-aware WeakMaps/WeakSets of the time (which are not intended to be virtual, so they're allowed to consume RAM for every entry). But when we implemented virtual collections, we should have built an on-disk version of this table.

So the work item is to figure out how to keep that table on disk. We probably want two separate tables: use the existing approach for vref-aware WeakMap/WeakSets, but build a new thing for virtual collections.

The on-disk table will probably map from the vref of the thing being used as a weak key, to the vref of the collection enclosing it. Actually it will probably map to a stringified array of vrefs, since a single object can be used as a key in multiple collections.

Until we implement this, virtual collections will continue to consume memory O(N) in the number of entries.

**Comment by FUDCo** [comment]
> Until we implement this, virtual collections will continue to consume memory O(N) in the number of entries.

Minor nit: this issue only applies to weak-keyed virtual collections.  Still needs to be fixed though.

**Comment by FUDCo** [comment]
In pondering this, I came up with a question about the best design for the on-disk inverse table (the thing that keeps track which weak stores are using which vrefs as keys).  As far as my imagination is able to go, I think there are, roughly speaking, two possible schemes:

(A) store each inverse-table entry in its own vatstore record, with essentially the entire thing kept in the key.  The key string would look something like `vom.ref.${vref}|${collectionID}` and the value would just be something nominal to indicate that the record is there, say `1` or the empty string (it really doesn't matter, so make it short).

(B) store each vref's information as a single entry that lists the relevant collections.  So the key would be something like `vom.ref.${vref}` and the value would be something like `${collectionID1},${collectionID2},${collectionID3},...`

The four operations we need to support are: _add_ an entry, _delete_ an entry, _delete all_ entries for a given vref, and check if a given vref _has_ an entry at all.

For scheme A:
- working state requires N DB entries
- _add_ is a single DB write (1 disk I/O, O(1) in RAM)
- _delete_ is a single DB delete (1 disk I/O, O(1) in RAM)
- _delete all_ is N DB deletes where N is the number of collections that hold the vref (N disk I/Os, O(N) in RAM)
- _has_ is a single DB read (a single call to `vatstoreGetAfter`) (1 disk I/O, O(1) in RAM) [note: a single `vatStoreGetAfter` is almost certainly more work for the DB than a `vatstoreGet` but not nearly as expensive as a full iteration)

For scheme B:
- working state requires 1 DB entry
- _add_ is a DB read - modify - DB write cycle (2 disk I/Os, O(N) in RAM)
- _delete_ is a DB read - modify - DB write/delete cycle (2 disk I/Os, O(N) in RAM)
- _delete all_ a single DB delete (1 disk I/O, O(1) in RAM)
- _has_ is a single DB read (1 disk I/O, O(1) in RAM)

Of these _add_, _delete_, and _has_ will be the most common operations (though the frequency ratio of _add_/_delete_ vs. _has_ is not obvious), while _delete all_ will be comparatively rare.

Scheme B seems more straightforward from an encoding point of view, but if we regard DB operations as costing a lot more than fiddling with (likely smallish) lists in memory, then I think the analysis favors scheme A, but I wanted to document my thinking here in case anybody has a different take.
