### ISSUE TITLE
Support offerArgs in wallet.addOffer 

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#4860]
## What is the Problem Being Solved?

Zoe supports an offerArgs param in `zoe.offer`, but the wallet API does not have any logic to include this arg. This should be added so a dapp can propose an offer in the wallet with specified args.

## Description of the Design

Add `offerArgs` as a param to `wallet.addOffer`, and in `executeOffer` the wallet should include the arg.

## Test Plan

A unit test should ensure the arg is being passed through.

## Additional Considerations

How should the wallet UI show these args in the proposal? Perhaps there should be a way to expand a proposal to show the stringified args. The wallet can hydrate this string using known petnames and add it to `proposalForDisplay`.

cc @michaelfig

**Comment by michaelfig** [comment]
Turns out we need this feature for MN-1, since it is how oracles wire themselves into a priceAggregator.
