### ISSUE TITLE
Add test for vaultManager totalDebt is updated for burned RUN

### ISSUE THREAD

**Issue by dtribble** [Agoric/Agoric#4878]
## What is the Problem Being Solved?

A change to not track burned RUN didn't fail regression tests.

## Description of the Design

N/A

## Security Considerations

An attacker could cycle minting and running a modest amount and effectively consume the debt limit. 

## Test Plan

Add the test. Break debt reduction reporting and see if the test fails.

**Comment by turadg** [comment]
Closing as can't repro. When I disable this line that updates totalDebt, the "manager notifications" test fails:
https://github.com/Agoric/agoric-sdk/blob/8cbf6974a8c1e189589620fef4b682b1c3e134b2/packages/inter-protocol/src/vaultFactory/vaultManager.js#L688

(Same for all other lines that set `state.totalDebt`)
