### ISSUE TITLE
testability for persistence

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4914]
## What is the Problem Being Solved?

When we convert from ephemeral objects to virtual object using `defineKind`, it would be very helpful to be able to write tests that demonstrate paging objects out of memory and back in so that we can use test to verify that all the crucial state has been captured. Being able to use them as regression tests would be an added benefit.

## Description of the Design

To be detailed here

## Security Considerations

This is a robustness issue, more than a security issue.

## Test Plan

Yes, that's the plan!

**Comment by warner** [comment]
@Chris-Hibbert could you close this if you're satisfied?

**Comment by Chris-Hibbert** [comment]
Closed with #5207
