### ISSUE TITLE
Governance to invoke javascript code in bootstrap context

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4915]
## What is the Problem Being Solved?

During bootstrap (and presumably later) it will be necessary for the Econ Committee to be able to set up portions of the economy using actions that are not directly supported by the governance framework. This might include 

* installing contracts, 
* establishing a committee
* creating IBC channels and relayers
* setting up oracle price feeds

Some of these actions will need access to powers that were created in bootstrap

## Description of the Design

__Please fill in details here__

The econ committee should have access to a subset of the powers from bootstrap.

## Security Considerations

Very powerful capabilties

## Test Plan

__Please fill in details here__

**Comment by dckc** [comment]
@Chris-Hibbert I don't understand my assignment here. The description seems to be work-in-progress, and I think I'm missing some context necessary to complete the design. Did you mean to label it **needs-design**?

**Comment by Chris-Hibbert** [comment]
@dckc  I assigned it to you because you've been working on bootstrap, and my instincts tell me that's where this work belongs. Actual work assignments are magic between @dtribble, @Tartuffo and individual engineers, but I hoped you might opine on how this could be done.

I agree that it **needs-design**.

**Comment by dckc** [comment]
The simplest design I can see is that the subset of the powers from bootstrap needed by the Econ committee is empty. Help me find out who knows enough to tell me that this is inadequate?

**Comment by Chris-Hibbert** [comment]
If the econ committee can vote to change contract parameters and to invoke the collateral reserve's API for adding funds to an AMM pool, then it needs access to governance facets for voting that would not be public.

**Comment by dckc** [comment]
> If the econ committee can ... invoke the collateral reserve's API for adding funds to an AMM pool, ...

Well, do we require that the committee can do so? This seems to raise the same questions of scope. I suppose I'll stand by for progress on #4828.

**Comment by Tartuffo** [comment]
Do we need special ability for the Econ Committee to execute JS code?  We believe the answer is "no", so we are going to close this issue.
