### ISSUE TITLE
Companion `lookup(...path)` function for deploy scripts and REPL

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Agoric#4918]
## What is the Problem Being Solved?

Our deploy scripts and REPL need to find objects by naming paths.  To make this easier, I'd like to add a `lookup(...path)` function to have an integrated namespace for traversal.

In doing so, deployment script parameters can specify `lookup` naming paths to find objects, without changes to code.

## Description of the Design

As one of the "deploymentPowers" arguments and also in the REPL as a `lookup` endowment, we would have:

`lookup('agoricNames', 'brand', 'RUN')` - lookup by agoricNames
`lookup('board', 'board0...')` - lookup by board ID
`lookup('namesByAddress', 'agoric1...', 'depositFacet')` - lookup via published names by address
`lookup('wallet', 'brand', 'LINK')` - lookup brand via wallet
`lookup('wallet', 'offerResult', 345)` - lookup offer result identified in wallet

## Security Considerations

This is a powerful endowment and should not be shared.  However, it's no more powerful than the existing capabilities granted to deploy scripts and the REPL.

## Test Plan

Manual testing for now.

**Comment by dckc** [comment]
> Our deploy scripts and REPL need to find objects by naming paths.

They do? That's not self-evident to me.

> ... it's no more powerful than the existing capabilities granted to deploy scripts and the REPL

That much is clear; that is: this looks like a refactoring of existing APIs.

Is there more context to this that I don't see? Is this in service of some other feature?

**Comment by dckc** [comment]
ah...
> Intended to be first used in the oracle deploy scripts.

OK, if this helps with oracles somehow, then... whatever.
