### ISSUE TITLE
Vault creation should have a minimum collateral

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#4967]
Per discussion in wallet meeting, creating a vault should have a governance-controlled minimum collateral parameter at the asset level, which would be enforced only on creation.  

Ideal scenario would be ~$5-$10 range as initial value

**Comment by Tartuffo** [comment]
@rowgraus should also create an equiv ticket for AMMs.

**Comment by Tartuffo** [comment]
We believe this minimum should be defined in RUN.

**Comment by Chris-Hibbert** [comment]
The collateral is never denominated in RUN. One possible interpretation of this is that a new vault won't be opened unless the user deposits enough collateral that they could withdraw $MIN of RUN considering the current price (according to the priceAuthority) and liquidationMargin. It might also mean that the collateral has to be worth $MIN according to the priceAuthority, regardless of liquidationMargin.  Another possibility is that they have to actually ask for $MIN of RUN. 

Requiring that they ask for $MIN of RUN is the simplest. The others are a little more involved. Do you have a preference?   @rowgraus

**Comment by rowgraus** [comment]
Requiring that they ask for $MIN of RUN works just fine.  Essentially: you can't open a vault with zero debt.  That seems reasonable.
