### ISSUE TITLE
 precious state of Inter Protocol features in Vaults release is reachably durable

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4983]
**Acceptance criteria**

Every contract in Inter Protocol is audited for precious state and it's determined to be reachably durable

This does not require that [protocol be upgradable](https://github.com/Agoric/agoric-sdk/issues/5795).

**Comment by Chris-Hibbert** [comment]
Complement of #4511.

**Comment by dckc** [comment]
@ivanlei For reference, the following are the 22 vats created at bootstrap in pismoA:

    "vats": {
        "v1": "bootstrap",
        "v2": "vatAdmin",
        "v3": "comms",
        "v4": "vattp",
        "v5": "timer",
        "v6": "zoe",
        "v7": "board",
        "v8": "chainStorage",
        "v9": "centralSupply",
        "v10": "mintHolder: USDC_axl",
        "v11": "mintHolder: AUSD",
        "v12": "psmCharter",
        "v13": "committee.econ",
        "v14": "mintHolder: BLD",
        "v15": "bank",
        "v16": "walletFactory",
        "v17": "governor: PSM(USDC_axl)",
        "v18": "governor: PSM(AUSD)",
        "v19": "governor: ?",
        "v20": "PSM(USDC_axl)",
        "v21": "PSM(AUSD)",
        "v22": "provisionPool"
    },

https://github.com/agoric-labs/vatviz-g8/blob/06c844b3d71eaf04452776442d50ee49ac7b85c0/www/index.html#L31-L54

**Comment by turadg** [comment]
Closing because all the items in the epic are done:
- vaultFactory reachably durable was done but not closed
- BLD Boost isn't necessary for Vaults release so I removed it and clarified the scope of this epic

Remaining durability and upgrade requirements for release are tracked through milestones.
