### ISSUE TITLE
issues with docker image tags causing makefile commands to fail

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/Agoric#4991]
## Describe the bug
running `make docker-build-deployment` inside of `agoric-sdk/packages/deployment` led me to notice an issue in which the makefile is unable to parse the tag for the docker image in question and instead opts for using `undefined` as the tag. the result of this is a failing build.

## To Reproduce
1. cd agoric-sdk/packages/deployment
2. `make docker-build-deployment`

## Expected behavior
The command should default to the most recent version of the docker image by appending `latest` onto the images tag.

## Platform Environment
 - what OS are you using? what version of Node.js? 
   - MacOS Monterey 12.3 
   - Node v16.14.
 - is there anything special/unusual about your platform?
   - No 
 - agoric-sdk version:
   - agoricdev-8-374-g86a8bade8
  
## Additional context
hard-coding the "latest" tag into the makefile fixes the issue. this is demonstrated in the video below following the initial failed attempt to run the command

## Screenshots

https://user-images.githubusercontent.com/6646552/161320573-0156d048-9e9f-4482-b7f8-c74ae70802b1.mp4

**Comment by arirubinstein** [comment]
Hey @tgrecojs - this makefile is intended to be used with a TAG arg, e.g. `TAG=agoricdev-13 make docker-build-setup`
