### ISSUE TITLE
Maps and sets incorrectly distinguish NaN values

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4998]
For further details, see https://github.com/Moddable-OpenSource/moddable/issues/888

@gibson042 asked whether this is in scope for MN-1. @erights said:
> I am not confident at all that we’re safe from this. Our stores wrap builtin `Map` and `Set`, and delegate much behavior to them under the assumption they are correct. ... Please let’s get this in by MN1. Either that, or we need to review all code that might be affected by this.
> If for some reason we decided to live with it, we’d at least need to fix `MapStores` and `SetStores` to hide the problem, reducing our worries to direct uses of `Map` and `Set`.

The solution is most likely to update our XS to include a fix from moddable, but this issue lets us track it in any case.

**Comment by kriskowal** [comment]
Needs assignee. This looks like it’s close to marshal layer. @erights @FUDCo @mhofman?

**Comment by dckc** [comment]
reportedly fixed Jun 2 in [d7729b2](https://github.com/Moddable-OpenSource/moddable/commit/d7729b28fb72bf72578988580312eb282690ca32)
