### ISSUE TITLE
register handlers for durable promises

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5006]
## What is the Problem Being Solved?

At today's meeting we figured out a smaller approach for #3787 . The problem statement is:

* a vat subscribes to some large number of imported promises
* the vat gets upgraded
* the new version still needs to react to those promises becoming resolved

The "large number" means that we don't want to consume RAM for each promise while we're waiting for it to be resolved. We aren't sure we can manage that in the short-term, but changes to `HandledPromise` (in particular being able to sense `.then` being called) might enable it.

For now we're going to focus on allowing the callbacks to survive upgrade.

## Description of the Design

Rather than implementing something generic like (#4932), we realized we can do something specifically for promise handlers. We'll define a new kind of durable collection. This collection is like a Map: it is enumerable, and stores at most one value per key. The keys are Promises, specifically *imported* promises (decided by the kernel, not the vat holding this collection), which either arrived in some inbound message or resolution, or created as the result promise of an outbound message. The values are any durable data, which we name `context`.

Like `defineDurableKind`, each instance of this collection has a long-lived durable Handle that must be created exactly once, and then stored into (or retrieved from) the vat-upgrade "baggage".

Unlike Kinds (where each Kind has a distinct behavior), each *instance* of this collection is configured with a distinct behavior. The author provides this as a pair of functions named `fulfilledFunc` and `rejectedFunc`. These correspond to the two arguments to `Promise.prototype.then()`. But unlike those, these functions receive *two* arguments:
```js
function fulfilledFunc(fulfillment, context) { ... }
function rejectedFunc(reason, context) { ... }
```

Users can add promise/context pairs to this table by calling `init`, just like a Map-like Store.

If/when the Promise becomes resolved, the appropriate fulfillment/rejection function will be invoked, with both the per-Promise `context` and the resolution value. The Promise will also be removed from the table at that time, so the table will only ever hold unresolved Promises.

Like a WeakStore, the table is not enumerable. However the entries are retained until the Promise is resolved, even if everybody else drops the Promise object.

The entries of this table survive the vat being upgraded. Liveslots will convert each promise into its `vpid` and store that in a table, associated with the serialized (durable) `context` data. When a promise resolution notification (`dispatch.notify`) arrives, liveslots will deserialize the context object and invoke the user-provided function.

We couldn't decide on a name for it, so I'm going to call it EnthusiasticWeasel to avoid biasing the eventual bikeshedding.

```js
const handle = makeEnthusiasticWeaselHandle('table name');

function fulfilledFunc(fulfillment, context) {
  E(context.listener).report(context.other, fulfillment);
}
functiln rejectedFunc(reason, context) {
  E(errorHandler).abort(context.other, reason);
}
const table = makeEnthusiasticWeaselTable(handle, fulfilledFunc, rejectedFunc);

root = Far('root', {
  receivePromise(p, listener) { table.init(p, { listener, other }); },
  doThing(target) { table.init(E(target).foo(), { other }); }
});
```

The table should probably include `.delete` functionality. It's conceivable that it should include `.get` and `.set`, but maybe we can get away without it.

## Future Syntax

@dtribble suggested it would be interesting to integrate this into our eventual-send operation, by adding options that name a table and a context. Something like:
```js
E(target, { watcher: [ table, { other } ] }).foo();
```
which would automatically do `table.init(p, { other })`. This could add the `vpid` without needing to reify the result `Promise` object (although we'd need to do that anyways if we couldn't tell if someone paid attention to the return value of `E(..).foo()`).

Independently of that, if we find a way to instrument the HandledPromise returned by `E(..).foo()` to sense the use-vs-neglect of `.then`, then we could avoid reifying the Promise entirely, which means the memory footprint of these result promises *and* their callbacks goes away, making this suitable for high-cardinality subscribers.

## Security Considerations

Each EnthusiasticWeasel table effectively provides access to the values captured by the handler functions, so different components of the system should have their own instances. This lines up well with our planned usage of Handles for Kind registration, e.g. Zoe gets access to one portion of "baggage", while the contract gets a separate portion, and each can stash their own instance of these tables in their own portion.

Allowing `.get` or `.set` would allow someone to amplify access to both the Promise and the table into access to the handler, which would be surprising (generally, having access to a Promise means you can add *new* callback behavior, but not invoke or read or interfere with anybody else's callbacks). That's probably a good argument to omit `.get` and `.set`, and maybe even `.delete`. And it means the Store's use of `.init` instead of `.set` is great, no possibility of overwriting someone else's behavior.

## Test Plan

Unit tests.

## Alternate Designs

We originally considered making the table enumerable but not associating behavior. Instead, at the beginning of each new vat version, user code would be able to enumerate the promises in the table, and could add their own `.then` handlers to each. This requires reifying all Promises (which costs RAM) when in fact the behavior can probably be factored out and provided just once (using a context object to behave differently for each Promise).

Instead of providing the two behavior functions at table definition time, we considered an additional call which sets (or re-sets) the behavior later. We've observed that a lot of our durable behavior tools wind up involved in circular definitions, where we need to access the table from some behavior functions, but we need those functions before we can defined the table. By providing behavior to `makeEnthusiasticWeaselTable()`, we avoid the questions of "what if someone forgets to call `setBehavior`?" and "what if someone calls it twice?", but we push the mutable-binding complexity onto the user.

The promise provided to `table.init(p, context)` must be decided by the kernel, not the vat. It will throw an error if given a promise that is (or would be) decided by the local vat, e.g. a Promise that liveslots does not yet know about (which would be exported to the kernel and thus decided by the vat). We considered allowing these promises to be used, and invoking the handler functions if the vat subsequently resolved them, but that leaves open a question about what should happen in version-2. Only the old version-1 RAM image had access to the `resolve`/`reject` functions, so after upgrade, these promises won't ever resolve (the Promises might be durable, but the resolvers/rejectors are not). So we'd have to arrange for liveslots to reject them all (e.g. call all their `rejectionF` behaviors) during upgrade, shortly after the new behaviors were reassociated. That seemed unhelpful, so we decided to refuse to accept non-imported Promises outright.

## Names

Some words that might go into the name:
* register
* define
* unsettled
* promise
* when
* then
* table
* store
* durable
* handler
* behavior
* callback
* callbacks

Note that the callbacks/behavior themselves are not durable (each version of the vat must supply new ephemeral functions). The context object *is* durable (`table.init` will throw an error if you attempt to save non-durables in `context`, just like a durable MapStore). The Promises must be imported, so it might be fair to call them durable promises.

## CC

@FUDCo @erights @michaelfig

**Comment by mhofman** [comment]
Reading this, it occurs to me that what you're creating is a durable promise watcher of a certain shape with a user defined state. There is also logic to automatically create that virtual watcher and linking it when adding the promise to a special kind of table, but I'm wondering if that's strictly necessary.

```js

const watcherKind = makeKindHandle('watcher');

const initWatcher = (other, listener) => {
  const state = { other, listener };
  return state;
};

const makeWatcher = defineDurableKind(
  watcherKind,
  initWatcher,
  {
    fulfilled: ({ state }, fulfillment) => E(state.listener).report(state.other, fulfillment),
    rejected: ({ state }, reason) => E(errorHandler).abort(state.other, reason),
  }
);

E(target, { watcher: makeWatcher(other) }).foo();
// or
E.watch(promise, makeWatcher(other));
```

The `fulfilled` or `rejected` methods of the durable virtual watcher would be called once the imported promise settles.

For delete, there are multiple options, including:
- Modelled like [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) with `E.watch` accepting an abort `signal`.
- `E.watch()` returning a durable `canceller` of the shape `{ cancel: () => void }`

These objects would all have to be durable. In the case of the abort controller, that's probably a pattern we can re-use for other use cases, and we could consider having liveslots setup the durable kind for them (afaik liveslots is free to have it's own section of the baggage?).

Then if the contract has any interest in remembering the watcher objects, it can use regular durable weak collections (do we have those?):

```js

const watcherMapKind = makeKindHandle('watcherMap');

const watcherMap = makeScalarBigWeakMapDurableStore(watcherMapKind);

const watcher = makeWatcher(other);
const abortController = makeAbortController();
watcherMap.init(promise, { watcher, abortController });
E.watch(promise, watcher, { signal: abortController.getSignal() });

// Later

const { watcher, abortController } = watcherMap.get(promise);
abortController.abort();
// or
watcher.someCustomMethod(someData);
```

**Comment by michaelfig** [comment]
> Reading this, it occurs to me that what you're creating is a durable promise watcher of a certain shape with a user defined state.

I can see the composability merits of your comment.  From the code you wrote, I'd counter with a slightly different spelling:

```js
const watcherKind = makeKindHandle('watcher');
const makeWatcher = defineSelfishDurableKind(
  watcherKind,
  {
    fulfilled: (self, fulfillment) => E(self.listener).report(self.other, fulfillment),
    rejected: (self, reason) => E(errorHandler).abort(self.other, reason),
  }
);

// interpret `watcher` in liveslots' HandledPromise traps ...
E(target, { watcher: makeWatcher({ other }) }).foo();
// or use a powerful global
VatData.watch(promise, makeWatcher({ other, listener }));
```

---

Do note that I'm leaning on some boilerplate reduction vis-a-vis `defineSelfishDurableKind`.  This is a strawman:

```js
const defineSelfishDurableKind = (kindHandle, methods) => {
  const wrapWithSelf = method => ({ state: { self }}, ...args) => method(self, ...args);
  const kind = defineDurableKind(
    kindHandle,
    self => harden({ self }),
    Object.fromEntries(Object.entries(methods).map(wrapWithSelf)),
  );
};
```

- The trivial `init` argument doesn't need to be written out.
- No support for multifacets removes need for access to `context`.
- Implicitly extracting the `state.self` property reduces the need for destructuring.

**Comment by michaelfig** [comment]
I'll sketch out a variant to bring my strawman one step closer to the initial description by @warner mixed with what I understand of @mhofman's comments:

```js
const watcherKind = makeKindHandle('watcher');
const makeWatcher = definePromiseWatcher(
  watcherKind,
  (fulfillment, context) => E(context.listener).report(context.other, fulfillment),
  (reason, context) => E(errorHandler).abort(context.other, reason),
);

E(target, { watcher: makeWatcher({ other }) }).foo();
VatData.watch(promise, makeWatcher({ other, listener }));
```

and:

```js
const definePromiseWatcher = (kindHandle, fulfilled, rejected) => {
  const kind = defineDurableKind(
    kindHandle,
    ctx => harden({ ctx }),
    {
      fulfilled: (context, fulfillment) => {
        if (fulfilled) {
          // Adapt arguments.
          const { state: { ctx }} = context;
          return fulfilled(fulfillment, ctx);
        }
        return fulfillment;
      },
      rejected: (context, reason) => {
        if (rejected) {
          // Adapt arguments.
          const { state: { ctx }} = context;
          return rejected(reason, ctx);
        }
        throw reason;
    },
  );
};
```

**Comment by warner** [comment]
I can mostly visualize what `VatData.watch` or the earlier liveslots-supported tools would take to build. What's the current situation with an `E()` options bag? IIRC it was in some draft of the spec, but do we have an implementation?

**Comment by michaelfig** [comment]
> What's the current situation with an `E()` options bag?

I now know what to do to make the options bag robust wrt options vs. required features.  I will create a work item issue on the eventual-send repo, and get some agreement behind it.

> do we have an implementation?

I was holding the implementation until the switch to `Promise.delegated`, but just doing the options bag should not take much work to implement in `HandledPromise`.  I'd estimate 2-4 hours work on my part, but probably a calendar day for all the reviews and coordination between `tc39/proposal-eventual-send`, `endojs`, and `agoric-sdk`.

**Comment by mhofman** [comment]
I don't know how the layering would work exactly, but I kinda assumed that `E.watch` or some options to `E` would delegate to "handlers" that liveslots sets up and fallback to a default implementation. E.g. `E.watch` in a non-liveslots environment would simply do `promise.then(watcher.fulfilled, watcher.rejected)`

**Comment by warner** [comment]
In today's meeting, we (@warner @michaelfig @FUDCo @mhofman) converged on the following user-visible syntax:

```js
// this happens once per vat
const watcherKindX = makeKindHandle('watcher');

// this happens once per version
const watcherX = VatData.makePromiseWatcher(watcherKindX,
                                            (fulfillment, ...args) => stuff,
                                            (reason, ...args) => stuff
                                            );

// this happens once per call
const p = E(target).method();
VatData.watch(p, watcherX, ...args);
```

Notes:
* the user-written callback/errback functions get their context (`...args`) as additional arguments, not as captured variables or a `state` object
* if the user functions throw or return a Promise which rejects, the platform's unhandled-rejection behavior is triggered (maybe logging an error message)
* `VatData.watch` returns `undefined`, not a Promise: we don't enable chaining (to keep the implementation simpler and to avoid allocating additional promises)
  * so the user functions need to do their own chaining and error handling
  * so they'll probably be longer than a single line
  * so it's likely that they'll be defined elsewhere and only their names will appear in the call to `makePromiseWatcher()`
* the `...args` given to `VatData.watch` must be durable, else `watch` throws

If/when we get an option bag in `E()`, we can imagine some alternate ways to register the watcher:
```js
E(target, { watcher: watcherX }).foo();
E(target, { watcher: [watcherX, ...args] }).foo(); // mathieu: eww
E(target, { watcher: watcherX, watcherArgs: args }).foo(); // mathieu: better
```

Internally, `makePromiseWatcher` is implemented by creating a new durable Kind and making a single instance of it:
```js

function makePromiseWatcher(watcherKindHandle, f1 = x => x, f2 = x => { throw x }) {
  const makeW = defineDurableKind(watcherKindHandle, () => {},
                                  {
                                    onFulfilled: ({}, res, ...args) => f1(res, ...args),
                                    onReject: ({}, res, ...args) => f2(res, ...args),
                                  });
  return makeW();
}
```

and then `VatData.watch` (provided by liveslots) manages a durable table with effectively three columns: the `vpid` of the watched Promise, the `vref` of `watcherX`, and the serialized (durable) `args`. When liveslots receives a `dispatch.notify(vpid)`, it will unserialize `watcherX` and invoke either its `onFulfilled` or `onReject` method with the unserialized resolution/reason and the unserialized `args`.

```js
// table: [vpid, vrefWatcherX), argsCapData]

// when p is resolved:
const w = unserialize(vrefWatcherX))
const res = unserialize(resolutionCapData);
const args = unserialize(argsCapData);
w.onFulfilled(res, ...args)
```

## analysis

This approach specializes for the promise watcher, rather than letting the user associate a generic durable object (with `.onFulfilled/.onRejected` methods) with the promise. This removes some boilerplate, and avoids the need to allocate a new durable object for each call.

The `E(target, { watcher })` form might not return a Promise: by providing `watcher`, you're telling E() that the watcher is sufficient and we don't need a real `Promise` to attach the response behavior. If so, there wouldn't be a RAM obligation incurred by the call: we'd never need a real `Promise` so we'd never need to add its resolver/rejector to a table. That'd be great for reducing RAM usage.

We figured that each binding (each call which needs resolve/reject callback behavior) has about 3 properties: the promise being watched, the kind of behavior to trigger, and the context data carried from the point of send (promise creation) to the point of response (callback/errback execution). That gives `3! = 6` ways to order the arguments and probably another 2x ways to glue them together.

One alternative was `VatData.watch(p, durableObj)`, in which case you'd define a normal durable Kind (with `onFulfilled/onRejected` methods), and then the callback-attachment site would need to allocate a new one to stash the `context` (`VatData.watch(p, makeResponseX(context))`). A nice property of that approach would be that liveslot's table just maps `vpid` to one (or more) durable objects, and simply calls the right method on them. We could conceivably push that out into the kernel: `syscall.subscribe(vpid)` might become `syscall.subscribe(vpid, responderVref, contextCapData)`, and the *kernel* could take responsibility for sending a *message* to the responder object if/when the promise became resolved. If the responder were in some other vat, that would shorten some paths. (This feels like it would overlap with promise forwarding / path-shortening, but probably not in a good way). However, user code would be more verbose.

**Comment by mhofman** [comment]
> One alternative was `VatData.watch(p, durableObj)`, in which case you'd define a normal durable Kind (with `onFulfilled/onRejected` methods)

The past tense is misleading. User are free to take that approach with the proposed design, it's just not the emphasized way.

One advantage of that approach is for example if `durableObj` is one of the facet of a multi-facetted object which can now have its state updated through the other facets.

**Comment by warner** [comment]
Hmm, I think the form you're thinking of is `VatData.watch(p, durableObj, ...args)`. And yeah, users are free to do that with this scheme. The alternative I think we rejected was to omit the third++ arguments, and make users do something closer to `VatData.watch(p, makeDurableResponderX(args))`. That would look more like the "make a new closure at the point of `.then`" pattern that folks are used to, but it would also have more overhead (allocating new durable-object IDs, creating a short-lived Representative).

**Comment by mhofman** [comment]
I meant `args` are not required. The current design accept them (and should accept args being empty), and should simply accepts any durable object for the second argument, so that users are able to make a sort of "closure" in the form of a unique durable object if they want.

**Comment by dtribble** [comment]
It may just be a passable object (eg just data)

**Comment by mhofman** [comment]
If you're referring to the type of the `args`, I'm not sure what the right terminology is, but it's basically "durable data", aka anything passable except (recursively) no virtual but non-durable object, an no far objects, but does include copy data and presences.

That does remind me. If we wanted to support virtual but non-durable watchers, for use cases like handling a large amount of promises (assuming we can avoid leaking the result promise in the first place), what would the API look like? Should we name the durable promise `makeDurablePromiseWatcher` and reserve `makePromiseWatcher` for the virtual non-durable case? Then `VatData.watch` could sense if the watcher is durable or not, and use a virtual or durable map internally?

Btw I don't remember the discussions, but I suppose we ruled out having a single `defineKind` which builds a virtual kind if the first arg is a string, and a durable kind if the first arg is a kind handle? In which case we could also have a single (pass-through) `makePromiseWatcher`.
