### ISSUE TITLE
Integrate PSM with bootstrap

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5010]

**Comment by dckc** [comment]
@Tartuffo @dtribble @rowgraus let's flesh out the description by telling a story about what the world looks like when this is done, ok? My impression is something like:

 1. Somebody makes a USDC transfer over IBC, resulting in IBC denom 98239427 in the Agoric chain
     1. [ ] from where? gravity bridge?
 2. Somebody makes a cosmos governance proposal to start the PSM
     1. Bootstrap to add 98239427 to VBANK, resulting in an ERTP issuer to play the `AUSD` role in the PSM
     2. Bootstrap to start an instance of the PSM contract, giving it RUN fee mint access as well as timer, AUSD, etc.
         1. "the PSM contract" is identified by hash
 4. BLD holders vote for the proposal
 5. the proposal passes and the PSM is started

cc @michaelfig @Chris-Hibbert

**Comment by dckc** [comment]
@michaelfig this VBANK IBC denom for AUSD seems to be the only part of the RUN protocol governance that isn't a design-time parameter. I'm inclined to make psm start its own governance proposal, for that reason. Our design accomodates multiple proposals per package, right?

**Comment by michaelfig** [comment]
> Our design accomodates multiple proposals per package, right?

Right!

**Comment by dckc** [comment]
psm governance is separate: #5153

but the PSM boot code following the normal pattern (#5165) expected to have `psm` and `AUSD` in agoricNames at bootstrap, but that's not the case. So we'll need a workaround.

**Comment by dckc** [comment]
@michaelfig while working on this PSM work-around, I'm thinking about an alternative to some of the `writeCoreProposal` mechanics: one board ID for a `Map<Hash, Installation>`.

On [dc-psm-gov-workaround](https://github.com/Agoric/agoric-sdk/tree/dc-psm-gov-workaround), see:
 - [run-protocol/src/psm/writePsmScript.js](https://github.com/Agoric/agoric-sdk/blob/dc-psm-gov-workaround/packages/run-protocol/src/psm/writePsmScript.js)
 - [run-protocol/scripts/gov-startPSM.js](https://github.com/Agoric/agoric-sdk/blob/dc-psm-gov-workaround/packages/run-protocol/scripts/gov-startPSM.js)
