### ISSUE TITLE
Move penalty funds from Liquidation to Reserve

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#5012]
## What is the Problem Being Solved?

VaultFactory now collects penalties when Vaults are liquidated, but currently those funds sit in a seat in the liquidation contract.

## Description of the Design

Periodically (hourly? daily? weekly?) call a function to invoke the collectPenaltyFees method of liquidation, and transfer the funds to the Collateral Reserve. It should first check to see the balance on the seat, and if it's empty, no more work has to be done. 

There's little value in moving the money as soon as it's collected, since it would just sit in the Reserve waiting for a committee decision to deploy it. Collecting the funds in the penaltySeat is low-cost, since that's a reallocate within Zoe. Transferring the money to the reserve is a costly transaction, since it involves multiple contracts and multiple purses. A daily check is probably a good choice.  

## Security Considerations

The process is probably triggered from bootstrap. It has valuable capabilities (the ability to collect funds from the liquidity contract) so should be carefully handled. Ensure the facets aren't exposed unnecessarily.  
Ensure the task will be reinitialized on restart.

## Test Plan

validate that funds make it all the way from collecting a penalty to depositing in the Reserve.

**Comment by Tartuffo** [comment]
Dup with #5367
