### ISSUE TITLE
don't drop adminNode needed to upgrade Zoe

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5013]
## What is the Problem Being Solved?

We're definiing a bunch of mechanisms to allow individual contracts to be upgraded, most of which is driven by Zoe and the per-contract governance code.. We need to nail down the process by which Zoe itself is upgraded.

At the swingset level, this will use the same tools as contract upgrade: something with the admin facet for the Zoe vat (probably bootstrap) will use it to tell swingset to shut down the old vat and replace it with a new code bundle. Zoe will need to keep all its retained state in durable objects/collections, and deliver the important parts to its successor via `baggage`. The new version will need to re-establish behavior for all durable kinds.

Tentatively assigning to MarkM as keeper of Zoe.

## Description of the Design

TBD

## Security Considerations

all of them

**Comment by dckc** [comment]
DT: we need to distinguish upgrading zoe and upgrading zcf. This looks like the Zoe service.

Nick: dup of #4383?
Zoe meeting: concur.

**Comment by warner** [comment]
This issue is about how to upgrade the Zoe service. Making Zoe's state durable (#4383) is a necessary precondition, but we also need:
* the bootstrap code must hold on to the adminFacet for vat-zoe (since Zoe is no longer a static vat)
* somebody needs to be able to tell the bootstrap code to do `E(zoeAdminFacet).upgrade(newBundleCap, vatParameters)`

I'm guessing the latter will be done by the "big JS hammer" governance tool. If so, the only change needed to close this ticket is for the bootstrap code to retain the adminFacet in a place where the hammer can reach it.

I don't think that's the case yet, so I'm reopening this, to make sure we don't wind up with a durable-but-not-upgradable Zoe.

**Comment by warner** [comment]
adding @dckc since I think he's the one to change bootstrap to retain the admin facets

**Comment by dckc** [comment]
> ... since Zoe is no longer a static vat

If returning Zoe to a static vat would simplify things, that's straightforward.

In fact, the main motivation for moving vats from static to dynamic was that some of them are only for demo purposes, not production. I don't see any lasting examples of that... perhaps `vat-mints.js` was the only one, and it went away altogether.

_p.s. marking this as pre-requisite to #4548 ; there are a few related issues I'd like to brainstorm about together._

**Comment by warner** [comment]
Nope, actually, we don't yet have a mechanism to upgrade static vats, so leaving it as a dynamic one is better. But bootstrap does need to unpack and retain the admin facet at the same time it gets the root object.
