### ISSUE TITLE
Sufficient durability / upgradability of Vat contracts for launch

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5014]
This is an umbrella ticket to track the pieces needed for upgrading individual contracts and core pieces of the chain.

* Vat Upgrade:
  * #1848
  * ~#4382~ unscheduled
  * bundlecaps to name bundles:
    * #4372
    * #3269
    * #4566
    * #4326
    * ~#1346~ unscheduled
    * #4521
  * bundlecaps to load bundles:
    * #4373
    * ~#4486~ unscheduled
    * #4719
    * #4396
  * zoe using bundlecaps to name contracts:
    * #4563
    * ~#4564~ V+1
    * ~#4565~ V+1
  * vat upgrade gets contract bundlecaps:
    * #4726
    * #4588
    * #4381
* durable objects/collections so upgrade retains behavior:
  * #4495
  * #4255
  * #2004
  * "baggage":
    * #4325
    * #2910 
  * makeKind upgrade
    * #3062
* Liveslots upgrade:
  * #4376
* Kernel upgrade:
  * #4375?
* make contracts durable:
  * #4511
* contract upgrade:
  * #3272
* zoe upgrade:
  * #4383
  * #5013

**Comment by dckc** [comment]
From a PSM slog, I have this list of vats; I wonder to what extent they're covered by existing issues:

 - "v7": "board", #6553
 - "v8": "chainStorage", #6553
 - "v15": "bank", #6849
 - "v6": "zoe", #4383
 - "v1": "bootstrap", #4548
 - "v4": ~~mailbox~~ vattp #5667
 - "v2": "vatAdmin", #5669
 - "v3": "comms", "is transcriptless, so it's already taken care of."
 - "v5": "timer", #5669

vats that are contracts:
 - "v9": "centralSupply", #6553
 - "v10": "mintHolder: USDC_axl", #6553
   - "v11": "mintHolder: AUSD", #6553
   - "v14": "mintHolder: BLD", #6553
 - "v12": "psmCharter", #5200
 - "v13": "committee.econ", #5200
 - "v17": "governor: PSM(USDC_axl)", #5200
   - "v18": "governor: PSM(AUSD)", #5200
   - "v19": "governor: ?", #5200
 - "v16": "walletFactory", #5894
 - "v20": "PSM(USDC_axl)", #6099
   - "v21": "PSM(AUSD)", #6099
 - "v22": "provisionPool" #6553

**Comment by turadg** [comment]
@warner I went through the open items in the description task list with @dckc . We struck out the ones that aren't scheduled for Vaults release. All that were left were already done so I'm closing this.
