### ISSUE TITLE
Governance determine liquidation strategy for Vaults

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#5015]
## What is the Problem Being Solved?

The liquidation strategy is a parameter for Vaults. It's currently specified as a `Strategy` object, which is an API with `{ makeInvitation, keywordMapping, makeProposal }`.  

Our assumption was that the liquidation strategy could be specified separately from the contract, but no mechanism was provided.

## Description of the Design

The choice of liquidation approach should be controlled by governance. It's obviously a parameter. It would be possible to add a type for the strategy, or treat is as `unknown`, but I think would be perfectly sensible to use an `instance`. The liquidation contract (`liquidateMinimum.js`) is parameterized with the AMM, and probably the liquidation penalty, so the `installation` wouldn't be sufficient.

Vaults should be refactored to take the liquidation `instance` as a governed parameter.

We don't yet have a solid proposal for a second liquidation approach, so the need for this is not imminent. Various theories are being bandied about. 

## Security Considerations

Standard cross-contract dependency issues. The liquidation contract collects fees and holds them for the Reserve (#5012). Governance would control which contract the Vaults make use of.

## Test Plan

Verify that liquidation approach changes after the vote.

**Comment by dtribble** [comment]
Addressed by #5211
