### ISSUE TITLE
ERTP payment will need proper TS type def for new VO API

### ISSUE THREAD

**Issue by FUDCo** [Agoric/Agoric#5018]
## What is the Problem Being Solved?

PR #4962, when it lands, introduces a revised API for virtual objects.
This required updating the existing VOs to match the API changes, which that PR does.
However, it does not properly update all of the corresponding JSDoc TS type annotations, on account of non-obviousness.

In particular, `packages/ERTP/src/payment.js` contains the comment:
```
  // XXX the following type cast is meatball surgery to make tsc shut up
  // somebody who understands this should do it properly
```
Somebody who understands this should do it properly.

**Comment by FUDCo** [comment]
Addendum: `packages/run-protocol/src/vaultFactory/vault.js` also needs a rigorous pass from somebody who understands the TS subtleties.  In general, I suspect the type declaration issues surfaced there will apply to any use of the new VO API, so if we can get some general base TS type infrastructure to that end as part of the deal that would be awesome.

**Comment by Tartuffo** [comment]
@FUDCo What is the meeting label for this?  cosmic-swingset?
