### ISSUE TITLE
Real-time price updates in AMM UI

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#5019]
The AMM needs to be able to update the price of swaps from a notifier in real-time

**Comment by Tartuffo** [comment]
This does not have to block launch.  @samsiegart can you revisit the estimate on this one?  Don't we already get state from notifiers, and this is just one more notification to render?

**Comment by samsiegart** [comment]
@Tartuffo Currently the UI gets the price by polling the contract for the total liquidity for each asset in the pool and calculating the exchange rate from that. It only updates when you select different assets. It's my understanding that `priceAuthority` should be used instead.

Currently there's some bugs/crashes around the aforementioned logic, so I'll need to rewrite that code anyway. The estimate I believe is accurate because of those bugs, and there may be some nuance to iron out around debouncing price updates while the user is changing inputs.

**Comment by dckc** [comment]
https://github.com/Agoric/agoric-sdk/issues/4648 should provide the relevant notifier

**Comment by samsiegart** [comment]
> #4648 should provide the relevant notifier

To be explicit, we need the notifier for `The pool amounts (X, Y, LP)` to calculate the estimated results of each swap.
