### ISSUE TITLE
Run expensive integration tests before merging

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#5030]
## What is the Problem Being Solved?

Some CI jobs are currently too expensive to run for every PR push (e.g. deployment-test which takes 30+ minutes each time), so we have some integration tests that run only on master, and notifications sent if tests fail on master.

We've had multiple occurrences of PRs breaking integration tests, sometimes requiring a simple update to the dependent system, sometimes requiring more complex changes, and the notifications cause noise and questions as to who is responsible to take action.

In a perfect world, a "candidate" branch would be created with the tentative PR merge commit, all regular + integration tests would run on that temporary branch, and if all tests pass, the master branch would fast forward to the merge commit on the candidate branch, showing the PR as merged. That's how GH merge queues work, but not how mergify works. Unfortunately GH merge queues do not support the rebase + merge pattern that we prefer.

## Description of the Design

It's unclear how to solve this situation.

Mergify does support "merge branches" but these create a temporary PR which is then merged into master, creating unnecessary noise, conflicting with our tidy commits, and simply disconnecting the PR from the merge commit.

There may be other merge bots which support our requirements better.

Another idea might be to require labels as check status , if it doesn't interfere with reporting of CI jobs success / failure (maybe use a `action_required` completion ?):

First step, once the PR has gone to initial review iterations, one of either:
- `ready-for-merge` to trigger more expensive integration jobs
- `bypass-integration` to advance without running integration jobs

Then, simultaneously or later, one of either:
- `automerge: rebase`, `automerge:squash`, `automerge:merge` to trigger mergify
- `manual-merge` to allow merging using GH directly instead of mergify

The [`github-checks` action](https://github.com/marketplace/actions/github-checks) may help leverage the more extensive [Checks API](https://docs.github.com/en/rest/reference/checks).

## Security Considerations

Bypassing integration CI jobs (or the merge queue) should not be the common flow, and we could possibly notify in chat when those actions are taken.

Administrators should maintain an escape hatch to bypass all checks and be able to forcibly merge, but this flow shouldn't be available to most members.

## Test Plan
This will probably require trial and error, and setting up a new repo to try alternatives instead of disrupting the flows on this repo would be preferable.

**Comment by Tartuffo** [comment]
If we don't do something automatic, we should determine the SLA.

**Comment by mhofman** [comment]
This has mostly landed, in #5254 and follow-up PRs.

There are still ways to bypass, even inadvertently, but the job will run on master in those cases, and fallback to the email/slack message for notification.
