### ISSUE TITLE
Zoe supports Snoozing specific incoming offers for invitations

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5036]
When RUN Protocol is launched, we may face a situation where there are bugs or attacks on contracts that pose economic danger to individual users or the entire chain economy.

We considered the following options for handling these kinds of situations:

- "Hammer": for a contract instance, Zoe rejects offers for invitations whose descriptionString is in the snooze list
- "Wrench": for a contract instance, Zoe rejects all reallocates that use a brand that is in the snooze list
- "Screwdriver": for a contract instance, Zoe rejects all offers for a particular internal “partition” (e.g., pool or vault or account)

We've decided to implement the "Hammer" solution for MN-1.

The appropriate Governance committee can vote to "snooze" incoming offers for invitations from making it to the target contract.   During the snooze period, those offers for invitations will be rejected, with an appropriate error message.

On the Zoe side, we could leverage or extend the stopAcceptingOffers capability granted to Zoe in zoeService/startInstance.js.

This issue covers the code implementation to support this feature.  Another ticket should be created to cover the governance workflow and documentation.

**Comment by Tartuffo** [comment]
@rowgraus Please create a ticket for the Governance side of this.

**Comment by Tartuffo** [comment]
Design here: https://drive.google.com/drive/u/0/folders/13MifhaEn0slybFA-_bD_xMDOFJc2kJLV

**Comment by Chris-Hibbert** [comment]
Discussed at Zoe meeting 2022/4/27.  The accepted approach is via contract governance and zcf.

1. add a method to ZCF to allow the contract to specify a list of strings. Attempts to exercise invitations whose description match a string on the list will error.
2. Add support for governance to be able to update that list.
3. (#4142) Also add a question posing contract to guide and constrain the Econ committee in creating governance questions for the contracts they control.

implications: 

A. Zoe remains ignorant of governance
B. The contract's electorate can make these changes, which also means that the economic committee has this power for the core economic contracts.

**Comment by Chris-Hibbert** [comment]
Fullfilled by #5749
