### ISSUE TITLE
Version tagging for dapps

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#5037]
## What is the Problem Being Solved?

Dapps are constantly broken due to `agoric-sdk` changes. This is because there's an implicit assumption that dapps will be run alongside the latest `master` branch of `agoric-sdk`.

## Description of the Design

The dapps should all have branches that correspond to specific `agoric-sdk` releases, and their `README`s should document which branch of the dapp and sdk to run. Whenever an `agoric-sdk` **devnet** release is cut, e.g. https://github.com/Agoric/agoric-sdk/tree/agoricdev-8, we should go through all the dapps, cut a new release branch (e.g. https://github.com/Agoric/dapp-treasury/tree/beta), make sure it works, and update the `README`.

## Test Plan

The following dapps should initially be fixed up to work with `https://github.com/Agoric/agoric-sdk/tree/agoricdev-8`, have a new branch called `dev-8` cut, and have their `README`s updated to instruct users to checkout `agoricdev-8` and `dev-8` respectively:

- [x] https://github.com/Agoric/dapp-treasury
- [x] https://github.com/Agoric/dapp-amm
- [x] https://github.com/Agoric/dapp-fungible-faucet
- [x] https://github.com/Agoric/dapp-card-store

**Comment by michaelfig** [comment]
Please make the branch `agoricdev-8`, not `dev-8`.  We're referring to a specific chain ID, not just a short tag.

**Comment by michaelfig** [comment]
@samsiegart, I think I see a problem that likely misguided you: `git checkout beta` in the `agoric-sdk` should always point to the latest devnet, but it was pointed at `agoricdev-7`.  I just now updated it to `agoricdev-8`; that would probably make your instructions a lot clearer on all the repos (rather than referring to an `agoricdev-*` tag by name, just use `beta`).

Sorry about that!

**Comment by samsiegart** [comment]
> @samsiegart, I think I see a problem that likely misguided you: `git checkout beta` in the `agoric-sdk` should always point to the latest devnet, but it was pointed at `agoricdev-7`. I just now updated it to `agoricdev-8`; that would probably make your instructions a lot clearer on all the repos (rather than referring to an `agoricdev-*` tag by name, just use `beta`).

Updated all the linked PRs to point to `beta` instead of `agoricdev-*`. PTAL.
