### ISSUE TITLE
Improve failure handling in liquidation

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5045]
## What is the Problem Being Solved?

The liquidation queue assumes the liquidating the head will succeed eventually. There may be unforeseen reasons it doesn't and that would block the rest of the queue.

Problem is lack of analysis of ways liquidation could fail and and how to recover. Also known bugs like https://github.com/Agoric/agoric-sdk/issues/5100

## Description of the Design

Research needed but some nascent ideas:

- vaults that fail go into a separate collection to be processed again (periodically or on a governed method invocation)

## Steps to reproduce

1. Change the liquidate function in liquidation.js to throw
2. run vault automated tests
Alternatively, add the throw in the liquidateMinimum contract. Same result.

Requirements
- vaults that fail to liquidate keep their collateral

**Comment by Tartuffo** [comment]
@dtribble is this fixed?

**Comment by turadg** [comment]
I think this is addressed by https://github.com/Agoric/agoric-sdk/pull/5223
