### ISSUE TITLE
Document Inter Protocol governance parameters

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5046]
All Inter Protocol contract governance should be documented in Gitbook and updated prior to the Vaults release

**Comment by Tartuffo** [comment]
As @Chris-Hibbert pointed out: "This doc doesn't mention that all governed contracts have a governed parameter for their electorate."  I need to add that.

**Comment by dckc** [comment]
This has largely transitioned from engineering to product:
 - <a href="https://docs.inter.trade/inter-protocol-system-documentation/protocol-and-chain-governance">Protocol &amp; Chain Governance - Inter Protocol User &amp; System Docs</a>

I suppose that raises the question of how / whether to keep those docs in sync with `packages/run-protocol/docs/governance-params.md`...

**Comment by dckc** [comment]
The Gitbook documentation is done.
