### ISSUE TITLE
Install latest chain platform software in devnet on April 18

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5049]
## What is the Problem Being Solved?

In preparation for the RUN Protocol preview release on April 22 (#5062), we plan to install the latest chain platform software in devnet on April 18.

## Description of the Design

Address the following blocker issues:

 - #4564 
 - #4911
 - #5128 
 - #5094 
 - #5029 

Then release as usual following [internal testnet / devnet release process](https://github.com/Agoric/agoric-private/wiki/Testnet-Release-Process).

## Security Considerations

No impact on production.

## Test Plan

TBD

**Comment by dckc** [comment]
"latest" now? Or "latest" with some in-progress features? If so, which features? What's in the critical path?

In particular, I gather hash bundles are planned; I'm not sure which issue captures that feature; #4974 is at least part of it.

Also, at least one of the solutions we are considering for #5029 involves a platform change (bootstrap vat), so unless / until we choose another design, that one seems critical path.

**Comment by dckc** [comment]
It's alive!

https://devnet.explorer.agoric.net/blocks/2
4F1529001AD114859965C6B2A8B71770646137C167C84F83C7319AD1402D5F52
19 Apr 2022, 12:13:52am UTC (12 minutes ago)

https://github.com/Agoric/agoric-sdk/pull/5142
