### ISSUE TITLE
As a new user creating a vault, I need to be able to deposit assets into Agoric from alternative chains

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5064]
E.g.,  Osmosis and Junoswap deposit screens

**Comment by dckc** [comment]
@rowgraus we figured out how to do this from the command-line: https://github.com/Agoric/agoric-sdk/issues/5247#issuecomment-1112848713

Does that suffice for this preview?

**Comment by dckc** [comment]
Is this worth tracking separately from https://github.com/Agoric/dapp-inter/issues/34 ?
Or should we close it as a dup?

**Comment by otoole-brendan** [comment]
@samsiegart @dckc agree we should closed this in favor of #34.
