### ISSUE TITLE
As a new user creating a vault, I need to be able to be able to choose which asset to use (if multiple are available) and to understand the cost and risk implications

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5065]

**Comment by samsiegart** [comment]
![image](https://user-images.githubusercontent.com/8848650/163901687-7ece7f9b-4b6c-4c43-bfe0-caafa7377a0e.png)

Also "A stability fee of [x]% will be charged on vault creation." in step 2.

**Comment by rowgraus** [comment]
Confirmed, closing

**Comment by dckc** [comment]
This isn't working in devnet, is it?

How was the screenshot above produced? What software version(s)?

**Comment by samsiegart** [comment]
> This isn't working in devnet, is it?
> 
> How was the screenshot above produced? What software version(s)?

Yes (as of 3 days ago), I tried on devnet and the vaults didn't load. We've been testing these on sim-chain at the latest head commit at the time.

**Comment by otoole-brendan** [comment]
superseded by https://github.com/Agoric/dapp-inter/issues/2
