### ISSUE TITLE
As a new user creating a vault, I need to understand the relevant parameters that affect the vault that I will create

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5066]
Stability fee
Liquidation fee
Collateralization Requirement
System-level amount of RUN available to borrow (driven by asset-specific debt limit at the system level)
RUN available to borrow (based on debt limit per collateral type)

**Comment by samsiegart** [comment]
TODO:
- System-level amount of RUN available to borrow (driven by asset-specific debt limit at the system level)
- RUN available to borrow (based on debt limit per collateral type)

**Comment by otoole-brendan** [comment]
superseded by https://github.com/Agoric/dapp-inter/issues/2
