### ISSUE TITLE
As an existing user managing a large number of vaults, I need to be able to easily find the vaults I’m looking to manage

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5068]

**Comment by samsiegart** [comment]
Related 
![image](https://user-images.githubusercontent.com/8848650/163903047-1864eb71-2e66-4f04-b6a7-7679009aa9a9.png)

A savvy user may use cmd+f and search by collateral token symbol, but perhaps this needs better design

**Comment by rowgraus** [comment]
Confirmed - good enough for preview release.  Design firm is aware of challenge for users with >10 vaults (likely rare)

**Comment by otoole-brendan** [comment]
superseded by https://github.com/Agoric/dapp-inter/issues/12
