### ISSUE TITLE
As an existing user managing my vaults, I need to be able to see the current status of each of my vaults quickly 

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5069]

**Comment by samsiegart** [comment]
Related 
![image](https://user-images.githubusercontent.com/8848650/163903171-5c95e721-c0c8-4d93-a9e8-060569048101.png)

**Comment by rowgraus** [comment]
Confirmed

**Comment by otoole-brendan** [comment]
superseded by https://github.com/Agoric/dapp-inter/issues/12
