### ISSUE TITLE
As an existing user managing my vaults, I need to be able to adjust my collateralization and borrow levels either independently or together

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5070]
All adjustments subject to borrow limit
I should see the impact of my proposed transaction on my risk and other factors prior to making the transaction
I may think about this process through the lens of the collateralization ratio (if my intent is to manage my risk) or through the lens of total debt (if my intent is to manage my interest/fees paid)
I would like to see a history of my adjustments to my vault

**Comment by samsiegart** [comment]
TODO:
- I would like to see a history of my adjustments to my vault

**Comment by otoole-brendan** [comment]
superseded by https://github.com/Agoric/dapp-inter/issues/18 and https://github.com/Agoric/dapp-inter/issues/14
