### ISSUE TITLE
As a trader, I need to be able to verify the authenticity of a token

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5074]

**Comment by samsiegart** [comment]
I guess this is a large can of worms. One idea I have: initially, users can be responsible for importing the authentic issuers themselves, i.e.
![image](https://user-images.githubusercontent.com/8848650/163919113-9dd52cce-652d-4515-9d77-6c3aceaca45c.png)

And the board IDs would be discovered from a trusted source like https://docs.chain.link/docs/link-token-contracts/

**Comment by dckc** [comment]
We're tracking a related issue in #4819.

This isn't clear enough to act on, so I'm closing it **wontfix** / **invalid**.

@rowgraus if there is something about this story that is critical to run preview (#5085), please re-open and clarify.

**Comment by Tartuffo** [comment]
Oops, this was wontfix.
