### ISSUE TITLE
add liquidity to an existing pool (with smart wallet)

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5077]
As a new liquidity provider, I need to be able to add liquidity to an existing pool

- [x] I must add liquidity in the existing ratio of assets the pool
- [ ] I would like quick action buttons that will add maximum liquidity based on my asset balances (note: UX issue - asset balances may span multiple purses)
- [ ] I would like “single asset liquidity provision” which lets me pick one asset to provide, and the front end then trades half into the other asset and adds the result as liquidity (nice-to-have; not blocking)
- [ ] use background signer (#4406) when adding the liquidity issuer?

**Comment by samsiegart** [comment]
I believe this is implemented, but not the single asset part

![image](https://user-images.githubusercontent.com/8848650/163920697-03c8c814-f3b6-455c-840e-371842155f78.png)

**Comment by samsiegart** [comment]
@rowgraus Can we break out the single-asset-liquidity feature into a separate ticket?

**Comment by dckc** [comment]
I can't get this to work on devnet. The UI spins after I choose IbcATOM.

I thought maybe it was because there is no liquidity yet, but I can't get adding liquidity to work from the REPL either.
log of my attempts: https://gist.github.com/dckc/4415d09a33d257267f2825ab967e7b06

@Chris-Hibbert @arirubinstein @mhofman can you tell what I'm doing wrong?

**Comment by dckc** [comment]
@arirubinstein pointed me at [amm_swap.js](https://github.com/Agoric/instagoric/blob/main/bases/ag-solo-tasks/tasks/amm_swap.js); I had no luck with that either.

I basically just substituted IbcATOM for BLD:
https://gist.github.com/dckc/4415d09a33d257267f2825ab967e7b06#file-amm_swap-js

```
$ agoric deploy scripts/amm_swap.js 
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /home/connolly/projects/agoric/agoric-sdk/packages/run-protocol/scripts/amm_swap.js
agoric: deploy: Deploy script will run with Node.js ESM
awaiting home promise...
swap
add liquidity
CapTP bundle exception: (RemoteRangeError(error:captp:unknown#20001)#1)
RemoteRangeError(error:captp:unknown#20001)#1: floorDivide: zero divider

  at WebSocket.<anonymous> (packages/agoric-cli/src/deploy.js:120:13)
  at WebSocket.emit (node:events:520:28)
...
```

**Comment by dckc** [comment]
### AUSD pool works

The IbcATOM pool is in some strange state. So with @Chris-Hibbert , I made a new pool using the "Anchor" asset, AUSD (aka USDC) and all seems well:
![Screenshot at 2022-05-03 18-55-15](https://user-images.githubusercontent.com/150986/166604807-bde9b1ce-279c-4083-a02f-143899a64666.png)
![Screenshot at 2022-05-03 18-56-21](https://user-images.githubusercontent.com/150986/166604813-243a49b3-b2c2-432c-9e53-5252b1a3b332.png)
![Screenshot at 2022-05-03 18-58-00](https://user-images.githubusercontent.com/150986/166604817-deebaba3-b2ef-460c-aafb-24e420f48529.png)

**Comment by dckc** [comment]
We're talking about this as a stretch goal for an upcoming release.

**Comment by dckc** [comment]
@rowgraus , our current approach to adding a the liquidity issuer (#5914) involves an interactive signature (using keplr). We aim to take advantage of the background signer (#4406) in due course; I'm interested on your take on how important that is for this launch story. I suppose you'll ask for an estimate, so we better look into it, @samsiegart .

**Comment by dckc** [comment]
@nalinbhatt was able to add liquidity. rough edges:

 - [ ] "why do I have to choose that pool thing?"
 - [ ] "add issuer" issue was unresponsive (clue/work-around: reload wallet, dapp)

**Comment by dckc** [comment]
I think changes to the smart wallet API mean this doesn't quite work any more.

**Comment by turadg** [comment]
I think this is no longer planned. If it is, @otoole-brendan please reopen and revise the description with what's left to do.

**Comment by otoole-brendan** [comment]
Agreed
