### ISSUE TITLE
remove my liquidity from an AMM pool

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5080]
As an existing liquidity provider, I need to be able to
 - [x] remove my liquidity from a pool
   - [x] Quick action buttons or a slider based on percentage of liquidity (i.e., up to 100%)
   - [x] I am shown a projected amount of each token returned after the transaction

**Comment by samsiegart** [comment]
We have this but the buttons only go up to 75%, need to add 100% button

**Comment by samsiegart** [comment]
Added 100% button

**Comment by dckc** [comment]
@samsiegart I can't see any reason why you didn't close this.

**Comment by dckc** [comment]
@samsiegart reports getting this to work with the smart wallet, along with adding (#5077), so let's include it in this round of e2e testing.

**Comment by dckc** [comment]
@nalinbhatt was able to remove liquidity.

rough edges:
 - [ ] only the "add" button showed up, not "remove" (took screenshot)
   - work-around: reload the dApp

**Comment by dckc** [comment]
I think changes to the smart wallet API mean this doesn't quite work any more.
