### ISSUE TITLE
As a BLD staker with no RUNstake position, I need to be able to open a position by placing a lien on my staked BLD and receiving RUN

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5081]
- Subject to RUN per BLD limits
- Subject to asset level debt limit

**Comment by dckc** [comment]
lots of overlap with #3788 ; perhaps I'll reduce scope of #3788 to the contract.

**Comment by dckc** [comment]
For smoke testing, I'll try the steps I used before: https://github.com/Agoric/agoric-sdk/issues/4348#issuecomment-1092364297

**Comment by dckc** [comment]
### REPL-based smoke test passed in **agoricstage-23**

including details such as
  - it's called `runStake`, not `getRUN` in `agoricNames`
  - the notifier structure is updated

full REPL transcript: https://gist.github.com/dckc/265974f3ebbde19ee570542114fbd088

cc @Tartuffo @rowgraus

**Comment by dckc** [comment]
## REPL-based smoke test passed in agoricstage-24

transcript: https://gist.github.com/dckc/f3ae334fd92c601594fba8ad6a1cd668

**Comment by samsiegart** [comment]
https://github.com/Agoric/dapp-treasury/issues/64

**Comment by dckc** [comment]
Looks like this is done, i.e. tested in devnet:

https://gist.github.com/samsiegart/4015af98add766be5eb688bb0e97d0f4

**Comment by dckc** [comment]
I'm able to reproduce the results above.

![image](https://user-images.githubusercontent.com/150986/166552580-ba48c32b-00e7-43af-88eb-ae2765f2c0b0.png)

![image](https://user-images.githubusercontent.com/150986/166552548-802fd6ba-3d80-4d0f-bcad-3a0494745434.png)

![image](https://user-images.githubusercontent.com/150986/166552473-182a11f7-dd17-47a5-afbd-60712d3f54db.png)

**Comment by ivanlei** [comment]
This is an antique plan lost to the sands of time.
