### ISSUE TITLE
As a BLD staker with an existing RUNStake position, I need to be able to manage it; that is: adjust my RUN debt and BLD lien within the bounds of the contract.

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5082]
- Process should feel familiar to vaults

**Comment by samsiegart** [comment]
https://github.com/Agoric/dapp-treasury/issues/64

**Comment by samsiegart** [comment]
This is testable on https://run.agoric.app/ currently. Instructions: https://gist.github.com/samsiegart/4015af98add766be5eb688bb0e97d0f4

**Comment by dckc** [comment]
@samsiegart I don't see any reason why you didn't close this.

**Comment by ivanlei** [comment]
This is an antique plan lost to the sands of time.
