### ISSUE TITLE
Governance to get Oracles completely integrated into RUN Protocol

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5084]
In order to complete integration of Oracle prices into RUN Protocol, e.g. to see those prices used in Vaults, there is some remaining Governance work that needs to happen:

1. Adding the vaultManager on chain
2. Blessing an IBC asset in the bank
3. Actually adding collateral type.

**Comment by dckc** [comment]
@michaelfig is there a relevant PR for this?
I'd appreciate a brief update.

**Comment by dckc** [comment]
> I'd appreciate a brief update.

@michaelfig pointed me to https://github.com/Agoric/dapp-oracle/blob/main/README-gov.md

**Comment by dckc** [comment]
### Revised aggregator invitations sent


```
$ make
ORACLE_ADDRESSES=agoric1gdga5q620ddhfpkyk05c7x03qxj7y3qal3ef0x,agoric1nqqme6acmvh5fmtzn2jr5c650umxa7gf68239h,agoric12lm2hhup5u2ngndeykqlsl97ey6fcv2fa72rjk \
AGORIC_INSTANCE_NAME="ATOM-USD priceAggregator" \
IN_BRAND_DECIMALS=6 \
IN_BRAND_LOOKUP='["agoricNames","oracleBrand","ATOM"]' \
OUT_BRAND_DECIMALS=6 \
OUT_BRAND_LOOKUP='["agoricNames","oracleBrand","USD"]' \
agoric deploy api/scripts/init-core.js
```

 - a6d5a7a Merge pull request `#34` from `Agoric/mfig-keep-solo-state`

https://devnet.explorer.agoric.net/proposals/5
End Voting Time 2 May 2022, 11:28:20pm UTC

`priceAggregatorRef: "board04661"`

```
command[30] E(home.board).getValue("board04661")
history[30] [Object Alleged: Installation]{}
E(history[30]).getBundle().then(b => b.endoZipBase64Sha512)
history[32] "9873f6a9b9181612e4d7ab06c9b03a82a882fa88a6a13e72e7a1d89741c1fd7dcff8bf935572a64c4c579024e4eface9859987f52ab4490b37fe74a9b10f1d3c"
```

**Comment by dckc** [comment]
The oracles seem to be working!

Hm... I assumed this was about Oracle governance, but the description is mostly about vaults. #4349 is clearly about Oracle governance; I just closed that one and I'm closing this one as more or less a dup.

Let's track the remaining vault governance stuff as #3924.
