### ISSUE TITLE
Allow the mint module to mint new BLD tokens upon governance proposal

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5087]
This mint should go to a whitelisted account that is controlled by a contract to manage the economy.
This functionality does not currently exist in Cosmos so would need to be implemented at that level

**Comment by Tartuffo** [comment]
This would be a Cosmos module.

**Comment by Tartuffo** [comment]
Should find the matching Cosmos ticket, perhaps could be done by bounty.

**Comment by aj-agoric** [comment]
Closing as we will not do this for now per Rowland
