### ISSUE TITLE
CLI testing tools for PSM

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5119]

**Comment by dckc** [comment]
## Installation: `npm install @agoric/psm-tool`?

My current draft is a script inside the agoric-sdk, under `packages/inter-protocol/scripts`.
But it's a stand-alone script that doesn't rely on the inter-protocol package nor anything else in the SDK.
We could distribute it as a single file that folks just download and run. But I think supporting `npm install`
is more what the relevant audience expects.

## name: `psm-tool`?

Is `psm-tool` an adequate name?

## features

The features I have prototyped are:
 - get contract info: boardId, fee parameters
   - bug: assumes 1 PSM whose reference / anchor asset was registered as AUSD
   - bug: limited to xnet, ollienet, or a locally running node
 - get wallet info: balances, in-progress offers (same bug about network limitations)
 - format a "wallet action" for a trade (for use with `agd` to sign and submit the transaction)

**Comment by dckc** [comment]
## Use cosmjs to avoid agd dependency?

While having a single-file script with no dependencies is nice, it doesn't actually allow users to trade unless they build / install `agd`. Perhaps it's worth using cosmjs to fill in the gap... though that raises a question of key management.

**Comment by dckc** [comment]
Managing this on an agoric-sdk branch is awkward because I want to use it to test other branches.

a recent version:
https://gist.github.com/dckc/dfc2182a59b11ec4527349afd5ca050f#file-psm-tool-js

cc @gibson042

**Comment by Tartuffo** [comment]
@dckc has built various tools for this.

**Comment by dckc** [comment]
in discussion with @dtribble , we do want a CLI in the product for performance testing etc.; not necessarily for PSM RC0

**Comment by dckc** [comment]
sounds like @mhofman is doing a mult-trade tool

**Comment by mhofman** [comment]
This is a complete hack based on importing the mnemonic of an "ag-solo", and creating a Cosm.js signing wallet. I would not consider this as a general purpose tool.

**Comment by dckc** [comment]
complete hacks are completely fair game here.

**Comment by turadg** [comment]
Work to close this out:
- [ ] understand the update stream from new smart wallet
- [ ] ? coalesce updates from before the tool ran
- [ ] make it part of agoric-cli

**Comment by dckc** [comment]
@turadg feel free to take or leave the `psm-tool` code in #6015

Ari's ask is for a way to tell when a trade is done. The `psm-tool` can be used to poll for the status of offers given an address. A "wait until offer XXX is done" feature would probably be nice (the tool would poll at, say, Nyquist frequency of the block time, so every 3sec.)

The other repo we were talking about is https://github.com/Agoric/psmload
where we find a copy of an older version: https://github.com/Agoric/psmload/blob/main/psm-tool.js
