### ISSUE TITLE
change vaultFactory (and run-protocol?) to require settled `priceAuthority` and `timerService`, not promises

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5121]
## What is the Problem Being Solved?

#5106 is a swingset bug that's triggered by userspace code storing Promises in virtual data (`state` properties of virtual objects, or virtual collections). I'm working on fixing swingset, but I don't know that I can finish it in time for next week's deadline.

Also, you can't store Promises in *durable* objects/collections, so any contract code doing that will probably need to change before it can be made upgradable.

The one case where we do this (vaultFactory) looks like it'll be pretty easy to convert now, which means I can deprioritize fixing the swingset bug, and also it brings us closer to durable-izing / upgrade-able-izing the contract.

## Description of the Design

The main thing is that the `state` of `makeVaultManagerKit` needs to have arguments which are `PriceAuthority` and `TimerService`, not `ERef<PriceAuthority>`/etc. I'm looking to see how far upstream that can/should be pushed. Something before the call to `makeVaultManager()` needs to `await`  both arguments, to turn them into a Presence rather than a Promise.

cc @dtribble @turadg

**Comment by dtribble** [comment]
The notifier issue likely also exists in RUNStake.

**Comment by dtribble** [comment]
In `econ-behaviors`, the initialization of the price authority just needs to await it. BUT it must happen after the AMM is resolved just in case we are using an AMM-based price authority: 
```javascript
  const feeMintAccess = await feeMintAccessP;
  const pa = await priceAuthority;
  const vaultFactoryTerms = makeGovernedTerms(
    pa,
    ...
```
