### ISSUE TITLE
Move dirty tree check to end of every CI job

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#5140]
## What is the Problem Being Solved?

A [recent change](https://github.com/Agoric/agoric-sdk/pull/5123) introduced [non-gitignored build output](https://github.com/Agoric/agoric-sdk/pull/4989#issuecomment-1101488440). While arguably that directory pattern should have been ignored in the first place, CI should have prevented a change creating a dirty tree.

We have a check, but it currently only runs after `yarn install` to make sure the `yarn.lock` file is not clobbered. We should extend this to anything done to the git tree during a test, including new / untracked files, not just modified files

## Description of the Design

Run a dirty tree check at the end of every job as a macro, which also checks for untracked files, and fail the job if the tree is dirty.

We'll likely need to move all integration tests to check out secondary repos not in a sub-folder (or make sure those are ignored)

**Comment by mhofman** [comment]
A post run step added by `restore-node` might do the trick. See https://github.com/actions/runner/issues/1478 and https://github.com/marketplace/actions/run-and-post-run-action

**Comment by rabi-siddique** [comment]
@mhofman I'm not sure if this issue is still ongoing since it was removed from the Engineering Items, but it is still open.

A possible solution I thought of was to create a reusable script that runs a simple `git status` check after each job in our CI pipeline. Something like:
```
git_status=$(git status --porcelain)

if [ -n "$git_status" ]; then
  echo "Git tree is dirty: ${git_status}"
  exit 1
fi

echo "Git tree is clean."
exit 0
```

**Comment by mhofman** [comment]
I would very much prefer to avoid modifying every workflow to add this check. Running as a post run step of "restore-node" if possible sounds a lot more reusable since all workflows use that action.

**Comment by rabi-siddique** [comment]
@mhofman Do you think we should close this issue now?

**Comment by mhofman** [comment]
Done with #9804
