### ISSUE TITLE
Econ committee for Devnet

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5169]
### Description

Arrange for a committee of a few people to be able to vote on proposals such as changing interest rates.

 - [x] send voter invitations to wallets
 - [x] figure out how to pose questions

Need addresses for folks on Devnet

**Comment by dckc** [comment]
Devnet Econ members, from today's meeting:
Rowland: agoric1qed57ae8k5cqr30u5mmd46jdxfr0juyggxv6ad
Bill: agoric1xgw4cknedau6xhrlyn6c8e40d02mejee8gwnef
DCKC: agoric1yumvyl7f5nkalss7w59gs6n3jtqv5gmarudx55

**Comment by dckc** [comment]
Today we agreed this need not be deployed at the same time as the RUN protocol contracts (#5062); it can follow by some days.

**Comment by dckc** [comment]
related work: #4561

**Comment by dckc** [comment]
drafted code to distribute the invitations with @turadg :
https://gist.github.com/dckc/1bd0a160ccf0873cef36f3088cbc24c4

I'm not sure about posing questions yet...

**Comment by dckc** [comment]
### Committee of 1 seated on agoricdev-10

Good news: working with @Chris-Hibbert and @michaelfig , I got my invitation to propose questions and vote on them.

It's possible to replace this committee with a committee of 3; we'll see whether this is cost-effective just now.

```
command[0] E(home.myAddressNameAdmin).getMyAddress()
history[0] "agoric14s56vwftwx8p5kz23fercqptnwex5uw2yj903l"

command[22] history[18].at(-2)[1]
history[22] [Object Alleged: Zoe Invitation purse]{}
command[23] E(history[22]).getCurrentAmount()
history[23] {
  "brand":[Object Alleged: Zoe Invitation brand]{},
  "value":[
   {
    "description":"identifies the voting contract instance",
    "handle":[Object Alleged: InvitationHandle]{},
    "installation":[Object Alleged: Installation]{},
    "instance":[Object Alleged: InstanceHandle]{}
   },
   {
    "description":"Voter0","handle":[Object Alleged: InvitationHandle]{},
    "installation":[Object Alleged: Installation]{},
    "instance":[Object Alleged: InstanceHandle]{}
   }
  ]
}
```

```
$ make submit-proposal
git describe --tags --always
@agoric/sdk@16-205-g268355a7e
git diff --stat
 packages/run-protocol/Makefile                        | 10 ++++++----
 packages/run-protocol/docs/run-preview-vault-asset.md |  6 +-----
```

https://devnet.explorer.agoric.net/proposals/9
End Voting Time 3 May 2022, 1:22:18am UTC

#### Committee of 3 failed: only 1 voter invitation available

Today's proposal was to ask for invitations from the committee contract that was started 27 Apr and send them to deposit facets of 3 members. Unfortunately, that committee was of size 1; then change to default size 3 didn't go into the code until _after_ the committee contract was installed and started on 27 Apr.

```
$ make submit-proposal
git describe --tags --always
@agoric/sdk@16-205-g268355a7e
git diff --stat
 packages/run-protocol/Makefile | 10 ++++++----
 1 file changed, 6 insertions(+), 4 deletions(-)
```

https://devnet.explorer.agoric.net/proposals/7
End Voting Time 3 May 2022, 12:47:43am UTC

#### Committee part of proposal 5 failed due to insufficient permit

```
Error#7: agoricNamesAdmin not permitted, only [ 'zoe', 'agoricNames', 'namesByAddress', 'economicCommitteeCreatorFacet', 'reserveGovernorCreatorFacet', 'ammGovernorCreatorFacet', 'vaultFactoryGovernorCreator', 'board' ]
CORE_EVAL failed: (Error#7)
```

https://devnet.explorer.agoric.net/proposals/5
End Voting Time 2 May 2022, 11:28:20pm UTC

fix: 268355a7e

**Comment by dckc** [comment]
> It's possible to replace this committee with a committee of 3; we'll see whether this is cost-effective just now.

@Tartuffo and others in a meeting just now decided that no, it is not. The existing committee of 1 suffices for this RUN Preview.

**Comment by dckc** [comment]
Let's set this up again for [**agoricdev-11**](https://devnet.explorer.agoric.net/blocks/2).

@rowgraus as we discussed, please [set up your client](https://github.com/Agoric/agoric-sdk/wiki/Setting-up-an-Agoric-Dapp-Client-with-docker-compose) again and send me your address (noting it here is ideal). @btulloh if you'd like to play along, please do likewise.

**Comment by dckc** [comment]
new addresses:

 - @rowgraus `agoric14nt7n99jstnk7zzgmw4hzhc05yqjplerrv9uqd`
 - @dckc `agoric1j5sm4kr2mdae6sfey6qjm9vaamddmp0yuxs6kz`
 - @michaelfig: `agoric1y5gpzqd876gqmkyl2c5q66vp6e30se4vwn644v`

_p.s. had to add a 3rd to match `committeeSize` in the code._

_p.p.s. MF's wallet for agoricdev-11 actually has a different address. So he's a non-voting member :)_

**Comment by dckc** [comment]
The committee for **agoricdev-11** is seated.

https://devnet.explorer.agoric.net/proposals/4
End Voting Time 11 May 2022, 3:31:26am UTC

```
$ make submit-proposal
git describe --tags --always
agoricdev-12-2-g0c16a68b1
git diff --stat
 packages/run-protocol/Makefile                        |  5 ++---
 packages/run-protocol/docs/run-preview-vault-asset.md | 13 ++-----------
 packages/run-protocol/scripts/add-collateral-core.js  |  5 ++++-
 3 files changed, 8 insertions(+), 15 deletions(-)
cat /home/connolly/projects/agoric/wallet-dev11/ag-cosmos-helper-address
agoric1j5sm4kr2mdae6sfey6qjm9vaamddmp0yuxs6kz
agd --node=[https://devnet.rpc.agoric.net:443](https://devnet.rpc.agoric.net/) --chain-id=agoricdev-11 \
  --home=/home/connolly/projects/agoric/wallet-dev11/ag-cosmos-helper-statedir --keyring-backend=test \
  tx gov submit-proposal swingset-core-eval \
  gov-add-collateral-permit.json gov-add-collateral.js gov-invite-committee-permit.json gov-invite-committee.js \
  --title="RUN Protocol Preview: Interchain Asset Vaults on agoricdev-11" --description="$(cat ./docs/run-preview-vault-asset.md)" \
  --deposit=1000000ubld \
  --gas=auto --gas-adjustment=1.2 \
  --yes --from=ag-solo -b block
gas estimate: 1360941
...
txhash: 121AFCDAFFB6A8766BEB98C717427A443CEE50727FF115E9972A95939778541E
```

![image](https://user-images.githubusercontent.com/150986/167770827-08922d7b-7800-442f-a5df-30c12ab9dac0.png)

**Comment by dckc** [comment]
### Onboarding another gov cttee member

https://gist.github.com/dckc/9153053d3fdd22f09abfead8b09896bc#file-vote-prep-repl-1-js
https://gist.github.com/dckc/9153053d3fdd22f09abfead8b09896bc#file-vote-ui-prep-js
https://github.com/agoric-labs/gov-demo1/pull/5


![image](https://user-images.githubusercontent.com/150986/168300320-0ed15918-892a-4c29-b8af-7103b7a8c020.png)
