### ISSUE TITLE
a result promise being included in the args of the same message might cause problems

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5189]
## What is the Problem Being Solved?

While pondering #5106, an unusual sequence occurred to me that is worth a unit test.

```js
const payload = [];
const p = E(target).foo(payload);
payload.push(p);
```

The `HandledPromise` handler (provided by liveslots) doesn't run on the same turn as the call to `E` or the Proxy that it returns. So the caller has a whole turn to mutate the arguments they provided before anything gets serialized. That's not a big deal by itself, but it does mean that they might mention the result promise they got back from E.

Liveslots' `queueMessage` assumes that the `returnedP` it gets has not been observed before. If it was also included in `args`, it will be serialized earlier than expected, and assigned a `vpid` just as if it was an exported promise. But that will be a different vpid than the one it allocates for the result, so when it populates `valToSlot`/`slotToVal` at the end of the function, it will be overwriting the other assignment.

One symptom might be that sending the result promise to someone else might not give them a promise that resolves at the right time. It might also interfere with pipelining. Also some promises might not round-trip properly. All these cases are worth exercising with a unit test.

## Description of the Design

I think the fix is to allocate the vpid and populate `valToSlot`/etc earlier, before we serialize the arguments. That way the serialization should re-use the vpid we allocated, instead of allocating a new one.

I don't know how this will/should interact with the `const p = makePipelinablePromise(resultVPID)`, though. I *think* that this line should be unchanged: we create a new (local) Promise that's distinct from the result promise / `returnedP` that userspace sees, as before. We pass `resultVPID` into `makePipelinablePromise` so it can prepare to handle `dispatch.notify` later (`notify` causes `p` to get resolved, we return `p` from the handler, so `returnedP` will get resolved when HandledPromise sees `p` resolve).

## Security Considerations

I *think* this could only cause grief to the code that decided to exercise it. It might enable a memory leak of some sort, but that grief is also self-directed. So I'm ok with deferring it to MN-2 or MN-3.

## Test Plan

Unit tests that look at the syscalls being made.

**Comment by mhofman** [comment]
I came to almost the same realization [yesterday when discussing the promise watchers PR](https://github.com/Agoric/agoric-sdk/pull/5130#discussion_r855376422), except my example was flawed as it was using an argument in a subsequent `E` call, which would similarly be delayed since we're delaying marshaling arguments as well.

I am however somewhat surprised at that delayed treatment of arguments here. While the delayed send is not really directly observable by the contract, the late marshaling of arguments definitely is as you've seen demonstrated. Any reason not to marshal arguments synchronously at the time of the call (and keep reporting a marshal error in the result promise of course)?

That would definitely require that the result promise be assigned a slot synchronously as well, but it could probably still be done after the arguments are marshalled.

I am just not comfortable at the idea of letting the contract mutate the arguments after the call has been made.

**Comment by warner** [comment]
@erights or @michaelfig can probably answer that better, but I know the main concern is to prohibit reentrancy surprises, and the threat is probably a rogue handler attached to the HandledPromise: HP invokes those handlers in a later turn to protect the caller of `E(x).foo(args)` against the provider of `x` (= the provider of its attached handler). I don't think you could allow the "good" provider (liveslots) to get access to `args` for synchronous serialization without also allowing the "bad" provider of an unknown `x` to gain control in the middle of the `E(x)...` caller's execution.

**Comment by mhofman** [comment]
> I don't think you could allow the "good" provider (liveslots) to get access to `args` for synchronous serialization without also allowing the "bad" provider of an unknown `x` to gain control in the middle of the `E(x)...` caller's execution.

I don't see why not. Maybe not with the existing hook, I'm not familiar enough with HandledPromise, but I don't see why the proxy can't serialize the args synchronously and remember the outcome / exception until the target is resolved in the next turn, at which point it can reject the result or let live slots know about the send.

**Comment by mhofman** [comment]
I guess the question is whether we want to protect against reentrancy from arguments.

**Comment by warner** [comment]
I tried to build a unit test to trigger this, and it looks like `E` hardens the arguments synchronously, before control returns to the caller. I need to verify that (probably in `eventual-send`), but if true, that would remove this problem entirely.

**Comment by mhofman** [comment]
Regardless, with the `requireNew` check in the kernel added in #5124 would blow up the vat if it attempted to use the result promise as argument.

**Comment by warner** [comment]
I found the spot in eventual-send (`E.js` and `handled-promise.js`): the user-provided `args` gets hardened when the function returned by the Proxy (`E(target).method`) is invoked:

* https://github.com/endojs/endo/blob/%40endo/eventual-send%400.15.3/packages/eventual-send/src/E.js#L33
* https://github.com/endojs/endo/blob/%40endo/eventual-send%400.15.3/packages/eventual-send/src/handled-promise.js#L416
* https://github.com/endojs/endo/blob/%40endo/eventual-send%400.15.3/packages/eventual-send/src/handled-promise.js#L483

So I'm reasonably convinced that userspace could not trigger this. And @mhofman 's newly-added "all non-pipelining result promises must be new" means that we'll kill a non-pipelining vat that tries (i.e. if a raw vat did it).

That leaves remote (comms) systems, which we have less control over. Inbound comms messages might share a vpid between `result` and `args`. Our comms vat is marked as `isPipeline`, so the kernel won't kill it should this happen, but the resulting message will be pushed onto the run-queue, and will be delivered to some other local vat. We need to make sure the kernel and the local vat can handle this correctly.

I think there are eight total places that need to be examined / cause a problem:

* liveslots, in `queuedMessage`, because it serializes `args` before allocating a vpid and mapping it to `returnedP`
* the kernel-side translator (`vatTranslator.js` in `translateSend()`), mapping the vrefs to krefs for the args before doing so for the result
* the kernel-side translator (`translateMessage()`) mapping krefs to vrefs, same problem
* liveslots in `dispatch.deliver`: it unserializes `args` before preparing the `.then` on the delivery promise, so liveslots will think it has an imported (kernel-decided) promise even though it's really vat-decided
* kernel-to-comms (`sendFromKernel`)
* remote-to-comms (`sendFromRemote`): this already translates the result before the args.. I think I did it that way because that's the order they appear in the serialized form
* comms-to-kernel (`sendToKernel`)
* comms-to-remote (`sendToRemote`): already translates the result before the args

The `eventual-send` hardening means that we don't necessarily need to protect against the first one (and we don't have a decent way to test it either: `E` prevents us from triggering the bug in liveslots). But the fact that remote comms peers might do this means that we still need to change the translators to tolerate it, and we need liveslots to tolerate it for inbound `dispatch.deliver` (which can come from comms messages).

The unit tests will need a raw vat to the messages that liveslots cannot create. For the comms tests, we'll use `test-comms.js` to exercise the comms translators without involving liveslots. For completeness, I think we should change liveslots `queueMessage` to process the result before the args, even though E's automatic `harden` means that case cannot be triggered: this part will need manual testing.

**Comment by mhofman** [comment]
> * liveslots in `dispatch.deliver`: it unserializes `args` before preparing the `.then` on the delivery promise, so liveslots will think it has an imported (kernel-decided) promise even though it's really vat-decided

This can legitimately happen already, right? Or is there a difference because it's in the same delivery?
```
// vatB:
p1 = alice~.one()
p2 = p1~.three()
p3 = alice~.two(p2)

// vatA
const p1Kit = makePromiseKit();
alice = {
  one: () => p1Kit.promise,
  two: (p2) => {
    p2.then((result) => console.log(`${result} should be 42`));
    p1Kit.resolve(alice);
  },
  three: () => {
    console.log('called with previously imported promise as the result promise');
    return 42;
  },
};
```

**Comment by mhofman** [comment]
I also agree we should be consistent in the processing order of args vs result, but I'm not convinced that result before args is automatically the way to go. Is there a specific reason to go for one before the other? From a JS code execution point of view, arguments to a function are always evaluated first.

**Comment by warner** [comment]
> This can legitimately happen already, right? Or is there a difference because it's in the same delivery?

If I understand your example correctly, then that's a case where the vat is told (in arguments) about a promise that it is deciding (because of a `result` in an earlier message). The `result` arrives in delivery-1, and the reference to that `vpid` arrives in delivery-2. I'm pretty sure we handle that already, although I'm struggling to find a test for it.. might be in `message-patterns.js`. 

The new case is when both the `result` and the reference arrive in the same delivery. The issue is that we special-case the "deserialization" of `result`: it's not a plain `vpid` arriving in arguments.. we have to prepare it differently. So if we allow the general-purpose `m.unserialize` see the `vpid` first, then `convertSlotToVal` doesn't realize the promise is arriving as a `result` and treats it as imported (kernel-decided).

**Comment by mhofman** [comment]
> If I understand your example correctly, then that's a case where the vat is told (in arguments) about a promise that it is deciding (because of a `result` in an earlier message). The `result` arrives in delivery-1, and the reference to that `vpid` arrives in delivery-2.

Nope, it's the opposite. The message with the vpid in arguments is received first by the vat (in `two`), then the message with it as result (in `three`).

**Comment by warner** [comment]
([Test `a86 local` ](https://github.com/Agoric/agoric-sdk/blob/50c130d8600aa773988a0202940518c0064db27f/packages/SwingSet/test/message-patterns.js#L840) happens to exercise the pattern I was talking about, where `billP` is a result promise that then appears in the arguments of a (later) `E(b.bob).b87_three(billP)` message, and the receiving vat uses `await` to make sure liveslots actually causes that promise to be resolved.)

> Nope, it's the opposite. 

Ah, so first it appears as an argument (decider==kernel), then it appears as `result` (transferring control to the vat). Yeah, I think you're right, userspace could provoke that already by taking advantage of a non-pipelined stalled message. Sounds like we should add that to message-patterns.js.

And, yes, the code in liveslots needs to handle the general-purpose case of an already-known promise (which could have arrived long ago) becoming used as `result`, in which case it shouldn't matter whether `dispatch.deliver` processes `args` or `result` first.

I'll add tests of your scenario in addition to the other ones I have in mind.
