### ISSUE TITLE
Unable to restart validator node after ~4000 blocks

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#5194]
## Describe the bug
During the spinup of the stage testnet, where we deployed a few contracts and proposals, the validator node that was working, now after reboot is unable to boot.  It appears that there are no swingset logs on invocation, and the process hangs 100% on node, however the 100% utilization hops around node threads.

## To Reproduce
0. Download https://drive.google.com/file/d/172acPvjlnGqQiqj5V16Se7aWiYTM-xS2/view?usp=sharing
1. unzip into agoricstage-21
2. `docker run -it --entrypoint /bin/bash -v $PWD/agoricstage-21:/state agoric/agoric-sdk:17`
3. `agd start --home /state`
4. swingset wont launch, as well as the node process will sit on 100%

## Expected behavior

Swingset should boot and the node process should start 

## Platform Environment
 - what OS are you using? what version of Node.js?
 this originally happened on gcp/x86 however it reproduces on arm64/m1
 - is there anything special/unusual about your platform?
 nope
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
agoric/agoric-sdk:17 docker
[c74a2355e6f45bf4606cea7a3398809b8793791b](https://github.com/Agoric/agoric-sdk/commit/c74a2355e6f45bf4606cea7a3398809b8793791b)

**Comment by mhofman** [comment]
@arirubinstein I'm curious, is there a reason that state has `127.0.0.1:26656` (is that itself?) as a persistent peer?

**Comment by JimLarson** [comment]
@arirubinstein can you explain more about the setup tested here, and how it was generated?

**Comment by arirubinstein** [comment]
https://gist.github.com/arirubinstein/848229f8b16c97e2005b05943bdf72d2

**Comment by arirubinstein** [comment]
> @arirubinstein I'm curious, is there a reason that state has `127.0.0.1:26656` (is that itself?) as a persistent peer?

this is from the genesis file - peers are configured in config however

**Comment by JimLarson** [comment]
Can also reproduce without docker: `agd start --home $PWD/agoricstage-21`

Can also reproduce using `ag-cosmos-helper`, which is an all-Go process and will work with standard tools: `ag-cosmos-helper start --home $PWD/agoricstage-21`.

Extracting data from the built-in pprof port: `curl localhost:6060/debug/pprof/profile > cpu.prof`.

Examining the data: `go tool pprof cpu.prof`.

Graph of CPU profile: 
![profile001](https://user-images.githubusercontent.com/32469398/167459882-310e3d65-062f-4bba-90b8-6e0aae0ba94a.svg)

**Comment by JimLarson** [comment]
I can see a code path where it spins forever in `tendermint/blockchain/v0/pool.go` between `makeRequestersRoutine()` and `makeNextRequester()`. Working on how it gets into this condition given the initial state. Will also look for fixed tendermint bugs.

**Comment by JimLarson** [comment]
It looks like we'll have the same behavior with the current Tendermint master: https://github.com/tendermint/tendermint/blob/master/internal/blocksync/pool.go

**Comment by JimLarson** [comment]
With @michaelfig we were able to confirm that this seems to be the questionable but normal behavior of tendermint when restarting a node with nonzero block history when it can't contact any peers. Normally not an issue since such an isolated node would not be useful, but could be an issue if, e.g. it had 100% of the voting power but maintained some rpc nodes. Will file one or more Tendermint issues, but will close this one as "working as intended".
