### ISSUE TITLE
add controller.getRunQueueSize()

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5238]
## What is the Problem Being Solved?

To support #5176, in which cosmos will stop accepting messages into the mempool and into blocks once the kernel announces it is too full, we need to give the kernel a voice. @michaelfig says it'd be sufficient to let cosmic-swingset poll the kernel for it's queue depth.

## Description of the Design

Add `controller.getRunQueueSize()` (feel free to bikeshed the name). Returns a set of Nat (non-negative integer), one for active queues, one for inactive queues (such as promise queues). Only safe/consistent to call when the kernel is idle (i.e. outside of a `controller.run()`).

Caller is responsible for deciding how to interpret the result. 0 means empty, but the "full" threshold is up to the caller (and should be configurable). Once priority queues are introduced (#4318), this would need to be updated to expose different numbers for low and high priority queues, and the caller may pay attention to two thresholds.

## Security Considerations

None I can think of.

## Consensus Considerations

The kernel-reported value will grow in response to kernel device IO calls (e.g. adding messages to the Mailbox device will push work onto the kernel queue, increasing the number). Calling `controller.run()`, with some particular `runPolicy`, on a non-empty queue could either increase or decrease the number (but in the long run should decrease, assuming no runaway computation).

So this should be safe to use for consensus operations as long as all replicas use the same sequence of device writes and `controller.run()` calls, and use the same `runPolicy`, and refrain from calling it concurrently with a `controller.run()` (which might sample the queue at random points during execution, which would give inconsistent results).

~~However we don't currently plan to use this for consensus operations: accepting messages into the mempool is done separately by each validator and is outside of consensus.~~

We plan to use this mechanism for both consensus (validating a proposed block) and non consensus (accepting into the mempool)

## Test Plan

Unit tests, probably in `test-kernel.js`.

**Comment by mhofman** [comment]
My thinking was actually to have something like `controller.currentlyAcceptingLowPriority()` based on https://github.com/Agoric/agoric-sdk/issues/5027. I don't think cosmic-swing benefits from knowing the depth of the queue size.

**Comment by warner** [comment]
> My thinking was actually to have something like `controller.currentlyAcceptingLowPriority()` based on #5027. I don't think cosmic-swing benefits from knowing the depth of the queue size.

That feels cleaner to me (along with a parallel predicate for other priorities), but then we also need to expose controls for the now- kernel-enforced thresholds, and we need to add code somewhere higher up to set the thresholds, within consensus.

We could do `controller.setLowPriorityQueueSizeThreshold(n)`, and implement some cosmic-swingset -side governance mechanism to change it. Or we could implement `E(vatAdminService).setLowPriorityQueueSizeThreshold(n)` (or implement some other control-the-kernel-from-within vat) and let the Big JS Hammer control it. We'd need to make sure that we couldn't get stuck with a knob that needs to be twiddled but the only code that can twiddle it is stuck, waiting for the twiddling.

@michaelfig suggested that cosmic-swingset is mostly ready to go with a a depth-reading predicate, and since this is only affecting the mempool, it doesn't need to be within consensus, so that might be a shorter path. Also, we could probably switch from a depth-reading predicate to a kernel-decided threshold after MN-1 without too much fuss.

**Comment by mhofman** [comment]
My concern with depth reading is that the notion of what the depth is will change with multiple queues. That said, the logical tie to the run policy does exist, as these queues will need to be conceptually exposed to the "policy" that decides (within priority and ordering invariants) which queue to process next.

So my concern is not automatically to shield the host which makes those decisions from these queue concepts, but how to properly abstract them consistently.

**Comment by warner** [comment]
Yeah, I think it'd suffice for a while to just sum all the queues together and report back a single number. We can add something more sophisticated later, especially since this isn't being used for consensus.

**Comment by warner** [comment]
@mhofman and I walked through this today, plan is to add `controller.getQueueDepth()` (name TBD) to return an integer, and let the cosmic-swingset side choose how to react. The result is consistent iff you call it while the kernel is idle: it may change unpredictably between `p = controller.run()` and that `p` promise firing. Even when idle, the value may change in response to calls you make to device input functions (like adding messages to the mailbox's inbox).
