### ISSUE TITLE
Create fake Oracle for economic testing

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5242]
## Problem to Solve

For economic stress test and other test deployments, we must enable directly specify the price, and have it propagated through.

## Design

Clone `ManualPriceAuthority` and move the `setPrice` operation onto the creator facet rather than the priceAuthority. Note that ManualPriceAuthority` is made to simplify unit tests. Most code is reused from elsewhere, so I don't think it's worth trying to make a single notifier that covers both use cases.

**Comment by Tartuffo** [comment]
@dtribble Please add detail.

**Comment by dckc** [comment]
To get the oracleAdmin:

 - [manual\-price\-feed\.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/scripts/manual-price-feed.js)

To get a quote from it:

 - https://github.com/Agoric/agoric-sdk/issues/7782
