### ISSUE TITLE
price movement notifications for arbitrary pairs through an anchor currency

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5267]
## What is the Problem Being Solved?

Price Authority notifies of prices between a pair, but requires a direct data source. Use cases like a collateralized loan pool (e.g. Compound protocol) of N collateral brands require N^2 comparisons. We don't have price authorities for all of them. Presently a contract has to poll in order to calculate the price events for such a use case.

## Description of the Design

TBD. 

Brainstorm
* price authority supports inferred pricing
* a new kind of price authority does
* contracts subscribe to price movement notifications against the central currency; then act if that results in a change in the pair

## Security Considerations
TBD

## Test Plan

TBD

**Comment by Tartuffo** [comment]
We need to provide them support on how to do this, we won't implement this ourselves.

**Comment by turadg** [comment]
The gist is:
* calculate thresholds for quotes  on the existing priceAuthority sources
* have logic that reacts and updates quote as needed

This is for userland but a library to be used in multiple contracts would be welcomed.
