### ISSUE TITLE
Reserve's addIssuer should be public

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#5271]
## What is the Problem Being Solved?

Before assets can be "contributed" to the Reserve, the Issuer must be known. Currently `addIssuer` is on the creator facet.

## Description of the Design

Move addIssuer to the public facet to make adding new collateral types permissionless.

## Security Considerations

We want to accept arbitrary assets, but someone could use this to add an unlimited number of issuers to our zcf.

## Test Plan

no big deal.

**Comment by turadg** [comment]
Decided instead to repeat the `addIssuer` calls from AMM. See https://github.com/Agoric/agoric-sdk/pull/5429
