### ISSUE TITLE
LMDB has a tiny key size. We need new code to stay below this tiny limit.

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#5278]
Our heap stores are built on JS maps and sets, whose keys are limited to scalars. But the size of those scalars are not limited (beyond normal large heap size limits, as far as we know). We have been treating them that way, sometimes using as keys data from untrusted users, like petname name strings, which can be arbitrarily long.

Our virtual and durable stores are currently built on LMDB, and their keys are mapped (via encode and decode steps) to LMDB string keys. However, LMDB keys are limited to be tiny. (I'll let @FUDCo clarify how tiny --- there seem to be two hypotheses.) Certainly, for our current system, it is easy for user-provided data, used as keys, to exceed those limits. If they do, we currently have no graceful way to recover.

We should encode these limits in the methods of stores by which keys enter stores, like the `init` method of mapStores. Their semantics is already to reject any key that violates the `keySchema`. For scalar stores (currently our only kind), these methods also reject non-scalar keys. They should also reject keys that exceed some implementation-defined-but-deterministically-replayable limit. We then need to rereview our uses of stores to ensure that they cope with these failures gracefully. Conceivably, we need to add a check as to whether a JS value would be acceptable as a key in a given store, so that applications can impose these limits early rather than only in reaction to attempting to mutate a store.

Longer term, we need to lift these limits. Long term, we already expect to examine alternative storage tech like LevelDB as well as some sql databases. We should notice what limits they impose. Alternatively, if we remain on storage tech with ridiculously tiny keys, we should refactor our store implementation to segment our to-be-unlimited keys, such as segmenting it into chunks, and then building a trie structure where each step of the trie is indexed by a chunk.

**Comment by erights** [comment]
Attn @warner @FUDCo @jessysaurusrex @Chris-Hibbert @arirubinstein @mhofman @gibson042 @Tartuffo

**Comment by erights** [comment]
Related: https://github.com/Agoric/agoric-sdk/issues/5277

**Comment by warner** [comment]
I think this matches the "alternate design" I sketched out in #5277 , and that a hard-coded (and regrettably small) limit is the easiest and safest short-term solution. @erights if it's ok with you, let's close this ticket in favor of #5277 .

When we get a more capable DB, we can decide how Swingset should manage the remaining limitations. It's tempting to have some sort of negotiation or configuration to happen between the host application (who creates and supplies the DB) and swingset-as-consumer. But it might be much easier to declare that swingset requires a `SwingStore.kvStore` which handles keys of at least 1MB, and then swingset can impose a fixed-size limit on Stores, and not try to take advantage of every single byte the DB can give us. (And I suspect the DB API will be sufficiently different that we'd implement that limit very differently than what we might design today).

**Comment by FUDCo** [comment]
The vatstore, implemented on top of the kvstore, is where we could potentially have long keys that overflow LMDB's limit.  However, the kernel's use of the kvstore involves key sizes that are much more modest.  If we rehome on top of some other kind of database, it's not obvious to me that we would keep the vatstore API as it is, and it's definitely not obvious that the constraints that apply for supporting the kernel need have any relationship to the constraints that apply for the data storage that is exposed to liveslots.

**Comment by erights** [comment]
As suggested, closing in favor of #5277
