### ISSUE TITLE
Make VaultFactory reachably durable

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5285]
## What is the Problem Being Solved?

https://github.com/Agoric/agoric-sdk/pull/5736 made Vault Factory sort of durable, but it has some hacks around https://github.com/Agoric/agoric-sdk/issues/4567 and it's not yet _reachably durable_ .

For the next release we need it to be not just reachably durable, but upgradable: https://github.com/agoric/agoric-sdk/issues/6791

## Description of the Design

Store everything precious.

## Security Considerations

State on disk.

## Test Plan

Manual review that all precious state is stored.

**Comment by dtribble** [comment]
A simpler solution in this case:  upon upgrade I would expect to restart the liquidator activity, which is the loop waiting for the quote promise to be resolved. Basically,  `liquidationInProgress` and `outstandingQuote` need to be made ephemeral.

**Comment by turadg** [comment]
I think this has been done a while, actually.
