### ISSUE TITLE
Reserve contract covers vault shortfalls

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5299]
## What is the Problem Being Solved?
The Inter Protocol relies on successful liquidation to ensure the stable token remains over collateralized.  In cases where individual liquidations do not cover the outstanding debt for any reason, the protocol must track the outstanding balance so that it can be made whole through later operations.  This ticket allows the Reserve contract to both track the ongoing shortfall and to burn IST to reduce it.

## Description of the Design
Shortfalls that occur during liquidation are passed to the reserve contract which manages a shortfall balance.  This logic must survive as liquidation contract is changed.

The reserve contract must burn IST to reduce shortfall.  Suggest adding method that can be called by governance which takes IST from the Reserve's IST purse to handle this.

Reserve's IST purse is funded through execution fees and excess reward flows as described in #4399, but it must also be able to accept additional ad-hoc deposits as needed.  I.e., governance could decide to sell other assets to and fund the Reserve IST purse for the purpose of burning to reduce shortfall.

## Security Considerations
The liquidation shortfall which occurs during execution of the liquidation contract within the vault manager must be passed correctly to the reserve to ensure shortfalls cannot fail to be tracked

**Comment by rowgraus** [comment]
Econ committee abilities which allow it to let the reserve manage the shortfall

Governance: Burn IST from purse and reduce debt
Governance: Redeem liquidity tokens 
Governance: Sell on AMM and deposit into IST pool
Governance: Take collateral in collateral purse, mint IST, deposit

**Comment by dckc** [comment]
> Governance: Take collateral in collateral purse, mint IST, deposit

sounds like #5298
