### ISSUE TITLE
Rename RUN to Inter (IST) in the wallet UI

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5327]

**Comment by turadg** [comment]
This is done in the Wallet of SDK. What's left is to do it in https://github.com/Agoric/dapp-treasury

@samsiegart do you want this ticket to be for that work or have a new ticket in the treasury repo? I lean towards the latter so we can close out the SDK's epic

**Comment by samsiegart** [comment]
Sure we can track this separately from the AMM and Vaults UI. I can create the issues.

**Comment by turadg** [comment]
@samsiegart can you point me to them?

**Comment by samsiegart** [comment]
@turadg  Yep, just made https://github.com/Agoric/dapp-amm/issues/28 and https://github.com/Agoric/dapp-treasury/issues/136

**Comment by turadg** [comment]
There's no RUN left in this repo so I'll close this. The remaining work is in the two dapps ^.
