### ISSUE TITLE
Rename RUN to Inter (IST) in Bootstrap

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5328]

**Comment by Tartuffo** [comment]
@dckc I was thinking you'd be the right person to do this, please LMK if you disagree.

**Comment by dckc** [comment]
Presuming this is about user-visible occurrences "RUN" in the wallet and such, yes, I can do this.

**Comment by dckc** [comment]
### A long way from DRY

a search for the string constant `'RUN'` turns up 77 results in 50 files.
`'run`' occurs 35 times in 19 files
total: 112 occurrences in 68 files.

`'urun'` shows up 12 times in 8 files.

**Comment by turadg** [comment]
Done in https://github.com/Agoric/agoric-sdk/pull/5332
