### ISSUE TITLE
Unable to deploy card store dapp to the testnet

### ISSUE THREAD

**Issue by ktomascz** [Agoric/Agoric#5341]
## Describe the bug
When trying to deploy the card store dapp (installed from dapp-card-store template) to the testnet, the deploy freezes and chain (node) responds with error.

## To Reproduce
1. agoric init --dapp-template dapp-card-store card-store
2. cd card-store
3. agoric install
4. agoric start --reset testnet 8000 https://devnet.agoric.net/network-config
5. !faucet client agoric1y6ss3wren9jnte5lz0sl2qamlrnnama43nen5r (in discord channel)
6. agoric deploy contract/deploy.js api/deploy.js

In running chain's shell: 
```
2022-05-11T09:00:19.490Z chain-cosmos-sdk: Error: error unmarshalling: invalid character '<' looking for beginning of value

2022-05-11T09:00:19.490Z chain-cosmos-sdk: Error sending (SyntaxError#6)
SyntaxError#6: Unexpected end of JSON input

  at JSON.parse (<anonymous>)
  at sendFromMessagePool (packages/solo/src/chain-cosmos-sdk.js:690:28)
  at runMicrotasks (<anonymous>)
  at async recurseEachSend (packages/solo/src/chain-cosmos-sdk.js:786:5)
```

In deployment's shell:
```
➜  card-store git:(master) ✗ agoric deploy contract/deploy.js api/deploy.js
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /home/vscode/agoric-sdk/card-store/contract/deploy.js
agoric: deploy: Deploy script will run with Node.js ESM
```
App deployment is stuck, while chain's shell keep throwing above mentioned error repeteadly.
Seems like node is not responding correctly for some reason. Not sure if I am doing something wrong.

## Expected behavior
Dapp (both contract and api deploy scripts) deploys with SUCCESS. 

## Platform Environment
Fedora 35
NodeJS v16.15.0
Agoric 0.15.1
Python 3.10.4
GO go1.18beta1 linux/amd64

## Additional context
I was able to deploy this dapp successfully last week (first week of May). 
Deploying within local-chain worked ok as well. 

Based on discord discussion this may relate to: [https://github.com/Agoric/agoric-sdk/pull/5321](https://github.com/Agoric/agoric-sdk/pull/5321)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by Tartuffo** [comment]
Thank you for working with the Agoric system, and reporting this issue!

You probably need more RUN tokens.  Please get some from the faucet.

**Comment by ktomascz** [comment]
Does that mean I need to run the faucet request twice (several times)? 
Can I even do so? 

Please, refer to the reproduce steps.
Thank you.

**Comment by Tartuffo** [comment]
Please ask for help in https://discord.com/channels/585576150827532298/755164472397660313

**Comment by Tartuffo** [comment]
Appears to be user error.
