### ISSUE TITLE
trusting brand getDisplayInfo() too much in oracle interface?

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5348]
## Describe the bug
In several places we're breaking this declared constraint on how to use `getDisplayInfo()`,

At this point they're all for cases of interfacing with price authorities (oracles):
https://github.com/Agoric/agoric-sdk/pull/5340/files#diff-d56ddc40a4b59310856f424addfbf1724d19ea75f439fd1460ef9bf71754348aR93-R107

https://github.com/Agoric/agoric-sdk/blob/b44f27bd9039925617c67ec378641d3fdb368de0/packages/run-protocol/src/vaultFactory/vaultManager.js#L565-L576

## Expected behavior
No exceptions to the constraint.

## Additional context

In meeting with @erights @dckc @Chris-Hibbert determined this is not to be solved for MN-1 but documented as the sole exceptional use.

**Comment by michaelfig** [comment]
Algebraically, `decimalPlaces` can be ignored only when adding or subtracting two amounts (fixed point numbers) with the same number of decimalPlaces.  They cannot be ignored when the brands differ or when multiplying or dividing amounts (such as ratios).

The oracles rely on price ratios (two different brands, numerator and denominator).  The decimalPlaces must not be ignored.

I don't understand why this receives so much pushback (not calling out anybody in particular, but I've had to make this argument repeatedly without any seeming conclusion).

**Comment by erights** [comment]
I'm the source of the pushback. I do not yet understand your objection but am eager to. We should talk.

**Comment by erights** [comment]
@michaelfig , thanks for clearing up my confusion.

The answer is that the displayInfo uses in question, considered abstractly enough, do affect only the user interface. They do not affect the value of any amounts. They *do* affect the bigints used in ratios, but do *not* affect the abstract rational number that the ratio denotes. For example, the ratio 3/5 denotes the same abstract rational number as the ratio 3000/5000. More interesting, this difference in ratio representations do not affect the bigints produced by the operations on ratios, like `floorMultiplyBy`, even though it internally uses a `floorDivide` which does lose precision. Scaling the ratio up does not affect how much precision is lost.

@michaelfig , did I get this right?

**Comment by turadg** [comment]
Sounds like because oracles _are_ a UI case the "Expected behavior"  is already being fulfilled,
> No exceptions to the constraint.

So I'll close this bug ticket.
