### ISSUE TITLE
Cosmic-swingset actions for message admission checks

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#5350]
## What is the Problem Being Solved?

To enable cosmos to decide whether to admit a transaction into the mempool and into blocks (#5176) as part of the simple backpressure mechanism (#5334), cosmic-swingset needs to expose the currently stored admission policy and related kernel state. It also needs to initialize the admission policy from genesis params, and handle updates.

## Description of the Design

Update actions handled by cosmic-swingset's block manager:
- add a new action to store a new admission policy. It should be part of actions processed between the block begin and end actions, but doesn't need to be delivered into swingset itself. Instead the block manager / cosmic-swingset can directly store it under a new explicit `host.` section of the swingstore (#5349).
- When committing the block, cosmic-swingset would read the current admission policy and the Swingset queue state (#5238) and use them as return value. Both should be fully deterministic and part of consensus state.

The cosmos side can cache that result and consult it any time as part of its checks.
TBD: how should cosmos receive the startup values before committing a block. Maybe as the result of `AG_COSMOS_INIT` ? How does that mesh with hangover restarts where the cosmos layer forgot it delivered messages to cosmic-swingset which changed this state.

The initial admission policy would be set from `genesis.json`, and processed by cosmic-swingset.

## Security Considerations

Since the "host" section of the swingstore is not part of the activity hash, there is a risk this value could deviate between validators and not be caught by the more stringent consistency checks Swingset has.

## Test Plan
TBD

**Comment by warner** [comment]
Today's discussion notes:
* @michaelfig will ask Zarko about whether we can use checkTx for admission control into the mempool, and how frequently it is called
* cosmos-side action to store admission policy/config into the IAVL tree
* cosmic-swingset asks kernel for queue depth at end-of-block, sends that data to golang side
  * golang side stores it in the IAVL tree next to admission policy/config
  * golang side also stores a copy in RAM (or a transient non-hashed IAVL store) for use by checkTx
* deliverTx reads persistent+hashed IAVL data to compute remaining swingset window size for low-priority messages, also to implement policy/"what is high priority" tests, either accepts or rejects swingset txns on that basis
  * window size is reduced for each accepted message (of any priority, probably)
* checkTx uses RAM copy to do similar tests
  * open question: should the in-RAM window size be reduced when accepting messages into mempool?
    * we don't get to find out when the message is removed from the mempool
    * we're trying to estimate the size of a queue without complete information
    * also, all the other validators / RPC nodes are accepting messages at the same time
    * are we trying to estimate the global queue size?

**Comment by mhofman** [comment]
Couple clarification:
- We'd be splitting the admission policy in 2 blobs:
  - the address + message type blob only processed by go, and stored directly in the IAVL tree (does not result in an action sent to cosmic-swingset, or if it does it's fully ignored)
  - the "queue size" policy blob, which is sent to cosmic-swingset as an action, and stored in the swingstore.
- At the end of the block (but not at init/restart), when processing the commit block action, cosmic-swingset reads the queue size policy from the swingstore and asks swingset for the current queue state, and returns a "window size" of the number of messages that would fill up the queues.
  - That window size would be stored in the IAVL tree to be used by the next deliverTX (along with the address+message type policy)
  - This max number is NOT enforced by the JS side of cosmic-swingset, nor Swingset, only by the go side. If go sends an action with a message, JS will queue it.

**Comment by warner** [comment]
Remind me, does the queue size policy blob specifically need to be held in the swingstore? For e.g. `SWING_STORE_META_KEY`, which holds `savedHeight` and `savedChainSends`, it's critical to have those values (effectively a write-ahead log) to be committed in the same DB and txn as the kernel state changes that result. But I don't think the queue-size policy has that same requirement.

Storing it in the swingstore might be the least bad option, but I thought part of our conversation today was about holding that data in the IAVL tree, rather than swingstore. I'd like to write down what the constraints are. @michaelfig: If it's in the IAVL tree, does that make it harder to retrieve at all the necessary times?

**Comment by mhofman** [comment]
The queue size policy would have to be readable by the JS side to compute the window size at the end of every block. Afaik, we don't currently have a way to read the IAVL tree from JS.

The JS side would return the window size as a result of block commit, and the go side can store that number in the IAVL tree for its usage.

**Comment by michaelfig** [comment]
> Afaik, we don't currently have a way to read the IAVL tree from JS.

We do, in the form of the chain storage API.  Maybe that's a better place for it?

> The JS side would return the window size as a result of block commit, and the go side can store that number in the IAVL tree for its usage.

Oh, `COMMIT_BLOCK` is too late (no IAVL mutation there).  Instead, we'd do it at as the last step of `END_BLOCK`, writing to the chain storage at that time (where Golang can fetch it when needed).

**Comment by mhofman** [comment]
After discussion, this is no longer needed for MN-1 as we're shifting focus to a priority queue based approach.
See https://github.com/Agoric/agoric-sdk/issues/5334#issuecomment-1215793695

**Comment by mhofman** [comment]
This was done
