### ISSUE TITLE
Expose per-Vault economic data via notification and RPC

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5352]

**Comment by Tartuffo** [comment]
@dckc Please confirm that @dtribble 's assertion that per-Vault Collateral amount and interest amount is available via notification, and close this ticket if it is confirmed.

**Comment by dckc** [comment]
Yes, it does, as shown in these unit tests:

https://github.com/Agoric/agoric-sdk/blob/12e61941bfd2b043a935fd71659a2235e261f35a/packages/run-protocol/test/vaultFactory/test-vaultFactory.js#L532-L539

https://github.com/Agoric/agoric-sdk/blob/12e61941bfd2b043a935fd71659a2235e261f35a/packages/run-protocol/test/vaultFactory/test-vaultFactory.js#L1456-L1458
