### ISSUE TITLE
Support publishing to chainStorage-backed subscriptions

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5353]
## What is the Problem Being Solved?

On-chain vats need to publish sequential values for off-chain consumers.

## Description of the Design

Create a function that accepts a chainStorage node (cf. #4558) and returns an updater/publication object (cf. https://agoric.com/documentation/guides/js-programming/notifiers.html ) such that writes end up in chain storage. Since such writes are committed only at block boundaries, It will probably be necessary to invent a container format communicating multiple results in a single chainStorage string (and possibly a way to opt out of that for publishers whose consumers are guaranteed to tolerate loss of intermediate state).

## Security Considerations

We can control the publish _capability_, but all data written to chain storage is inherently public.

**Comment by turadg** [comment]
planning meetings tomorrow will save time having an estimate for this going in. @gibson042 ?

**Comment by Tartuffo** [comment]
Done.
