### ISSUE TITLE
Smart wallet can trade with small # of users

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5354]
Epic/milestone for smart wallets.

## Acceptance criteria

- If you walk up to a new browser with your 24 words you can make a transaction
  - actually, that requires #4654 , which is beyond the scope here
- (stretch goal): If two browser tabs open it continues to work

## plan

 - [x] (stretch) #3908 
 - [x] #5386 
    - [x] PR #4648
    - [x] PR #5400
 - [x] #4406 
 - [x] #5356 
    - [x] #3756 
        - [x] #4558 
    - [x] #5353 
    - [x] #4331 
    - [x] (dup?) #3756

**Comment by dckc** [comment]
I was thinking the main point here is that the only cosmos level transaction we have to sign to make an AMM trade is to accept the offer.

@samsiegart pointed out that this might not be feasible; we might need another one to get an invitation. #3908 is about getting an offer from a dapp to the wallet without going thru the chain.

In any case, the "two browser tabs" angle is only tangentially relevant.

**Comment by dckc** [comment]
@samsiegart where are we now? Would you please add

 - a quick-n-dirty screen recording of whatever works
   - _p.s. a swap works! We got a 1.5min recording_
 - a few text bullet points about what works, and the first thing that does not
 - a sketch of how I could reproduce those results
   - _p.s. https://gist.github.com/samsiegart/9a81face0a8683fdb2ebb72c600a6563_

**Comment by dckc** [comment]
yay! we landed all the pieces. Let's use #5073 to track end-to-end testing.
