### ISSUE TITLE
Long block times for a network under load

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#5361]
## Describe the bug
On a testnet with 90 ag-solos interacting with the AMM, block times are abnormally long (15 seconds).  Additionally in the log output it appears that consensus times out multiple times depending on the host. 

## To Reproduce
1. spin up a new testnet with 4 validators
2. launch 90 ag-solos 
3. see block times take a lot more than 5 seconds with only 90 clients

## Expected behavior
Block times for < 2000 active connections should be less than the empty block interval

## Additional context
I can spin up an instagoric environment that exhibits this behavior easily

## Screenshots
Consensus log: https://gist.github.com/arirubinstein/5270b67b15f042f57965b1cc811c1354

<img width="1368" alt="Screen Shot 2022-05-12 at 6 30 19 PM" src="https://user-images.githubusercontent.com/22369/168193705-fb3f73d9-f1a0-4f3d-9a89-487c33d634e5.png">

**Comment by warner** [comment]
We've fixed a couple of memory bugs since this test run, so I'm going to close this and expect that we'll do an updated test in the next week or two.
