### ISSUE TITLE
Wallet UI crashes on invalid value type in offer passed to addOffer

### ISSUE THREAD

**Issue by 0xshipthecode** [Agoric/Agoric#5364]
## Describe the bug

This pertains to the `beta` branch of the Agoric SDK.

The wallet UI lists offers that have been sent to it e.g. via an `addOffer` call across the wallet bridge. If such an offer is malformed, the wallet UI crashes. The crash persists across wallet UI page reloads and only remedy is to remove the offending offer (by e.g. restarting the ag-solo process entirely). This is effectively a denial of service, since no other offers can be processed by the user.

## To Reproduce
Simplest reproduction uses a modified `dapp-fungible-faucet`  (note:  also`beta` branch).

- Install Agoric as customary, run the ag-solo process
- deploy both contract and api
- In ui code, modify the line https://github.com/Agoric/dapp-fungible-faucet/blob/d97d1953076227db30efb89a55857d7fc04bfe9d/ui/public/src/main.js#L48 so that the numeric value of 1000 becomes the string "1000".
- Run the ui, approve the dApp in the wallet and then click on the "mint tokens" button.

## Expected behavior
I expected the offer to be rejected as malformed and also I expected the wallet UI to continue functioning and accepting other orders.

## Platform Environment
Node 16, vanilla OS X, sdk @agoric/sdk@16 (branch `beta` with latest commit 75965ee3ba8e4ef42b55a710cc743ea8a874c4ef)

##  Screenshot

The following error shows up in the **wallet** console and the UI henceforth fails to render.
<img width="629" alt="image" src="https://user-images.githubusercontent.com/1494839/168373872-64694587-f3b0-40d7-88ec-9fa3d2f74fdf.png">

**Comment by samsiegart** [comment]
This is probably fixed by https://github.com/Agoric/agoric-sdk/pull/5617, self-assigning to verify when possible
