### ISSUE TITLE
Offer UI does not show actual item on hover when kind is AssetKind.SET

### ISSUE THREAD

**Issue by 0xshipthecode** [Agoric/Agoric#5383]
## Describe the bug
Hovering over a proposal item of AssetKind.SET shown within the wallet applications as part of the offer popup does not show the actual Asset.  

## To Reproduce
1. Use the **beta** branch of `agoric-sdk`.
1. Clone agoric example from gateway conference `https://github.com/RBFLabs/gateway-agoric-workshop-2022`
2. Run `agoric install` and then skip to instructions for the [react-ui](https://github.com/RBFLabs/gateway-agoric-workshop-2022#react-ui)
3. Mint 200 moolas. Accept offer in wallet.
4. Write a string "name" for the "NFT" and press the "Mint the NFT!"
5. An offer is shown within wallet context. Hovering over the `dApp-NFTs.Awesomez` purse pet name or anywhere else does not show me the "name" I have minted

## Expected behavior
I'd like to be able to examine the content of the offer (what is the dApp claiming that I **want**)?

## Platform Environment
OS X, updated, beta branch of agoric-sdk

## Screenshots
<img width="435" alt="image" src="https://user-images.githubusercontent.com/1494839/168762275-9f2c377b-fa51-46e2-92e7-9e85c4f3d82a.png">

**Comment by Tartuffo** [comment]
@samsiegart please look at endo marshal to converts json to justin.

**Comment by 0xshipthecode** [comment]
Note that this might not be relevant anymore due to `AssetKind.SET` possibly being retired. See issue #5384

**Comment by erights** [comment]
`AssetKind.SET` is being deprecated and *eventually* retired. But it will be around for a long time before it is actually gone, so this issue is relevant until then.

**Comment by samsiegart** [comment]
Will implement CopyBag as well for this bug, and also support sending from purses for both (right now only NATs are supported)

**Comment by Tartuffo** [comment]
Sam let's discuss.

**Comment by samsiegart** [comment]
Tracking "send" in https://github.com/Agoric/agoric-sdk/issues/5807
