### ISSUE TITLE
lint floating promises

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5407]
## What is the Problem Being Solved?

We use promises extensively. The language allows floating promises (fire and forget) but that's rarely what we want. We've seen bugs with missing error handling, surprising order of execution or loss of stack trace.

## Description of the Design

Adopt the typescript-eslint rule [no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md)

## Security Considerations
--

## Test Plan

Check with developers to get the right signal to noise ratio in the config

**Comment by dckc** [comment]
yes, please!

I think there's wide support for this in the dev team, presuming the tooling is good.
