### ISSUE TITLE
vat terminated when doing attMaker.makeAttestation from wallet

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#5409]
## Describe the bug
BLD Boost (RUN Stake) does not work on local chain. When I try to open a loan the following error occurs: https://gist.github.com/samsiegart/a67434be91ad31314591f61dd70c91be

## To Reproduce
1. Follow https://gist.github.com/samsiegart/ed32bcbaeb88b36ddb584f11a2baed06
2. Try to "Make Offer" from the RUN Stake UI and accept it in your wallet
3. Observe the offer fails and the above logs occur

## Expected behavior
It liens my BLD and gives me RUN.

**Comment by warner** [comment]
From the slogfile, the fatal delivery was:

```
{"time":1653069933.5145257,"type":"deliver","crankNum":5516,"vatID":"v21","deliveryNum":189,"replay":false,"kd":["notify",[["kp862",{"state":"fulfilled","data":{"body":"{\"bonded\":{\"brand\":{\"@qclass\":\"slot\",\"iface\":\"Alleg
ed: BLD brand\",\"index\":0},\"value\":{\"@qclass\":\"bigint\",\"digits\":\"11000000\"}},\"currentTime\":{\"@qclass\":\"bigint\",\"digits\":\"1653069928\"},\"liened\":{\"brand\":{\"@qclass\":\"slot\",\"index\":0},\"value\":{\"@qcla
ss\":\"bigint\",\"digits\":\"0\"}},\"locked\":{\"brand\":{\"@qclass\":\"slot\",\"index\":0},\"value\":{\"@qclass\":\"bigint\",\"digits\":\"0\"}},\"total\":{\"brand\":{\"@qclass\":\"slot\",\"index\":0},\"value\":{\"@qclass\":\"bigin
t\",\"digits\":\"13000000\"}},\"unbonding\":{\"brand\":{\"@qclass\":\"slot\",\"index\":0},\"value\":{\"@qclass\":\"bigint\",\"digits\":\"0\"}}}","slots":["ko83"]}}]]],"vd":["notify",[["p+54",false,{"body":"{\"bonded\":{\"brand\":{\
"@qclass\":\"slot\",\"iface\":\"Alleged: BLD brand\",\"index\":0},\"value\":{\"@qclass\":\"bigint\",\"digits\":\"11000000\"}},\"currentTime\":{\"@qclass\":\"bigint\",\"digits\":\"1653069928\"},\"liened\":{\"brand\":{\"@qclass\":\"s
lot\",\"index\":0},\"value\":{\"@qclass\":\"bigint\",\"digits\":\"0\"}},\"locked\":{\"brand\":{\"@qclass\":\"slot\",\"index\":0},\"value\":{\"@qclass\":\"bigint\",\"digits\":\"0\"}},\"total\":{\"brand\":{\"@qclass\":\"slot\",\"inde
x\":0},\"value\":{\"@qclass\":\"bigint\",\"digits\":\"13000000\"}},\"unbonding\":{\"brand\":{\"@qclass\":\"slot\",\"index\":0},\"value\":{\"@qclass\":\"bigint\",\"digits\":\"0\"}}}","slots":["o-54"]}]]]}
```

This did a few valid syscalls, then did:
```
{"time":1653069933.528532,"type":"syscall","crankNum":5516,"vatID":"v21","deliveryNum":189,"syscallNum":2,"replay":false,"vsc":["send","o-69",{"methargs":{"body":"[\"mintAndEscrow\",[{\"brand\":{\"@qclass\":\"slot\",\"iface\":\"Alleged: Attestation brand\",\"index\":0},\"value\":{\"@qclass\":\"tagged\",\"tag\":\"copyBag\",\"payload\":[[\"agoric13gtnx0gayj6550y87kty4mw29afwmwvx5dnwc2\",{\"@qclass\":\"bigint\",\"digits\":\"11000000\"}]]}}]]","slots":["o-70"]},"result":"p+56"}]}
```

which provoked a syscall error:
```
{"time":1653069933.5285957,"type":"syscall-result","crankNum":5516,"vatID":"v21","deliveryNum":189,"syscallNum":2,"replay":false,"ksr":["error","syscall translation error: prepare to die"],"vsr":["error","syscall translation error: prepare to die"]}
```

That error message is a bit deceptive: it is triggered by any kernel-side assertion during processing of the syscall, so it could be a kernel bug, rather than the vat trying to use a bad vref (which is what the message kinda implies). The two vrefs cited in that syscall (`o-69` and `o-70`) don't appear in a `syscall.dropImports` before that point, so there's no reason for them to be missing from the c-list.

The next step is to look at the console output of the kernel/chain process and see if the full error message is captured.

**Comment by warner** [comment]
```
2022-05-20T18:31:38.452Z SwingSet: kernel: error during syscall translation: (Error#1)
Error#1: unknown qClass tagged in legibilizeValue

  at legibilizeValue (.../swingset-vat/src/lib/kdebug.js:46:8)
  at legibilizeValue (.../swingset-vat/src/lib/kdebug.js:54:30)
  at eval (.../swingset-vat/src/lib/kdebug.js:96:32)
  at Array.map (<anonymous>)
  at legibilizeMessageArgs (.../swingset-vat/src/lib/kdebug.js:96:21)
  at translateSend (.../swingset-vat/src/kernel/vatTranslator.js:254:23)
  at Object.vatSyscallToKernelSyscall (.../swingset-vat/src/kernel/vatTranslator.js:572:8)
  at vatSyscallHandler (.../swingset-vat/src/kernel/kernel.js:1201:17)
  at Object.syscallFromWorker (.../swingset-vat/src/kernel/vat-loader/manager-helper.js:253:12)
  at handleUpstream (.../swingset-vat/src/kernel/vat-loader/manager-subprocess-xsnap.js:87:11)
  at handleCommand (.../swingset-vat/src/kernel/vat-loader/manager-subprocess-xsnap.js:110:14)
  at runToIdle (packages/xsnap/src/xsnap.js:198:42)
```

It looks like the recent kernel `methargs` PR landed, which incidentally changed `legibilizeValue`. I'm guessing that `legibilizeValue()` doesn't understand something that the vat's `marshal` is emitting, and asserts or throws an error.

The kernel should definitely not assume that it can understand this information: vats are allowed to send anything they want, including new `@qclass` types, and the kernel should tolerate it. 

@FUDCo this is looking like one for you. The interesting `@qclass` is `tagged`, whatever that means. But simply making that work is not sufficient: we need to tolerate completely arbitrary stuff in that capdata.

**Comment by warner** [comment]
A workaround is probably to edit packages/SwingSet/src/lib/kdebug.js line 46, and replace the `assert.fail` with something like `return 'unknown'`

**Comment by FUDCo** [comment]
I think the correct fix is just to treat an unknown `@qclass` like any other object literal, i.e., don't try to interpret it, just stringify it.  It's a very easy tweak, though I'm not entirely sure how to test it.
