### ISSUE TITLE
"yarn lint" succeeds even when vscode correctly shows lint errors

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#5416]
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/273868/169635807-5c31fd6c-6567-497f-8916-e8655d454e32.png">

The hover in the left pane above correctly shows that `vatParams` is an unused parameter (and therefore should be spelled `_vatParams`). The right pane shows that when we ran `yarn lint` in the same directory, it did not complain. Similarly, running `yarn lint` at the top of agoric-sdk does not complain about this.

**Comment by erights** [comment]
@michaelfig @turadg I'm guessing when I assigned this to y'all. Please reassign to whoever is appropriate. Thanks.

**Comment by erights** [comment]
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/273868/169638163-17a39f2a-f1ae-42e3-aeb7-ba60b1dbb288.png">

Just another example. This one showing two errors on the left, neither of which is reported on the right. The non-report of the `// @ts-expect-error` is especially unfortunate, since that's why we switched to it from `// @ts-ignore-error` in the first place.

**Comment by turadg** [comment]
[Known issue](https://github.com/Agoric/agoric-sdk/issues/4620), the solution for which is a [big amount of work](https://github.com/Agoric/agoric-sdk/issues/4560) explicitly deprioritized to after MN-1.
