### ISSUE TITLE
swingset-tests in inter-protocol - restore? retire?

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#5433]
## What is the Problem Being Solved?

_IOU details._ context
-  https://github.com/Agoric/agoric-sdk/pull/5431

**Comment by Tartuffo** [comment]
@dckc @Chris-Hibbert Did we decide this was MN-1?  If it is in Chris's "Up Next", it should be critical for MN-1.

**Comment by Chris-Hibbert** [comment]
I don't believe we want to abandon these tests, or even allow them to bitrot through MN-1/
