### ISSUE TITLE
Kernel memory leak causing test SIGKILL

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#5447]
## Describe the bug
As of `4279-critical-vat-panic` (https://github.com/Agoric/agoric-sdk/pull/5436), the SwingSet test `test/vat-admin/terminate/test-terminate.js` fails after 27ish tests (out of 31) on an OOM failure, even when run serial, but apparently only when using an XS worker.

## To Reproduce
1. `cd packages/SwingSet`
2. `yarn test:xs -s --verbose 'test/vat-admin/terminate/test-terminate.js'`

## Expected behavior
Successful test

## Platform Environment
 - what OS are you using? what version of Node.js? Node 16 on Debian buster (in a WSL VM)
 - is there anything special/unusual about your platform? Low-ish memory with hard cap on swap (memory = 8GB RAM + 8GB swap)
 - what version of the Agoric-SDK are you using? `c99ef9eb2606eb7f0badaaecf5df710f2f03d897`

## Additional context
https://agoricopco.slack.com/archives/C038E5369FT/p1653534455289559

The process seem to grow to a VMM size of 12GB, skipping 3-4 tests, the suite completes successfully. It runs fine under Node workers but may just be a matter of not growing the overall memory as quickly (less multi process overhead, each with their own copy of the supervisor).

Re-bundling before each test (aka not sharing any explicit state between tests) does not solve the issue. If something holds onto the memory, it's somewhere in the implementation.

## Screenshots
https://github.com/Agoric/agoric-sdk/runs/6606673500

**Comment by warner** [comment]
On my linux box (Node 16, Ubuntu "focal", 64-bit x86) I see current trunk (1a6f5d9b0)'s `test-terminate-non-critical.js`, using `test:xs`, gets a `node` process with a VM size of about 11-12 GB (but the RSS never seems to grow above 500MB), and 6-8 `xsnap` processes each with a VM size of 1GB (and an RSS of about 56MB).

The total claim on VM size could easily exceed an 8+8 system limit. My box has 32GB of RAM and another 8GB of swap.

Also I think there's an "overcommit" setting somewhere. It might be set (or imlemented) differently on a linux-under-windows WSL VM than on the linux-on-bare-metal machine I tested with.

I wonder if it's not this test in particular, but any test which launches more than `(16GB - 12GB) / 500MB` xsnap workers.

@mhofman you might try an experiment: run a couple of `node.js` REPLs in the background, estimate how much VmSize they're consuming, then start the `yarn test`. If it's a total-committed-vmsize limit, then more tests should fail if those extra REPLs have some VMsize pinned. Another cheap trick I've done is something like `'a'.repeat(1_000_000_000)` to allocate and fill a large chunk of memory (which can be swapped out almost immediately, but still consumes Vmsize)

**Comment by warner** [comment]
@mhofman This sounds like another instance of the Promise.race issue, which should now be fixed. Have you seen any evidence for/against this hypothesis? Do you think we can close this now?

**Comment by mhofman** [comment]
Oh good call, gonna try to repro with the unsplit tests and see if the problem persists

**Comment by mhofman** [comment]
Apparently we're still running into the same issue if I revert the test split, so I think there's another leak lurking. I'll see if I can quickly wire a heap snapshot to trace the source of the leak.

**Comment by mhofman** [comment]
It looks like most of the retained size are JSON stringified bundles (`{"moduleFormat":"endoZipBase64","endoZipBase64":"UEsDBAoAAAAAAAAAAACbQUOu4...`), which seems held through the `getStackString` and/or `Compartment` on the global. I'm really unsure of how or why, but it seem to be a problem of the SES shim.

Repro branch with unsplit test and added heap snapshots: https://github.com/Agoric/agoric-sdk/tree/repro-5447

cc @kriskowal @erights

**Comment by kriskowal** [comment]
@mhofman Do you have an example of the a full retention path from a heap snapshot? It seems likely to me that there are a number of places along the way where we might be able to jettison references back to the bundle.

**Comment by mhofman** [comment]
The retention path was a bit obscure to me, including edges in WeakMap and internal v8 structures. It's pretty easy to repro however with the instructions and branch above.
