### ISSUE TITLE
voter invitation offer hangs in wallet

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#5483]
### Symptoms

  - a deploy script ([vote-raise-debt-limit.js](https://gist.github.com/dckc/7733f85be2c25a1a47b639e4b94816ac#file-vote-raise-debt-limit-js)) that does `const voterFacet = await E(zoe).offer(voterInvitation)` seems to work, but
  - a script that uses the wallet to handle the offer ([vote-raise-debt-limit-wb.js](https://gist.github.com/dckc/7733f85be2c25a1a47b639e4b94816ac#file-vote-raise-debt-limit-wb-js)) does not; the offer hangs in "pending" state and the wallet doesn't seems to update the offers notifier until I hit **exit**

### Diagnosis (presumed)

The offer handler in committee.js doesn't exit the seat:

https://github.com/Agoric/agoric-sdk/blob/ee043dc013f3aadf63473825968f362d83ca6f1f/packages/governance/src/committee.js#L41-L43

I don't have a clear sense of what `seat.exit()` is all about. I wonder if we have clear docs anywhere.

by the way.. why is that offer handler `Far`? Anybody know?

cc @michaelfig @Chris-Hibbert

**Comment by Chris-Hibbert** [comment]
> I wonder if we have clear docs anywhere.

Is the [doc page](https://agoric.com/documentation/zoe/api/zoe-contract-facet.html#zcfseat-exit-completion) sufficient?

**Comment by dckc** [comment]
No; the ZCFSeat docs don't make clear to me me whether the committee contract has a bug here. It doesn't tell me what are the possible states of a ZCFSeat and how the `.exit()` method changes the state.

**Comment by Chris-Hibbert** [comment]
`Far` on `offerHandler` is unnecessary.

> what are the possible states of a ZCFSeat and how the .exit() method changes the state.
I think they can be active or exited. When active, they have allocations that are under the control of the contract. The contract can use `zcfSeat.exit()` or `zcfSeat.fail()` to exit the seat. In either case the holder of the userSeat can see the `offerResult` and collect the payouts. There's much more internal detail about the seats, but it doesn't seem to be relevant to your question.

If the wallet depends on the seat being exited (which releases any payment) then we should consider declaring it normal practice to exit when done. This offer makes no payments, so it didn't even look at the seat.

**Comment by dckc** [comment]
Both parts are less than ideal:

 - wallet shouldn't wait for .exit() to get offerResult
 - committee contract should .exit() when it's done with the seat
