### ISSUE TITLE
A contract must not lose assets if it dies

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5486]
## What is the Problem Being Solved?

Contracts can hold assets in ZCFSeats during their lifecycle.  If a contract dies, we need to ensure that the assets that were held on seats at the time of death are not lost.

This issue was raised [here](https://github.com/Agoric/agoric-sdk/discussions/5469).

**Comment by dckc** [comment]
> Contracts can hold assets in ZCFSeats during their lifecycle.

Isn't it Zoe that holds assets represented by ZCFSeats?

**Comment by dckc** [comment]
result of today's Zoe meeting:

There are enough ways to avoid this problem, and alternatives are sufficiently costly, that we don't plan to change our Zoe design in this area.

We may find ways to improve our contracts in this area, using some of the ways to avoid it.

_here's hoping for time to write up the alternatives a bit... seller seats and such..._
