### ISSUE TITLE
re-examine IST contracts for user-supplied parameter validation

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#5494]
## What is the Problem Being Solved?

#5492, #5293 were recent cases in which contracts were not sufficiently validating their user-supplied inputs. #5131 is a case where the contract wasn't checking prerequisites.

## Description of the Design

Examine IST contracts and verify that user-supplied inputs, including brands in proposals are validated before being used.

## Security Considerations

General contract hygiene.

## Test Plan

Include tests for each fix.

**Comment by dckc** [comment]
Another security consideration: **availability** of the Inter protocol contracts is critical to the Agoric economy.

Our fail-stop norms and tools do a good job on _integrity_, and while a stuck AMM is better than one that leaks assets, it's no good when a vault needs to be liquidated.

**Comment by Chris-Hibbert** [comment]
With the closing of #5496, I'm done looking for more issues here.
