### ISSUE TITLE
Agoric wallet crashed when dApp use AssetKind.COPY_BAG

### ISSUE THREAD

**Issue by vigh18** [Agoric/Agoric#5553]
## Describe the bug
Agoric wallet crashed when dApp use AssetKind.COPY_BAG

## To Reproduce
1. Use the main branch of agoric-sdk.
2. Clone agoric example from gateway conference https://github.com/RBFLabs/gateway-agoric-workshop-2022
3. Run agoric install and then skip to instructions for the [react-ui](https://github.com/RBFLabs/gateway-agoric-workshop-2022#react-ui)
4. Accept dApp in wallet and wait until it tries to render dApp-NFTs.Awesomez.

## Expected behavior
Wallet dApp should not crash.

## Platform Environment
OS X, updated, beta branch of agoric-sdk

## Screenshots
<img width="1491" alt="Screenshot 2022-06-09 at 11 54 17" src="https://user-images.githubusercontent.com/14995194/172820151-08d5ab8e-3635-4893-9a2a-e982a5834b75.png">

**Comment by Tartuffo** [comment]
FYI @michaelfig

**Comment by turadg** [comment]
As part of fixing this the UI should be made more robust (needn't crash when UI fails to parse an amount).

Scheduling for MN-1. @samsiegart please estimate.

**Comment by samsiegart** [comment]
The crash should be fixed from #5617, but actual CopyBag support will be implemented in https://github.com/Agoric/agoric-sdk/issues/5383, closing this now.
