### ISSUE TITLE
swingset transcript.js returns bogus VatSyscallResults during replay for GC syscalls

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5557]
When I fixed #5511 to record and return the full VatSyscallResult (both for errors and successes), I forgot to change `simulateSyscall`, which short-circuits the GC syscalls (`dropImports`, `retireImports`, `retireExports`). When it sees one of these, it 1: ignores the transcript, and 2: returns `undefined`.

That second part needs to change: `undefined` is not a valid `VatSyscallResult` (it is the data portion of `['ok', undefined]`, which *is* a valid VSR, and is the standard response to all GC syscalls, which don't have any other return value to offer).

@mhofman observed apparently non-fatal errors in the logs of a loadgen run which were caused by this bug. They were probably fatal to the `dispatch.bringOutYourDead` delivery happening at that time, but maybe because they were happening during replay, they didn't cause any significant problems beyond a different in logging.

I'm wondering if we should stop stripping the GC syscalls from the transcript. We did this when we wanted to tolerate different organic GC schedules between different vats (the "formal vs local GC" era). Given our need to have metering be identical, and our work to make GC consequences only observable during `bringOutYourDead`, I think at this point we could reasonably expect all GC activity to be in consensus, and thus it might no longer be necessary to ignore GC syscalls when replaying the transcript.

If we stopped ignoring them, this bug would probably have surfaced much faster: if the error caused a second GC syscall to not happen, we'd have gotten an `AnacrophobiaError` during replay.

We should also make sure that any errors during replay (non-`ok` VatDeliveryResults) cause a replay failure (and ultimately a kernel panic).

**Comment by mhofman** [comment]
> We should also make sure that any errors during replay (non-`ok` VatDeliveryResults) cause a replay failure (and ultimately a kernel panic).

I suppose we wouldn't be replaying the delivery in the first place if it had previously failed (aka the vat had gotten terminated).

This occurred during the CI deployment test integration: https://github.com/Agoric/agoric-sdk/runs/6818734359?check_suite_focus=true#step:10:8734

<details>

<summary>Relevant logs with previous context showing it's when replaying after restart:</summary>

```
stage-1: chain: 2022-06-09T18:55:26.535Z launch-chain: buildSwingset
stage-1: chain: SwingSet xs-worker tracing: {
stage-1: chain:   XSNAP_TEST_RECORD: '/usr/src/agoric-sdk/chaintest/results/chain-stage-1-xsnap-trace'
stage-1: chain: }
stage-1: monitor-chain: found process 30013 for vat v1 "bootstrap"
stage-1: chain: 2022-06-09T18:55:27.514Z SwingSet: vat: v1: reserveGovernorCreatorFacet settled; remaining: [ 'reserveCreatorFacet', 'reservePublicFacet', 'vaultFactoryCreator', 'vaultFactoryGovernorCreator', 'vaultFactoryVoteCreator' ]
stage-1: chain: 2022-06-09T18:55:27.515Z SwingSet: vat: v1: reserveCreatorFacet settled; remaining: [ 'reservePublicFacet', 'vaultFactoryCreator', 'vaultFactoryGovernorCreator', 'vaultFactoryVoteCreator' ]
stage-1: chain: 2022-06-09T18:55:27.517Z SwingSet: vat: v1: reservePublicFacet settled; remaining: [ 'vaultFactoryCreator', 'vaultFactoryGovernorCreator', 'vaultFactoryVoteCreator' ]
stage-1: chain: 2022-06-09T18:55:27.520Z SwingSet: vat: v1: instance reserve settled; remaining: [ 'Treasury', 'VaultFactory', 'VaultFactoryGovernor', 'amm', 'interchainPool', 'psm', 'psmGovernor', 'reserveGovernor', 'runStakeGovernor' ]
stage-1: chain: 2022-06-09T18:55:27.522Z SwingSet: vat: v1: instance reserveGovernor settled; remaining: [ 'Treasury', 'VaultFactory', 'VaultFactoryGovernor', 'amm', 'interchainPool', 'psm', 'psmGovernor', 'runStakeGovernor' ]
stage-1: chain: 2022-06-09T18:55:27.573Z SwingSet: vat: v1: instance amm settled; remaining: [ 'Treasury', 'VaultFactory', 'VaultFactoryGovernor', 'interchainPool', 'psm', 'psmGovernor', 'runStakeGovernor' ]
stage-1: chain: 2022-06-09T18:55:27.670Z SwingSet: xsnap: v1: worker got error during syscall: (Error#1)
stage-1: chain: 2022-06-09T18:55:27.683Z SwingSet: xsnap: v1: Error#1: Check failed
stage-1: chain: 2022-06-09T18:55:27.684Z SwingSet: xsnap: v1: Error: Check failed
stage-1: chain:  at construct ()
stage-1: chain:  at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:5943)
stage-1: chain:  at makeError (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2705)
stage-1: chain:  at fail (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2832)
stage-1: chain:  at baseAssert (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2850)
stage-1: chain:  at insistVatSyscallResult (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:6761)
stage-1: chain:  at syscallToManager (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:17517)
stage-1: chain:  at doSyscall (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:17229)
stage-1: chain:  at scanForDeadObjects (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15823)
stage-1: chain:  at ()
stage-1: chain:  at ()
stage-1: chain: 
stage-1: chain: 2022-06-09T18:55:27.689Z SwingSet: xsnap: v1: error Error: Check failed during vat dispatch() of bringOutYourDead
stage-1: chain: 2022-06-09T18:55:28.051Z SwingSet: xsnap: v1: worker got error during syscall: (Error#2)
stage-1: chain: 2022-06-09T18:55:28.058Z SwingSet: xsnap: v1: Error#2: Check failed
stage-1: chain: 2022-06-09T18:55:28.059Z SwingSet: xsnap: v1: Error: Check failed
stage-1: chain:  at construct ()
stage-1: chain:  at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:5943)
stage-1: chain:  at makeError (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2705)
stage-1: chain:  at fail (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2832)
stage-1: chain:  at baseAssert (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2850)
stage-1: chain:  at insistVatSyscallResult (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:6761)
stage-1: chain:  at syscallToManager (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:17517)
stage-1: chain:  at doSyscall (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:17229)
stage-1: chain:  at scanForDeadObjects (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15823)
stage-1: chain:  at ()
stage-1: chain:  at ()
stage-1: chain: 
stage-1: chain: 2022-06-09T18:55:28.062Z SwingSet: xsnap: v1: error Error: Check failed during vat dispatch() of bringOutYourDead
```

</details>

**Comment by warner** [comment]
Replay can never terminate a vat: termination only happens as part of consensus, and replay occurs as the local validator is trying to catch up after a (outside-of-consensus) process restart. So if something surprising happens during replay, it's the local validator that halts.

But yeah, if replay was stopped because of a syscall mismatch during one delivery, we wouldn't/shouldn't be trying to replay any subsequent deliveries on that worker. And then we either need to panic the kernel (best, for visibiltiy), or maybe kill the worker and try again (meh).

**Comment by mhofman** [comment]
Sorry I wasn't clear. I meant that if a delivery non`-ok` result had happened the first time around, the vat would have been terminated (or in the future paused), and we wouldn't have to replay that delivery to begin with. I was just trying to confirm why it was the right approach to panic when seeing a non-`ok` delivery result during replay.

**Comment by mhofman** [comment]
I opened https://github.com/Agoric/agoric-sdk/pull/5563 to fix the issue. And filed https://github.com/Agoric/agoric-sdk/issues/5564 and https://github.com/Agoric/agoric-sdk/issues/5565 to implement the transcript changes suggested by @warner above.

**Comment by mhofman** [comment]
@warner I left this issue opened since you expressed interest in writing a test explicitly for it (that my be independent of the 2 issues I opened).

**Comment by Tartuffo** [comment]
@warner please review, decide if it needs a test, and close.

**Comment by Tartuffo** [comment]
@warner close if done please.

**Comment by Tartuffo** [comment]
@warner please take another look.

**Comment by warner** [comment]
I'm not realistically going to get to write a test for this, and we haven't seen any other problems related to it, so I'm going to close this one.
