### ISSUE TITLE
connection refused when deploying dapp-fungible-faucet to devnet

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#5601]
## Describe the bug

Following the getting started instructions, we get as far as [Deploy the contract](https://agoric.com/documentation/getting-started/start-a-project.html#deploy-the-contract-and-api) but it fails with `connection refused`.

I suspect the `tx swingset install-bundle` support from #4975 isn't integrated with `agoric start testnet`.

## To Reproduce
1. check out agoricdev-13 ; yarn ; yarn build
2. `agoric init demo15; cd demo15; agoric install`
3. `agoric start --reset testnet 8000 https://devnet.agoric.net/network-config`
4. `agoric deploy ./contract/deploy.js ./api/deploy.js`

```
$ agoric deploy ./contract/deploy.js ./api/deploy.js
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /home/connolly/projects/agoric/demo15/contract/deploy.js
agoric: deploy: Deploy script will run with Node.js ESM
agoric: deploy: /home/connolly/projects/agoric/agoric-sdk/golang/cosmos/build/agd tx swingset install-bundle --gas auto --gas-adjustment 1.2 --home /home/connolly/projects/agoric/demo15/_agstate/agoric-servers/testnet-8000/ag-cosmos-helper-statedir --keyring-backend test --from ag-solo --chain-id agoricdev-13 --yes @/tmp/agoric-cli-bundle--2328033-OEV9okvXA6GG/bundle.json
Error: post failed: Post "http://localhost:26657": dial tcp 127.0.0.1:26657: connect: connection refused
Usage:
  agd tx swingset install-bundle <JSON>/@<FILE>/- [flags]
```

## Expected behavior
contract gets deployed

## Platform Environment
 - _what OS are you using?_ Ubuntu _what version of Node.js?_ v16.14.2
 - _is there anything special/unusual about your platform?_ trying to deploy to devnet
 - _what version of the Agoric-SDK are you using? (run `git describe --tags --always`)_ bb2451d

cc @michaelfig @kriskowal

**Comment by dckc** [comment]
##  Additional context

I opened this on behalf of @vejmelkam , who noted it in discord

**Comment by Tartuffo** [comment]
@kriskowal Please add this to your MN-1 work list!

**Comment by kriskowal** [comment]
This is a mitigation https://github.com/Agoric/dapp-fungible-faucet/pull/48

**Comment by dckc** [comment]
I'm struggling to verify that this is fixed. Using 98eac1daf857e7bad4 when I `agoric start local-solo` I get

```
2022-09-05T02:00:38.517Z SwingSet: ls: v10: TypeError: target has no method "getMyAddress", has ["myAddressNameAdmin","nameHub"]
```

I think what I did was
1. git clone agoric-sdk at 98eac1daf857e7bad4 ; `yarn && yarn build`
2. `agoric init demo15; cd demo15; agoric install`
3. `agoric start local-chain --reset -v`
4. `agoric start local-solo --reset -v`
