### ISSUE TITLE
remove everything @deprecated for MN-1 release

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5605]
## What is the Problem Being Solved?

MN-1 launch requires some breaking changes. Let's bundle them together so we have fewer breaks after.

## Description of the Design

Including but not limited to,
- legacyMap.js

**Acceptance criteria**
- No `@deprecated` in repo
- Loadgen not broken (e.g. [using fallback](https://github.com/Agoric/testnet-load-generator/pull/76))

**Comment by abebeos** [comment]
@turadg The related milestone looks closed (sidenote: has still one dangling issue):

https://github.com/Agoric/agoric-sdk/milestone/37

Can this techdebt issue here be closed?

**Comment by ivanlei** [comment]
There are still @deprecated in the codebase https://github.com/Agoric/agoric-sdk/search?p=1&q=deprecated&type=code
