### ISSUE TITLE
Vesting Contract

### ISSUE THREAD

**Issue by vigh18** [Agoric/Agoric#5638]
Let assume that Agoric's issuer, mint, brand trio is the way how can anyone create its own tokens which is analogy to ERC20. I can see a lot of use cases where the token owner want to distribute his tokens to other people according some specified vesting schedule by some trustless way. And the vesting contracts can exactly do that. We can take an open zeppelin as a reference. https://github.com/OpenZeppelin/token-vesting-ui

**Comment by dckc** [comment]
good question... we started discussing it...

**Comment by trentlapinski** [comment]
Definitely something we’re looking into.

I see that project is no longer maintained, was there anything specific you liked about it? How could we make it better?
