### ISSUE TITLE
durable kinds must upgrade to the same number/names of facets

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5662]
## What is the Problem Being Solved?

While walking through ZCF/contract upgrade with @erights and @Chris-Hibbert , I realized that v1 of a vat/contract might define a durable kind with facets `[aliceFacet, bobFacet]`, and then a subsequent v2 might use the same (stored) `KindHandle` to associate new behavior that used *different* facet names, or a different number of facets.

They originally thought that this should be fine, even desirable: being able to add new facets would be a convenient form of upgrade.

But after walking through how facet vrefs are managed, I think I convinced them that we cannot accomodate changes to the shape of a cohort record (a MultiKind) during upgrade:

* we map facet names to integers (using `getOwnPropertyNames().sort()` on the behavior record), and then use those integers:
  * as the `facet` component of a vref: `o+3/2:1` means "kind o+3, instance 2, facet 1"
  * as an index into the string stored in the export-status record: a three-facet cohort might have a record of `rsn`, where the first facet has status `r` (reachable by the kernel), the second facet has status `s` (recognizable aka "seen" by the kernel), and the third facet `n` is not currently exported to the kernel at all

We record the list of `facetNames` in RAM (`virtualReferences.js > rememberFacetNames()`), but we do not store it durably in the DB. As a result, the next version might call `defineKindMulti()` with a behavior record that provides a different set of facets. Bad things that would result:

* existing vrefs could get reassigned to a different facet of the same cohort
  * if exported, a client who had access to `bobFacet` might wind up talking to `aliceFacet`
* those vrefs might wind up pointing to no facet at all (if the number of facets was reduced), probably causing a crash during message delivery, or virtual-data deserialization
* the export status of existing vrefs would probably get confused

## Description of the Design

The immediate task is to make sure this does not happen. We need to record the `facetNames` durably, when we define the Kind for the first time. In later versions, when re-defining the Kind, we must assert that the new behavior record is parsed into exactly the same set of facet names.

In the future, we can think about how to relax this, by allowing the creation of new facet names. I think we must insist that the old facets remain in place (same names, same order), but if we could figure out how to allow the export status records to be open-ended (treat short strings as if they had an implicit suffix of `n`s ?), then we could probably tolerate the addition of new ones. Note that this is at odds with our current practice of sorting the facet names; we'd have to make up some rule like "sort all the new ones, then append the new ones to the stored old list".

## Security Considerations

Vat upgrade gets to change the behavior of a lot of stuff, and the new Kind record is in complete control of how the old exported vrefs behave, but that's no reason to allow the upgrader to cause this sort of chaos.

## Test Plan

Unit tests that do an upgrade with different facets (all three cases: more facets, fewer facets, same number but differently named facets).

cc @FUDCo

**Comment by FUDCo** [comment]
If we already need to explicitly store the facet names for the purpose of validating post-upgrade kind (re)definitions, it's trivial for the record that does that to also capture the mapping from a facet name to its cohort index.  This means that adding new facets during an upgrade should be quite easy.

Longer term, we could enable a redefinition to abandon an unused facet by simply not providing behavior for it.  To be safe, this would require a scan of the database to ensure that all existing instances of the facet were unreferenced (looking at the range of `vom.es.${kind}/${instance}` records to check that each has an `n` at the corresponding facet index). This would be O(n) in the number of instances of the kind in question, which could be expensive but perhaps justifiable in some cases.

**Comment by warner** [comment]
Let's aim for asserting the set of facets does not change, for MN-1, and consider allowing the addition of new facets for a later release.
