### ISSUE TITLE
Consume metrics into DB/Prometheus for Econ Stress Test

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#5681]
## What is the Problem Being Solved?

Econ Stress test needs a bunch of data in a convenient form.

## Design

_up to @arirubinstein and co_

## Security Considerations

gets a whole bunch of moving parts, including a private signing key, out of the equasion

## Test Plan

manual, with, Nalin, @btulloh and co.

**Comment by dckc** [comment]
## amm, vaults w/governance working via RPC

 - [ist-monitor2.mjs](https://github.com/dckc/ag-admin/blob/rpc/scripts/ist-monitor2.mjs) 2b8203f
 - [spreadsheet](https://docs.google.com/spreadsheets/d/1R94HzdrKYjFlr0PSg04XGvZXWDUjLHdZXOgnyUOuYi8/edit#gid=8916276)

## TODO: PSM, Reserve, BLD Boost

Among the other targets from #5421:

- reserve https://github.com/Agoric/agoric-sdk/issues/4651
- PSM https://github.com/Agoric/agoric-sdk/issues/4968
- BLD Boost https://github.com/Agoric/agoric-sdk/issues/4653
- Oracle / price authority https://github.com/Agoric/agoric-sdk/issues/4652

We have all but Oracle available, to at least some extent:

```
$ agd query vstorage keys published
children:
- amm
- psm
- reserve
- stakeFactory
- vaultFactory
```

## Oracle???

I'm not sure if we have clear plans for this one. _p.s. yes, we do: #4652_

That reminds me...

### `chainStorage` for unprivileged contracts?

How do ordinary contracts publish their data for read-only RPC? `chainStorage` is currently privileged.

_for follow-up, see #5687_

**Comment by dckc** [comment]
6cd8054 is working pretty well. no individual vaults yet. nor reserve etc.

**Comment by dckc** [comment]
I'm not sure what to make of this:

```
PROOF VERIFICATION FAILURE; crashing follower (Error#4)
Error#4: {"code":-32603,"message":"Internal error","data":"min height 76703 can't be greater than max height 76702"}
```

for now, I set `proof: 'none'`

[ist-monitor2.mjs](https://github.com/dckc/ag-admin/blob/rpc/scripts/ist-monitor2.mjs) [09d5a8d](https://github.com/dckc/ag-admin/commit/09d5a8d2f5d0bb3e611cc6e4992ad32eb156063c)

_p.s. @gibson042 suspects a timing issue with follow-up queries going out too early or some such._

**Comment by dckc** [comment]
I deployed it to GCP using a systemd user unit... it gets the starting / current values, but doesn't seem to update as new values come in.

[ist-monitor.service](https://github.com/dckc/ag-admin/blob/rpc/ist-monitor.service)

**Comment by dckc** [comment]
@arirubinstein I'd like to go over [ist-monitor.service](https://github.com/dckc/ag-admin/blob/rpc/ist-monitor.service) with you.

I went over [ist-monitor2.mjs](https://github.com/dckc/ag-admin/blob/rpc/scripts/ist-monitor2.mjs) with @gibson042 ; using that as a throw-away prototype, the two of you should be able to put together a service that works for @btulloh and Nalin.

Using a google sheet is not necessary; whatever works for the customer is fine by me. But I'd be a little surprised if the "write CSV or JSON to stdout" approach works, since then the customer has to install and run the code and maintain updates.

**Comment by dckc** [comment]
@gibson042 re `insertedAt` vs. block time, I found the issue: #5508

**Comment by Tartuffo** [comment]
Handing off to @arirubinstein

**Comment by dckc** [comment]
dev work on this is planned for after we have a network running with the features in this release such as

 - #5354 
 - #5077

**Comment by dckc** [comment]
## vault detail available via RPC on xnet

<details>
<summary>published.vaultFactory.manager0.vaults.vault2</summary>

```console
$ ~/go/bin/agd --node=https://xnet.rpc.agoric.net:443 query vstorage data published.vaultFactory.manager0.vaults.vault2 -o json | jq '.value | fromjson | {body: .body | fromjson, slots}'
```
```json
{
  "body": {
    "debtSnapshot": {
      "debt": {
        "brand": {
          "@qclass": "slot",
          "iface": "Alleged: IST brand",
          "index": 0
        },
        "value": {
          "@qclass": "bigint",
          "digits": "30300000"
        }
      },
      "interest": {
        "denominator": {
          "brand": {
            "@qclass": "slot",
            "index": 0
          },
          "value": {
            "@qclass": "bigint",
            "digits": "100"
          }
        },
        "numerator": {
          "brand": {
            "@qclass": "slot",
            "index": 0
          },
          "value": {
            "@qclass": "bigint",
            "digits": "100"
          }
        }
      }
    },
    "locked": {
      "brand": {
        "@qclass": "slot",
        "iface": "Alleged: IbcATOM brand",
        "index": 1
      },
      "value": {
        "@qclass": "bigint",
        "digits": "50000"
      }
    },
    "vaultState": "active"
  },
  "slots": [
    "board0074",
    "board03446"
  ]
}
```
</details>

**Comment by dckc** [comment]
@arirubinstein gave a demo of
 - [Agoric/metricsreader](https://github.com/Agoric/metricsreader) [018c35a](https://github.com/Agoric/metricsreader/commit/018c35aca1c5cb40d2fce086ec7e3bfe2421025c)

@nalinbhatt plans to try it out. Presuming that works out, I'm closing this. (Feel free to re-open if doesn't work and you can't otherwise find out how to get the data you need).
