### ISSUE TITLE
Upgrade tendermint to 0.34.19

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#5699]
## What is the Problem Being Solved?

Relevant to #5694, upgrading tendermint to pick up recent bug fixes.

- tendermint/tendermint#7992
- tendermint/tendermint#7994

## Description of the Design

Upgrade agoric-labs/tendermint then have ag0 and agd use it.

**Comment by 48198880** [comment]
How Can I update the version ?<img width="393" alt="ccecf21ed479a3a0470061a1b29ec84" src="https://user-images.githubusercontent.com/24585220/176933280-a3bcec63-c3df-4d76-84f7-54d370fff11d.png">

**Comment by JimLarson** [comment]
It looks like the tendermint upgrade requires a cosmos-sdk upgrade as well. We're working on it for ag0.

edit: target: cosmos-sdk v 0.44.8

**Comment by 48198880** [comment]
My Validator has been jailed due to this error 
<img width="652" alt="6c7d1be7def66488d09348da1fc8cba" src="https://user-images.githubusercontent.com/24585220/176938635-67562751-e122-44f4-a977-b4bd7361f0b6.png">
> It looks like the tendermint upgrade requires a cosmos-sdk upgrade as well. We're working on it for ag0.

**Comment by JimLarson** [comment]
We're not completely sure that the upgrade will fix it - check #validator-peer-support on Discord.

**Comment by JimLarson** [comment]
Obsoleted by #5773
