### ISSUE TITLE
remove makeNotifierFromAsyncIterable from vat-timer

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5709]
## What is the Problem Being Solved?

It's a "hot notifier" in the updater is driving the changes instead of the client. In a _cold_ notifier the client asks for the next update and the notifier figures out what to do. Is doesn't any activity at all until the client calls next() again.

## Description of the Design

Most of the uses of `makeNotifierFromAsyncIterable` take subscriptions so they'll be converted in https://github.com/Agoric/agoric-sdk/pull/5695 to use the new function for those cases.

These two don't:

https://github.com/Agoric/agoric-sdk/blob/cafa284c7d13d6ad520e34f11c9e53e0aa55f9f7/packages/SwingSet/src/vats/timer/vat-timer.js#L66-L73

https://github.com/Agoric/agoric-sdk/blob/cafa284c7d13d6ad520e34f11c9e53e0aa55f9f7/packages/zoe/tools/fakePriceAuthority.js#L233-L256

@michaelfig suspects the latter may solve a leak so tagging this with 'performance'.

## Security Considerations
--
## Test Plan

--

**Comment by warner** [comment]
#5763 now tracks the zoe portion, this ticket now only tracks the swingset portion.

**Comment by warner** [comment]
I'll handle this as part of the #5668 rewrite of vat-timer/device-timer

**Comment by warner** [comment]
The new vat-timer [implements the Notifier API directly](https://github.com/Agoric/agoric-sdk/blob/130feae4b0341bd8ea17569837376481dfa82f1b/packages/SwingSet/src/vats/timer/vat-timer.js#L789-L844), without using `makeNotifierFromAsyncIterable`. It implements the Iterable API directly too. The memory usage should be proportional to the number of unresolved Promises fetched by clients with `getUpdateSince()` and `next()`, respectively.
