### ISSUE TITLE
fix swing-store "unawaited promise" warnings

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5729]
## What is the Problem Being Solved?

My CI runs are reporting two Promises that aren't being `await`ed in swing-store:

https://github.com/Agoric/agoric-sdk/blob/d07a5025ab4fe5ef9f6008fbb8150e6e5c50154b/packages/swing-store/src/swingStore.js#L273

https://github.com/Agoric/agoric-sdk/blob/d07a5025ab4fe5ef9f6008fbb8150e6e5c50154b/packages/swing-store/src/swingStore.js#L288

If I'm reading this right, our new LMDB library returns a Promise for the write operations `db.put()` and `db.remove()`, and our swing-store layer is dropping that Promise.

@mhofman You helped us make the shift to `lmdb-js`, could you take a look at this? It might be might be trivial or it might be serious: does this API mean that we're supposed to wait for the Promise to resolve for something? I'd expect the `put` to just add the change to a txn buffer (synchronously), and then it'd be `db.commit()` that returns a Promise which doesn't resolve until everything was safely flushed.

If the put/remove Promise means something else, it might be safe to slap a `void ` on it, to silence the warning.

## Security Considerations

I think it's unlikely, but if the `db.put()` Promise somehow needs to be honored beyond/in-addition-to what we do in `commit()`, this could cause DB corruption if there's a race somehow.

## Test Plan

None, just look at CI results to see that the warning goes away.

**Comment by mhofman** [comment]
Correct, `void` is sufficient as within a transaction, `put` and `remove` will simply record in the txs, and `lmdb` guarantees that subsequent synchronous `get` will read from the transaction buffer.

**Comment by warner** [comment]
Why does it return a Promise? Oh.. does that promise fire when the enclosing txn finally retires?

**Comment by mhofman** [comment]
Right, the promise settles once the transaction does.
