### ISSUE TITLE
bootstrap method to stash object/device refs for use by CORE_EVAL

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5740]
## What is the Problem Being Solved?

As @FUDCo and I were try to think through upgrade scenarios, it occurred to us that we might some day need to add a new device to the running (chain-side) kernel. Maybe a "timer v2" with new features, or some new sort of storage thing.

We can imagine adding code to the kernel to many it possible to create a new device post-initialization, and some cosmic-swingset code that triggers at a particular block height to call some `controller` APIs. This code could synthesize the kref for the new root device node, and then use `controller.queueToVatRoot()` to send it into the bootstrap vat.

But we'll need something in the bootstrap vat to receive this reference (as a vref). We already have the CORE_EVAL "Big JS Hammer" upgrade mechanism, which is a bridge-device message that supplies JS code to be evaluated in a powerful context. But CORE_EVAL only gets a string (and the bridge device can only provide a string). So we need a way for the CORE_EVAL code to access vrefs that we invent and deliver from elsewhere.

## Description of the Design

I'm thinking we add an extra method to our `vat-bootstrap` which just takes its arguments and stashes them in a local `let` binding, then make sure this binding is in scope for the CORE_EVAL evaluation. Alternatively, create a `Map` or something, have the new method populate/`set()` things in it, and include the Map in the endowments of CORE_EVAL.

Then, if/when we invent something that must be delivered as krefs, our upgrade process does:
* create new kref
* `controller.queueToVatRoot('bootstrap', 'stashThing', capdata(newKref))`
* wait for that to be delivered
* use the Big JS Hammer to evaluate code which references the stash and uses the new facilities somehow (maybe distribute it to some new vats or something)

## Security Considerations

The Big JS Hammer is already super-powerful over the authorities that it is born with, but this would let us add new authorities (object refs) that come from even more powerful code (outside the kernel, with access to `controller` and whatever new kernel tools we invent later).

## Test Plan

A unit test that grabs a kref with `pinVatRoot()` on some secondary vat, then does `controller.queueToKref()` to the bootstrap vat, then uses the Big JS Hammer to retrieve the secondary ref from the stash and make sure it looks good.

cc @dckc @FUDCo @erights  (I don't know what Label to put on this: what do we use for code in `packages/vats` ?)

**Comment by dckc** [comment]
> what do we use for code in `packages/vats` ?

**cosmic-swingset** seems close enough.
