### ISSUE TITLE
Upgrade ag0 to safe version of ibc-go

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#5773]
## What is the Problem Being Solved?

Current ag0 uses ibc-go v2.0.2, which is marked as "do not use" because of a security issue. Gaia v6.0.X all also use versions of ibc-go which should not be used. We need to use an ibc version that is thought to be safe.

## Description of the Design

We'd like to avoid a novel combination of component versions, and if we're upgrading to a new major release, we might as well upgrade to the latest stable version of that major release. This suggests upgrading ag0 to match gaia v7.0.2 and its component versions.

We also need to make sure that agoric-sdk/agd are similarly upgraded.

## Security Considerations

Targeted versions of all dependencies should be checked for security notifications.

**Comment by arirubinstein** [comment]
let's call this `agoric-upgrade-7`

**Comment by dckc** [comment]
some additional context: https://commonwealth.im/agoric/discussion/6256-update-2-root-cause-identified-for-node-restart-issues-next-steps-for-improving-network-stability-etc?comment=26366

**Comment by JimLarson** [comment]
Created #5870 for the upgrade of agd, so this can be closed when ag0 is upgraded.

**Comment by JimLarson** [comment]
Closed by https://github.com/Agoric/ag0/pull/16
