### ISSUE TITLE
Invitations are missing on instagoric using the default propsals

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#5783]
## Describe the bug
Invitations are missing on instagoric using the default propsals.  This was working but seems to be broken with the latest 44c34cbdf936e86a8872622acb0e5c733f927f75

## To Reproduce
1. Stand up instagoric
2. no zoe invites in the ag-solo-manual-0 are received

## Expected behavior
zoe invites should be populated

https://github.com/Agoric/instagoric/blob/main/bases/shared/resources/economy-proposals.json

**Comment by dckc** [comment]
@turadg I wonder if this is a consequence of smart wallet integration in #5701 . I'm struggling to recall how we resolved the conflict between ag-solo wallets and on-chain smart wallets. I think it was something like "don't do that" but did we provide a way to avoid it?

**Comment by dckc** [comment]
Closing this as a consequence of merging #5806 is a bit optimistic; please do re-open it if end-to-end testing doesn't agree, @arirubinstein .
