### ISSUE TITLE
[story] Oracle operators can send updates to PriceAuthority running on chain

### ISSUE THREAD

**Issue by dtribble** [Agoric/Agoric#5791]
Chainlink operators provide the Agoric price feeds. We want to make that as easy as possible. (Idiomatic for Chainlink and for Agoric.) We need a way to wire them together.

## What is the Problem Being Solved?

From @jacquesvcritien of the oracle team:
> The old setup consisted of an ag-solo, an [external initiator](https://github.com/smartcontractkit/external-initiator), a Chainlink node an [external adapter](https://github.com/thodges-gh/CL-EA-NodeJS-Template). The ag-solo would have the logic running on it, holds state and it would initiate new jobs by calling the external initiator which triggers a job on the Chainlink node. The result of this job is sent to the external adapter which replies back to the ag-solo to push on chain. The issue with the ag-solo was that its state was not recoverable and we saw it breaking down too often, causing node operators to constantly having to reset their setups and recreate oracles. 
>
> Due to this, Michael had suggested that I build a middleware (Node.JS script which runs with agoric run) which replaces the logic on the ag-solo, the external initiator and the external adapter. This would keep the state of the last runs and prices, submit jobs every minute to the chainlink node, receives back the result from the chainlink node and submits the result on chain if there was a change in price which exceeds a certain threshold. This middleware is ready, however, Michael had also told me that in order for this middleware to communicate with the chain directly, there was some additional software which was being built by himself/Agoric team. I do not know the exact details about the status and the specific details of this missing piece. However, if I am not mistaken, I remember Michael mentioning that it had to do with `cosmJS` if that helps. Therefore, the final missing piece is a piece of code which allows this middleware to be able to submit the price to a price authority.

This is critical for future oracles joining the network.

## Description of the Design

TBD how to submit a price to the price authority.

Depends on Agoric run scripts having access to the cache in the smart wallet. We need the caching layer to behave properly with off-chain data. Currently it's a transaction to read the cache for a given value. We need the state of the cache to be exposed as a chain storage node. (Cache needs to expose its data off-chain.)  https://github.com/Agoric/agoric-sdk/issues/5868

Design requirements:
- price info transactions are different from other Cosmos transactions (like on-chain wallets, other routes into the chain than the ag-solo)
- fit the smart wallet transactions model (where we already have solutions for signing and legibility)
  - contain collection of arbitrary objects (ocaps) you can send messages to

1. Get a reference to the smart wallet for the given casting client
2. Send it a message to update the price for this reference (that is somehow named in the wallet, a petname or some other kind of name b/c pet names should be private (not on chain or hard-coded in scripts). 
3. ?? exchange the 

We pass out invitations (for offers) to the Oracle Providers and they distribute to wherever they need to get. If the provider puts the those offer results into its cache, then the script can indicate how to lookup the price info (USD brand, ATOM brand, price ratio) and provide all that's needed to publish. 

## Test Plan

**Acceptance criteria**
- [x] CLI to use a smart wallet to submit a price update
- [x] oracle operator after obtaining price info in a CL node can transit the result onto the chain (send updates to the price authority)

**Comment by dckc** [comment]
I'm not sure #6499 closes this. It provides a configuration where Oracle operators can send price updates, but that configuration is for testing, not for production use. I'm inclined to leave this open, for planning purposes.

**Comment by turadg** [comment]
I understood this ticket to be so that partners could build integrations. That's what the estimate was based on and that's what was completed.

I accept repurposing this ticket as a production story. Since that's new I've removed my estimate and assignment.

**Comment by dckc** [comment]
another option is to update the title / description to match "partners could build integrations"

**Comment by turadg** [comment]
Ok, I'll do that. That is the ostensible "Problem being solved." The other requirements will be driven by the partners.
