### ISSUE TITLE
Inter Protocol contracts upgradable

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5795]
For Pismo release the requirement was [reachably durable](https://github.com/agoric/agoric-sdk/issues/4983). For the Vaults Release we need upgradability. That requires:
- an automated test for each contract, like the one for coveredCall
- https://github.com/Agoric/agoric-sdk/issues/7562

This ticket is for the former. Here is the state of inter-protocol contracts as of 2023-05-04, on which this ticket was closed:

| filename | status | note |
| -------- | ------ | ---- |
| stakeFactory.js | irrelevant | out of release |
| feeDistributor.js | nondurable | "cron job" with no important state. can terminated and replaced at will. |
| auctioneer.js | reachably durable | if we need to upgrade we'll write a `prepare` that can pull out the state | 
| econCommitteeCharter.js | upgradable, untested | worst case we re-invite the EC (see also `committee.js` durable facets in https://github.com/Agoric/agoric-sdk/pull/7593 )  |
| fluxAggregatorContract.js | [upgrade tested](https://github.com/Agoric/agoric-sdk/tree/9bbad051a217fcc84a363be84069481ff4b4a011/packages/inter-protocol/test/swingsetTests/fluxAggregator) | 
| assetReserve.js | [upgrade tested](https://github.com/Agoric/agoric-sdk/blob/9bbad051a217fcc84a363be84069481ff4b4a011/packages/inter-protocol/test/swingsetTests/reserve/test-assetReserve-upgrade.js) 
| psm.js | [upgrade tested](https://github.com/Agoric/agoric-sdk/tree/9bbad051a217fcc84a363be84069481ff4b4a011/packages/inter-protocol/test/swingsetTests/psmUpgrade) |
| vaultFactory.js | [upgrade tested](https://github.com/Agoric/agoric-sdk/blob/9bbad051a217fcc84a363be84069481ff4b4a011/packages/vats/test/bootstrapTests/test-vaults-upgrade.js)

**Comment by dckc** [comment]
Let's reconcile the bundles in https://github.com/Agoric/agoric-sdk/blob/6653-vats-pkg-upgrade/packages/inter-protocol/scripts/init-core.js#L42 with the contents of this epic; either remove stuff (like AMM) or add tasks.

(discussion with @warner )
