### ISSUE TITLE
Governance for Zcf contract pause 

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#5796]
## What is the Problem Being Solved?

#5749 added the ability to pause processing of invitations. Currently that functionality is accessible via zcf. This is minimally legible, in that access to the functionality is visible, but each contract would have to individually manage updating the list.

## Description of the Design

The zcf function should be handed off to governance, and general support should be added to the governance API so the electorate that governs the contract can shut things down when necessary.

## Security Considerations

Standard legibility and POLA concerns.

## Test Plan

TBD

**Comment by dckc** [comment]
For the Agoric Econ Committee to pause contracts, I think that power has to be added to [econCommitteeCharter.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/run-protocol/src/econCommitteeCharter.js).

_Is this in scope here? If not, please either make a separate issue or let me know that I should._

**Comment by Chris-Hibbert** [comment]
That is in scope. Thanks for including the link.

**Comment by dckc** [comment]
as we discussed, `econCommitteeCharter.js` should be the one to set quorum and perhaps constrain deadline. Some requirements shopping is in order.

meanwhile, having `voteOnParamChanges` only support `QuorumRule.MAJORITY` seems like the wrong coupling.
