### ISSUE TITLE
Zcf contract pause list for an instance should be visible

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#5797]
## What is the Problem Being Solved?

#5036  added the ability to pause processing of some invitations of a  contract. The block list should be visible.

## Description of the Design

Add a method to Zoe, so those who have the contract instance can find out.

## Security Considerations

This is a legibility issue for the contract's clients

## Test Plan

standard thorough tests.

**Comment by dtribble** [comment]
And it should be controlled by governance.

**Comment by Chris-Hibbert** [comment]
Completed by #6037
