### ISSUE TITLE
Possible use of relative time (delay) where absolute time is needed

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#5810]
https://github.com/Agoric/agoric-sdk/blob/dbdd77861de4f8602c796277f243bdb9fa02a057/packages/zoe/tools/manualTimer.js#L189

Noticed while working on https://github.com/Agoric/agoric-sdk/pull/5809

**Comment by Chris-Hibbert** [comment]
It's a bug.  If it doesn't get fixed in #5821, ([comment](https://github.com/Agoric/agoric-sdk/pull/5821#discussion_r930256043)) we should fix it. I'll be surprised if more than a couple of tests need to be adjusted when we do that.

**Comment by Chris-Hibbert** [comment]
Fixed in #5821
