### ISSUE TITLE
Turn on Cosmos message admission fee before launch

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5817]
To prevent spam DDOS attacks, we must turn on Cosmos message admission fees before launch.  

Ideally, we will accept multiple token types: uBLD, uIST, or even uATOM.

We should  roll this out on Ag0 some time ahead of launch so people get used to providing it.

**Comment by Tartuffo** [comment]
@arirubinstein and @JimLarson please discuss and see who will be primary on this.

**Comment by dckc** [comment]
**possible-post-launch** depending on #4654

**Comment by dckc** [comment]
I gather @warner and @michaelfig are looking at this in the context of overall system message flow and cost recovery.

**Comment by dckc** [comment]
I gather the plan is to charge for WalletAction like we do for DeliverInbound.

**Comment by dckc** [comment]
I'm struggling to verify that `/agoric.swingset.MsgWalletSpendAction` results in fees being charged.

I don't understand why this transaction went thru with zero fees in the signed transaction; no IST was deducted.

chainId | agoricollinet-23 |   |   |   |  
-- | -- | -- | -- | -- | --
txhash | AD683EF922FCAE915335E4832D7B0D7B5669294C4BAA36CC5C31D07C4369B372 |   |   |   |  
status | Success |   |   |   |  
height | 42866 |   |   |   |  
timestamp | 2022-09-05 11:10 |   |   |   |  
gas | 111069 | / | 200000 |   |  
fee |   |   |   |   |  
memo |   |   |   |   |  
timeout_height | 0 |   |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  
@Type | /agoric.swingset.MsgWalletSpendAction |   |   |   |  
Owner | agoric1ggkanx6sv492tr3j2j4lf8kvlw9vtutwgr2fhn |   |   |   |  
Spend_action | { "type": "acceptOffer", "data": { "id": "1662394157180", "instancePetname": "instance@board05311", "requestContext": { "dappOrigin": "unknown", "origin": "unknown" }, "meta": { "id": "1662394157180", "creationStamp": 1662394157180 }, "status": "proposed", "invitationMaker": { "method": "makeWantStableInvitation" }, "instanceHandleBoardId": "board05311", "proposalTemplate": { "give": { "In": { "pursePetname": "AUSD", "value": 200020000 } }, "want": { "Out": { "pursePetname": "Agoric stable local currency", "value": 200000000 } } } } } |   |   |   |  
  |   |   |   |   |  
  | length | 540 |   |   |  

chainId	agoricollinet-23				
txhash	[AD683EF922FCAE915335E4832D7B0D7B5669294C4BAA36CC5C31D07C4369B372](https://ollinet.explorer.agoric.net/agoric/tx/AD683EF922FCAE915335E4832D7B0D7B5669294C4BAA36CC5C31D07C4369B372)				
status	Success				
height	[42866](https://ollinet.explorer.agoric.net/agoric/blocks/42866)				
timestamp	2022-09-05 11:10				
gas	111069	/	200000		
fee					
memo					
timeout_height	0				
					
					
@Type	/agoric.swingset.MsgWalletSpendAction				
Owner	agoric1ggkanx6sv492tr3j2j4lf8kvlw9vtutwgr2fhn				
Spend_action	{ "type": "acceptOffer", "data": { "id": "1662394157180", "instancePetname": "instance@board05311", "requestContext": { "dappOrigin": "unknown", "origin": "unknown" }, "meta": { "id": "1662394157180", "creationStamp": 1662394157180 }, "status": "proposed", "invitationMaker": { "method": "makeWantStableInvitation" }, "instanceHandleBoardId": "board05311", "proposalTemplate": { "give": { "In": { "pursePetname": "AUSD", "value": 200020000 } }, "want": { "Out": { "pursePetname": "Agoric stable local currency", "value": 200000000 } } } } }				
					
	length	540
