### ISSUE TITLE
install Inter protocol defi contracts after boostrap using publishBundle

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#5819]
## Problem Statement?

Unlike the PSM contract, which can be considered part of the platform, vaults introduce defi considerations that motivate launching them as a separate governance action.

## Description of the Design

Somewhat like the RUN Protocol Preview (#5062), but use `publishBundle` (#4975) and hash bundles to avoid putting the full text of the bundles inside swingset messages.

## Documentation Considerations

A runbook seems in order, much like ...

 - [Runbook: RUN Protocol Preview · Agoric/agoric\-sdk Wiki](https://github.com/Agoric/agoric-sdk/wiki/Runbook:-RUN-Protocol-Preview)

See also:
 - https://github.com/Agoric/agoric-sdk/issues/7493

## Security Considerations

see also

 - #4280
 - #4395

## Test Plan

Note that the testnets/devnets we typically stand up lately using instagoric avoid this problem by using a swingset config (derived from `decentral-demo-config.json`) where the contracts get installed as part of bootstrap. So testing this involves

 1. start a chain _without_ the Inter protocol contracts
 2. Do enough governance to get the Vaults working
    1. generate proposals to install them (`agoric run inter-protocol/scripts/init-core.js`)
        - including any `add-collateral-core.js` proposals to add IBC assets to the VBANK and such. 
    2. submit the proposals using `agd gov submit-proposal swingset-core-eval ...` as in `cosmic-swingset/Makefile`
    3. vote on the proposals
    4. Exercise gov committee, Oracle invitations to set up the Vaults, Auction, etc.
 3. Verify that you can open a vault, get liquidated, etc.

optional goals:
   - static typing for coreProposals

cc @warner

**Comment by dckc** [comment]
## Do we really want to start the SwingSet VM without the Inter Protocol contracts?

Based on plans from April (#5062), the sketch above includes:
> 1. start a chain without the Inter protocol contracts
> 2. Do enough governance to get the AMM and Vaults working

but maybe it's simpler to combine those steps?

Combining them is the more well-trodden path in engineering. @michaelfig and I added `make scenario2-run-chain-economy` for use by @samsiegart and others. @arirubinstein integrated something analagous into instagoric. Doing them separately includes kludges such as this ticket is intended to address, as well as other aspects that have likely bit-rotted.

Doing them together is arguably simpler from a BLDer DAO governance perspective.

Other product launch considerations may apply. @Tartuffo I hope you'll help coordinate those.
cc @dtribble

**Comment by kriskowal** [comment]
@dckc, I believe this issue is solved by `agoric publish` or `agd tx swingset install-bundle` workflows. May I close this?

**Comment by dckc** [comment]
no; there's also all the bootstrapping to wire up `feeMintAccess` and such.

**Comment by dckc** [comment]
## pruning work-around from description

but let's keep it available for searching...


In the course of the RUN Protocol Preview (#5062), we ran into some (cosmos?) size limitation when installing the contracts using the normal technique of calling `E(zoe).install(bundle)` from a deploy script.

### Work-around: fragmentation and reassembly

We came up with [inter-protocol/scripts/deploy-contracts.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/scripts/deploy-contracts.js), which does fragmentation and reassembly:

 1. install [endo-pieces-contract.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/deploy-script-support/src/endo-pieces-contract.js), which is small enough to not need fragmentation
 2. use [installInPieces.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/deploy-script-support/src/installInPieces.js), which fragments bundles into modules and sends themto `endo-pieces-contract.js` for reassembly

## Description of the Design

Use `publishBundle` (#4975) and hash bundles to avoid putting the full text of the bundles inside swingset messages.

One part of the work-around that would be nice to keep is a resulting `E(home.scratch).get('installCache')` of the form
```
CopyMap<Hash,
            {
              sha512: string,
              installation: Installation,
              path?: string
            }>
```

But maybe that's rendered obsolete in favor of `chainStorage` stuff for installations?

**Comment by dckc** [comment]
## Which parts can/should be included in genesis/bootstrap?

 - starting the EC? We did for pismo
 - starting the Oracle network?
 - starting the PSM(s)?
    - at least one is needed for smart wallet creation

p.s. yes to all 3. In particular, re Oracles:

 - #6950

**Comment by dckc** [comment]
broke ground:

c21dea943 * origin/5819-launch-inter fix(devnet): omit vaults contracts from platform launch config

**Comment by dckc** [comment]
PSM prefixes config didn't land in #6645, did it?

**Comment by ivanlei** [comment]
This is no longer plan of record for the vaults release.

**Comment by dckc** [comment]
For reference, the BLD stakers have been invited to consider which way to go on this:

- discussion: [\[Signaling Proposal\] Update Inter Protocol by installing Vaults contracts during the Agoric Mainnet\-1b chain upgrade \- Governance / Signaling Proposals \- Agoric Community Forum](https://community.agoric.com/t/signaling-proposal-update-inter-protocol-by-installing-vaults-contracts-during-the-agoric-mainnet-1b-chain-upgrade/272)
- on-chain vote: [#32 [Signaling Proposal] Update Inter Protocol by installing Vaults contracts during the Agoric Mainnet-1b chain upgrade](https://bigdipper.live/agoric/proposals/32)
