### ISSUE TITLE
x/authz and x/feegrant don't support ledger signing

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#5825]
## Describe the bug

Our design to delegate to a non-interactive key (#4406) depends on using authz and feegrant. For ledger (#3628 ), this is only supported in yet-to-be-released versions of cosmos-sdk:

 - https://github.com/cosmos/cosmos-sdk/issues/11190 closed Feb 22
 - https://github.com/cosmos/cosmos-sdk/pull/11224

## To Reproduce
1. `agd tx authz grant ...`
2. result: error

_IOU more precise steps._

## Expected behavior
grant works so that we can, for example, send a `MsgWalletAction` using an ephemeral key.

## Platform Environment

https://github.com/Agoric/agoric-sdk/blob/dbdd77861de4f8602c796277f243bdb9fa02a057/go.mod#L7

## Additional context

 - #5761

**Comment by Tartuffo** [comment]
Gaia 8 will include cosmos-sdk 4.6 which fixes this.  Otherwise, we have to backport.

**Comment by Tartuffo** [comment]
May be solved by Gaia 8 (Rho)

**Comment by ivanlei** [comment]
This is no longer an issue. Resolved upstream and verified in Dec `23 on Agoric chain as part of ReturnGrant efforts.
