### ISSUE TITLE
UserSeat.getCurrentAllocations should be avoided in production code

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#5833]
https://github.com/Agoric/agoric-sdk/blob/35b68062f69dc84041b98f670572683b572aa29e/packages/zoe/src/contractSupport/zoeHelpers.js#L357

As explained at https://github.com/Agoric/agoric-sdk/pull/5826#pullrequestreview-1051462243 , this usage is likely not incorrect *only* because we know this happens only after the seat has been exited. The general availability of this method is a hazard ("footgun") likely to lead to bugs in production code.

Indeed #5826 renames this method to `getCurrenAllocationsJig` to emphasize that it should be used only for testing purposes. We use "Jig" elsewhere for similar purposes. For testing purposes, use of this specialized method is appropriate, 
   * because tests sometimes want to check whether the expected thing has happened with internal state
   * because tests run in isolation, where we're not concerned about arbitrary races caused by any other possible activity.

When access to this internal state would violate a security property, then we would need some special arrangement so *only* testing code can use it. In this case, there is no such security violation, and so this method can be publicly exposed with the cautionary name.

**Comment by Chris-Hibbert** [comment]
With #6362, there are no current uses in production. Unfortunately, there are quite a few in test, so we can't easily get rid of the method.

**Comment by erights** [comment]
@Chris-Hibbert assuming this is gone now, I'm closing. But please reopen if I'm missing something.
