### ISSUE TITLE
QA the wallet UX

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5840]
## What is the Problem Being Solved?

Wallet needs QA of the UX.

## Description of the Design

- Go through user flows and make sure there aren't any kinks. 
- Go through other docs of issues
  - [UX Issues (from Econ Testing)](https://docs.google.com/document/d/1Kho6aLrNaD-qxG7StOQXLSMPTZMHGHQLbV7x70jEEDk/edit#)
- Triage what needs to be fixed

**Comment by btulloh** [comment]
This is a link to a Google Doc where the Econ Testing team is tracking UX issues it runs into as it goes along.
https://docs.google.com/document/d/1Kho6aLrNaD-qxG7StOQXLSMPTZMHGHQLbV7x70jEEDk/edit#

**Comment by samsiegart** [comment]
I propose we close this since we launched now. We'll need some continuous QA process going forward that won't be constrained to a single issue
