### ISSUE TITLE
change priceAuthority Notifier to a Subscriber

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5853]
## What is the Problem Being Solved?

priceAuthority holds a Notifier internally, which requires complete history of notifications. 
https://github.com/Agoric/agoric-sdk/blob/0e8644a34f996242935d4a525c631ae32e1da462/packages/zoe/src/contractSupport/priceAuthority.js#L258

## Description of the Design

Use a prefix lossy Subscriber instead. Possibly change its external `makeNotifier` to `makeSubscriber`.

## Security Considerations
--
## Test Plan

--

**Comment by Tartuffo** [comment]
@michaelfig  pointed out that notifier has no history, subscriptions have history.  The subscribers are prefix lossy. we'll do this when we formally deprecate notifier.
