### ISSUE TITLE
Expose key Oracle economic data via subscription

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5854]
## What is the Problem Being Solved?

This data can be used in Blockchain Explorers and via sites like The Graph for the community to get key information about the state of the RUN Protocol components.

From [our meeting on Feb 22](https://docs.google.com/document/d/1HkNLG8Kmm9DV6XGxvZEGVWUtHli2OfkR5ph7Q77x3QE/edit#), here is the data we want to expose from the Oracle:

For each asset pair
- Aggregate price https://github.com/Agoric/agoric-sdk/issues/4652
- Source information (per oracle node operator) TBD
~Governance parameters~ there are none

**Comment by dckc** [comment]
splitting this out looks like a good idea; seems like it should inherit **MUST-HAVE** while we're at it, at least until we hear from @btulloh .

**Comment by turadg** [comment]
closing per @btulloh
