### ISSUE TITLE
Instagoric test of snapshot divergences

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#5856]
## What is the Problem Being Solved?

In order to close https://github.com/Agoric/agoric-sdk/issues/5330 we need to do a little more extensive testing than the current deployment CI job. While we can probably not formally prove that no other snapshot divergences exists, we can gain confidence through empirical testing.

## Description of the Design

Run an instagoric load test with:
- Randomly restarting validator nodes
- Nodes on different architectures (arm64 / x64)
- Swingstore tracing enabled to capture snapshot hashes across multiple validators and multiple restarts

## Security Considerations

Once we have enough confidence, we should be able to move the snapshot hashes into consensus (remove `local.` prefix) so that the snapshot contents can be shared more safely between validators as a step towards https://github.com/Agoric/agoric-sdk/issues/3769

## Test Plan

Execute instagoric test. Process swingstore trace with a variant of https://github.com/Agoric/agoric-sdk/blob/master/scripts/process-integration-swingstore-traces.sh

**Comment by arirubinstein** [comment]
For diversity's sake it's probably best to conduct this test in a devnet, or a small simulated unit test if possible that we can run on an independent vm as it would be usable across cloud providers and configurations.  Is this a path that is validated via normal testing route in ci/local dev?

**Comment by mhofman** [comment]
I don't believe CI / local dev can orchestrate multiple validator nodes on multiple architectures.

**Comment by arirubinstein** [comment]
Could we simulate divergence by using fixture snapshots and loading them in different architectures?

**Comment by Tartuffo** [comment]
Changing this to RC0, as I don't want to cut RC0 and _then_ find out this is a problem!

**Comment by mhofman** [comment]
FYI, I'm happy having this be a one of test at first, just to get an idea of where we stand. We don't need to automate this yet, or make it part of CI (a snapshot divergence check is done in the deployment CI job, but non-enforcing and for same architecture)

**Comment by ivanlei** [comment]
Per slack with @arirubinstein 
> We’ve tested restarting and the replay tool mathieu is working on would be a better test than adhoc validation.
