### ISSUE TITLE
Large scale Vaults and Liquidation test

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5863]
Steps:

1. Create 10,000 vaults.  - Does the platform handle this number of Vaults?
2. Ensure the AMM has sufficient depth.
3. Trigger a liquidation that effects half of the Vaults.  - Does the liquidation complete?

If that works, repeat with 100,000 Vaults.

**Comment by aj-agoric** [comment]
Closing as no longer planned.
