### ISSUE TITLE
Monitor Oracle providers, with alerting

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5869]

**Comment by dckc** [comment]
@btulloh notes that the Oracles are in the reliance set of the inter-protocol.

**Comment by ivanlei** [comment]
via @otoole-brendan in slack
>  this can be closed as it's not necessary. Simply Staking will own network health monitoring. Plus they shared their monitoring dashboard this morning which likely satisfies this ticket anyway
