### ISSUE TITLE
Translate capdata into flat JSON

### ISSUE THREAD

**Issue by gibson042** [Agoric/Agoric#5878]
## What is the Problem Being Solved?

External consumers should not be expected to work with complex structured data, especially when that structure is `@qclass`-heavy capdata.

## Description of the Design

Create a utility for converting capdata into flat JSON, e.g. from
```
{
  centralAmount: {
    brand: { '@qclass': 'slot', iface: 'Alleged: RUN brand', index: 0 },
    value: { '@qclass': 'bigint', digits: '1859152806' }
  },
  liquidityTokens: {
    brand: {
      '@qclass': 'slot',
      iface: 'Alleged: BLDPoolLiquidity brand',
      index: 1
    },
    value: { '@qclass': 'bigint', digits: '4455322155' }
  },
  secondaryAmount: {
    brand: { '@qclass': 'slot', iface: 'Alleged: BLD brand', index: 2 },
    value: { '@qclass': 'bigint', digits: '2159517880' }
  }
}
```
to
```json
{ "central": "1859152806", "centralBrandBoardId": "board0425", "centralBrandAllegedName": "RUN", "liquidity": "4455322155", "liquidityBrandBoardId": "board03125", "liquidityBrandAllegedName": "BLDPoolLiquidity", "secondary": "2159517880", "secondaryBrandBoardId": "board03523", "secondaryBrandAllegedName": "BLD" }
```

## Security Considerations

The utility should be written such that adopting it does not risk a significant increase to potentially vulnerable surface area (e.g. by installing a complex executable).

## Test Plan

TBD

**Comment by dckc** [comment]
How does this integrate with the rest of the system? Does it get added to each contract?

Oh! it's a completely outboard, post-processing widget? OK.
