### ISSUE TITLE
Create Cosmic Swingset IDL generated stubs npm package

### ISSUE THREAD

**Issue by kriskowal** [Agoric/Agoric#5881]
## What is the Problem Being Solved?

Clients interacting with the Agoric chain over RPC in JavaScript need generated IDL stubs.

## Description of the Design

The prevailing idiom is to publish an npm package with the generated stubs from the IDL, rather than compelling clients do this themselves. We’ve elected to use `protoc`, `ts-proto`, and `tsc` in concert so we have both code and TypeScript types. There is no solution that generates JavaScript with TypeScript style JSDoc.

## Security Considerations

None known by this author.

## Test Plan

It should be sufficient to verify that the generated stubs can be imported and we expect any bugs discovered to either amount to configuration or implementation of the protoc and ts-proto tooling. We will shortly be using these stubs in `agoric-cli` which should give us adequate coverage in practice.

**Comment by dckc** [comment]
Another customer for this is #4406
