### ISSUE TITLE
chain node crashed trying to delete missing XS heap snapshot

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5901]
@arirubinstein spun up a test network this morning, and one of the validators halted when it attempted to delete an XS heap snapshot that was already missing.

```
2022-08-05T16:28:36.603Z block-manager: block 242 commit
portHandler threw (Error#1)
Error#1: [{"errno":-2,"code":"ENOENT","syscall":"unlink","path":"/state/agoricloadtest-18/data/ag-cosmos-chain-state/xs-snapshots/132a8428be21e653646f484a8e4ea19370e3eaaac57715b1f61294747df3177c.gz"}]

  at Object.commitDeletes (packages/swing-store/src/snapStore.js:267:13)
  at async commit (packages/swing-store/src/swingStore.js:340:5)
  at async saveOutsideState (packages/cosmic-swingset/src/launch-chain.js:285:5)
  at async blockingSend (packages/cosmic-swingset/src/block-manager.js:170:9)
  at async portHandlers.<computed> (packages/cosmic-swingset/src/chain-main.js:232:16)
```

I'm guessing that the refcounting mechanism (the one that tracks which snapshots are in use and which are not) got confused, and it tried to delete a snapshot twice. I'm looking at the logs now.

**Comment by arirubinstein** [comment]
https://drive.google.com/file/d/1WJ8vuyuHxUywLZRk3VT2B8vCpSzrIaFH/view?usp=sharing

**Comment by arirubinstein** [comment]
kernel dbs: https://drive.google.com/file/d/1Lr_DPFPbEvaX-bQFIG5G68dVCeH7dTSD/view?usp=sharing

**Comment by warner** [comment]
It looks like v8-board wrote out two snapshots with identical contents (i.e. the state of the vat was either unchanged or had returned to its earlier state by the time the next snapshot was written):

```
% cat slogfile_1659714207.json |jq -c 'select(.type=="heap-snapshot-save" and .vatID=="v8") | del(.time, .monotime)'
{"type":"heap-snapshot-save","vatID":"v8","snapshotID":"665d8eeaa8ff3b599b42dc9524e132886f8e8d0b4d38f1c74c265dbdca3bad12","endPosition":{"itemCount":2}}
{"type":"heap-snapshot-save","vatID":"v8","snapshotID":"66fb1d8bdfae110b834284f38978ac5f6e37ed9316508530f0fcbe8f529a0cc8","endPosition":{"itemCount":202}}
{"type":"heap-snapshot-save","vatID":"v8","snapshotID":"132a8428be21e653646f484a8e4ea19370e3eaaac57715b1f61294747df3177c","endPosition":{"itemCount":402}}
{"type":"heap-snapshot-save","vatID":"v8","snapshotID":"132a8428be21e653646f484a8e4ea19370e3eaaac57715b1f61294747df3177c","endPosition":{"itemCount":602}}
{"type":"heap-snapshot-save","vatID":"v8","snapshotID":"18482bc2bb07238e63a502be675f0aeec87654bd9732b690756381b078590522","endPosition":{"itemCount":802}}
```

I bet the refcount code somehow assumes the vat's new snapshot ID is different than the previous one, and we weren't seeing this before because XS snapshots were not deterministic enough to return to the previous state.

Supporting evidence: in the stdout log, I see only one "XS snapshot written to (FILENAME).gz : 899907 bytes compressed, 3927895 raw" message during block 191, but the slogfile shows two separate `heap-snapshot-save` events. That implies that the other write experienced some sort of error.

**Comment by warner** [comment]
I found the bug: `vatKeeper` was assuming the new snapshot was different than the old one, because it marked the old one for deletion without comparing them for equality first. The current snapshot was deleted at the next `snapStore.commit()` (at the end of the block). Then after enough deliveries are made to that vat, we reach the threshold to make a new snapshot (which is different this time), which marks the old ID for deletion *again*, and now `commit()` will throw ENOENT because the old file doesn't exist.

The "XS snapshot written to" message wasn't printed because the second write computed the same hash as the first, so snapStore just deletes the duplicate tempfile without ceremony.

We've had this bug all along, but I bet it was masked by `xsnap` not producing deterministic snapshots, and I think this was the first big test we've done since that fix landed. Read-only deliveries or `bringOutYourDead` where there's nothing to do could manage to leave the object graph in the same state that it started in, and with a snapshot that's more closely tied to the live object graph (and probably less influenced by the loose free objects waiting to be collected), we're more likely to actually observe an unchanged snapshot hash.

PR #5904 should fix the vatKeeper bug and adds some more tests to exercise that case.
