### ISSUE TITLE
Enable bootstrap 'big hammer' to force upgrade a contract

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#5928]
## What is the Problem Being Solved?

Our main economic contracts are being written with reachable durability for RC0, though we believe they should be migrated to upgradable as soon as possible. This might mean on the path to MainNet 1, or it might mean shortly after. In order for us to be able to upgrade reachably durable contracts post-launch, we'll need a mechanism that can be invoked by a cosmos vote that would cause a contract to be restarted from a different installation.

## Description of the Design

The [coveredCall upgrade test](https://github.com/Agoric/agoric-sdk/blob/master/packages/zoe/test/swingsetTests/upgradeCoveredCall/test-coveredCall-service-upgrade.js) and the [ERTP service upgrade](https://github.com/Agoric/agoric-sdk/blob/master/packages/ERTP/test/swingsetTests/ertpService/test-ertp-service-upgrade.js) show that the mechanisms exists in the kernel and in Zoe. 

The crucial lines of the coveredCall upgrade scenario look like this

```
      const v3BundleId = await E(vatAdmin).getBundleIDByName('coveredCallV3');
      const upgradeResult = await E(instanceAdmin2).upgradeContract(v3BundleId);
```

So the script needs access to the instanceAdmin of the contract, and a replacement installation.

## Security Considerations

Many, but it'll be under the control of chain governance.

## Test Plan

Show that we can replicate the covered call upgrade?  Or any null upgrade.

**Comment by dckc** [comment]
@Chris-Hibbert I agree that based on the design above, this is done. If not, we'll find out in

 - #6006
