### ISSUE TITLE
swingset kernel queue needs O(1) storage format

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5932]
We currently store the kernel's run-queue as a single JSON-serialized array in `kvStore.get('runQueue')`. That makes inserting or draining N records O(N^2), and we don't have any backpressure or other mechanisms that would keep the N from getting too large to ignore.

I think it's time for us to improve this data structure. I've kinda been putting it off because the two-queues or "each vat gets an input queue and an output queue" work (#3465 and maybe others) would either overlap or obsolete it. But in today's meeting we agreed on a cosmic-swingset -side prioritization approach for MN-1 that won't require kernel changes. So the kernel situation isn't going to be improved by that work, and we need to improve it in other ways.

Fortunately the changes are pretty simple:

* each queue entry goes into a separate key, `runQueue-${entryNum}`
* two additional keys remember the number of the next available entry and the oldest populated entry
* shifting the oldest item from the queue requires three reads, a delete, and a write
* adding an item to the queue requires a read and two writes
* the code that keeps track of the size of the run queue (for `kernelStats`) should be double-checked to make sure it still works, but probably doesn't need many changes

I think the biggest part of the task is updating the handful of tests that assert things about the run-queue storage. I'd recommend writing a helper function that scans the kvStore and returns the same array that used to be in the single `runQueue` key.

**Comment by FUDCo** [comment]
This seems straightforward.

I think I'd put the head and tail indices into the same key, since they're small and often accessed together.  This would reduce the number of reads for a dequeue operation by one.

I note in passing that the set of deleted queue entries looks an awful lot like the transcript, which makes me wonder if there's some synergy there, but it's probably not a good use of our time to dig too deeply into that right now.

I think we just need to make a decision on priority for this.

**Comment by warner** [comment]
Yeah, it's sort of a "kernel transcript" instead of a per-vat transcript. Unlike vats, it's not sufficient to reconstruct the kernel state (although super-useful for analyzing causality).

The "synergy" you mention would probably manifest as using the `streamStore` to record the kernel transcript. I bet you're right, but I agree, not right now. We'd need to delete the old entries (we don't do that for vats, to support a future upgrade that needs to start from the very beginning). But I'm certain that by the time we get to an input+output queue-per-vat, we're going to want to put them in the `streamStore` (SQLite) rather than as a zillion little keys in the `kvStore`.

OT3H, the `streamStore` and `kvStore` have different commit points. We convinced ourselves that it's safe to put vat transcripts into `streamStore`, because the *length* goes into `kvStore` (so if we commit `streamStore`, but then crash before committing `kvStore`, the next incarnation will just ignore the extra transcript entry, and eventually overwrite it). We'd have to do something similar with the kernel run-queue, plus we'd have to be careful about when to delete the items (we can't commit a `streamStore` deletion before we commit a `kvStore` "oldest entry" number, which won't be until the next block).

So that will become a whole lot easier if we can merge both `kvStore` and `streamStore` into SQLite first.
