### ISSUE TITLE
make agoricNames available via chainStorage / RPC

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#5959]
## What is the Problem Being Solved?

The AMM UI needs to know the AMM instance's board id and should no longer have to use a signed, paid-for transaction to get it
https://github.com/Agoric/dapp-amm/pull/27/files/c72887833df707be00c424eef0d91706af0d0ff3#r945300148

## Description of the Design

Put `agoricNames` in chainStorage using the board marshaler; in particular: the `.entries()` of each `NameHub`.

## Security Considerations

none; `agoricNames` is already published.

## Test Plan

_I think @turadg is putting together testing tools for this sort of thing. IOU a pointer_

**Comment by turadg** [comment]
> putting together testing tools for this sort of thing

https://github.com/Agoric/agoric-sdk/pull/5948
