### ISSUE TITLE
Update agd to gaia Rho

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#5986]
## What is the Problem Being Solved?

Pick up latest features and bugfixes by upgrading ag0 to gaia 8.0 (Rho) when it's released.

In particular, pick up fix for #11190

**Comment by JimLarson** [comment]
Note: message from Robert Zeremba in cosmos-tech 2022-12-15 16:25:

Copying my message from Discord (was noting already about it during the call today, but now confirmed with simd):
If you are updating to 0.46 or 0.47-alpha then don't use new SoftwareUpgradeProposal. Use legacy one! It breaks ping pub explorer, and most likely other explorers. Is there anyone from mintscan or atomscan to verify? Would be good to ask  explorers to support the new gov/v1 alongside old gov/v1beta1 endpoint.
EDIT: *don't use* ANY NEW PROPOSAL type. I've just verified with custom proposals, and they also fail with explorer.

Details:
https://github.com/cosmos/cosmos-sdk/issues/14334

**Comment by ivanlei** [comment]
This issue represents an old need for Interchain Stack upgrades. These are now captured in issues using Interchain Stack versions and this issue which references `ag0` is out of date.
