### ISSUE TITLE
package for sdk-internal exports

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5992]
## What is the Problem Being Solved?

We have some exports that don't fit conceptually into any of our agoric-sdk packages. E.g. `objectMap`. Such utilities are so generic that in most codebases they'd be imported from NPM (e.g. Lodash). 

Sometimes we do pick an arbitrary package, which can result in awkward dependency graphs (e.g. [cycles](https://github.com/Agoric/agoric-sdk/issues/4645)). Improving those graphs requires refactoring to a new package, which causes a breaking change to the export set. It's also often another imperfect home because we don't have a home for basic utils.

We have in places resorted to importing in code without declaring the package dependency. There are 174 results for disabling `import/no-extraneous-dependencies`. Most are in test code for setting up Endo globals (including `VatData`). That may be best solved by https://github.com/Agoric/agoric-sdk/issues/5244 as a `devDependency`. This issue is for a package that's a `dependency`.

## Description of the Design

Make a new package that is obviously not part of the public API of Agoric-SDK and move non-public utilities there. To convey that it shouldn't ever be depended on not to break from one release to another, it should never reach 1.0 which in semver means no guarantee. By Hyrum's Law someone will import it anyway and depend on that. It would still be better than the status quo in which we export from packages that are declared to be part of the SDK API. (Even when they aren't at the top level, many are available by deep exports https://github.com/Agoric/agoric-sdk/issues/5808) 

Some ideas for this package name:
- `@agoric/internal`
- `@agoric/private`
- `@agoric/unsupported`
- `agoricutils` (à la https://www.npmjs.com/package/fbjs )

## Security Considerations
--
## Test Plan

--

**Comment by kriskowal** [comment]
What concretely do you wish to populate this package with?

**Comment by erights** [comment]
I've been accumulating some at https://github.com/Agoric/agoric-sdk/blob/markm-interface-guards/packages/store/src/utils.js as I need them. All of these are potentially useful to any hardened js programmer, though some are admittedly unusual. In any case, none of these are specific to the store package. The only reason I accumulated them there is it was low enough on the import graph that everything that needed any of these could import them. Not a great reason.

**Comment by erights** [comment]
Just looked them over. The only one that is compelling to move to somewhere more principled is `objectMap`. All the other are rather obscure things to want.

However, I am confident that once such a package exists, we will find other things that genuinely deserve being moved.

**Comment by kriskowal** [comment]
I would be amused to name a package `endoscore` or `endobar` but I’d insist, for the lack of tree-shaking in our little ecosystem, that we encourage importing the utility methods individually like `@endo/score/object-map.js`. The scope of the package would need to be similar in spirit: missing elements of the Hardened JavaScript standard library not particular to one use or another.

**Comment by turadg** [comment]
It would be great to have hardened Lodash and `@endo/score` sounds like a useful future feature for Endo. 

Meanwhile agoric-sdk development shouldn't be coupled to Endo's roadmap in that way. We have a use now for an internal utils package and https://github.com/Agoric/agoric-sdk/pull/6001 is a proposal for review.
