### ISSUE TITLE
resolve all floating promise warnings

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6000]
## What is the Problem Being Solved?

Since https://github.com/Agoric/agoric-sdk/pull/5495 we have tooling that will detect and warn on floating promises.

https://github.com/Agoric/agoric-sdk/commit/4a84690f226c2e20bce25629757de4113f79d931 disabled them in CI as too slow. We've elected to postpone [re-enabling them in CI](https://github.com/Agoric/agoric-sdk/issues/5788) until after launch. This is fine because we don't necessarily need the feedback on every run.

The problem at hand is that we have unhandled (floating) promises in master that may contain bugs. We've seen them _hide_ bugs by creating bugs in tests.

## Description of the Design

Before launch, handle all `no-floating-promises` warnings.

Tackle on a per-package basis by running,
```
NODE_OPTIONS='--max-old-space-size=8192' AGORIC_ESLINT_TYPES=true yarn lint:eslint
```

https://github.com/Agoric/agoric-sdk/issues/5535 is an example. Though note it used `scripts/lint-with-types.sh` which since 4a84690f226c2e20bce25629757de4113f79d931 is a misnomer; it's more `ci-lint.sh` because it handles splitting the lint job and configuration of whether type linting is enabled in CI.

## Security Considerations
--
## Test Plan

Running `AGORIC_ESLINT_TYPES=true yarn lint | grep @typescript-eslint/no-floating-promises` has no output.

**Comment by turadg** [comment]
More fodder for prioritizing this: https://gist.github.com/samsiegart/f74a97206d43cdb7c5095714f84136fc

**Comment by samsiegart** [comment]
[PR#7485](https://github.com/Agoric/agoric-sdk/pull/7485) will be merged soon.

Assigning back to @ivanlei to delegate remaining work

**Comment by kriskowal** [comment]
I’ve sunk all floating promise warnings except those in:
- [ ] zoe (118 cases, each a hard choice)
- [ ] swingset (linter does not halt or report—presumably too big)

**Comment by turadg** [comment]
This will be closed when this report is empty:
```
git grep -rl no-floating-promises packages | sed -r 's/packages\/([[:alpha:]-]+)\/.*/\1/'  |sort |uniq
```

**Comment by turadg** [comment]
Since #9416 all that's left is the Zoe package. https://github.com/Agoric/agoric-sdk/compare/6000-no-zoe-floating-promises has some work towards it.
