### ISSUE TITLE
Split `giveStable` and `wantStable` into separate invitations in PSM

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#6005]
## What is the Problem Being Solved?

Splitting `giveStable` and `wantStable` into separate invitations would make it possible for governance to separately pause the two operations

## Description of the Design

The underlying operations are already distinct. They're kind of smooshed together to make the current invitation.

## Security Considerations

No impact.

## Test Plan

I suspect there are already separate tests for adding stable and removing it.

**Comment by dckc** [comment]
re test plan - I'd like to see this tested in combination with the zoe pausing feature, including a plausible governance story. Thoughts on whether that's in or out of scope here? Is it cost-effective to build a unit-test? Or better to wait for e2e testing? I'd be happy to talk it over.

**Comment by Chris-Hibbert** [comment]
> re test plan  I'd like to see this tested in combination with the zoe pausing feature, including a plausible governance story. Thoughts on whether that's in or out of scope here? Is it cost-effective to build a unit-test? Or better to wait for e2e testing? I'd be happy to talk it over.

I'd like to see a separate issue for that.
