### ISSUE TITLE
Subsume local.agoric.com into wallet.agoric.app

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#6027]
We can make wallet.agoric.app provide the functionality, which is currently just to save a pointer in local storage to the user's desired wallet UI URL. We should also make wallet.agoric.app the default instead of localhost:8000, so most users won't have to change anything.

**Comment by samsiegart** [comment]
Estimating at 3 because we may need to figure out some PWA stuff along with this change

**Comment by turadg** [comment]
Quick fix is to default to wallet.agoric.app and leave local.agoric.com necessity for developers. But ideally we drop local.agoric.com so there's less attack surface.
