### ISSUE TITLE
bootstrap does not save adminFacets from startInstance etc.

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6034]
## Describe the bug

I was looking at some code with @Chris-Hibbert  `const { creatorFacet } = await E(zoe).startInstance(...)`

(meeting time.  IOU more)

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by Chris-Hibbert** [comment]
I'll let @dckc finish filling out the bug description, but bottom line for me was my observation that nearly all calls to `await E(zoe).startInstance(...)` during bootstrap should save `adminFacet`, `creatorFacet`, and probably `instance` and `publicFacet` somewhere.  Without `adminFacet`, econ committee won't be able to pause, upgrade, or manage parameters.

**Comment by Chris-Hibbert** [comment]
> Without adminFacet, econ committee won't be able to pause, upgrade, or manage parameters.

correction: The adminFacet is needed for upgrade, but the creatorFacet is sufficient to exercise the other governance powers.

Our current theory is that upgrade will be handled by the **big hammer** exercised by a cosmos-level vote. We need to make that upgrade power accessible; I think that would be a script in `inter-protocol/proposals/`.

**Comment by dckc** [comment]
We addressed the scope necessary for PSM-first in #6101.
