### ISSUE TITLE
PSM-first configuration throughput is sufficient

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6041]
## What is the Problem Being Solved?

The system should provide service to the market under a variety of conditions.

## Description of the Design

 - requests complete within... say... 30 sec on avg.
 - 100 requests per block peak
 - forseeable DOS risks are managed sufficiently

_further refinement in progress_

## Security Considerations

DOS aka resource-exhaustion risks and integrity risks.

## Test Plan

 - [x] #6004 
 - [x] #6033
 - ... _perhaps more_

cc @Tartuffo @rowgraus @warner @arirubinstein

**Comment by Tartuffo** [comment]
The perf is sufficient.
