### ISSUE TITLE
chainStorage indirects thru bootstrap vat for bridge device

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6053]
## Describe the bug

Not only does the walletFactory write its state 17 times per PSM trade (#6038 ), but each one goes thru both the `chainStorage` vat (v8) and the bootstrap vat (v1) on its way to golang and the IAVL tree:

![image](https://user-images.githubusercontent.com/150986/186573177-93786a83-cd6e-4308-805b-8b97cc3f829e.png)

## To Reproduce

1. start a local-chain with a SLOG_FILE
2. do a PSM trade
3. look at `setValue` and `toBridge` deliveries in the SLOG_FILE

## Expected behavior

The `chainStorage` vat has 1 job; we might as well give it the bridge device so that it can do that job by itself, without going thru the bootstrap vat.

## Platform Environment
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

ac01a326c (dc-boot-psm) chore(vats): keep smartWalletStartResult in bootstrap space

cc @warner @michaelfig

**Comment by dckc** [comment]
@michaelfig Does the `bridgeManager` need exclusive access to the bridge device? Or is it OK for both the bootstrap vat and the chainStorage vat to have it?

cc @gibson042

**Comment by dckc** [comment]
Hm. I gave it a try, but I don't know how to give access to `D` to the chainStorage vat.

**Comment by warner** [comment]
`vatPowers.D`
