### ISSUE TITLE
smart wallet state grows with each offer

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6065]
## Describe the bug

The published state includes a list of all offers, past and present.

## Expected behavior
that the offer is removed when:
- the offerResult does not support continuing offers (all PSM offers, but not vault creation)
- or the offerResult is an error (since you cannot continue that)
- then once the offer is exited, the state update is reported via subscription and the offer is deleted from the wallet

cc @warner @samsiegart @turadg @dtribble @michaelfig

**Comment by dckc** [comment]
we're seeing huge state writes. wallets _and_ payments are important to consider

**Comment by dckc** [comment]
@gibson042 helped me sketch a test to write large strings to the chainStorage vat:
https://github.com/Agoric/agoric-sdk/blob/dc-wallet-prune2/packages/vats/test/swingsetTests/flatPerf/test-chainStorage-growth.js

**Comment by turadg** [comment]
@dckc do we know that 6095 solved the problem?
