### ISSUE TITLE
Create `agoric publish` command

### ISSUE THREAD

**Issue by kriskowal** [Agoric/Agoric#6087]
## What is the Problem Being Solved?

For PS0 launch, we can’t rely on `deploy` scripts since they depend on `ag-solo`. The [steps for proposing upgrading a contract](https://github.com/Agoric/agoric-sdk/issues/6086) would be considerably simplified with commands that will create and publish bundles.

## Description of the Design

- `yarn bundle-source --to-json bundle-cache/ contract/src/contract.js contract` would generate a JSON bundle that is suitable for verifying the resulting hash or publishing the resulting artifact in `bundle-cache/bundle-contract.json`.
- `agoric publish bundle.zip` would queue an SwingSet InstallBundle transaction and watch for the casting of the success or failure. That will produce a JSON hashed bundle suitable for passing to `zoe~.install` in a governance script.

**Comment by Tartuffo** [comment]
@Chris-Hibbert: If the tools can be added without the ability to upgrade a contract as a prerequisite, then they don't have to be in PS0 RC0.
@kriskowal: The tools would not require a contract change.

**Comment by kriskowal** [comment]
I’m recalling that @dckc put together a `bundle-source` command that is almost right for the governance case. We can either hack that to include an option to generate `json` instead of `js` or just make an `agoric bundle` that generates a single `json`. It would probably still be good for discoverability to have `agoric bundle` recapitulate `bundle-source`.

**Comment by kriskowal** [comment]
The `bundle-source` side of this story is best handled by https://github.com/endojs/endo/pull/1278 so I will not make an `agoric bundle`. The reason is that the bundler needs to be versioned with the dapp, and `agoric` is not necessarily paired with the dapp version, which could result in the generation of mismatching integrity hashes. #6147 will close this out when it lands.
