### ISSUE TITLE
Write a charter for multi-asset PSM param governance

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#6089]
## What is the Problem Being Solved?

`econCommitteeCharter` gives the econ committee the ability to wield governance powers. For the PS0 release, we need a corresponding charter for PSM-only.

The current theory is that it should use a continuing-invitation pattern rather than putting `voteOnFoo` methods in the publicFacet.

## Description of the Design

ContinuingInvitation that gives the ability to invoke `VoteOnParamChange` and `VoteOnPauseOffers`.

## Security Considerations

nothing out of the ordinary.

## Test Plan

just the usual.

**Comment by dckc** [comment]
How to introduce additional PSMs to the psmCharter?
ref. https://github.com/Agoric/agoric-sdk/pull/6142#issuecomment-1237629267

**Comment by Chris-Hibbert** [comment]
Done in #6142
