### ISSUE TITLE
Determine performance impact of enforcing Method Schemas

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#6098]
We need a perf measure comparing calling methods with and without input validation, to demonstrate that using the method schemas will not cause significant slowdown.

Ideally we'd do this w/o relying on end-to-end testing, because there is so much machinery involved it can be difficult to tell what the impact is.

**Comment by dtribble** [comment]
Initial plan:
- build a test to run a set of interface guard checks (iteratively)
- time it in nodejs
- for best fidelity with XS, use `NODE_OPTIONS=--jitless` 
- if optimization seems necessary, analyze with node profiling tools

**Comment by erights** [comment]
> We need a perf measure comparing calling methods with and without input validation, to demonstrate that using the method schemas will not cause significant slowdown.

This is not a sensible comparison. We should compare methods using interface guards for input validation vs methods that do input validation themselves with manually written code. No matter what the perf says, we do not have the option of exposing methods that are not doing input validation somehow.

**Comment by warner** [comment]
If you can make the code-under-test self-contained enough to survive `bundleSource`, then we can build a harness to run it under XS (but outside of a vat: no SwingSet). I think that will give us the most meaningful results.

**Comment by erights** [comment]
Regarding our desire to benchmark manual input validation vs pattern-based input validation, https://github.com/Agoric/agoric-sdk/pull/6114#discussion_r964116347 is an extreme but realistic example. All the input validation it did was mandatory.
