### ISSUE TITLE
verify by end-to-end test a contract on-chain can be upgraded

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#6099]
## What is the Problem Being Solved?

After the bulldozer, the only way to upgrade contracts will be through the AdminFacet's `upgradeContract()`. We don't have experience yet executing that in a live chain.

## Description of the Design

A chain integration test that does the following:
- bundle and install a buggy contract via a proposal
- use a smart wallet to demonstrate the bug
- bundle and upgrade to a contract that preserves the buggy one's state but fixes the bug
- use a smart wallet to demonstrate that the state is preserved and the bug is fixed

## Security Considerations

The relevant security here is the feeling of confidence that we can do something about it if a problem is discovered in a contract on a live chain.

## Test Plan

Demonstrate one contract being upgraded on a running chain.

**Comment by dckc** [comment]
@kriskowal help me try `agoric bundle` and `agoric publish` on ollinet, please?

**Comment by kriskowal** [comment]
> @kriskowal help me try `agoric bundle` and `agoric publish` on ollinet, please?

I’ll implement them right away https://github.com/Agoric/agoric-sdk/issues/6087

**Comment by dckc** [comment]
needs #5460 ; currently `agd query vstorage children published` doesn't include `installation`.

**Comment by kriskowal** [comment]
I’ve made a first attempt to upgrade PSM and encountered an error in upgradeContract behavior https://github.com/Agoric/agoric-sdk/issues/6207

**Comment by Tartuffo** [comment]
Moving this out of the critical path for the PSM-First launch.  We can side-grade the PSM to a new contract: 

1. Turn off the offer sides of the old PSM contact
2. Stand up a new PSM contract
3. Use JS Hammer to:
 a. mint a bunch of IST
 b. buy the USDC from the old contract
 c. put the USDC in a new PSM
 d. burn the bunch of IST
4. Tear down the old contract

**Comment by dckc** [comment]
we also have a couple other options:
 - upgrade the contract to a PSM with durable governance (#5200) 
 - restart the whole VM (#6644)

**Comment by turadg** [comment]
@dckc going to take this on because @kriskowal is out. I'm taking on a dependency,
- https://github.com/Agoric/agoric-sdk/issues/7466

**Comment by Tartuffo** [comment]
Congrats everyone!  This is a major accomplishment.
