### ISSUE TITLE
reallocate should guarantee that stage failure cannot happen

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6116]
https://github.com/Agoric/agoric-sdk/blob/757b887edd2d41960fadc86d4900ebde55729867/packages/inter-protocol/src/psm/psm.js#L192

**Comment by dckc** [comment]
also, consider factoring out `atomicReallocate`.

https://github.com/Agoric/agoric-sdk/pull/6102#discussion_r960760639

**Comment by Tartuffo** [comment]
Not required for PSO.

**Comment by erights** [comment]
Progress on #6116 at #6577 , where `stageMgr.commit()` replaces `zcf.reallocate(...)` and does guarantee that all staging are cleared, whether the commit succeeded or failed..
