### ISSUE TITLE
support new smart wallet in Wallet UI

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6127]
## What is the Problem Being Solved?

https://github.com/Agoric/agoric-sdk/pull/6084 changes the API for smart wallet. We need the Wallet UI to migrate to using it.

## Description of the Design

Requirements
- one purse per brand (until https://github.com/Agoric/agoric-sdk/issues/6126 )
 - UI should disable aspects for >1

Non-requirements
- supporting Smart Wallet and solo wallet at once
  - solo wallet will no longer have a UI; only smart wallet will

Ideas
- see whether only https://github.com/Agoric/agoric-sdk/blob/master/packages/wallet/ui/src/components/SmartWalletConnection.jsx needs changing
- explore using `coalesceUpdates` utility from the new wallet and a Flux-like "something changed" update pattern to propagate

## Security Considerations

--

## Test Plan

--

**Comment by Tartuffo** [comment]
Closed by #6134

**Comment by turadg** [comment]
@Tartuffo we left this one open until @rowgraus verifies it meets Product acceptance criteria. If you want to track that separately okay.

**Comment by Tartuffo** [comment]
> @Tartuffo we left this one open until @rowgraus verifies it meets Product acceptance criteria. If you want to track that separately okay.

Let's track testing separately.  There should be a user story issue for this @rowgraus
