### ISSUE TITLE
[requirement] smart wallets retain non-Cosmos assets through bulldozer upgrade

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6131]
## What is the Problem Being Solved?

The plan for https://github.com/Agoric/agoric-sdk/issues/6099 is to blow away and recreate the wallet contract. That requires that all assets to be held held at the Cosmos level so they can be re-associated with the JS purses.

Invitations and liquidity tokens, two essential assets in the Inter economy are not held at the Cosmos level and would be blown away by the upgrade mechanism in 6099. After PSM launch we need to support retention of these assets.

## Description of the Design

TBD

**Comment by dckc** [comment]
I see 2 kinds of non-cosmos assets to preserve:

## invitations

Seems straightforward to just resend invitations to the EC.

## smart wallet purchase price (10 BLD)

We have the list of accounts that have paid:
`agd --node https://main.rpc.agoric.net:443 query vstorage children published.wallet`

### chainStorage read is tricky

I thought it would be straightforward to add a read method to chainStorage, but in discussion with @warner I learned it's very much against the grain of an architectural direction for SwingSet. So whatever we want to read from chainStorage, we might want to do so in the go code that boots the JS world.

**Comment by dckc** [comment]
only non-cosmos things are invitations, which we can re-issue in the bulldozer upgrade
