### ISSUE TITLE
UI for getting a smart wallet

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6211]
## What is the Problem Being Solved?

UI for making a `provision-one` transaction.

## Description of the Design

?

(I can provide some references on back-end stuff)

## Test Plan

cc @samsiegart @rowgraus

**Comment by samsiegart** [comment]
@dckc If you could point me to some sample `JSON` message to sign for creating the wallet I can take it from there

**Comment by dckc** [comment]
as we discussed, the thing to use is `MsgProvision`, analagous to `MsgWalletSpendAction`.

https://github.com/Agoric/agoric-sdk/blob/7645df0e3c4b8ae901ea78e82b34a224ffaf1c2a/golang/cosmos/proto/agoric/swingset/msgs.proto#L87
