### ISSUE TITLE
potential await hazard in liquidateIncrementally

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#6220]
https://github.com/Agoric/agoric-sdk/blob/a1dedeae72908fda45afcb6038d76f8359adc8de/packages/inter-protocol/src/vaultFactory/liquidateIncrementally.js#L200

      // This await almost certainly does not do what was intended.
      // `oncePerBlock()` returns an async generator, not a promise,
      // and does nothing observably effectful to anyone not pulling on
      // the generator, which this code drops. AFAICT, this code is
      // equivalent to `await null;`. It imposes a non-delayed turn boundary
      // and does nothing else.

(Noticed while doing https://github.com/Agoric/agoric-sdk/pull/6219 )

**Comment by turadg** [comment]
Dropping from Vaults Release as we're not using liquidateIncrementally there. @Chris-Hibbert is replacing liquidation.

**Comment by turadg** [comment]
Obsolete as the module was removed
