### ISSUE TITLE
Await safety uncertain in inter-protocol/src/proposals/demoIssuers.js

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#6229]
https://github.com/Agoric/agoric-sdk/blob/a1dedeae72908fda45afcb6038d76f8359adc8de/packages/inter-protocol/src/proposals/demoIssuers.js#L628

The triage at https://github.com/Agoric/agoric-sdk/pull/6219 currently classifies this as

    // TODO FIXME This code should be refactored to make this
    // await checkably safe, or to remove it, or to record here
    // why it is actually safe.

Git blame shows @dckc as the one who should probably investigate this, so I'm assigning to them. Feel free to reassign as appropriate of course.

As the comments on #6219 indicate, this is not production code. It still needs to be fixed because it serves as an example that future production code may follow. But it is much less urgent. I am also omitting the "security" label for this reason.

**Comment by dckc** [comment]
I can see motivation to refactor this, but I don't see evidence of a bug.

If there's a bug, what steps can I take to reproduce it?

**Comment by erights** [comment]
My response is the same as at https://github.com/Agoric/agoric-sdk/issues/6230 , including deprioritizing if you're confident it is safe, even in the absence of explaining your refutation.

**Comment by erights** [comment]
With the simpler `await` safety rule, this issue is obsolete. Closing.
