### ISSUE TITLE
Await safety uncertain in SwingSet/src/controller/initializeSwingset.js

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#6231]
https://github.com/Agoric/agoric-sdk/blob/a1dedeae72908fda45afcb6038d76f8359adc8de/packages/SwingSet/src/controller/initializeSwingset.js#L333

The triage at https://github.com/Agoric/agoric-sdk/pull/6219 currently classifies this as 

    // TODO FIXME This code should be refactored to make this
    // await checkably safe, or to remove it, or to record here
    // why it is actually safe.
    //
    // As the default value of a destructuring, this `await` is bizarrely
    // conditional. It'll happen if `kernelBundles` is either absent or
    // undefined in `initializationOptions`, in which case we'll take a turn
    // boundary here. Otherwise, we'll continue into the subsequent code
    // synchronously. I could make this safe by introducing an extra turn
    // boundary, but for this code I'm scared to do that without understanding
    // the code better first.

Git blame shows @warner @FUDCo and @dckc as the ones who should probably investigate this, so I'm assigning to them. Feel free to reassign as appropriate of course.

**Comment by dckc** [comment]
I'm inclined to leave this to others. Let me know if you'd rather I stay involved.

**Comment by erights** [comment]
If @warner or @FUDCo pick this up, that's certainly adequate. Feel free to remove yourself from the assignees.
