### ISSUE TITLE
Await safety not yet fixed in swing-store/src/snapStore.js for `writeContents` argument function

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#6240]
https://github.com/Agoric/agoric-sdk/blob/293f88efbd01553cc5be4d29c435cd509302b2e7/packages/swing-store/src/snapStore.js#L265-L267

The triage currently at #6219 would fix it, with the explanation and code

```js
        // The `await` within `atomicWriteInRoot` above is only safe
        // when the second `writeContents` argument,
        // in all calls to `atomicWriteInRoot`, is a function whose calls cannot
        // synchronously throw. Even though this arrow function
        // seems to only call `filter`, which is a local async function and
        // therefore safe by itself, this arrow function also calls
        // `createGzip()`, which we cannot locally verify does not
        // synchronously throw. Thus, we made the arrow function async,
        // so that it cannot throw regardless. This seems to be consistent
        // with its purpose, and with the likely assumptions the program
        // author made when placing it here.
        //
        atomicWriteInRoot(baseName, async tmpGzPath =>
          filter(tmpSnapPath, createGzip(), tmpGzPath, { flush: true }),
        ),
```

Most of #6219 consists of commentary or cosmetic code changes, and so can be postponed until after PS0. But this is a safety fix. Whether we should cherry pick it, to get it in before PS0 depends on what the consequences are of not fixing it.

Assigning myself since I have the fix done in #6219 and would do the cherry picking if we decide to do that.

Git blame shows @gibson042 and @dckc as the ones who should probably investigate this, so I'm assigning to them as well. Feel free to reassign as appropriate of course.

**Comment by dckc** [comment]
@gibson042 is working on #6225 , which seems to overlap. Perhaps that's an opportunity to refactor/rewrite this code.

**Comment by erights** [comment]
With the simpler `await` safety rule, this issue is obsolete. Closing.
