### ISSUE TITLE
get loadgen exercising PSM trades too

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6258]
## What is the Problem Being Solved?

Our loadgen testing framework exercises the Vault and AMM contracts, which of course are not part of the PSM-only release. And it does *not* exercise the PSM contracts. #6257 is an error with our `pso-rc0` release when exercising the Vault and AMM contracts, which is interesting, but it would be much more interesting to exercise the PSM contract with the same sort of intensity.

So our loadgen testing framework should be updated to exercise the PSM contract too.

**Comment by mhofman** [comment]
We previously had https://github.com/Agoric/agoric-sdk/issues/6004 for this kind of loadgen, but that issue morphed into an instagoric based load test.

**Comment by turadg** [comment]
@warner is there a specific need to test load of PSM trades? TMK it's low load. Fair to rescope this ticket to "e2e test of PSM trading" ? Loadgen is our de facto e2e testing system, but it doesn't need to be. We can have a separate e2e for PSM trades that doesn't have the weight of longitudinal data collection.

**Comment by mhofman** [comment]
I'm not sure how an e2e test of PSM would look much different than the current loadgen CI. One thing I believe we'd like to keep exercising is the multiple validator consensus to make sure we don't have any divergence introduced by smart wallet and PSM paths. At that point, most of the cost of the loadgen CI infra is there.

**Comment by turadg** [comment]
It doesn't need to look different to be different. ;-)

One requirement for loadgen is that it can run on arbitrarily old states of the repo. A mere e2e test does not have that requirement. If it is expedient to build it by copying loadgen, that's fine.

This isn't to say that it must not be implemented on top of the existing loadgen. E.g. if it would mean a shorter CI cycle to include this in the existing "chain deployment test".

My question is to understand the requirements and gaps. Which I'm still not clear on. What e2e coverage of PSM trades do we have now in CI? What is the value in exercising the PSM contract "with the same sort of intensity" as loadgen does for the Vault and AMM?

**Comment by mhofman** [comment]
To be clear, the loadgen in CI is indeed an abus, and I'd be open to a dedicated e2e integration test. That said I'd also like for the loadgen infra to be exercised as an integration test to make sure it doesn't get broken. As you mentioned, the cost of running 2 separate integration tests may be prohibitive, so hopefully we can find a way to reconcile them.

Also the loadgen in CI does not actually produce much load, but instead performs 2 trades each of the vault and amm, and exits.

**Comment by turadg** [comment]
We now have dedicated e2e testing with the deployment upgrade tests so don't need to abuse loadgen in this way
