### ISSUE TITLE
Establish Relayers for Pismo Launch

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#6275]
Establish the following relayer connections:

- Agoric (main) to Cosmos Hub (main)
- Agoric (main) to Axelar (main)
- Agoric (testnet aka emerynet) to Axelar (testnet)
- Agoric (main) to Osmosis (main)
- Agoric (main) to Crescent (main)
- Agoric (testnet aka emerynet) to Cosmos Hub (testnet)

**Comment by dckc** [comment]
@Tartuffo @arirubinstein please confirm that the connection and channel ids are consistent between these relayers, the chain registry (for example [_IBC/agoric-cosmoshub.json](https://github.com/cosmos/chain-registry/blob/master/_IBC/agoric-cosmoshub.json)) and discussion in [#ibc-infrastructure](https://discord.com/channels/585576150827532298/1010261359184859271).

**Comment by Tartuffo** [comment]
Here are the initial channel mappings that @dckc was referencing above:

```
agoric <-> axelar:
channel-6 <-> channel-40
connection-11 <-> connection-50
07-tendermint-8 <-> 07-tendermint-68
agoric <-> cosmoshub:
channel-5 <-> channel-405
connection-8 <-> connection-649
07-tendermint-6 <-> 07-tendermint-927
agoric <-> osmosis:
channel-8 <-> channel-359
connection-13 <-> connection-1699
07-tendermint-10 <-> 07-tendermint-2184
agoric <-> crescent:
channel-7 <-> channel-22
07-tendermint-9 <-> 07-tendermint-25
connection-12 <-> connection-28
```

**Comment by dckc** [comment]
Well, those are mappings that we saw last Friday, Sep 30. I suspect the ones established earlier in the chain registry are the ones to use.

**Comment by Tartuffo** [comment]
Where are the ones in the earlier chain registry?

**Comment by dckc** [comment]
In https://github.com/cosmos/chain-registry/tree/master/_IBC the ones that include `agoric` are currently:

https://github.com/cosmos/chain-registry/blob/master/_IBC/agoric-cosmoshub.json
https://github.com/cosmos/chain-registry/blob/master/_IBC/agoric-crescent.json
https://github.com/cosmos/chain-registry/blob/master/_IBC/agoric-gravitybridge.json
https://github.com/cosmos/chain-registry/blob/master/_IBC/agoric-osmosis.json

currently = [827fd83](https://github.com/cosmos/chain-registry/commit/827fd832133dfce1c9dbebc69417e5f3d7285b0e) 4 days ago

**Comment by dckc** [comment]
Note chain-registry update [15e3365](https://github.com/cosmos/chain-registry/commit/15e3365f01777966cb22e96b73736e25e4d5918b) with updates to agoric-cosmoshub and the addition of agoric-axelar.
