### ISSUE TITLE
Validator guides for AgD, release notes

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#6276]

**Comment by dckc** [comment]
note that https://github.com/Agoric/agoric-sdk/wiki/Validator-Guide-for-Devnet is what the community has been trained with so far.

**Comment by dckc** [comment]
progress: i have the install part more or less done.

 - https://github.com/Agoric/agoric-sdk/wiki/ag0-to-agd-upgrade
 - https://asciinema.org/a/528403

next up: integrate https://github.com/Agoric/upgrade-test stuff (from #6421)

**Comment by dckc** [comment]
Hm... release notes... I wonder what belongs there.

re-iterate phased release
note 3rd party contract support is in a later phase

Regressions w.r.t. ag0:

 - #3769
 - #6455

Performance suggestions:

 - `TMPDIR` - #6248

Major Features:
 - #6211 
 - #6064
 - #6021 
 - #6007

**Comment by arirubinstein** [comment]
@dckc do we need to include information about the TMPFS?

**Comment by dckc** [comment]
TMPFS? Oh yeah... #6248

Darn; we didn't add `TMPDIR` to [docs/env.md](https://github.com/Agoric/agoric-sdk/blob/master/docs/env.md).

But sure... it can go in these release notes.

**Comment by dckc** [comment]
https://github.com/Agoric/agoric-sdk/issues/6455#issuecomment-1284549948 shows there's a bit more to do on https://github.com/Agoric/agoric-sdk/wiki/ag0-to-agd-upgrade

meanwhile, @jessysaurusrex and I did get [release notes](https://github.com/Agoric/agoric-sdk/releases/tag/pismoA-rc4) out.

**Comment by dckc** [comment]
Thanks, @jessysaurusrex , for finishing up https://github.com/Agoric/agoric-sdk/wiki/ag0-to-agd-upgrade-for-mainnet-1-launch
