### ISSUE TITLE
More than one PSM tab in the browser: support, don't allow, or give warning

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#6280]
## What is the Problem Being Solved?

Having multiple Wallet tabs open causes an infinite loop of CapTP messages.

## Description of the Design

Whatever fits into 3 points. If support, then go for it. But notifying the user is the only requirement.

## Security Considerations

TBD

## Test Plan

TBD

**Comment by turadg** [comment]
@rowgraus this is good ergonomics but doesn't hinder functionality so we decided this isn't a launch blocker. Can be a quick follow and could possibly get done in time.

**Comment by samsiegart** [comment]
Obsolete with latest improvements
