### ISSUE TITLE
Guide for non-technical users to govern PSM

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6281]
## What is the Problem Being Solved?

The economic committee are not all technical and will need detailed documentation on how to install the tools and use them to govern.

## Description of the Design

- Living documentation that can be amended easily
- Users can comment to request additional clarification
- Way to dry run to make sure they can handle any urgent votes

## Security Considerations

--

## Test Plan

Run through with @rowgraus and @jessysaurusrex . 
Another run with an EC member?

**Comment by turadg** [comment]
WIP https://docs.google.com/document/d/1IvYMCaglcFhGoEAsvz_1HVKE-ZffJscnxXk5tp82vSQ/edit#

**Comment by turadg** [comment]
I've updated the doc with how to use https://github.com/Agoric/agoric-sdk/issues/6290

I'll leave this open until it has screenshots taken with a fresh account on devnet.

**Comment by dckc** [comment]
for reference: [Inter Protocol \- Econ Governance Guide](https://docs.google.com/document/d/14HFmCG9i7SfD38Ss5LNsd2WIKOYm1e-u1M2c1LFABYo/edit#heading=h.e0x1htytyn5)
