### ISSUE TITLE
PSM Deployment for Mainnet

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#6284]
## What is the Problem Being Solved?

Similar to #6283, we want to make installation of PSM in mainnet as easy as possible for our Validators.

## Description of the Design

Similar approach to #6283, bake in the bootstrapping of PSM, create the denoms for the tokens to be used in the PSM, bake in PSM Governance committee keys, etc.

Needs to set up the IBC denom for USDC, and any other denoms we plan to have in PSM at launch.

**Comment by Tartuffo** [comment]
@rowgraus we are blocked on this because we need to know what IBC denoms we should include at launch of PSM.  This will be assigned to @dckc once @rowgraus has listed the denoms.

**Comment by dckc** [comment]
For Axelar, I suggest:

```
          {
            "keyword": "USDC_axl",
            "proposedName": "Circle's stablecoin on Axelar",
            "decimalPlaces": 6,
            "denom": "ibc/295548A78785A1007F232DE286149A6FF512F180AF5657780FC89C009E2C348F"
          },
```

The denom is from a transaction I made:
https://axelarscan.io/tx/9126C3AEE3D561C3070EF18A6C172CBECC2ED6F04E0F881C48EC4B8C5CDC1740 -> https://bigdipper.live/agoric/accounts/agoric1nrmj0tufmckkwh4zjvmttrvn5p7e9c5aweupkh

decimalPlaces is 6 according to what I saw on etherscan while working on that transaction.

The **suggestedName** is from the chain registry:
https://github.com/cosmos/chain-registry/blob/3d6d63055be68a1f4cbf25b62ca729a6c9c50081/axelar/assetlist.json#L28


The keyword is similar to `USDC.axl` as used in Osmosis and crescent, but with `.` replaced by `_` to avoid  constraints from vstorage / chainStorage and Zoe:

```
2022-10-10T23:07:45.857Z SwingSet: ls: v8: Error#1: Path segment names must consist of 1 to 100 characters limited to ASCII alphanumerics, underscores, and/or dashes: USDC.axl

2022-10-10T23:07:48.434Z SwingSet: ls: v6: Error: keyword "USDC.axl" must be an ascii identifier starting with upper case.
...
 at assertKeywordName (.../zoe/src/cleanProposal.js:39)
 at forEach ()
 at cleanKeywords (.../zoe/src/cleanProposal.js:57)
 at storeIssuerKeywordRecord (.../zoe/src/issuerStorage.js:145)
 at storeIssuerKeywordRecord ()
 at makeZoeInstanceStorageManager (.../zoe/src/zoeService/zoeStorageManager.js:130)
```

**Comment by Tartuffo** [comment]
Blocked on getting econ committee into the bootstrap.

**Comment by dckc** [comment]
I verified trading Axelar testnet USDC for emerynet IST, end-to-end:

1. used axelar discord faucet to get some AXL and aUSD ([axelar testnet tx 943...](https://testnet.axelarscan.io/tx/943078E80082CB9F1B8CD5834ADE1F2975A895A91A572B50DEF0B0CB8B8092DD))
2. added axelar testnet to keplr (including a config tweak for aUSD)
3. used keplr to do an IBC transfer of 4 aUSD to emerynet (courtesy of Strangelove relayers)
4. made an emerynet `swingset.CoreEval` governance proposal: [9. Add Axelar USDC Parity Stability Module on agoric-emerynet-](https://emerynet.explorer.agoric.net/agoric/gov/9)
5. emerynet validators passed it (yay!)
6. the 4 USDC_axl showed up in my wallet, and USDC_axl showed up in the "select asset" control in psm.inter.trade
made a swap ([emerynet tx 081...](https://emerynet.explorer.agoric.net/agoric/tx/081877C46A77D9B0FB47B94AC4F6A515A6D38F34A8B26445F48945E3C88BA2B8))


keplr config tweak for step 2 using https://docs.axelar.dev/resources/keplr :
add `,{"coinDenom":"aUSD","coinMinimalDenom":"uausdc","coinDecimals":6}` to get:

```
{"rpc":"[https://axelartest-rpc.quickapi.com:443](https://axelartest-rpc.quickapi.com/)","rest":"[https://axelartest-lcd.quickapi.com:443](https://axelartest-lcd.quickapi.com/)","chainId":"axelar-testnet-lisbon-3","chainName":"Axelar Testnet","stakeCurrency":{"coinDenom":"AXL","coinMinimalDenom":"uaxl","coinDecimals":6},"bech32Config":{"bech32PrefixAccAddr":"axelar","bech32PrefixAccPub":"axelarpub","bech32PrefixValAddr":"axelarvaloper","bech32PrefixValPub":"axelarvaloperpub","bech32PrefixConsAddr":"axelarvalcons","bech32PrefixConsPub":"axelarvalconspub"},"bip44":{"coinType":118},"currencies":[{"coinDenom":"AXL","coinMinimalDenom":"uaxl","coinDecimals":6},{"coinDenom":"aUSD","coinMinimalDenom":"uausdc","coinDecimals":6}],"feeCurrencies":[{"coinDenom":"AXL","coinMinimalDenom":"uaxl","coinDecimals":6}],"gasPriceStep":{"low":0.05,"average":0.125,"high":0.2},"features":["stargate","no-legacy-stdTx","ibc-transfer"]}
```
