### ISSUE TITLE
Cosmos Upgrade Handler

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#6285]
## What is the Problem Being Solved?

To install Pismo on the chain, we need a stub upgrade handler that calls agoric-upgrade-8.

This helps drive the chain upgrade at a certain block height, even if the upgrade handler itself is empty.

**Comment by Tartuffo** [comment]
See: https://github.com/Agoric/ag0/wiki/Syncing-Up
And: https://github.com/Agoric/ag0/blob/Agoric/app/app.go#L669-L691

**Comment by JimLarson** [comment]
Closed by #6310
