### ISSUE TITLE
consensus failure due to build-host pathname sensitivity

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6298]
In today's kernel meeting, we realized that the `lockdown` and `supervisor` bundles (both created with `bundleSource({ format: 'getExports' })` and thus using `rollup`) are likely to embed the directory name of the original source tree, which of course varies from one machine to another (it would have `/home/warner/` on my machine, but not yours). These bundles are evaluated into the `xsnap` worker process, and the strings therein become part of the JS state.

That means, at the very least, the `xsnap` heap snapshots will differ between executions whose bundles were created on different machines. If you initialize your validator on machine A, it won't produce the same heap snapshot hashes as the ones from machine B. Even if you copy the state DB from A to B and then run both on B, they'll have different pathnames in their bundles.

Worse, the pathnames might be of different lengths, which means the strings used in stack traces/etc are longer, which means more memory must be allocated to hold them, which might cause organic GC to happen slightly earlier. That will turn into a syscall divergence, eventually.

I believe we currently catch this very early, because we write the full contents of these two bundles into the `kvStore` during `initializeSwingset()`, and we record an `activityHash` that includes all writes to the kvStore.

Apparently validators discovered that they get immediate consensus errors unless they unpack their source tree into a directory that matches the docker images that our CI uses, suggesting that this sensitivity already exists but has been worked around by the community.

We'd like to not be sensitive to those pathnames. The `EndoZipBase64`-format bundler (which does *not* use `rollup`) does not suffer from this problem, but we can't easily use it for `lockdown` and `supervisor` because that format requires more than a simple `eval` to load into the new `xsnap` worker. (The supervisor bundle includes the loader for `EndoZipBase64`, which makes it possible to deliver the vat bundle in that format, later).

@michaelfig said that @kriskowal has a plan for Endo to generate `getExport` -format bundles without `rollup`, which would remove these embedded directory names, and allow lockdown/supervisor bundles made on different machines to have identical contents. If we could switch to that today, we could (hopefully) remove this validator workaround.

Further work might yield `nestedEvaluate`-format bundles too, which would improve our debugging experience (we don't always get useful line numbers out of `getExport` format bundles) when we see problems in liveslots or the supervisor code.

**Comment by warner** [comment]
I took a quick look at the supervisor bundle from a recent investigation, and the last part says:

```
//# sourceURL=/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js\\n\",\"sourceMap\":\"//# sourceURL=/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js\\n\"}
```

So yes, it captured the `/usr/src/` directory that the code was unpacked into.

To check this locally, given a STATE directory with a `data.mdb` file (e.g. `~/.agoric/data/ag-cosmos-chain-state/`), use:
```
$ cd packages/SwingSet/misc-tools
$ node ./db-get.js STATE supervisorBundle | tail -c200
```

**Comment by kriskowal** [comment]
It’s been on the back of my mind that I should fully replace both `getExport` and `nestedEvaluate` with Endo’s bundler since that would remove Rollup from our supply chain and give us control over determinism. Since I wasn’t able to readily find an issue tracking that ambition, I’ve created https://github.com/endojs/endo/issues/1294 to track.

**Comment by Tartuffo** [comment]
@michaelfig to explore shortcuts to this.

**Comment by warner** [comment]
@turadg suggested looking at rollup's `makeAbsoluteExternalsRelative` option, although we may need a solution that doesn't involve a new Endo (`bundleSource`) release. We might do a hack within swingset to strip out the paths from our two bundles.

**Comment by warner** [comment]
@michaelfig : we build the `lockdown` and `supervisor` bundles during swingset initialization, here:

https://github.com/Agoric/agoric-sdk/blob/a75543df865af81674c8a139dcb3a1f4a9f4f333/packages/SwingSet/src/controller/initializeSwingset.js#L51-L68

Maybe we could compute `new URL('../..', import.meta.url).pathname` to learn the absolute path of the `packages/SwingSet` directory, and then use a regexp or two to strip that prefix out of the generated bundle's `.source` property? So instead of ending with:
```
r.handleItem);\n\nreturn module.exports;\n}\n//# sourceURL=/home/node/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js\n","sourceMap":"//# sourceURL=/home/node/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js\n"}
```

it would end with:
```
r.handleItem);\n\nreturn module.exports;\n}\n//# sourceURL=src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js\n","sourceMap":"//# sourceURL=src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js\n"}
```

What would that do to stack traces created by XS? Or are those already broken?

We might consider using `../../../..` instead, rooting the remaining path at the top of `agoric-sdk`, but I want this to keep working even when consumers use `@agoric/swingset-vat` as a standalone package, not from the monorepo.

**Comment by mhofman** [comment]
@turadg mentioned the [`makeAbsoluteExternalsRelative` rollup config](https://rollupjs.org/guide/en/#makeabsoluteexternalsrelative), but according to the docs, that should default to true, so we may be missing something.
