### ISSUE TITLE
how to prevent unbounded inboundQueue growth and excessive trade latency

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6306]
## What is the Problem Being Solved?

@arirubinstein did some testing and was able to fill the new `inboundQueue` with 15k PSM trades pretty quickly, with a moderate number of workers and fees. That amount of work could take hours or days to clear. Someone who submits a request while the queue is that full would see their cosmos txn get accepted into a block fairly quickly, but the trade wouldn't actually execute for a long time.

This is a basic queueing-theory problem: when things are slow, it should be first-come-first-served, but there will always be times when there is enough demand to cause delays. Our first question is to figure out what the desired experience is. When Alice submits a trade to a queue with N seconds/minutes/hours of work ahead of her, will her request be rejected immediately, be rejected later, be processed eventually (but maybe much later than she wants)? How much control does she get to chose between those outcomes? How much visibility does she get into her request's current status?

We're limited by existing implementation layers:
* a stateless/non-consensus "ante handler" is checked before accepting a message into the mempool
* the Tendermint layer uses arrival ordering to choose which txns get from the mempool into a proposed block (filtered, but not sorted, by max gas value, against a per-validator threshold)
* once accepted into a block, gas fees are always charged, but a given message might be executed (i.e. added to `inboundQueue`) or rejected (which ought to be detectable by clients, just as if they'd ran out of funds to pay for gas, or had some syntax error in their transaction)
  * a stateful/within-consensus form of the ante handler runs here and makes this decision
* our stateful ante handler has the ability to charge an "admission fee" when the messge is executed, based on whatever criteria we like

There are four basic categories of approaches we're thinking of taking, each with different user experiences under load.

* 1: allow the unbounded `inboundQueue`
* 2: cap `inboundQueue` at some fixed depth, perhaps one that corresponds to one hour of work. New txns continue to be accepted into blocks, but when the block is executed, they'd be rejected rather than being added to `inboundQueue`
* 3: charge an admission fee upon execution which increases as `inboundQueue.length` grows, maybe exponentially
* 4: compute that admission fee, but check the txn for a `maxAdmissionFee`, and either reject the txn or (charge fee and add to `inboundQueue`

### Unbounded Queue

Our existing unbounded `inboundQueue` has two downsides:
* the chain must store unbounded state (however we can safely assume this storage cost is basically covered by our admission fee)
* a given request's latency is unbounded: it will be proportional to the number of requests on the `inboundQueue` when their message was accepted into a block and then executed

The user experience is something like:
* look at the chain, see how long the queue currently is, decide to submit or not
* submitted txns hang out in the mempool for some amount of time before being accepted into a block
* once accepted, the message is added to the end of `inboundQueue`, which might be longer or shorter than it was when the user decided to submit it
* message then slowly works through `inboundQueue` until being processed

The user's message would always get processed eventually, but it could be days if the queue were really full, and the actual time can't be known until it gets past the mempool.

### Size-Limited Queue With Reject (second ante-handler only)

Option 2 causes block transaction messages to be dropped if `inboundQueue` is too full. The user experience is:
* look at the chain, try to guess your chances of success, decide to submit of not
* submitted txn hands out in mempool for some time, then gets accepted into block
* once accepted into a block, the block is executed:
  * some percentange of the time, the txn is rejected: gas fees are charged, but no trade happens
  * some other percentage of the time, the txn is accepted into `inboundQueue`, and is processed within an hour

### Size-Limited Queue With Reject (both ante-handlers)

@michaelfig pointed out that it isn't hard to make the first (non-consensus) ante-handler do this check too. This changes the experience to:
* submit a txn
* if the validator/node you submit it to currently has a full `inboundQueue`, the txn is rejected immediately, without being added to the mempool, and you get a fast error, and no gas fees are paid
* if it thinks it has space, the txn hangs out in the mempool for a while
* eventually it gets into a block, then gets executed (which costs you gas fees regardless of the outcome)
* a second check against `inboundQueue.length` is made
  * sometimes the txn is rejected
  * sometimes the txn is added to `inboundQueue`, then gets processed within an hour

Because it's stateless, it probably always be comparing against the `inboundQueue.length` from the end of the last block (and not keeping track of how many txns have been accepted into the mempool since then), so if multiple txns arrive between blocks, they might all be accepted into the mempool, even though the chain only has room for one of them. The first one will get into `inboundQueue`, the rest will be gas-fee-charged and rejected by the second ante handler. I'd have to do some simulations to estimate what percentage of submitted txns hit the three categories: rejected by the first handler, rejected by the second handler, or accepted and eventually processed.

### Escalating Admission Fee, No User Limit

We currently charge an admission fee in the second ante handler (independent of the gas fees), in IST, whose value depends upon the type and size of the message. We could change that to impose a congestion fee: the fee grows (probably exponentially) with the current depth of `inboundQueue`. So the fees are trivially low when the queue is empty, and prohibitively high when the queue is full. This lets us avoid having a fixed size and probabilistic accept/reject behavior when it is reached.

However the user experience then looks like:
* look at the chain, estimate the admission fee based on the current `inboundQueue.length`, decide to submit or not
* submit a txn
* txn hangs out the mempool, then gets included in block and executed
* user gets charged variable fee depending upon `inboundQueue` at the time of execution
  * if user has enough funds, message is added to `inboundQueue` and executed within an hour
  * if not, message is rejected and no admission fee is charged (although gas still applies)

That would be surprising. 

### Escalating Admission Fee, User-Defined Limit

If we add a new property to the transaction class, named `maxAdmissionFee` or something, then we can give the user a way to express their willingness to pay the fee. This gives them more control and predictablity of what they pay.

This requires some work:
* the message class (in x/swingset) needs a new property, and is serialized differently than before
* the class requires new accessors to reveal this property to the ante handler
* ante handler must compare the computed `f(inboundQueue.length)` fee against the new property, reject if exceeded
* CLI tools must add a new `--max-admission-fee=` argument when creating/sending the txn

The user experience looks like:
* look at chain, estimate admission fee, decide if that is worth it or not
* choose `max-admission-fee`, submit txn
* if the node you submit it to computes a required fee (based on current `inboundQueue`) that exceeds your limit, txn is dropped immediately, no fees paid
* else txn hangs out in mempool for a while, gets added to block, executed
* real fee is calculated from current `inboundQueue` depth, compared against limit
  * if exceeded, txn is rejected, you pay gas fees but not admission fee
  * if accepted, you pay admission fee (perhaps below your limit), txn is processed within an hour

Note that, unlike gas fees (which are paid exactly for all txns that get included in a block), you do not always pay the full admission fee amount you were willing to pay. But sometimes you might.
  
This isn't quite a priority auction: you can increase the chances that your txn will be processed by stating a higher limit, but that doesn't cause your txn to be processed any earlier. To be a priority auction, we'd need some pool of work that is sorted by bid or max-fee or something, rather than being serviced in FIFO order, and we don't have any easy candidates:

* the Tendermint mempool-to-proposed-block selector doesn't currently do this (and it is not easy for us to customize), and only knows about gas, not cosmos-sdk -level transaction properties like a `max-admission-fee`
* Cosmos executes the txns within a block in strict inclusion order
* `inboundQueue` has actions which represent multiple things: user-submitted PSM trades, IBC events, vbank balance updates, ag-solo mailbox messages. Many of these require a fixed FIFO execution order.
  * to enable priority selection, we'd probably need to isolate the user-submitted PSM trades into their own priority queue, kept sorted by some bid, and arrange for the bid to be charged when the trade was processed
  * currently swingset doesn't know about fees (all fees are paid by the time x/swingset puts the message into the action queue, well before they get added to `inboundQueue`)
  
## Current Plan

We'll implement at least 2, and maybe 4.

@mhofman is going to expose `inboundQueue.length` to Golang. @michaelfig or @JimLarson  will implement an ante handler that compares it against a configured length and rejects txns if exceeded.

@michaelfig said he or @JimLarson could look into adding the `max-admission-fee` property (and API/UI), and then change the ante handler to compute/compare/charge an admission fee (using more configured parameters: if we use exponential, we need an `A*e^(B*length)`).

**Comment by mhofman** [comment]
Related:
- https://github.com/Agoric/agoric-sdk/issues/5350
- https://github.com/Agoric/agoric-sdk/issues/5176

**Comment by Tartuffo** [comment]
We decided to implement "Size-Limited Queue With Reject (both ante-handlers)" for Pismo launch.

**Comment by warner** [comment]
Today we decided to implement option 2: ante-handler checks of the current `inboundQueue.length`, rejection of x/swingset events when the current length is too big (with a configurable definition of "too big"), and no new admission fees.

* #6313 : expose the queue length to golang
* #6314 : change ante-handler to reject messages once the threshold is reached
