### ISSUE TITLE
expose inboundQueue.length to x/swingset go code

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6313]
## What is the Problem Being Solved?

For #6306, the go-side "ante handler" needs to know the "current" value of `inboundQueue.length`. This queue is extended/drained during END_BLOCK processing, so the value is only updated at the end of swingset processing (`ActionType.END_BLOCK` in `blockingSend()` inside `launch-chain.js`).

The task is to send this value from the JS side into the golang side at two points:
* during BEGIN_BLOCK, so the stateful x/swingset ante-handler can reference it as it processes each of the block's txns (so it can reject some of them)
* during END_BLOCK, so the stateless ante-handler can reference it as it considers accepting txns into the mempool

## Description of the Design

Not sure, @mhofman has a plan.

## Security Considerations

none

## Test Plan

probably manual, since we don't have much test coverage in cosmic-swingset

**Comment by mhofman** [comment]
Closed by #6381
