### ISSUE TITLE
ante-handler should reject x/swingset messages if the inboundQueue is too full

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6314]
## What is the Problem Being Solved?

The second half of our good-enough fix for #6306, after #6313 makes the `inboundQueue` length available to go, is to change the ante-handler to reject x/swingset messages if that queue is longer than some configurable threshold.

That queue is extended/drained during END_BLOCK processing, so really:

* the stateless ante-handler invocation that gates admission into the mempool should know the queue length as of the end of the previous block
  * ideally, this handler would only admit `max - current` swingset-bound messages into the mempool
  * but I suspect it's so stateless that it can't maintain a "number added since last block" counter
  * oh well
* the in-consensus ante-handler which gets called as blocks are executed should know both the queue length as of the end of the previous block, plus it should maintain a counter
  * so if the threshold is 1000, and the `inboundQueue` had 999 entries at the end of the last block, and the new block has 500 new entries, the first should be accepted and the remainder should be rejected
  * if it didn't maintain a counter, then all 500 would be accepted, driving `inboundQueue` up to 1499 entries

The cutoff threshold must be in-consensus, and should be configurable somehow (I think this is a "chain parameter"?) via governance.

**Comment by warner** [comment]
I'm thinking the initial value of this should represent about an hour's worth of PSM trades, and the last number I saw was about 1.4 trades per block, at about 2s of compute time (plus 5s of consensus delay), so 7/1.4 = 5s per trade, so 3600/5 = a limit of about 720. Maybe call it 1000 entries to make it a round number.

**Comment by mhofman** [comment]
Closed by #6381
