### ISSUE TITLE
Hard refresh on psm.inter.trade causes it to wait for wallet connection even though it is connected

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#6320]
Application hangs until user clicks 'signal wallet', which is unnatural when it's already connected and user can see the dapp in their wallet connections.

Is it possible to have the app detect or attempt to signal on its own?

![image.png](https://images.zenhubusercontent.com/5fd77cb9688d8a64c14e7e66/bcaf8ec9-bb09-4e60-8563-2a5d22039b48)
![image.png](https://images.zenhubusercontent.com/5fd77cb9688d8a64c14e7e66/ec447cc0-ba1f-4bce-950c-c95b32ac44ff)

**Comment by samsiegart** [comment]
This is in part limited by the browser, in some cases we need a user gesture to connect to local storage for the bridge to work. https://github.com/Agoric/agoric-sdk/pull/6332 makes it so we connect without a user gesture whenever the browser permits, but no guarantees on if/when it will.
