### ISSUE TITLE
Convert kernel/liveslots to use smallcaps

### ISSUE THREAD

**Issue by FUDCo** [Agoric/Agoric#6326]
## What is the Problem Being Solved?

The marshal package has been upgraded to use a new and improved, but currently optional, serialization format we're calling "smallcaps" (in contrast to the existing format "capdata").  Taking advantage of this requires that the kernel and liveslots be converted to use it.

## Description of the Design

In principle this is simply a matter of adding a `serializeBodyFormat: 'smallcaps'` option to the options parameter to `makeMarshal`.  However, the source code for the kernel, liveslots, and many of their various tests incorporate strings and object literals that contain pre-serialized data in the "capdata" format, which means that various things will almost certainly break.  These need to be located and revised so that everything works properly again and all the tests pass.

**Comment by erights** [comment]
@kriskowal , for @FUDCo to make progress on this, we'll need a post-smallcaps endo release.

**Comment by erights** [comment]
> However, the source code for the kernel, liveslots, and many of their various tests incorporate strings and object literals that contain pre-serialized data in the "capdata" format, which means that various things will almost certainly break. 

Just a reminder that less will break than you might expect, because the unserializer understands both. I expect some things to break anyway, but curious to see what those are.
