### ISSUE TITLE
land mhofman's slog-sender changes on release-pismo

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6334]
## What is the Problem Being Solved?

PR #6325 changed trunk to optionally move most of the slog-processing work (serialization, OTEL conversion, publishing) into a subprocess, where it won't delay block operations. Hopefully this will remove a significant slowdown, which limits the amount of work we can afford to do in each block.

We need to cherry-pick those changes and add them to the `release-pismo` branch, so they'll be available on our `pismo-A` release.

The commits are:
* 0b5ba98792042e0b2aa25c00c1626c2d6fd11a48
* 05b98f84efabd67945a9ee6b11e0e7c62ebd5b89
* 9fa268fc9b59d9fb26d829300d7a9d5a768e47bc
* b57c1d202367833a7de09af1ef1822b4b6481a78

**Comment by warner** [comment]
cc @mhofman

**Comment by warner** [comment]
closed by #6335, not sure why this didn't auto-close

**Comment by mhofman** [comment]
Wondering if auto-close only work for the default branch
