### ISSUE TITLE
Disable SWAP button if it won’t succeed in PSM UI

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#6341]
## What is the Problem Being Solved?

To provide better user ergonomics (and avoid obtuse Zoe error messages), disable the SWAP button if:

1. Input offered exceeds the amount he user has available
2. Input amount wanted exceeds Reserve Balance (which needs to be renamed, see #6344)
3. Input amount wanted  exceeds the Mint Limit

In order for 3) to make sense, we also need to display the Mint Limit in the GUI (see #6345).

**Comment by turadg** [comment]
@rowgraus this is good ergonomics but doesn't hinder functionality so we decided this isn't a launch blocker. Can be a quick follow and could possibly get done in time.
