### ISSUE TITLE
In PSM UI, signal user when they need to switch to the Smart Wallet

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#6356]
## What is the Problem Being Solved?

When the user hits the SWAP button in the PSM UI, there is no indication that they need to go to their Smart Wallet tab to accept the transaction.

## Description of the Design

There are multiple ways to approach this, please do whatever has the right combination of being a good indicator and not too hard to implement.

**Comment by dckc** [comment]
I get a "please approve the offer in your wallet" prompt. You don't see one?

**Comment by samsiegart** [comment]
This is completed
