### ISSUE TITLE
PSM trades can take long amounts of time to "finish"

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#6372]
When testing against ebbfc4, when tasking 20 or 100 workers with making wallet action psm trades, some of the works take an extremely long time to acknowledge the completion of the trade, via `agops perf satisfaction`.  e.g. there are no logs from the contract or vbank during this period of waiting.  This can be demonstrated by the odd max times here:

<img width="742" alt="Screen Shot 2022-10-01 at 8 59 26 PM" src="https://user-images.githubusercontent.com/22369/193437248-f6834852-b716-4ce1-ab46-1283e4a46bf9.png">

For the following samples - swingset seems to be doing no vat work, but agops perf satsifaction workers are waiting.  near the end, it appears 1 worker gets satisfied per block
Blocks:
- 1483 - 1495 
- 1543 - 1571

What's happening in these block if anything? Is there notification work waiting to be saved to the chain that isn't represented in our current telemetry?
If absolutely nothing is happening in these blocks, could the client not be querying the offer status correctly?

Slogs: https://drive.google.com/drive/folders/1LBHoDsrbESyc0WG-JPg7mp9d9LvuFoUJ?usp=sharing

This is easily reproducible with a loadtest of 100 workers performing a trade

**Comment by turadg** [comment]
Current hypothesis: the lag in runs 13-15 is due to validators getting out of sync and the round-robin getting unlucky. Due to the fast retries of the perf command (100ms) it can reach exponential backoff max of 30s and then in the last outstanding offers not make any requests while the data may be available.

Testing now with 100 workers on `loadtest`. Results will be in `run-ta-1539.txt`

**Comment by warner** [comment]
I sampled the slogfile from blocks 1400 to 1500.

* 1400-1410: every block pulls 4 or 5 bridge items from `inboundQueue` and completes them
  * this shows the effects of raising the bean/computron limit, previously we would only complete one or two per block
  * every block is 100% swingset work (all but the last finish with negative `.remainingBeans`)
* 1411-1459 : no swingset work
* 1460-1479 : 100% swingset work (block 1479 was the first that had any `remainingBeans`)
  * this performed 92 trades in 428 seconds, at 4.65 s/trade (= 0.215 trades/s)
* blocks 1480-1500: no swingset work

I looked at the next chunk too:
* blocks 1520-1542
  * 101 trades in 510 seconds, 5.05 s/trade (= 0.198 trades/s)
* blocks 1543-1554 are empty, but complete much faster than expected
  * about 300ms each
  * that's pretty weird, is it not voting or something?
* block 1555 takes about 5.5s, as expected, as do the ones beyond that point

**Comment by turadg** [comment]
Diagnosis is that this is client-side only. Contracts are finishing quickly but the client can take a while to find out due to how the loadtest is configured.

We can solve this client-side and since it's an easy push, we'll wait to see if this is a problem in production.

**Comment by turadg** [comment]
https://github.com/Agoric/agoric-sdk/issues/6384 would solve this. But another option is to try using HTTP keep-alive to get the same validator in a subsequent request. So I'll leave this open until we decide when/whether/how to solve the apparent delay.

**Comment by turadg** [comment]
The "get latest height and data" is now atomic so round-robin stickiness is not a problem. (see https://github.com/Agoric/agoric-sdk/issues/6384)

@arirubinstein does your loadtest still exhibit the problem with latest master?

**Comment by ivanlei** [comment]
Per @arirubinstein in slack
> This was mitigated by the alternate fifo queue for the psm release. If we change the queuing mechanism in a future release this issue becomes relevant again
