### ISSUE TITLE
contract governance state is not very visible

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#6414]
The econ committee doesn't have good mechanisms for viewing the state of governance controls on contracts.

The committee can tell what votes have taken place, but it doesn't answer questions about what the current state is.

The state includes the values of various parameters, and which methods have been paused. 

The parameter values are available from the contract directly. We have some CLI tools that expose the current values of the governed parameters, but that's not very accessible to the committee members.

The state of paused parameters is known to Zoe itself, and not to the contract. Zoe doesn't record that in the off-chain state anywhere, so that's even less visible to committee members.

The governance tool could display all of this, but the Zoe state would require active queries, rather than queries of the off-chain data.

**Comment by Chris-Hibbert** [comment]
To clarify, from a slack discussion:

A. displaying parameter values is a UI issue.

B. The pause state can be made visible from on-chain state, or using other tools.  If that's not good enough, we'll need to fix it in RC3.

**Comment by Tartuffo** [comment]
Further clarification: A is a block for Pismo launch.  B, we can do best effort short of changes that would require an RC3 before launch.

**Comment by dckc** [comment]
> The econ committee doesn't have good mechanisms for viewing the state of governance controls on contracts.

hm. what's wrong with https://econ-gov.inter.trade/ ?

![image](https://user-images.githubusercontent.com/150986/194664595-251cddf7-d971-40ea-9587-62adb0e927d9.png)

**Comment by Chris-Hibbert** [comment]
> hm. what's wrong with ....?

Does that give updates on the current settings?  I didn't realize.

**Comment by dckc** [comment]
yes.

**Comment by Tartuffo** [comment]
This feature exists.
