### ISSUE TITLE
Econ-Gov UI frequently (but not always) fails to notice Keplr Extension 

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#6420]
Loading the econ-gov UI either from a fresh Chrome session or a new tab or a refresh often fails to notice the Keplr extension.  I am able to power through this by refreshing many times and eventually it works.

**Comment by turadg** [comment]
Has this been observed since https://github.com/Agoric/dapp-econ-gov/commit/02f9273cef3e6068e77002c9e8572949eda50f88 ?

**Comment by turadg** [comment]
Closing until there's a new observation. If it does happen again, please copy the browser console and include it here.
