### ISSUE TITLE
Ongoing Wallet, PSM and Econ-Gov UX/UI Enhancements

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#6443]
This ticket will track a list of ongoing UX/UI enhancements for the PSM.

- [x] Add logos for USDC_grv (https://frontier.osmosis.zone/_next/image?url=%2Ftokens%2Fgusdc.png&w=64&q=75) and USDC_axl (https://github.com/cosmos/chain-registry/blob/master/axelar/images/axlusdc.png)

- [x] Update PSM asset petnames to 'USDC_axl' , 'USDC_grv'

- [x] IST logo incorrectly used as default for newly added pairs (should be unknown telescope logo) or better yet we just use the correct one once known

- [x] Add new PSM assets 'USDT_axl' (https://github.com/cosmos/chain-registry/blob/master/axelar/images/axlusdt.png) and 'USDT_grv' (https://frontier.osmosis.zone/_next/image?url=%2Ftokens%2Fgusdt.png&w=48&q=75)
- [x] Change _AXL and _GRV to be lower-case in PSM UI so _axl and _grv (they already lower-case in wallet UI)

**Comment by samsiegart** [comment]
@otoole-brendan The USDC_axl logo has some whitespace to the left and right ![Screen Shot 2022-10-11 at 7.02.48 PM.png](https://images.zenhubusercontent.com/614a110f5d273b498df17d49/ee1fdc95-528c-49b2-a007-11a3e7a05e42) 

**...while the USDC_grv logo does not:**

![Screen Shot 2022-10-11 at 7.03.18 PM.png](https://images.zenhubusercontent.com/614a110f5d273b498df17d49/de092ae9-11fd-4388-adee-93bf79425f4a)

**...making them appear to be different proportions when rendered next to eachother:**
![Screen Shot 2022-10-11 at 7.05.42 PM.png](https://images.zenhubusercontent.com/614a110f5d273b498df17d49/b61bfa86-7343-4e5d-b7d4-a37f271c68ae)

Is this okay?

**Comment by otoole-brendan** [comment]
@samsiegart struggling to find an alternative png logo. What if we edit the current png and remove the whitespace...would that fix the rendering issue?

**Comment by otoole-brendan** [comment]
I tried cropping myself @samsiegart - see if this works:
![axlusdc_cropped.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/a19b6df3-aaff-4c55-950b-0602f36c6360)

**Comment by samsiegart** [comment]
@otoole-brendan What do you mean by "Update PSM asset petnames to 'USDC_axl' , 'USDC_grv'"? Should I make it not all-caps? It loads the petnames from the contract.

**Comment by otoole-brendan** [comment]
@samsiegart I thought there was an action item stemming from [this](https://agoricopco.slack.com/archives/C038TM0EUKG/p1665520490531089?thread_ts=1665516859.822449&cid=C038TM0EUKG) comment but I guess not? AFAIK USDC_axl and USDC_grv are correct

**Comment by otoole-brendan** [comment]
Also - we intend to launch with USDT_axl and USDT_grv also. I will dig out logos for these but heads up you may need to do other FE work to add them

**Comment by samsiegart** [comment]
@otoole-brendan Just deployed the latest PSM and Wallet UIs with the new logos

**Comment by otoole-brendan** [comment]
Thanks @samsiegart! Looks good! I don't see USDT yet but presumably you haven't added those yet as that was only added as a requirement today?

**Comment by samsiegart** [comment]
> I don't see USDT yet but presumably you haven't added those yet as that was only added as a requirement today?

Yea I don't know how to add IBC assets to the network. The icons are in the UI for when they are added though.

**Comment by otoole-brendan** [comment]
ah ok gotcha. It was ticked in above list but I unticked. Sounds like a discussion with Dan is warranted?
