### ISSUE TITLE
Error: missing SMART_WALLET due to outdated devnet discord faucet

### ISSUE THREAD

**Issue by EmreNOP** [Agoric/Agoric#6445]
After upgrading devnet host to v0.32.0 noticed below error in the logs when i start node. its not repeating just one time error. 

Oct 11 21:55:50 host agd[1361969]: 2022-10-11T19:55:50.959Z SwingSet: xsnap: v1: RemoteError(error:liveSlots:v19#70001)#1: missing SMART_WALLET in powerFlags
Oct 11 21:55:50 host agd[1361969]: 2022-10-11T19:55:50.960Z SwingSet: xsnap: v1: Error: missing SMART_WALLET in powerFlags
Oct 11 21:55:50 host agd[1361969]:  at construct ()
Oct 11 21:55:50 host agd[1361969]:  at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:56)
Oct 11 21:55:50 host agd[1361969]:  at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:242)
Oct 11 21:55:50 host agd[1361969]:  at decodeErrorCommon (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:284)
Oct 11 21:55:50 host agd[1361969]:  at unserialize (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:359)
Oct 11 21:55:50 host agd[1361969]:  at notifyOnePromise (/bundled-source/.../packages/SwingSet/src/liveslots/liveslots.js:1189)
Oct 11 21:55:50 host agd[1361969]:  at notify (/bundled-source/.../packages/SwingSet/src/liveslots/liveslots.js:1213)
Oct 11 21:55:50 host agd[1361969]:  at dispatchToUserspace (/bundled-source/.../packages/SwingSet/src/liveslots/liveslots.js:1457)
Oct 11 21:55:50 host agd[1361969]:  at runWithoutMetering (/bundled-source/.../packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:52)
Oct 11 21:55:50 host agd[1361969]:  at ()
Oct 11 21:55:51 host agd[1361969]: 2022-10-11T19:55:51.200Z SwingSet: xsnap: v1: UnhandledPromiseRejectionWarning: (RemoteError(error:liveSlots:v19#70002)#2)
Oct 11 21:55:51 host agd[1361969]: 2022-10-11T19:55:51.201Z SwingSet: xsnap: v1: RemoteError(error:liveSlots:v19#70002)#2: missing SMART_WALLET in powerFlags
Oct 11 21:55:51 host agd[1361969]: 2022-10-11T19:55:51.202Z SwingSet: xsnap: v1: Error: missing SMART_WALLET in powerFlags
Oct 11 21:55:51 host agd[1361969]:  at construct ()
Oct 11 21:55:51 host agd[1361969]:  at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:56)
Oct 11 21:55:51 host agd[1361969]:  at makeError (/bundled-source/.../node_modules/ses/src/error/assert.js:242)
Oct 11 21:55:51 host agd[1361969]:  at decodeErrorCommon (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:284)
Oct 11 21:55:51 host agd[1361969]:  at unserialize (/bundled-source/.../node_modules/@endo/marshal/src/marshal.js:359)
Oct 11 21:55:51 host agd[1361969]:  at notifyOnePromise (/bundled-source/.../packages/SwingSet/src/liveslots/liveslots.js:1189)
Oct 11 21:55:51 host agd[1361969]:  at notify (/bundled-source/.../packages/SwingSet/src/liveslots/liveslots.js:1213)
Oct 11 21:55:51 host agd[1361969]:  at dispatchToUserspace (/bundled-source/.../packages/SwingSet/src/liveslots/liveslots.js:1457)
Oct 11 21:55:51 host agd[1361969]:  at runWithoutMetering (/bundled-source/.../packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:52)
Oct 11 21:55:51 host agd[1361969]:  at ()

**Comment by dckc** [comment]
odd. I think I would need more information to understand what's going on. Exactly how did you start the node? What version are you using? If you can provide more of the stuff suggested in https://github.com/Agoric/agoric-sdk/blob/master/.github/ISSUE_TEMPLATE/bug_report.md , that would be great.

**Comment by dckc** [comment]
I suspect this is from someone using the beta process to [register a client via the Agoric discord faucet](https://github.com/Agoric/agoric-sdk/wiki/Setting-up-an-Agoric-Dapp-Client-with-docker-compose#register-your-client-via-the-agoric-discord-faucet). The [discord faucet](https://github.com/Agoric/faucet) is out-of-date w.r.t. SMART_WALLET provisioning.

cc @michaelfig @cboydstun

**Comment by cboydstun** [comment]
@dckc remove the faucet from the docs?

**Comment by cboydstun** [comment]
if so, then shouldn't we bring that discord channel down, too?

**Comment by dckc** [comment]
probably so

**Comment by cboydstun** [comment]
@Tyrosine22 has a branch brewing nearly ready for a pull request - want this one too?

**Comment by dckc** [comment]
Following the [docker-compose docs](https://github.com/Agoric/agoric-sdk/wiki/Setting-up-an-Agoric-Dapp-Client-with-docker-compose) still leads to a recommendation to use a discord faucet:

```
ag-solo_1  | =============
ag-solo_1  | agoricdev-16 chain does not yet know of address agoric1zu39hunnat9970qhxgwkcetq3ravwxv39e5d24
ag-solo_1  | 
ag-solo_1  | Send:
ag-solo_1  | 
ag-solo_1  |   !faucet client agoric1zu39hunnat9970qhxgwkcetq3ravwxv39e5d24
ag-solo_1  | 
ag-solo_1  | to the appropriate faucet channel on Discord (https://agoric.com/discord)
ag-solo_1  | =============
```

https://github.com/Agoric/agoric-sdk/blob/162fdf2a51c54e2da89c8ed35f06cab09fb013d2/packages/solo/src/chain-cosmos-sdk.js#L30

**Comment by dckc** [comment]
the `packages/solo` code was fixed in...

 - #6688
