### ISSUE TITLE
Add pre-populated Axelar and Gravity buttons/links to PSM UI to improve bridging UX

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#6453]
## What is the Problem Being Solved?
The PSM bridge UX is not intuitive. 

## Description of the Design
To improve this we can allow users to link out to Axelar and Gravity UIs that have pre-selected/auto-populated source, destination and token denom.
 
This will remove a few steps for users and thereby improve UX flow. This also mitigates against user error.

**Comment by otoole-brendan** [comment]
Example flow on Crescent:
When you click ‘Go Bridge’, it takes you to Axelar page with Source = Ethereum, Destination = Crescent and denom = USDC (This is the behavior we want)
![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/865b241a-eaed-4c0a-af08-c49be7df83e2)
![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/19bbcadd-a147-4d8c-ab8b-9656d42cce5e)

**Comment by otoole-brendan** [comment]
Note: this looks to be possible for Bridged Axelar USDC and USDT but not for Gravity USDC USDT since Gravity UI requires user to connect their source and destination wallets before allowing token selection and address population (See screenshot below). This might mean there is little we can do to to pre-populate the Gravity UI link. 
![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/753e53bc-21f1-4582-91d7-b6fbe3659d7c)

**Comment by samsiegart** [comment]
Any thoughts where that button/link should go? I was thinking maybe just a little link right under the petname after you've selected the asset

**Comment by otoole-brendan** [comment]
![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/8a8ebcc3-c91b-4ed6-91cf-18161a169308) so directly under the 'USDC_axl' or 'USDC_grv' text? I tried researching other examples of bridge link button/link placement but failed to find any but where you're suggesting seems to be the most intuitive in my view...

**Comment by samsiegart** [comment]
> so directly under the 'USDC_axl' or 'USDC_grv' text?

Yea, I can't think of a better place for it at the moment unless we want to create a whole separate panel or something. Like a "Bridge Assets" link on top where this "View Liquidity Pools" text is in the AMM, which could open a drawer with a list of assets and links to the bridge. Seems a bit overkill though.
<img width="599" alt="Screen Shot 2022-10-14 at 10 25 33 AM" src="https://user-images.githubusercontent.com/8848650/195905879-9d78327c-70b3-4051-bd9e-ebad9137fc22.png">

**Comment by otoole-brendan** [comment]
Yeah agree another panel would be overkill for now. Happy to go with under the text location! (Unless it looks really weird but I guess we'll find out)

**Comment by otoole-brendan** [comment]
@turadg as discussed, we are simplifying this by simplying adding some hyperlinked text that brings users to our Gitbook bridging instructions.

For UI text, I'm thinking: 'Need to Bridge Assets?' but it might be too long and look weird so open to suggestions, or maybe if you can render it then we can review. @rowgraus - shout if you prefer something else.

Link destination should take them here: https://docs.inter.trade/user-how-to/mainnet-only-bridge-external-tokens-to-agoric

**Comment by turadg** [comment]
https://github.com/Agoric/dapp-psm/pull/23/files#diff-b7e21ae2d4fd82d7f5e6b420d4dc6b60016e28b778e68bee19a6da4950d99bf9 adds a help link. Let's see discuss what else may be necessary.
