### ISSUE TITLE
Trade gets stuck showing as Pending in Wallet

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#6459]
Reported by @mhofman, sounds like a similar problem experienced by @arirubinstein recently:

When doing a PSM trade, the wallet asked to approve the offer, which I did, then I confirmed in Keplr. I saw [transaction go through](https://loadtest.explorer.agoric.net/agoric/tx/FCB03880409F6B147F75B55CF7F381EFF850319F32E4A369FE55B3167F968962). After a minute or 2, the wallet still showed as pending (even though the balances had updated), so I refreshed the wallet, which reverted to asking to accept the offer. I subsequently re-approved, which asked keplr to approve and [submit another transaction](https://loadtest.explorer.agoric.net/agoric/tx/0D435BA5DEBBB20CED524CD5A4B1EBB68BBFC898C6F86BB059E3B727EF6AFCCD), which did not result in another balance change since wallet spend have a unique id, however I may have been charge gas / swingset fees? The offer still shows as pending.

**Comment by Tartuffo** [comment]
May be the same as the already closed #6416

**Comment by mhofman** [comment]
This was not a caching problem for me as the chrome profile was brand new, so the version of the wallet I loaded was the one deployed Friday afternoon. Of that had some kind of fix included, it didn't work in my case.

**Comment by samsiegart** [comment]
I believe this is fixed now with the latest bridge changes, so closing
