### ISSUE TITLE
wallet-ui: ensure offer ids are always increasing

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#6478]
## What is the Problem Being Solved?

Offer ids will be rejected by the smart wallet contract if they are not higher than all previous offer ids.

So if a user makes two offers and clicks Approve on the later one first, the the earlier one will always fail.

## Prioritization

Not a launch blocker because we don't expect users to have multiple PSM orders to approve at the same time.

**Comment by otoole-brendan** [comment]
@samsiegart how do you propose to solve the problem? Will you allow approval of all offers or stop user submitting another offer if there is already an active one?

**Comment by samsiegart** [comment]
@otoole-brendan I was thinking allow approval of all offers. I did not consider only allowing one proposed offer at a time. Would that be an acceptable solution also?

**Comment by otoole-brendan** [comment]
@samsiegart does allowing multiple (and potentially unlimited) offers to be approvable create any performance concerns? Practically I presume a user is only ever going to be creating and approving one offer at a time - I don't see the benefit of allowing them to submit multiple at once and then subsequently approving multiple at once in the wallet...but I may be missing something...

**Comment by otoole-brendan** [comment]
@rowgraus keen to hear your thoughts on this too in case there's a use case I'm missing

**Comment by samsiegart** [comment]
> @samsiegart does allowing multiple (and potentially unlimited) offers to be approvable create any performance concerns? Practically I presume a user is only ever going to be creating and approving one offer at a time - I don't see the benefit of allowing them to submit multiple at once and then subsequently approving multiple at once in the wallet...but I may be missing something...

No performance concerns, no.

**Comment by samsiegart** [comment]
Obviated by https://github.com/Agoric/agoric-sdk/pull/6556
