### ISSUE TITLE
clarify why tokens from unsupported IBC paths do not show up in smart wallet

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#6507]
## What is the Problem Being Solved?
Message from user:
2:15 AM]: hi. transferred a small amount of USDCgrav to Agoric in order to test the PSM. I can see the USDC in my Keplr but it doesn't show up in Agoric's smart wallet (edited)
[2:21 AM]: (actually it is USDCaxl bridged through Gravity Bridge fwiw)
IBC assets have specific denoms depending on the route it came from i.e. USDC sent from Ethereum to Agoric through Gravity bridge will have a different denom to USDC_grv sent from Gravity bridge to Osmosis and then to Agoric.

New IBC asset denoms need to be explicitly added to the vat-bank because we don't know their decimal places (a necessary parameter when finalizing ERTP) in order to be represented/tradable in Agoric contracts.

The Agoric wallet does not recognize or display new/unknown IBC asset denoms. This means if unknown IBC assets are sent to Agoric wallet they will not appear in UI as a purse.

Is there a way for the Agoric wallet to show IBC asset tokens before they have been formally added via governance? This is currently happening to users who are unaware of the bridge source nuance on asset denoms so we need to be able to offer some guidance/solution to handle this scenario.

The user impact here is, user's may not understand that their bridged assets unknowingly have different denoms and wonder why they aren't appearing in the Agoric smart wallet

**Comment by mhofman** [comment]
Since there is currently no good way to know which IBC denom is held in a vbank purse, I suggested that maybe we could query how many IBC denoms are held in the cosmos account, compare that to the number of non-zero balance vbank purses, and show a message only if the number doesn't match?

**Comment by dckc** [comment]
#5762 could / should provide the list of demos supported by the vbank; this seems like another reason to prioritize it for a future release.

**Comment by otoole-brendan** [comment]
From discussing further with Rowland - the least effort/high impact stopgap for now until we can solve more gracefully would be to have a general notice in Wallet UI near purse balances along the lines of 'Can't see all your assets? Your asset may not be supported. Please see information on supported assets' - linking out to relevant page on docs.inter.trade.

@samsiegart where do you think the most logical place for this would be? I'm thinking below the purse list as it's own tile or alternatively as it's own line item in the purse with a magnifying glass or such that infers 'missing'.

**Comment by samsiegart** [comment]
For messaging, what about something like: "Only certain asset types are supported by the Smart Wallet in Mainnet Phase 1. Additional assets and IBC denoms will be supported in future upgrades". And it links out to whatever docs/roadmap.

UX-wise, I'm thinking something more tucked away like some link text, "Assets missing?", that shows an info card when clicked. Or maybe an "Add purse (+)" button and when you click it it shows a dialog with the above text and an "Unsupported" title. I can try a few things and see how it looks.

**Comment by mhofman** [comment]
Some IBC denoms will likely never be supported by the Smart Wallet. Maybe they could be supported by the wallet UI to perform IBC transfers, but that's about it.

Aka if you sent USDCaxl from whatever-chain instead of directly from axl, you won't be able to do anything with it on our chain, and should send it back to where it came from (possibly automatically once automatic IBC routing is implemented by cosmos chains)

**Comment by samsiegart** [comment]
@otoole-brendan I have a screenshot in https://github.com/Agoric/wallet-app/pull/31, does this pattern work? If so, could you help me out with the final messaging/content link?

**Comment by otoole-brendan** [comment]
@samsiegart I think it's an option but a user would have to click to 'i' to find out the information. Where would you put the 'Assets Missing?' text that links an info card? Could I please see a version of that for comparison? 

Re content link: please hyperlink 'Please see information on supported assets' with https://docs.inter.trade/inter-protocol-system-documentation/parity-stability-module/supported-assets

**Comment by samsiegart** [comment]
> Where would you put the 'Assets Missing?' text that links an info card?

I tried putting it a few places (below the list, at the top, under "Purses"), but it just stood out too much. It just seems heavy-handed to draw all users' attention to it every time they look at their wallet when it's not a concern most of the time, it makes it seem like something's broken almost. I would hope that if something doesn't seem right the user would think to click the info icon

**Comment by otoole-brendan** [comment]
@samsiegart yeah that was my concern too (about it being an exception pathway and not the happy path and so us attracting too much attention to it maybe not the right way to go) so consider me persuaded!

**Comment by otoole-brendan** [comment]
Can we add more info to the pop-up though? 'The smart wallet only supports certain assets and IBC denoms. If you are missing assets it may be because it is not supported. Please see information on supported assets.'

**Comment by samsiegart** [comment]
@otoole-brendan See @turadg's question on https://github.com/Agoric/wallet-app/pull/31:
```
this link is to a PSM resource. the smart wallet is outside PSM and even Inter Protocol. I think this Smart Wallet UI must not
prefer any particular dapps or protocols.

Can this information be put somewhere neutral? E.g. on this repo?
```

**Comment by otoole-brendan** [comment]
Hmm we already cover Agoric Smart Wallet and provisioning in user docs on docs.inter.trade...https://docs.inter.trade/user-how-to/wallet-usage/create-your-agoric-account-and-smart-wallet. If we're now saying there needs to be some separation that begs the wider question of where? I'm not a fan of pointing users back to GH repo for friendly user-facing docs. Would wallet section under https://docs.agoric.com/ be a better home? (I might lift this convo into Slack for wider discussion)

**Comment by turadg** [comment]
> I'm not a fan of pointing users back to GH repo for friendly user-facing docs

I meant having the web app point to itself. I.e. you're on wallet.agoric.app (where the repo is deployed now) and if there's a link to learn more about the Wallet UI it's to a local url. e.g. `href="/docs/supported-tokens"`

Not a hard blocker but something we need to think about more holistically and carefully.

**Comment by dckc** [comment]
updated title to reflect scope / design that we seem to have chosen, since we're not actually fixing the fact that USDCaxl bridged through Gravity does not show up

**Comment by dckc** [comment]
Should this issue move to https://github.com/Agoric/wallet-app ? Would that help with release notes / changelogs?

**Comment by turadg** [comment]
> Would that help with release notes / changelogs?

Those are constructed from Git history so the issue location won't make a difference.

**Comment by samsiegart** [comment]
Can we close this now?

**Comment by samsiegart** [comment]
Can we close this now?

**Comment by dckc** [comment]
yes; it's clearly fixed in https://github.com/Agoric/wallet-app/pull/31

_oops... maybe the question was to @otoole-brendan?_
