### ISSUE TITLE
API to get summary of swingstore block changes

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#6562]
## What is the Problem Being Solved?

In order to solve state-sync (#3769, #5542), we need to capture the content of changes to swingset state, and save it either to the IAVL tree (#5934), or write it in an external blob (WAL like for a full state dump).

Only the resulting write and deletes are needed, not any intermediate mutations, or any read.

This also need to be cognizant of potential crank rollbacks, so a simply memory based approach like the current crank buffer is probably not appropriate.

This is currently complicated by the fact SwingSet state is split over 3 kind of storage: LMDB for the swing-store, SQLite for the stream-store, and raw files for snapshots of the snap-store.

## Description of the Design

Once a [single SQLite DB](https://github.com/Agoric/agoric-sdk/issues/3087) is used for all SwingSet state (as initiated by https://github.com/Agoric/agoric-sdk/pull/6561), the following approach may work:
- Swingstore create a second memory back SQLite DB for every block
- Every write and delete is saved into this DB, handling crank rollbacks (which can use regular transactions instead of savepoints)
- At the end of the block, and dump of this DB is taken (and normalized)
- The dumb is either send to the cosmos side, or written to disk and hashed as appropriate

The DB / table would likely require 3 column: `key`, `newValue` and `deleted`.

## Security Considerations

None I can think of

## Test Plan

TBD

**Comment by warner** [comment]
cc @FUDCo

**Comment by warner** [comment]
This is really the incremental aspect of #6773, and thus superceded by it.
