### ISSUE TITLE
verify `priceAggregatorChainlink.js` is production-ready

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Agoric#6571]
## What is the Problem Being Solved?

refs: #5791

The `priceAggregatorChainlink.js` contract is not yet ready for production, due to some neglect and missing features.  It should be upgraded, then used by the oracle network instead of `priceAggregator.js`.

## Description of the Design

- [x] uses rounds (https://github.com/Agoric/agoric-sdk/pull/6629)
- [x] supports continuing invitation (https://github.com/Agoric/agoric-sdk/pull/6629)
- [x] is reachably durable https://github.com/Agoric/agoric-sdk/issues/6716
- [x] is upgradeable https://github.com/Agoric/agoric-sdk/issues/6853
- [ ] publishes whatever data is needed by economists: https://github.com/Agoric/agoric-sdk/issues/5854

## Test Plan

For the canonical priceAggregator contract…
- supports arbitrary Passable as oracle key
- has no legacy calls
- no FIXMEs or TODOs
- [limits work by message size](https://github.com/Agoric/agoric-sdk/wiki/Limit-work-by-message-size)

**Comment by turadg** [comment]
Done enough for release. The tech debt of TODOs and legacy calls are acceptable tech debt. The only FIXME are types.
