### ISSUE TITLE
Governance charter deployment to existing chain

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Agoric#6598]
## What is the Problem Being Solved?

We need a way to add smart-wallet-compatible governance charters as part of installing new features like vaults.

## Description of the Design

Ensure the new contracts and core-eval modules are grouped by deployable feature so that the charter capability is sent to the appropriate address when that feature is deployed.

From `packages/inter-protocol/src/proposals/committee-proposal.js` `inviteCommitteeMembers`:

```js
            // TODO: This null invitation is used just to identify the
            // closely-held economy charter instance handle.  Instead, the
            // economy charter should use continuing invitations like the PSM
            // charter does for compatibility with the smart wallet.
```

**Comment by dckc** [comment]
That TODO is from a version of #6568 that didn't survive code review. It's gone now.
