### ISSUE TITLE
Potential leak in v17 (bank) and v18 (smart wallet)

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#6611]
on [agoric-3](https://ui.honeycomb.io/agoric/datasets/agoric-3/result/sSJ2Even2zv), it appears that v17 and v18 are growing in size over time:

<img width="1799" alt="Screenshot 2022-11-30 at 3 37 51 PM" src="https://user-images.githubusercontent.com/22369/204931716-62ac8ba5-d65b-4ed9-91f4-813e7c645c2d.png">

<img width="1813" alt="Screenshot 2022-11-30 at 3 37 46 PM" src="https://user-images.githubusercontent.com/22369/204931702-bfd1ffb2-d3f2-45c0-99e1-d4ba56d95dd1.png">

**Comment by dckc** [comment]
It's less surprising that vat-bank grows; #5885 is still open.

#4489 is closed, so the smart wallet should be using virtual objects to limit heap growth.

**Comment by dckc** [comment]
@mhofman pointed out that this closure likely keeps all representatives in the heap rather than just in virtual storage:

https://github.com/Agoric/agoric-sdk/blob/2c812d22161cd297587979b262eab6e2cc76e23d/packages/smart-wallet/src/smartWallet.js#L523-L524

**Comment by turadg** [comment]
I think @dckc fixed this in #6774. There's only one observer, within the asset registry shared by all wallets:
https://github.com/Agoric/agoric-sdk/blame/9aa48736a3b158f8e8746e815f7a94887e02b46e/packages/smart-wallet/src/walletFactory.js#L64-L78
