### ISSUE TITLE
Provide price feeds on local chain

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#6649]
## What is the Problem Being Solved?

For vaults UI we need a way to read price feeds from the chain. Currently `make scenario2-run-chain-economy` does not publish any price feeds to rpc.

## Description of the Design

TBD

## Test Plan

Start a local chain and read prices for IST and IbcATOM or some collateral brand via RPC.

**Comment by turadg** [comment]
@samsiegart the price feed is publishing; there just aren't any prices fed into it. To do that see the steps in https://github.com/Agoric/agoric-sdk/blob/master/packages/agoric-cli/test/agops-oracle-smoketest.sh

If you want those to be automated, I don't think we should put it into the bootstrap or manifest, but we could have `start-local-chain.sh` do them as a convenience.

**Comment by turadg** [comment]
Gonna close this for now. Please reopen if it's still an issue @samsiegart
