### ISSUE TITLE
AmountMath.min() and .max() can give incorrect results for non-fungibles.

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#6691]
## Describe the bug

AmountMath.min and max were added, and they return `Y` if `X > Y`, otherwise `X`. But non-fungibles can have pairs where neither amount is greater than the other.

## To Reproduce

Define a non-fungible type, for instance, theater seats.
`[{ seat a}, {seat b}]` is greater than `[{ seat a}]`, but neither greater than nor less than `[{ seat c}]`.
It's incorrect to return either amount when there's no relationship.

## Expected behavior

It should throw.

## Platform Environment
N/A

**Comment by Chris-Hibbert** [comment]
cc @erights

**Comment by erights** [comment]
That's truly bizarre. It was added as of https://github.com/Agoric/agoric-sdk/pull/4474 , without any discussion of this obvious bug. I approved it, again, with no sign that this obvious bug even occurred to me. Apparently not obvious at the time, but I cannot imagine why not.

Scary!
