### ISSUE TITLE
EC can propose and vote on changes to oracle operators list

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6701]
## What is the Problem Being Solved?

To support https://github.com/Agoric/dapp-econ-gov/issues/35

## Description of the Design

TBD

> Should this be the EC invitation or a new price feed admin invitation distributed to the EC members?

The EC invitation should suffice. If we decide to make a separate oracle admin electorate, the electorate is a governed param, so we can change it at that time. An invitation to a new electorate is also likely to meet requirements, if that's more straightforward.

> Should the invitation be to administer oracles for all oracle-based price feeds, or a particular one?

TBD

> Should the proposal be for addition/removal or a specific list? If a list, the contract can resolve the add/remov. If add/remove, is it singular or a list?

Product says add/remove singular.

### Tech details

Make the priceaggregator contract governed.
Then we can allow the EC go call its methods to add and remove oracles.
Smart wallet will also need to support api calls if it doesn't already.

For revoking the existing oracles, try the [Caretaker pattern](https://github.com/dckc/awesome-ocap/wiki/CareTaker).
The caretaker itself should be virtual to not consume RAM (though since there are so few, it's arguable that it should just be noted as a scaling consideration).

**Comment by dckc** [comment]
> Should this be the EC invitation or a new price feed admin invitation distributed to the EC members?

The EC invitation should suffice. If we decide to make a separate oracle admin electorate, the electorate is a governed param, so we can change it at that time.

An invitation to a new electorate is also likely to meet requirements, if that's more straightforward. I can't imagine that it is.

**Comment by ivanlei** [comment]
Per @rowgraus in slack on 01/20/2023
> Based on EC conversation yesterday, they did not believe they needed control over the oracle nodes or feeds on launch.  This is different from what I had heard previously and is more aligned with Dean’s goal that Simply Staking instead is in charge of that.  Based on Chainlink’s responses today it sounds like this control also hasn’t been required by them in production, which makes me feel better. Hopefully this might save some governance work on our end.

Thus closing this.

**Comment by ivanlei** [comment]
Reopening based on changing requirements. @rowgraus please help clarify.

**Comment by otoole-brendan** [comment]
Subject to discussion today in Inter Proto meeting

**Comment by otoole-brendan** [comment]
@turadg discussed with @dckc that it made sense to assign to you, lmk if we got that wrong

**Comment by dckc** [comment]
see also [mock ui](https://docs.google.com/spreadsheets/d/1dxnxMdWvN1YMNOZwzuIML4jZU1_LCoH898GSb0pJJvg/edit#gid=837070347) sketched with @otoole-brendan 

_perhaps more relevant to the UI issue: https://github.com/Agoric/dapp-econ-gov/issues/35#issuecomment-1406952310_
