### ISSUE TITLE
move makeBufferedStorage from swingset to cosmic-swingset

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6704]
## What is the Problem Being Solved?

After @FUDCo 's PR #6561 lands, swingset itself will no longer be using the `makeBufferedStorage()` defined in `packages/SwingSet/src/lib/storageAPI.js`. The only other client is in `cosmic-swingset`, which uses a deep import to fetch it.

The task is to move this utility out of SwingSet and into cosmic-swingset.

cc @gibson042 

## Description of the Design

Move file. Change import. Figure out where the unit test lives and move it too. Celebrate.

**Comment by gibson042** [comment]
Closed by #6814.
