### ISSUE TITLE
Smart-wallet like vat to handle oracle price updates

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#6749]
Based on https://github.com/Agoric/agoric-sdk/issues/6576#issuecomment-1362238505, we need a vat similar to the smart wallet that will exclusively handle oracle price update messages.

That vat should be the sole holder the price aggregator admin facets, and map those 1:1 per sender.

**Comment by dckc** [comment]
Adding the new proto msg type seems to be in scope here rather than #6576

**Comment by mhofman** [comment]
I believe so. I think I had started on a branch for that, let me dig it up, so you don't have to redo that part.

Edit: here it is: https://github.com/Agoric/agoric-sdk/tree/mhofman/6749-oracle-action (very first draft that I stopped when questions arised regarding separation into another vat)

**Comment by mhofman** [comment]
Today we decided we can get away with not doing this, but instead rely on a list manually maintained through governed params.
