### ISSUE TITLE
does finalizeDroppedCollection() make syscalls sensitive to GC?

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6760]
## What is the Problem Being Solved?

While studying the liveslots virtual-collection code, I ran across `finalizeDroppedCollection`:

https://github.com/Agoric/agoric-sdk/blob/669ad6d309b550acf250b73f5c3f7714bbe217bf/packages/SwingSet/src/liveslots/virtualReferences.js#L612-L614

This is wired to a FinalizationRegistry during initialization (in startVat):

https://github.com/Agoric/agoric-sdk/blob/669ad6d309b550acf250b73f5c3f7714bbe217bf/packages/SwingSet/src/liveslots/virtualReferences.js#L32-L34

and can do things like call `voAwareWeakSetDeleter`:

https://github.com/Agoric/agoric-sdk/blob/669ad6d309b550acf250b73f5c3f7714bbe217bf/packages/SwingSet/src/liveslots/virtualObjectManager.js#L355-L371

which can do syscalls:

https://github.com/Agoric/agoric-sdk/blob/669ad6d309b550acf250b73f5c3f7714bbe217bf/packages/SwingSet/src/liveslots/virtualReferences.js#L514-L519

I'm worried that this creates an additional syscall sensitivity to GC, like #6360 , because `finalizeDroppedCollection` does not go through a `possiblyDeadSet` (which doesn't get serviced until BOYD).

The task is to audit this pathway with whatever tools or techniques we come up with for #6360, determine whether it's an actual sensitivity, if so decide whether we care deeply enough to fix it, and then fix it. The fix will probably involve some kind of BOYD/`possiblyDeadSet` delay, where it doesn't matter when the finalizer runs, and nothing that could trigger a syscall (or influence other syscalls) can happen until a BOYD.

Things to be wary of:
* metering sensitivity of the finalizer running
* `finalizeDroppedCollection` reducing virtual-reference refcounts (the "vref pillar") of other objects before BOYD, allowing them to be collected when e.g. their export pillar is dropped, which would cause different syscalls.
* remember that finalizers run at the end of each delivery (we control XS enough to defer them *during* a delivery, but they run for all deliveries, not just BOYD

cc @FUDCo

**Comment by warner** [comment]
cc @mhofman

**Comment by mhofman** [comment]
I finally looked at the code and concur this finalizer can have observable side effects.

> * metering sensitivity of the finalizer running

As far as I understand, finalizers are run after the promise queue is drained and before setImmediate calls back. Since I don't see any metering disablement for finalizers, it seems that all of them (virtual objects and vref manager) run metered, which would further make consensus execution sensitive to worker gc, including organic. I filed https://github.com/Agoric/agoric-sdk/issues/6795.

**Comment by warner** [comment]
I just did another pass and I agree: metering will be affected, but not syscalls.

* `virtualReferences.js` has its own FinalizationRegistry, named `droppedCollectionRegistry`
* it is only used by VirtualObjectAwareWeakMap/Set, when a new WeakMap/WeakSet is created
  * the descriptor it registers points to the Map/Set's `voAwareWeakMapDeleter`
  * so the only collections being watched by this FR are VO-aware WeakMap/Sets (which don't have vrefs, and don't virtualize their data)
* when such a collection is FINALIZED, that `Deleter` will call `vrm.removeRecognizableVref(vref, map/set)` for each vref
* `removeRecognizableVref` takes a third `recognizerIsVirtual` argument, which will always be false here (the third argument isn't even provided)
  * that skips the branch which uses `vom.ir.${vref}|${recognizer}` vatstore keys (i.e. virtualized recognition-graph edges)
  * instead, it manipulates some in-RAM Sets and Maps which keep track of which vo-aware WeakMap/Sets are paying attention
  * it deletes any now-empty ones
  * and may submit the vref to `addToPossiblyRetiredSet(vref)`, indicating that a RAM-recognizability pillar has just been dropped
* `addToPossiblyRetiredSet()` adds the vref to a set which is not processed until BOYD

So I'm pretty sure that no syscalls can happen because of this pathway. It's not as obvious as I'd like, because `removeRecognizableVref` is serving two clients: one that uses a FinalizationRegistry (this one), and another that behaves less GC-sensitively but which calls it in a way that uses `vatstoreDelete`.

The next time we consider refactoring in this file, we should consider splitting `removeRecognizableVref` into two separate functions, instead of using a third `recognizerIsVirtual` argument to distinguish the cases.

Based on that, and since we have #6795 to track the metering variations (which come from all finalizers, not just `finalizeDroppedCollection`), I'm going to close this one.
