### ISSUE TITLE
publish price feeds of tradeable brands per vault manager

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6765]
## What is the Problem Being Solved?

The only price feeds published yet by RPC are of the inter brands that the oracle network uses. Dapp-inter for vault trades needs to know prices in terms of the tradable brands the VaultManager uses.

## Description of the Design

Have the VaultManager publish the prices from the authority its using itself (a `scaledPriceAuthority`). We could publish under a broader scope but this decouples VaultFactory uses from the general `priceRegistry`.

So just subscribe to the priceAuthority the VM already gets and publish that to RPC. Consider https://github.com/Agoric/agoric-sdk/issues/6779 while doing this.

This blocks https://github.com/Agoric/dapp-inter/issues/7

**Comment by dckc** [comment]
#6700 made the displayInfo available. What's missing is publishing the _scaled_ price authority's price. Having `priceAuthorityRegistry` publish everything that's registered would probably take care of it.

**Comment by turadg** [comment]
@otoole-brendan I removed vaults_triage because we changed the scope of this issue. It is required for Vaults Release.

**Comment by otoole-brendan** [comment]
@turadg 'vaults triage' label just means we've considered the issue in lieu of vaults release and determined either a) it's in vaults release or b) it's not in vaults release. The issue gets the 'vault triage' regardless. If it's required for Vaults release it's get the label AND gets added to the 'Vaults' release and put in appropriate pipeline. If not in Vaults release, it gets label and gets added to appropriate pipeline i.e. likely product backlog
