### ISSUE TITLE
Include extra replay data in vat transcripts

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#6770]
## What is the Problem Being Solved?

When replaying vats with the `replay-transcript.js` tool, some information is useful or necessary to ensure fidelity of the replay with the original:
- The schedule of heap snapshot saves: they cause a forced GC impacting the following state of the worker
- The computrons used by a delivery influence the Swingset execution (through the run policy) but cannot be matched during replay with the tool.

## Description of the Design

This data should be included along other vat transcript data in the stream store.
I believe stream store additions are not currently part of the activityHash generation, but even if it were, both of these are effectively part of consensus operations already, so they could safely be included even then (we decided to move heap snapshots hashes under consensus for state-sync, see https://github.com/agoric/agoric-sdk/issues/3769).

## Observation

While we've also seen reload from snapshot triggering bugs in XS and impacting further execution, these operations should not be included in the transcript data because:
- loading is not an operation performed under consensus
- these are XS bugs which should disappear over time (see https://github.com/Agoric/agoric-sdk/issues/5330)
- the slog records those load from snapshot already
- the replay tool is able to fork its execution on snapshot taking, allowing to explore the space of divergence more fully (https://github.com/Agoric/agoric-sdk/pull/6723)

## Test Plan

Some unit test to verify data is included. No integration test exists for the replay tool.

**Comment by mhofman** [comment]
@FUDCo this is the extra info I mentioned we should have recorded in the transcript.

**Comment by warner** [comment]
I'm working on this now, on top of the groundwork in PR #7428

**Comment by warner** [comment]
Both heap snapshot saves (with snapshotID hashes in the results) and computrons spent during delivery (also in the results) are now included in the transcript, thanks to #7484.

We also add `load-snapshot` transcript entries, whose arguments include the snapshotID. These entries are always included, immediately after the `save-snapshot` (but in the subsequent transcript span), even though the kernel is free to either continue using the existing worker, or to discard the worker and launch a new one. Thus the kernel's worker-reuse policy is *not* part of consensus.

All transcript entries (including results) are folded into the current-span hash, which causes an update to the swing-store export data, which makes them part of consensus.

Declaring victory on this one.
