### ISSUE TITLE
stale comment in addRecognizableValue ?

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6778]
While accidentally rediscovering #4834, I came across a [comment](https://github.com/Agoric/agoric-sdk/blob/229708bcc66afa53dbab929ce1826787942179f7/packages/SwingSet/src/liveslots/virtualReferences.js#L460-L474) in [`addRecognizableValue()`](https://github.com/Agoric/agoric-sdk/blob/229708bcc66afa53dbab929ce1826787942179f7/packages/SwingSet/src/liveslots/virtualReferences.js#L495) which might be stale:

```js
  /**
   * A map from vrefs (those which are recognizable by (i.e., used as keys in)
   * VOM aware collections) to sets of recognizers (the collections for which
   * they are respectively used as keys).  These vrefs correspond to either
   * imported Presences or virtual objects (Remotables do not participate in
   * this as they are not keyed by vref but by the actual Remotable objects
   * themselves). We add to a vref's recognizer set whenever we use a Presence
   * or virtual object as a key into a weak store instance or an instance of
   * VirtualObjectAwareWeakMap or VirtualObjectAwareWeakSet.  We remove it
   * whenever that key (or the whole collection containing it) is deleted.
   *
   * A recognizer is one of:
   *   Map - the map contained within a VirtualObjectAwareWeakMap to point to its vref-keyed entries.
   *   Set - the set contained within a VirtualObjectAwareWeakSet to point to its vref-keyed entries.
   *   deleter - a function within a WeakStore that can be called to remove an entry from that store.
   */
  /**
   * @typedef { Map<string, *> | Set<string> } Recognizer
   */
  /** @type {Map<string, Set<Recognizer>>} */

  const vrefRecognizers = new Map();
```

Before #4834 was fixed by #5059 (by moving the recognizer edges into the vatstore), we used this `vrefRecognizers` to track these edges. The key of this Map is the baseref of a virtual object, and the value describes the (weak) collection that can recognize it (by virtue of the vobj being used as a key in a WeakMap, or as a member of a WeakSet).

Originally, this was only used for `VirtualObjectAwareWeakMap/Set`, which are not themselves virtual, so they consume RAM, and therefore any auxilliary tables (like these reference trackers) are also allowed to consume RAM: it doesn't violate our memory goals. So the values in `vrefRecognizers` were either the underlying (real) Map or Set, from which we should delete the vref if/when the virtual object went away.

Then we added virtual collections, some of which are weak, and these had the same need for tracking recognizability. At that time, I think `vrefRecognizers` grew to include a third type of value, which was a `deleter` function owned by a specific (virtual, weak) collection. But that violated our memory goals (holding tracking data in RAM for a purely virtual object), so #4834 was about fixing it. #5059 moved that table into the vatstore.

But I'm thinking that the comment didn't get updated. The typedef did, but the prose still talks about a `deleter`, and the third sentence says "as a key into a weak store instance" which I think is no longer a real case.

Anyways, I got tripped up by the comment while working on something else, and thought I'd discovered a memory-consumption bug, when in fact the bug was fixed 9 months ago.

**Comment by warner** [comment]
@FUDCo does that story seem right to you?

**Comment by FUDCo** [comment]
I just reread the code the uses this map and I believe you are right: the `vrefRecognizers` map is no longer used for virtual recognizers.  Feel free to update the comment or assign this issue to me and I will update it.
