### ISSUE TITLE
switch to new marshalling format everywhere

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6822]
## What is the Problem Being Solved?

During today's show-and-tell presentation by @samsiegart , @erights noticed that the chain-storage published data was still using the old `@qclass` serialization format. We switched SwingSet to use the `serializeBodyFormat: 'smallcaps'` format in f289ec0868bf66ab3d48b32e5933ef12aa3a9edc (#6326), but there are other places in agoric-sdk which use `makeMarshal` to serialize data, which are still using the old format. I found the following with `rgjs -w makeMarshal |grep -v test |grep -v SwingSet | grep -v import`:

```
cache/src/store.js:  const { serialize: keyToJsonable } = makeMarshal(valToSlot);
casting/src/defaults.js:    unserialize: makeMarshal(undefined, slotToVal).unserialize,
cosmic-swingset/src/chain-main.js:      const marshaller = makeMarshal();
deploy-script-support/src/code-gen.js:const { serialize } = makeMarshal();
notifier/src/storesub.js:  marshaller = makeMarshal(undefined, undefined, {
vats/src/lib-board.js:    ...makeMarshal(val => {
vats/src/lib-board.js:    ...makeMarshal(
wallet/api/src/lib-dehydrate.js:  const { serialize: dehydrate, unserialize: hydrate } = makeMarshal(
wallet/api/src/lib-wallet.js:  const { unserialize: fillInSlots } = makeMarshal(noOp, identitySlotToValFn, {
wallet/api/src/marshal-contexts.js:    ...makeMarshal(valToSlot, slotToVal),
wallet/api/src/marshal-contexts.js:    fromBoard: makeMarshal(valToSlot.fromBoard, slotToVal.fromBoard, {
wallet/api/src/marshal-contexts.js:    fromMyWallet: makeMarshal(valToSlot.fromMyWallet, slotToVal.fromMyWallet, {
```

The basic fix is to add `serializeBodyFormat: 'smallcaps'` to the `options` bag, but since the chain already has IAVL-tree data in the old format (which *won't* go away during the bulldozer upgrade), we must make sure the client-side tools that follow that data will be able to handle both. `makeMarshal` is tolerant of both, but if we have any other code that thinks it knows about the serialization details, that code will need to change.

We had originally planned to drop read-side support for the old format from `makeMarshal` after completing the transition of all clients. However the presence of old-format IAVL data on the chain may prevent us from doing that, or perhaps preventing the client code from upgrading to a newer version of `makeMarshal`.

BTW, `makeMarshal` lives in the Endo project/repository.

## Test plan

Most of these should work automatically by the Casting abstraction.

- [x] dapp-psm works with new format
- [x] agoric-cli and agops commands work with new format
- [x] dapp-inter works with new format
- [x] dapp-econ-gov works with new format
- [x] wallet-app works with new format
- [x] https://github.com/p2p-org/p2p-agoric-vstorage-viewer/ works with new format

**Comment by mhofman** [comment]
Please consider also doing https://github.com/Agoric/agoric-sdk/issues/6879 / https://github.com/endojs/endo/issues/1478 if/when doing this.

**Comment by dckc** [comment]
I just made #7013 to explore changing the board marshaller and hence smart wallet etc.

As to the others...

> cache/src/store.js:  const { serialize: keyToJsonable } = makeMarshal(valToSlot);

I'm not sure about that one... I suspect it's not used. @michaelfig ?

> casting/src/defaults.js:    unserialize: makeMarshal(undefined, slotToVal).unserialize,

That's unserialize-only; it will Just Work.

> cosmic-swingset/src/chain-main.js:      const marshaller = makeMarshal();

That one goes to chainStorage. I should add it to #7013 .

> deploy-script-support/src/code-gen.js:const { serialize } = makeMarshal();

The output of that one is fed immediately to `decodeToJustin`, so it's invisible. (might be worth upgrading anyway)

> notifier/src/storesub.js:  marshaller = makeMarshal(undefined, undefined, {

adding that to #7013

> vats/src/lib-board.js:    ...makeMarshal(val => {
> vats/src/lib-board.js:    ...makeMarshal(

That's where I started.

> wallet/api/src/lib-dehydrate.js:  const { serialize: dehydrate, unserialize: hydrate } = makeMarshal(
> wallet/api/src/lib-wallet.js:  const { unserialize: fillInSlots } = makeMarshal(noOp, identitySlotToValFn, {

I think those are only used in the ag-solo wallet.

> wallet/api/src/marshal-contexts.js:    ...makeMarshal(valToSlot, slotToVal),
> wallet/api/src/marshal-contexts.js:    fromBoard: makeMarshal(valToSlot.fromBoard, slotToVal.fromBoard, {
> wallet/api/src/marshal-contexts.js:    fromMyWallet: makeMarshal(valToSlot.fromMyWallet, slotToVal.fromMyWallet, {

I suspect `marshal-contexts.js` is dead code. I should try pruning it to be sure.

**Comment by warner** [comment]
On one hand, smaller serialized data means fewer bytes published to IAVL, which will speed up validators (slightly) and speed up client access (slightly), which are good.

On the other hand, asking off-chain developers to use a custom deserializer for the data they fetch from the chain is a drag. OT3H they pretty much have to do that for the old format too, since JSON doesn't even support BigInts (which are pervasive in the data we publish), but at least plain `JSON.parse` on the old format doesn't throw, whereas the deliberate leading `#` in the smallcaps format (used to distinguish between old and new) raises the entry bar to even get started experimenting with a decoder (which we know folks will do anyways, no matter how well we document the format).

I think that, if it doesn't cause insurmountable problems for the front end, that we should make this change while we still can (i.e. before the release).

**Comment by dckc** [comment]
@warner note https://github.com/Agoric/dapp-inter-jumper/commit/8ac016bbef70003e6b96ed981e93423909fad8a8#r100912032

for follow-up, see

 - https://github.com/Agoric/dapp-inter-jumper/issues/6

**Comment by dckc** [comment]
I gather @warner and @FUDCo have done their bit and @samsiegart is checking the dapps.

**Comment by ivanlei** [comment]
All done!
