### ISSUE TITLE
make swingset import E and Far from @endo/far

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6830]
## What is the Problem Being Solved?

qv #3833, we should make sure that everything that needs `E` or `Far` from Endo are getting them from `import { E, Far } from '@endo/far';`, not from `@endo/marshal`, which will untangle some of our dependencies.

It looks like most everything in `packages/SwingSet/` is still importing from `@endo/marshal`.

## Description of the Design

```js
import { makeMarshal } from '@endo/marshal';
import { E, Far, passStyleOf, Remotable } from '@endo/far';
```

**Comment by erights** [comment]
A lot of this would already be done by https://github.com/Agoric/agoric-sdk/pull/6792 . Please have a look.

**Comment by FUDCo** [comment]
Questions:
- It looks like everything in SwingSet imports `E` from `@endo/eventual-send`, not `@endo/marshal`, but it still could be imported from `@endo/far` it that's what we want.  Which is The Way? 
- The title suggests the issue is `E` and `Far`, but the text suggests also `passStyleOf` and `Remotable` should be imported from `@endo/far`.  Is this so?  (In particular, as I read it, `@endo/far` does not actually export `Remotable`, so I think that bit of the spec at least is wrong).

**Comment by warner** [comment]
cc @erights who probably has the canonical answers

You might also poke around https://github.com/endojs/endo/tree/master/packages and see if you can identify the package which actually owns those exports (as opposed to re-exporting them their original home).

**Comment by erights** [comment]
`@endo/far` currently exports `E`, `Far`, `getInterfaceOf`, and `passStyleOf`. @FUDCo you are correct that it does not export `Remotable`. `Remotable` (in contrast to `Far`) is for more specialized use, and should remain not exported from `@endo/far`. In retrospect, I think we should not have exported `getInterface` from `@endo/far`, but it is more arguable, so I'm not inclined to try changing it.

Modules in agoric-sdk that need any of `E`, `Far`, `getInterfaceOf`, or `passStyleOf` should prefer to import them from `@endo/far`. `Remotable` should prefer to be be imported from `@endo/pass-style` over `@endo/marshal`.

All this is very subjective and not based on clear criteria. If you have any clear criteria to suggest, please let me know.

**Comment by FUDCo** [comment]
Currently if you try to import `Remotable` from `@endo/pass-style` you get a jillion type check errors from TypeScript, so I'm leaving that alone for now.

**Comment by erights** [comment]
Leaving those alone is fine.
