### ISSUE TITLE
Add Minimum Initial Debt to vault-governed parameters

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#6837]
## What is the Problem Being Solved?
We need minimum initial debt to be a governed parameter at the vault manager level which the EC should have control over. Having a minimum initial debt amount holds users to a certain debt commitment, reduces risk of DoS attacks and helps avoid excessive small transactions on chain.

## Description of the Design

1. Add 'Minimum Initial Debt' as a vault-governed parameter by the EC.
2. Do not allow user to open a vault unless they have enough collateral to mint this minimum amount
3. Do not include vault creation fee (loan fee) in calculating this minimum amount

**Comment by dckc** [comment]
I'm pretty sure this is a dup of #4967.

**Comment by otoole-brendan** [comment]
Per latest conversation https://agoricopco.slack.com/archives/C038TM0EUKG/p1678311223466859?thread_ts=1677543546.876889&cid=C038TM0EUKG , there is no longer a requirement for this to be vault manager-level and is fine to be at a director-level (across all vault and collateral types) (i.e. as per current implementation)
