### ISSUE TITLE
upgrade uses of Ubuntu to 22 LTS

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6840]
## What is the Problem Being Solved?

Our CI jobs use Ubuntu 18 (since perhaps  https://github.com/Agoric/agoric-sdk/issues/3709) and [version 18 hits EOSS in April 2023](https://wiki.ubuntu.com/Releases).  [Github Actions intends to stop supporting it April 1st](https://github.com/actions/runner-images/issues/6002).

## Description of the Design

Update to Ubuntu 22 LTS (Jammy Jellyfish) which is supported until 2027.

Solve the known problem with Ansible in deployment-test. ([discussion](https://github.com/Agoric/agoric-sdk/pull/6832#discussion_r1085566928)) This is likely the bulk of the work.

## Security Considerations
Get off unsupported OS

## Scaling Considerations
--

## Test Plan

Use `force:integration` on the PR before review because Ansible is only exercised in deployment-test.

**Comment by mhofman** [comment]
For anyone coming to look at this, I had a stab at trying this in April 2022. [Slack notes](https://agoricopco.slack.com/archives/C038TEA5YTG/p1651269345758209) indicate it was possibly because we're using Debian `buster` to generate some Docker images for deployment.

**Comment by turadg** [comment]
Two of my PRs were just disembarked from the merge queue because they failed "deployment test" due to a brownout. (Url quoted to not link: `https://github.com/actions/runner-images/issues/6002`)

<img width="1554" alt="Screenshot 2023-02-07 at 12 14 04 PM" src="https://user-images.githubusercontent.com/21505/217355165-3f1be9ad-97a8-490f-90e7-5c0c55a98043.png">

**Comment by mhofman** [comment]
Ugh that's gonna become a problem. Nothing we can do about it today, but we should try to fix before Feb 21.
