### ISSUE TITLE
Rename pattern function `fit` to something better

### ISSUE THREAD

**Issue by FUDCo** [Agoric/Agoric#6844]
## What is the Problem Being Solved?

I had an objection to the function name `fit` in my review of PR #6819 on the grounds that it was misleading.

In normal English usage "fit" means “make it fit” or “determine what will be needed to make it fit” — it suggests that the function is going to do something active to bring about compliance, when that’s not the case.  Here we want something that connotes “does it fit?” or “fail if it doesn’t fit”.

## Description of the Design

After some discussion, @erights and I agreed that the most suitable replacement is `mustMatch`.  Mark requested I file a ticket to keep track, hence this issue.

The most complicated thing is choreographing the rename operation, as much of the relevant code is in the midst of migrating Agoric-sdk to the Endo repository, but I have faith that Mark is up to it.

**Comment by erights** [comment]
> but I have faith that Mark is up to it.

I am not volunteering to do this change. Reassigned back to @FUDCo
