### ISSUE TITLE
an `object` InvitationSpec to target arbitrary objects through smart wallet

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6850]
## What is the Problem Being Solved?

The smart wallet currently supports three sources of invitations:
- `contract` takes an instance of the contract
- `purse` takes an instance of the contract that made the invitation which is in the wallet's Invitations purse
- `continuing` takes a previousOffer id to get its invitationMakers object

For use cases like https://github.com/Agoric/agoric-sdk/issues/6518 we need to be able to call methods on objects that aren't instances or the result of a previous offer.

## Description of the Design

A new InvitationSpec for `source: 'object'` which takes an `object` ref and `method` string argument to specify what to call on that object.

How do we name the objects? maybe from `agoricNames.objects` instead of the board. 

Can we point to sub-objects? Ideally but TBD

**Comment by samsiegart** [comment]
>Can we point to sub-objects?

I wonder if we can serialize E() calls into promises that the smart wallet can unserialize and await?

**Comment by samsiegart** [comment]
> I wonder if we can serialize E() calls into promises that the smart wallet can unserialize and await?

This doesn't seem to be straightforward with our current architecture. I'm not sure how to serialize such a thing from the UI side. Simply changing from `E(marshal).serialize(instance)` to `E(marshal).serialize(E(instance).foo())` throws with `target has no method "foo", has []`. Maybe we have to change the import context or something.

cc @michaelfig @dckc

**Comment by michaelfig** [comment]
> I wonder if we can serialize E() calls into promises that the smart wallet can unserialize and await?

No need to use `E()` (which is too general, and runs into current limitations of the ocap fabric).  Just directly encode chained calls like:

```js
  E(E(target)[method](...args))[method2](...args2)
```

in a recursive call specification like:

```js
  { source: 'call', spec: [[target, method, args], method2, args2] }
```

It's up to you if you want to prevent recursive calls (maybe only enable them later), but this general approach would be enabled by the `[target, method, args]` convention.

Tangibly, if you need to look stuff up in agoricNames, you could allow something like:

```js
// E(E(agoricNames).lookup('object', 'abc123'))[method](...args);
const spec = [['agoricNames', 'lookup', ['object', 'abc123']], method, args];
```
