### ISSUE TITLE
EC charter power to update value of well-known name for UI hosting

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6860]
## What is the Problem Being Solved?

For decentralized dapp hosting (#4350), an elected body such as the EC needs the ability to update a hash under a well-known name such as `published.vaults.governance`.

## Description of the Design

Add a `uiVersionHash` to the vault factory governed parameters.

## Security Considerations

This is a solution to a bunch of security constraints explored in #4350 .

## Scaling Considerations

The on-chain work is like any other EC decision (IOU # of known issue there).

There's a bunch of off-chain fan-out, but that's outside the scope of this issue.

## Test Plan

unit test

**Comment by arirubinstein** [comment]
example hash: `QmWGhGssVvEnG8b8TEftMSfE6HXsy96CXTNfB1QLWmYRcW`

**Comment by dckc** [comment]
idea: make the hash a governed parameter of the vaults contract.
