### ISSUE TITLE
PSM dapp, wallet poll RPC nodes rapidly

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6870]
## Describe the bug

When using our wallet or PSM dapp, the browser makes a dozen or so requests per second to an RPC server.

@arirubinstein noted a cosmos community operational norm of <= 2 requests / second per client on RPC servers.

## To Reproduce

1. Open the wallet and/or dapp-psm
2. Connect your keplr wallet
3. check the browser console and/or network inspector
4. see many more than 2 requests per second to RPC node as we poll every ~400ms at N vstorage keys etc.

_This is from memory. IOU a more direct observation, including log exerpt._

## Expected behavior

 - [ ] rate limiting to <= 2 requests per second to any 1 RPC server

I gather from @michaelfig that there are plans for `@agoric/casting` to meanwhile support

 - [ ] batching https://github.com/Agoric/agoric-sdk/issues/7155
 - [ ] fail-over among multiple RPC nodes

https://github.com/Agoric/agoric-sdk/issues/6647 will reduce HTTP requests by half.

## Platform Environment

mainnet / prod; any browser / os

_IOU one example of all these details_

 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context

A community member trying out dapp-psm asked why it was making so many requests so rapidly, noting several requests per second in their browser console. (_I thought they opened an issue, so this might be a dup_.)

@samsiegart and @turadg and I have noted this in a couple recent PRs (back-links to follow).

## Screenshots

_IOU log excerpt_

**Comment by dckc** [comment]
[test-watch-balances.js](https://github.com/Agoric/agoric-sdk/blob/dc-wallet-balances-dry/packages/agoric-cli/test/test-watch-balances.js) is WIP (https://github.com/Agoric/agoric-sdk/pull/6807) to read `x/bank` balances using casting, to get

  - proofs
  - multi-RPC-node fail-over
  - batching

and all those goodies.

### cannot push to something in xstream

It currently fails a la...

```
@@balances {
  value: '\n\fibc/usdc1234\x12\n1476000000',
  blockHeight: 1761,
  currentBlockHeight: 1761
}
retrying CosmJS follower (round-robin endpoints) in 880ms after attempt #0 (TypeError#1)
TypeError#1: Cannot add property 0, object is not extensible

  at Array.push (<anonymous>)
  at packages/casting/src/follower-cosmjs.js:159:33
```

grr... somebody is monkeying with the stack trace. line 159 is `const info = await client.abciInfo();`

With the JS debug console, I can see the offending `.push()`. But it's deep in `xstream`, inside some cosmjs stream thing. I suppose we hardened something that somebody wasn't expecting to be hardened, but I'm having a hard time seeing what.

**Comment by dckc** [comment]
interim approach: reduce polling frequency... perhaps something around the block time

**Comment by samsiegart** [comment]
I'm observing that the default behavior is to jitter about every 2-4 seconds. We could maybe do every 8 seconds for a ~2-3x reduction in cost without much noticeable UX difference. A longer reduction might be poor UX if users see, for example, offers completing but their vault dashboard not updating for a long time.

<img width="309" alt="Screenshot 2023-04-26 at 1 28 07 PM" src="https://user-images.githubusercontent.com/8848650/234694725-d64f970e-af34-44ec-a97e-42d899b1236d.png">

However, I think the real problem is these queries keep going as long as you have the window open. So, someone who incidentally has several tabs open for hours will rack up a lot of data transfer (I estimate 2 MB transferred per minute per `dapp-inter` tab). We could try not querying if the app isn't in focus, but users might have it open on the side expecting it to update while they interact with a different window.

It's probably best to just go straight for the websocket/long-polling solution.

**Comment by samsiegart** [comment]
Actually, looks like `document.hidden` is smart enough to know whether the window is out of focus and hidden or just out of focus: https://iamsahilralkar.github.io/document-hidden-demo/

Maybe we can just try 8 second jitters, only when `document.hidden` is `false` before moving to websockets.

**Comment by dckc** [comment]
nice work, @samsiegart and co!

These fixes were measured to **reduce requests by 90% and traffic by 97%**, IIRC.

@samsiegart please correct me if I'm off by much.

**Comment by samsiegart** [comment]
@dckc Yes, that's about right. Depends on which UI, as not every request is going through this new library and some have more requests to batch, but enough that we're under the 2 qps norm.

=========================

Dapp-inter RPC efficiency improvements, as measured on emerynet when using gov1 account with 9 open vaults...

[Old dapp-inter ](https://bafybeibxidzkf3kb3xnhc7qpimdw4r7v3e43w7pvio3z7zu32jygyqetza.ipfs.cf-ipfs.com/#/vaults)using casting/proofs: 2800 requests, and 3.8MB per minute

[New dapp-inter](https://bafybeihvfdfrc4ehziau2u55yj4w7ftgs52whjwgldv5yxq275rqhdublu.ipfs.cf-ipfs.com/#/vaults) using [batch queries](https://github.com/Agoric/dapp-inter/pull/140): 36 requests and 150KB per minute

A 98.7% decrease in QPS, and 96% decrease in bandwidth!
