### ISSUE TITLE
IBC Deposit and Withdrawal Front End Component

### ISSUE THREAD

**Issue by jeetraut** [Agoric/Agoric#6872]
## Description
Build a front end component that application developers can use to allow their users to deposit and withdraw IBC assets to/from the Agoric chain. Start with ATOM and the Cosmos Hub chain.

Component should pop up as a modal which walks the user through the flow.  For example, to deposit ATOM to the Agoric chain
Display available ATOM on the Cosmos Hub
Allow the user to choose an amount to deposit
Deposit amount must be less than the amount available, leaving enough room for any transaction/IBC transfer fees
Allow the user to trigger the transaction
Detect and display when the transaction has completed
Display success with current ATOM on the Agoric chain and allow the user to close the modal

## Context
The next Inter Protocol release for vaults will need to allow users to deposit and withdraw funds from other IBC-connected chains, starting with ATOM.  This component will be important in the primary user flows.

## Acceptance Criteria
User can deposit ATOM from the Cosmos Hub to the Agoric chain
User can withdraw ATOM from the Agoric chain to the Cosmos Hub
Modal front end flow works as shown in Description
User prevented from overspending to run out of gas
Failed transactions gracefully handled

## Time Estimation
2 weeks

## Reward
$6,400

Payment will be made in USD (fiat currency) via wire transfer. The developer is responsible for providing their completed tax documents (W9 for US based developers and/or W8 or W8-BEN-E for non-US based developers) and providing their banking details in order to receive payment. 

## Applicant Assessment Criteria
Important: Please provide a clear work plan for how you will approach this bounty.  Use the work plan as an initial demonstration that you would be a good candidate.  Bounties will require coordination with the Agoric team, so unfortunately only plans submitted in English will be considered.

Applicants will be assessed based on the following criteria: 
* Issue-specific domain experience
* Issue-specific technical capability
* Familiarity with Agoric's platform
* JavaScript experience
* Availability and communication

## Experience Write-up (1000-1500 words)
As part of completing the bounty, we ask that you write up a short (or long!) summary of your experience building on Agoric. Write-up should:
Begin with a compelling, relevant introductory hook statement (<50 words). 
Clearly explain the specific bounty project (~100 words). 
Describe how the developer approached the problem (~300 words). 
Give a step-by-step description of the solution (>500 words && <1000 words).
At least three code snippets per write-up. They do not count toward overall word count. 
Conclude with clear calls to action on developing with Agoric - specifically how any ambition developer reading this piece could do more themselves (~100 words). 
This is important feedback for us as we evolve the platform.

## Review Process
* Agoric team reviews your submitted work plan on Gitcoin
* It is best to join our Discord and post your gitcoin name in the bounties channel, so that we can follow up with you. Otherwise, we will write on your gitcoin profile wall and say hello!
* Agoric contacts you to provide reference projects / sample code for engineering review
* Introductory call to discuss your plans and expected timeline
* You join the Agoric Discord bounties channel (if you haven’t done so already) 
* Agoric accepts you on Gitcoin and you get started!

## References
- Reference app.stride.zone as a good example of this flow done for depositing ATOM
- Reference app.osmosis.zone -> assets page as an example of deposit/withdraw (not via Modal)
- [Agoric Documentation](https://docs.agoric.com/)
- #bounties channel in Discord

**Comment by ManyRios** [comment]
Hi! is this bounty still open to work on it?
