### ISSUE TITLE
Document Bot Bidding Process for Liquidations

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#6889]
## What is the Problem Being Solved?
Since we're launching without a Liquidation Bidding UI, the only way users can bid on liquidated collateral is via API endpoints. Given this, we need to document how one would go about bidding this way so it's clear and can be communicated appropriately come launch.

We are working off the assumption that this audience is relatively technical and are familiar with CLI

## Description of the Design
@Chris-Hibbert to provide documentation around how this works to explain process to would-be bidders

## Security Considerations
Unknown
## Test Plan
TBD

**Comment by dckc** [comment]
@otoole-brendan as we just discussed, bidders (the audience of this documentation) are expected to have basic [CLI](https://en.wikipedia.org/wiki/Command-line_interface) knowledge, which makes this more feasible than #6281 turned out to be.

**Comment by otoole-brendan** [comment]
Thanks @dckc updated body of issue to reflect that

**Comment by ivanlei** [comment]
When #6930 is completed, @otoole-brendan will meet with @dckc to get up to speed on the tool and create the user facing documentation.

**Comment by dckc** [comment]
The initial bidding cli code comes with some reference docs:

https://github.com/Agoric/agoric-sdk/blob/master/packages/agoric-cli/test/snapshots/test-inter-cli.js.md

**Comment by otoole-brendan** [comment]
Documented: https://docs.inter.trade/user-how-to/bidding-for-liquidated-collateral
