### ISSUE TITLE
offer exit ability through smart wallet bridge

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6906]
## What is the Problem Being Solved?

An offer may take longer to satisfy than the user can tolerate. Currently a vault opening or balance adjustment waits for the latest price from an oracle and if oracles are paused then the offer resolution would also be paused.

While an offer is in flight, the user's funds are escrowed by Zoe. So the problem is that users don't have access to their wants or their gives.

## Description of the Design

Make the smart wallet take an `exitOffer` message that calls `tryExit` on the seat of an earlier `executeOffer`.

**Comment by erights** [comment]
> Exiting an offer is essential for ERTP. 

I think you mean "essential for Zoe". ERTP has no idea what an offer is or what exiting one would mean.

**Comment by samsiegart** [comment]
Discussed with @turadg- we'll revisit this after https://github.com/agoric/agoric-sdk/issues/6992 lands to see if there's any multi-turn offers in the implementation. Otherwise this is not worth implementing for EVP.
