### ISSUE TITLE
Vault fee distribution is controllable by BLDer DAO

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#6926]
## What is the Problem Being Solved?
Currently, the feeDistributor contract collects fees earned from Vaults and distributes them in proportion between the Reserve and the "Reward Pool."  This proportion currently is not easily changeable through governance.  This ticket is to give control of this distribution routing to the BLDer DAO

## Description of the Design
From Slack conversation: An `adjustRewardShares` method on the `feeDistributor` `creatorFacet` would make it a lot easier for the BLDer DAO to tweak that at will.

**Comment by dtribble** [comment]
Also @rowgraus to determine the initial parameter value.
