### ISSUE TITLE
Place Liquidation Bid via CLI

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#6930]
## What is the Problem Being Solved?
In the absence of a liquidation UI for Vaults launch, we will need a means for user (presumably with bots) to be able to place bids for liquidated collateral via CLI

## Description of the Design

_revised by @dckc_

Follow established pattern for commands that format smart wallet offers and sign/send them. See also test plan below.

## Security Considerations

`agoric` cli relies on cosmos-style `agd` for key / keyring management.

## Scaling Considerations

none?

## Test Plan

Among others, test that...

```[tasklist]
 - [x] Users can place bids with a bidding agent as specific prices
 - [x] Users can place bids with a bidding agent as discounts to oracle price
 - [ ] Users can receive the asset(s) purchased by the bidding agent
 - [x] Users can cancel bids and receive their IST back
- [ ] https://github.com/Agoric/agoric-sdk/issues/7249
```

To modify a bid, users can cancel and place another bid.

_Testing has been a mix of manual and automated approaches._

**Comment by otoole-brendan** [comment]
https://github.com/Agoric/agoric-sdk/issues/6889 serves to document how one might follow the CLI bidding process

**Comment by dckc** [comment]
I added some detail to the design, test plan.

**Comment by dckc** [comment]
## modify bid feasible? required?

Having looked at this in a little detail (#7132) I don't see how to do "modify bid". @Chris-Hibbert I don't see support for it in the contract. Did I miss it? Or did you plan to add it?

@otoole-brendan can we do without modify?

I can probably combine "exit bid offer" and "place new bid" into one cli action, if that's close enough... though partial failure makes it tricky.

_p.s. in a user stories doc, I see: "If ‘modify’ is challenging, sufficient to cancel and create a new one - UI could abstract this into a ‘modify’"_

**Comment by Chris-Hibbert** [comment]
> I don't see how to do "modify bid". @Chris-Hibbert I don't see support for it in the contract. Did I miss it? Or did you plan to add it?

I missed this requirement. I have no plans or design. The easiest approach is probably exit and place new bid.

**Comment by dckc** [comment]
## Place priced bid; receive payouts working

```
2023-03-20T23:46:04.918Z SwingSet: vat: v49: ----- VM.11  20 lockPrice { brand: Object [Alleged: IbcATOM brand] {}, value: 1_000_000n } { brand: Object [Alleged: IST brand] {}, value: 2_600_000n }
```

```
$ inter bid list --from gov1 --keyring-backend=test
{"id":"bid-1679355396104","give":{"Currency":"50IST"},"want":"5IbcATOM","price":"0.000009IST/0.000001IbcATOM}","payouts":{"Collateral":"5IbcATOM","Currency":"37IST"}}
```

**Comment by dckc** [comment]
some sequence diagrams:

Notes:
  - dotted lines are "replies" to (or more generally: consequences of) solid lines
  - "10 IST Pmt" denotes a payment of 10 IST -- actual assets -- where "10 IST" is an amount -- just a description of assets.

## Context: Creating a Vault

```mermaid
sequenceDiagram

title Creating a Vault

actor Alice
participant Zoe
participant VaultFactory
participant Oracle

    Oracle->>VaultFactory: pushPrice(12.34)
    Alice->>Zoe: contract: VaultFactory<br>give: 15 ATOM Pmt<br>want: 100 IST
    Zoe-->>VaultFactory: seat1<br>give: 15 ATOM<br>want: 100 IST
    VaultFactory-->>Zoe: reallocate 100 IST for 10 ATOM<br>result: vault0
    Zoe-->>Alice: 100 IST Pmt, vault0
    Zoe-->>VaultFactory: 15 ATOM
```

## Liquidation Bidding

```mermaid
sequenceDiagram

title Liquidation Bidding

actor Alice
participant Zoe
participant VaultFactory
participant Auctioneer
participant Oracle
actor Bob

    Bob->>Zoe: contract: Auctioneer<br>give: 50 IST Pmt<br>want: 5 ATOM<br>price: 10 IST/ATOM
    Zoe-->>Bob: UserSeat 2
    Zoe-->>Auctioneer: seat 2<br>give: 50 IST, want: 5 ATOM<br>price: 9.5 IST/ATOM
    Oracle->>VaultFactory: pushPrice(9.99)
    VaultFactory-->>Alice: vault0 liquidating
    VaultFactory-->>Auctioneer: 15 ATOM Pmt to sell
    Auctioneer->>Zoe: seat: 2<br>reallocate 5 ATOM for 47.5 IST
    Zoe-->>Bob: 5 ATOM Pmt, 2.5 IST Pmt
```
