### ISSUE TITLE
Incorporate security patch from 0.34.25 into tendermint fork

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#6937]
To ensure we are patched against the recent security issue identified in tendermint (https://github.com/informalsystems/tendermint/security/advisories/GHSA-cpqw-5g6w-h8rr), we need to apply this patch to our fork, which is included in 0.34.25

Note - this may require considering 0.34.26 due to dependency requirements:
https://github.com/informalsystems/tendermint/blob/v0.34.26/CHANGELOG.md#v03426

**Comment by JimLarson** [comment]
Closing as a dup of #6945. We don't seem to be running into the dependency problem - probably because we're not on the informalsystems fork yet.
