### ISSUE TITLE
Auction starts after the hour to give liquidator time to liquidate all vaults

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#6949]
## What is the Problem Being Solved?
The liquidator auction should take in all of the vaults which have been liquidated prior to its start.  The processing of those liquidations to hand off to the liquidator will take an unknown amount of time.

## Description of the Design
There is no robust way for the auction to confirm that it has received all vaults subject to liquidation - in particular since in the future the liquidator may receive vaults from multiple vault managers or even assets from other sources.

Initial design is to delay the start of the auction for several minutes to allow time for vault liquidations to process.  Making this delay a governed parameter would allow adjustments by the economic committee if any issues are seen in production

**Comment by Chris-Hibbert** [comment]
The current version of the PR (#7000) has a governed parameter `AuctionStartDelay` that says how long after the nominal auction starting time to wait to allow the vaults to liquidate starting at the nominal time.
