### ISSUE TITLE
devnet oracle addresses

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#6950]

**Comment by dckc** [comment]
The bulk of this seems done as of, if not before, #6957 .

But I suppose we lack the actual **production addresses of the oracle operators**. So I'll leave it open for that and re-assign to @otoole-brendan 


### what we have:

before any proposals:
 - a priceAuthorityAdmin, i.e. a widget for getting a price authority for arbitrary pairs in a proposal to add, for example, ATOM as a vault collateral:
 - a price aggregator contract, where invitations go to oracle operators
 - CLI tools to pushPrice
 - real operator node stuff to pushPrice
 - a scaledPriceAuthority widget to take idealized ATOM/USD prices and convert to ATOM-via-ibc/IST prices
plus:
 - a test widget to get the scaledPriceAuthority to hand out prices before anyone has done any pushPrice
I'm not aware of anything else that might be needed for vaults.

The delayed oracle stuff (#5843) doesn't seem to need more bootstrap config.

**Comment by otoole-brendan** [comment]
Have asked Simply Staking for both devnet and mainnet oracle operator addresses. @dckc where is best place to share these when I receive them?

**Comment by dckc** [comment]
Here in this issue would work for me. Or in a spreadsheet or whatever.

Eventually it ends up in source code; for example:

https://github.com/Agoric/agoric-sdk/blob/f3be9148f79fcd0c89ef26fe88acc30c3fd91787/packages/vats/decentral-main-psm-config.json#L36-L43

**Comment by otoole-brendan** [comment]
@dckc I received the devnet oracle operator addresses from Simply Staking. See below:

P2P - agoric10vjkvkmpp9e356xeh6qqlhrny2htyzp8hf88fk
Simply Staking - agoric1chxpyq88g9vhv7lkje3ap8yexajmwkq66fyfhq
DSRV - agoric1lw4e4aas9q84tq0q92j85rwjjjapf8dmnllnft
01node - agoric1ra0g6crtsy6r3qnpu7ruvm7qd4wjnznyzg5nu4
Stakin - agoric1zj6vrrrjq4gsyr9lw7dplv4vyejg3p8j2urm82

(mainnet addresses still pending though)

**Comment by otoole-brendan** [comment]
Although I just realized you may only care about mainnet addresses...

**Comment by otoole-brendan** [comment]
Tracking dependency of addresses via #7431

**Comment by dckc** [comment]
let's re-scope and close this one, then

**Comment by dckc** [comment]
The more relevant dependency is from

 - #7311
