### ISSUE TITLE
Impose liquidation penalty on liquidated vaults

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#6951]
## What is the Problem Being Solved?
Vaults subject to liquidation are assessed a penalty (a governed parameter controlled by the EC) that is expressed as a percentage of their debt

## Description of the Design
Key points of the design:

* Penalty is taken in the collateral asset (to avoid having to sell it)
* The liquidation penalty % is expressed as a % of debt
* The price to use for the collateral asset when calculating how much of the asset is needed to cover the the penalty in terms of the debt is the **current oracle price at the start of liquidation** (which may be different from the auction start price as the auction starts based on an adjustment of this price)

**Comment by Chris-Hibbert** [comment]
If the auction doesn't raise enough to cover the debt+penalty, the penalty portion shouldn't be reported to the reserve as part of the shortfall.

**Comment by rowgraus** [comment]
More on the liquidation penalty and when to take it is discussed in: https://github.com/Agoric/agoric-sdk/issues/7123 which may subsume this issue
