### ISSUE TITLE
Auction targets a specific amount of IST to raise; returns excess collateral to vault holders

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#6952]
## What is the Problem Being Solved?
Due to overcollateralization of vaults, significantly more collateral may be sent to liquidation than is actually needed to cover debt.  

Vault holders would prefer to receive excess collateral back rather than having it sold.

**Comment by Chris-Hibbert** [comment]
@rowgraus 
 If there are more than one contributor to an auction, do you have a preference for how their limits get combined?  I see two main plausible cases: a) two Vaults with different parameter settings for the same asset, and b) a vault and the reserve, which would likely not want to set a maximum sale.

There are three obvious choices, two of them easy, and the third requiring more work. (for design/test/implement the runtime wouldn't likely matter.)
1) take the minimum proportion of the two (or more) requests. The other vaultManager would get less IST than required to cover the debt
2) take the maximum proportion of the two (or more) requests. The other vaultManager would get IST returned above the debt, and would return it to vaultHolders. (that distribution code is already written.)
3) track the requirements from the two (or more) requests through the auction, so the auctioneer can pro-rate the returns across different asset classes.

If 1) or 2) is acceptable (only) for the near-term, we can put off implementing 3) until we add support for multiple vaultManagers for an asset, or enable the Reserve to sell to the auction. Alternatively, we could make the auctioneer refuse to accept more than one deposit for an asset during one cycle, so the Reserve would be limited to selling during rising markets. This  wouldn't support multiple vaultManagers liquidating the same asset, but we may not be getting to that soon.

**Comment by Chris-Hibbert** [comment]
@rowgraus and I chatted, and he chose 3).

**Comment by rowgraus** [comment]
Answered on call - option #3
