### ISSUE TITLE
consider running high-priority inboundQueue before doing timer.poll()

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6964]
## What is the Problem Being Solved?

related to #4318

To allow high-priority (governance, price oracle) messages compete successfully with everything else, we plan to add a second `inboundQueue` (#5966), and service it before anything in the normal queue. The cosmos side will be responsible for populating it with the right messages.

In a meeting with @arirubinstein and @JimLarson today, I walked through the new order of operations. For each block, when END_BLOCK happens, `launch-chain.js` `endBlock()` will do:

* 1: `timer.poll()`, possibly causing the timer device to push a message onto the kernel run-queue that will tell vat-timer to notify wakers/handlers
* call `runKernel()`, which does:
* 2: do an initial `controller.run()`, which catches up on old work and also does timer-triggered work
* 3: sample the high-priority inbound-queue, do `controller.run()`, repeat until all high-priority items are drained
* 4: sample the low-priority inbound-queue, do `controller.run()`, repeat until all low-priority items are drained

(each `controller.run` stops if we reach the `runPolicy` computron limit, of course)

@arirubinstein suggested that we might want to do 3/1/2/4 instead of 1/2/3/4. Assuming that we were already caught up, that would mean draining the high-priority queue before triggering any timer work. We thought this might protect high-priority inbound messages against some pathological timer things.

refs #4318 

## Description of the Design

Rearrange `launch-chain.js`:
* maybe merge `endBlock()` and `runKernel()`, refactor to make this all easier
* catch up first
* service high-priority queue in a loop, until drained or policy limit reached
* timer.poll(), run, return if policy limit reached
* service low-priority queue in a loop, until drained or policy limit reached

## Security Considerations

DoS maybe?

**Comment by mhofman** [comment]
I think the more appropriate order would be 2/3/1(/2)/4. I don't see a reason not to finish existing work first, and I'm not sure what the benefits would be in the current approach of interleaving remaining work with new timer work.
