### ISSUE TITLE
incomplete recovery from hitting vaults minting limit

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6969]
## Describe the bug

While working on the vaults UI, @samsiegart hit the minting limit and was surprised that his balance didn't recover. Chain log:
https://gist.github.com/samsiegart/2c1a4a563a2fc96fdd7d4383a062f0fc

## To Reproduce

???

1. ~~check out `1323a207983fbdb69aa09752d613d8d695324d4a` aka `dc-refund-durable `.~~

_that test turned out to be faulty; adding `await eventLoopIteration();` made it pass_

## Expected behavior

funds returned

## Platform Environment

 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
Sam was running 1323a207983fbdb69aa09752d613d8d695324d4a when he reported the problem.

## Additional context

_IOU pointer to the issue sam was working on_

## Screenshots

_sam shared a few internally..._

**Comment by dckc** [comment]
update: unit test did _not_ reproduce the problem. it was missing some synchornization.

2dc40e2c5 passes

**Comment by turadg** [comment]
I was unable to repro with PSM.

To repro with VF, make an offer that exceeds maxDebtFor (e.g. insufficient give for the want). 
https://gist.github.com/turadg/ff968f888c41bac607a7a13c5348075e

**Comment by dckc** [comment]
The PSM symptoms came from my faulty unit test. Taking "PSM" out of the description...
