### ISSUE TITLE
add BOYD to upgradeVat sequence

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#7001]
## What is the Problem Being Solved?

As part of #6650, the vat upgrade sequence should perform a BOYD delivery to the old vat just before shutting it down. This will give it one last chance to clean up while it still remembers what needs to be cleaned up:
* recently GCed ephemeral objects can be dropped, which may free up other references
* that might allow some imports to be dropped, and maybe retired, and thus removed from the c-list
* it may drop some virtual objects, allowing their contents to be dropped
* that may drop some durable objects, allowing their durable data to be removed from the vatStore

Currently we do some portion of this cleanup from inside the `stopVat` message, but 1: not enough, and 2: we want to remove the requirement for `stopVat` (to better preserve our ability to upgrade vats that are so broken they can't execute `stopVat`).

## Description of the Design

In kernel.js `processUpgradeVat()`, just before we do the `stopVat` message, create and deliver a `bringOutYourDead` message. The overall process will look just like the way we do `stopVat`: we synthesize a KernelDeliveryObject, translate it into a VatDeliveryObject, submit it to `deliverAndLogToVat`, await completion, retrieve and parse the status. If either the `bringOutYourDead` or the `stopVat` fails, we roll back the upgrade.

The code should include a comment to remind us that the BOYD is optional: if a vat is *so* broken that even BOYD fails, then we could dig ourselves out of the hole by:
* modify the kernel to add a "don't do BOYD" option to `vatAdminFacet.upgrade()`
* in `processUpgradeVat()`, the option says to skip the BOYD delivery and proceed directly to replacing the worker (since we'll have removed stopVat by then)
* deploy a kernel upgrade to the chain
* perform a contract governance action to upgrade the troubled vat without the BOYD step

This would result in more garbage being left behind than usual, but that should only cost us DB space and lingering imports, which is a better state than having the vat remain broken.

## Security Considerations

none, we send BOYD to vats all the time

## Scaling Considerations

This will slow down the vat-upgrade sequence slightly, since we're doing more work. It will probably be comparable to how upgrades used to work, back when we had `stopVat` doing a lot of cleanup (which we disabled to minimize the risk of `stopVat` failing, at the cost of more lingering garbage).

## Test Plan

The tests in `packages/SwingSet/test/upgrade/` have a section which examines the set of imports/virtual/durable state before and after the upgrade, to assert that everything we expect to be cleaned up, has actually been cleaned up:

https://github.com/Agoric/agoric-sdk/blob/f6996583c94e4b1d61160a102f1e92f81cc27bb0/packages/SwingSet/test/upgrade/test-upgrade.js#L267

There is a diagram (https://github.com/Agoric/agoric-sdk/blob/f6996583c94e4b1d61160a102f1e92f81cc27bb0/packages/SwingSet/test/upgrade/object-graph.pdf) which shows the object graph constructed by this test, with annotations to show what must be retained, what can be cleaned up (but currently isn't), and what ought to be cleaned up.

Unfortunately we disabled this portion of the test, probably about the same time we changed `stopVat` to remove the extra cleanup it was doing. But the diagram still covers the space of possible retentions/releases, and the vat code which sets up the object graph is still there.

For this ticket, I think we should examine that diagram and figure out what retentions/releases we expect, and we should re-enable some portions of the test to assert as much as we can about the GC behavior we'll get from a single BOYD. That means an ephemeral object which holds onto an import (which, now that I look at it, might need to be added to the digram) should be collected during BOYD, and thus emit a `dropImports` and `retireImports` for the import. This could be added to the test as a separate object, without untangling the disabled portion of the test.

**Comment by gibson042** [comment]
> just before we do the `stopVat` message, create and deliver a `bringOutYourDead` message

This might just be academic, but do we want BOYD _before_ stopVat or _after_ it? The current implementation of stopVat is basically `releaseOldState(…)`, and that function ends with `bringOutYourDead()` (followed by a commented-out block that itself also ends with `bringOutYourDead()`). And it's certainly conceivable that stopVat would leave some state that BOYD could clean up.

**Comment by warner** [comment]
I think we want to declare that `stopVat` is not obligated to leave the vat in a usable state (liveslots would be within its rights to set a flag and refuse any subsequent deliveries). So I'd say BOYD should happen before `stopVat`, not after.

This probably means that adding BOYD to `upgradeVat` should happen in the same PR which removes the `stopVat`, or at least in one that empties `stopVat` entirely.
