### ISSUE TITLE
Unable to open vault on loadtest, resulting in loss of funds

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#7005]
## Describe the bug
On loadtest, in the gov2 wallet, I'm unable to open a vault. It gives me an offer, after signing, the offer does not get rejected, and after a wallet refresh, the offer status goes back to proposed.  There is no vault created.

Despite signing this and the offer appearing to fail, I lose my 100 atom from my wallet, and the cosmos chain.

The smart wallet doesn't appear to have recorded any offers either:
```
AGORIC_NET=loadtest agoric wallet show --from agoric140dmkrz2e42ergjj7gyvejhzmjzurvqeq82ang
```

Git Commit: 52646a
Docker Tag: 20230215214838-52646a-linux_amd64

## To Reproduce
1. Goto https://bafybeiam5ccaokbftxs4bhiozarooneuhdti42nnam6fptku36tbdqkghq.ipfs.cf-ipfs.com/?network=loadtest&wallet=main
2. join wallet at https://main.wallet-app.pages.dev/wallet/ (network connection https://loadtest.agoric.net/network-config ) 
3. switch keplr to the gov2 wallet
4. Ensure you have at least 200 BLD in your wallet.  if not, get some at loadtest.faucet.agoric.net
5. attempt to open a vault with ~100 BLD
6. BLD goes away from your wallet, and no vault is created

## Expected behavior

vault is created, and no tokens are lost

**Comment by turadg** [comment]
That the offer fails is due to unfinished work: https://github.com/Agoric/agoric-sdk/issues/6957.

That the failure results in loss of assets is due to a bug: https://github.com/Agoric/agoric-sdk/issues/6969

I think this should be closed once the garden path offer is shown to work in loadtest. The other bug will stay open until resolved.

**Comment by ivanlei** [comment]
I was able to open a vault on loadtest following these instructions - except using ibcATOM collateral.
