### ISSUE TITLE
Chain fails to start - cannot locate the bindings file

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#7007]
## Describe the bug

While testing upgrade, I did the following sequence:

- checked out the repository at `agoric-upgrade-8-1`
- built everything
- started the chain
- did a governance proposal to upgrade to `upgrade-9`
- it halted as expected
- checked out at `release-pismo`
- rebuilt
- tried to restart the chain

and the restart failed with the following error:

```
2023-02-16T04:00:38.766Z launch-chain: Launching SwingSet kernel
portHandler threw (Error#1)
Error#1: Could not locate the bindings file. Tried:
 → /Users/jim/agoric-sdk/node_modules/better-sqlite3/build/better_sqlite3.node
...
```

Following a suggestion from @mhofman I removed the `node_modules` directory and redid the build. The chain was then able to start.

## To Reproduce
- Follow the [upgrade testing procedure](https://www.notion.so/agoric/Testing-Upgrades-b2e003b2121244508930d995ee2abd5c)
    - except `export UPGRADETO=agoric-upgrade-9`
- Build steps are
    - `yarn install`
    - `yarn build`
    - `(cd packages/cosmic-swingset && make)`

## Expected behavior
The chain should be able to halt, upgrade, and restart via the normal `yarn` and `make` instructions, without having to remove `node_modules`.

## Platform Environment
 - what OS are you using? what version of Node.js?
     - macOS Ventura 13.1
     - node.js v16.19.0
 - is there anything special/unusual about your platform?
     - no
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
     - says `agoric-upgrade-8-1-40-gb9efe84b0` but `git status` shows me up-to-date with `release-pismo`

**Comment by mhofman** [comment]
Yeah I don't think anything can really be done about this. It's a quirk of yarn/npm and of some dependencies. We may need to find more reliable update commands and update the instructions with them.

**Comment by JimLarson** [comment]
Surely there must be something we can do for those who are upgrading, even if it inconveniences development? Could we add yarn instructions to remove that directory as the first action when running `yarn install`? Is this something that affects all future upgrades, or just this one?

**Comment by JimLarson** [comment]
Many suggest that an earlier upgrade-then-downgrade of node might have caused this issue. The command `yarn install --force` will have the effect of clearing the `node_modules` file, and might be a safer procedure for those trying to upgrade, so I'm going to close this bug in favor of a doc fix for the force flag.
