### ISSUE TITLE
eliminate stagings in Vaults Release code

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7025]
## What is the Problem Being Solved?

The staging mechanism has flaws such as,
- https://github.com/Agoric/agoric-sdk/issues/3850

Thus we need to,
- https://github.com/Agoric/agoric-sdk/issues/6678

For the vaults release we don't have to remove them all, just the ones going on chain.

## Description of the Design

Verify none of these,
- stageDelta
- reallocate
- incrementBy
- decrementBy

are used in these contracts,
- liquidation
- psm
- [provisionPool.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/vats/src/provisionPool.js)
- vaultFactory
- walletFactory
- _anything else in [decentral-test-vaults-config.json](https://github.com/Agoric/agoric-sdk/blob/master/packages/vats/decentral-test-vaults-config.json)_

**Comment by dckc** [comment]
Is that list of contracts meant to be exhaustive? it's missing [provisionPool\.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/vats/src/provisionPool.js), I think.

To find all of them, I suggest using the list of bundles in the relevant config files such as [decentral\-test\-vaults\-config\.json](https://github.com/Agoric/agoric-sdk/blob/master/packages/vats/decentral-test-vaults-config.json). It's a conservative list: some bundles are for vats that are not contracts.

I occasionally see requests for a list of all contracts. I wonder about a unit test that checks the list of bundles against a known list, and if it finds one it's not familiar with, it gripes: "Is this bundle a contract? if so, have you checked it for contract best practices such as stagings, durability/upgrade, blah, blah, and blah?"
