### ISSUE TITLE
vaults bootstrap includes extra bundle: vat-network

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#7044]
## What is the Problem Being Solved?
vat-network is not being used in the vaults release. by removing it from the bootstrap we can avoid having to worry about it being durable or upgradeable. This allows us to defer #[5973](https://github.com/Agoric/agoric-sdk/pull/5973)

**Comment by dckc** [comment]
closely related:

 - #6687

**Comment by dckc** [comment]
network vat is mostly about IBC, but see also https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/docs/networking.md

need to have some plan to preserve viability of...

 - https://github.com/Agoric/agoric-sdk/issues/5108
