### ISSUE TITLE
wrong args to makeOfferDestination in setting up reserve, fee distribution

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#7046]
### Discussed in https://github.com/Agoric/agoric-sdk/discussions/6967

<div type='discussions-op-text'>

<sup>Originally posted by **anilhelvaci** February 10, 2023</sup>
## Context
In [The Inter Protocol Whitepaper's](https://inter.trade/static/whitepaper-6106f841c1ed6c564afd2fc3238240a9.pdf) `Section 2.4`, there mentioned a `Reserve Pool`. I assume that `Reserve Pool` is the one in [packages/interProtocol/src/reserve/assetReserve.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/src/reserve/assetReserve.js) when I'm asking my question. If I'm wrong please point me to the correct `Reserve Pool`.

## Question

I don't quite understand how the distribution of fees collected from `vaultFactory`, `amm` and `stakeFactory` end up in [assetReserve.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/src/reserve/assetReserve.js). In [econ-behaviors' startRewardDistributer method](https://github.com/Agoric/agoric-sdk/blob/4189c0d0934660f1f399d60ae12db6eb79a282f9/packages/inter-protocol/src/proposals/econ-behaviors.js#L533) there's [this code](https://github.com/Agoric/agoric-sdk/blob/4189c0d0934660f1f399d60ae12db6eb79a282f9/packages/inter-protocol/src/proposals/econ-behaviors.js#L597-L600).  Below is the snippet:

```js
await E(instanceKit.creatorFacet).setDestinations({
    RewardDistributor:
      rewardDistributorDepositFacet &&
      E(instanceKit.creatorFacet).makeDepositFacetDestination(
        rewardDistributorDepositFacet,
      ),
    Reserve: E(instanceKit.creatorFacet).makeOfferDestination(
      'Collateral',
      E.get(reserveKit).publicFacet,
      'makeAddCollateralInvitation',
    ),
  });
```
As far as I can understand here's the flow;

```mermaid
sequenceDiagram
    boot->>+feeDistributer: Set destinations
    Note over boot,feeDistributer: Reward, Reserve
    feeDistributer ->> feeDistributer: update shareConfig
    feeDistributer ->> vaultFacotry/amm/stakeFactory: collectFees
    feeDistributer ->> bank (Reward Pool): pushPayment
    feeDistributer ->> assetReserve (Reserve Pool): pushPayment
```

My questions;
The signature of `makeOfferDestination` is like below;
```js
 /**
     * Create a destination that generates invitations and makes Zoe offers.
     *
     * @param {ERef<ZoeService>} zoe
     * @param {string} keyword
     * @param {unknown} target
     * @param {PropertyKey} makeInvitationMethod
     * @param {unknown[]} [args]
     */
    makeOfferDestination: (
      zoe,
      keyword,
      target,
      makeInvitationMethod,
      args = [],
    ) => {
    // Method body...
    }
``` 

But in `startRewardDistributor`'s ;

```js
Reserve: E(instanceKit.creatorFacet).makeOfferDestination(
      'Collateral',
      E.get(reserveKit).publicFacet,
      'makeAddCollateralInvitation',
```

1. The method is called without the first argument which is `zoe`
2. The keyword is `Collateral`, shouldn't it be `Fee` as the IST is collected under the keyword `Fee` in [collectFees.js](https://github.com/Agoric/agoric-sdk/blob/4189c0d0934660f1f399d60ae12db6eb79a282f9/packages/inter-protocol/src/collectFees.js#L18) like below;
   ```js
    const collectFees = seat => {
      const amount = feeSeat.getAmountAllocated(keyword, feeBrand);
      atomicTransfer(zcf, feeSeat, seat, { [keyword]: amount }, { Fee: amount }); // To keyword is `Fee`

      seat.exit();
      return `paid out ${amount.value}`;
    };
   ```

Am I wrong or is this a bug? @dckc . If I'm wrong, can someone please point me to the correct direction? 

Thanks 🙏 
   </div>

cc @Chris-Hibbert @turadg

**Comment by Chris-Hibbert** [comment]
The keyword is interpreted with respect to the contract accepting the offer, which is `assetReserve` here, and it uses `Collateral`. 

`feeDistributor.makeOfferDestination()` returns a Far object with a `pushPayment` method, which allows the holder to send a payment to the specified destination using an invitation supplied by the destination. When sending to the AssetReserve, the terms and payment record need to specified using the keyword `Collateral`.

The `zoe` parameter does needs to be supplied to `makeOfferDestination`.

**Comment by dckc** [comment]
It seems odd that a contract (fee distributor) would rely on a client to tell it who zoe is.

**Comment by Chris-Hibbert** [comment]
Looks like that was factored out to make testing `makeFeeDistributor` possible.  I think you're right that it would be better to cut it differently so the client-facing method doesn't need to provide `zoe`.

**Comment by dckc** [comment]
In office hours today, I/we wondered why we weren't getting a static error about the args mismatch.

The following is a stash of some edits I made while exploring...

```diff
diff --git a/packages/inter-protocol/src/feeDistributor.js b/packages/inter-protocol/src/feeDistributor.js
index cd28efad8..8b2b298c2 100644
--- a/packages/inter-protocol/src/feeDistributor.js
+++ b/packages/inter-protocol/src/feeDistributor.js
@@ -298,7 +298,7 @@ export const makeFeeDistributor = (feeIssuer, terms) => {
     },
 
     /**
-     * @param {Record<Keyword, FeeDestination>} newDestinations
+     * @param {Record<Keyword, ERef<FeeDestination>>} newDestinations
      */
     setDestinations: async newDestinations => {
       destinations = newDestinations;
diff --git a/packages/inter-protocol/src/proposals/econ-behaviors.js b/packages/inter-protocol/src/proposals/econ-behaviors.js
index 8122a69f5..b9266c609 100644
--- a/packages/inter-protocol/src/proposals/econ-behaviors.js
+++ b/packages/inter-protocol/src/proposals/econ-behaviors.js
@@ -587,18 +587,21 @@ export const startRewardDistributor = async ({
       return undefined;
     });
 
+  /** @type {Awaited<ReturnType<typeof import('../feeDistributor.js').makeFeeDistributor>>} */
   const instanceKit = await E(zoe).startInstance(
     feeDistributor,
     { Fee: centralIssuer },
     feeDistributorTerms,
   );
+  /** @type {ERef<import('../feeDistributor.js').FeeDestination>} */
   await E(instanceKit.creatorFacet).setDestinations({
-    RewardDistributor:
-      rewardDistributorDepositFacet &&
-      E(instanceKit.creatorFacet).makeDepositFacetDestination(
-        rewardDistributorDepositFacet,
-      ),
+    ...(rewardDistributorDepositFacet && {
+      RewardDistributor: E(
+        instanceKit.creatorFacet,
+      ).makeDepositFacetDestination(rewardDistributorDepositFacet),
+    }),
     Reserve: E(instanceKit.creatorFacet).makeOfferDestination(
+      zoe,
       'Collateral',
       E.get(reserveKit).publicFacet,
       'makeAddCollateralInvitation',
```
