### ISSUE TITLE
Hermetic builds

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#7052]
Ensure that the standard agoric-sdk build process does not affect state outside of the build directory so that development and testing can occur on two separate versions of the sdk concurrently.

Related to #6574 for controlling the location of build artifacts. Test scripts will need to be written to rely on search paths in environment variables or relative directory paths rather than hardcoded absolute paths.

It is not within scope to bring all build dependencies within the hermetic bubble. Concurrently-testable versions of the agoric-sdk must have non-empty version range requirements of, e.g., node software.

**Comment by michaelfig** [comment]
`agoric-sdk/bin/agd build` accomplishes this, then use `agoric-sdk/bin/agd ...` to run it.
