### ISSUE TITLE
IST Competitor Tracking Bounty Requirements

### ISSUE THREAD

**Issue by jeetraut** [Agoric/Agoric#7060]
## Description
This is a bounty to create a dashboard in Google Sheets that scrapes the desired data from the sources listed below. Some sources are to be scraped daily and some sources weekly. 

## Context:

Pull Daily
Protocol/dApp Source URL | Source URL | Data Fields Desired
-- | -- | --
Osmosis | https://app.osmosis.zone/pools | Pool name/tokens in poolAPRLiquidityFeesIncentives: Y/NIncentive amounts
Osmosis | https://info.osmosis.zone/ | Token NamePriceVolumeLiquidity
Crescent | https://app.crescent.network/farm | PairAPRRewards and who provided byTVL
Injective | https://helixapp.com/markets | MarketLast PriceVolume
Injective | https://helixapp.com/markets?type=spot | MarketLast PriceVolume
Injective | https://helixapp.com/markets?type=derivative | MarketLast PriceVolume
Umee | https://app.umee.cc/#/markets | MarketTotal supplied (for that market)Total borrowed (for that market)Supply APYBorrow APY
Carbon/Demex | https://app.dem.exchange/markets | Market24 Hr volumeChains onSpot, futures, or perpetual?
Composable Finance - Pablo | https://app.pablo.finance/pool | PoolTVLVolume
White Whale/Comdex | https://app.whitewhale.money/comdex/pools | PoolPriceAPR24H volumeTotal LiquidityChain
dYdX | https://trade.dydx.exchange/portfolio/overview | Trading volume (24H)Open interestTrades
Axelar | https://www.axelarscan.io/ | Active validatorsTotal transactionsTotal transaction volume# connected chains# cross chain contracts

Pull Weekly:

Protocol/dApp Source URL | Source URL | Data Fields Desired
-- | -- | --
Injective | https://injective.com/ | On chain transactions count
Umee | https://app.umee.cc/#/markets | Total supplied (all markets)Total borrowed (all markets)
Comdex | https://defillama.com/chain/Comdex | TVL ComdexTVL CSwap
Injective | https://defillama.com/chain/Injective | TVL InjectiveTVL Helixdex
Composable Finance - Picasso | https://app.picasso.xyz/stats | Account holdersTotal transactionsPicasso MCapActive users
Composable Finance | https://defillama.com/protocol/composable-finance | TVL

## Acceptance Criteria
A Google Sheet dashboard that includes all the sources listed above as well as their respective desired data fields.
## Time Estimation
30 hours

## Reward
$2400

Payment will be made in USD (fiat currency) via wire transfer. The developer is responsible for providing their completed tax documents (W9 for US based developers and/or W8 or W8-BEN-E for non-US based developers) and providing their banking details in order to receive payment. 

## Applicant Assessment Criteria
Important: Please provide a clear work plan for how you will approach this bounty.  Use the work plan as an initial demonstration that you would be a good candidate.  Bounties will require coordination with the Agoric team, so unfortunately only plans submitted in English will be considered.

Applicants will be assessed based on the following criteria: 
* Issue-specific domain experience
* Issue-specific technical capability
* Familiarity with Agoric's platform
* JavaScript experience
* Availability and communication

## Review Process
* Agoric team reviews your submitted work plan on Gitcoin
* It is best to join our Discord and post your gitcoin name in the bounties channel, so that we can follow up with you. Otherwise, we will write on your gitcoin profile wall and say hello!
* Agoric contacts you to provide reference projects / sample code for engineering review
* Introductory call to discuss your plans and expected timeline
* You join the Agoric Discord bounties channel (if you haven’t done so already) 
* Agoric accepts you on Gitcoin and you get started!

## References
- [Agoric Documentation](https://docs.agoric.com/)
- #bounties channel in Discord

**Comment by LovelyDev829** [comment]
Hi, @jeetraut, I am really interested in your open issue.
Could you please let me know if it is still available for me?
Thank you.
