### ISSUE TITLE
Need endo release, update agoric-sdk to depend on that release

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#7090]
We have a large overhang of code in agoric-sdk which is redundant with code in recent endo. Once updated, we could remove the redundancy and the hazards of divergence.

See
 - https://github.com/Agoric/agoric-sdk/pull/6792
 - https://github.com/Agoric/agoric-sdk/pull/7081
 - https://github.com/endojs/endo/pull/1502
   - would fix https://github.com/Agoric/agoric-sdk/issues/6570
https://github.com/Agoric/agoric-sdk/pull/6816
 - #7129 

Speedups we may need that are also blocked on this:
 - https://github.com/endojs/endo/pull/1503
 - https://github.com/endojs/endo/pull/1504
 - https://github.com/endojs/endo/pull/1528 (+ https://github.com/Agoric/agoric-sdk/pull/7263 )

Debugging support we need, that's blocked on this:
https://github.com/endojs/endo/pull/1513 (though see #7270 )

cc @ivanlei

**Comment by turadg** [comment]
Once sdk has the latest Endo, we won't need this `makeTypeGuards` function in /internal: https://github.com/Agoric/agoric-sdk/pull/6866/files#diff-34f00c7262c12fbaede03f8adf5cc087fa139380893014d57aba98294ebba1feR4

Closing this issue should include changing that guard definition to be like the others.

**Comment by michaelfig** [comment]
> Once sdk has the latest Endo, we won't need this `makeTypeGuards` function in /internal:
> Closing this issue should include changing that guard definition to be like the others.

I'm not sure why that is the case.  Do you mean moving that definition out of `@agoric/internal`, or that `@agoric/internal` can take a hard dependency on `@endo/patterns`, or something else?

**Comment by turadg** [comment]
> that @agoric/internal can take a hard dependency on @endo/patterns

that's what I had in mind. @agoric/internal shouldn't depend on other @agoric/ package but it's fine to depend on anything in @endo/. It already depends on three.
