### ISSUE TITLE
correct debt terminology in inter-protocol

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7099]
## What is the Problem Being Solved?

Vaults and Stakes have debts but the term "loan" is misleading.

## Description of the Design

Remove "loan" from the code.

Will be a breaking change to setting and reading of governance param `loanFee`.

## Test Plan

`grep -r loan inter-protocol`

**Comment by Chris-Hibbert** [comment]
The word 'loan' appears only in tests, README.md and AttackersGuide.md.

**Comment by Chris-Hibbert** [comment]
#7539 covers the remaining work.
