### ISSUE TITLE
hdPath derivation logic in makeCosmosBundlePublisher (agoric-cli)

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/Agoric#7114]
## Describe the bug
In the `makeCosmosBundlePublisher` function in `agoric-cli`, two wallets are instantiated using a `hdPath` function:
https://github.com/Agoric/agoric-sdk/blob/3ff8f54a4eadf771580be2a36134294b716fbe36/packages/agoric-cli/src/publish.js#L38-L39
https://github.com/Agoric/agoric-sdk/blob/3ff8f54a4eadf771580be2a36134294b716fbe36/packages/agoric-cli/src/publish.js#L263-L266

I believe this derivation logic is incorrect, and we should be incrementing `accountIndex` instead of `account` to generate additional sets of keys (`stringToPath('m/44'/${coinType}'/0'/0/${account}')`). Please see [this document](https://github.com/confio/cosmos-hd-key-derivation-spec/blob/main/README.md#bip44) and [this example](https://github.com/cosmos/cosmjs/blob/38a650f30764b6c015732cffc240dbca9c2a777f/packages/amino/src/paths.ts#L7-L15) from cosmjs for more details.

Notably, from what I can tell, it seems like the second wallet generated is never used, so the impact here is probably negligible. Perhaps we can also remove `hdPath(Agoric.CoinType, 1)` on L265 unless it's serving a specific purpose: 
https://github.com/Agoric/agoric-sdk/blob/3ff8f54a4eadf771580be2a36134294b716fbe36/packages/agoric-cli/src/publish.js#L268

## Expected behavior
Wallet instantiation should use the correct hd derivation path. 

## Platform Environment
`agoric-upgrade-8-1091-g70e6f9103`

## Additional context
Here are the proposed changes. Please let me know if the testing approach makes sense! 
https://github.com/Agoric/agoric-sdk/compare/master...pcooney10:pc/fix/hd-path

**Comment by dckc** [comment]
What are the symptoms of this bug? What bad thing happens with the current code?

I suppose you say...

> the impact here is probably negligible

then I'm struggling to understand the nature of the bug.

**Comment by 0xpatrickdev** [comment]
Hey @dckc, your reply here slipped through my notifications for some reason.

> What are the symptoms of this bug? 

Unclear, and seemingly non existent since only the first account generated on L263 is used. (`const [from] = await wallet.getAccounts();`)
I am unsure how `stargateClient` ultimately consumes `wallet` and the accounts array (L293), but that seems to be the only other place this is used.

> What bad thing happens with the current code?  

`hdPath(Agoric.CoinType, 1)`, using the current `hdPath` function will return an invalid Agoric address. If `(await wallet.getAccounts())[1]` is used in the future, I would expect to see errors about an invalid public key. 

> Suggestion 

This bug seemingly/thankfully has no impact, but the output of the logic in hdPath (L38-L39) is only correct by coincidence and should be fixed:

```diff
const hdPath = (coinType = 118, account = 0) =>
-  stringToPath(`m/44'/${coinType}'/${account}'/0/0`);
+  stringToPath(`m/44'/${coinType}'/0'/0/${account}`);
```

Also, if the second account (`hdPath(Agoric.CoinType, 1)`) is never used, it may be best to remove it:

```diff
const wallet = await DirectSecp256k1HdWallet.fromMnemonic(mnemonic, {
  prefix: Agoric.Bech32MainPrefix,
-  hdPaths: [hdPath(Agoric.CoinType, 0), hdPath(Agoric.CoinType, 1)],
+  hdPaths: [hdPath(Agoric.CoinType, 0)],
});
```

**Comment by dckc** [comment]
> I would expect to see errors about an invalid public key. 

I routinely use accounts with hdpaths of `m/44'/118'/1'/0/0`, `m/44'/118'/2'/0/0`, and `m/44'/118'/3'/0/0` in production without any such errors.

Also, the Keplr UI gives no indication that changing any of the 3 path slots is better or worse than the others.

> Also, if the second account is never used, it may be best to remove it

Yes, that code was copied from another context where it had a purpose. I suppose a PR is welcome, though it may take us a while to get to it; we're in a bit of a crunch.

**Comment by 0xpatrickdev** [comment]
Ok. I was using [this](https://github.com/confio/cosmos-hd-key-derivation-spec/blob/main/README.md#bip44) and [this](https://github.com/cosmos/cosmjs/blob/38a650f30764b6c015732cffc240dbca9c2a777f/packages/amino/src/paths.ts#L7-L15) as references, which seem to indicate `account` should always be 0. But reading a bit more I see that you can increment both `account` and `address_index`. 

Apologies for my confusion, and thank you for responding! Please feel free to close
