### ISSUE TITLE
restore or replace test-gov-collateral

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7175]
## What is the Problem Being Solved?

This test for the ability of the BLDer DAO to add vault collateral types is brittle to maintain and was disabled in https://github.com/Agoric/agoric-sdk/pull/7047

## Description of the Design

Improve its setup to be less bespoke or move what it tests into other tests

**Comment by dckc** [comment]
I think it's subsumed by...

https://github.com/Agoric/agoric-sdk/blob/e68f2805dde79871d1421e50c60f08e854e1851d/packages/boot/test/bootstrapTests/test-liquidation-1.js#L402-L409

**Comment by Chris-Hibbert** [comment]
At a glance, it appears that `test-liquidation-1` includes tests that match `'Benefactor can add to reserve'` and `'assets are in Vaults'`, It doesn't appear that it covers `'voters get invitations'` or `'Committee can raise debt limit'`.

Are the latter two worth resurrecting?  Do we have better places to test that functionality?

**Comment by dckc** [comment]
I think invitations and debt limit are sufficiently tested elsewhere.
