### ISSUE TITLE
make auctioneer contract upgradable

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7181]
## What is the Problem Being Solved?

https://github.com/Agoric/agoric-sdk/pull/7047 introduced the new liquidation system, using a new `auctioneer` contract. But it's not yet durable or upgradable as it must be in production.

## Description of the Design

No module scope state: https://github.com/Agoric/agoric-sdk/pull/7047#pullrequestreview-1344652614

**Comment by dckc** [comment]
Last week, when I ran the `bid for liquidation` test, it passed, but the log included:

```
UnhandledPromiseRejectionWarning: (TypeError#1)
TypeError#1: Cannot add property collateralAmountShape, object is not extensible
  at finish (.../inter-protocol/src/auction/auctionBook.js:475:28)
```

I saw a `FIXME PITA that this state is async` in the relevant part of the code.

I'm not certain which version I was running. But for reference, it was on March 17 at around 4:20pm CT.

cc @Chris-Hibbert

**Comment by ivanlei** [comment]
We do not plan to do this. If we need to change the auctioneer contract we will deploy another.
