### ISSUE TITLE
Capture start/upgrade information in transcript

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#7199]
## What is the Problem Being Solved?

In #6775 we decided to keep historical transcript metadata so that a Manchurian style replay (#1691) would be possible.

Such a replay may only be necessary for the latest incarnation of a vat. Or possibly the latest N incarnations

However with an upgradable vat, we currently lose the information of the source used to start previous vat incarnations, whether that's the lockdown and supervisor bundles (which will become upgradable), or the vat bundle itself. Since #7026, we also do not make it possible to discover at what position in the transcript the latest incarnation started from. We have also never stored the transcript positions of previous vat upgrades.

## Description of the Design

- Add a synthetic `create-vat` transcript entry as the first "delivery" of a span representing a new incarnation. This would reference the bundle ids of lockdown, supervisor and vat source.
- Add metadata to the transcript spans indicating the incarnation number corresponding to the span, so that it's possible to get a list of spans representing the transcript of a single incarnation. (#7482)
- Possibly add the same incarnation number to the snapstore. This is not strictly necessary, but could help future house keeping where we decide to in consensus drop the snapshot metadata associated to previous incarnations. This technically can be derived from the incarnation data we would add to the transcript spans (through position correlation)

## Security Considerations

None I can think of, besides this information needing to survive export / import.

## Scaling Considerations

None

## Test Plan

TBD

**Comment by mhofman** [comment]
One of the use cases is the extract-transcript-from-kernel-db tool, and is this issue is thus tangentially related to https://github.com/Agoric/agoric-sdk/issues/6770

**Comment by warner** [comment]
In #7484 we added the `initialize-worker` pseudo-event to the transcript, which includes the `source.bundleID` (i.e. bundle hash), and the complete `workerOptions` (both `type: 'xsnap'` and the helper bundleIDs for lockdown/supervisor).

#7506 added `incarnation` to both the transcript-span records and the transcript items themselves. There's no swingstore API for using them, but it would be trivial to `SELECT * FROM transcriptItems WHERE vatID=? AND incarnation=?`.

We did not add the incarnation ID to the snapstore. The approach that fits with my plan for transcripts is more like:

* first = `SELECT * FROM transcriptItems WHERE vatID=? AND incarnation=?`
* `const { d } = JSON.parse(first)`
* `const [ type, loadConfig ] = d`
* `assert.equal(type, 'load-snapshot')`
* `const { snapshotID } = loadConfig`

We still record the `snapPos` with each snapshot row, so an alternative approach is to `SELECT startPos FROM transcriptSpans WHERE ..`, compute `snapPos = startPos - 1`, and then `SELECT * FROM snapshots WHERE vatID=? AND snapPos=?`.

Given that, I'm declaring victory on this ticket.
