### ISSUE TITLE
record worker bundleIDs in vat metadata, use during reload

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#7208]
Here's the new plan, to replace the #6596 of making a new package for the stable "worker-v1" behavior.

* we'll land `swingset-xsnap-supervisor` (#7063), but abandon `swingset-worker-xsnap-v1` (#7101)
* we'll leave everything in the monorepo, no changes to the release process
* we'll enhance @FUDCo's new `bundleStore` to accept `nestedEvaluate` bundles too (with an ID that's probably the hash of the JSON encoding of the whole bundle object) (#7190)
* when the kernel is initialized, we'll sample the lockdown and supervisor bundles, store them in the `bundleStore` under their hash IDs, and add a pair of `kvStore` keys to remind the kernel of what the "current lockdown/supervisor bundle ID" are
* when creating a new vat, the kernel will copy these IDs into some per-vat metadata (in `options`)
* when launching a vat worker, we'll use the metadata IDs to pull the lockdown/supervisor bundles from the `bundleStore` and feed them to the new worker, instead of using fixed copies

_Originally posted by @warner in https://github.com/Agoric/agoric-sdk/issues/6596#issuecomment-1476880896_

**Comment by gibson042** [comment]
Does this include #7012?

**Comment by warner** [comment]
> Does this include #7012?

Nope. It records and retains the xsnap-lockdown and swingset-xsnap-supervisor bundles (whatever is present in the corresponding dependencies under `node_modules/` when the vat is started or upgraded). But it makes no attempt to measure or influence the `xsnap` that is used.

We'll have to refrain from changing the `xsnap` dependency in non-completely-compatible ways between the release that we use for the bulldozer upgrade, and the subsequent Vaults+1 upgrade release.

During that window, we'll probably implement some sort of metadata flag to say "use xsnap-1.x", and we'll figure out some sort of aliased dependency so that "1.x" can coexist with a subsequent "2.x". We won't have that metadata in the bulldozer-created vats, but it wants to live in `vatOptions.workerOptions.xsnapVersion`, added to the existing `{ type: 'xsnap', bundleIDs }`. We'll have to treat the lack of that field as meaning the initial version.
