### ISSUE TITLE
Pending Liquidation UI

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#7250]
## Describe the bug
For at-risk vaults, a user should be able to understand the time remaining before the liquidation will take place

## To Reproduce
1. get some vaults in a liquidation-pending state
2. No hints for when that will happen in the UI

## Expected behavior

Some countdown timer or hint of when liquidation will happen

<img width="1226" alt="Screenshot 2023-03-27 at 4 43 25 PM" src="https://user-images.githubusercontent.com/22369/228091243-00bfc0df-2f9c-4922-bd41-8837ab3456f7.png">
<img width="1247" alt="Screenshot 2023-03-27 at 4 43 19 PM" src="https://user-images.githubusercontent.com/22369/228091248-1365fd03-9d6b-4dd1-99f9-8312a1227b54.png">

**Comment by otoole-brendan** [comment]
@samsiegart we intended to show mins remaining to liquidation in Figma design. We recently discussed how you'd arrive at this (using price lock period timing to top of the hour) so once you wire that up it should solve this.

**Comment by otoole-brendan** [comment]
@samsiegart I believe you should have everything you need to show this in UI since Chris's issue landed to make this available

**Comment by otoole-brendan** [comment]
Punting to V+1

**Comment by otoole-brendan** [comment]
Time until liquidation added via https://github.com/Agoric/dapp-inter/pull/112 so this ticket can be closed
