### ISSUE TITLE
[CLI] Auction Status interface

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#7266]
## Describe the bug
As a bidding user, I want to list the remaining time left on an auction and the current price of the auction, so that I can best inform my bidding strategy.

## To Reproduce
1. Bid on some liquidating vaults
2. Unable to easily see other bids I'm competing with, or how long there is for an auction I have already bid on, or if my bid will currently win the auction at the end of the duration

## Expected behavior
A user can see if their bid is the current winning bid, the time remaining on the auction, and easily list in ranked order the other bids in competition

**Comment by rowgraus** [comment]
Would suggest we want the following details about the auction:

Auction Details
1. Auction start time
2. Auction starting price
3. Collateral available for sale at start time
4. IST target at start time
5. Current price (i.e., the current collateral price being accepted at this tier/step)
6. Collateral currently available for sale
7. IST raised so far (or, IST target remaining - whichever is more straightforward)
8. Time until next price step

Governance settings:
1. Step size
2. Step time
3. Minimum discount

**Comment by dckc** [comment]
re "Unable to easily see other bids I'm competing with" see also #7159

**Comment by dckc** [comment]
> Governance settings:

Those are available via RPC/vstorage/chainStorage now. Adding a concise version the `agops inter liquidation status` output is straightforward.

<details><summary>Details</summary>
```
$ agoric follow :published.auction.governance -B https://ollinet.rpc.agoric.net:443
{
  current: {
    AuctionStartDelay: {
      type: "relativeTime",
      value: {
        relValue: 2n,
        timerBrand: slot(0,"Alleged: timerBrand"),
      },
    },
    ClockStep: {
      type: "relativeTime",
      value: {
        relValue: 180n,
        timerBrand: slot(0),
      },
    },
    DiscountStep: {
      type: "nat",
      value: 500n,
    },
    Electorate: {
      type: "invitation",
      value: {
        brand: slot(1,"Alleged: Zoe Invitation brand"),
        value: [
          {
            description: "questionPoser",
            handle: slot(2,"Alleged: InvitationHandle"),
            installation: slot(3,"Alleged: BundleIDInstallation"),
            instance: slot(4,"Alleged: InstanceHandle"),
          },
        ],
      },
    },
    LowestRate: {
      type: "nat",
      value: 4500n,
    },
    PriceLockPeriod: {
      type: "relativeTime",
      value: {
        relValue: 3n,
        timerBrand: slot(0),
      },
    },
    StartFrequency: {
      type: "relativeTime",
      value: {
        relValue: 3600n,
        timerBrand: slot(0),
      },
    },
    StartingRate: {
      type: "nat",
      value: 10500n,
    },
  },
}
```
</details>

**Comment by dckc** [comment]
Please be sure the `timerBrand` is published, while you're at it. Without it, auctioneer governance is somewhat opaque, and I'm struggling to make time records for #7249.

Note the `null` slot 0.

```
$ agoric follow --output text :published.auction.governance -B https://ollinet.rpc.agoric.net:443|jq '{body: .body|fromjson, slots}'
{
  "body": {
    "current": {
      "AuctionStartDelay": {
        "type": "relativeTime",
        "value": {
          "relValue": { "@qclass": "bigint", "digits": "2" },
          "timerBrand": {  "@qclass": "slot",  "iface": "Alleged: timerBrand", "index": 0 }
        }
      },
...
  },
  "slots": [    null,    "board0074",    null,    "board03523",    "board06120"  ]
}
```

_Slot 2 is a questionPoser invitation handle, which is not published by design._

**Comment by dckc** [comment]
the contract now provides the relevant info, but the CLI hasn't been updated to show it.
