### ISSUE TITLE
After upgrading to recent endo, when should we disable deep stacks in production?

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#7270]
After https://github.com/Agoric/agoric-sdk/issues/7090 is closed (likely by #7129), we get https://github.com/endojs/endo/pull/1513 which makes deep stacks be finite and on by default.

When deep stacks are on, we will create many error objects to remember these stacks. When these extra error objects are painfully expensive[1] in production, we should consider turning them off. We will need to turn it off explicitly, either by setting

```js
globalThis.process.env.TRACK_TURNS = 'disabled';
```

very early! Before `@endo/eventual-send` initializes. This is the preferred option, if we can do it selectively for production only.

Or, by setting the environment variable

```sh
$ export TRACK_TURNS=disabled
```
for those cases where environment variables are reflected into `globalThis.process.env`.

Attn @warner @mhofman @arirubinstein @ivanlei 

[1] The finite stack mechanism will drop these error objects, so we're not worried about the storage cost. Just the runtime cost of creating them.

**Comment by ivanlei** [comment]
Assigned to @michaelfig for decision

**Comment by michaelfig** [comment]
We decided to default to `TRACK_TURNS=disabled`.  This is probably the right thing to do in Endo itself, so I opened endojs/endo#1553
