### ISSUE TITLE
Cleanup assert detail strings in the kernel and kernel adjacent packages

### ISSUE THREAD

**Issue by FUDCo** [Agoric/Agoric#7271]
## What is the Problem Being Solved?

Testing has shown that an unreasonable amount of computation is being expended on runtime asserts, in particular on the construction of detail strings that will never be used.  We've developed new coding patterns to address these, and while these patterns are being used in new code they have not yet been systemically retrofitted on existing code.  The task here is to perform that retrofit with respect to the kernel and kernel-related packages (currently: `SwingSet`, `swing-store`, and `swingset-liveslots`).

## Description of the Design

Any assertion with a detail string where the detail string is anything other than a single string literal should be converted to the new `Fail` pattern:
 
That is, convert asserts such as
```
assert(expr, X`...`);
```
to
```
expr || Fail`...`;
```
or to
```
if (!expr) {
  throw Fail`...`;
}
```
if TypeScript's type inference engine gets confused by the simpler form and reports type errors.

Asserts of the form `assert(expr)` (i.e., no details) or `assert(expr, 'simple message')` (i.e., details consist of a single string literal) need not be converted.

The reference to `assert` here is for illustrative purposes. Other kinds of asserts such as `assert.equal(...)`should follow the same logic.  However, measurement has shown that type checking is faster inline, so `assert.typeof(....)` should always be converted to the `Fail` form regardless of details.  It may also make sense to always convert direct failures (`assert.fail(...)`) simply because it's cleaner and shorter.

## Security Considerations

None in particular.  Semantically this conversion should be no-op.

## Scaling Considerations

None as such, though obviously the point of the exercise is to improve performance, which will help with scaling.

**Comment by erights** [comment]
Turns out that `assert.equal(x, y, ...)` tests `Object.is(x, y)`. When we are certain[1] that `x` and `y` are not numbers, this is equivalent to `x === y`. So I have generally been rewriting
```js
assert.equal(x, y, X`...`);
```
to
```js
x === y || Fail`...`;
```

[1] Don't believe TypeScript. Don't do turn an `Object.is` test into a `===` unless you're certain from other evidence. Otherwise

```js
Object.is(x, y) || Fail`...`;
```
would be fine.
