### ISSUE TITLE
VaultManager publish lockedPrice and time for next liquidation

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#7281]
## What is the Problem Being Solved?

The Vaults UI is expected to show the user the time and price at which liquidation will next take place, but VaultManager (which has the price in its state) is not currently publishing that anywhere.

related - possible dupe - #6947

## Description of the Design

Add it to the data published by `updateMetrics()`.  Also add in the scheduled time, which VM knows how to get from the auction.

## Security Considerations

None. This is intended to be public info. It could be calculated from info the auction makes available and access to the oracles.

## Scaling Considerations

Replaces requests to the on-chain state.

## Test Plan

verify that it's being added to metrics, and that it's empty when there's no lockedPrice.

**Comment by ivanlei** [comment]
This should be helpful for #7266

**Comment by dckc** [comment]
added to vaults per PM

**Comment by Chris-Hibbert** [comment]
This was handled by #7339.
