### ISSUE TITLE
IBC transfer 1m IST from local or test chain to SEI network testnet

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#7315]
## What is the Problem Being Solved?
SEI network is testing using IST in their testnet for various internal purposes.  They want the IST to arrive over IBC from an Agoric test network so they can ensure all the internal plumbing works correctly for when they'd work in mainnet.

The Agoric network shouldn't need to remain active after the transaction has completed.

## Description of the Design
Needs:
1. Mint IST in sufficient amount (>1 million)
2. Send over IBC with relayer present to relay to correct SEI network (TBD: relayer run by SEI)

**Comment by rowgraus** [comment]
Per update in dev-inter-prototocol meeting:

Will use Emerynet for this transfer
Will mint >1m tokens via multiple faucet transactions
SEI is running a relayer and we will be in touch with them on their plan for IBC transfer

**Comment by ivanlei** [comment]
Not currently planned.
