### ISSUE TITLE
remove @agoric/notifier from @agoric/swingset-vats

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7324]
## What is the Problem Being Solved?

@agoric/swingset-vats uses @agoric/notifier only for some metering functionality that is effectively dead.  (vat-admin can notify the creator of a Meter that it is close to exhaustion, but all the uses are commented out because Notifiers aren't durable, and Meters need to be)

## Description of the Design

in https://github.com/Agoric/agoric-sdk/pull/5846/files#diff-ca5941a6452529623ac794dff449e12b01b6f8288fecd7471dfa2e60829f55c9R56 @FUDCo described a plan at the time.

@warner anticipates a future upgrade to vat-vat-admin that would reintroduce some kind of Meter notification functionality (maybe with a simple callback object instead of a Notifier)

**Comment by warner** [comment]
The plan at the time:

https://github.com/Agoric/agoric-sdk/blob/841a7012831166f6c29f00bdffc907f2b35a7b0c/packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js#L55-L68

The file contains `meterNotifiersTemp`, a WeakMap keyed by the Meter instance, which is our pattern for non-durables holding durables for the duration of the current incarnation.

To fix this ticket (removing the use of `@agoric/notifier` for now), we'll need to remove this WeakMap, stop creating notifiers entirely (`getNotifier()` throws "not implemented", the `meterCrossedThreshold` callback becomes a nop), `test.skip` the unit tests which specifically exercise meter notification, and comment out the notification-related portions of any other tests. We want to continue to test Meters in general, just not the notification part.
