### ISSUE TITLE
Upgraded `stateShape` may be incompatible with existing state

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#7337]
## Describe the bug
An ExoClass accept a `stateShape` argument that validates the state at get/set (including init).

If a new incarnation provides a `stateShape` that is incompatible with the state created in previous incarnations, the existing instances will fail when they try to read their state.

## Expected behavior
Rewiring the kinds with `stateShape` checks should enforce that the new `stateShape` is "compatible" with the previous one, aka that all existing states pass the new `stateShape` check. If incompatible, redefining the ExoClass should fail.

I'm not sure if removing a stateShape is possible, but if it is, it should be the equivalent to setting the new `stateShape` to `M.any()`, aka any further restriction is impossible.

**Comment by mhofman** [comment]
@erights suggests that the Exo class definition could take an `upgradeHook` along `stateShape`, which is called when:
- The representative is first recreated (which must be a non gc sensitive event), and
- The instance's state correspond to a previous `stateShape`, and
- The instance's state does not match against the new `stateShape`

This would require keeping track of which `stateShape` each instance was last associated with, either individually or by segmenting the VO definitions by incarnations.

This also implies that `upgradeHook` would have to support reading from any previous state, not just the N-1 state shape. This is basically the centralized equivalent of the current status quo where behavior methods must handle state from previous incarnations if no shape checks exist.

**Comment by erights** [comment]
Since we can test whether two `stateShape` patterns are literally identical, rather than segmenting VO storage by incarnation, I suggested (and prefer) to segment it by distinct `stateShape`. But this is probably not an observable difference anyway.

In order to compress a given instance by the `stateShape` that was current when the instance was last stored, we'd need such segmentation anyway.

Only durable kinds need support either segmentation or `upgradeHook`. Virtual-non-durable kinds are single incarnation anyway, so the issue does not arise.

**Comment by erights** [comment]
Also suggest that similar schema upgrade concerns will apply to change of `keyShape` or `valueShape` for the durable stores.

Similarly, only durable stores need support for such schema change. Virtual-non-durable stores are single incarnation anyway, so the issue does not arise.

**Comment by warner** [comment]
In #7407 I wrote up this upgrade process with a bit more detail, specifically for durable Kinds (perhaps we should merge the tickets?). In doing so, I came to the conclusion that we really should use a distinct version number of some kind, instead of relying only on `shape` changes. Please take a look at the arguments there and see if you agree.

**Comment by mhofman** [comment]
I think these are not entirely mutually exclusive. If a user provides an existing version number, we need to check that the shape is the same as the one that was recorded for that version.

But besides that, I agree we would no longer need to compare the stateShape before and after to decide if it's different, and create a new segment. Only the user provided version would create new segments.

**Comment by warner** [comment]
We landed the "`stateShape` must be identical" change in e47f45608065751753f7e39f365e80bc4dccd00f as part of PR #7365.

Let's define this ticket to mean "accept different `stateShape` as long as it is a (non-strict) superset of the previous version".

If we implement #7407 upgrades first, then we don't need to implement this ticket:
* when the new version uses a new version number, we'll accept entirely incompatible state shapes, and the user's migration function will be responsible for dealing with the changes
* when the new version uses a pre-existing version number, we'll demand that the "new" `stateShape` is identical to the previous one

**Comment by mhofman** [comment]
I would say that #7407 is the likely approach to be taken, and that the immediate concern with incompatible state shape changes has been satisfied in #7365, so this can be closed. We can always re-open if we decide not to do #7407 .

**Comment by gibson042** [comment]
Specific need: adding/removing/changing an annotation-only Remotable/Promise matcher label—cf. https://github.com/endojs/endo/pull/1933#discussion_r1447806963

**Comment by warner** [comment]
I'll agree that #7407 is the likely approach (merely relaxing the schema is harder to measure implement, and would make compression more difficult), and that we can close this now.
