### ISSUE TITLE
disable all ATOM vault invitations, all MakeVault invitations: add tests

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#7340]
## What is the Problem Being Solved?

We seem to lack automated test for:
 - disable all vaultFactory MakeVault invitations for ATOM
 - disable all vaultFactory MakeVault invitations, regardless of collateral type
 - disable all ATOM vaultFactory invitations, regardless of MakeVault vs CloseVault etc.

In a discussion of #7317 today, we (@erights @Chris-Hibbert @gibson042 and I) found that contract makes descriptions of the form `ATOM: MakeVault`. And the Zoe description matching supports prefixes delimited by `:`. So disabling all methods on the ATOM collateral type seems to be supported, but not disabling `MakeVault` across all collateral types (except by enumeration, since Zoe takes a _list_ of strings). More tests would make it clear that this is by design.

https://github.com/Agoric/agoric-sdk/blob/013fff8bdc7bb3e8fbecd6c06b59e065ed706e50/packages/inter-protocol/src/vaultFactory/vaultManager.js#L324

https://github.com/Agoric/agoric-sdk/blob/013fff8bdc7bb3e8fbecd6c06b59e065ed706e50/packages/inter-protocol/src/vaultFactory/vaultManager.js#L882-L884

The lack of tests is somewhat due to disabling swingset tests in inter-protocol:

 - #5433

https://github.com/Agoric/agoric-sdk/blob/013fff8bdc7bb3e8fbecd6c06b59e065ed706e50/packages/inter-protocol/test/swingsetTests/governance/test-governance.js#L67-L69

## Test Plan

perhaps tests similar to [bootstrapTests/test-vaults-integration.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/vats/test/bootstrapTests/test-vaults-integration.js)

cc @turadg

**Comment by turadg** [comment]
> - disable all ATOM vaultFactory invitations, regardless of MakeVault vs CloseVault etc.

This is tested in https://github.com/Agoric/agoric-sdk/blob/9f2254e811d88f271c5febf8249580698f207993/packages/inter-protocol/test/vaultFactory/test-vault-pause.js#L20-L30

If you're looking for pausing ATOM you're not going to find it. Because must support multiple managers with the collateral types they have to be keyed by the manager. 

> disable all vaultFactory MakeVault invitations for ATOM

To do that would be another small case in the file above, just like, https://github.com/Agoric/agoric-sdk/blob/9f2254e811d88f271c5febf8249580698f207993/packages/inter-protocol/test/vaultFactory/test-vault-pause.js#L44-L55

> disable all vaultFactory MakeVault invitations, regardless of collateral type

I think that would just be `md.setGovernedFilters(['Makevault']);` but it would be good to have a test for.

**Comment by dckc** [comment]
> > * disable all ATOM vaultFactory invitations, regardless of MakeVault vs CloseVault etc.
> 
> This is tested in
> 
> https://github.com/Agoric/agoric-sdk/blob/9f2254e811d88f271c5febf8249580698f207993/packages/inter-protocol/test/vaultFactory/test-vault-pause.js#L20-L30

yay!
 
> If you're looking for pausing ATOM you're not going to find it. Because must support multiple managers with the collateral types they have to be keyed by the manager.

Right... `manager0` then. Very well.

> > disable all vaultFactory MakeVault invitations, regardless of collateral type
> 
> I think that would just be `md.setGovernedFilters(['Makevault']);` but it would be good to have a test for.

The filters match on exact string equality or a prefix ending with a `:`. So this doesn't work:

```
test('AdjustBalances for all vault managers', async t => {
  const { aeth, run } = t.context;
  const md = await makeManagerDriver(t);

  const vd = await md.makeVaultDriver(aeth.make(100n), run.make(50n));

  await md.setGovernedFilters(['AdjustBalances']);

  await t.throwsAsync(vd.giveCollateral(10n, aeth), {
    message: 'not accepting offer with description "manager0: AdjustBalances"',
  });
});
```

I get:

```
  AdjustBalances for all vault managers
  Promise resolved with:

  'We have adjusted your balances, thank you for your business'

  › packages/inter-protocol/test/vaultFactory/test-vault-pause.js:52:11

  ─

  1 test failed
```

**Comment by turadg** [comment]
> The filters match on exact string equality or a prefix ending with a `:`.

Oh right. So this ticket is about a capability, not tests. There's a new requirement being specified, "disable all vaultFactory MakeVault invitations, regardless of collateral type", which wasn't in the user story: https://github.com/Agoric/agoric-sdk/issues/6944

This requires a new capability in Zoe for more either kinds of string filters (e.g. a suffix starting with `:`) or a way to condition the filters on more than string (https://github.com/Agoric/agoric-sdk/issues/7317 )

**Comment by Chris-Hibbert** [comment]
> Because must support multiple managers with the collateral types they have to be keyed by the manager.

If we're sticking with this approach, is there a reasonable way for the EC to find the name corresponding to a particular vault?

**Comment by turadg** [comment]
> is there a reasonable way for the EC to find the name corresponding to a particular vault?

I assume you mean to a particular vault _manager_. The GUI will abstract this. Most of the differentiators will be viewable in `.governance`. E.g. `DebtLimit` has the minted brand. Another manager with the same DebtLimit might have a different `LiquidationMargin` or `LoanFee`.

> If we're sticking with this approach

Is there an alternative you would like considered? (Product spec so far: https://github.com/Agoric/agoric-sdk/issues/6518 )

**Comment by Chris-Hibbert** [comment]
> I assume you mean to a particular vault manager.

Yep. thanks.

> Is there an alternative you would like considered?

Nope.

**Comment by dckc** [comment]
> Oh right. So this ticket is about a capability, not tests.

Well, I'm starting with a guess that it's working as designed and just looking for a test to confirm.

**Comment by turadg** [comment]
Ah. The tests show it's working as spec-ed out by Product. Confirmed.
