### ISSUE TITLE
Error: key "[Alleged: SeatHandle]" not found in collection "seatHandleToZoeSeatAdmin"

### ISSUE THREAD

**Issue by Jorge-Lopes** [Agoric/Agoric#7344]
## Describe the bug
A strange behavior has occurred while trying to make a zoe offer, the following error is triggered:
`key "[Alleged: SeatHandle]" not found in collection "seatHandleToZoeSeatAdmin"`
This was only noticed today (06/04/23) after pulling the most recent updates from agoric-sdk repo.

## To Reproduce
1. Context:
`Contract: `
```js
import { Far } from '@endo/marshal';
import { M } from '@agoric/vat-data';
import { AmountShape } from '@agoric/ertp';

const start = async (zcf) => {

  const { zcfSeat } = zcf.makeEmptySeatKit();
  
  const dummyHook = (userSeat) => {
    const { give: {In: givenAmount }} = userSeat.getProposal();
    zcfSeat.incrementBy(userSeat.decrementBy(harden({ In: givenAmount })));
    zcf.reallocate(zcfSeat, userSeat);
    userSeat.exit();

    return 'Sucess';
  };
  
  const makeDummyInvitation = () => {
    return zcf.makeInvitation(
      dummyHook,
      'dummy',
      undefined,
      M.splitRecord({
        give: { In: AmountShape },
      }),
    );
  };

  const creatorFacet = Far('creatorFacet', {
    makeDummyInvitation,
  });

  return { creatorFacet };
};

harden(start);
export { start };
```

`SetUp: `
```js
export const setUpDummy = async (zoe, issuer) => {
  const sourceRoot = '../src/contract.js';
  const contractUrl = await importMetaResolve(sourceRoot, import.meta.url);
  const contractPath = new URL(contractUrl).pathname;
  const contractBundle = await bundleSource(contractPath);
  const installation = await E(zoe).install(contractBundle);
  const issuerKeywordRecord = harden({
    In: issuer,
  });
  const { creatorFacet } = await E(zoe).startInstance(
    installation,
    issuerKeywordRecord,
  );
  return {
    creatorFacet,
  };
};
harden(setUpDummy);
```

`Test: `
```js
test.only('Test dummy contract', async (t) => {
  const dummyKit = makeIssuerKit('Dummy');
  const { brand, issuer, mint } = dummyKit;
  const dummyAmount = AmountMath.make(brand, 100n);

  const { zoe } = await setUpZoeForTest(() => {});
  const { creatorFacet } = await setUpDummy(zoe, issuer);

  const invitation = await E(creatorFacet).makeDummyInvitation();
  const proposal = harden({ give: { In: dummyAmount } });
  const payment = harden({ In: mint.mintPayment(dummyAmount) });

  const userSeat = await E(zoe).offer(invitation, proposal, payment);

  const result = await E(userSeat).getOfferResult();

  t.deepEqual(result, 'Sucess');
});
```
2. Run the following command to execute the test:
`npx ava test/test-contract.js`

3. See error
```
  ✔ Test dummy contract (2.9s)

  Unhandled rejection in test/test-contract.js

  TypeError: target has no method "makeNoEscrowSeatKit", has []

  Unhandled rejection in test/test-contract.js

  Error: key "[Alleged: SeatHandle]" not found in collection "seatHandleToZoeSeatAdmin"
    at Alleged: weakMapStore.get (packages/swingset-liveslots/src/collectionManager.js:301:19)
    at packages/zoe/src/zoeService/startInstance.js:121:62
    at Array.forEach (<anonymous>)
    at Object.replaceAllocations (packages/zoe/src/zoeService/startInstance.js:120:33)
    at Alleged: zoeInstanceAdmin.method (packages/store/src/patterns/exo-tools.js:161:18)
    at Alleged: zoeInstanceAdmin.In "replaceAllocations" method of (zoeInstanceAdmin) [as replaceAllocations] (packages/store/src/patterns/exo-tools.js:40:22)

  › Alleged: weakMapStore.get (packages/swingset-liveslots/src/collectionManager.js:301:19)
  › packages/zoe/src/zoeService/startInstance.js:121:62
  › Array.forEach (<anonymous>)
  › Object.replaceAllocations (packages/zoe/src/zoeService/startInstance.js:120:33)
  › Alleged: zoeInstanceAdmin.method (packages/store/src/patterns/exo-tools.js:161:18)
  › Alleged: zoeInstanceAdmin.In "replaceAllocations" method of (zoeInstanceAdmin) [as replaceAllocations] (packages/store/src/patterns/exo-tools.js:40:22)

SES_UNHANDLED_REJECTION: (TypeError#1)
  ─

  1 test passed
  2 unhandled rejections
```

## Expected behavior
The test should pass, being the offer result a string with the message "Sucess".

## Platform Environment
 - MacOS with node version v16.16.0
 - agoric-upgrade-8-1591-g9f2254e81

**Comment by Chris-Hibbert** [comment]
This test passes cleanly for me.

The unhandled rejection could come from a different test, run in parallel. Is there another test marked `test.only` in `test-contract.js`?  unhandled rejections often appear intermingled with the output of a different test from the one that caused them.

I don't see anything that looks incorrect in your contract, setup or test.

**Comment by Chris-Hibbert** [comment]
This is an interesting enough failure (i.e. it should *never* happen) that I'm going to do a little work to see if it can be reproduced in some recent version. (I'm asking around about how to recreate `agoric-upgrade-8-1591-g9f2254e81`. Thanks for that detail.)

**Comment by Chris-Hibbert** [comment]
Hmm. Still no luck. that version string leads to a very recent release, and my copy of the test above runs cleanly there. 

If this is still happening for you, I'd be interesting in learning any more details you can provide.

**Comment by Jorge-Lopes** [comment]
Good morning @Chris-Hibbert,
Thank you for your reply. 

That was the only test on that test file, I have tried again today and the output was the same.

After updating the agoric-sdk to the newest version:
`agoric-upgrade-8-1628-g524bbf7aa`
The error is no longer triggered.

If it is useful in any way, I can revert to the previous configuration and try to help building a more detailed report.

**Comment by Chris-Hibbert** [comment]
It would be helpful. (I'm glad to see that it's not happening on a recent version, but I don't know of anything relevant that we've changed, so this is still mysterious.)

If we can organize it, I'd be willing to look over your shoulder to learn more, though a more detailed report would be a good place to start.

**Comment by Jorge-Lopes** [comment]
Greetings @Chris-Hibbert 

It was a little tricky to recreate the same error but I was able to do it.
It is not related with the agoric-sdk version but instead with a fail while running `yarn & yarn build` after checkout.

I am very sorry for waisting your time! 

If it is still useful, my steps to recreate the error was:

1. run `git checkout 65d3f14c8102993168d2568eed5e6acbcba0c48a` (sdk version we are using for chainboard academy)
2. run `yarn & yarn build`
3. run `agoric install` on demo directory
4. run test ( passed)

5. run `git checkout agoric-upgrade-8-1628-g524bbf7aa`
6. run `yarn & yarn build` ( it failed, the console log can be seen on the attachment)
7. run `agoric install` on demo directory
8. run test (fail with the same error message as described in the first comment)

9. repeat `yarn & yarn build` (successfully)
10. run test ( passed)

[Terminal Saved Output.txt](https://github.com/Agoric/agoric-sdk/files/11201536/Terminal.Saved.Output.txt)

**Comment by Chris-Hibbert** [comment]
I'm glad we tracked this down.  It could have been something important, so it was worth the time to investigate. There will be other problems that look just as mysterious and unlikely to start, and if we don't spend the effort to figure out what's going on, we will occasionally miss an actual bug that really matters. Thanks for taking the time.

**Comment by Jorge-Lopes** [comment]
Thank you as well.
