### ISSUE TITLE
Add unit tests for state-sync

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#7349]
## What is the Problem Being Solved?

#7225 is likely to land with only integration tests. However there are some edge cases that the end to end test does not exercise.
To get coverage for those, we need some unit tests of at least the golang ExtensionSnapshotter logic.

## Description of the Design

Tests covering the following edge cases in golang:
- Reaching a snapshot block height when a snapshot is still in progress
- Reaching commit time with an active snapshot that hasn't returned from it's request to JS
  - Make sure commit is delayed through `WaitUntilSnapshotStarted` correctly stalling
- Reaching a second commit after snapshot has started: make sure no wait
- JS Snapshot initiate request fails
- JS Snapshot retrieval request fails

In an ideal world, we'd have tests covering the following edge cases in JS:
- Snapshot initiates request when a snapshot is already in progress
- Commit action before snapshot initiate completes (verify that swingstore commit is delayed)
- Snapshot discard before init completes
- Snapshot discard while snapshot in progress. Make sure any retrieval request is rejected
- Snapshot discard after snapshot data dir already removed

**Comment by JimLarson** [comment]
Unfortunately, Go isn't really suited for tests to ensure that something is blocked. What's needed is some sort of "run until quiescent" method, or "give up my scheduler slot and let every other runnable thing have a chance" (often `sleep(0)` does this), but Go does not have these features. The hacky workaround would be to add a pause in the main goroutine to let other goroutines run, but this is a strong anti-pattern that makes tests slow and flaky. IMHO, the cost of a unit test for blocking exceeds its possible value.

**Comment by JimLarson** [comment]
Moved the JS unit tests to #7590 so this can be closed.
