### ISSUE TITLE
Cannot find package '@endo/init' from agd build

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#7356]
## Describe the bug

While writing docs for getting started as a liquidation bidder (#7295) I tested `agd build` on a blank debian container. It failed with `Cannot find package '@endo/init'`

## To Reproduce
1. start a blank debian container: `docker run --rm -ti debian:stable-slim`
2. `git clone https://github.com/agoric/agoric-sdk` (have to `apt update && apt install git curl -y` 1st)
3. `cd agoric-sdk; SKIP_DOWNLOAD=false ./bin/agd build`
4. See error:

```
$ yarn build:bundles
$ node ./scripts/build-bundles.js
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@endo/init'
```

## Expected behavior

install Just Works

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
[If applicable, add screenshots to help explain your problem, especially for UI interactions.](https://gist.github.com/dckc/838a51eec7467cacfd577904681162f1)

**Comment by michaelfig** [comment]
This was a simple logic error in the `yarn install` dependency calculation.  Fixed in #7223 (which already changed `bin/agd`) and it will land shortly.
