### ISSUE TITLE
resurrect Node-subprocess worker, to help with memory-leak investigation

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#7369]
## What is the Problem Being Solved?

@mhofman is working hard to figure out why our create-lots-of-Vaults benchmark is showing increasing RAM usage over time, when everything is supposed to be virtualized. One of the tools he's using is the V8 "heap dump", which emits a JSON file of the whole object graph. The Chrome devtools know how to display and investigate this dataset. By comparing the dump from before and after a number of benchmark cycles, he's hoping to figure out what RAM objects are new, and thus probably the ones that are growing in size/number over time, when they should be flat.

This task is complicated by the fact that the heap includes both the kernel and all vats. It would be a lot easier if we could get the heap of just a single vat.

Once upon a time, we had a vat worker type named `subprocess-node`. This ran in a child subprocess, just like our usual `subprocess-xsnap` worker, but the child ran Node.js/V8 instead of `xsnap`/XS. It wasn't complete: it lacked synchronous/blocking syscalls, which was a fatal problem given how much we now rely upon `vatstoreGet`. And we weren't using it anywhere: I kept it around to keep us honest about supporting multiple worker types. But it had outlived its usefulness, so I deleted it a few months ago, in the process of refactoring the `swingset-xsnap-supersivor` code into a separate package.

## Description of the Design

So the proposed task is to bring this worker back, with a blocking syscall interface (using `fs.readSync` on the command pipe) so it works properly.

We can mine git history for most of the code. I think the main child-side command-pipe code needs to be rewritten, because it was using some clever streams / async iterators, which makes sense for the kernel side, but complicates the need for a blocking pipe on the child side.

## Security Considerations

We should consider whether we want userspace (via the `E(vatAdminService).createVat()` option named `managerType`) to select this worker type. I think we don't, in fact I think userspace shouldn't get to choose between `local` and `xsnap` workers either. We might already have this restriction in place, but if not, we should probably impose it before adding a new worker option.

We should include the (appropriately-sanitized) vat name in some dummy argument of the child process, so that a `ps` listing will show which vat is which (just like we do for xsnap), ala #4738 . As with xsnap, we should ensure this userspace/attacker-controlled name cannot cause problems or confusion. The child process will be spawned with an `argv` array, so I'm not worried about shell injection / etc, but still I think it'd be a good idea to limit the characters allowed in the name to avoid confusion. Probably only letters, numbers, hyphen, comma, period. And the actual argument should starts with the vatID, so e.g. `v8-user-provided-name`. Prohibiting spaces means the argument doesn't look like it might actually be multiple arguments. Preventing slashes makes it not look like a pathname. Prepending the vatID means even if the userspace name has a leading hyphen, the actual argument string won't look like a command-line option.

## Scaling Considerations

None

## Test Plan

Resurrect the `packages/SwingSet/test/workers/test-workers.js` test case for the new worker type. Make sure it exercises the blocking syscalls that previously it avoided using.

**Comment by warner** [comment]
cc @FUDCo

**Comment by warner** [comment]
branch [`7369-worker-subprocess-node`](https://github.com/Agoric/agoric-sdk/tree/7369-worker-subprocess-node) has a start on this, but it needs to be updated to handle the new transcript management changes

**Comment by warner** [comment]
Also this will help with perf investigations

**Comment by mhofman** [comment]
FWIW, this branch was invaluable for some of my perf investigation a month-ish ago.
