### ISSUE TITLE
power to upgrade BLD mintHolder contract not saved; others?

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#7433]
## Describe the bug

While adding labels to calls to `startInstance()` (#7426) I discovered a couple where we don't save the `adminFacet` and hence can't upgrade. I fixed `economicCommittee` but not `mintHolder` and I'm not certain there are no other cases.

https://github.com/Agoric/agoric-sdk/blob/c832a55a303dbe2f1ae750c9f6a4874ea570998c/packages/inter-protocol/src/proposals/startPSM.js#L254

## Expected behavior

The `adminFacet` from every call to `startInstance` is available to later bootstrap actions for upgrade.

## Platform Environment
 - what version of the Agoric-SDK?

c832a55a303dbe2f1ae750c9f6a4874ea570998c

## Additional context

This is essentially the same bug as #6034, but I gather we prefer not to re-open issues.

**Comment by dckc** [comment]
price-feed-proposal.js doesn't save the adminFacets of the flux aggregator nor its governor

**Comment by dckc** [comment]
I wonder about refactoring bootstrap so nobody gets the raw zoe capability but rather only a zoe.install() capability that's guaranteed to save all the facets. (and use something like startGovernendContract uniformly)

@samsiegart for ref:

https://github.com/Agoric/agoric-sdk/blob/bb6a227cbfb1037531bd8b6c162600cb3459530c/packages/vats/src/core/startWalletFactory.js#L43-L44

**Comment by Chris-Hibbert** [comment]
The main object of this PR was addressed by #7545. Does anything remain to be done?

**Comment by dckc** [comment]
I don't suppose we save the adminFacet for `binaryVoteCounter`; I'm inclined to consider that part of #3907, which we have postponed.

If there are no other exceptions, that is: if all calls to `E(zoe).startInstance()` have their adminFacet saved, then this is done.

**Comment by Chris-Hibbert** [comment]
I think all the relevant `startInstance()` calls used to be in `econ-behaviors.js`, but now I don't think even `projects/inter-protocol/src/proposals/` contains them all. 

Can someone enumerate the relevant locations that are part of bootstrap?

**Comment by Chris-Hibbert** [comment]
in proposals, I checked these and all the `adminFacets` are saved.
 * econ-behaviors.js
 * committee-proposal.js
 * core-proposal.js
 * startEconCommittee.js

Do any of these matter?
 * in `addAssetToVault.js`, the adminFacet for `mintHolder` isn't saved in `publishInterchainAssetFromBank()`. 
 * in `addAssetToVault.js`, the adminFacet for `scaledPriceAuthority` isn't saved in `registerScaledPriceAuthority()`. 
 * in `price-feed-proposal.js`, the adminFacet for `priceAggregator` isn't saved in `createPriceFeed()`. 
 * in `startPsm.js`, the adminFacet for `mintHolder` isn't saved in `makeAnchorAsset()`.

**Comment by dckc** [comment]
> Do any of these matter?

yes; all of them. thanks for auditing. They all seem to use the relevant utility to start the contract and save all the facets (`startUpgradable` or `startGovernedUpgradable`).

> * in `addAssetToVault.js`, the adminFacet for `mintHolder` isn't saved in `publishInterchainAssetFromBank()`.

This call to `startUpgradable` saves it in `vBankKits`, no?

https://github.com/Agoric/agoric-sdk/blob/0a2843b787b998a57ca5977b00f9432bb7201607/packages/inter-protocol/src/proposals/addAssetToVault.js#L93-L101

> * in `addAssetToVault.js`, the adminFacet for `scaledPriceAuthority` isn't saved in `registerScaledPriceAuthority()`.

looks right to me:

https://github.com/Agoric/agoric-sdk/blob/0a2843b787b998a57ca5977b00f9432bb7201607/packages/inter-protocol/src/proposals/addAssetToVault.js#L214-L221

> * in `price-feed-proposal.js`, the adminFacet for `priceAggregator` isn't saved in `createPriceFeed()`.

looks good to me:

https://github.com/Agoric/agoric-sdk/blob/fb9d18f4067c3821caa7819425b4fb2684ddf1ae/packages/inter-protocol/src/proposals/price-feed-proposal.js#L163-L178

> * in `startPsm.js`, the adminFacet for `mintHolder` isn't saved in `makeAnchorAsset()`.

looks good to me:

https://github.com/Agoric/agoric-sdk/blob/fb9d18f4067c3821caa7819425b4fb2684ddf1ae/packages/inter-protocol/src/proposals/startPSM.js#L336-L343

looks like we missed an opportunity to refactor starting the PSM contract to use `startGovernedUpgradable`, but the net effect is the same.

**Comment by dckc** [comment]
I'm not worried about this one... the initial supply is always 0 in production. I hope this gets deleted shortly.

https://github.com/Agoric/agoric-sdk/blob/fb9d18f4067c3821caa7819425b4fb2684ddf1ae/packages/vats/src/core/basic-behaviors.js#L472-L473

**Comment by dckc** [comment]
The BLD mintHolder noted in the title of this issue looks like it's still outstanding:

https://github.com/Agoric/agoric-sdk/blob/fb9d18f4067c3821caa7819425b4fb2684ddf1ae/packages/vats/src/core/basic-behaviors.js#L514-L515

**Comment by Chris-Hibbert** [comment]
I agree with your updates. I thought I grabbed  latest state before reviewing, but these were merged 2 days ago.

Thanks for checking on the cases in vats.  I didn't know what else mattered.
