### ISSUE TITLE
defineDurableKindMulti can't add new facets during upgrade

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#7437]
## Describe the bug

@Chris-Hibbert asked me today about what, exactly, can be changed about a durable Kind when the vat/contract is upgraded. I told him:

* faceted-ness vs unfacetness must remain the same (either use `defineDurableKind` both times, or `defineDurableKindMulti` both times
* any existing facets (i.e. the facet name) must still exist
* new facets can be added (* caveat 1)
* the methods of each facet can be completely changed
* the state of the instances must have the same property names (* caveat 2)
* the optional `stateShape` constraint, if provided, must be the same (* caveat 2)

"Caveat 2" is that we have a plan (#7407) to allow a migration function that will let the state contents and/or `stateShape` be changed across upgrades.

"Caveat 1" is that I think I was wrong. We intended to allow new facets during upgrade, but our implementation sorts the facet names before assigning them integers, so the "does this facet still exist, and with the same integer index" check is working on the *sorted* names. The consequence is that you ~can only add facets if they sort alphabetically *later* than any existing facets~, which is clearly not useful.

EDIT: further investigation shows that you cannot add new facets at all, the check ensures that everything on the new list is also on the old list, which means that it incorrectly tolerates the removal of late-alphabet facets.

It looks like we have several *negative* tests, which assert than an upgrade fails if you change various aspects of the facet list. But we don't have any positive test which shows an upgrade *succeeding* when new facets are added.

## The Fix

When we examine the facet names of the new behavior record, and assign them integers, we should consult the old (recorded) list first, and use the same integer for any pre-existing facet. Then we should check that all old facets still exist. Then we should take all of the new names and assign them new integers.

We need to confirm that the reference counts and export status DB values are still compatible. The export status is a string of length `numFacets`, so the question is whether a short string will be correctly interpreted as having the new facets be unexported.

I don't remember how the refcount string is encoded, we need to check and make sure it is tolerant of new facets too.

## Priority

We don't strictly need to do this before the Vaults upgrade, since the first time it will be needed is during contract upgrades that happen post-Vaults, which will work as long as we upgrade the chain to use a new version of liveslots (with the new `defineDurableKindMulti`) by then. But if there's any problem with refcount/export-status data, we might want to get that fixed beforehand, so we don't run into any surprises later.

**Comment by Chris-Hibbert** [comment]
@Tyrosine22  The bulleted list above should be added to documentation about contract upgrade when we get to that.

**Comment by warner** [comment]
cc @FUDCo

**Comment by warner** [comment]
Further investigation shows that `defineDurableKindMulti` incorrectly tolerates removal of late-alphabet facets, so if v1 defines:

```js
const facets = {
 bar: {},
 clu: {},
 foo: {},
};
```

and v2 defines:
```js
const facets = {
  bar: {},
  clu: {},
};
```

then `defineDurableKindMulti` will "successfully" return a `make` function, but something bad would happen if an instance were deserialized (maybe an internal error, maybe a broken set of facets, not sure yet).

The cause is the loop in https://github.com/Agoric/agoric-sdk/blob/1b2a03fa6fa9c74e74523fc1f81f37b194cfd118/packages/swingset-liveslots/src/virtualObjectManager.js#L191-L195


where `facetNames` are the new names, and `desc.facets` are the old ones. This loop only walks the new names, and stops when it runs out. A complete check would need to also compare the lengths of the two arrays. A check that tolerates the addition of facets would need to walk the old names, not the new ones (and needs more code anyways, to reassign the old index for existing facets).


This revelation changes this ticket from a feature-omission to an actual bug, and increases the priority somewhat: userspace could cause liveslots corruption by upgrading to a bogus Kind definition. It still won't be a problem until a vat/contract is upgraded, so we could still defer this until after Vaults: we must upgrade the chain to an agoric-sdk with a fixed liveslots before we can upgrade any vat/contract that might 1: try to corrupt liveslots by omitting facets from their upgraded Kind, or 2: wants to add facets.
