### ISSUE TITLE
Some VaultFactory and Auction.Book liquidation/auction-specific names are confusing/unclear

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7475]
## Description of the Design

vaultFactor.Manager
- [ ] 'liquidatingCollateral' looks to be total cumulative liquidated collateral for a given vault manager (please confirm @dckc and @Chris-Hibbert). If this is the case, the name is confusing and should be renamed to 'TotalCollateralLiquidated' 

- [ ] likewise for 'liquidatingDebt' -> renaming to 'TotalDebtLiquidated' seems to make more sense

auction.book0
- [ ] From watching a few auctions, 'collateralAvailable' seems to tick up as collateral is sold in the auction so it's not really tracking available collateral. It would make more sense to either change the calculation logic here such that it starts at total amount of liquidated collateral available that needs to be sold and counts downwards as the auction ticks forward.
Alternatively (but a second preference), it could be renamed to 'CollateralSold' if changing calculation logic is a harder lift.

## Security Considerations
Unknown
## Scaling Considerations
Unknown

**Comment by Chris-Hibbert** [comment]
liquidatingCollateral should reflect the total value of the collateral for vaults sent to be liquidated. It should be zero between auctions, rise to the total at the start of the auctions, and at the end be reduced to zero again.  I see the calls to reduce it at the end of flows 1 and 2a, but not 2b. 

liquidatingDebt should be the total debt for vaults sent to liquidation. It should be zero between auctions, rise to the total at the start of the auctions, and at the end be reduced to zero again. This is controlled by the same calls, so it's missing in the same place.

`collateralAvailable` is calculated in `auctionBook`. (The above are in `vaultManager`.) The value here may be inverted from the intended meaning. 

I think the names are correct and the values need to be cleaned up.
