### ISSUE TITLE
execute Pismo -> Vaults upgrade in test nets

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7491]
## What is the Problem Being Solved?

Assurance that executing the upgrade will work in mainnet.

## Description of the Design

Follow [the runbook](https://github.com/Agoric/agoric-sdk/issues/7493) once all the dependencies are landed:

```[tasklist]
### Dependencies
- [ ] https://github.com/Agoric/agoric-sdk/issues/7493
- [ ] https://github.com/Agoric/agoric-sdk/issues/6644
- [ ] https://github.com/Agoric/agoric-sdk/issues/6099
- [ ] https://github.com/Agoric/agoric-sdk/issues/7499
- [ ] https://github.com/Agoric/agoric-sdk/issues/7499
- [ ] #7652
- [ ] https://github.com/Agoric/agoric-sdk/issues/7562
- [ ] https://github.com/Agoric/agoric-sdk/issues/7640
```

## Test Plan

Reuse the testing procedure from #7499 but upon actual state cloned from Pismo-C

**Comment by dckc** [comment]
It's not clear to me how this requires #5795 and #6553; upgrade of contracts/vats would happen _after_ the Pismo -> Vaults upgrade.

**Comment by turadg** [comment]
> It's not clear to me how this requires #5795 and #6553; upgrade of contracts/vats would happen _after_ the Pismo -> Vaults upgrade.

Righto. This is the P -> V testing ticket. I've made a separate,
- https://github.com/Agoric/agoric-sdk/issues/7562
and moved over the two tickets you mentioned.

**Comment by ivanlei** [comment]
All done
