### ISSUE TITLE
create an upgrade runbook

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7493]
## What is the Problem Being Solved?

Need to specify how we'll upgrade

## Description of the Design
("vat" here include contract vats)

- what vats are on chain
- what vats will be added
- what vats will be replaced in kind (and what state must be maintained)
- what vats will be upgraded in place (maintaining reachably durable state)

Include end state requirements, such as:
- smart wallets for those who paid 10 BLD are preserved

Rough draft:
1. OpCo qualifies the software for the community to use ([execute Pismo -> Vaults upgrade in test nets · Issue #7491 · Agoric/agoric-sdk](https://github.com/Agoric/agoric-sdk/issues/7491) )
2. Staking community makes and votes proposal to bulldoze
  Another runbook covers community proposals
  Chain goes down and when it’s back up we have Pismo functionality restored (PSMs and Smart Wallets)
3. OpCo qualifies the chain for further proposals
4. EC accepts their fresh invitations
5. OpCo demos proposal to add Vaults to a running chain
6. bundles installed on chain (~2k IST) 
7. Staking community makes and votes a proposal to start Vaults contract
8. Staking community makes and votes to add a collateral type for Vaults

## Test Plan

validate through analysis.

also execute:

 - https://github.com/Agoric/agoric-sdk/issues/7491

**Comment by ivanlei** [comment]
https://docs.google.com/document/d/1XDXWykJjWhPoSW70fbAsEqALXdrl9iT_Dis0BR_dEg0 suffices
