### ISSUE TITLE
automated test harness of upgrading Pismo to Vaults

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7499]
## What is the Problem Being Solved?

Need a test harness for the process of bulldozing Pismo Swingset on a running chain and starting up Vaults with the same state .

## Description of the Design
lightweight using this shell script - https://www.notion.so/agoric/Testing-Upgrades-b2e003b2121244508930d995ee2abd5c?pvs=4
1. Start a new Pismo chain
2. Do a handful of transactions to get state to preserve
- Has to be all the state we care about checking
- Provision wallets
- Have Cosmos/vbank balances
- Change governance parameters
- EC purses with invitations (to make sure it doesn’t break anything when it’s no longer present)
3. Swapping out the binary
4. Do the upgrade
5. Check that the state from transactions is still present
- e..g provisioned wallets are restored
7. Check EC restore
- They can accept fresh invitations
- Change parameters
8. PSM functionality
- Trade again. Vbank updates

**Comment by ivanlei** [comment]
With the framework in place, we'll track further test cases added to it as part of #7640
