### ISSUE TITLE
cannot publish inter protocol bundles over 1M due to max_tx_bytes tendermint config

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#7501]
## Describe the bug

publishing bundles over 1M conflicts with `max_tx_bytes = 1048576` [tendermint config](https://docs.tendermint.com/v0.34/tendermint-core/configuration.html) setting.

## To Reproduce

1. bundle vaultFactory as json (see details below)
2. make sure you have > 3450 IST
3. run a local node, state-sync'ed to devet (agoricdev-17)
4. try `agd tx swingset install-bundle ...`
5. get error code 21

## Expected behavior

bundle is published on chain

Maybe we have to use a higher `tx_max_bytes` when we start the network?

## Platform Environment
 - agoricdev-17 088b0abf2

```
# agd version --long
version: 0.32.2
commit: 088b0abf2
```

## Additional context

closely related:

https://github.com/Agoric/agoric-sdk/issues/6454#issuecomment-1521103559

Note that publishing the 836K `mintHolder` bundle works.

## Screenshots / Terminal Sessions

bundle:

```
packages/inter-protocol# yarn bundle-source --cache-json bundles src/vaultFactory/vaultFactory.js vaultFactory
yarn run v1.22.19
$ /usr/local/src/agoric-sdk/node_modules/.bin/bundle-source --cache-json bundles src/vaultFactory/vaultFactory.js vaultFactory
bundles add: vaultFactory from src/vaultFactory/vaultFactory.js
bundles bundled 189 files in bundle-vaultFactory.json at 2023-04-25T15:18:01.125Z
Done in 2.63s.

packages/inter-protocol# ls -sh bundles/bundle-vaultFactory.json
1.7M bundles/bundle-vaultFactory.json
.
```

Try to submit without enough IST:

```
packages/inter-protocol# agd tx swingset install-bundle @./bundles/bundle-vaultFactory.json --keyring-backend=test --from test-acct --chain-id=agoricdev-17 --yes --gas=auto
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = controller refused message admission: 427850000uist is smaller than 3424800000uist: insufficient funds: mempool is full [/usr/local/src/agoric-sdk/golang/cosmos/ante/vm_admission.go:58] With gas wanted: '0' and gas used: '1762055' : unknown request

```

Submit and get code 21:

```
packages/inter-protocol# agd tx swingset install-bundle @./bundles/bundle-vaultFactory.json --keyring-backend=test --from test-acct --chain-id=agoricdev-17 --yes --gas=auto
gas estimate: 52670047
code: 21
codespace: sdk
...
txhash: A5E2439B577E803E552E0F1CC0FCD640F3231A399A76B56D4427BA7CBADCD1D1
```

cc @arirubinstein @michaelfig @ivanlei

**Comment by michaelfig** [comment]
There's only one use in `agoric-cli/src/publish.js`, and we don't need to change it since nothing known relies on it yet.

**Comment by JimLarson** [comment]
Per our discussions, I've implemented an option to compress the bundle within the `MsgInstallBundle`.

**Comment by migueldingli1997** [comment]
I've run into the `request body too large` error when installing a bundle and I'm using `--compress`. Not sure if it's due to the same reason described above or in https://github.com/Agoric/agoric-sdk/issues/6454

```bash
+ agd tx swingset install-bundle --compress @/root/.agoric/cache/b1-87ebdf9be77f33521967261b02f32bc524d392ccd9bdc493aa57be8c3c0de6d63a66ae09e42c8abe14b9654ca0f8b706d2854beb1b58fd77715db57851e4c851.json --from user1 --keyring-backend=test --gas=auto --chain-id=agoriclocal -bblock --yes -o json
Error: RPC error -32600 - Invalid Request: error reading request body: http: request body too large
```

For a bit more context, I'm based on the https://github.com/Agoric/dapp-game-places template and just edited the contract a bit.

**(Update 22/12/2023 - refer to https://github.com/Agoric/agoric-sdk/issues/8621#issuecomment-1866731153 for follow-up)**
