### ISSUE TITLE
Issues with Liquidation Bidding CLI testing tool setup

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#7521]
## Describe the bug
Have encountered multiple issues with the [Bidding Tool CLI setup](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/test/auction/README-bidding-cli.md).  Currently blocked as unclear how to move forward. Documenting here.

## To Reproduce
Issue 1: installed agoric-sdk into a directory with a space in the name ("Agoric Development").  When running SKIP_DOWNLOAD=false .bin/agd build command, setup could not find any of my subdirectories.  Adjusted to a new directory without any spaces and seemed to move past this issue

i.e., likely resolved but might need to be mentioned in docs if this truly was the problem

Issue 2: SKIP_DOWNLOAD=false .bin/agd build command ended with errors.  
<img width="597" alt="image" src="https://user-images.githubusercontent.com/60824328/234601154-7ee940fa-5bd8-41a5-a5e2-576412233455.png">

I was able to find an agd version after this completed, so I continued with the steps.  However, possible that the last issue is caused by this one as well.

Issue 3: yarn run agops inter command failed
<img width="580" alt="image" src="https://user-images.githubusercontent.com/60824328/234601596-515f3d19-9ea3-4895-bbb7-f11d5028455b.png">

## Expected behavior
Run through the setup steps without errors.

## Platform Environment
 - what OS are you using? what version of Node.js?
 MacOS
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
master

**Comment by arirubinstein** [comment]
Can you validate the following:
Running `sw_vers` in terminal outputs the following:
```
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
```

and `xcodebuild -version` yields 
```
Xcode 14.3
Build version 14E222b
```

**Comment by rowgraus** [comment]
It didn't and I got it there with some finagling.  This unblocked me from this stage.  Closing with this comment. 

Thanks @arirubinstein !
