### ISSUE TITLE
smart wallets for those who paid 10 BLD should be preserved

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#7537]
## Describe the bug

Much like #6645, this precious state from the previous VM should be preserved.

## To Reproduce
_IOU_

## Expected behavior
if I paid 10BLD for a wallet in pismo, I should be able to use it in vaults

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context
https://github.com/Agoric/agoric-sdk/issues/6644#issuecomment-1404138609

**Comment by gibson042** [comment]
Notes: This presumably involves lazily dealing with a list of addresses carried forward in bootstrap.

**Comment by dckc** [comment]
I think the lazy check should apply when we look for the smart wallet by address:

https://github.com/Agoric/agoric-sdk/blob/ab38bdefa7fec337f897de122041bd5b79ea0196/packages/smart-wallet/src/walletFactory.js#L184

If that lookup would fail, but the address is in the pre-paid list, then use `provideSmartWallet` to make the lookup succeed:

https://github.com/Agoric/agoric-sdk/blob/master/packages/smart-wallet/src/walletFactory.js#L246

**Comment by dckc** [comment]
The code that starts the contract is

https://github.com/Agoric/agoric-sdk/blob/master/packages/vats/src/core/startWalletFactory.js#L130

It should get the list much like the way `startPSM` gets former PSM state:
https://github.com/Agoric/agoric-sdk/blob/ab38bdefa7fec337f897de122041bd5b79ea0196/packages/inter-protocol/src/proposals/startPSM.js#L137-L140

though this case should be simpler, because only the keys are relevant; the values aren't important (we don't rely on redundantly storing x/bank balances there any longer).
