### ISSUE TITLE
Audit `makeScalarBigMapStore` usages for pseudo baggage

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#7578]
## What is the Problem Being Solved?

kind handles should be reachable from the root baggage so kinds can be redefined in vat upgrades (See https://github.com/Agoric/agoric-sdk/issues/7577). If a vat fails to redefine kinds , it will fail its upgrade. We should audit all usages of `makeScalarBigMapStore` to ensure these collections are not used to store kind handles, unless themselves added to a durable object reachable from baggage.

One particularly worrisome case is currently `makeIssuerKit`:
https://github.com/Agoric/agoric-sdk/blob/3a983388191ad2f157e79022ab48f2f86fc7e368/packages/ERTP/src/issuerKit.js#L185-L201

## Description of the Design

Manual audit until a more low level enforcement mechanism is added (#7577)

## Security Considerations

Must be sure these usages are sound to avoid future upgrade failures.

## Scaling Considerations

None

## Test Plan

If a case is found, understand why it wasn't detected by upgrade tests, and modify upgrade tests to increase coverage if applicable.

**Comment by warner** [comment]
I thought of a tool we could build to help with this, for unit tests or manual audit of a running chain. 

* take the vatID to examine
* start with a swingstore `dbDir` pathname, or a `swingstore.sqlite` pathname, or any of `swingStore.kernelStorage.kvStore`, or a `controller.dump()` output
* extract that vat's `vatStore` data
* build a temporary SQL database with tables like:
  * `collection`: `(vref == baseRef, description)`
  * `facet`: `(vref, baseRef)`
  * `object`: `(baseRef)` (plus maybe a description or kindID)
  * `export`: `(vref, reachable: BOOL)` (`!reachable` implies merely-recognizable)
  * `edge`: `(from, to)`
  * `kind`: `(kindID, handleVref, tag)`
* find the `vkind` and `dkind` entries, build a Map from kindID to virtual-vs-durable and the facetedness
  * for each kind, parse the stateShape capdata to get any slots
  * for each slot, add an `edge` from the kindhandle vref to the slot vref
* find the known collections kinds, walk the collection contents for each
  * add each to `collection`
  * for each, parse the contents to extract their slots (vrefs)
  * for each slot, add an edge from the collection's vref to the slot vref
* for the special KindHandleKind, walk the instances (`vom.${baseRef}.*`)
  * for each, add `object` with the baseref of the KindHandle vref
  * also add `kind` with the other data
* for all other kinds, walk their instances (`vom.${baseRef}.*`)
  * add a row to `object` with the baseref
  * for each facet, add a row to `facet` with the facet vref and the cohort baseref
    * it's weird, but create both one `facet` and one `object` for each single-faceted object
    * instead of merging the two
  * for each, parse the cohort data, examine all state properties
    * for each property, remember the name, parse the value, extract their slots
    * for each slot, add an edge from `${collectionVref}[${propname}]` to the target slot
* walk the vatstore exportStatus section (`vom.es.${baseRef}`)
  * for each, use the facetedness to compute the separate vrefs and status
  * for each reachable or recognizable vref, add to `export` with from='exported', to=vref
  * for extra credit, add a `(kref, vref)` to a separate table, to correlate against other vats
* add another edge from `${vatID}.baggage` to the baggage collection vref

Then, for manual audit, dump the entire table of edges and exports to a `.dot` file, and throw it at graphviz. Color virtuals and durables differently. `baggage` and `exported` will be the roots. If there are any unconnected clusters, they should stand out, and that means something would be orphaned during an upgrade. Any cluster which is reached by `exported` but not `baggage` falls into the "yes, but why?" category.

For automated use, add a `mark` column to `collection`, `facet`, `object`, and `kind`. Then traverse the reachable graph, setting `mark = true`, starting from the baggage collection and any `reachable` exports. When done, dump the unmarked `kind` objects. The unit test fails if there are any unmarked kinds.

**Comment by FUDCo** [comment]
Such a comprehensive tool might well prove useful in the future, but for the matter at hand here I think it's substantial overkill.  We don't need to pay any attention at all to facets or cohorts, since all we care about is the data.  For this issue it should be sufficient to compute the transitive closure of kindID values reachable from the baggage root and compare it to the set of kindID values that exist.  If the two sets don't match then there's a problem.

I also don't think we need to pay attention to exports at this stage, because I don't think we're trying to support some kind of use case where vat A is tasked with holding onto vat B's kindIDs for it.  This won't work in the current system anyway since exchanging messages with a remote vat requires one to be up & running, while the reassociation of existing kinds with new behaviors after upgrade happens prior to when such message exchange becomes possible.  KindIDs could be injected as vatParams, but it's not a thing anybody does right now so there can't be any extant bugs due to somebody doing it wrong.

**Comment by FUDCo** [comment]
I also don't think there are any cases where we're storing kindIDs as data in durable objects, so all we really need to pay attention to right now are collections.

**Comment by FUDCo** [comment]
On the other hand, I think there is a case we need to worry about where even if all the kinds are reachable in containers from baggage there's still a circular dependency problem between kind definitions.  I think we actually encountered some bugs of this sort in our contracts.

**Comment by mhofman** [comment]
@warner @FUDCo, I am using this issue to track a manual audit of our codebase.

It's possible there may be value to an automated tool as well, I guess as long as there is a corpus of test the tool can be applied on? However what I'm unclear about is whether an approach that would prevent this situation from arising in the first place (aka #7577), e.g. by requiring kind handles to be minted from the durable zone, would leave much value for an automated auditing tool. Would you mind filling a separate issue to describe the design and motivation of the automated tool you describe?

**Comment by FUDCo** [comment]
Yeah, it looks like there were two entirely different but tangentially related issues that were getting conflated here.  I'll make a ticket for the other one...
