### ISSUE TITLE
Enable cleanup old swingset state on bulldozer

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#7591]
## What is the Problem Being Solved?

The upcoming vaults release performs a bulldozer upgrade (#6644), which uses a sqlite DB for the whole swingstore instead of the previous combination of LMDB, sqlite and plain files.

When upgrading the new swingstore will simply create the new file backing its DB and go along merrily. However the former files backing the old swingstore will stick around on the filesystem.

We should consider cleaning up the old swingstore state for housekeeping, or at least make it easier to cleanup in the future.

## Description of the Design

- Use a new path under which to store the new swingstore. @michaelfig proposed `${cosmosHome}/data/agoric`
- (optional) If that path does not exists, remove any `${cosmosHome}/data/ag-cosmos-chain-state`

## Security Considerations

Potentially removing some unexpected data

## Scaling Considerations

None

## Test Plan

Manual?

**Comment by michaelfig** [comment]
I don't want the removal to be automatic.  We have no idea what kind of precious files (copies of slogs for debugging problems, etc) validators might be storing in the old directory.

We should socialize to validators who have gone through the upgrade that they can free up disk space by manually deleting the old directory.
