### ISSUE TITLE
cannot pass non-frozen objects error when attempting to bid on ollinet

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7601]
## Describe the bug
Get a 'cannot pass non-frozen objects like...' error when attempting to bid on Ollinet

```
brendanotoole@Brendans-MacBook-Pro agoric-sdk % inter bid by-price --price 10.05 --give 15IST --maxBuy 1_000_000ATOM --from brendan   
(Error#1)
Error#1: Cannot pass non-frozen objects like {
  method: 'executeOffer',
  offer: {
    id: 'bid-1683165512314',
    invitationSpec: {
      source: 'agoricContract',
      instancePath: [Array],
      callPipe: [Array]
    },
    proposal: { give: [Object] },
    offerArgs: { maxBuy: [Object], offerPrice: [Object] }
  }
} . Use harden()

  at sendAction (packages/agoric-cli/src/lib/wallet.js:109:47)
  at placeBid (packages/agoric-cli/src/commands/inter.js:332:26)
  at Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:417:15)
  at async packages/agoric-cli/src/bin-agops.js:76:3
```

## To Reproduce
1. Setup CLI for bidding (install Agoric SDK, all tools, set network env etc)
2. Attempt to bid
3. Receive below error

## Expected behavior
Bid should be successfully accepted

## Platform Environment
 - what OS are you using? what version of Node.js?

 - is there anything special/unusual about your platform?

Nope - just pulled down latest Xsnode tools and updated to MacOS to Ventura yesterday
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

agoric-upgrade-8-2223-g720a16fd7

**Comment by ivanlei** [comment]
Closed by #7615
