### ISSUE TITLE
automated test coverage of functionality after Pismo -> Vaults upgrade

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7640]
## Description of the Design
Use https://github.com/Agoric/agoric-sdk/issues/7499

- [x] 1. Start a new Pismo chain

- [x] 2. Do a handful of transactions to get state to preserve
- Has to be all the state we care about checking
- Provision wallets
- Have Cosmos/vbank balances
- Change governance parameters
- EC purses with invitations (to make sure it doesn’t break anything when it’s no longer present)
- [x] 3. Swapping out the binary
- [x] 4. Do the upgrade
- [x] 5. Check that the state from transactions is still present
- e..g provisioned wallets are restored
- [x] 7. Check EC restore
- They can accept fresh invitations
- Change parameters
- [x] 8. PSM functionality
- Trade again. Vbank updates
- [x] 9. Metrics (to be added in  #7705)
- Contract metrics are retained after upgrade
- [x] 10. Provision pool balance

Use https://github.com/Agoric/docker-upgrade-test/tree/main/upgrade-test-scripts to make a new upgrade handler.
It includes gov1,gov2,gov3 accounts.
Use agoric and agops CLI commands in the scripts, as an end user could. Maybe adapt https://github.com/Agoric/agoric-sdk/blob/master/packages/agoric-cli/test/agops-vaults-smoketest.sh

Consider adapting the bootstrapTests which specify behavior and expected results.

## Test Plan
- Verify that product works with realistic state after restart of all vats
- Cover the [Inter Protocol User Stories](https://docs.google.com/document/d/19xP4AjLDdHvlGYFyC_Yq3Opp7oR60rRc-9UKAyb26a4/edit#heading=h.q4dfmhvjth5q)

**Comment by raphdev** [comment]
> Add a test in https://github.com/Agoric/docker-upgrade-test/blob/main/Dockerfile that triggers a CORE_EVAL proposal (V+1 is just a contract upload and a CORE_EVAL, approved by BLD Stakers but not validators)

This sounds like Vaults -> V + 1 upgrade, while this issue describes mostly Pismo -> Vaults upgrade. Is this in scope? If it isn't we should track separately.

**Comment by turadg** [comment]
> This sounds like Vaults -> V + 1 upgrade, while this issue describes mostly Pismo -> Vaults upgrade. Is this in scope? If it isn't we should track separately.

I'll edit the test plan of this. We do have coverage of testing the V --> V+1 upgrade _ability_:
- https://github.com/Agoric/agoric-sdk/pull/7698
- https://github.com/Agoric/agoric-sdk/pull/7691
- https://github.com/Agoric/agoric-sdk/pull/7660

Per our discussion with @arirubinstein yesterday IIUC we wouldn't want that to go in upgrade-test system because it's not an actual upgrade. With something like https://github.com/Agoric/agoric-sdk/issues/7725 we could get the above into Docker upgrade-test without making recording it as an upgrade.
