### ISSUE TITLE
Vaults that receive collateral back after liquidation (reconstituted or excess collateral) do not reflect it in the UI or metrics query

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#7665]
## Describe the bug
Ran through "Reconstitute" scenario in liquidation testing, which should have resulted in a reconstituted vault with 14.899 collateral and 100.5 debt

Vault UI shows a vault with the correct amount of debt but no collateral
![image.png](https://images.zenhubusercontent.com/5fd77cb9688d8a64c14e7e66/2b7d9702-f80d-4b83-a7c9-39a1308fee98)

## To Reproduce
1. Run through liquidation in 'reconstitute' scenario
2. Validate that reconstituted vault shows no collateral in the UI

**Comment by rowgraus** [comment]
Per Sam, CLI output showed no collateral for the vault either

However, right at the time of the next liquidation, the vault appeared to receive the correct amount of collateral
<img width="658" alt="image" src="https://github.com/Agoric/agoric-sdk/assets/60824328/638fb067-2e38-42ab-8e29-da40c5bf6d11">

**Comment by rowgraus** [comment]
On new attempt, after the failed liquidation, I deposited extra collateral into the vault and now see it showing both the collateral I deposited *and* the collateral it should have received
<img width="603" alt="image" src="https://github.com/Agoric/agoric-sdk/assets/60824328/31344d81-12f9-46d6-a878-b4ff9dd747c6">

**Comment by rowgraus** [comment]
Similar behavior observed in "Happy Path" liquidation scenario in which excess ATOM is redistributed back to vault holders.  Vault in UI shows "0 ATOM to claim" but upon closing vault, user receives ATOM back

Referenced in #7757

**Comment by ivanlei** [comment]
From slack:
> tribble
> Nothing in VaultManager.distributeProceeds ever calls updateUIState on vaults

**Comment by dtribble** [comment]
As far as I can tell, [`distributeProceeds`](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/src/vaultFactory/vaultManager.js#LL624C19-L624C19) updates vault internal state directly and never calls `updateUIState` on vaults. If the same is true on other liquidation paths, then they will not update any watching UIs when the collateral and debt are changed.

**Comment by dtribble** [comment]
Ah!  Correction:  `recordLiquidation` is called (which in turn calls `updateUIState`, but before the reallocate of collateral back to the vault. As a result, it captures the 0 collateral balance in the subscription publish, and then the collateral balance is updated.

**Comment by rowgraus** [comment]
Yep this explains all the behavior we've seen around this (eg debt balance
showing but collateral not on reconstituted vaults)
