### ISSUE TITLE
VaultManager does not consider price update and allow vault creation

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#7670]
## Describe the bug

Getting below error in Wallet UI upon attempting to approve vault creation transaction (following txn signing in Keplr):

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/ce01a8f5-144c-4e1d-b65d-a67e036c5ab0)

## To Reproduce

1. Go to Vaults UI
2. Submit create vault offer
3. Approve in Wallet UI
4. Sign Keplr transaction
5. Get error

## Expected behavior

Vault should be created

## Platform Environment

- what OS are you using? what version of Node.js?
- is there anything special/unusual about your platform?
- what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots

If applicable, add screenshots to help explain your problem, especially for UI interactions.

Additional comment from Sam on original ticket
More context: The UI displays a price of 14.5, with 175% MCR. The numbers in the screenshot above appear to be enforcing a price of 0.151, which was the result of a previous price round. However, the price was since updated to 14.5, which the UI sees, but the contract doesn't seem to be enforcing.

@turadg @dckc I'm soliciting some input here, I'm thinking either the UI or the contract is reading the price from the wrong source. The UI is watching manager0.quotes, is that correct? How can we make sure the contract and UI are in sync?

**Comment by turadg** [comment]
@Chris-Hibbert figured out that we may need to clear the `lockedQuote` after a liquidation. 

The locked liquidation price (`lockedQuote`) should clear when the auction begins. Also need to check that the locked period isn't longer than the StartFrequency.

**Comment by Chris-Hibbert** [comment]
> Also need to check that the locked period isn't longer than the StartFrequency.

`computeRoundTiming` asserts this. The was a conceivable issue if the lockedPrice was to be zeroed at the end of the auction. Since it'll be zeroed at the start, there's no interaction.
