### ISSUE TITLE
Clear out current auction price at the end of an auction

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#7678]
## Describe the bug
After a liquidation auction, the auctioneer continues reporting the "current price" as the final step in the auction

## To Reproduce
Run a liquidation auction and observe!

## Expected behavior
Price should be either zeroed or N/A

**Comment by Chris-Hibbert** [comment]
When I look at [the place I thought I would need to fix this](https://github.com/Agoric/agoric-sdk/blob/effbf7f7a278863b88419e0a19ae19f0db4b30a0/packages/inter-protocol/src/auction/auctionBook.js#L699), it's already doing the right thing. 

Do you remember where you observed the current price after the end of an auction? Have you seen it do this recently?

**Comment by Chris-Hibbert** [comment]
Closed by #8070
