### ISSUE TITLE
Provisionpool Metrics aren't retained across vaults upgrade

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#7705]
to reproduce

1. `git clone git@github.com:Agoric/agoric-sdk.git && cd agoric-sdk && checkout ari/vaultstest`
2. `cd packages/deployment/upgrade-test`
3. `TARGET=agoric-upgrade-8 make build run`
4. in container, `agoric follow :published.provisionPool.metrics`
see output:
```
{
  totalMintedConverted: {
    brand: slot(0,"Alleged: IST brand"),
    value: 20000000n,
  },
  totalMintedProvided: {
    brand: slot(0),
    value: 750000n,
  },
  walletsProvisioned: 2n,
}
```
5. `TARGET=agoric-upgrade-10 make build run`
6. in container, `agoric follow -F :published.provisionPool.metrics`
see output:
```
{
  totalMintedConverted: {
    brand: slotToVal("board0257","Alleged: IST brand"),
    value: 0n,
  },
  totalMintedProvided: {
    brand: slotToVal("board0257"),
    value: 0n,
  },
  walletsProvisioned: 0n,
}
```

**Comment by dckc** [comment]
nice catch!

This looks like it can be solved similarly to the way PSM metrics are preserved:

https://github.com/Agoric/agoric-sdk/blob/d15a03cc8c21560c743cf67a938a6773eeb1dcb4/packages/inter-protocol/src/proposals/startPSM.js#L233-L247

**Comment by raphdev** [comment]
I added a test for this that should help reproduction as well as testing a potential fix. Since the test fails, my suggestion would be to test the proposed fix against the commit in the PR and make sure it builds correctly:


```sh
# in packages/deployment/upgrade-test
make local_sdk
make build
```
