### ISSUE TITLE
reserve cosmos account is "not allowed to receive funds"

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#7727]
In a fresh `start-local-chain.sh` setting in agoric-sdk d06717b40

```
agd \
  --home=t1/bootstrap --keyring-backend=test --from=bootstrap \
  tx bank send bootstrap agoric1ae0lmtzlgrcnla9xjkpaarq5d5dfez63h3nucl 2382019900uist \
  --gas=auto --gas-adjustment=1.2 --broadcast-mode=block --yes --chain-id=agoriclocal
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: agoric1ae0lmtzlgrcnla9xjkpaarq5d5dfez63h3nucl is not allowed to receive funds: unauthorized [agoric-labs/cosmos-sdk@v0.45.11-alpha.agoric.2/x/bank/keeper/msg_server.go:43] With gas wanted: '0' and gas used: '47985' : unknown request
```

Context: based on discussion with @rowgraus , I was trying to confirm that we can move IST from the cosmos reserve account to the reserve contract via a core eval proposal. But I couldn't even get as far as putting funds into that reserve account.

---

@JimLarson once the provision pool account is "fixed" by the upgrade-10 handler, will we see the same problem?

---

The upgrade-10 handler will not affect the reserve pool. The reserve pool, like all module accounts except for the provision account, may not accept external transfers. The exception for the provision pool is implemented [here](https://github.com/Agoric/agoric-sdk/blob/d06717b40354171f921de509daf821f9191e1fd6/golang/cosmos/app/app.go#L966).

---

I think we need another exception for the reserve account. Is that more or less a 1-line change? I could give it a try... but maybe I'd mess and you'd rather do it?

---

We'd need to make the corresponding change in the location I cited, plus a chain start change to explicitly create the reserve account as a module account - to make sure that in new chains the reserve account doesn't accidentally get initialized as a default account. I can do it, but let's surface this in team-engineering to get a thumbs-up, since we're so close to cutting the release.

**Comment by dckc** [comment]
p.s. with the fix in #7728, we can indeed transfer to the reserve contract from the reserve module account:

[0-reserve-txfr-notes.md](https://gist.github.com/dckc/9e747cb91f61d2b2923c8633b864fbd0#file-0-reserve-txfr-notes-md)
