### ISSUE TITLE
ToyUSD PSM governance brands are mismatched

### ISSUE THREAD

**Issue by raphdev** [Agoric/Agoric#7750]
## Describe the bug
The PSM governance metrics have the correct values, but the brands do not match the boardIDs in `published.agoricNames`:

```shell
# agoric follow -lF :published.agoricNames.brand
[
  [
    "AUSD",
    slotToVal("board04542","Alleged: AUSD brand"),
  ],
  [
    "BLD",
    slotToVal("board0566","Alleged: BLD brand"),
  ],
  [
    "IST",
    slotToVal("board0257","Alleged: IST brand"),
  ],
  [
    "Invitation",
    slotToVal("board0074","Alleged: Zoe Invitation brand"),
  ],
  [
    "USDC_axl",
    slotToVal("board01034","Alleged: USDC_axl brand"),
  ],
  [
    "USDC_grv",
    slotToVal("board05736","Alleged: USDC_grv brand"),
  ],
  [
    "USDT_axl",
    slotToVal("board03138","Alleged: USDT_axl brand"),
  ],
  [
    "USDT_grv",
    slotToVal("board03040","Alleged: USDT_grv brand"),
  ],
  [
    "timer",
    slotToVal("board0425","Alleged: timerBrand"),
  ],
  [
    "ATOM",
    slotToVal("board02152","Alleged: ATOM brand"),
  ],
]
```

```shell
# agoric follow -lF :published.psm.${PSM_PAIR}.governance
{
  current: {
    Electorate: {
      type: "invitation",
      value: {
        brand: slotToVal("board02810","Alleged: Zoe Invitation brand"),
        value: [
          {
            description: "questionPoser",
            handle: slotToVal("board05311","Alleged: InvitationHandle"),
            installation: slotToVal("board04312","Alleged: BundleInstallation"),
            instance: slotToVal("board0074","Alleged: InstanceHandle"),
          },
        ],
      },
    },
    GiveMintedFee: {
      type: "ratio",
      value: {
        denominator: {
          brand: slotToVal("board0188","Alleged: IST brand"),
          value: 10000n,
        },
        numerator: {
          brand: slotToVal("board0188"),
          value: 0n,
        },
      },
    },
    MintLimit: {
      type: "amount",
      value: {
        brand: slotToVal("board0188"),
        value: 133337000000n,
      },
    },
    WantMintedFee: {
      type: "ratio",
      value: {
        denominator: {
          brand: slotToVal("board0188"),
          value: 10000n,
        },
        numerator: {
          brand: slotToVal("board0188"),
          value: 0n,
        },
      },
    },
  },
}
```

Additionally, querying this in vstorage shows the brands in "\@qclass".

## To Reproduce
1. `cd packages/deployment/upgrade-test`
2. `make build_test run`
3. Wait up to a minute for bootstrap to finish...
4. `agd q vstorage data published.psm.${PSM_PAIR}.governance | grep qclass`
5. `agoric follow -lF :published.agoricNames.brand`
6. `agoric follow -lF :published.psm.${PSM_PAIR}.governance`

Tests in https://github.com/Agoric/agoric-sdk/compare/raph/7730-upgrade-tests fail.

## Expected behavior

Brand boardIDs should match and there should be no qclass in metrics or governance parameters, since we're using smallcaps.

## Platform Environment
 - Using docker-upgrade-tests

## Additional context

First seen on 91ba5f94983f6cd67947b3c543a7d9d562aee555, observed present in f078d4221812788c19ac3df9febe5f7c1b11cb48.

Related to #7705. @dckc raised this in #7730 and noted that tests aren't sensitive to this, so we discussed adding some tests in upgrade-tests as currently only values are checked.

**Comment by dckc** [comment]
ProvisionPool? the steps to reproduce seem to be about the PSM. I'm juggling too much.

**Comment by dckc** [comment]
The `PSM_PAIR` in `published.psm.${PSM_PAIR}.governance` seems to be `IST.ToyUSD` but there is no such PSM in the running config.

The `ibc/toyusd` denom is registered as `USDC_axl`. If we use that pair, we get the expected results:

```
# agd q vstorage data published.psm.IST.USDC_axl.governance | grep qclass
```

@arirubinstein notes this is a consequence of evolving toward the emerynet config; we seem to need a 3rd option in addition to `build` and `build_test`.

See also discussion of config file names in #7746
