### ISSUE TITLE
totalDebt outdated after adjusting vault

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#7751]
## Describe the bug
On the latest master, testing on a local chain, looks like totalDebt is not updating after I created a vault with 1000 IST of debt and adjusted it down to 800 IST:

![image](https://github.com/Agoric/agoric-sdk/assets/8848650/c8fc8ebb-881a-47d8-92a9-4bc5481ccd4a)

## To Reproduce
1. `cd packages/inter-protocol && scripts/start-local-chain.sh`
2. Go to dapp-inter and create a vault
3. Note the "IST Outstanding (Vaults)" updates to non-zero amount
4. Adjust the vault to lower the debt
5. Observe the "IST Outstanding (Vaults)" doesn't update
6. Adjust the vault again, see it update to the previous value after the prior adjustment

Tried reloading the page and double-checking with `agd query` to rule out the possibility of a UI bug

## Expected behavior
It updates at step 5, and at step 6 it shows the most up-to-date value

## Platform Environment
agoric-sdk @ f078d4221812788c19ac3df9febe5f7c1b11cb48

**Comment by raphdev** [comment]
Is the total collateral amount also reported correctly? I can't tell.
