### ISSUE TITLE
Vaults receiving collateral back post-liquidation do not correctly report state

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7757]
## Describe the bug

Following happy path (flow 1) per https://github.com/Agoric/agoric-sdk/issues/7123 for liquidation bidding testing, my 3 liquidated vaults failed to receive any collateral (per Vaults UI) when expectation was that they each should have received a proportional amount as per below given auction has succeeded in raising sufficient IST to cover debt.

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/10b53d05-5238-4778-bc97-78da04a056fc)

See also Liquidation Model that outlines happy path scenario: https://docs.google.com/spreadsheets/d/16OZh7zSfwvVF777peK8NLhDeGjqHV3R9L3ZOYto28e0/edit?usp=sharing

## To Reproduce

 (Using head of master local chain setup from upgrade-test (TARGET...agoric-upgrade-10...etc)
1. Create 3 vaults on Gov 1 account
Vault 1: 15 ATOM, 100 IST debt (100.5 after mint fee)
Vault 2: 15 ATOM, 103 IST debt (103.51 after mint fee)
Vault 3: 15 ATOM, 105 IST debt (105.525 after mint fee)

2. Place bids via Gov 1 account
Bid 1: 80 IST at 10% discount
Bid 2: 90 IST at price of $9
Bid 3: 150 IST at 15% discount

3. Trigger liquidation by changing price from 12.34 to 9.99
4. Observe auction. Upon completion check vaults in Vaults UI
5. See 0 collateral balance to claim on all 3 liquidated vaults

## Expected behavior

Each vault should have:
3.373
3.024
2.792 
respectively

## Platform Environment

- what OS are you using? what version of Node.js?
- is there anything special/unusual about your platform?
- what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/acd5f8d4-56e3-4347-b48f-1a23596a063f)

**Comment by otoole-brendan** [comment]
Recording of said issue: https://agoric.zoom.us/rec/share/XUsEl75_KdidIEfKg7g_oirMvYAOJuqx0Dv74ixrt3QHMoRApY7U9RIGHnu9ugCK.EcDdfAnKYyY9o_Ei 
(ask Brendan for password to view)

**Comment by rowgraus** [comment]
This issue is subsumed by #7665 - comment added referencing this issue on that issue.  I am closing this for now
