### ISSUE TITLE
Automate a daily build & package for release process to ensure releases work well

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#7776]
## What is the Problem Being Solved?
We currently rarely run a release and when we do it's at a point that we're short on time. Errors found in this time period - like https://github.com/Agoric/agoric-sdk/issues/7769 - are stressful and can cause delay.

## Description of the Design
Let's run something that makes the build happen daily.

**Comment by michaelfig** [comment]
I think #7770 handles this gracefully, by packing a release as part of every PR's CI.  That provides actionable feedback to the person who makes changes that break the release.

Closing as complete.  Feel free to reopen with further discussion if this is unsatisfactory.
