### ISSUE TITLE
inter bid list errors with "unknown record updated undefined"

### ISSUE THREAD

**Issue by raphdev** [Agoric/Agoric#7777]
## Describe the bug
`agops inter bid list` returns:

```
(Error#1)
Error#1: unknown record updated undefined

  at Object.update (packages/smart-wallet/src/utils.js:73:15)
  at storedWalletState (packages/agoric-cli/src/lib/wallet.js:228:17)
  at async Promise.all (index 1)
  at async Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:573:34)
  at async packages/agoric-cli/src/bin-agops.js:78:3
```

## To Reproduce
1. `cd packages/deployment/upgrade-test && make build run`
2. place some bids
3. note bids are accepted and wallet UI shows bids as pending
4. `agops inter bid list --from $GOV1ADDR --keyring-backend=test --all`

2 and 3 are optional and I was able to reproduce with 1 and 4.

## Expected behavior

Current bids are listed, and empty if no bids.

## Platform Environment

* Via docker upgrade-test.
* Current HEAD: 8d17ccef5b83f5feff95318e234067d1866edd8d
* `git describe --tags --always`: agoric-upgrade-8-2726-g8d17ccef5

## Additional context

@otoole-brendan first observed this while placing bids.

## Screenshots
TODO: @otoole-brendan screenshots?

**Comment by dckc** [comment]
seems to be a consequence of the `{}` wallet update records introduced in #7763.
