### ISSUE TITLE
1 vault not reconstituted and liquidation penalty atom not added to reserve balance

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7784]
## Describe the bug
Upon re-testing [liquidation reconstitution scenario (flow #2)](https://docs.google.com/document/d/1bXnQ_o3wwfnu-uhX2KSb6ZXB0dU6CsAsGBWm1DXgmE0/edit?usp=sharing) following PR fixes (https://github.com/Agoric/agoric-sdk/pull/7752) from last night, I discovered:

- only 1 vault reconstituted (the highest CR vault) (expecting 2 vaults to do so)
- reconstituted vault value after auction were 14.79 ATOM and 100.5 IST -> was expecting 14.899 but debt is as expected.
- liquidation penalty ATOM was not added to reserve balance
- shortfall balance looked correct (5.525)

## To Reproduce
1. Using 12.34 oracle price, set up liquidation testing scenario flow #2 per https://docs.google.com/document/d/1bXnQ_o3wwfnu-uhX2KSb6ZXB0dU6CsAsGBWm1DXgmE0/edit?usp=sharing 
2. Change to 9.99 to trigger liquidation
3. Observe auction start and complete.
4. Check reserve metrics to check post-auction values
5. Check Vaults UI to check reconstituted vaults

## Expected behavior

- Vault 1 and vault 2 should have been reconstituted
- liquidation atom penalty should have been added to reserve balance

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/2fb3be1a-d47b-42b9-b720-c8fae895630d)If applicable, add screenshots to help explain your problem, especially for UI interactions.

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/5d2ac754-5f56-41f9-8243-5e3c15de9638)

**Comment by dckc** [comment]
@Chris-Hibbert investigated this and concluded it's as-designed.
@otoole-brendan plans to double-check.
