### ISSUE TITLE
test of liquidations after upgrade

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7791]
## What is the Problem Being Solved?

Auction and liquidation require the coordination of multiple contracts with precise timing. We need to be confident these work after upgrade. We want these in CI to prevent breakage.

## Description of the Design

Ideally we get this into the Docker upgrade-test, but the main bootstrap configures auction StartFrequency to 60min. Two auctions get scheduled at start so that's 2 hrs, which is too long for CI.

One alternative is to test this only in the "test" bootstrap mode and set its config to a rapid auction StartFrequency.

Another is to develop confidence that a bootstrapTest would suffice and implement it there instead.

**Comment by ivanlei** [comment]
Reopening for merge into release branch
