### ISSUE TITLE
Liquidation never takes place following rebuild from master despite conditions conducive to it, vaults hung in liquidating state and bids never fill

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7796]
## Describe the bug
After rebuilding docker from master to test @Chris-Hibbert's fix https://github.com/Agoric/agoric-sdk/issues/7784 - I setup test scenario for reconstitution, pushed price to trigger liquidations but liquidation never completes (even though auction continues to run).
Vaults are hung in 'liquidating' state'.

## To Reproduce
1. Rebuild docker against Master
2. Set Flow 2b liquidation scenario with price of 12.34, 3x vaults + 2 bids as per: 
3. Observe default 1hour auction schedule via 'agops inter action status', wait for 1-1.5 cycles for it to pick up testing default of 10min (600s start freq) and 5mins price lock period (300s).
4. Observe vaults go into 'liquidating' state in Vaults UI but never complete liquidation.
5. Observe no collateral on offer and no bids filled for outstanding debt despite bids in.
6. Observe 'liquidating' vaults stuck in loop.
7. Observe auctions start and complete in cycles but no collateral on offer or bids filled.

## Expected behavior
Expected auction schedule to have settled, liquidation to have occurred and auction complete with bids filled and 2x vaults reconstituted

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context
Tried changing auction params to see if it would refresh/wake-up liquidator but didn't have an effect.

## Screenshots
![Pasted Graphic 6](https://github.com/Agoric/agoric-sdk/assets/93355546/27ba81ca-c017-431f-833e-0e2efedd67ce)

<img width="649" alt="Pasted Graphic 7" src="https://github.com/Agoric/agoric-sdk/assets/93355546/265edb48-c91c-4f21-857e-9df3571e4334">

<img width="774" alt="Pasted Graphic 8" src="https://github.com/Agoric/agoric-sdk/assets/93355546/7febb1cc-043a-46c0-92b2-410468f1fc12">

**Comment by otoole-brendan** [comment]
Created another vault and dropped price to 9.99 to force liquidation seemed to have unstuck it a bit. The vault was actually liquidated properly and auction ticked forward selling some collateral. Vault even received excess collateral but the other 3 vaults remain stuck in state of 'liquidating'
![image](https://github.com/Agoric/agoric-sdk/assets/93355546/5ba4f303-9f24-4a44-90ce-d08053d5e9f6)
<img width="760" alt="image" src="https://github.com/Agoric/agoric-sdk/assets/93355546/62d307c0-2229-4410-a0e0-046529d78757">

**Comment by otoole-brendan** [comment]
Was able to reproduce on another account - the 3 vaults are hung in liquidating state, auction never starts, bids are not filled, vaults not liquidated.
![image](https://github.com/Agoric/agoric-sdk/assets/93355546/1abf0fde-ae2b-40a7-96af-b99ad1f94059)
<img width="400" alt="image" src="https://github.com/Agoric/agoric-sdk/assets/93355546/01cfe67b-c784-4ea8-a3f9-9096b96836e6">

**Comment by dckc** [comment]
> To Reproduce
> 1. Rebuild docker against Master

Master is currently feb253e ; I hope that's close enough, though I suppose I could use the time this issue was opened to be sure...
