### ISSUE TITLE
Auction schedule adopts 60min start freq schedule on start-up, then 30min schedule for one auction before finally settling on 10m schedule.

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7809]
## Describe the bug
After I rebuild from master this morning (and cleared docker cache) - auction schedule tells me activeStartTime is 17:00 UTC (T+35mins) next auction start time is in ~1.5hours at 18:00UTC (see output below). 

Auction does not first run until 18:00UTC (signalling 60min start freq schedule) and when it does it runs with 3min clock steps (and we suspect 30mins price lock period but that could not be verified at the time).

At 18:00UTC, nextStartTime updates to 18:30UTC - signalling it's about to follow a 30mins start freq schedule.

The 18:00UTC auction runs and works as expected - takes 24mins (3min step time) - happy path runs fine -> liquidated vaults get excess collateral, bids are filled etc.

At 18:30 UTC, the nextStartTime updates to 18:40UTC - signalling it's now adopting 10min start freq schedule. Every subsequent nextStartTime is 10mins so the 10min schedule persists.

## To Reproduce
1. Rebuilt docker from master as of 5/19 8am PST
2. Observe currentStartTime and NextStartTime with 'agops inter auction status'
3. Set up happy path liquidation scenario per https://docs.google.com/document/d/1bXnQ_o3wwfnu-uhX2KSb6ZXB0dU6CsAsGBWm1DXgmE0/edit?usp=sharing (including changing price to 9.99 to trigger liquidation)
4. Observe when first auction actually runs
5. Observe it follow 60mins schedule with 3mins clock steps and 30mins price lock period
6. Observe it revert to a 30mins schedule for one auction cycle
7. Observe it revert to 10min schedule which then persists

## Expected behavior
Auction should adopt pre-set auction schedule (10mins) upon start-up. At very least, shouldn't smooth to 10min schedule with a 30min schedule which is unexplained at this point in time.

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context
![Pasted Graphic 12.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/5d06912c-41d2-49dd-bc45-7cf89fc7d078)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by dckc** [comment]
@otoole-brendan please copy the slogfile to some place safe... gdrive or something.
The `cp slog.slog /workspace` command you entered in the container should have resulted in a file in your clone of `agoric-sdk`: `agoric-sdk/packages/deployment/upgrade-test/slog.slog`

**Comment by otoole-brendan** [comment]
Update on auction status: completed after ~24mins which means 3min clock steps confirming first auction that ran used 60min start freq, 3mins clock steps and we assume 30min price lock period (but we couldn't confirm).
Happy Path was successful -> bids filled, liquidated vaults received excess collateral.
![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/d092991c-ffbd-4293-9ce3-e6d3bf38f4d0)

**Comment by otoole-brendan** [comment]
Update: 
after 18:00UTC auction concludes and T = 18:30, NextStartTime updates to show 10mins start freq, 20s clock step and 5mins price lock period

root@c4c3c1fc6749:/usr/src/agoric-sdk# agops inter auction status
{
  "schedule": {
    "activeStartTime": "2023-05-19T18:30:02.000Z",
    "nextStartTime": "2023-05-19T18:40:02.000Z",
    "nextDescendingStepTime": "2023-05-19T18:31:02.000Z"
  },
  "book0": {
    "startPrice": "9.99 IST/ATOM",
    "currentPriceLevel": "9.4905 IST/ATOM",
    "startCollateral": "0 ATOM",
    "collateralAvailable": "0 ATOM"
  },
  "params": {
    "DiscountStep": "5.00%",
    "ClockStep": "00:00:20",
    "LowestRate": "65.00%"

**Comment by Chris-Hibbert** [comment]
The 30 minute schedule isn't an anomaly!  It's just the scheduler scheduling a 10 minute auction after the **endTime** of the 60 minute auction. The 60 minute auction has 8 descending steps of 3 minutes each, so it's done in 24 minutes. The next multiple of 10 minute is at :30, so it schedules it then.  This is completely fine.

**Comment by dckc** [comment]
@rowgraus and @otoole-brendan are satisfied that this is working as-designed
