### ISSUE TITLE
Unexpected excess collateral amounts distributed to happy path liquidated vaults

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7837]
## Describe the bug
When testing happy path liquidation scenario following #7779 during pre-RC cutting testing  - I noticed a slight discrepancy in the excess collateral each vault received vs what was expected. I one case - it was higher than expected and then lower than expected for other two vaults.

The delta is not quite the penalty (thought it might be penalty-related):
Expected - Actual = Delta
Vault 1: 3.373-3.52 = +0.147
Vault 2: 3.024-3.18 = -0.156
Vault 3: 2.791-2.64 = -0.151

## To Reproduce
1. Configure vaults and bids per happy path liquidation scenario
2. Trigger liquidation by setting price to 9.99
3. Await for auction to complete and for liquidated vaults status to update to show excess collateral received

## Expected behavior
Expected to receive V1: 3.373 V2: 3.024 V3: 2.791 per liquidation model https://docs.google.com/document/d/1bXnQ_o3wwfnu-uhX2KSb6ZXB0dU6CsAsGBWm1DXgmE0/edit?usp=sharing

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/29084f40-a9d2-40dc-88f8-d8ab9d1f7083)If applicable, add screenshots to help explain your problem, especially for UI interactions.

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/c4a2cf20-8654-492d-935d-f3958908773e)

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/16a91380-e184-4a01-8354-9b3731efda7c)

**Comment by otoole-brendan** [comment]
@Chris-Hibbert this may relate to #7806. Previously discussed in Slack about a week ago but I just realized I'd never raised a ticket since we determined it wasn't a RC blocker (https://agoricopco.slack.com/archives/C038E5369FT/p1684365506388859)

**Comment by Chris-Hibbert** [comment]
This will be fixed in #7827.  The penalty wasn't being deducted from the vault's collateral to find the maximum that could be returned.  With this fixed, I get the following in the "Happy path" scenario.

vault | collateral | actual debt | debt as collateral | penalty as collateral | max return
-|-|-|-|-|-
vault 1 | 15000000 | 100.5M | 11,474,253 | 100,601 | 3,425,146
vault 2 |  15000000 | 103.515M | 11,818,481 | 103,619 | 3.077,900
vault 3 |  15000000 | 105.525M| 12,047,966| 105,631 | 2.846,403
