### ISSUE TITLE
Changed 'EndorsedUI' to 'ReferencedUI' as a governed parameter so it reflects same in Econ Gov UI

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7839]
## What is the Problem Being Solved?

This is a contract change to support https://github.com/Agoric/dapp-inter/issues/125.

## Description of the Design

Change 'EndorsedUI' to 'ReferencedUI'. End result should be Econ Gov UI should not show 'EndorsedUI' but 'ReferencedUI' to align with consistent language including #125. 
 https://agoricopco.slack.com/archives/C03FUCJV2J2/p1685031797142509

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/414285dc-bd8f-495a-ad94-ca54d819f226)

**Comment by dckc** [comment]
Is this really about #125 Comment stale? Or is the citation a little off?
