### ISSUE TITLE
In Ollinet, auction continued selling past IST limit

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#7842]
## Describe the bug
Observed in Ollinet on 5/25
Auction continues selling ATOM past the IST raise target.  Extra IST raised not apparent in metrics.

Note: had not seen this behavior in previous testing.  Recent tests on master (from Turadg) did not show it either.  Have reproduced it twice in Ollinet, so filing.

Observed behavior
Ran HappyPath scenario from Liquidation Model
Auction fully filled all 3 bids instead of filling 2 and partially filling the last.  This resulted in selling too much ATOM (ended with 8.427481 ATOM instead of 9.659 ATOM) and raising 320 IST instead of 309.54
Correctly paid 0.30985 ATOM as penalty to reserve
Was left with 8.11xx ATOM to return to Vault holders

Vault holders received excess collateral correctly given those numbers.  However, it is not clear where the extra 10.46 IST raised ended up.  Did not observe it in Reserve or Vaults

## To Reproduce
In Ollinet
Set auction frequency, clock step, delay period, to reasonable settings for testing (10 minutes, 20 seconds)
Set oracle price to 12.34
Set up Vaults from Happy Path scenario - ensure no other vaults are present
Set up Bids from Happy Path scenario - ensure no other bids are present
Set oracle price to 9.99
Await liquidation auction to complete

## Expected behavior
Described above 

## Screenshots
See auction with too little collateral remaining
![image.png](https://images.zenhubusercontent.com/5fd77cb9688d8a64c14e7e66/73346f8a-56f8-446e-ab3a-387f6e005c6b)

**Comment by rowgraus** [comment]
Repro'ed on second attempt by me and @ivanlei

**Comment by Chris-Hibbert** [comment]
I've seen similar effects in tests running with the fake clock. If you set up the timer so it (unintentionally) skips over the start time, you can end up with the auction running without having copied the `proceedsGoal` from `startProceedsGoal` over to `remainingProceedsGoal`. Once in that state, the auction doesn't know that it should stop selling at some point.

That could happen if `settleAtNewRate` were called without calling `setStartingRate`, but I don't know how to cause that without timequakes or mismatched schedule params.

What are the chances that logs are available, or even slogs?
The release running on Ollinet is *ea8c1c64911b4c58fb43635b25e17e3d50d0cf2a*

**Comment by otoole-brendan** [comment]
Just reproduced this on Emerynet @Chris-Hibbert @rowgraus

**Comment by otoole-brendan** [comment]
Screen grab of Emerynet auction status shortly after start. Auction ran at 11:15AM PST/1:15PM CT 
<img width="422" alt="Pasted Graphic 20" src="https://github.com/Agoric/agoric-sdk/assets/93355546/a617f117-509d-4b04-9a8c-f6ffd5445963">

**Comment by Chris-Hibbert** [comment]
```
10:02:51  previous auction ends
10:10:09   capture oracle price,  start round
10:10:10  start round at 105%
10:10:12  add assets
10:10:30 start round at 100%
10:10:50 start round at 95%
10:11:09 start round at 90%, sell to two bidders w/out proceeds limit
```
**The assets arrived nearly 3 minutes into the auction**. I intended to ensure that when that happened, the proceeds goal would be increased, but it looks like I missed a case. In the meantime, notice that the `auctionStartDelay` doesn't seem to be sufficient.

**Comment by otoole-brendan** [comment]
@Chris-Hibbert I tested with 3min auctionStartDelay and it worked i.e. auction stopped when it reached target IST raise, 2 bids filled and 3rd partial, all values matching as expected. Given this - I think the fix here is to increase auctionStartDelay default in any bootstrap, or have EC change this after upgrade.
