### ISSUE TITLE
Vaults stuck in liquidating state

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7850]
@otoole-brendan commented on [Fri May 26 2023](https://github.com/Agoric/dapp-inter/issues/132)

## Describe the bug

After testing reconstitution scenario on Emerynet (which was successful) - the two reconstituted vaults were liquidated again in the next auction (expected). While in a state of 'liquidating' - I changed the price to 12.34 (previously 9.99). Even thought the auction finishes, the vaults never leave the liquidating state (i.e. they are not reconstituted, at least per the UI). 
I'm unable to take action/click etc.

Looks like this 

## To Reproduce

1. Test Reconstitution liquidation scenario (or I suspect happy path)
2. When vault is in a state of 'liquidating' - change the price to something higher than liquidation price i.e. 12.34
3. Oberve when auction finishes if vaults complete liquidation/are reconstituted

## Expected behavior

Changing price during liquidation should not break/hang the state of the vaults in the UI

## Platform Environment

- what OS are you using? what version of Node.js?
- is there anything special/unusual about your platform?
- what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/26375838-3d45-449a-a644-cfaa2e26d15d)If applicable, add screenshots to help explain your problem, especially for UI interactions.

---

@rowgraus commented on [Fri May 26 2023](https://github.com/Agoric/dapp-inter/issues/132#issuecomment-1564821074)

Metrics show that the vaults have correctly reconstituted.  However, the status is stuck as Liquidating, which prevents the user from adjusting their vault in the UI
<img width="583" alt="image" src="https://github.com/Agoric/dapp-inter/assets/60824328/0f8871fb-f1d0-4809-b928-2164be166062">

**Comment by rowgraus** [comment]
New liquidation auctions do not pick these vaults up even if they are underwater from a collateralization standpoint.  They appear stuck in this status.

**Comment by turadg** [comment]
Proximal cause was https://github.com/Agoric/agoric-sdk/issues/7851 but acceptance criteria for this issue is that we have general error handling
