### ISSUE TITLE
changes to go.mod/go.sum do not cause lerna version bump of golang/cosmos/

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#7912]
While @JimLarson and I were doing the `mainnet1B-rc3` release last night, following the MAINTAINERS.md recipe, we noticed that `yarn lerna version` did not create any new versions of any packages. The only changes that went into `rc3` were to `go.mod`, `go.sum`, and `CHANGELOG.md` (all at the top of the tree, not in any package). While we knew there were no JS code changes, and so we didn't expect a lot of new packages, there's still the `@agoric/cosmos` package (whose `package.json` lives in `golang/cosmos/`).

Our release process, specifically [get-released-tags.js](https://github.com/Agoric/agoric-sdk/blob/39b15861be74ddab196be88f24476f04cc4acb6f/scripts/get-released-tags#L15), creates a `vNN.NN` tag for each  e.g. `@agoric/cosmos@NN` tag it finds. This tag is used by the `go get` build process.

The problem we ran into was that `get-released-tags.js` did not see a new `@agoric/cosmos` tag, so it did not create a new `vNN.NN` tag, which means the go build process would not have anything to work with.

To overcome this, we committed a small change to `golang/cosmos/CHANGELOG.md` (which is normally only modified by the `lerna version` automation), then re-ran the `yarn lerna version` command. The change allowed `lerna version` to believe that the go code had changed, so it bumped the version of `golang/cosmos/`, creating the necessary tag, and also bumped the version of all packages that transitively depend upon it.

(we tried using `yarn lerna version --force-publish=@agoric/cosmos`, but it didn't work)

The core issue is that the top-level `go.mod` and `go.sum` files are effectively source files, which are just as important to the built Go binaries as the contents of `golang/cosmos/*`, but because they don't live there, `lerna version` doesn't notice them.

I think we need to either find a way to move these files into that subdirectory, or somehow teach `lerna` to pay attention to them, or establish a convention that every time we change them we must also change something under `golang/cosmos/`. Or, move all the golang stuff into a separate repo, I suppose.

cc @michaelfig @JimLarson

**Comment by JimLarson** [comment]
...or stop pushing the golang stuff as an NPM package. I don't think there are any consumers.

**Comment by michaelfig** [comment]
For current master, I have already moved these files under `golang/cosmos/`

> I don't think there are any consumers.

The reason I moved them is because I started testing the consumers in CI.  I haven't yet given up hope that users would only need to run `npx agoric ...` to get access to all of the CLI's functionality, including running a local chain.

**Comment by michaelfig** [comment]
Closing due to fix landed on `master`.  Please reopen if the problem reoccurs.
