### ISSUE TITLE
Vault smoke test - refunded vault "debt requested too small to accrue interest"

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#7961]
Seeing issue below when attempting to create first vault.  The min debt is 5 IST and I'm attempting to create with 30 IST. 

The vault creation fee is currently set at 0.0% and stability fee is set at 2.5%.  Note - attempted twice and got same results. 

![image.png](https://images.zenhubusercontent.com/5fd77cb9688d8a64c14e7e66/e1c1e56f-b912-4d5a-9a35-104e8d172146)

**Comment by otoole-brendan** [comment]
reproduced:
<img width="439" alt="image" src="https://github.com/Agoric/agoric-sdk/assets/93355546/81d20313-78b4-4cbc-b9c3-66c529e7d3f5">

**Comment by rowgraus** [comment]
Driven by a setting of zero on the vault creation fee.  Zero is not a recommended value as it may drive excess chain activity.

Resolution is to work with the EC to have them change this value.
