### ISSUE TITLE
CI job to run benchmarks and publish data to a dashboard

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#7964]
## What is the Problem Being Solved?

#7960 adds a `yarn bench` command, which runs some (currently just one) benchmark test, and creates a `.json` file in a well-known place.

`node ➜ ~/trees/agoric-sdk/packages/vats $ cat benchmark-stress-vaults.json`

```json
{
  "name": "stress-vaults",
  "durationMs": 3556.3310430049896,
  "avgPerVaultMs": 355.633104300499,
  "memStats": {
    "memoryUsage": { .. },
    "heapStats": { .. },
    "statsTime": { .. },
  },
  "test": "stress vaults",
  "where": "agoric-sdk/packages/vats/test/bootstrapTests/bench-vaults-performance.js"
}
```

Currently the only meaningful measurement in this file is `avgPerVaultMs`. The other useful keys are `name`/`test`/`where`. (The memory data includes kernel and AVA overhead, so is not particularly useful to track long-term).

The task is to create a dashboard on a service like DataDog, with a time-series graph of the measurement. Also, create a GitHub Actions job which runs this benchmark and uploads the data to the dashboard. The job should run daily, and also once per each push to the `master` branch.

## Description of the Design

I'll make a branch with the sketch of the GH Actions .yml file. It will need a DataDog API key in our repo's `secrets` stash.

## Security Considerations

None

## Scaling Considerations

Should be pretty lightweight: the test takes about 60s to run, and will only run once per commit (plus once per day).

## Test Plan

No extra tests necessary: seeing the dashboard get updated will convince us that this works.

**Comment by warner** [comment]
https://github.com/Agoric/agoric-sdk/tree/7964-benchmark-ci-job is the branch

**Comment by toliaqat** [comment]
Initial vault benchmark tests are added in CI with a DD dashboard showing the historical results. We will add more benchmark tests to CI as they become available from https://github.com/Agoric/agoric-sdk/issues/8327.
