### ISSUE TITLE
add Agoric NFT offer legibility to Keplr Wallet extension

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7975]
## What is the Problem Being Solved?

Agoric offers are more rich that most Cosmos transactions. The most popular Cosmos wallet is [Keplr](https://github.com/chainapsis/keplr-wallet) and it renders them as JSON, which users cannot easily understand. We built https://github.com/Agoric/wallet-app/ to present the offers in a very legible way to users, but it requires a separate browser tab and a complicated bridge with the dapp.

## Description of the Design

Add a feature to Keplr Wallet whereby it can detect an Agoric offer and render it helpfully to the user.

This ticket is to fork their repo and add the feature in a branch. Once we've validated it we can send it as a PR upstream.

## Test Plan

With the branch build a Chrome extension and test usability with real users.

Must render NFTs (non-vbank assets) as more than a data dump.

Working with the release from the Chrome Web Store.

**Comment by samsiegart** [comment]
https://github.com/chainapsis/keplr-wallet/issues/804

**Comment by turadg** [comment]
This is partially implemented. Still need to support non-vbank assets (NFTs).

We'll keep this open until the functionality is available in the Chrome Web Store.

**Comment by aj-agoric** [comment]
Returning to the appropriate state of "In Progress" as "Up Next" was a mistake.

**Comment by turadg** [comment]
OpCo eng work is done. Will close once Keplr has merged it. May require more eng work to shepherd.

Meanwhile we may improve the UX, though that work is not P1/Blocker.

**Comment by turadg** [comment]
Closing as it's been available in Chrome Web Store since Aug 30.

**Comment by turadg** [comment]
Closed in error because legibility is in CWS. Reopened because only vbank assets are fully legible.

Will close once non-vbank assets have full legibility, per this test plan item,
> Must render NFTs (non-vbank assets) as more than a data dump.

**Comment by samsiegart** [comment]
This is completed and deployed in Keplr now
