### ISSUE TITLE
mainnet upgrade-11 chain-software upgrade/deployment

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#7977]
## What is the Problem Being Solved?

Some time in the next month or two, we'll upgrade our mainnet with a new version of the "chain software". This roughly consists of everything under the `golang/` directory, and packages `cosmic-swingset`, `SwingSet`, `swing-store`, `xsnap`. The deployment process involves a stakeholder vote and a chain halt/upgrade/restart cycle (similar to the [`agoric-upgrade-10`](https://explorer.kjnodes.com/agoric/gov/34) process that got `mainnet1B` launched).

This ticket will track the code we intend to deploy in that upgrade, cross-module dependencies, etc. It is meant to fill the gap between "I got my PR landed, so development is done", and "my code has been deployed to our most important instance, the feature/bugfix/etc is now available to users". This should also provide a place to raise version dependencies between multiple deployable units which cannot all be deployed at the same time, e.g. "we must deploy kernel version X before we can start using liveslots version Y", or "contract Z depends upon using liveslots Y".

Note that *any* changes to files within the transitive dependency graph of those packages above will be incorporated into the deployment, whether they were deliberately intended for release or not. And many dependencies are shared by multiple deployable units. For example, a lot of Endo is imported by the kernel, but also by liveslots, and specific vats and contracts, all of which are deployed in separate actions, probably separated by weeks of time.

**Comment by aj-agoric** [comment]
Im closing this as we have completed upgrade 11
