### ISSUE TITLE
Bidding CLI tool doesn't consider gas fees 

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7995]
## Describe the bug
The bidding CLI tool wasn't scoped to include handling mainnet fees. It is therefore not documented and is problematic for bidders as they need to specify fees when submitting bid on mainnet (this was not a problem/requirement on testnets).

A workaround has been documented for bidders here: https://docs.inter.trade/user-how-to/bidding-for-liquidated-collateral however an actual fix is required.

Slack ref: https://agoricopco.slack.com/archives/C038TM0EUKG/p1688134435159649 (Internal)

## To Reproduce

Attempt to submit a bid
Bid fails as bidder has not specified fee option

## Expected behavior
Bidding tool should better handle mainnet fees without having to do any magic/pass too many arguments

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by otoole-brendan** [comment]
1. When submitting a bid, use `--generate-only` to first output it to json e.g. `inter bid by-price --price 9 --give 50IST --generate-only --from [your Agoric address] >spend-action.json`. (Note: it doesn't matter which address you use here, but the tool requires a well-formatted address or a name in your keyring)

2. Then use `agd` to sign and broadcast (including chain ID and fee amount); for example: 
`agd --node=https://main.rpc.agoric.net:443 tx swingset wallet-action --allow-spend "$(cat spend-action.json)" --chain-id=agoric-3 --fees=5000ubld --from [your Agoric address]`

The output should include a tx hash such as `38E782E5A70D0704BC76323A7032B3C7FD4940B4EA4AE4CB64AFC9D203AF82A8` which you can look up in an explorer.

You can also confirm with `inter bid list`:
```
inter bid list --from [your Agoric address]
{"id":"bid-1688145581493","price":"7 IST/ATOM","give":{"Bid":"0.003 IST"},"maxBuy":"1000000 ATOM","result":"Your bid has been accepted"}
```

**Comment by dckc** [comment]
@otoole-brendan I did some testing and then tweaked your comment. How's that?

**Comment by otoole-brendan** [comment]
Thanks @dckc I have updated user documentation to include reference to these workaround changes (not I haven't referres to them as a workaround - we can just update late when fix is ready): https://docs.inter.trade/user-how-to/bidding-for-liquidated-collateral
