### ISSUE TITLE
agoric-sdk unprepared for `assert.bare` from latest endo

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#8005]
https://github.com/endojs/endo/pull/1606 correctly added `bare` to `assert`, correctly updating the types `Assert` types declared in `types.js` and `types.d.ts` to match.

agoric-sdk has its own `@agoric/assert` package which is merely a packaging of `assert` to reexport it as a module export. However, it is missing the `'bare'` property both from the `Assert` type declared in its own `types.js` as well as the list of property names checked in its own `assert.js`. This does not yet cause a problem, because agoric-sdk does not yet depend on an endo incorporating https://github.com/endojs/endo/pull/1606 . But it will be a problem once so upgraded. In the meantime, we cannot easily fix this in anticipation, because adding `'bare'` to these two places will cause conflicts until agoric-sdk is so upgraded.

@gibson042 I'm giving this to you because it is fallout from https://github.com/endojs/endo/pull/1606 . Please reassign as appropriate. Attn also @turadg

**Comment by turadg** [comment]
If it can wait until next week I can take it on. This package should just re-export the type that Endo exported.

**Comment by erights** [comment]
@turadg @gibson042 is this now fixed? Can we close this issue?

**Comment by turadg** [comment]
I think it won't be fully done until agoric-sdk has the latest Endo with `@endo/errors` and https://github.com/Agoric/agoric-sdk/issues/5672 is done to use it.

But I think it's fine to close this as redundant with that scheduled work.
