### ISSUE TITLE
agd sends Ledger diagnostic to stdout mixed with JSON

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#8015]
## Describe the bug

agd writes this diagnostic to stdout:

```
Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
```

When using `agd ... --output json` from other tools, this interferes with parsing the output as JSON.

## To Reproduce
1. add a ledger key using something like `agd keys add --coin-type 118 --ledger lx2`
2. use the devnet faucet to send some tokens to the resulting address
3. send a transaction using `agd tx ... --output json` (details below)
4. Try to parse the output as json. Note error: `Unexpected token D in JSON ...`

<details><summary>agd command args details</summary>

```js
[
  '--node',
  'https://devnet.rpc.agoric.net:443',
  '--chain-id',
  'agoricdev-20',
  '--fees',
  '2000ubld',
  '--from',
  'agoric1c72g3z3xhkntak4jntyhezj738psrrus9cjsp6',
  'tx',
  'swingset',
  'wallet-action',
  '--allow-spend',
  '{"body":"#{\\"method\\":\\"executeOffer\\",\\"offer\\":{\\"id\\":\\"bid-1688600504414\\",\\"invitationSpec\\":{\\"callPipe\\":[[\\"makeBidInvitation\\",[\\"$0.Alleged: BoardRemoteATOM brand\\"]]],\\"instancePath\\":[\\"auctioneer\\"],\\"source\\":\\"agoricContract\\"},\\"offerArgs\\":{\\"maxBuy\\":{\\"brand\\":\\"$0\\",\\"value\\":\\"+1000000000000\\"},\\"offerPrice\\":{\\"denominator\\":{\\"brand\\":\\"$0\\",\\"value\\":\\"+1\\"},\\"numerator\\":{\\"brand\\":\\"$1.Alleged: BoardRemoteIST brand\\",\\"value\\":\\"+7\\"}}},\\"proposal\\":{\\"give\\":{\\"Bid\\":{\\"brand\\":\\"$1\\",\\"value\\":\\"+1100\\"}}}}}","slots":["board02152","board0257"]}',
  '--output',
  'json',
  '--yes'
]
```

</details> 

## Expected behavior

Diagnostics go to stderr. `--output json` is parseable as JSON.

## Platform Environment
 - what OS are you using? what version of Node.js?
Ubuntu 22.04.2 LTS
node v18.14.0

 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
`@agoric/cosmic-swingset@0.41.3-181-gaae3179c8` aae3179c8

## Additional context
found while working on liquidation bidding: https://github.com/Agoric/agoric-sdk/pull/8000#issuecomment-1622741721

**Comment by JimLarson** [comment]
Should also be submitted upstream.

**Comment by mhofman** [comment]
Still present upstream: https://github.com/cosmos/cosmos-sdk/blob/58855c685902c20fcf8bafb3cb26274eedd209dc/client/cmd.go#L305

**Comment by JimLarson** [comment]
Can workaround by explicitly adding `--sign-mode amino-json`.

**Comment by ivanlei** [comment]
Closing based on easy work around. Fixing is not plan of record.
