### ISSUE TITLE
aZcfSeat.getPayouts() promise times out when aZcfSeat has not exited

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/Agoric#8016]
## Describe the bug
When `E(aZcfSeat).getPayouts()` is called before the contract or user has exited the seat, ava throws a promise timeout error with an unhelpful stack trace (` Error: Promise returned by test never resolved at process.emit (node:events:513:28)`). This is remediated by calling `E(aZcfSeat).tryExit()` first, but perhaps the [`getPayout` and `getPayouts` handlers](https://github.com/Agoric/agoric-sdk/blob/c50ca190ec2254d16e6d15d8f1235fcb4aa63560/packages/zoe/src/zoeService/zoeSeat.js#L265-L285) should fail fast and throw a helpful error message to developers and users.

## To Reproduce
I made a simple contract to reproduce the issue: https://github.com/0xpatrickdev/agoric-getpayouts-timeout/. Here is the problematic code that times out: https://github.com/0xpatrickdev/agoric-getpayouts-timeout/blob/main/contract/test/test-contract.js#L131-L135

## Expected behavior
The `getPayouts` and `getPayout` methods should fail with a helpful error message: `Cannot get payouts. Seat has not exited`. 

## Platform Environment
 - what OS are you using? what version of Node.js? macOS 12.x and node v16.18.1
 - is there anything special/unusual about your platform? No
 - what version of the Agoric-SDK are you using? `47e7f4f`, `agoric-upgrade-8-2922-ga45018f29` 

## Additional context

1. Naively, it seems like maybe adding the inverse of [`assertHasNotExited`](https://github.com/Agoric/agoric-sdk/blob/c50ca190ec2254d16e6d15d8f1235fcb4aa63560/packages/zoe/src/zoeService/zoeSeat.js#L48-L51), `assertHasExited`, in the [`getPayout` and `getPayouts` handlers](https://github.com/Agoric/agoric-sdk/blob/c50ca190ec2254d16e6d15d8f1235fcb4aa63560/packages/zoe/src/zoeService/zoeSeat.js#L265-L285) could resolve the issue.

2. I am assuming that a seat needs to be exited before it can claim payouts, but maybe this is not the case. That would change the expected behavior comments.

## Screenshots
<img width="940" alt="image" src="https://github.com/Agoric/agoric-sdk/assets/11021913/7201bef6-c8be-45b8-acbe-017d99d8839f">

**Comment by Chris-Hibbert** [comment]
`E(aZoeSeat).getPayouts()` returns a promise that is guaranteed to resolve once the seat has exited. It is often useful to write `E.when(E(aZcfSeat).getPayouts(), payouts => doSomethingWith(payouts), e => reactToFailure(e));` to handle the payouts once they are available.

As a test framework, Ava expects everything to settle promptly, and helpfully warns you if something didn't finish quickly. In this case, the contract should call `E(aZcfSeat).exit('done')` once the contract's business with that seat has been completed.

We provide `E(aZoeSeat).hasExited()` to query whether the seat has been exited, but in the normal case, it's much better to write a handler using `.then()` or `E.when()` to respond once the contract has finished.

We will add something to the [userSeat documentation](https://docs.agoric.com/reference/zoe-api/user-seat.html#e-userseat-getofferresult) for `getPayouts()` and `getPayout()` explaining the timing of these promises. It's not obvious from those documents that `.getOfferResult()` is intended to resolve quickly, `.getProposal()` and `.hasExited()` should resolve immediately, while `.getPayout()` and `.getPayouts()` like `.numWantsSatisfied()` and `.getFinalAllocation()` don't resolve until the seat exits.

**Comment by 0xpatrickdev** [comment]
Very helpful - thank you!
