### ISSUE TITLE
Vault Collateralization Notifier

### ISSUE THREAD

**Issue by jeetraut** [Agoric/Agoric#8068]
## Description
Write code for an off-chain service with a front-end that allows a user to sign up to receive notifications (email is sufficient) when his/her Inter Protocol vault falls below a given collateralization ratio.

## Context
The Vault system allows users to open up long lived positions in which they mint IST against crypto collateral.  The system protects itself from taking losses on volatile collateral by liquidating vaults that have fallen below a certain collateralization threshold.  

Liquidation is bad for users as it charges them fees and may result in them losing funds relative to their current position.  However, the Vault system currently has no way to proactively notify users when their positions are close to liquidation.  This offchain service would provide an option.

## Acceptance Criteria
Front end requires login with email - user accounts required to manage notifications
User must confirm ownership of email address
Notifications sent over email
Other methods such as SMS or Slack likely also valuable to users
User can create a notification using a Vault ID and a desired collateralization ratio on which a notification gets sent
Alternative to Vault ID is allow user to connect with wallet and select one or multiple of their vaults
A notification remains in force until a user cancels it - may notify the user multiple times if the Vault crosses the threshold
Notifications can be canceled at any time
Notification occurs when Vault collateralization ratio moves from above to below the threshold (i.e., does not notify again until Vault rises above CR and then drops back past it)
A user may have multiple notifications set for different vaults

## Time Estimation
1.5 weeks(60 hours)

## Reward
$4800

Payment will be made in USD (fiat currency) via wire transfer. The developer is responsible for providing their completed tax documents (W9 for US based developers and/or W8 or W8-BEN-E for non-US based developers) and providing their banking details in order to receive payment. 

## Applicant Assessment Criteria
Important: Please provide a clear work plan for how you will approach this bounty.  Use the work plan as an initial demonstration that you would be a good candidate.  Bounties will require coordination with the Agoric team, so unfortunately only plans submitted in English will be considered.

Applicants will be assessed based on the following criteria: 
* Issue-specific domain experience
* Issue-specific technical capability
* Familiarity with Agoric's platform
* JavaScript experience
* Availability and communication

## Experience Write-up (1000-1500 words)
As part of completing the bounty, we ask that you write up a short (or long!) summary of your experience building on Agoric. Write-up should:
Begin with a compelling, relevant introductory hook statement (<50 words). 
Clearly explain the specific bounty project (~100 words). 
Describe how the developer approached the problem (~300 words). 
Give a step-by-step description of the solution (>500 words && <1000 words).
At least three code snippets per write-up. They do not count toward overall word count. 
Conclude with clear calls to action on developing with Agoric - specifically how any ambition developer reading this piece could do more themselves (~100 words). 
This is important feedback for us as we evolve the platform.

## Review Process
* Agoric team reviews your submitted work plan on Gitcoin
* It is best to join our Discord and post your gitcoin name in the bounties channel, so that we can follow up with you. Otherwise, we will write on your gitcoin profile wall and say hello!
* Agoric contacts you to provide reference projects / sample code for engineering review
* Introductory call to discuss your plans and expected timeline
* You join the Agoric Discord bounties channel (if you haven’t done so already) 
* Agoric accepts you on Gitcoin and you get started!

## References
- [Agoric Documentation](https://docs.agoric.com/)
- #bounties channel in Discord
- info.inter.trade dashboard shows vault details. A similar approach could be used to track vault data for this service
- app.inter.trade pulls up a user’s vaults when they have connected with their wallet.  A similar approach could be used if this is implemented with wallet connection

**Comment by dckc** [comment]
See also: [Vault Collateralization Notifier \- Agoric Components Library](https://components.agoric.com/bounties/vault-collateralization-notifier)

**Comment by curlypoint** [comment]
Hey, I know this is a really old is a really old issue, but by any chance the bounty is still available?
thanks

**Comment by dckc** [comment]
I think it's done.

https://github.com/0xpatrickdev/agoric-vault-collateralization-notifier Oct 18 [75f49a9](https://github.com/0xpatrickdev/agoric-vault-collateralization-notifier/commit/75f49a9a029eed23bc5ff80ed771a5eab0d801ee)

cc @0xpatrickdev @jeetraut @kbennett2000
