### ISSUE TITLE
can't send to account by address: namesByAddress is empty

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#8113]
```[tasklist]
### Tasks
- [ ] #8821
- [ ] https://github.com/Agoric/agoric-sdk/issues/8887
- [ ] https://github.com/Agoric/agoric-sdk/pull/8901
```
## Describe the bug

#5822 involves sending assets to accounts by address. As described in #8115, it should work something like...

```js
const destDepositFacet = E(home.namesByAddress).lookup(addr, 'depositFacet');
```

but  `E(namesByAddress).entries()` is empty: it resolves to `[]`.

@anilhelvaci reported seeing `[]` in a REPL. I reproduced it in an ava test.

## To Reproduce
1. `cd agoric-sdk/packages/vats`
2. apply diff below to the `sim/demo config provides home with .myAddressNameAdmin` test to show the entries
3. `yarn test test/bootstrapTests/test-demo-config.js -m '*home*'`
4. see an empty list of entries: `[]`

```diff
diff --git a/packages/vats/test/bootstrapTests/test-demo-config.js b/packages/vats/test/bootstrapTests/test-demo-config.js
index d9a53b5fd..41743b0c5 100644
--- a/packages/vats/test/bootstrapTests/test-demo-config.js
+++ b/packages/vats/test/bootstrapTests/test-demo-config.js
@@ -64,6 +64,8 @@ test('sim/demo config provides home with .myAddressNameAdmin', async t => {
   const home = await makeHomeFor(addr, EV);
   const actual = await EV(home.myAddressNameAdmin).getMyAddress();
   t.is(actual, addr, 'my address');
+  const xxx = await EV(home.namesByAddress).entries();
+  console.log('@@@@', xxx);
   keyArrayEqual(t, keys(home).sort(), homeKeys);
 });
```

## Expected behavior
An entry for each provisioned user.

## Platform Environment
 - _what OS are you using? what version of Node.js?_

```
$ uname -a
Linux bldbox 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ node --version
v18.14.0
```

 - is there anything special/unusual about your platform?

I was working on a branch at the time I reproduced the problem, but it also reproduces on master.

 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
`@agoric/cosmic-swingset@0.41.3-369-ge28392f88` e28392f88

## Additional context

@anilhelvaci reports that this is blocking a [bounty issue](https://github.com/Agoric/agoric-sdk/labels/bounty) that @schnetzlerjoe is working on (most likely #5822)

## Screenshots

```
$ yarn test test/bootstrapTests/test-demo-config.js -m '*home*'
...
@@@@ []
  ✔ sim/demo config provides home with .myAddressNameAdmin (16.2s)
    ℹ bootstrap produced provisioning vat
```

**Comment by dckc** [comment]
## workaround for `vat-provisioning` on local chains

@schnetzlerjoe does 71a2c83ed get your bounty issue work un-stuck?

For ref: I started a branch: [8113-provision-names](https://github.com/Agoric/agoric-sdk/tree/8113-provision-names). currently:

 - 71a2c83ed fix(provisioning): don't use disconnected namesByAddress
 - 2796df226 chore(provisioning): extra NameHub tracing

cc @michaelfig @anilhelvaci

p.s. @schnetzlerjoe says:
> This works like a charm!!!!!

**Comment by dckc** [comment]
## TODO: find consumers of disconnected `namesByAddress`

Somehow this didn't impact sending invitations to EC members and oracle operators. I suppose those functions used `namesByAddressAdmin`.

But anything that consumed `namesByAddress` has got a useless unrelated NameHub.

cc @turadg 

_p.s. done: https://github.com/Agoric/agoric-sdk/pull/8786#issuecomment-1905063611_

**Comment by dckc** [comment]
## impact: cannot send assets to account by address

I'm inclined to change the title to be more about this.

Background:

 - https://github.com/Agoric/agoric-sdk/discussions/8115

**Comment by dckc** [comment]
## work-around idea

In a core-eval proposal, rather than using `{ consume: { agoricNames } }`, use `{ consume: { agoricNamesAdmin } }` and then `const agoricNames = E(agoricNamesAdmin).readOnly()`.

**Comment by dckc** [comment]
The work-around triggered another bug: #8408

There we have [a more complete work-around](https://github.com/Agoric/agoric-sdk/issues/8408#issuecomment-1741445458).

**Comment by 0xpatrickdev** [comment]
> use { consume: { agoricNamesAdmin } } and then const agoricNames = E(agoricNamesAdmin).readOnly().

Is it possible to create a power called `agoricNamesAdminReadOnly`, or `agoricNamesReadOnly` ?


Relatedly, I wonder if we can do something like [this](https://github.com/Agoric/agoric-sdk/issues/8378#issuecomment-1834406095) to better scope permit permissions for writing to agoricNames: 

```json
{
  "consume": {
    "chainStorage": {
      "agoricNamesAdmin": {
        "instance": {
          "MyContract": true,
          "MySecondContract": true
        }
      }
    }
  }
}

```

**Comment by dckc** [comment]
`agoricNamesAdminReadOnly` is called `agoricNames`.

And for installation, instance, brand, and issuer, the stuff is already shaped like this:

```js
{
  consume: {...},
  instance: {
    produce: {
      MyContract: true,
      MySecondContract: true,
    }
  }
}
```

And the contents of these namehubs are automatically reflected to chainStorage.

_p.s. see [makeWellKnownSpaces](https://github.com/Agoric/agoric-sdk/blob/225b7bdd2ea6730fa9856ee8d46dcb5d0b2fcbc5/packages/vats/src/core/utils.js#L230)_
