### ISSUE TITLE
revive zoe-full-upgrade test

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#8121]
## What is the Problem Being Solved?

The zoe-full-upgrade test in deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/zoe-full-upgrade [was bypassed](https://github.com/Agoric/agoric-sdk/issues/8116) because it was failing.

It should be re-instated once the [new coreProposal ugrade handler](https://github.com/Agoric/agoric-sdk/issues/8095) is in place.

## Description of the Design

An earlier version of the test included instructions on rebuilding the bundle and updating the hash. We should leave those instruction in until the test can depend on a git hash to select the version of source code it will be built from.

## Security Considerations

Minor. 

## Scaling Considerations

None

## Test Plan

This is about building a test that will continue to execute the same upgrade as was performed on-chain. It's hard to set that up as a stable test before the chain upgrade takes place.

## Upgrade Considerations

The test is intended to convince us (ahead of time) and server as a regression test (after the fact) that the Zoe/ZCF upgrade will succeed.

**Comment by dckc** [comment]
@iomekam as I mentioned in an [Aug 24 comment](https://github.com/Agoric/agoric-sdk/pull/8237#issuecomment-1692364251), in order for the upgrade core-eval to fit inside a chain upgrade, we need to use [the agoric run / writeCoreProposal approach](https://github.com/Agoric/agoric-sdk/discussions/8087#discussioncomment-6534378).

We were on that path earlier in #7969:

 - [packages/vats/scripts/replace-zoe.js](https://github.com/Agoric/agoric-sdk/pull/7969/files#diff-a587424197c6cee5874333b6a1c93ddc74e0c6354425b771e0fedb0eed4e7885)
 - [packages/vats/src/proposals/zcf-proposal.js](https://github.com/Agoric/agoric-sdk/pull/7969/files#diff-59f5d410f604382979831c5d4b765dd6b2d3f07ac6eeab529f16a9ac805573e3)

I'm about ready to take this on as part of #8291 (#8298). Should we assign this to me? Are you already started? Should we talk?

cc @turadg

**Comment by iomekam** [comment]
Yes, I'm fine with assigning it to you. I'd love to have someone else utilize the new JS work, and I'm happy to pair on it as well if you run into any roadblocks.

**Comment by dckc** [comment]
well, #8291 is on the back burner now. So I'll leave this assigned to you.

But I did get this part more or less working. The relevant commits are:

 - https://github.com/Agoric/agoric-sdk/pull/8298/commits/3f03c847a95d61601cd8d617ede64471e7e993be
 - https://github.com/Agoric/agoric-sdk/pull/8298/commits/61c8459f7a212f32bde81d6318030100f68e1c10

here's hoping we find a little time to talk about them

**Comment by Chris-Hibbert** [comment]
The is [sufficiently tested in A3P](https://github.com/Agoric/agoric-sdk/blob/247cc9bb9c7838242d7b217230adffe634f3224c/a3p-integration/proposals/a%3Aupgrade-next/probeZcfBundleCap.test.js#L13) now.
