### ISSUE TITLE
CI should enforce protobuf generated code is up to date

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#8131]
## What is the Problem Being Solved?

When a PR updates protobuf definitions, it should also refresh the generated files, both in `golang/cosmos` and in `packages/cosmic-proto`. Currently we have some stale generated files when re-running the generation step.

## Description of the Design

A required CI job that regenerates the protobuf files, and checks that the source tree is not dirty.

## Security Considerations

None

## Scaling Considerations

None

## Test Plan

Add job, check that it catches the currently outdated cases. Then fix outdated files in same PR.

It should not be bypassable

## Upgrade Considerations

None

**Comment by turadg** [comment]
https://github.com/Agoric/agoric-sdk/issues/9018 that @JimLarson is working on may be a part of a broader solution.
