### ISSUE TITLE
Review recent security.md edits & add codeowners to ensure future changes are reviewed

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#8171]
## What is the Problem Being Solved?
Ensure security team reviews recent `security.md` edits so they know how to approach with the public.
Ensure future edits are reviewed by security team via `codeowners`

**Comment by raphdev** [comment]
I've reviewed and proposed changes, raising where I think we should discuss.

@ivanlei We'll need to give [write access to @Agoric/sec for the `CODEOWNERS` to work](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax), as well as [turning on branch protection to ensure changes are reviewed](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-and-branch-protection).

Once this is set and PR is merged. We are good to close.
