### ISSUE TITLE
Ensure Inter contracts meet clear performance & scale goals

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8188]
## What is the Problem Being Solved?
A required step prior to Reference-Partner Go Live. From the [MN2 Reference Partner Go-Live Steps](https://docs.google.com/document/d/1UDZPHXK9ZylTHE4CKyPrwej18lK1j2BquuRw96fnuzY/edit?usp=sharing)
- - Need to define Rowland & Warner

## Description of the Design
TBD

## Security Considerations
TBD

## Scaling Considerations
TBD

**Comment by turadg** [comment]
I think this was made in error
