### ISSUE TITLE
Code Review - Kryha core-eval

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8194]
## What is the Problem Being Solved?
Task: Code review the core-eval which will be used to deploy the contract. 
Purpose: This allows verification that the permissions asked for in the core-eval are necessary. This allows verification that the bundles being installed on chain are the bundles that have been reviewed.
Instructions: OpCo engineers to arrange review with partner via Slack.

**Comment by dckc** [comment]
I take it this is for the Kryha core eval.
I'll update the title soon unless I hear otherwise

**Comment by dckc** [comment]
I gather the contract needs timestamps but not timer wake-up. Let's be sure to use `E(timerService).getClock()`.

p.s. done as of...

https://github.com/Kryha/KREAd/blob/beb28dcc338e53dd4bc863061d59a106e5783ba6/agoric/contract/src/proposal/chain-storage-proposal.js#L392-L393

**Comment by dckc** [comment]
review in progress:

## Requested powers

```json
{
  "consume": {
    "chainTimerService": "timer",
    "board": true,
    "chainStorage": true,
    "zoe": true,
    "startUpgradable": true,
    "agoricNamesAdmin": true,
    "agoricNames": true
  },
  "produce": {
    "kreadKit": true
  },
  "instance": {
    "produce": {
      "kread": true
    }
  }
}
```
-- https://github.com/Kryha/KREAd/blob/beb28dcc338e53dd4bc863061d59a106e5783ba6/agoric/contract/src/proposal/powers.json#L1-L19

### Straightforward, legitimately necessary authorities

 - `consume.chainTimerService` - the core-eval code uses `getClock()` to reduce authority given to the contract to only the clock facet. The contract uses the clock to add timestamps to character NFT amount details. _I haven't studied the contract well enough to know why it does that, but it's presumably a legitimate use and in any case fairly low risk._
 - `consume.board`, `consume.chainStorage` are needed for setting up a `published.kread` storage node.
 - `consume.zoe` is used for `E(zoe).installBundleID(contractInfo.bundleID)`. In any case, the contract, like any zoe contract, can get access to `zoe` via `zcf.getZoeService()`.
 - `consume.startUpgradable` is used for the primary purpose of this proposal: to start the contract
 - `instance.produce.kread`: again, used for the/a primary purpose of this proposal: making the contract instance well-known 

### Room for improvement

   - `agoricNamesAdmin` it's clear how and why this is used, and while it used to be necessary, it no longer is: https://github.com/Kryha/KREAd/issues/2
   - `agoricNames` - is used to access the IST issuer. The permit could declare exactly that (`issuer.consume.IST`) to be a bit more clear or the proposal could get the IST issuer using `E(zoe).getFeeIssuer()`, but `agoricNames` is expected to be widely shared anyway.
 - `produce.kreadKit`: redundant given `startUpgradeable`, so not strictly necessary, but not a serious problem

### Critical problems: none.

## Opportunities for SDK improvement

   - the SDK could support declaring the clock in a permit to avoid needing to audit the proposal code
   - the SDK could support declaring a permit for a storage node such as `published.kread`

cc @turadg

**Comment by dckc** [comment]
> ### Room for improvement
> * `agoricNames` - is used to access the IST issuer. The permit could declare exactly that (`issuer.consume.IST`) to be a bit more clear

This turned out to be necessary in some testing contexts, so...

 - https://github.com/Kryha/KREAd/pull/5

p.s.

> `agoricNamesAdmin` ... is no longer necessary

 - https://github.com/Kryha/KREAd/pull/8

**Comment by dckc** [comment]
In https://github.com/Kryha/KREAd/commit/dd02b14759041cf37a5128ba86add50d5276947e , we noted:

```
    // Extremely powerful. Must be attenuated immediately.
    // The APIs will be changed to not require this of the proposal.
    zone: rootZone,
```

I opened https://github.com/Agoric/agoric-sdk/issues/8378 to represent such plans.

**Comment by dckc** [comment]
Adding governance involved considerable re-organization of the core-eval proposal. I'm satisfied that the result poses at most acceptable risks to the platform.

Changes to the data in `base-inventory.js` are also low-risk, provided they don't exceed size limits on inter-vat messages.

for reference:

https://github.com/Kryha/KREAd/tree/develop/agoric/contract/src/proposal currently `3209723`
