### ISSUE TITLE
Kread Code Review of Contract Code

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8195]
## What is the Problem Being Solved?
To support go-live of a Reference Partner's Kread dapp as outlined in the [Partner Go Live Checklist](https://docs.google.com/document/d/1UYq7hzSKBwZcRZnpIAUN5Lm78AOGILVaNPoPJxxLdLo/edit?usp=sharing)
Task: Code review the contract code which will be deployed to chain.
Purpose: Audit to raise confidence that contract implements desired behavior, is upgradable, properly uses durability & virtualization, doesn’t have bugs like infinite loops.
Instructions: OpCo engineers to arrange review with partner via Slack.

**Comment by dckc** [comment]
## minting

_based on `5651c94`_

```mermaid
sequenceDiagram
  actor player
   note right of player: smartWallet

  participant zoe
  participant kread

    player->>kread: makeMintCharacterInvitation()
    kread-->>player: inv1
    player->>zoe: offer(inv1, { want: { name: 'Fred' } })
    zoe-->>kread: handle(seat1, { want: { name: 'Fred' } })
    kread-->>kread: random character attributes
    kread-->>vstorage: updateMetrics('character', ...)
    kread-->>zoe: zcfMint(character)
    zoe-->>player: { payouts: character }

```

### minting and offer-safety

offer safety of character minting looks a lot like #2349 - that is: it would probably need amount patterns (#2230)

**Comment by dckc** [comment]
just opened

 - https://github.com/Kryha/KREAd/pull/11 to address
   - https://github.com/Kryha/KREAd/issues/7

**Comment by dckc** [comment]
fix: get paymentBrand from Money issuer
Rather than a separate term for the paymentBrand, use the brands
provided by Zoe derived from issuers provided to startInstance().
This ensures that the contract is doing business in the same
brand for which Zoe is providing offer safety.
https://github.com/agoric-labs/KREAd/commit/c38ea004c591a303eed4ff1914fe238935a9178e

**Comment by dckc** [comment]
Several of us spent most of the last few days working closely with the Kryha on the contract. I'm satisfied that it poses at most acceptable risks to the chain.

for reference: https://github.com/Kryha/KREAd , currently [875f5de](https://github.com/Kryha/KREAd/commit/875f5de2bf0591d33dd2f2e311ce32cf56623058)
