### ISSUE TITLE
Display NFTs in wallet-app

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8200]
## What is the Problem Being Solved?
As a Kread dapp user on a mobile device who has just minted an NFT, I need to be able to view my NFT asset:

No Agoric Engineering work needed here other than to confirm the below flow is available.

## Description of the Design
P1: As a Kread dapp user on desktop who has just minted an NFT, I need to be able to see my NFT character asset in my Agoric Wallet purse 
Alice navigates to the Kread dapp browser tab and submits an offer proposal to mint character NFT.
Alice is prompted with the offer in Keplr pop-up and approves.
Alice IST balance is deducted and the NFT character is minted to her Agoric1 address.
Alice opens up wallet-app in a separate tab.
Alice can see ‘Kryha Character NFT’ (or similar) as a listed asset in her purse

**Comment by turadg** [comment]
We think is done. @otoole-brendan will confirm.

**Comment by otoole-brendan** [comment]
Awaiting [confirmation](https://agoricopco.slack.com/archives/C04HNJ36RJT/p1693263117343339?thread_ts=1692273818.890579&cid=C04HNJ36RJT)

**Comment by otoole-brendan** [comment]
Confirmed https://agoricopco.slack.com/archives/C04HNJ36RJT/p1693293151265669?thread_ts=1692273818.890579&cid=C04HNJ36RJT
