### ISSUE TITLE
resolve all floating-promise warnings in kernel/platform packages

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#8210]
## What is the Problem Being Solved?

https://github.com/Agoric/agoric-sdk/issues/6000

## Description of the Design

Handle package in the purview of kernel team (out of https://github.com/Agoric/agoric-sdk/issues/6000#issuecomment-1680630006 ) 

```[tasklist]
### kernel/platform packages with warnings
- [ ] SwingSet
- [ ] cosmic-swingset
- [ ] internal
- [ ] solo
- [ ] swingset-liveslots
- [ ] xsnap
- [ ] xsnap-lockdown
- [ ] swing-store
- [ ] swingset-runner
- [ ] swingset-xsnap-supervisor
```

## Upgrade Considerations
Fully compat

**Comment by warner** [comment]
@toliaqat can you take this on? Some are straightforward (either add `await` or add `void`). Some are tricky. I'll attach a list with my best guesses on which ones fall into each category. Running `yarn lint` in each package will reveal the complaints that need addressing.

**Comment by toliaqat** [comment]
@warner yes, I can take it.
