### ISSUE TITLE
Demo of pausing offers in Kread Dapp

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#8228]
## What is the Problem Being Solved?

We want to demonstrate that governance can pause offers in the Kread dapp to take control in emergency situations.

## Description of the Design

Add a governance wrapper around the Kread app (https://github.com/Kryha/KREAd/tree/develop/ ). At this point, it doesn't appear that they need any governed params beyond the electorate.

## Security Considerations

The goal is assurance that the contract is governable.

## Scaling Considerations

Not an issue.

## Test Plan

A test that shows that governance can (selectively) suppress exercise of invitations.

## Upgrade Considerations

use upgradable governance. (#5200)

**Comment by dckc** [comment]
> ... governance can pause offers ...

In particular, governance consisting of one or more addresses chosen by Kryha (based on discussion with @ivanlei who talked with Kryha about this a few weeks back)

Much like oracle operators or EC members, the addresses go into the proposal to be confirmed by BLD stakers.

**Comment by turadg** [comment]
In progress at https://github.com/Kryha/KREAd/pull/3

**Comment by turadg** [comment]
Demoed using steps in https://github.com/Agoric/agoric-sdk/pull/8361/files#diff-e9df3b3edff5b92259fe52e6ab00c94752e56fe975980355341a4acd083a8730
