### ISSUE TITLE
Anachraphobia in upgrade tests

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#8248]
## Describe the bug

in packages/inter-protocol, `test -m test/swingsetTests/**/test-*.js` [provokes anachrophobia](https://github.com/Agoric/agoric-sdk/actions/runs/5958148963/job/16162025108?pr=8157) in #8157 at [this commit](https://github.com/Agoric/agoric-sdk/pull/8157/commits/bb53e6e92ac6ff2b01ba9786839065414e485a94).

For now, I'm going to disable these tests. They're old-style upgrade tests that we will need to recapitulate as docker-styole deployment tests before releasing, so there's nothing we need to preserve about them.

## Expected behavior
User code should never provoke anachrophobia.

## Platform Environment

Seems general. @warner reported:
```
I was able to reproduce locally (N=2). I changed the test to use defaultManagerType: 'xsnap',, and then I got a different error (again, twice): Error#1: resolution of kp124 is still pending.
if I had to guess, maybe this is our old friend "GC under V8 is not deterministic"
...
node-subprocess gets the anachrophobia too (N=2)
...
creationOptions = { nodeOptions: ['--jitless', '--gc-global', '--single-threaded-gc'] }, gets me anachrophobia too (edited) 
```

## Additional context

[Slack discussion](https://agoricopco.slack.com/archives/C039CDU2GHF/p1692133252558299)

**Comment by FUDCo** [comment]
@Chris-Hibbert I suspect the command you gave there got mangled somehow on its way to being entered into the issue, because it's not syntactically valid, and the various obvious tweaks to it that I tried don't lead to anything useful or that runs.
If I just do `yarn test` in `inter-protocol` everything works fine for me, so I think there's more to the story.

**Comment by Chris-Hibbert** [comment]
I tried it again using `yarn test test/swingsetTests/**/test-*.js`, and got three failures, all reporting **anachrophobia**. Sorry about the mistake.  You can also see it in CI [here](https://github.com/Agoric/agoric-sdk/actions/runs/5968107690/job/16191300223?pr=8157).

**Comment by FUDCo** [comment]
OK, I reproduced it.  It's definitely connected to something in your PR, since it doesn't happen with `master` but does with the PR branch.  That gives me a place to start digging...

**Comment by Chris-Hibbert** [comment]
We decided that the anachrophobia issue was a mere side-effect of a more relevant problem in #8157. No action required.
