### ISSUE TITLE
adopt Ava default `files` glob

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8273]
## What is the Problem Being Solved?

Our `package.json` has an `"ava":` section that configures a custom `"files"` glob. There are two problems with this:
1. It requires that every package.json repeat the same custom config. Customizing tool defaults should have a high bar because of the maintenance cost they incur.
2. The naming scheme chosen puts "test" at the front of what is obviously a test from its path context. To run a particular test from the CLI requires typing "test" three time to pick one: `yarn test test/test-something.js`. With Ava's default it would be `yarn test test/something.test.js` and typing the "so" can autocomplete. 

## Description of the Design

Remove all the custom globs.
Rename test files to `.test.js`.

## Security Considerations
none

## Scaling Considerations
none
## Test Plan
Before closing this ticket, check that all open PRs don't have new test files that would be ignored upon merge.
## Upgrade Considerations
none

**Comment by erights** [comment]
This should only be fixed for agoric-sdk (this issue) in coordination with fixing it for endo (https://github.com/endojs/endo/issues/1913)

See https://github.com/Agoric/agoric-sdk/pull/8653#pullrequestreview-1795505142

**Comment by turadg** [comment]
To be closed in June, when
- `files` property removed, so only default is available
- check that all open PRs don't have new test files that would be ignored upon merge.
