### ISSUE TITLE
Create core-eval proposal for launching vat-network & vat-ibc

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#8320]
## What is the Problem Being Solved?
MN-2 developers want to use vat-network & vat-ibc from their contracts. #5696 & #8319 track making these vats durable and upgradeable. This issue tracks the need to create a core-eval proposal to deploy & start vat-network & vat-ibc on mainnet.

## Test Plan
This should be tested in the docker upgrade tests and on emerynet

**Comment by michaelfig** [comment]
https://github.com/Agoric/agoric-sdk/blob/3a319f2197ced19696fa2f4b964b63c7f18326e9/packages/builders/scripts/vats/init-network.js does this job, and is tested in the upgrade-test (using `UPGRADE_INFO_12`).  Closing.
