### ISSUE TITLE
types for permissioned contract deployment not exported

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#8328]
## Describe the bug

[Permissioned Contract Deployment](https://dc-permissioned-deployment.documentation-7tp.pages.dev/guides/coreeval/) is now an SDK-customer-facing API. We expect MN-2 partners to write core-eval proposals. Our examples have `@param {BootstrapPowers} powers` but that type does not seem to be exported.

## Expected behavior

Static types sufficient to guide writing core-eval proposals for permissioned deployment.
In particular, `BootstrapPowers`, which is currently in `@agoric/vats`.

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
e669bb12f (this is a branch; I haven't checked master)

KREAd repo:
2023-09-07 14:45 beb28dc sync repo: develop

## Additional context

 - #8194 

where code review is starting to take the form of PRs

cc @turadg

**Comment by dckc** [comment]
#8335 is some work in this area; in particular: [types-ambient.d.ts](https://github.com/Agoric/agoric-sdk/blob/master/packages/vats/src/core/types-ambient.d.ts)

**Comment by turadg** [comment]
Some other progress https://github.com/Agoric/agoric-sdk/pull/8230/

**Comment by dckc** [comment]
they seem to be exported now.

for example, I'm using them in dapp-agoric-basics without trouble.
https://github.com/Agoric/dapp-agoric-basics/blob/5d800a05eae8b77118ee9a8a27e2943fd91dee5c/contract/src/postal-service.proposal.js#L23
