### ISSUE TITLE
deployment upgrade test of Kread

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8329]
## What is the Problem Being Solved?

We need to test our code against current and future states of Mainnet. https://github.com/Kryha/KREAd/ is destined for Mainnet so we need a test of in the upgrade layers.

## Description of the Design

Add a test like `11wf` for the KRead core proposal

## Upgrade Considerations

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/8228
```

**Comment by dckc** [comment]
Should this target the master branch or the [release-mainnet1B](https://github.com/Agoric/agoric-sdk/tree/release-mainnet1B) branch?

**Comment by dckc** [comment]
#8361 is largely working as of 3ff341c
