### ISSUE TITLE
Relay stATOM tokens to Emerynet to enable testing

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#8363]
As part of the Multiple Collateral and stATOM Support work - we will need to relay stATOM tokens to Emerynet in order to test core user flows as part of the qualification process before promotion to mainnet proposal.

In the absence a testnet relayer provided by Stride to complete this, we will need to complete this work ourselves per defined process below:

1. Stand up local chain
2. Create the test token i.e. stATOM (alternatively they could just relay uBLD which we're guaranteed to have and just pretend it's stATOM - since it's coming from new local chain it won't clash with uBLD already on Emerynet)
3. IBC transfer it to tester on relevant network i.e. Emerynet using local relayer
4. Deprecate local chain and relayer

Limitations:

- Can't send token back (from where it came) unless you keep local chain and relayer running.
- Test tokens are long-lived in event of Emerynet update where same chain state (restart or hard fork). Resetting 2/3 of the validator's state will break the chain resulting in you losing your token balances and IBC channels

**Comment by ivanlei** [comment]
It is satisfactory to use a "fake stATOM" denom.

**Comment by dckc** [comment]
## gov1 on emerynet has a zillion fake stATOM

[gov1 on agoric-emerynet-8](https://emerynet.explorer.agoric.net/agoric/account/agoric1ldmtatp24qlllgxmrsjzcpe20fvlkp448zcuce) shows a huge balance of a new IBC token:

![Screenshot at 2023-10-03 12-56-44](https://github.com/Agoric/agoric-sdk/assets/150986/57f47a50-535f-4d03-9d95-6e8d16de80da)

another way to see it:

```
# agd --node https://emerynet.rpc.agoric.net:443 query bank balances agoric1ldmtatp24qlllgxmrsjzcpe20fvlkp448zcuce
balances:
- amount: "3123456000200"
  denom: ibc/B60D2EF81DE7CCAE53C59B7850667595A7D580200C5636C8922ED78C95532BA7
```

> alternatively they could just relay uBLD which we're guaranteed to have and just pretend it's stATOM - since it's coming from new local chain it won't clash with uBLD already on Emerynet

I went with that approach.

```
# agd --node https://emerynet.rpc.agoric.net:443 query ibc-transfer denom-trace ibc/B60D2EF81DE7CCAE53C59B7850667595A7D580200C5636C8922ED78C95532BA7
denom_trace:
  base_denom: ubld
  path: transfer/channel-3
```
