### ISSUE TITLE
missing a dist-tag for a mainnet-compatible agoric-sdk

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8366]
## Describe the bug

Developers need to be able to `agoric install` a version that matches Mainnet, rather than master.

## To Reproduce

Try installing on of the dist-tags listed at `npm info @agoric/zoe`. It doesn't match Mainnet.

## Expected behavior
One would expect `agoric install agoric-upgrade-11` to work, but it has some problems related to npm package publishing and installation.

**Comment by mhofman** [comment]
There is now an `agoric-upgrade-12` dist tag, and `latest` also points at the same. If there are issues with those packages, let's track in separate issues.
