### ISSUE TITLE
golang/cosmos build failing: filesize exceeds vmsize

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8367]
## Describe the bug
I'm not certain whether this is a bug or PEBCAK but I figure it's worth documeting.

## To Reproduce
1. `cd $AGORIC_SDK/golang/cosmos`
2. `make build:all`

See the build configure step fail,
<details><summary>Details</summary>
<pre>

cp binding.gyp.in binding.gyp
node-gyp configure build  || { status=$?; rm -f binding.gyp; exit $status; }
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@18.18.0 | darwin | arm64
gyp info find Python using Python version 3.11.5 found at "/opt/homebrew/opt/python@3.11/bin/python3.11"
gyp info spawn /opt/homebrew/opt/python@3.11/bin/python3.11
gyp info spawn args [
gyp info spawn args   '/opt/agoric/agoric-sdk/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/agoric/agoric-sdk/golang/cosmos/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/agoric/agoric-sdk/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/turadg/Library/Caches/node-gyp/18.18.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/turadg/Library/Caches/node-gyp/18.18.0',
gyp info spawn args   '-Dnode_gyp_dir=/opt/agoric/agoric-sdk/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/turadg/Library/Caches/node-gyp/18.18.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/agoric/agoric-sdk/golang/cosmos',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/agcosmosdaemon/src/agcosmosdaemon-node.o
  SOLINK_MODULE(target) Release/agcosmosdaemon.node
ld: segment '__DWARF' filesize exceeds vmsize in '/opt/agoric/agoric-sdk/golang/cosmos/build/libagcosmosdaemon.so'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Release/agcosmosdaemon.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/agoric/agoric-sdk/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Darwin 22.6.0
gyp ERR! command "/Users/turadg/.nodenv/versions/18.18.0/bin/node" "/opt/agoric/agoric-sdk/node_modules/.bin/node-gyp" "configure" "build"

</pre>
</details> 

## Expected behavior
Success building.

## Platform Environment
 - Mac OS 13.5.2
 - `node -v v18.18.0`
 - `node-gyp -v v9.4.0`
 - `go version go1.21.1 darwin/arm64`
 - agoric-sdk master (57685b)

**Comment by ivanlei** [comment]
Seems related to https://github.com/golang/go/issues/62577

**Comment by michaelfig** [comment]
Backward-compatible workaround:
```diff
diff --git a/golang/cosmos/Makefile b/golang/cosmos/Makefile
index 02696a028..3b1aee787 100644
--- a/golang/cosmos/Makefile
+++ b/golang/cosmos/Makefile
@@ -32,13 +32,18 @@ ldflags = -X github.com/cosmos/cosmos-sdk/version.Name=$(VersionName) \
                -X "github.com/cosmos/cosmos-sdk/version.BuildTags=$(build_tags_comma_sep)"
 
 gcflags =
+shared_ldflags = $(ldflags)
 
 ifneq ($(GO_DEBUG),)
 ldflags += -compressdwarf=false
 gcflags += -N -l
+else ifeq ($(shell uname -s 2>/dev/null),Darwin)
+# Darwin's latest ld crashes with https://github.com/Agoric/agoric-sdk/issues/8367
+shared_ldflags += -w
 endif
 
 BUILD_FLAGS := -tags "$(build_tags)" -gcflags '$(gcflags)' -ldflags '$(ldflags)'
+SHARED_BUILD_FLAGS := -tags "$(build_tags)" -gcflags '$(gcflags)' -ldflags '$(shared_ldflags)'
 
 all: compile-chain
 
@@ -69,7 +74,8 @@ compile-gyp:
        rm -f binding.gyp
 
 compile-libdaemon: go-mod-cache
-       go build -v $(MOD_READONLY) $(BUILD_FLAGS) -buildmode=c-shared -o build/libagcosmosdaemon.so ./cmd/libdaemon/main.go
+       go build -v $(MOD_READONLY) $(SHARED_BUILD_FLAGS) -buildmode=c-shared \
+               -o build/libagcosmosdaemon.so ./cmd/libdaemon/main.go
 
 go-mod-cache: go.sum
        @echo "--> Download go modules to local cache"
```
