### ISSUE TITLE
facility for testing MN-2 partner contracts in chain upgrade tests

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8376]
## What is the Problem Being Solved?

Our docker-based `upgrade-tests` are our only way in CI to verify that new proposals against (approximate) Mainnet will succeed.

Partner proposals (outside agoric-sdk) change Mainnet too and must be included in the history.

## Description of the Design

Some way for agoric-sdk to fetch manifests and bundles from partner proposals.

And/or a new repo outside of agoric-sdk that tests chain upgrades against a history.

 - [x] #8443

**Comment by dckc** [comment]
@turadg and I plan to land this in a separate repo (#8443)

**Comment by dckc** [comment]
The agoric-3-proposals design seems to suffice; we have 2 CoreEval proposals working:

 - [49:smart-wallet-nft](https://github.com/Agoric/agoric-3-proposals/tree/main/proposals/49%3Asmart-wallet-nft)
 - [55:statom-vaults](https://github.com/Agoric/agoric-3-proposals/tree/main/proposals/55%3Astatom-vaults)
