### ISSUE TITLE
getting-started CI test should actually track Getting Started docs

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#8381]
## What is the Problem Being Solved?

Some time ago, the docs site switched the Getting Started instructions from the fungible faucet dapp to the card store dapp, but our CI job didn't get the same update

## Description of the Design

Replicate the actual docs, using `dapp-card-store`.
Also make sure that `cd ui && yarn build` works (it is currently broken with latest NPM, see #8379 and #8380)

## Test Plan

CI that passes

**Comment by dckc** [comment]
dapp-offer-up replaces dapp-card-store as of...

 - https://github.com/Agoric/documentation/issues/726

**Comment by dckc** [comment]
@turadg noticed that `gettingStartedWorkflowTest` is failing in ci for #8638:

```
  - 'too many retries'
  + 'listening'
```
https://github.com/Agoric/agoric-sdk/actions/runs/7158926782/job/19491612341?pr=8638#step:8:2031
