### ISSUE TITLE
Separate chain upgrade tests from SDK

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8443]
## What is the Problem Being Solved?

The [Dockerized Chain Upgrade Tester](https://github.com/Agoric/agoric-sdk/tree/master/packages/deployment/upgrade-test#dockerized-chain-upgrade-tester) is an essential tool for verifying that a particular proposal will succeed when executed on Mainnet ([agoric-3](https://main.agoric.net/network-config)). The SDK branch [release-mainnet1B](https://github.com/Agoric/agoric-sdk/tree/release-mainnet1B/) has been maintained as the current code on Mainnet.

This poses two problems:
1. Any improvements to the _tooling_ (which aren't part of Mainnet) have to be cherry-picked back to that branch in order to be used for testing. And as master drifts from that branch it becomes less feasible.
2. There are proposals on Mainnet that have nothing to do with the Agoric SDK (e.g. [#53
KREAd-rc1 to Mainnet](https://bigdipper.live/agoric/proposals/53)) but should be captured in the upgrade history this test covers

## Description of the Design

Move the "chain upgrade test" concern out of SDK and into its own repo.

Approach
1. Start a new repo in the Agoric org (`mainnet-proposals` because it's testing proposals (ones to come, stacked on ones that have run)
2. Move the `upgrade-test` directory from agoric-sdk over to it. (perhaps using git magic to maintain commit history)
3. Test https://github.com/Agoric/agoric-sdk/issues/8329 upon it
4. Set up its CI to run the tests on every push (must just maser, since any PR in this repo is specifically about the test)

## Security Considerations
n/a
## Scaling Considerations
n/a

## Upgrade Considerations

Proposals to Mainnet should have PRs on this repo before going to stakers.

**Comment by mhofman** [comment]
> How to integrate with agoric-sdk?
> * One option is that this is a test of _proposals_ so there's no need to integrate with the state of SDK.
> * Of course it would be nice to find out for any change in SDK whether pending proposals will fail if they were to build with the updated SDK.

IMO, agoric-sdk can have a simplified upgrade test that builds on top of a docker image published from this new separate repo. The separate repo build an image that is representative of the latest state of the public chain. The agoric-sdk upgrade test simulates a chain software upgrade starting from that state, by creating a docker test which pulls from the latest base image.

We could separately consider an integration test in the new repo to make sure that updates to the test framework do not brake the integration test that agoric-sdk does. That is what some dapps and the loadgen do for example, they run an approximation of the integration test that agoric-sdk performs, to ensure agoric-sdk CI doesn't break.

**Comment by turadg** [comment]
I'm removing this open question:
> Open questions:
> - How to integrate with agoric-sdk? 
>   - One option is that this is a test of _proposals_ so there's no need to integrate with the state of SDK.
>   - Of course it would be nice to find out for any change in SDK whether pending proposals will fail if they were to build with the updated SDK. 

I think for now we don't need each SDK commit to be tested as a hypothetical proposal to the chain. This new repo tests actual chain proposals. No proposal will go to the chain without having a test here, so the integration testing will happen.

If we find that we are failing to discover quickly enough changes to SDK that would cause upgrade to fail AND they're much harder to fix than if we had found them earlier, then we can invest in earlier and more frequent integration.

**Comment by turadg** [comment]
We now have the new repo for passed proposals. We still need to make agoric-sdk pull that built image and test its current upgradeHandler upon it.

That depends on https://github.com/Agoric/agoric-3-proposals/issues/6
