### ISSUE TITLE
Code Review - Crabble core-eval

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8464]
## What is the Problem Being Solved?
Task: Code review the core-eval which will be used to deploy the contract.
Purpose: This allows verification that the permissions asked for in the core-eval are necessary. This allows verification that the bundles being installed on chain are the bundles that have been reviewed.
Instructions: OpCo engineers to arrange review with partner via Slack.

**Comment by dckc** [comment]
The current [proposal-permit.json](https://github.com/CrabblePitch/crabbleProtocol/blob/4c6581dfaeca5e0b394474c05d5f76dffbb64c77/source_code/contract/src/proposals/proposal-permit.json) includes several very powerful capabilities:

  - `contractKits`
  - `governedContractKits`
  - `instancePrivateArgs`

This includes authority to upgrade any contract, mint IST, etc.

Looking at [core-eval.js](https://github.com/CrabblePitch/crabbleProtocol/blob/4c6581dfaeca5e0b394474c05d5f76dffbb64c77/source_code/contract/src/proposals/core-eval.js), this seems to be motivated by lack of...

 - #8330

**Comment by dckc** [comment]
`namesByAddressAdmin` shouldn't be necessary; `namesByAddress` should suffice, but for...

 - https://github.com/Agoric/agoric-sdk/issues/8113

**Comment by dckc** [comment]
As of [crabble PR 155](https://github.com/CrabblePitch/crabbleProtocol/pull/155)  / `0d0759e`, the code to start the Crabble contract does not get the powerful authorities below.
The approach is to have 1 swingset-core-eval governance proposal with 2 permit/script pairs:

 1. fixes #8330 by building `startMyGovernedUpgradable` out of the powerful capabilities
 2. starts the Crabble contract by using `startMyGovernedUpgradable`

The fix for #8330 included in `0d0759e` is largely based on the #8589 draft. @turadg I presumed that you're satisfied with the result when I approved crabble PR 155; if not, please let us know.

> The current [proposal-permit.json](https://github.com/CrabblePitch/crabbleProtocol/blob/4c6581dfaeca5e0b394474c05d5f76dffbb64c77/source_code/contract/src/proposals/proposal-permit.json) includes several very powerful capabilities:
> 
> * `contractKits`
> * `governedContractKits`
> * `instancePrivateArgs`
> 
> This includes authority to upgrade any contract, mint IST, etc.

**Comment by dckc** [comment]
In discussion with @turadg , we've come up with a different design we prefer for #8330: https://github.com/Agoric/agoric-sdk/pull/8589#pullrequestreview-1775823084

**Comment by dckc** [comment]
Granting authority to start a bespoke contract governor is something I didn't look at closely enough earlier. In discussion of #8330, @turadg noticed that the crabble governor doesn't support replacing the electorate. We've submitted a PR (https://github.com/CrabblePitch/crabbleProtocol/pull/161) to address that.

**Comment by dckc** [comment]
OK, this is done.
PR 161 was merged in [ba318e3](https://github.com/CrabblePitch/crabbleProtocol/commit/ba318e3d6e28373037acc6eec1d70460cfc52bb2)

**Comment by Chris-Hibbert** [comment]
Some of the links above are to a private repo. If you need access, request it through appropriate channels.
