### ISSUE TITLE
Crabble -  Resource Measurement on A Testnet Deployment

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8468]
## What is the Problem Being Solved?

Task: Deploy with core-eval on a testnet and exercise core functionality in a stress like manner. Measure CPU, memory, & storage utilization.

Purpose: Ensure contract will be well behaved before more advanced metering solves come in.

Instructions: OpCo engineers to work with Partner to designate a test network & share a monitoring dashboard showing memory, CPU, storage usage, blocktime, etc. on that network. Partner performs a functional stress test and observes metrics with OpCo.

**Comment by dckc** [comment]
@ivanlei notes that the contract has been deployed on xnet a week or two ago; he has looked at metrics and, for example, everything looked flat for the core eval execution.

**Comment by toliaqat** [comment]
May be crabble deployed the contract on xnet before I deployed mainfork on xnet on Nov. 29th. After that Anil could not provision smart wallet on xnet, and then got busy with fixing issues reported in code reviews. He will try deploying the code review on friday. I am fixing the issues he reported and will redeploy xnet today.

**Comment by dckc** [comment]
@ivanlei asked @toliaqat if all is well and he said yes, we are ready at Dec 15 7:47:06 PM.
