### ISSUE TITLE
linear-history should enforce rules on rebase too

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#8500]
## Describe the bug
#8253 added a `linear-history` check which enforce that no `fixup` or merge commits exists, to address #7768. The check is only enforced on merge PRs, assuming the rebase PRs would get autosquashed by mergify, or somehow always rebased. However if the `fixup` commit doesn't have a base to fixup, mergify will happily proceed forward (I believe that's the default git behavior). Also if the PR is already up to date from a merge commit with the destination branch, the rebase will not be performed.

## To Reproduce
See #8481 and #8559

## Expected behavior
No fixup or nested merge commits in history, regardless of automerge strategy

## Additional context
We either need to get mergify to prevent merging in the rebase cases, or modify the `linear-history` check to run on rebase (likely has to simulate the interactive rebase first).

**Comment by mhofman** [comment]
Apparently mergify only runs on up to date PRs if [`allow_inplace_checks`](https://docs.mergify.com/configuration/file-format/#queue-rules) is false.

Edit: we don't want to use `allow_inplace_checks: false` as it would create a separate PR / merge not linked as well in GH.

Solution is likely to simulate a rebase, maybe only if the PR is up-to-date, before checking if there are any fixup commits left.

**Comment by mhofman** [comment]
Related to this issue, we should also enforce that no merge commits exist on `automerge:rebase`, to prevent situations like https://github.com/Agoric/agoric-sdk/pull/8559

**Comment by frazarshad** [comment]
completed by #9794
