### ISSUE TITLE
fix(vibc): accommodate ibc-go v3 breaking changes

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8501]
## What is the Problem Being Solved?
Opening this issue to to relate to PR [fix(vibc): accommodate ibc-go v3 breaking changes](https://github.com/Agoric/agoric-sdk/pull/8127). More Details to come as needed however this is a rectified issue, used for tracking purposes  #8127

**Comment by gibson042** [comment]
Closed by #8127.
