### ISSUE TITLE
restore independence of atomicRearrange() helper

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8520]
## What is the Problem Being Solved?

[The plan](https://github.com/Agoric/agoric-sdk/issues/6679) was to defer “removing the deprecated helper” and that’s still unchecked. I don’t recall how “add that functionality into ZCF” included “make the helper depend upon it”.

We're hitting problems with the new helper (which depends on new ZCF) being run against the old ZCF (which hasn't been deployed to Mainnet). 

## Description of the Design

Restore the older helper code so it can run without the newer ZCF.

## Security Considerations
Trust that the helper does the same as the ZCF method.

## Scaling Considerations
--
## Test Plan
--
## Upgrade Considerations
Removes a problematic version coupling.

**Comment by Chris-Hibbert** [comment]
As of Upgrade 15, [ZCF has `atomicRearrange()`](https://github.com/Agoric/agoric-sdk/blob/0f12662fd0c22ce168a6939b050d48d3508e8f70/packages/zoe/src/contractFacet/zcfZygote.js#L289). 

Can we close this issue now?
