### ISSUE TITLE
Add deployment test

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8546]

**Comment by aj-agoric** [comment]
As discussed in today's Crabble Demo. Should be done prior to launch.

**Comment by mhofman** [comment]
Nit: can this issue be renamed to capture this is a Crabble related task ?

**Comment by aj-agoric** [comment]
Marked as closed since this will be tracked as part of #8464

**Comment by dckc** [comment]
Is this supposed to be the "Deployment Test" item from [the checklist](https://github.com/Agoric/agoric-sdk/discussions/8280)? If so, please let's put that in the description, along with...

 - https://github.com/Agoric/agoric-sdk/discussions/8173

**Comment by aj-agoric** [comment]
Done

**Comment by dckc** [comment]
> Marked as closed since this will be tracked as part of https://github.com/Agoric/agoric-sdk/issues/8464

I didn't end up doing it as part of #8464 .

I don't see anything relevant in [agoric-3-proposals PRs](https://github.com/Agoric/agoric-3-proposals/pulls?q=is%3Apr+sort%3Aupdated-desc). So to be conservative, I'm reopening this.

**Comment by dckc** [comment]
@anilhelvaci tells us he's updating work on this w.r.t. the impact of #8464
