### ISSUE TITLE
Allow return grant of clawback vesting accounts

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#8570]
## What is the Problem Being Solved?

We would like the recipient of a clawback vesting grant to be able to return all unvested assets to the funder. This is the same action as the funder-initiated clawback, but initiated by the grantee.

We'd also like grantees of Periodic vesting accounts to be able to return them to the funder some day, but at the moment we do not track the funder.

## Description of the Design

- No ability to return a fraction of the unvested amount - it's all returned.
- No ability to specify an alternative address, lest it be sent to a grantee-controlled account. It all goes back to the funder address.
- The self-clawback will be preceded by a withdrawal of all pending staking rewards, and the consequent division into vested and unvested character.

We can leverage the existing clawback mechanism, but because of the slightly different inputs, as well as the future goal of periodic vesting accounts, we'll use a new message type, rather than allowing the recipient to sign the existing clawback message.

## Security Considerations

The grantee must not be able to specify an alternative account as the destination of the funds - the funds must only go back to the funder's address.

## Scaling Considerations

N/A

## Test Plan

Unit testing.

## Upgrade Considerations

N/A

**Comment by JimLarson** [comment]
@dtribble suggests requiring funder address - a useful statement of intention currently, and useful in the future if we allow multiple grants from different sources.

**Comment by dtribble** [comment]
Upon reflection, I think better is that the simple operation is "return everything".  Future versions can have arguments when it's well-motivated to select a subset.

**Comment by JimLarson** [comment]
Reopening until it's incorporated in agoric-sdk.
