### ISSUE TITLE
Casting follower crashes on invalid capdata

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#8579]
## Describe the bug
We noticed the dapps weren't getting wallet updates in https://github.com/Agoric/ui-kit/issues/57. More details in the issue comments, but it turns out when an offer to close a vault fails (e.g. due to insufficient IST in one's purse), the vstorage update in `published.wallet.agoric1[useraddress]` contains an error object that cannot be parsed as valid capdata by `@endo/marshal`. This was causing the follower in casting to crash silently and stop yielding updates for offer statuses. This would also cause the next offer status update to fail, because when you load the dapp, it would hit this error, and the follower would crash.

## To Reproduce
1. Open a vault on app.inter.trade
2. Try to close the vault with insufficient IST in your purse
3. Notice that you never see the offer status update in the toast

## Expected behavior
The status update is able to be unserialized as valid capdata and the casting follower doesn't break

**Comment by ivanlei** [comment]
Fixed by @samsiegart with https://github.com/Agoric/agoric-sdk/pull/8562
