### ISSUE TITLE
Node 18.19 breaks release-mainnet1B branch

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#8599]
## Describe the bug

A [patch](https://github.com/nodejs/node/pull/48703) to make the `Symbol.dispose` and `Symbol.asyncDispose` in Node spec compliant, aka non-configurable got back-ported to the latest Node 18 LTS: [v18.19.0, which was just released Nov 29th](https://nodejs.org/en/blog/release/v18.19.0). Unfortunately this triggers a bug in the SES shim used in the release branch which couldn't remove those new symbols.

Unfortunately the version of SES used in agoric-sdk affects both the kernel and tooling running under node, as well as the lockdown code ran in xsnap. Changing the latter results in a different bundle, which would be used for new vats started on chain.

The least intrusive approach is likely to apply https://github.com/endojs/endo/pull/1579 as a `patch-package` in agoric-sdk since the semver allows newer patch versions of `ses` with the fix to be installed for NPM based installs.

## To Reproduce
Checkout `release-mainnet1B` and run tests using latest Node 18 LTS

**Comment by dckc** [comment]
for folks searching for error messages... one person reported these symptoms:

```
Removing intrinsics.Symbol.dispose
failed to delete intrinsics.Symbol.dispose (TypeError#1)
TypeError#1: Cannot delete property 'dispose' of function Symbol() { [native code] }

(TypeError#1)
```

**Comment by dckc** [comment]
## workarounds

I don't see these symptoms when I use node v18.17.1
@turadg reports that v18.18.0 also avoids these symptoms.
