### ISSUE TITLE
Nodeterministic tests in cosmos-sdk

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#8612]
## Describe the bug

Some agoric-labs/cosmos-sdk tests experience nondeterministic failures.

See comment in agoric-labs/cosmos-sdk#342 (with [proposed patch](https://github.com/agoric-labs/cosmos-sdk/pull/342#issuecomment-1839775572))

The fix should be upstreamed to cosmos/cosmos-sdk

## To Reproduce
CI tests for agoric-labs/cosmos-sdk

## Expected behavior
Tests should be deterministic.

## Platform Environment
All

**Comment by michaelfig** [comment]
Upstream Cosmos SDK has worked around the problem by running all of `coin_test.go`'s test suite serially.  So we don't need to do anything here except rerun CI if it breaks, and expect the flake to go away in a future version.
