### ISSUE TITLE
Refine Simple Exchange to not clone Agoric SDK

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/Agoric#8628]
## What is the Problem Being Solved?
Today [[SimpleExchange sample dapp](https://github.com/alexanderem49/simple-exchange/blob/develop/docs/tutorial.md)] checks out an Agoric SDK branch to deploy and test their SimpleExchange sample dapp.

Dan and co have successfully created a [Game Place Dapp](https://github.com/agoric-labs/dapp-game-places). As shown in the accompanying [draft getting started documentation](https://dc-npm-only.documentation-7tp.pages.dev/guides/getting-started/#getting-support), agoric-sdk packages are installed from NPM (using yarn) rather than by cloning the agoric-sdk repo.

We would like BytePitch to ditch cloning Agoric SDK and instead use the NPM package.

This would create a familiar dev experience from when they test the Game dapp and graduate to SimpleExchange.

## Description of the Design

1. Use the same SimpleExchange but it is deployed and launched on Local Chain in Docker.

## Test Plan

We don't test our NPM packages as much as we would like, so we would love for BytePitch to test creation of smart contracts using these packages and outline what capabilities are hindered as a developer.

**Comment by dckc** [comment]
Two particularly relevant changes to get the game places dapp to work without cloning and `agoric install`:

 - [build(contract): update `@agoric/*` deps to match npm](https://github.com/agoric-labs/dapp-game-places/commit/eca91cc99cbda16111fd363d6c4ae97d0f2e252d)
 - [build(contract): update endo deps to match agoric-sdk](https://github.com/agoric-labs/dapp-game-places/commit/af4fb9df2db1351c7b4f58a8eaf57c030214113b)

I gather @mhofman has a suggestion to refine these slightly.

cc @michaelfig
