### ISSUE TITLE
incompatible with Node 20

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8636]
## Describe the bug

Several packages depend on Bufferfile, which is incompatible with Node 20
- https://github.com/Agoric/agoric-sdk/pull/8365#issuecomment-1841242029
- https://github.com/agoric-labs/BufferFromFile/pull/2

## Platform Environment
 - Node 20 in GH CI

## Additional context

When fixing this, update code points for all mentions of this issue. Also update the package.json engines to include 20. Might be as simple as reverting: [build: defer Node 20 compatibility](https://github.com/Agoric/agoric-sdk/pull/8365/commits/d71ec867a0ee341ca2d81915d6b04a8814d695a1)

**Comment by dckc** [comment]
We can’t use Node 20 and anyone using the Active LTS can’t use Agoric SDK.

 - 11 Dec: @Chris-Hibbert reported complaints from yarn about node versions; @ivanlei noted this issue.
 - 18 Dec: @LuqiPan ran into this when trying to follow agoric-sdk/README.md

The cost to address this is mostly solving the circular buffer in flight-recorder.js which uses BufferFromFile which doesn’t work in Node 20 and seems to be no longer maintained

**Comment by turadg** [comment]
fixed in https://github.com/Agoric/agoric-sdk/pull/8920
