### ISSUE TITLE
emerynet node crashing after upgrade-13, hangover-recovery failing

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#8650]
While testing `agoric-upgrade-13` (`-rc0`) on emerynet, we had one validator crash (apparently due to OOM?), and then when it restarted, the hangover-recovery code failed:

```
portHandler threw (Error#1)
Error#1: fatal: replaying chain send [1,"{\"args\":[\"actionQueue.tail\"],\"method\":\"get\"}"] resulted in "\"1\""; expected null

  at replayChainSends (packages/cosmic-swingset/src/chain-main.js:235:15)
  at doBlockingSend (packages/cosmic-swingset/src/launch-chain.js:845:13)

panic: Error: fatal: replaying chain send [1,"{\"args\":[\"actionQueue.tail\"],\"method\":\"get\"}"] resulted in "\"1\""; expected null
```

This code is run when the cosmos side tells the JS side to execute a block which the JS side remembers having done already. The JS side uses its stored "chain sends" table to re-perform all the JS->Cosmos actions that it did the first time, and expects the Cosmos side to respond in the same ways.

The JS side reads from `actionQueue` to see if there are more actions that need to be taken. When the action queue is fully drained, both `.head` and `.tail` are deleted. So `expected: null` means that the JS side remembers asking for actions and seeing none to be taken.

The "resulted in '1'` suggests that the Cosmos side had added something to the action queue, in this block, which wasn't there the first time around.

There are two separate bugs/concerns here:

* why did the node crash? if it was OOM, why was the memory usage so high?
* why didn't the hangover-recovery code succeed?

**Comment by warner** [comment]
We're still investigating the OOM. One factor might be a state-sync export happening, except the block height (2843573-2843574) was nowhere near a multiple of 1000, which is when most configs would start an export. Another factor might be the IAVL DB having a lot of old blockheights (i.e. not having been successfully pruned recently), and we suspect that IAVL takes more time (and maybe more RAM?) when pruning large DBs (walking through lots of nodes, seeing which are still in use, maybe the refcounts are held in RAM during the prune?). A third factor might be a large contract operation taking place at that time: block -574 had a kread smoketest which exceeded the per-block computron limit (spilling over into -575 if the node had survived long enough to run it).

We're diving further into that one: @toliaqat and @raphdev are restarting the validator node from a week-old disk snapshot, playing it forward to the recent `agoric-upgrade-13` halt-for-upgrade, (taking another disk snapshot for faster iteration), upgrading to 13, then playing forward and hoping to catch the OOM in action. We'll add a host agent to track memory usage (RSS and [PSi](https://docs.kernel.org/accounting/psi.html)) of each process, in the hopes of knowing which process was asking for lots of memory (the OOM killer tends to kill the biggest process, but that's not necessarily the one that was causing the trouble). I'd love to get the kernel's OOM report, but these validators are running inside containers, making that difficult.

On the "why didn't hangover recovery succeed?" front, we have a theory. @mhofman studied that code and concluded that we are not clearing the previous block's `chainSends` early enough. And we were able to sample the swingstore's `host.chainSends` data from the crashed node, and we clearly see a combination of the no-work-done sends from block -573, concatenated with the kread action in block -574. We currently think hangover recovery has always been executing actions from both blocks N-1 and N, but if block N was empty, this didn't matter (the extra `chainSends` are idempotent in that case). And, he believes that it only becomes a problem if we trigger hangover-recovery twice in a row.

#8652 is a new ticket with the hangover recovery bug. I'll also add the timeline we've been able to deduce from this crash (from the slogfiles, the app logs, and the sqlite `host.chainSends` extraction).

**Comment by mhofman** [comment]
Details of the hangover bug: https://github.com/Agoric/agoric-sdk/issues/8652

**Comment by warner** [comment]
Timeline of events:
* monday morning (11-dec-2023, about 9am PT), emerynet halts for upgrade to `agoric-upgrade-13`, and everyone restarts their nodes using software from git tag `agoric-upgrade-13-rc0`
* our emerynet validator named `validator-2` is restarted, running what we'll call "launch-0"
  * something happens to launch-0, I don't yet have information about what
* 2:11:57am PT tuesday morning (12-dec-2023), validator-2 is restarted, beginning what we'll call "launch-1"
  * launch-1 performs its kernel init, then executes blocks 2,843,490 through 2,843,573 without incident
  * (block -573) is empty
  * launch-1 runs for about 7 minutes
* 2:18:50am launch-1 ends partway through executing block -574
  * we believe due to an OOM killing the kernel/node.js/agd process
  * the kernel was in the process of reloading v37-walletFactory at the time
  * the last slog messages were `create-vat`, `clist`, and `heap-snapshot-load`
  * we believe launch-1 terminated without committing either IAVL or swing-store
* 2:19:34am (44 seconds later) launch-2 was started
  * launch-2 takes 33s to perform its kernel-init, then (re-) executes block -574
  * it finishes the swingset work for -574 at 2:20:20am, and commits swing-store
  * it then returns to cosmic-swingset, which would then start the IAVL commit
  * the log ends with `cosmic-swingset-commit-block-start` but no corresponding `-end`
  * the process dies with an OOM
  * we surmise that the IAVL commit had started but did not complete
  * we do not know how atomic the IAVL commit is
* later, launch-3 was attempted
  * this terminates promptly with the `fatal: replaying chain send` error

**Comment by warner** [comment]
Thanks to amazing detective work by @mhofman and @toliaqat , we were able to conclude that the OOMs happened because our emerynet validators are configured (in kubernetes) to use a ramdisk for `/tmp` (`type: tmpfs`), and the state-sync export process writes tens of GB to files in `/tmp/`. This "disk" usage was actually consuming RAM, triggering the OOM killer (but *not* increasing most of the metrics that would have let us track this down faster, like how much RAM the processes were using). The fix is to just remove that volume from the containers, allowing `/tmp/` writes to go to disk.

The root cause is a conflict of assumptions: our k8s config assumed (like many OSes do) that `/tmp` will be small, whereas our state-sync code mainly cares that `/tmp` is short-lived (because there's no good application-side way to delete partial exports). The state-sync code wrote more data to `/tmp` than the k8s config was expecting.

**Comment by mhofman** [comment]
Investigation into crash is complete. Tracking hangover logic bug in #8652
