### ISSUE TITLE
Update @agoric/dapp to point to dapp-game-places

### ISSUE THREAD

**Issue by toliaqat** [Agoric/Agoric#8690]
We want `yarn create @agoric/dapp demo` to create this dapp which currently requires running the following command: 
```
yarn create @agoric/dapp \
  --dapp-base https://github.com/agoric-labs/ \
  --dapp-template dapp-game-places \
  demo
```

 - [x] https://github.com/agoric-labs/dapp-game-places/issues/15
 - [x] https://github.com/Agoric/agoric-sdk/pull/8630

**Comment by dckc** [comment]
The code for this is in agoric-sdk (in packags/agoric-cli). I'm moving this issue...

p.s. can't transfer it to agoric-sdk without transferring this repo to the Agoric org

 - https://github.com/holman/ama/issues/413

I could copy it, but I think I'll leave it alone for now.

**Comment by dckc** [comment]
I started a PR for this, but realized this repo should be moved to the Agoric/ org:

 - https://github.com/agoric-labs/dapp-game-places/issues/15

**Comment by dckc** [comment]
with Agoric/dapp-offer-up#15 done, @kbennett2000 is shortening the command to

```sh
yarn create @agoric/dapp --dapp-template dapp-offer-up demo
```

Getting rid of `--dapp-template` is much more involved. @sufyaankhan has agreed to postpone that.
