### ISSUE TITLE
test that restarting v43-wallet will re-subscribe to v14-bank asset subscriptions

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#8725]
As part of #8499 (look for `v14-bank-v28-provisionpool`, [the second section](https://github.com/Agoric/agoric-sdk/pull/8499#issuecomment-1842457715)), we investigate how v43-wallet will react when it is upgraded, specifically with respect to the promises that it follows from v14-bank. These promises appear in v43-wallet in [`makeAssetRegistry()`](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/smart-wallet/src/walletFactory.js#L80) when it calls `E(poolBank).getAssetSubscription()`. This code uses `observeIteration` (which tolerates the *decider* getting upgraded/restarted), however it doesn't use a `DurablePromiseWatcher`, so our concern is what happens when the *subscriber* (v43-wallet) is upgraded/restarted.

This code is [called](https://github.com/Agoric/agoric-sdk/blob/release-mainnet1B/packages/smart-wallet/src/walletFactory.js#L221) from a `prepare` method, which provides evidence thaht it will be called each time v43-wallet is restarted. If so, we're good. If not, the new version of the vat might not correctly follow new assets created after upgrade.

We've already restarted v43-wallet once, in gov-49 (which activated 21-Sep-2023). I don't know if we've added any assets since then.

The task for this ticket is to test this case, ideally through a3p or some reproducible mechanism, and demonstrate that:
* 1: the new version of v43-wallet calls `getAssetSubscription()`
* 2: the upgraded wallet vat correctly reacts to new assets being announced by v14-bank

**Comment by dckc** [comment]
restarting v43-wallet has happened on mainnet, in proposal 49.
https://github.com/Agoric/agoric-3-proposals/tree/main/proposals/49%3Asmart-wallet-nft

and it evidently _did_ subscribe to new vbank assets, cuz stATOM was added later in proposal 55
https://github.com/Agoric/agoric-3-proposals/tree/main/proposals/55%3Astatom-vaults

So we have an a3p test of this already.

It's reasonably straightforward to see how this happened:
 - restarting the contract invokes the start function (called `prepare` in this case)
 - prepare calls `makeAssetRegistry`
 - `makeAssetRegistry` calls `E(assetPublisher).getAssetSubscription()`

**Comment by dckc** [comment]
@Chris-Hibbert concurs that we've addressed this
