### ISSUE TITLE
agd reported incompatible with Ledger cosmos app

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#8783]
## Describe the bug
[Stakecito reported](https://discord.com/channels/585576150827532298/1004795902868852817/1198616247286366219) being unable to use the latest `agd` (currently at `agoric-upgrade-13`) with a Ledger, and provided a link to a [PR on another cosmos project](https://github.com/bitsongofficial/go-bitsong/pull/227) which also had the issue and solved it by bumping ledger-go related packages.

The issue as reported:
> the latest ag0/agd* binary is not compatible with Ledger anymore. The dependencies have to be upgraded. Could the team please look into that?

> txs do not work anymore with Ledger (e.g. tx authz). We just get an empty error:
> ```
> confirm transaction before signing and broadcasting [y/N]: y
> Error: 
> Usage: 
> ```

## To Reproduce
1. e.g. `agd tx authz` using Ledger

## Expected behavior
`agd` successfully signing tx using Ledger

## Platform Environment
 - `agoric-sdk` at `agoric-upgrade-13` release
 - Cosmos Ledger app at `v2.34.12`

## Additional context
- #8462 is already bumping `zondax/hid` to `v0.9.2`, and scheduled for inclusion in `agoric-upgrade-14`.
- We are currently using `v0.14.1` of `zondax/ledger-go`, and the [bump to `v.0.14.3`](https://github.com/Zondax/ledger-go/compare/v0.14.1...v0.14.3) seems to only be changing an error message and bumping the `zondax/hid` dep to `v0.9.2`.
- We are currently using `v0.12.2` of `cosmos/ledger-cosmos-go` and the [bump to `v0.12.3`](https://github.com/cosmos/ledger-cosmos-go/compare/v0.12.2...v0.12.4) seems to only be lowering the size of a message buffer, and bumping `zondax/hid` to `v0.9.2`
- The [changes to `zondax/hid`](https://github.com/Zondax/hid/compare/v0.9.1..v0.9.2) seem related only to MacOS detection issues

I suspect the actual fix is the message buffer size change in `cosmos/ledger-cosmos-go`. Regardless, updating these deps seems harmless.

**Comment by dckc** [comment]
I've got the ball on reproducing the problem using my spare Ledger (Ledger Nano S).

I updated the cosmos app to v2.34.12, as suggested by @mhofman .

p.s. problem reproduced and fix confirmed: https://github.com/Agoric/agoric-sdk/pull/8798#issuecomment-1906787429

**Comment by JimLarson** [comment]
Confirmed the fix with manual testing on current `master`.

**Comment by JimLarson** [comment]
Confirmed the fix with manual testing of upgrade-14 rc0 on emerynet.

- Hardware: Ledger NanoX V2.0
- Firmware:
    - Secure Element 2.2.3
    - Microcontroller 2.30
    - Bootloader 1.16
- Cosmos App: v2.34.12

```
# set up local config to point at emerynet
agd --home . keys add testledger0 --ledger --coin-type 118
# ledger sees request and approves
tl0=$(agd --home . keys show testledger0 -a)
# provision account via faucet
agd --home . keys add testledger1 --ledger --coin-type 118 --account 1
tl1=$(agd --home . keys show testledger1 -a)
agd --home . tx bank send $tl0 $tl1 1000ubld --from testledger0
# works, verified transfer
```
