### ISSUE TITLE
Connect wallet button component

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8813]
```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/ui-kit/pull/87
```

**Comment by aj-agoric** [comment]
As part of UI [meeting](https://docs.google.com/document/d/1dPJxTzp3WaStJcq3RJAHPMBIDH3DVPyvWBugLgL7nHM/edit?usp=sharing) we discussed exploring offering a connect button with the fully integrated smart wallet provisioning. This was to include checking if user has bld, ist, and loading required leap elements.

**Comment by aj-agoric** [comment]
Should be a solution working with metamask and leap wallet, and keplr.

**Comment by samsiegart** [comment]
As discussed in sprint planning, I just made a separate issue for a provisioning component/react hooks https://github.com/Agoric/ui-kit/issues/78.

This issue will track the wallet connection component which will be separate.

**Comment by otoole-brendan** [comment]
Note this has a dependency on https://github.com/Agoric/ui-kit/pull/87 before it is complete
