### ISSUE TITLE
Investigate TODOs in Network Vat

### ISSUE THREAD

**Issue by iomekam** [Agoric/Agoric#8854]
## Describe the bug
We've been doing a bunch of work to make the network and IBC vats durable. While doing that work, we've run into a few concerning comments that may need to be addressed before the network vat is ready for production

## To Reproduce
https://github.com/Agoric/agoric-sdk/blob/a253f74729e1001bf6e7302bb7da978a9f700a1e/packages/network/src/network.js#L207-L213

https://github.com/Agoric/agoric-sdk/blob/a253f74729e1001bf6e7302bb7da978a9f700a1e/packages/network/src/network.js#L270

https://github.com/Agoric/agoric-sdk/blob/a253f74729e1001bf6e7302bb7da978a9f700a1e/packages/network/src/network.js#L207-L213

https://github.com/Agoric/agoric-sdk/blob/a253f74729e1001bf6e7302bb7da978a9f700a1e/packages/network/src/network.js#L531-L579

## Expected behavior
These TODOs should be investigated to ensure that there isn't missing functionality/work that needs to be done. If we can launch with them in place, they should be replaced with issues tracking each item.

## Platform Environment
all platforms since mainnet1B launch.

**Comment by dckc** [comment]
note also some commented-out code https://github.com/Agoric/agoric-sdk/pull/8721#discussion_r1471927639

**Comment by dckc** [comment]
@michaelfig The impact of these isn't clear to me. I'm going to have to interview you or @warner or somebody...

The loopback protocol ( `prepareLoopbackProtocolHandler` ) is mostly for testing, but it will be part of the network vat in production, right?
The `onCreate` body is marked TODO. We don't seem to be suffering from that.
Do I understand correctly that `onCreate` is an opportunity to do suff, but there is no obligation?

or is loopback used more than that?
