### ISSUE TITLE
Drop Zoe's prohibition on "Wash Sales"

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#8859]
## What is the Problem Being Solved?

Zoe prohibits putting the same amount in both `want` and `give`. (IOU more details) This is mostly to prevent accidents, but violating it might have simplified KREAd's API. 

## Description of the Design

Verify that dropping the prohibition wouldn't break anything, and then remove it.

## Security Considerations

shouldn't be an issue

## Scaling Considerations

KREAd's workaround for this may cause scaling issues. We may have other ways to address the issues.

## Test Plan

It would be more lenient, so the only tests that should break would be any verifying the prohibition is enforced. New tests would be added that Zoe behaves sensibly when the same asset is in both `want` and `give`.

## Upgrade Considerations

This would be a backward compatible (more lenient) change to Zoe's APIs.

**Comment by Chris-Hibbert** [comment]
There is no prohibition on "wash sales". Zoe prohibits the same keyword appearing in both `want` and `give`, but allows a brand to be mentioned under multiple keywords in both `give` and `want`. This is intentional so that a contract can define keywords for `Asset`, `Price` and `Fee`, and then a user could use the same brand for `Price` and `Fee` and the contract wouldn't care.

I've long given the trivial example of a contract for "Hold my beer". Until the user collects the payout, the assets are held in escrow by Zoe. All the contract has to do is transfer the assets from one keyword to another.

We may have used the same pattern for `escrowToVote`, which is no longer a contract. The user submits proof of assets (something non-fungible, with identity), and their vote. The contract records the assets against the identity, and immediately returns the assets.

**Comment by anilhelvaci** [comment]
Is this the current behavior? Are there any code implemented that "drops Zoe's prohibition"? 

cc @Chris-Hibbert

**Comment by Chris-Hibbert** [comment]
> Is this the current behavior? Are there any code implemented that "drops Zoe's prohibition"?

This is the current (and past) behavior. There was never a prohibition, so no code change was required. The original issue was based on misunderstanding. The comment on Feb. 5 documents the situation as it always was.

**Comment by anilhelvaci** [comment]
Thanks! @Chris-Hibbert
