### ISSUE TITLE
mainnet fork upgrade14 test with time measurement

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8875]
## What is the Problem Being Solved?
With concern regarding mainnet performance of a few changes in this release —

release notes say IAVL upgrade took 15min on Osmosis
we do not have data on how rapidly KREAd core-proposal will run.

We aim to produce a run of upgrade14 on a mainfork to get produce accurate time estimates

**Comment by gibson042** [comment]
### ollinet mainfork upgrade with `iavl-disable-fastnode = false`
| Time           | Duration | Concluding Event                                                                   |
|----------------|----------|------------------------------------------------------------------------------------|
| 20:40 (approx) | -        | start new software                                                                 |
| 21:55:39       | 1h15m39s | message:starting node with ABCI Tendermint in-process (no actual logs before that) |
| 21:56:37       | 58s      | Launching SwingSet Kernel                                                          |
| 21:57:34       | 57s      | Launched SwingSet kernel                                                           |
| 21:57:47       | 13s      | block-manager: block 13718557 begin                                                |
| 21:57:48       | 1s       | vat: v1: coreProposal: upgradeWalletFactory                                        |
| 21:58:52       | 1m4s     | kernel: vat v43 upgraded from incarnation 1 to 2                                   |
| 22:01:02       | 2m10s    | vat: v1: Successfully upgraded WalletFactory                                       |
| 22:04:54       | 3m52s    | vat: v1: coreProposal: upgradeZcf                                                  |
| 22:04:57       | 3s       | kernel: vat v9 upgraded from incarnation 0 to 1                                    |
| 22:09:10       | 4m13s    | vat: v1: coreProposal: repairKread                                                 |
| 22:09:52       | 42s      | block 13718557 commit                                                              |

**Comment by mhofman** [comment]
State sync snapshot creation timing on mainfork

| event time | event name |
| - | - |
| 17:23:02 | block 13731000 commit |
| 17:23:02 | snapshot initiate |
| 18:04    | swing-store export complete |
| 18:29:09 | swing-store export retrieve |
| 18:51:53 | swing-store artifacts added to state-sync snapshot |
| 18:52:03 | state-sync snapshot complete |

Snapshot complete at block 13731991

**Comment by mhofman** [comment]
The mainfork snapshot was taken from export of agoric-3 at height 13512995. As of today, agoric-3 is at height 13986253.

**Comment by mhofman** [comment]
We did some testing on a snapshot from about January which informed the expected upgrade time for mainnet and emerynet. While we could do a new test with a more recent snapshot, it's unlikely we'll learn anything more worth the effort.
