### ISSUE TITLE
vat-orchestration expose client (chain) connection info

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8879]
## What is the Problem Being Solved?
As a part of building the vat orchestration for the orchestration api, we need to allow a method to expose the client (chain) connection info

- ⚠️ `@agoric/orchestration`, `vat-orchestration` (done through agoricNames instead)
- ✅ Expose client (chain) connection info 
- ✅ Lookup (connection-0) by chainId
- ❌ Display current capabilities (host_enabled, allow_messages, allow_queries) [no use cases yet require]
- ❌ Alert when status changed (closed, expired)  [no use cases yet require]

**Comment by aj-agoric** [comment]
Considering this is in the current sprint, I am  marking the delivery date as 2/23 @0xpatrickdev lmk if this is a challenge

**Comment by 0xpatrickdev** [comment]
Here are pointers for some of the minimum configuration details required to create a [Chain](https://agoric-sdk.pages.dev/interfaces/_agoric_orchestration.Chain).


```
# /ibc.core.connection.v1.Query/Connections

$ agd query ibc connection connections

{
  "connections": [
    {
      "id": "connection-0",
      "client_id": "07-tendermint-0",
      "versions": [
        {
          "identifier": "1",
          "features": [
            "ORDER_ORDERED",
            "ORDER_UNORDERED"
          ]
        }
      ],
      "state": "STATE_OPEN",
      "counterparty": {
        "client_id": "07-tendermint-1",
        "connection_id": "connection-1",
        "prefix": {
          "key_prefix": "aWJj"
        }
      },
      "delay_period": "0"
    },
  ]
}
```

`IBCConnectionID` for the host and counterparty can be grabbed from here. `IBCClientID` is useful to gather if we want to make the following query:

```
# /ibc.core.client.v1.Query/ClientState
$ agd query ibc client state $CLIENTID

{
  "client_state": {
    "@type": "/ibc.lightclients.tendermint.v1.ClientState",
    "chain_id": "a-chain-id",
    "trust_level": {
      "numerator": "1",
      "denominator": "3"
    },
    "trusting_period": "100s",
    "unbonding_period": "100s",
    "max_clock_drift": "60s",
    "frozen_height": {
      "revision_number": "0",
      "revision_height": "0"
    },
    "latest_height": {
      "revision_number": "1",
      "revision_height": "1000"
    },
  }
}
```
We are able to retrieve a `chainId` from here. `latestHeight` is helpful for building timeout parameters for tx packets and height parameters for queries, but will update frequently.


```
# /ibc.core.channel.v1.Query/ConnectionChannels
$JQ_FILTER='.channels | map(select(.port_id == "transfer" and .state == "STATE_OPEN"))'
$ agd query ibc channel connections $CONNECTION_ID --output json | jq $JQ_FILTER

[
  {
    "state": "STATE_OPEN",
    "ordering": "ORDER_UNORDERED",
    "counterparty": {
      "port_id": "transfer",
      "channel_id": "channel-1"
    },
    "connection_hops": [
      "connection-0"
    ],
    "version": "ics20-1",
    "port_id": "transfer",
    "channel_id": "channel-0"
  }
]
```
The above is able to give us a list of active ics20-1 transfer channels. Useful for building `ibc/MsgTransfer` and denom mapping.

**Comment by 0xpatrickdev** [comment]
Also see Allow Queries and Messages:
https://github.com/Agoric/agoric-sdk/blob/pc/ibc-chain-info/packages/cosmic-proto/test/test-chain-info.js#L213
https://github.com/Agoric/agoric-sdk/blob/pc/ibc-chain-info/packages/cosmic-proto/test/snapshots/test-chain-info.js.md#allow-queries-and-messages

**Comment by dckc** [comment]
@mitdralla note the Xs in the description; these represent either clarification or changes in requirements / design or something.
