### ISSUE TITLE
vat-orchestration - create ICAs - consumer creates a channel (ICA)

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8880]
## What is the Problem Being Solved?
as part of the vat-orchestration we would like the consumer the ability to creates an channel (ICA) on a specific chain.

**Comment by aj-agoric** [comment]
adding to current sprint and delivery date of 2/23

**Comment by anilhelvaci** [comment]
Is there any work happening on this? @aj-agoric

**Comment by aj-agoric** [comment]
closing as this is a duplicate and will not be tracked with 9064
