### ISSUE TITLE
Flake in `liveslots-real-gc` test

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#8883]
## Describe the bug
We've been seeing a few flakes in merge CI in the past couple days, in the `GC syscall.dropImports` test

- https://github.com/Agoric/agoric-sdk/actions/runs/7833178289/job/21373774099#step:25:97
- https://github.com/Agoric/agoric-sdk/actions/runs/7847167484/job/21415682613#step:25:97
- https://github.com/Agoric/agoric-sdk/actions/runs/7851270943/job/21428167209#step:25:97
- https://github.com/Agoric/agoric-sdk/actions/runs/7874448868/job/21484248980#step:25:97
- https://github.com/Agoric/agoric-sdk/actions/runs/7879633554/job/21500379870?pr=8899#step:25:97
- https://github.com/Agoric/agoric-sdk/actions/runs/7887719793/job/21523780369?pr=8801
- https://github.com/Agoric/agoric-sdk/actions/runs/7889720450/job/21530406924?pr=8889
- https://github.com/Agoric/agoric-sdk/actions/runs/7889720450/job/21532172214?pr=8889
- 
## To Reproduce
CI? Not sure if the flake triggers locally

## Expected behavior
No error

## Platform Environment
CI / master

## Screenshots
```
not ok 59 - liveslots-real-gc › GC syscall.dropImports %ava-dur=36ms
  ---
    name: AssertionError
    assertion: falsy
    operator: '!'
    values:
      'Value is not falsy:': 'Object @Alleged: undefined {}'
    at: 'packages/swingset-liveslots/test/test-liveslots-real-gc.js:136:5'
```

**Comment by mhofman** [comment]
Unfortunately #8910 didn't fix the issue.
New failure after it landed: https://github.com/Agoric/agoric-sdk/actions/runs/7896729757/job/21551266273#step:25:103

**Comment by turadg** [comment]
Failure two hours after #8913,
- https://github.com/Agoric/agoric-sdk/actions/runs/7903646739/job/21572176454?pr=8889

**Comment by mhofman** [comment]
Ok, I'm running out of ideas. @warner are you aware to any changes to liveslots or dependencies that happened circa Feb 8 / 9?

I also fail to understand why this specific test fails but not the other very similar ones.
