### ISSUE TITLE
Core-eval not found after submit on new cosmos-sdk

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#8887]
## Describe the bug
After submitting a core-eval proposal, the pending proposal is not found with `agd query gov proposals`. 

## To Reproduce
Run the integration tests of [mhofman/provisioning-upgrade](https://github.com/Agoric/agoric-sdk/compare/mhofman/provisioning-upgrade)

## Expected behavior
Success of the test with the proposal being found in a query, a deposit successfully submitted, and the vote passed.

## Additional context
Test error: https://github.com/Agoric/agoric-sdk/actions/runs/7837253947/job/21386560224#step:7:255

```
agd tx -bblock gov deposit 50000000ubld --from agoric1fduvw78gft96syan9fkdxhyzpg2hrv2yu2zjcc "--chain-id=agoriclocal" --yes --keyring-backend test -o json
Error: accepts 2 arg(s), received 1
    Usage:
      agd tx gov deposit [proposal-id] [deposit] [flags]
```

This is because the `lastProposalId` in [`voteLatestProposalAndWait`](https://github.com/Agoric/agoric-3-proposals/blob/8524c77695191078fcb5d53c16200076749836f5/packages/synthetic-chain/src/lib/commonUpgradeHelpers.js#L150-L153) is undefined since the proposal wasn't found.

The proposal was submitted successfully:

```
{
  txhash: '678735B35C2FD47671CE2030368B48474BB2D593B7A92F17A517711B370D64E3',
  code: 0,
  height: '1298',
  gas_used: '318196'
}
```

**Comment by JimLarson** [comment]
Attempted to validate on emerynet. See notes at https://github.com/Agoric/agoric-sdk/issues/8871#issuecomment-1974971931

I can definitely see the submitted proposal, but I think the issue is that the JS query and processing could not see it.
