### ISSUE TITLE
Job test-dapp in workflow Test Dapp Card Store of Agoric/agoric-sdk status failure

### ISSUE THREAD

**Issue by kriskowal** [Agoric/Agoric#8897]
## To Reproduce

Our recurring “test-dapp” workflow is failing with an error attempting to merge `integration-endo-*` branches, attempting to write `endo-sha.txt`.

I’m not sure how to reproduce this failure apart from somehow causing the workflow to run directly from Github actions, but I assume this will work:

1. Clone agoric/dapp-card-store
2. Create a branch off main
3. Add a trivial commit `git commit --allow-empty -m 'Poke CI'`
4. Create a draft PR and observe CI
5. Observe error like: https://github.com/Agoric/agoric-sdk/actions/runs/7868048310

```
error: Your local changes to the following files would be overwritten by merge:
  endo-sha.txt
Merge with strategy ort failed.
Error: Process completed with exit code 2.
```

## Expected behavior

CI should pass.

## Platform Environment
 - Ubuntu 22.04.3 LTS
 - 
 - 
 -

**Comment by kriskowal** [comment]
This may be in @mhofman or @michaelfig’s wheelhouse. It looks like conflicts among endo integration branches, but I do not see any current `endo-integration-*` branches.

**Comment by mhofman** [comment]
Fixed by https://github.com/Agoric/agoric-sdk/pull/8892 this morning

**Comment by kriskowal** [comment]
Much obliged!
