### ISSUE TITLE
`update-check` in Manage Integration Check workflow sometime fails

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#8937]
## Describe the bug
The job sometimes fail, not sure why? I'm positing a sort of race where a previous `create-check` didn't complete yet.

Arguably the `update-check` should create if it doesn't exist, or retry?

The consequence is pretty bad: the `integration-test-result` check never completes, and the PR gets stuck.

## To Reproduce
- https://github.com/Agoric/agoric-sdk/actions/runs/7935219456

## Expected behavior
Completion result of integration test workflow always fully reflected in check result.

## Platform Environment
CI

## Context

https://github.com/Agoric/agoric-sdk/pull/8731

## Screenshots
> [update-check](https://github.com/Agoric/agoric-sdk/actions/runs/7935219456/job/21667863906#step:2:38)
> No integration-test-result check found for commit 19ee1166a6ae36f6115d7b807cc0498a9ad6992a https://github.com/Agoric/agoric-sdk/actions/runs/7935214947

**Comment by 0xpatrickdev** [comment]
https://github.com/Agoric/agoric-sdk/actions/runs/8621724430

Is this failed run something to be concerned with?

**Comment by mhofman** [comment]
yeah it's the race i've seen before. usually re-running will fix

**Comment by toliaqat** [comment]
@mhofman do you think it is done in [#9787](https://github.com/Agoric/agoric-sdk/pull/9787) then we can close it?
