### ISSUE TITLE
sha1sum command absent on MacOS

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#8983]
## Describe the bug
The `bin/agd` script invokes the `sha1sum` command, which is absent on MacOS.

I think the impact is that the binary will not be automatically rebuild.

## To Reproduce
Run `bin/agd` with any subcommand except `build`.

## Expected behavior
The command should run on as many important environments as we can support.

For MacOS, we should either require installation of `sha1sum` or use `shasum` if `sha1sum` is missing.

## Platform Environment
MacOS 14.2.1

**Comment by JimLarson** [comment]
See #8715 where we started using hashes instead of timestamps.

**Comment by erights** [comment]
What's the difference between `shasum` and `sha1sum`?

**Comment by warner** [comment]
Nothing major, just coming from different toolchains. `shasum` is a perl script. `sha1sum` (and equivalents for SHA256, SHA512, md5, blake-2, etc) are written in C, part of GNU Coreutils, and distributed under GPL3 (which is probably why they aren't on macOS). Different CLI flags, unfortunately.
