### ISSUE TITLE
refactor smartWallet error handling on executeOffer

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#8997]
## What is the Problem Being Solved?

In #8488, SmartWallet was refactored to use promiseWatcher to ensure that promises survived various kinds of upgrade trauma.

That refactoring left some error handling in a catch clause in `executeOffer`, missing the fact that that error handling would be lost when the walletFactory itself is upgraded. 

## Description of the Design

Move the [contents of the catch clause](https://github.com/Agoric/agoric-sdk/blob/695c440c0f48a3591b15a43665682c5f1ebbad9d/packages/smart-wallet/src/smartWallet.js#L992) in `executOffer` to appropriate sections of [`offerWatcher.js`](https://github.com/Agoric/agoric-sdk/blob/master/packages/smart-wallet/src/offerWatcher.js). 

## Security Considerations

Ensure that wallets correctly report on exceptions.

## Scaling Considerations

Not much relevance.

## Test Plan

It may be difficult to provoke the error conditions (multiple upgrades, and exceptions at carefully calibrated times would be required).  We aren't going to try to write tests for these corner cases, and will instead review carefully.

## Upgrade Considerations

This is about error behavior in upgrade situations. With the refactor, we expect the error handling to be invoked correctly even if there are vat upgrades.

**Comment by dckc** [comment]
"refactor"? this is a bug, no?

**Comment by turadg** [comment]
> "refactor"? this is a bug, no?

fwiw, the commit message was `fix`: 5397e0cf76f29074e77227f61576e784e5016d08
