### ISSUE TITLE
Better UX for mismatched chain and client versions

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#9020]
## What is the Problem Being Solved?

Cosmos-sdk sometimes breaks compatibility between client software and chains - old client software might not work when accessing a newer chain. Newer client software might remove functionality necessary for using old chains. The error messages are not necessarily helpful.

At a minimum, the error messages should be improved with a clear message to change one's client software.

Ideally, more backward- and forward- compatibility should be added.

This is work best done in conjunction with the Cosmos community so the changes can go into Cosmos releases.

**Comment by ivanlei** [comment]
Moving to lowest priority and unassigning. The problem described is not an issue that we're facing.
