### ISSUE TITLE
Go workspace configurations for development

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#9023]
## What is the Problem Being Solved?

Cosmos-sdk has an increasing number of separate Go modules within the same Github repository. We're starting to add multiple Go modules in agoric-sdk as well. This complicates development in several ways:

- VSCode is confused by nested Go modules and asks that each get explicitly opened explicitly as a new folder in the workspace.
    - Even after doing this, you have to be careful to navigate to files in the right way, preferring the workspace folder rather than the subdirectory.
- Testing changes to a depended-upon module requires editing all the transitive `go.mod` files that use it directly or indirectly.
- Changes spanning multiple Go modules become vastly more complicated. There's a temporary workaround using `replace` directives to find a dependency nested in your own source tree, but this is marked as temporary.

The situation gets a little better when using [Go Workspaces](https://go.dev/blog/get-familiar-with-workspaces), which act as-if you had manually done a lot of editing `go.mod` files to issue replace directives to use local paths. VSCode is able to interpret these files.

We'll need to support several different configurations:

- Developing local cosmos-sdk using the sources in the repo. The 0.47 and later releases come with a `go.work.example` file which handles this.
- Developing cosmos-sdk against a locally-modified cometbft.
- Developing local agoric-sdk using the sources in the repo.
- Developing agoric-sdk against a locally-modified cosmos-sdk (with modifications potentially in any embedded Go module).
- As above, but also with a locally-modified cometbft.

**Comment by ivanlei** [comment]
Reduced to lowest priority and unassigning. This issue has no impact on the product and minimal impact on the product developer.
