### ISSUE TITLE
Silence lint warnings in cosmos-sdk

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#9034]
## What is the Problem Being Solved?

Voluminous lint errors in `agoric-labs/cosmos-sdk` prevent us from seeing new real errors in our fork's code.

## Description of the Design

Our current cosmos-sdk base - `v0.46.16` - shows thousands of errors in a `golangci-lint` run, so we'll need to wait for these to be fixed in upstream releases. However, we can eliminate errors in our fork code.

To avoid unnecessary merge conflicts, we'll fix errors in modified files only when the surrounding code fixes the error, e.g. dealing with moved `Int` or `Wrapf()`.

## Security Considerations

Fewer lint messages will make vulnerabilities more visible.

## Scaling Considerations

N/A

## Test Plan

N/A

## Upgrade Considerations

To avoid unnecessary merge conflicts, we'll fix errors in modified files only when the surrounding code fixes the error, e.g. dealing with moved `Int` or `Wrapf()`.

**Comment by ivanlei** [comment]
This issue is written with a plan to wait for upstream to complete the work. This isn't actionable.
