### ISSUE TITLE
Allow RC1 to installs atop RC0

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#9047]
## What is the Problem Being Solved?
To allow us to dynamically deal with issues when discovered in Emerynet or other test nets. We need to allow multiple proposal handles allowing RC1 to installs atop RC0 

## Security Considerations
None to my knowledge as this will take existing install params

**Comment by aj-agoric** [comment]
Fixed with #9041

**Comment by gibson042** [comment]
#9041 was applied directly to branch dev-upgrade-14, but we should probably update master accordingly.

**Comment by mhofman** [comment]
#9101 is likely a better approach long term. We should decide whether to port the logic from #9041 to master before that is implemented

**Comment by gibson042** [comment]
This was fixed for upgrade-14 by #9041, and is being tracked for later releases by #9106.
