### ISSUE TITLE
`agd tx submit-proposal` upgrade-info must pass new CLI validation code

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#9048]
## What is the Problem Being Solved?
OpCo need to support the new validation done in the CLI of software-upgrade gov proposals.

While an [issue exists upstream with the parsing of the `upgrade-info`](https://github.com/cosmos/cosmos-sdk/issues/19686), it doesn't trigger for upgrade info values that contain valid binaries urls.

However the new cosmos CLI validation verifies the URLs point to valid artifacts.

## Description of the Design

Change the upgrade-info generation instructions (and script) to
- modify `upgrade-info.binaries.any` to include a `//agoric-sdk-$COMMIT_ID` suffix between the `.zip` and the `?checksum`. This is a [trick for `go-getter`](https://github.com/hashicorp/go-getter?tab=readme-ov-file#subdirectories) to unpack the top level folder of the GitHub archive.
- add a `upgrade-info.source` to be the previous value of the `upgrade-info.binaries.any` (without the suffix above), to support 3rd party downloaders which do not understand the go-getter trick.

## Security Considerations

None

## Scaling Considerations

None

## Test Plan

- a3p adhoc test: https://github.com/Agoric/agoric-3-proposals/pull/120 (does not need to be merged)

## Upgrade Considerations

ability to upgrade to new software

**Comment by gibson042** [comment]
PR: https://github.com/agoric-labs/cosmos-sdk/pull/405

**Comment by mhofman** [comment]
The forum posts were updated to reflect the above, and for the upgrade-14 branch, we did change the gen script as well (https://github.com/Agoric/agoric-sdk/pull/9041/commits/f091b6d179bc3eddabac3c5b548686458f0e8266). A similar change for the `master` branch should be implemented, maybe while doing #8784

**Comment by gibson042** [comment]
This was fixed for upgrade-14 by https://github.com/Agoric/agoric-sdk/commit/32bff4b84a382dd4897870a04063bcad5e489a33#diff-212b769d9a514d2e7813277e574999c609023d1d27de8d7b11244b879a81db3e as part of #9041, and is being tracked for later releases by #9105.
