### ISSUE TITLE
orchestration - chain - provide well-known chain

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#9063]
## What is the Problem Being Solved?
Allow an object derived from a `ZcfSeat` to return a `Chain` object based on a `chainName` which exposes common chain actions, including:
- Creating or retrieving an ocap to control an ICA account hosted on that chain
- Making an ICQ query to that chain
- Any custom chain actions

For chains _well-known_ to the API, the user should not have to specify IBC connection info.
```[tasklist]
### Well Known Chains
- [x] orchestration - create chain - Osmosis
- [x] Umee (UX Chain)
- [x] DYDX
- [x] Stride
- [x] Secret
- [x] Neutron
- [x] Noble
- [x] Celestia
- [x] Cosmos Hub
- [x] Omniflix
- [x] Stargaze
```

Additionally, allow for chains unknown to the API additional details like IBC connection info may be needed.

```[tasklist]
### Dependencies
- [ ] https://github.com/Agoric/agoric-sdk/issues/9187
```

**Comment by dckc** [comment]
> derived from a `ZcfSeat`

what does that mean?
