### ISSUE TITLE
orchestration - ICA Controller - Account - Create account on host chain

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#9064]
## What is the Problem Being Solved?
A `Chain` object should be able to create an ICA account on a host chain. The caller of this API should receive exclusive rights to an ocap representing the authority to control the ICA account. 

This API should support lazy creation - a `provide` pattern associating a name with the ICA and associating the ICA with the seat/user so the contract can easily say, "Which agoric1/user does this ICA belong to?" and "Which ICA have I created for this agoric1/user?"

**Comment by aj-agoric** [comment]
closed as this is a duplicate of [ICA - create channel 8880](https://github.com/Agoric/agoric-sdk/issues/8880)

**Comment by aj-agoric** [comment]
Actually the other was closed.. re-opening this one.
