### ISSUE TITLE
orchestration - ICA Controller - Account - Send ICA command

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#9065]
_p.s. dup of #8881_

## What is the Problem Being Solved?
An ICA Account object should allow the sending of ICA commands formatted as Protobuff or JSON.

This API is a base API that further abstractions for sending specific ICA commands will make use of.

**Comment by aj-agoric** [comment]
closing as this is a dup of #8881

**Comment by dckc** [comment]
changing completed -> not planned

**Comment by aj-agoric** [comment]
removing from gh projects as not planned.
