### ISSUE TITLE
orchestration - ICA Controller - Distribution - Withdraw Delegator Reward API

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#9071]
## What is the Problem Being Solved?
~~#9065~~ #8881 describes a generic method for sending ICA commands.

The `WithdrawDelegatorReward` API should build on that, allowing `cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward` messages to be sent without the caller needing to build a representation of the message objects.

**Comment by dckc** [comment]
> The `WithdrawDelegatorReward` API should ...

Should I take the name `WithdrawDelegatorReward` literally? Normally, we use camelCase, following [airbnb style](https://airbnb.io/javascript/#naming-conventions).

Also: is it supposed to be a function? or a method on an object?
[BaseOrchestrationAccount.withdrawReward](https://github.com/Agoric/agoric-sdk/blob/fbd8633ae9f8420a589dd9bc32925418f2dde060/packages/orchestration/src/types.d.ts#L383C3-L383C17) looks likely, but I don't see any implementations of `BaseOrchestrationAccount` yet.

We don't yet have [Orchestrator.getChain](https://github.com/Agoric/agoric-sdk/blob/master/packages/orchestration/src/types.d.ts#L107) nor `Chain.makeAccount` (nee createAccount).
Do we have issues to make those? The closest I can find is
 - #9187

I suppose `stakingAccountKit.js` has some relevant stuff:

```
        // TODO move this beneath the Orchestration abstraction,
        // to the OrchestrationAccount provided by createAccount()
```
https://github.com/Agoric/agoric-sdk/blob/fbd8633ae9f8420a589dd9bc32925418f2dde060/packages/orchestration/src/exos/stakingAccountKit.js#L96C1-L97C67

at @0xpatrickdev 's suggestion, I added a method there in #9307

**Comment by dckc** [comment]
The [spec for withdrawRewards](https://github.com/Agoric/agoric-sdk/blob/a2c6d29539d15c981e82f689834f95bba5943d1a/packages/orchestration/src/types.d.ts#L372-L376) says
> The promise settles when the rewards are withdrawn.
> @returns The total amounts of rewards withdrawn

How do I/we get a signal when the rewards are withdrawn?

_p.s. I'll assume a reply from `executeEncodedTx` means it's done._
