### ISSUE TITLE
orchestration - chain - ICQ Balance Query

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#9072]
## What is the Problem Being Solved?

[the chain object from #9063](https://github.com/Agoric/agoric-sdk/issues/9063) should expose an API for making ICQ balance queries.

Additionally, the `OrchestrationService` object should allow for chains unknown to the API to make ICQ balance queries.

**Comment by 0xpatrickdev** [comment]
I updated the description to include (slightly paraphrased) language from #9063 :
> Additionally, allow for chains unknown to the API additional details like IBC connection info may be needed.

This is in light of #9198, which adds `async createQueryConnection(controllerConnectionId : IBCConnectionID) => QueryConnectionKit['connection']`  to `OrchestrationService`. The planned behavior is for `Chain` objects to create and store and one of these objects and share it among users, but the facet is also available to any consumers of OrchestrationService.

If the idea is to do a provide pattern, where we only deal in `Chain` objects and OrchestrationService consumers are not permitted to request their own icqcontroller port / connection (_only networkVat / portAllocator consumers_), we can move the `createQueryConnection` and `createAccount` methods to a separate facet.  We should also document the intended behavior more explicitly in #9063.

**Comment by dckc** [comment]
I see a couple design questions in the PR:

 - https://github.com/Agoric/agoric-sdk/pull/9198#discussion_r1589366300
 - https://github.com/Agoric/agoric-sdk/pull/9198#discussion_r1589369951

What ICQ spec are we going by?
