### ISSUE TITLE
flake in gc-kernel device-transfer call to retireImports

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9089]
## What is the Problem Being Solved?

Similar to https://github.com/Agoric/agoric-sdk/issues/8883 but distinct,
```
not ok 4 - gc-kernel › device transfer %ava-dur=24931ms
  ---
    name: AssertionError
    assertion: is
    values:
      'Difference (- actual, + expected):': |-
        - '2,2'
        + '1,1'
    at: 'packages/SwingSet/test/test-gc-kernel.js:1[22](https://github.com/Agoric/agoric-sdk/actions/runs/8272299821/job/22633964312?pr=9086#step:6:23)6:5'
  ...
ok 5 - gc-kernel › sortVrefs %ava-dur=4ms
error during syscall translation: (Error#1)
Error#1: syscall.retireImports but o-50 is still reachable
  at packages/SwingSet/src/kernel/vatTranslator.js:437:15
```

**Comment by warner** [comment]
This might be another instance of #3240 or #5575, although I have no idea why it might be showing up now. I'll make a PR that changes that test to use XS instead of Node, that's our usual fix.

**Comment by warner** [comment]
Note the `error during syscall translation: (Error#1)` / 
`Error#1: syscall.retireImports but o-50 is still reachable` is normal, one of the other tests in that file is deliberately provoking an error handler.

It's the `2,2` vs `1,1` that is the symptom of this GC problem.

**Comment by turadg** [comment]
Got this again in https://github.com/Agoric/agoric-sdk/actions/runs/8457659593/job/23170228389?pr=8850
