### ISSUE TITLE
Launch Upgrade14-RC1 to Emerynet

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#9098]

**Comment by aj-agoric** [comment]
This is a placeholder to mark the work effort needed to get propose upg14 to emerynet, and vote it through is not solely opco work we can remove this.

**Comment by dckc** [comment]
[done](https://community.agoric.com/t/proposal-71-agoric-upgrade-14-interchain-stack-smart-wallet-upgrades/633/8?u=dckc)
