### ISSUE TITLE
Implement `agd snapshots export`

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#9100]
## What is the Problem Being Solved?

#7225 and later #8072 implemented state-sync support including SwingSet state by introducing a manual commit sync point in the Cosmos SDK (https://github.com/agoric-labs/cosmos-sdk/pull/297). That approach bypassed the `snapshot` call originally made by the SDK during commit, and instead initiated the swingset side of the snapshot before proceeding to the cosmos side because we couldn't guarantee the timing of the cosmos side and because the snapshot of the swingset side must be initiated before the state has further changed (no support for arbitrary height snapshot).

Cosmos 0.46 introduces a `snapshots` CLI command which allows amongst other things, to generate and restore from state-sync snapshots present in the snapshot DB. Unfortunately generating a snapshot (`snapshots export`) does not work because it doesn't initiate the swingset export as expected.

## Description of the Design

Either patch the CLI to initiate the swingset export akin to the patch made to the commit time snapshots, or refactor (and upstream) a mechanism for snapshot extensions to hook into the snapshot creation flow, allowing them to initiate work in a blocking way.

## Security Considerations

Potential for snapshot extensions to block forward progress if it has erroneous logic

## Scaling Considerations

Extension snapshot initiation while blocking should return promptly

## Test Plan

Test using `agd snapshots` commands.

Integration tests of state-sync (possibly part of #8794)

## Upgrade Considerations

None specific to this issue.

**Comment by aj-agoric** [comment]
removing from upgrade 16 per discussion in mn sustainability meeting.
