### ISSUE TITLE
Agoric documentation CI builds fail on xsnap

### ISSUE THREAD

**Issue by kriskowal** [Agoric/Agoric#9121]
## Describe the bug

Xsnap does not build in the https://github.com/agoric/documentation on agoric-sdk 4ebfb257fc26adf3688d87e9f474f5b7b81470f6.

## To Reproduce
1. Create a new pull request against the documentation repository with no changes.
CI fails under `yarn install`, unable to shell out to `make`.

## Expected behavior
No failures in CI

## Platform Environment
 - what version of the Agoric-SDK are you using? (run `@agoric/cosmic-swingset@0.41.3-1611-4ebfb257fc26adf3688d87e9f474f5b7b81470f6`)

**Comment by Chris-Hibbert** [comment]
It's also impacting `agoric-sdk/a3p-integration`, though it leaves me with a working system.

**Comment by kriskowal** [comment]
Reverted the offending change https://github.com/Agoric/agoric-sdk/pull/9122
