### ISSUE TITLE
Remove legacy query from Inter Protocol test documentation

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#9142]
## What is the Problem Being Solved?

See #9096 for `agoric-sdk/packages/inter-protocol/test/auction/README-bidding-cli.md`.

## Description of the Design

See parent issue.

## Security Considerations

N/A

## Scaling Considerations

N/A

## Test Plan

N/A

## Upgrade Considerations

See parent issue.

**Comment by ivanlei** [comment]
There is no curl command or query in this documentation that needs an update.
