### ISSUE TITLE
ensure the latest version of endo is added to upgrade 15 deployment branch

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#9150]
This task is to ensure the latest and greatest version of endo is fully compatible with the upgrade 15 development branch planned for launch.

**Comment by aj-agoric** [comment]
Open Questions for Endo - SDK sync alignment:

1. What is the latest and greatest Endo Version
@kriskowal  answer: "the latest version I shipped?"

2. what issues need to get into the upgrade 15
nothing currently outstanding that must get into 15. Confirm nothing in sdk relying on unreleased version

3. When those changes are released into endo branch
na

4. Have each of those been integrated into agoric SDK
na

Going Forward to track work in flight endo work thats needed for an upgrade. 

mirrored tracking ticket in agoric-sdk which is closed when an endo integration merge has landed where it is needed in agoric-sdk . Add "next-endo-sync"

**Comment by dckc** [comment]
a bit of motivation:

> I think I need to wait until I can depend on a more recent endo before proceeding farther. I need at least support for `M.raw()` in order to sidestep some of the exceptional cases.
 -- https://github.com/Agoric/dapp-agoric-basics/pull/29#discussion_r1540157070

**Comment by dckc** [comment]
@kriskowal this is what I get from `all-versions.sh`.

```
$ ../endo/scripts/all-versions.sh |grep endo
  "@endo/base64": "^1.0.3",
  "@endo/bundle-source": "^3.2.1",
  "@endo/captp": "^4.1.0",
  "@endo/check-bundle": "^1.0.5",
  "@endo/common": "^1.2.0",
  "@endo/compartment-mapper": "^1.1.3",
  "@endo/env-options": "^1.1.2",
  "@endo/errors": "^1.2.0",
  "@endo/eslint-plugin": "^2.1.1",
  "@endo/eventual-send": "^1.2.0",
  "@endo/exo": "^1.3.0",
  "@endo/far": "^1.1.0",
  "@endo/import-bundle": "^1.1.0",
  "@endo/init": "^1.1.0",
  "@endo/lockdown": "^1.0.5",
  "@endo/marshal": "^1.4.0",
  "@endo/nat": "^5.0.5",
  "@endo/netstring": "^1.0.5",
  "@endo/pass-style": "^1.3.0",
  "@endo/patterns": "^1.3.0",
  "@endo/promise-kit": "^1.1.0",
  "@endo/ses-ava": "^1.2.0",
  "@endo/stream": "^1.2.0",
  "@endo/stream-node": "^1.1.0",
  "@endo/zip": "^1.0.3",
```

**Comment by aj-agoric** [comment]
Closing as this is completed.
