### ISSUE TITLE
External-facing Interchain breaking changes resources

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#9161]
## What is the Problem Being Solved?

External users should receive warning of breaking changes associated with Interchain Stack upgrades.

It shouldn't be necessary to completely repeat all the issues, but we should announce the specific version numbers being changed, link to the Cosmos documents, and highlight the most major concerns.

## Description of the Design

A single wiki page containing breaking changes for all releases, for ease of maintenance and discoverability.

A note in the Interchain stack upgrade checklist to update it for each release.

## Security Considerations

N/A

## Scaling Considerations

N/A

## Test Plan

N/A

## Upgrade Considerations

N/A

**Comment by ivanlei** [comment]
This issue doesn't capture specific work. The release runbooks deal with breaking changes.
