### ISSUE TITLE
port allocation - centralized method for handing out ports to ensure that callers cannot squat on well-known ports

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#9165]
port allocation - centralized method for handing out ports to ensure that the same ports aren’t reused.  Right now Network Vat allows you to request any port.

**Comment by michaelfig** [comment]
First, I'd suggest creating a PortAllocator object with `vat-network.js`s `protocol` in its state, and methods like:

```js
{
  allocateIBCPort() {
    const { state } = this;
    // Allocate an IBC port with a unique generated name.
    return E(state.protocol).bind(`/ibc-port/`);
  },
  allocateICAControllerPort() {
    const { state } = this;
    state.lastICAPortNum += 1n;
    return E(state.protocol).bind(`/ibc-port/icacontroller-${state.lastICAPortNum}`);
  },
}
```

Then, I'd suggest rewriting `network-proposal.js#setupNetworkProtocols#makePorts` as follows:
```js
  { consume: { portAllocator }} // get the allocator object from the promise space
  //...
  const makePorts = async () => {
    // Bind to some fresh ports (either unspecified name or `icacontroller-*`)
    // on the IBC implementation and provide them for the user to have.
    const ibcportP = [];
    for (let i = 0; i < NUM_IBC_PORTS_PER_CLIENT; i += 1) {
      if (i === NUM_IBC_PORTS_PER_CLIENT - 1) {
        const portP = when(E(portAllocator).allocateICAControllerPort());
        ibcportP.push(portP);
      } else {
        const portP = when(E(portAllocator).allocateIBCPort());
        ibcportP.push(portP);
      }
    }
    return Promise.all(ibcportP);
  };
```

Exercise for the reader: make the PortAllocator available from `vat-network.js`'s root object via a `getPortAllocator()` function, taking a hint from the use of `zone.makeOnce` in that file.  Then, in `network-proposal.js` where the network vat is built, put the port allocator in the promise space.

**Comment by aj-agoric** [comment]
marking "in progress" per message with ikenna

**Comment by raphdev** [comment]
> Right now Network Vat allows you to request any port.

What's the consequence of this behavior? If I know what port a vat is using, could I request it and be able to listen on the same port?

**Comment by michaelfig** [comment]
> > Right now Network Vat allows you to request any port.
> 
> What's the consequence of this behavior?

Port names have special meanings to some IBC protocols or clients.  The Network Vat does not restrict the name of what you can allocate/bind.  That allows "squatters" to allocate vanity or conventional port names which is too powerful a capability to have for most clients.  An attenuated central port allocator can allow port names to be allocated without permitting squatters.

> If I know what port a vat is using, could I request it and be able to listen on the same port?

No, it's only allocated/bound once (until the original allocator revokes the port).  If you request a port name that is currently bound, you just get rejected.

**Comment by 0xpatrickdev** [comment]
>>What's the consequence of this behavior?

>Port names have special meanings to some IBC protocols or clients.

In the case of ICS-27, interchain accounts, the same port identifier can be reused to recover an account:

>In the event of a channel closing, the **active channel may be replaced by starting a new channel handshake with the same port identifiers on the same underlying connection of the original active channel**. ICS-27 channels can only be closed in the event of a timeout (if the implementation uses ordered channels) or in the unlikely event of a light client attack. Controller chains must retain the ability to open new ICS-27 channels and reset the active channel for a particular portID (containing {owner-account-address}) and connectionID pair.

>The controller and host chains must verify that any new channel maintains the same metadata as the previous active channel to ensure that the parameters of the interchain account remain the same even after replacing the active channel. The Address of the metadata should not be verified since it is expected to be empty at the INIT stage, and the host chain will regenerate the exact same address on TRY, because it is **expected to generate the interchain account address deterministically from the controller portID and connectionID (both of which must remain the same)**.

https://github.com/cosmos/ibc/blob/33d936aeecd649f25d4e357c942fcb5e4dec96e3/spec/app/ics-027-interchain-accounts/README.md#:~:text=In%20the%20event,remain%20the%20same).
