### ISSUE TITLE
adopt bundler moduleResolution in tsconfig

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9184]
## What is the Problem Being Solved?

The Endo bundler uses a modern resolver that understand package "exports" map and disallows path-based imports like `/dist`.

Typescript also does in the Node16/NodeNext mode, but we use the default, Node10.

## Description of the Design

Use the "bundler" option, which has the features of Node16/NodeNext but doesn't force us yet to use file extensions:
> 'bundler' for use with bundlers. Like node16 and nodenext, this mode supports package.json "imports" and "exports", but unlike the Node.js resolution modes, bundler never requires file extensions on relative paths in imports.

**Comment by mhofman** [comment]
What would be the cost of switching to extensions everywhere? Isn't that our preferred styles anyway? If so, is there a remaining difference between bundler and nodenext?

**Comment by turadg** [comment]
> What would be the cost of switching to extensions everywhere? Isn't that our preferred styles anyway? If so, is there a remaining difference between bundler and nodenext?

When I change `bundler` to `NodeNext` there are over 2000 errors. Only a handful point to file extensions as the problem. They may all be fixed by changing file extensions but I can't tell offhand whether that's true or how many.

> Isn't that our preferred styles anyway?

Yes. But it's not the status quo and it's not the scope of this issue to solve. Getting onto `bundler` solves an immediate problem. And if we later decide to adopt `NodeNext` the effort will be much less than if we hadn't taken this step.
