### ISSUE TITLE
orchestration - ICA Controller - Account - Close Connection Lifecycle

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/Agoric#9192]
In the course of #9114, we realized we need to give more thought to Closing accounts.

- Considerations
  - should we revoke ports?
  - should we attempt to retrieve assets before closing connections?
  - what contract state / storage should be cleaned up?

https://github.com/Agoric/agoric-sdk/pull/9114/files#r1550578668

**Comment by 0xpatrickdev** [comment]
Note: it does not seem that [localchain.js](https://github.com/Agoric/agoric-sdk/blob/b5cf8bd51585df36a72b65d7a1d66babd358b316/packages/vats/src/localchain.js#L67) has an equivalent concept of closing currently

**Comment by 0xpatrickdev** [comment]
Also to consider: connections can be closed from underneath us in some error cases (i think ordered channels are more susceptible to closing than unordered channels). In the `onClose` handler, we might consider adding logic that attempts to reinitialize the channel, via a new identifier (iow, recover the ICA account).

**Comment by 0xpatrickdev** [comment]
Something tangential to consider: localchain.js / vat-localchain does not have a concept of closing an account. Should it?

**Comment by LuqiPan** [comment]
Re-assigning to @0xpatrickdev for design

**Comment by 0xpatrickdev** [comment]
I worked with @michaelfig and this how we plan to handle the questions:

> should we revoke ports?

- No, the cost for keeping them around doesn't seem high. Also, a governance action to recover an accidentally revoked port (that still has assets) seems costly.
- The Port is held in the `IcaAccountKit` after a holder calls `.close()` and can be later used to `.reopen()` the connection. 

> should we attempt to retrieve assets before closing connections?

- No, there are too many considerations here. `IcaAccountKit` knows nothing about the assets held on a remote chain. It also might hold non ICS-20 assets that aren't easily retrievable back to the controller chain.
- The Port preservation and `.reopen()` method mentioned above shouldn't make asset recovery a concern.

> what contract state / storage should be cleaned up?

- We clean up `Connection`, `RemoteIbcAddress`, and `LocalIbcAddress`. When a connection is re-established with `.reopen()`, there will be a new Connection object and new `RemoteIbcAddress` and `LocalIbcAddress` values (by way of a new channelID). 
- The `ChainAddress` object and `Port` remotable are preserved in state.
- `IcaAccountKit` doesn't currently write to vstorage, so no cleanup is done there.
- `ComosOrchestrationAccount` does not do any cleanup yet. I think we should create a new ticket to track cleanup there.
  - (Tangentially - LocalChainAccount has no concept of .close())

**Comment by 0xpatrickdev** [comment]
> - IcaAccountKit doesn't currently write to vstorage, so no cleanup is done there.
> - ComosOrchestrationAccount does not do any cleanup yet. I think we should create a new ticket to track cleanup there.

At least the first item here is dependent on https://github.com/Agoric/agoric-sdk/issues/9066. I think #9587 will mark this closed if these items are tracked in a separate ticket (they seem out of scope to "ICA Controller", anyways, but this ticket was written some time ago) cc @mitdralla @LuqiPan
