### ISSUE TITLE
codegen RPC clients

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9199]
## What is the Problem Being Solved?

For a few weeks we had RPC query clients using Telescope:

But the implementation broke using the library in vats, which is more urgent. So this ticket is for restoring that functionality.

## Description of the Design

Some options:
1. publish them as a separate package, versioned by agoric-upgrade-NN
2. rework Telescope to output two hierarchies with one that is safe for vats
3. rework Telescope to inject the dependencies instead of importing them (e.g. provide a generic query util, one of which works over HTTP and another that uses the local chain host)

**Comment by mhofman** [comment]
Dup of #9200

**Comment by turadg** [comment]
> Dup of #9200

Thanks. Chrome reported a network change during the POST and I resubmitted to not lose the content. Apparently the first POST succeeded
