### ISSUE TITLE
base a3p-integration on upgrade-14

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9206]
## What is the Problem Being Solved?

With https://github.com/Agoric/agoric-3-proposals/pull/141 a3p:latest now includes dev-upgrade-14 branch's upgrade handler. 

Current master doesn't work atop u14 so [its a3p-integration is set to base on `use-upgrade-13`](https://github.com/Agoric/agoric-sdk/pull/9112/commits/d484d361701da5f492aaeac86006efc008b6b812) 

## Description of the Design

Change `agoricSyntheticChain.fromTag` back to `'latest'`. Then get it green.

**Comment by aj-agoric** [comment]
[Original discussion](https://agoricopco.slack.com/archives/C06AWUYQPHS/p1712351284797479)
