### ISSUE TITLE
bidirectional lookup of denoms / brands for IBC

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9211]
## What is the Problem Being Solved?

https://github.com/Agoric/agoric-sdk/issues/8879 manages IBC paths but developers need a way to establish a correspondence between a denom and its issuing chain, and optionally an ERTP Brand.

## Description of the Design

- Treat channel info as immutable
- We provide a lookup service to get the info for a particular chain
- The set is append-only (the value for a particular chain name is immutable)
- The right to append is held only by BLD Stakers
- If a developer needs the info before it’s on-chain (between staker votes) they look it up through some other trusted source (e.g. Google for the chain’s docs)

With the above requirements we landed on each contract having a ChainHub. That can load from agoricNames and/or be filled manually by contract code.

## Test Plan

`getBrandInfo` works with ChainHub (done in #9754)

All exos look up denoms using ChainHub

Not in scope: filling ChainHub using agoricNames, which is
-  #9752

## Upgrade Considerations
not yet deployed but needs an upgrade test

**Comment by dckc** [comment]
some recent relevant work: https://github.com/agoric-labs/ag-power-tools/pull/8#issuecomment-2050161852

see also:

 - https://github.com/DCFoundation/cosmos-proposal-builder/issues/38

**Comment by dckc** [comment]
btw "petname" is a bit of a stretch here. It suggests that each person can have their own name for the tokens and that the names can be changed. I suppose those are true from the perspective of the BLD stakers as one aggregate "person", but... it's a stretch.

**Comment by dckc** [comment]
"well known name handling" might be better

**Comment by turadg** [comment]
Reopening until [the "#9211" comments](https://github.com/search?q=repo%3AAgoric%2Fagoric-sdk%20%239211&type=code) (8 files) are resolved.
