### ISSUE TITLE
ChainAccount helpers for operations supported by the chain - orchestration

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9212]
## What is the Problem Being Solved?

Different chains support different functionality. The API should provide the appropriate methods that function on the particular chain.

## Description of the Design

Probably using or adapting Telescope. It may already have the chain info to generate the proper methods

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/10016
```

**Comment by dtribble** [comment]
Our canonical example: Stride chain should have a `liquidStake` ICA operation that's not part of the general chain API

**Comment by turadg** [comment]
Closing with #10017 deferred
