### ISSUE TITLE
EC proposing/voting txn failing due to account sequence mismatch

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#9225]
## Describe the bug

Nearly all of the EC members are running into account sequence mismatch errors when attempting to propose or vote on proposals. 4/6 have run into this in the last 24 hours. Some have succeeded after much refreshing and retrying others have not. It is currently impacting their ability to govern Inter protocol effectively as they are unable or severely delayed in making and voting through proposals.

Broadcasting transaction failed with code 32 (codespace: sdk). Log: account sequence mismatch, expected 101, got 102: incorrect account sequence

## To Reproduce
1. Be EC member
2. Attempt to propose
3. See error

1. Be EC member
2. Attempt to vote on a proposal
5. See error

## Expected behavior
Proposal or vote should succeed

**Comment by mhofman** [comment]
What RPC node do they use?

**Comment by rowgraus** [comment]
Note:  I had one member make a different Cosmos-level transaction (Transfer IST) and JS level (PSM trade).  

The Cosmos level transaction succeeded
The PSM trade failed with sequence mismatch error

@mhofman the econ-gov dapp doesn't let users view or manually change the RPC node so I am not sure.

The PSM seems to default to https://main.rpc.agoric.net:443

**Comment by mhofman** [comment]
My recollection is that this was addressed by making sure the RPC nodes used by the econ UI were healthy. Of course we still need to address how to proactively remove unhealthy RPC nodes, but that's a separate issue.
