### ISSUE TITLE
`#endo-branch:` mechanism incomplete or broken

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#9232]
At https://github.com/Agoric/agoric-sdk/actions/runs/8680969004/job/23802757406?pr=6432#step:6:173 we see

```
Error#1: 'mustCompress' is not exported by ../../node_modules/@endo/patterns/index.js, imported by ../swingset-liveslots/src/virtualObjectManager.js
```

from https://github.com/Agoric/agoric-sdk/pull/6432 , whose PR comment starts with 
```
#endo-branch: markm-pattern-based-compression-2
```

That is the branch of https://github.com/endojs/endo/pull/1584 , which does export `mustCompress` at

https://github.com/endojs/endo/blob/4ce652632397059410befb4f637c94cd83609198/packages/patterns/index.js#L76

So apparently, the @endo/patterns imported by liveslots is not the @ndo/patterns from that fork. 

@michaelfig , ok to assign to you?

**Comment by michaelfig** [comment]
> ok to assign to you?

Yes, definitely!  For prioritisation, could you let me know which upgrade this is blocking?  I'm mostly working on things that are blocking `agoric-upgrade-16` right now.

**Comment by michaelfig** [comment]
Turned out to be much easier to diagnose than I expected.  See #9237.

**Comment by mhofman** [comment]
FWIW, the `endo-branch` mechanism is also incomplete as it doesn't effect docker based tests: https://github.com/Agoric/agoric-sdk/issues/8938
