### ISSUE TITLE
ZCF in upgrade-14 cannot restart a contract due to await in 1st crank

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#9246]
## Describe the bug

When trying to upgrade walletFactory, I get:

```
agd-1  | 2024-04-16T18:46:18.574Z SwingSet: xsnap: v43: error during vat dispatch() of startVat,[object Object] buildRootObject unresolved
agd-1  | 2024-04-16T18:46:18.592Z SwingSet: kernel: WARNING: vat v43 failed to upgrade from incarnation 2 (startVat)
```

## To Reproduce
1. start an a3p chain upgraded to agoric-upgrade-14
2. make a core proposal using `upgradeContract`
3. see `buildRootObject unresolved`

## Expected behavior

contract should upgrade

## Platform Environment
 - what OS are you using? what version of Node.js?

linux, node 18.x

 - is there anything special/unusual about your platform?

I'm deploying to an upgrade-14 chain ( d69c011 )

 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

2024-04-16 17:42 26505ba29 fixup! chore(smart-wallet): upgrade; tryExit on selected offers

branch from master at:

2024-04-14 23:34 e2e36cc1e docs(eventual-send,pass-style): Add missing env var explanations (#9233)

## Additional context

This is fixed in #8911 (72c75740aff920) but that fix didn't make it into the upgrade-14 release branch.

```diff
diff --git a/packages/zoe/src/contractFacet/zcfZygote.js b/packages/zoe/src/contractFacet/zcfZygote.js
index ed15761a015..b4f3d1643e6 100644
--- a/packages/zoe/src/contractFacet/zcfZygote.js
+++ b/packages/zoe/src/contractFacet/zcfZygote.js
@@ -469,8 +469,12 @@ export const makeZCFZygote = async (
 
       await null;
       if (!zcfBaggage.has('repairedContractCompletionWatcher')) {
-        await E(zoeInstanceAdmin).repairContractCompletionWatcher();
-        console.log(`Repaired contract completion watcher`);
+        // We don't wait because it's a cross-vat call (to Zoe) that can't be
+        // completed during this vat's start-up
+        E(zoeInstanceAdmin)
+          .repairContractCompletionWatcher()
+          .catch(() => {});
+
         zcfBaggage.init('repairedContractCompletionWatcher', true);
       }
```

**Comment by dckc** [comment]
@mhofman plans to make a PR

**Comment by ivanlei** [comment]
Closed by https://github.com/Agoric/agoric-sdk/pull/9254
