### ISSUE TITLE
Need a better name than `vowishKey`

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#9302]
See https://github.com/Agoric/agoric-sdk/pull/9097#pullrequestreview-2021694008

`vowishKey` will be added by #9097 (asyncFlow) to the vow package. I'm adding the functionality with @michaelfig 's blessing. But the name is rather horrible and must be changed. All clear names I came up with were too long. Suggestions appreciated.

Opening this as a separate issue so this naming question does not block #9097

**Comment by erights** [comment]
@michaelfig , since this will be part of the vow package, I co-assigned this to the two of us Note that it is also scheduled as Backlog, but would be nice to fix before it becomes entrenched.

I wish I had a good suggestion.

**Comment by michaelfig** [comment]
`getKeyFromVow` ?
`getVowKey` ?

**Comment by erights** [comment]
But it is identity on non vows.

**Comment by michaelfig** [comment]
Maybe it should not be an identity, instead return `undefined` if not a
vow, and have the caller decide the logic?

-- 
Michael FIG
Software Engineer, Agoric

**Comment by erights** [comment]
But then I would still need to name the abstraction that builds the current
functionality on the narrower one

  Cheers,
  --MarkM

**Comment by michaelfig** [comment]
`getScalarKey`?
`scalarKeyFrom`?

-- 
Michael FIG
Software Engineer, Agoric

**Comment by erights** [comment]
Thanks, giving it a coercer name was the prod I needed. After looking at all the uses, at https://github.com/Agoric/agoric-sdk/pull/9097/commits/1425fb9c6ba3744db680bb07d9a347f1efa2cefe I changed the type and description and went with `toPassableCap`.
