### ISSUE TITLE
asyncFlow packaging should provide endowments, meta-operations

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#9304]
See #9097 

This does not affect the low level `asyncFlow` abstraction itself. But such conveniences must appear at the abstraction level immediately above it.

@mhofman , I'll leave this for you to describe, since you're already writing about this.

**Comment by erights** [comment]
For example, should add a meta operation for asking about the incarnation number of the next log state, that does not log the query, but would always give the same answer if asked at the same point. This would permit a successor to ask when its predecessor did not, and vice versa. (Suggested by @dtribble I think)

**Comment by mhofman** [comment]
This was essentially done in #9566

**Comment by mhofman** [comment]
Some tests may be missing, which is tracked by #9933

**Comment by mhofman** [comment]
Tracking meta operations at #10103

**Comment by mhofman** [comment]
Issue to review endowments: #10104
