### ISSUE TITLE
Investigate difference in Oracle price in vaults tab

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#9343]
Oracle price in Vaults -> summary table differs slightly from info.inter.trade. Why? Where is it getting the data from? It should probably be the latest published oracle price for that asset.

**Comment by toliaqat** [comment]
I have compared the Oracle Price data between old, new, and vstorage. And found that the new dashboard's prices are similar. Attaching the screenshot that shows all three places for comparison.

![Image](https://github.com/Agoric/agoric-sdk/assets/6778940/3e690bf8-08e1-44ce-b9be-eb4be3aed46d)
