### ISSUE TITLE
Add '/ limit' to PSM pairs under PSM tab

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#9344]
New dashboard is missing '/ limit'

New dashboard:

![Image](https://github.com/Agoric/agoric-sdk/assets/93355546/0f115bc1-e21d-4fcf-b4e4-971cfcaa899a)

Current dashboard:

![Image](https://github.com/Agoric/agoric-sdk/assets/93355546/d531ca34-442c-4198-9699-ce034fcd8ec3)

**Comment by toliaqat** [comment]
Fixed in https://github.com/agoric-labs/agoric-inter-dashboard/pull/44
