### ISSUE TITLE
numActiveVaults not including vaults with zero IST debt

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#9463]
## Describe the bug
While investigating https://github.com/agoric-labs/agoric-inter-dashboard/issues/69 @toliaqat noticed that app.inter.trade 'Total # of Active Vaults' metric was returning fewer known open vaults. 

This metric looks to be returning the sum of NumActiveVaults across all vault managers and doesn't include ~13 (as at 6/5/2024) open vaults that have no IST debt against them but still have some collateral locked up.

By definition - these should be treated as open/active vaults not excluded, even if there is no IST debt against these accounts.

## To Reproduce
1. Calculate sum of numActiveVaults
2. compare to info.inter.trade dashboard table of vaults which does include zero debt vaults (sort by 0% collateralization ratio)

## Expected behavior
By definition - these should be treated as open/active vaults not excluded, even if there is no IST debt against these accounts.

**Comment by Chris-Hibbert** [comment]
`numActiveVaults` is set from the cardinality of `prioritizedVaults`, which only includes vaults that can accrue interest or be liquidated. Those are currently all the vaults that the VaultManager actually tracks. We'd have to add code to count the vaults with no debt.

**Comment by otoole-brendan** [comment]
Closing this in favor of updating what we show in app.inter.trade rather than upgrading VaultFactory over this
