### ISSUE TITLE
MainNet proposals should dynamically provide oracle addresses

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#9571]
## Describe the bug

#9044 included a proposal for upgrading price feeds, and included fallback oracle addresses. 

While putting together the release @mhofman commented
> I'm not sure how the proposal should figure out the current oracle addresses TBH, but I don't think we should bake any address in the image

## Expected behavior

The proposal in #9044 tries to look up `GOV1`, `GOV2`, and `GOV3` from **`process.env`**, before falling back to baked-in addresses. If we need to remove the hard-coded addresses, we need to ensure that test nets and a3p will always have the GOV addresses defined.

**Comment by mhofman** [comment]
To clarify, the 2 requirements are:
- do not rely on environment variables.  if used environment variables should only be used for some kind of override mechanism
- have a single image be compatible with all existing networks that already have oracles set, such as mainnet, Devnet etc. these networks cannot expect validators to set environment variables for correctness.
