### ISSUE TITLE
test support: ibc bridge mocks for @agoric/orchestration

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/Agoric#9572]
## What is the Problem Being Solved?

In unit testing flows for `@agoric/orchestration`, the `EchoConectionKit` is used to mock network / ibc:

https://github.com/Agoric/agoric-sdk/blob/bc3bc6b6cf9f0a7017f5b17adf5e57c300f7e6fe/packages/orchestration/test/supports.ts#L107
https://github.com/Agoric/agoric-sdk/blob/ad29545174c43d481f1be7dbc6ce848c893a89e7/packages/orchestration/test/network-fakes.ts#L98-L108

This limits our ability to fully test contracts - we need to be able to simulate responses from a remote IBC Connection to see how a contract handles them.

In boot tests, we mocked some `Bridge.DIBC` events using responses for sim chains:
https://github.com/Agoric/agoric-sdk/blob/42b2e7ed09b2022a59bfddef7fda572e00fca5f5/packages/boot/tools/supports.ts#L358-L406

## Description of the Design

Provide a similar entry point for IBC mocks in @agoric/orchestration unit testing.

**Comment by LuqiPan** [comment]
> This limits our ability to fully test contracts - we need to be able to simulate responses from a remote IBC Connection to see how a contract handles them.

What kinds of IBC messages do we need to simulate responses for?

> In boot tests, we mocked some Bridge.DIBC events using responses for sim chains:

Could we reuse the code from boot test to simulate responses?
