### ISSUE TITLE
Make maxVatsOnline customizable to optimize resource usage

### ISSUE THREAD

**Issue by toliaqat** [Agoric/Agoric#9574]
## What is the Problem Being Solved?
Reduce resource usage in testnets and local chains by reducing the number of online vats.

## Description of the Design
SwingSet loads maxVatsOnline number of vats into memory at a time, "paging out" and "paging in" vats as needed, ensuring that at any time only maxVatsOnline vats are active. Currently, maxVatsOnline is hard-coded to 50, which might not be the best number for local chains.

The task is to add an environment variable that can make maxVatsOnline customizable by the node operators. 

## Security Considerations
Inconsistent maxVatsOnline by different validators in one chain might cause consensus failure (just a theory). We should make a note that mainnet validators should not be playing with this and only added for testnets and local test chains.

## Scaling Considerations
Reducing the number too low will negatively impact performance, potentially drastically, by causing vats to keep paging in and out.

## Test Plan
Add a test to verify that changing the parameter limits the number of loaded vats.
Ensure that if the variable is undefined, the default maximum number of vats is used.

**Comment by mhofman** [comment]
For scaling considerations: reducing the number too low will negatively impact performance, potentially drastically, by causing vats to keep paging in and out.
