### ISSUE TITLE
Upgrading scaled price authority causes vaults upgrade to not complete

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#9584]
## Describe the bug
The vaults upgrade is a 2 step process where first new price feeds and auction contracts are installed, then the vault factory is upgraded only after a price quote on a new feed was received.

For some reason upgrading the scaled price authority before vaults factory completes its upgrade ends up failing the vaults upgrade.

Furthermore integration tests of vaults upgrade did not fail when this happened.

## To Reproduce
run a3p tests on master

## Expected behavior
No error, and an integration test catching vaults upgrade failures

## Platform Environment
N/A

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/9866
```

**Comment by Chris-Hibbert** [comment]
#9911 decoupled upgrade of vaults and auctions from priceFeeds. Going forward, a priceFeed upgrade will be handled separately (#9928).
