### ISSUE TITLE
upgrade-16rc2 causing 'failed to load latest version'

### ISSUE THREAD

**Issue by toliaqat** [Agoric/Agoric#9682]
## Describe the bug
Upgrade-16-RC2 causes the node not to be able to start with the following error message.

```
failed to load latest version: failed to load latest version: failed to load store: initial version set to 6057125, but found earlier version 6047000
```

Ref: https://github.com/Agoric/agoric-sdk/releases/tag/agoric-upgrade-16-rc2

## To Reproduce
Upgrade the validator node using container tag: 46
Restart the node, and wait for it to generate blocks
Results in the node process exit with above error message

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by mhofman** [comment]
Fix for u16 release landed in #9683, will need to be posted to master, adapting the `isPrimaryUpgradeName` logic to support multiple primary names (a3p and basic)
