### ISSUE TITLE
Possible improvement in `vaultDirector`'s `allManagersDo()`

### ISSUE THREAD

**Issue by anilhelvaci** [Agoric/Agoric#9706]
## What is the Problem Being Solved?
In `vaultDirector`'s `allManagersDo` function, I believe there's an improvement can be made. 

https://github.com/Agoric/agoric-sdk/blob/17608dca6002fac10b4c07de4684fb18a8ef5be5/packages/inter-protocol/src/vaultFactory/vaultDirector.js#L267-L272

Imagine there are three vault managers; namely A, B and C. Suppose that manager B's price oracle is broken and didn't publish any prices. In such a case, manager C will not be able to lock its prices because(assuming manager are stored in the order [A, B, C])  `allManagersDo` sequentially invokes `vm.lockOraclePrices()` meaning, after `vmA.lockOraclePrices()` is successful(does not throw unhandled errors) `vmB.lockOraclePrices()` executes and so on. 

https://github.com/Agoric/agoric-sdk/blob/17608dca6002fac10b4c07de4684fb18a8ef5be5/packages/inter-protocol/src/vaultFactory/vaultDirector.js#L447-L451

cc @Chris-Hibbert @otoole-brendan 

## Description of the Design
I suggest using promises to invoke `fn()` like;

```js
  const allManagersDo = fn => {
    for (const managerIndex of collateralManagers.values()) {
      const vm = vaultManagers.get(managerIndex).self;
      Promise.resolve(vm).then(vm => fn(vm)).catch(e => trace(\'ERROR: allManagersDo\', e));
    }
  };
```

## Security Considerations
None.

## Scaling Considerations
None.

## Test Plan
TBD

## Upgrade Considerations
Don't see any reason why this doesn't go in the next vault factory upgrade given proper `a3p` test exists.

**Comment by Chris-Hibbert** [comment]
Thanks for the suggestion. I'll add it to the list of vault-related things I'm working on for the next upgrade.

Note to self: add a test that makes the problem evident before fixing it.
