### ISSUE TITLE
audit smart-wallet for any `watchPromise` during contract start

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#9738]
## What is the Problem Being Solved?

#9732 documents a bug of liveslots preventing upgrade of vats that call `wtachPromise` during start. smart-wallet is the current primary user of `watchPromise` and will be upgraded with vow support (#9308) before we can deploy a fix to liveslots. We need to make sure that no explicit `watchPromise` or implicit through VowUtils `watch` or `when` get called during the smart wallet start. There is an a3p-ntegration test upgrading the smart wallet, but if the watch is conditional on some state that is not present in a3p, we might not be triggering the case.

## Description of the Design

Audit smart wallet code to verify that no watch can be called during contract start

**Comment by Chris-Hibbert** [comment]
These are all `watchers` that are created in response to user actions (offers).  I don't see how they could be called during contract start.

**Comment by mhofman** [comment]
Feel free to close when you're confident there are no path
