### ISSUE TITLE
Error#1: The module '/data/.agoric/agoric-sdk/node_modules/better-sqlite3/build/Release/better_sqlite3.node'

### ISSUE THREAD

**Issue by jack-dot-wu** [Agoric/Agoric#9764]
I upgrade my node v15 to v16, but my node can't run,and the log show:Loading slog sender modules: @agoric/telemetry/src/flight-recorder.js
2024-07-24T06:29:53.630Z launch-chain: Launching SwingSet kernel
portHandler threw (Error#1)
Error#1: The module '/data/.agoric/agoric-sdk/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
  at makeSwingStore (file:///data/.agoric/agoric-sdk/packages/swing-store/src/swingStore.js:192:12)
  at openSwingStore (file:///data/.agoric/agoric-sdk/packages/swing-store/src/swingStore.js:647:10)
  at launch (file:///data/.agoric/agoric-sdk/packages/cosmic-swingset/src/launch-chain.js:351:42)
  at launchAndInitializeSwingSet (file:///data/.agoric/agoric-sdk/packages/cosmic-swingset/src/chain-main.js:466:21)
  at async toSwingSet (file:///data/.agoric/agoric-sdk/packages/cosmic-swingset/src/chain-main.js:676:24)
panic: cannot initialize Controller: Error: The module '/data/.agoric/agoric-sdk/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
I use the cmd 'npm rebuild' but it doesn't work. My node version is 18.20.4 , npm is 10.7.0 and system is ubuntu20.04.

**Comment by mhofman** [comment]
Some validators seem to have experienced this problem when the Node.js version available in the shell used to build agoric-sdk is different than in the service environment used to run the daemon. This can occur when using `nvm` during the build process but having a different node version installed globally. `nvm` is a tool that modified the current shell's `PATH` to manage the Node.js version available.

Some solutions were suggested in [Discord](https://discord.com/channels/585576150827532298/1004795902868852817) by validators, including using `nvm` in the service scripts, create a symlink to the NVM managed Node binary, or avoid using `nvm` completely and instead install Node.js globally.

**Comment by mhofman** [comment]
Closing in favor of https://github.com/Agoric/agoric-sdk/issues/9769
