### ISSUE TITLE
async flow membrane doesn't preserve Brand identity

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#9780]
## Describe the bug

When a host function returns a Brand, the guest sees a Brand guest wrapper that isn't useful for brand identity comparison.
Issuers likewise, presumably.

## To Reproduce

1. Check out the `dc-brand-info` branch - currently 8c772e6eb
2. `cd agoric-sdk/packages/orchestration`
3. `yarn test test/facade.test.ts -m 'asset / denom info'`
4. test fails due to difference between brand and brand guest wrapper and

```
 asset / denom info
  test/facade.test.ts:196

  -   brand: Object @Alleged: Token1 brand guest wrapper { ...  },
  +   brand: Object @Alleged: Token1 brand {},

  1 test failed
```

## Expected behavior

Brand returned in `orch.getBrandInfo()` can be compared by identity as usual.

## Additional context

#9754, #9211

**Comment by mhofman** [comment]
This is "working as intended". The test above attempts to compare a value inside the orchestrated function with a value captured in the context outside of it.

**Comment by dckc** [comment]
So the problem here was flows that closed over the brand. Following the norms for flows (#9692, #9693) means passing the brand in as an endowment, at which point the identity comparison works.
