### ISSUE TITLE
vat-environment `passStyleOf` cache holds strong references to objects with vrefs

### ISSUE THREAD

**Issue by gibson042** [Agoric/Agoric#9781]
## What is the Problem Being Solved?

Importing `passStyleOf` from endo results in the function being constructed on top of the virtual-object-aware WeakMap provided by liveslots, which holds strong references to objects with vrefs for purposes of hiding GC events. But this means that it is not appropriate for use as the `passStyleOf` cache, which sees all such objects that pass into or out of the vat.

## Description of the Design

We can instead let liveslots provide `passStyleOf` against the real WeakMap in such a way that the vat-environment import uses that endowment rather than rebuilding on top of the virtualized WeakMap. This is already in progress with coordination on the endo side.

## Security Considerations

It is important to continue protecting the real WeakMap—wrappers such as `passStyleOf` are acceptable only to the extent that they do not expose GC-sensing powers, and as such must be considered on a case-by-case basis.

## Scaling Considerations

This should significantly reduce RAM consumption by vats, dramatically so in the case of those that send and/or receive lots of Remotable-bearing messages (such as the board vat).

## Test Plan

We'll definitely be measuring the approach, with as close an approximation as possible to the real vat environment.

## Upgrade Considerations

Upgrade will be required to take advantage of the new endo and liveslots code.

**Comment by mhofman** [comment]
Correction: the virtual aware weak collections provided by liveslots do NOT hold any references strongly on the key side, whether that's the virtual objects reference, or the "physical" representative. Instead it uses a Map keyed by the vref string, and some registrations to indicate these vrefs have a recognizer. Of course that could cause some references to be held strongly if cycles involving the value part of these weak collections were involved, but that's not the case for `passStyle` ones.
