### ISSUE TITLE
Create a core-eval runbook for vat-orchestration

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/Agoric#9843]
## What is the Problem Being Solved?

In preparation for the vat-orchestration core-eval, we would like to create a runbook for it

## Description of the Design

Ideally this runbook could be re-usable for future core-evals but that's not necessary

**Comment by dckc** [comment]
I shared a draft with many open comments for review. In particular, I asked @LuqiPan to assign roles.

**Comment by dckc** [comment]
obsolete in favor of plans for a chain-halting upgrade, since golang changes are required
