### ISSUE TITLE
Possible metrics bug in Vaults

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#9854]
## Describe the bug

The VaultDirector [writes `sampleMetrics`](https://github.com/Agoric/agoric-sdk/blob/e1baf4e7e8efaab527d7eadf7305281dac8656c9/packages/inter-protocol/src/vaultFactory/vaultDirector.js#L159).

```
  /** @returns {MetricsNotification} */
  const sampleMetrics = () => {
    return harden({
      collaterals: Array.from(collateralManagers.keys()),
      rewardPoolAllocation: rewardPoolSeat.getCurrentAllocation(),
    });
  };
```
On every update it writes out the brands which are keys for collaterals rather than current total for that debt. Is that a bug?

## Screenshots

![vaultsMetrics](https://github.com/user-attachments/assets/d75428e8-e2e6-4fbb-8923-e2ca5bb6fccc)

**Comment by Chris-Hibbert** [comment]
It is recording the contents of the `rewardPoolSeat`. Other assets are reported by the Reserve.

**Comment by dckc** [comment]
the screenshot is consistent with [docs for published.vaultFactory](https://github.com/Agoric/agoric-sdk/blob/agoric-upgrade-13/packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.md):

```
    'published.vaultFactory.metrics',
    {
      collaterals: [
        Object @Alleged: aEth brand {},
      ],
      rewardPoolAllocation: {
        Minted: {
          brand: Object @Alleged: IST brand {},
          value: 151n,
        },
      },
    },
```

**Comment by Chris-Hibbert** [comment]
This data is redundant with the details written by each manager, but the managers seem to be providing all the information that might be needed. The `totalMinted` that is written to the same record is probably separately useful.  Until someone starts complaining about the space taken up, this isn't causing any problems, and it's not an indication that we aren't recording somethig crucial. 

Closing...
