### ISSUE TITLE
Set up mainfork environment with U16 and Oracles

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#9866]
## What is the Problem Being Solved?

In order to ensure that the coreEval that upgrades vaults, auctions, and priceFeeds coordinates correctly with the third-party oracles, we need a realistic test environment to work in.

## Description of the Design

The proposal is to create a mainFork instance (updated to upgrade 16, and set up a variation of the oracle scripts that will allow us to control the price feeds and observe the coordination between the oracles middleware and the upgraded priceFeeds.

SimplyStaking has provided instructions for setting up an oracle, but we'll need to build a test fixture that allows us to programmatically (or via a cyclic script) control the price feed. The usual path is `Middleware -> CL node -> Adapter -> CL Node -> Middleware -> Chain`. We want to test how `CL Node -> Middleware -> Chain` acts during upgrade, so we probably want to replace the `adapter` so we're not tied to Simply's oracle network. We may want to induce price drops to cause liquidations, so we need control of the price sources.

## Security Considerations

It's a test environment, so it doesn't directly impact the chain.

## Scaling Considerations

None

## Test Plan

Unneeded.

## Upgrade Considerations

Will be used for testing upgrade, but doesn't itself need to be upgradeable.

**Comment by LuqiPan** [comment]
We're gonna conduct this test on devnet instead of on mainfork

**Comment by Chris-Hibbert** [comment]
superseded by #9886
