### ISSUE TITLE
Use dapp-orchestration-basics to qualify vat-orchestration release

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/Agoric#9879]
## What is the Problem Being Solved?

In order to qualify the vat-orchestration core-eval release, we would need to run dapp-orchestration-basics on top of vat-orchestration core-eval using starship

```[tasklist]
### Dependencies
- [ ] https://github.com/Agoric/dapp-orchestration-basics/issues/12
- [ ] https://github.com/Agoric/dapp-orchestration-basics/pull/17
- [ ] https://github.com/Agoric/dapp-orchestration-basics/pull/18
- [ ] reconcile hard-coded account addresses
```

## Description of the Design

We would like to use dapp-orchestration-basics to exercise ICA and ICQ functionalities in vat-orchestration to qualify vat-orchestration core-eval release

## Test Plan

This ticket includes the work to test and qualify vat-orchestration core-eval release

**Comment by dckc** [comment]
@LuqiPan are relayers and other chains in scope here? dapp-orchestration-basics can't really do its thing (e.g. create an ICA) without relayers and all that, so I would assume so, but better to be explicit.

**Comment by LuqiPan** [comment]
I've updated the PR description to (hopefully) reflect the goal and details better

**Comment by dckc** [comment]
@0xpatrickdev and co noticed that the gentx in starship means that the environment doesn't include the a3p history. In discussion with @LuqiPan and @turadg , we confirmed that this is consistent with the plans we made Aug 14 (see change of title to take out "a3p").

**Comment by turadg** [comment]
This was done
