### ISSUE TITLE
Orchestration contract dependencies make them too large for Mainnet

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9900]
## What is the Problem Being Solved?

Bundles of contracts using Orchestration tend to be over 500KB, the limit for deploying to Mainnet. E.g. https://github.com/Agoric/dapp-orchestration-basics/pull/17/files#diff-1033217b1ee0740bea6f7c4bf49634318af4e0b4420a6048f55a686f3d5cfee5R56

`@agoric/cosmic-proto` is meant to be used in vats, UIs and contracts. Contracts have strict size limits to fit onto Mainnet and some of the codegen files in `@agoric/cosmic-proto` are huge.

When importing a module, the caller should only need to import (and bundle) what will be used. But right now importing the package main or `helpers` module will pull in `abci/types.js` which is over 100KB.

## Reduce overall weight of deps

Dupes should be prevented. Egregious export graphs should be trimmed but we shouldn't go down a rabbit hole optimizing these.

https://github.com/Agoric/agoric-sdk/issues/8621 is also a factor but easily mitigated by deduping node_modules (with Yarn _resolutions_)

Stop export of cosmos-interchain-service from package main

Stop import of `abci/types.js` in `helpers` (by moving `toRequestQueryJson` into another module) 

https://github.com/Agoric/dapp-orchestration-basics/tree/ta/mainnet-size has some experiments 

# Strip comments during bundling

Next thing to try:

- https://github.com/endojs/endo/issues/2413

## Externalize deps (Import from env)

Next biggest lift:

- https://github.com/endojs/endo/issues/1625
- https://github.com/Agoric/agoric-sdk/issues/9517
- https://github.com/Agoric/agoric-sdk/issues/5096
- https://github.com/Agoric/agoric-sdk/issues/9522

### Import between bundles

Maybe never…

- https://github.com/Agoric/agoric-sdk/issues/9522

**Comment by erights** [comment]
See also https://github.com/endojs/endo/issues/2411

**Comment by kriskowal** [comment]
There might be a small win in reducing `compartment-mapper.json` a bit more https://github.com/endojs/endo/issues/2313

**Comment by kriskowal** [comment]
`bundle-source --elide-comments` is merged https://github.com/endojs/endo/pull/2420

**Comment by turadg** [comment]
[multichain-testing now has the same limit as in Mainnet](https://github.com/Agoric/agoric-sdk/pull/9997/files#diff-21d2a90cae3a5ef9365c4e3d54aea66fb89a10901d11601043597d09f04d6423) and it installs contracts like `sendAnywhere` that use `withOrchestration` so we have CI coverage now of orchestration contracts fitting on Mainnet.

If we hit hit up against it again we can re-open this issue and work down the list of optimizations.
