### ISSUE TITLE
NPM Registry Flake

### ISSUE THREAD

**Issue by rabi-siddique** [Agoric/Agoric#9909]
In CI, when running integration tests, the step that sets up a local NPM registry occasionally fails. This issue occurs during our integration tests, which utilize a matrix strategy to execute across `Yarn`, `npm`, and `npx`. Our packages are published using [`Verdaccio`](https://verdaccio.org/) with a `dist-tag` of `ci`. We use this `dist-tag` to set up `agoric-cli` with `npm`, `npx`, and `Yarn` before running the `yarn integration test` command.

The script that tends to fail, [`scripts/registry.sh`](https://github.com/Agoric/agoric-sdk/blob/bef1be9b4fd16286ae5ca59a7d8812a775f7c6fe/scripts/registry.sh), is mainly designed to set up and run a local npm registry using `Verdaccio`, configure `npm` and `Yarn` to use it. 

https://github.com/Agoric/agoric-sdk/actions/runs/10361707252/job/28682520908?pr=9253
https://github.com/Agoric/agoric-sdk/actions/runs/10361707252/job/28682521191?pr=9253

# Possible Solutions
To address this issue, we could consider the following options:

- **Run yarn cache clean before publishing a package.** 
This can help clear any potential cache issues that might be causing the failures. More details can be found [here](https://stackoverflow.com/questions/55323656/error-command-failed-with-exit-code-1-when-i-try-to-run-yarn).

- **Add a retry mechanism.**
Implementing a retry mechanism could help mitigate transient failures and is a relatively safe and easy-to-implement option.

- **Try bumping versions of Lerna.**
There have been discussions around similar issues with Lerna, and bumping the versions might resolve the problem. For more details, see the [Lerna GitHub issue](https://github.com/lerna/lerna/issues/3570).

Given that this issue occurs occasionally, I am currently opting for the retry mechanism because it seems like a safe bet.

**Comment by michaelfig** [comment]
Both cited failures were in `lerna publish`, which is already known to fail during publishing packages as described in `MAINTAINERS.md`:
```
Tue, 13 Aug 2024 00:57:32 GMT lerna ERR! E503 one of the uplinks is down, refuse to publish
Tue, 13 Aug 2024 00:57:32 GMT error Command failed with exit code 1.
```

These `lerna publish` E503's can be mitigated with a loop to retry just `lerna publish from-package`, with a limited timeout on the job's publish step.  That surgical approach is more desirable than retrying the step as a whole, since rerunning the complete `bg-publish` starts a fresh Verdaccio instance and throws away all the successfully built and published packages.

See the [patch below](https://github.com/Agoric/agoric-sdk/issues/9909#issuecomment-2297132449)

**Comment by michaelfig** [comment]
Here's a patch I tested to implement the `lerna publish from-package` loop:

```diff
diff --git a/scripts/registry.sh b/scripts/registry.sh
index 954da1e3f0..943f4462c4 100755
--- a/scripts/registry.sh
+++ b/scripts/registry.sh
@@ -75,12 +75,8 @@ publish() {
 
     # Publish the packages to our local service.
     # without concurrency until https://github.com/Agoric/agoric-sdk/issues/8091
-    yarn lerna publish --concurrency 1 prerelease --exact \
-      --dist-tag="$DISTTAG" --preid=dev \
-      --no-push --no-git-reset --no-git-tag-version --no-verify-access --yes
-
-    # Convention used in Endo
-    yarn lerna run clean:types
+    yarn lerna version --concurrency 1 prerelease --exact \
+      --preid=dev --no-push --no-git-tag-version --yes
 
     # Change any version prefices to an exact match, and merge our versions.
     VERSIONSHASH=$(jq --slurpfile versions <(popd > /dev/null && git cat-file blob "$VERSIONSHASH") \
@@ -91,6 +87,17 @@ publish() {
       | (popd > /dev/null && git hash-object -w --stdin))
 
     git commit -am "chore: update versions"
+
+    while ! yarn lerna publish from-package \
+      --dist-tag="$DISTTAG" --no-git-reset --no-verify-access --yes; do
+      echo 1>&2 "Retrying publish..."
+      sleep 5
+    done
+    git reset --hard HEAD
+
+    # Convention used in Endo
+    yarn lerna run clean:types
+
     git checkout "$prior"
     popd
   done
```

**Comment by rabi-siddique** [comment]
> Here's a patch I tested to implement the `lerna publish from-package` loop:
> 
> ```diff
> diff --git a/scripts/registry.sh b/scripts/registry.sh
> index 954da1e3f0..943f4462c4 100755
> --- a/scripts/registry.sh
> +++ b/scripts/registry.sh
> @@ -75,12 +75,8 @@ publish() {
>  
>      # Publish the packages to our local service.
>      # without concurrency until https://github.com/Agoric/agoric-sdk/issues/8091
> -    yarn lerna publish --concurrency 1 prerelease --exact \
> -      --dist-tag="$DISTTAG" --preid=dev \
> -      --no-push --no-git-reset --no-git-tag-version --no-verify-access --yes
> -
> -    # Convention used in Endo
> -    yarn lerna run clean:types
> +    yarn lerna version --concurrency 1 prerelease --exact \
> +      --preid=dev --no-push --no-git-tag-version --yes
>  
>      # Change any version prefices to an exact match, and merge our versions.
>      VERSIONSHASH=$(jq --slurpfile versions <(popd > /dev/null && git cat-file blob "$VERSIONSHASH") \
> @@ -91,6 +87,17 @@ publish() {
>        | (popd > /dev/null && git hash-object -w --stdin))
>  
>      git commit -am "chore: update versions"
> +
> +    while ! yarn lerna publish from-package \
> +      --dist-tag="$DISTTAG" --no-git-reset --no-verify-access --yes; do
> +      echo 1>&2 "Retrying publish..."
> +      sleep 5
> +    done
> +    git reset --hard HEAD
> +
> +    # Convention used in Endo
> +    yarn lerna run clean:types
> +
>      git checkout "$prior"
>      popd
>    done
> ```

Thank you for sharing this. I've tested and verified it on my end, and this patch resolves the issue. :)
