### ISSUE TITLE
passStyleOf endowment should be inescapable

### ISSUE THREAD

**Issue by gibson042** [Agoric/Agoric#9981]
## What is the Problem Being Solved?

#9874 updated liveslots to endow its child compartment global object with passStyleOf via a property keyed on a `@endo passStyleOf` symbol reserved this purpose, but @erights points out that ZCF probably uses a child compartment of its own, which should _also_ have the same endowment.

## Description of the Design

Updating packages/swingset-liveslots/src/liveslots.js to declare `[PassStyleOfEndowmentSymbol]: passStyleOf` in `inescapableGlobalProperties` rather than `vatGlobals` should ensure that all descendant compartments get the endowment and can import a passStyleOf that will use it rather than build on top of the virtual-object-aware WeakMap.

## Security Considerations

We already convinced ourselves that such an endowment is safe.

## Scaling Considerations

This will provide the same benefits to contracts that are already anticipated for non-contract vats such as Zoe.

## Test Plan

Performance measurement is highly desired if feasible.

## Upgrade Considerations

Contracts will not get the benefits until upgrade to a version whose bundle includes an endowment-aware passStyleOf, or restart with a bundle that already includes it.

**Comment by warner** [comment]
stealing this one, I've got a patch
